### ISSUE TITLE
Suggestion to add a PreserveReferencesHandling.Auto

### ISSUE THREAD

**Issue by TylerBrinkley** [JamesNK/Newtonsoft.Json#1000]
So far I've always avoided using `PreserveReferencesHandling` due to how verbose the json becomes with adding a `$id` property to all json objects when I might only use the feature once or twice in all of the json. Instead I'd prefer it if Json.NET would only output the `$id` property on json objects that actually use the feature. This could be specified with a `PreserveReferencesHandling.Auto` value similar to `TypeNameHandling.Auto`.

From my understanding, the only barrier to implementing this is that the object graph would need a first pass to identify objects that would use the feature as `JsonWriter` is a forward only writer. Would this ever be considered if the overall performance is not affected, perhaps by storing the results of the first pass into a struct object tree and then serializing that object tree on the second pass?

**Comment by JamesNK** [comment]
What you can do is load JSON into a JToken after serialization and remove all the $ids that don't have a $ref pointing to them. I gave the scriptcs team code that does this a couple of years ago.

**Comment by TylerBrinkley** [comment]
Thanks for the idea.
