### ISSUE TITLE
Unable to deserialize BSON when Array / List<> is root

### ISSUE THREAD

**Issue by jdluzen** [JamesNK/Newtonsoft.Json#1004]
On the latest Json.Net, 9.0.1. When I am deserializing an object whose root is a List<>, I get

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.Int32]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> 
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> 
> Path '0'.

Repro code:

```
using Newtonsoft.Json;
using Newtonsoft.Json.Bson;
using System.Collections.Generic;
using System.IO;

namespace BsonTest
{
    class Program
    {
        static byte[] ObjectToBson(object o)
        {
            using (MemoryStream ms = new MemoryStream())
            using (BsonWriter writer = new BsonWriter(ms))
            {
                JsonSerializer ser = new JsonSerializer();
                ser.Serialize(writer, o);
                return ms.ToArray();
            }
        }

        static T BsonToObject<T>(byte[] b)
        {
            MemoryStream ms = new MemoryStream(b);
            BsonReader reader = new BsonReader(ms);
            return new JsonSerializer().Deserialize<T>(reader);
        }

        static void Main(string[] args)
        {
            object o = new List<int> { 1, 2 };
            byte[] stuff = ObjectToBson(o);

            var list = BsonToObject<List<int>>(stuff);

        }
    }
}

```

**Comment by JamesNK** [comment]
http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Bson_BsonReader_ReadRootValueAsArray.htm

**Comment by jdluzen** [comment]
Ah thanks, will try right away. May I ask what the reasoning is for having a property like this?

**Comment by JamesNK** [comment]
It's a flaw in the BSON spec.
