### ISSUE TITLE
System.FormatException "Invalid length for a Base-64 char array or string." thrown when deserializing large string

### ISSUE THREAD

**Issue by christianhuening** [JamesNK/Newtonsoft.Json#1005]
Hi there, 
I am porting an application over to .net Core and switched over to Json.NET from BinaryFormatter for my serialization issues .
At one point some files have to be serialized, send over the wire and be deserialized again. The files are DLLs and not large in size (usually << 500 KB). The files are organized as a List of a custom "ModelFile" object, while the actual file content is represented as a byte[].
While for most of the files it works, I receive a System.FormatException stating: "Invalid length for a Base-64 char array or string." for one entry at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength).

My deserialization code is simple, works for all other use cases I have and looks as follows:
```c#
protected virtual IScsMessage DeserializeMessage(byte[] bytes) {
   var output = Encoding.UTF8.GetString(bytes);
   return = JsonConvert.DeserializeObject<IScsMessage>(output);
}
```
Serialization is done accordingly:
```c#
protected virtual byte[] SerializeMessage(IScsMessage message) {
      var json = JsonConvert.SerializeObject(message, new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All });
      return Encoding.UTF8.GetBytes(json);
}
```

If helpful I could also provide the JSON, generated by the serialiazer.

The TraceWriter shows this:

> [Couple of OK deserializations here]
> 2016-09-02T09:19:16.439 Info Started deserializing LCConnector.TransportTypes.ModelStructure.ModelFile. Path 'Parameters.$values[0]._root.Contents.$values[4].Content', line 53, position 26.
> 2016-09-02T09:19:16.441 Error Error deserializing LCConnector.TransportTypes.ModelStructure.ModelFile. Invalid length for a Base-64 char array or string. Path 'Parameters.$values[0]._root.Contents.$values[4].Content.$value', line 55, position 7581.
> 

Stacktrace:

`"  System.FormatException "Invalid length for a Base-64 char array or string." at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)\r\n   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)\r\n   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)\r\n   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsBytes()\r\n   at Newtonsoft.Json.Serialization.TraceJsonReader.ReadAsBytes()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at [My Code from hereon]`

**Comment by christianhuening** [comment]
Sorry, the error must reside somewhere else. Ruled out Json.NET as the source.

/Closed

**Comment by D03107995** [comment]
Hi Christian can you elaborate on what was the cause of this issue if Json.NET is not the source?

**Comment by christianhuening** [comment]
It was caused by a non thread-safe piece of the receiver code where on some occasions the multiple receiver threads could write into the same buffer. Was rather old code, replaced it with a newer implementation using SocketAsyncEventArgs and all is well now :)
