### ISSUE TITLE
How to change the quotation marks

### ISSUE THREAD

**Issue by ropean** [JamesNK/Newtonsoft.Json#1006]
By default settings:

The josn string is : 
`{"result":true,"msg":"started!"}`

But, I want the result is:

`{'result':true,'msg':'started!'}`

How should I do? 

If you konw, please tell me, thank you!

**Comment by JamesNK** [comment]
Hi. Ask this kind of question on stackoverflow

**Comment by ropean** [comment]
ok, thanks you!
