### ISSUE TITLE
JToken.DeepEquals() fails on the JavaScript `Number` type

### ISSUE THREAD

**Issue by Kosta-Github** [JamesNK/Newtonsoft.Json#1007]
According to this documentation:
    https://developer.mozilla.org/en/docs/Web/JavaScript/Data_structures
there is only a single `Number` datatype in JavaScript, which is based on the `C` `double` floating point type.

There might be other places in the code base that don't deal well with respect to this definition, but right now this strikes me most with `JToken.DeepEquals()`. The following assertion (comparing `1` with `1.0`) should be fullfilled, but is failing right now:
```
Assert.True(JToken.DeepEquals(new JObject { { "value", 1 } }, new JObject { { "value", 1.0 } }));
```

**Comment by JamesNK** [comment]
Json.NET's equals logic doesn't nessessarily match JavaScript's. For example a Uri and a string could be written as the same JSON, but they won't equal each other with DeepEquals.

**Comment by Kosta-Github** [comment]
Can that statement be added to the docs then, please?
