### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by FalconCoder** [JamesNK/Newtonsoft.Json#101]
Hi Guys,

The Performance of Serialize & Deserialize it's far from what I expect when there is a lot concurrency it's affect the performance, currency i'm using this
http://techblog.procurios.nl/k/news/view/14605/14863/how-do-i-write-my-own-parser-(for-json).html
the performance to Hashtable it's 2-3ms compare to 69-90ms with .Net 4.5 (Json.Net)

Please improve the performance more

**Comment by nklnandu** [comment]
Do we have any solution or alter nate way to improve the first time latency from the application .
