### ISSUE TITLE
Serialization of dynamic type with TypeNameHandling.Auto

### ISSUE THREAD

**Issue by pardahlman** [JamesNK/Newtonsoft.Json#1012]
I have a bunch of sealed domain objects that I serialize with `Json.NET`, send to other applications and deserialize. These objects may have properties that are

- Defined as an abstract base class with multiple derived classes
- Dynamic Properties

The setting `TypeNameHandling.Auto` is perfect for derived classes, but it does not behave as I expect for `dymanic` properties. Consider the following class

```csharp
public class ExampleClass
{
	public dynamic DynamicProperty { get; set; }
}
```
When serializing an instance of it using a serializer with `TypeNameHandling.Auto`, it results in the following json
```json
{
   "DynamicProperty":{
      "$type":"<>f__AnonymousType0`1[[System.String, mscorlib]], Tester",
      "Foo":"Bar"
   }
}
```
Where `Tester` is the name of my assembly. When (in another assembly) trying to deserialize the json back to `ExampleClass` it fails, since `Json.NET` is not able to locate the `Tester` assembly.

`TypeNameHandling.Auto` should _include the .NET type name when the type of the object being serialized is not the same as its declared type._ In this scenario I would argue that the provided type and declared type is the same (even though it is more complex for anonymous types). Besides, if this is correct behavior, it limits the ability to deserialize to the assembly that instantiated the class (and assemblies that references it).

I'm very interested in hear your thought on this, and if possible point me to a solution. [I've asked around on StackOverflow](http://stackoverflow.com/questions/39386197/omit-type-for-dynamic-property-without-modifying-class) but haven't gotten any suggestions that works for me.

Keep up the good work!
-pardahlman

**Comment by JamesNK** [comment]
You should either turn off type name handling or don't use anonymous types. The two don't work well together.

**Comment by pardahlman** [comment]
Ok sure, but it I don't use type handling, how am I to deserialize derived classes to its actual type?

**Comment by weitzhandler** [comment]
Is there a way to use a custom type name resolver?

**Comment by weitzhandler** [comment]
Ok [got it](http://james.newtonking.com/archive/2011/11/19/json-net-4-0-release-4-bug-fixes).
Gonna keep these comments for the reference.

**Comment by weitzhandler** [comment]
Ok [got it](http://james.newtonking.com/archive/2011/11/19/json-net-4-0-release-4-bug-fixes).
Gonna keep these comments for the reference.
Tho, is there a shorter way to perform this?

Are there some attributes I can decorate properties to force their type resolving?
For instance:

public class Entity
{
    [TypeMap(typeof(IOtherEntity), typeof(OtherEntity)]
    public IOtherEntity { get; set; }
}
