### ISSUE TITLE
No matching parametrized constructor found for 'Type' (.NET Core)

### ISSUE THREAD

**Issue by pieceofsummer** [JamesNK/Newtonsoft.Json#1013]
This is actually resolved in #1002, I just wanted to highlight it as issue, not just an improvement.

If a custom `JsonConverter`'s constructor takes an argument of type `System.Type`, it won't be resolved correctly in portable / .NET Core versions. 

The reason is, because of changes in reflection subsystem, `System.RuntimeType` returned by `typeof(X)` is not equal to `System.Type` from parameter type anymore (even though they represent the same type).

This is not an issue on standard framework (since standard method binder is consistent with reflection changes), but the portable implementation uses a simple `SequenceEqual()` comparison to match parameters' types, and it fails.

Since .NET Core is gaining popularity, I hope it will be fixed in the main codebase.

**Comment by JamesNK** [comment]
Fixed with merge
