### ISSUE TITLE
When StringEnumConverter's AllowIntegerValues = false, integers can still slip through if submitted as strings

### ISSUE THREAD

**Issue by wmate** [JamesNK/Newtonsoft.Json#1014]
Hi Guys!

When using `StringEnumConverter` with `AllowIntegerValues = false`, integers can still slip through if submitted as strings!

Here's a quick example, consider this enum:

``` csharp
enum TestEnum
{
    Index0,
    Index1
}
```

And these settings:

``` c#
// setup StringEnumConvert and disallow integers
var settings = new JsonSerializerSettings();
settings.Converters.Add(new StringEnumConverter
{
    AllowIntegerValues = false
});
```

The following throws an exception as expected (naked JSON integer `1`):

``` C#
var test3 = JsonConvert.DeserializeObject<TestEnum>("1", settings);
```

This **should not work**, but unexpectedly, it does (a number quoted inside a JSON string `"999"`):

``` C#
// test5 will be set to 999
var test5 = JsonConvert.DeserializeObject<TestEnum>("\"999\"", settings);
```

Am I just crazy here? I have created a full example of code demonstrating this:
https://gist.github.com/wmate/adbb44553c2d80aa46569ff25a5adc1e

**Comment by Katsarakis** [comment]
bitte keine mails mehr...




Mit freundlichen Grüßen / With best regards

Michael Katsarakis
Software Developer 

KUNBUS GmbH
Heerweg 15C, 73770 Denkendorf, Deutschland/Germany
Telefon: +49 711 3409-7701 / Telefax: +49 711 3409-9-7086
E-Mail: mailto:m.katsarakis@kunbus.de 
Web: http://www.kunbus.com

Amtsgericht Stuttgart HRB 726876; Ust.-IdNr.: DE261128643; 
Geschäftsführung: Dr. Martin Kunschert 



Von:
wmate <notifications@github.com>
An:
"JamesNK/Newtonsoft.Json" <Newtonsoft.Json@noreply.github.com>, 
Datum:
09.09.2016 07:04
Betreff:
[JamesNK/Newtonsoft.Json] When StringEnumConverter's AllowIntegerValues = 
false, integers can still slip through if submitted as strings! (#1014)



Hi Guys!
When using StringEnumConverter with AllowIntegerValues = false, integers 
can still slip through if submitted as strings!
Here's a quick example, consider this enum:
enum TestEnum
{
    Index0,
    Index1
}
And these settings:
// setup StringEnumConvert and disallow integers
var settings = new JsonSerializerSettings();
settings.Converters.Add(new StringEnumConverter
{
    AllowIntegerValues = false
});
The following throws an exception as expected (naked JSON integer 1):
var test3 = JsonConvert.DeserializeObject<TestEnum>("1", settings);
This should not work, but unexpectedly, it does (a number quoted inside a 
JSON string "999"):
// test5 will be set to 999
var test5 = JsonConvert.DeserializeObject<TestEnum>("\"999\"", settings);
Am I just crazy here? I have created a full example of code demonstrating 
this:
https://gist.github.com/wmate/adbb44553c2d80aa46569ff25a5adc1e

**Comment by JamesNK** [comment]
The problem is that Enum.Parse itself accepts a number as a string. To fix this I would need to rewrite Enum.Parse.

What about if I add to the documentation that AllowIntegerValues only references to actual integers, and not strings with integers in them?

**Comment by JamesNK** [comment]
I think I found a way to fix this without too big an impact https://github.com/JamesNK/Newtonsoft.Json/commit/6c272eac6ee71705fd813c90ce61b1a6d6ef2a35

**Comment by wmate** [comment]
That's amazing @JamesNK ! I was going to take a crack at it but you beat me to it... and in a rather elegant fashion I might add! Thanks for the super-quick response. At the risk of repeating thoughts from the entire community, keep up the fantastic work on this epic JSON library of yours!

**Comment by yehtutlwin** [comment]
Hi @JamesNK 
Sorry to revive this, but I found that this is still taking in numbers with signs (e.g, "+1", "-1").
I found this SO answer (https://stackoverflow.com/a/35484440) to be handling that case. Perhaps it should be added in?

**Comment by JamesNK** [comment]
Thanks for the heads up
Fixed - https://github.com/JamesNK/Newtonsoft.Json/commit/4467bdb224f71522c9fb81609e7da82b3b4d1a88
