### ISSUE TITLE
Ignore specific properties when serializing a dynamic object

### ISSUE THREAD

**Issue by osela** [JamesNK/Newtonsoft.Json#1016]
When serializing regular (non-dynamic) objects I can choose to ignore certain properties on serialization by using a custom ContractResolver (as suggested [here](http://www.newtonsoft.com/json/help/html/ReducingSerializedJSONSize.htm)).

It seems this approach doesn't work for dynamic objects.

I've checked the [source code](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L883) and haven't found a way to to this other than removing the unwanted properties before the serialization.

Have I missed anything? Is there a built-in way to exclude properties when serializing dynamic objects?

**Comment by JamesNK** [comment]
No. dynamic is basically a dictionary.
