### ISSUE TITLE
JsonExtensionData emits duplicate properties during serialization if named property also exists

### ISSUE THREAD

**Issue by zarenner** [JamesNK/Newtonsoft.Json#1017]
JsonExtensionData appears to emit duplicate elements during serialization if a key in the JsonExtensionData dictionary also exists as a named property.

I would have expected (by default at least) for the named member to be serialized and the extension data property to be ignored.

Simple repro:
```
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Test
{
    public class Program
    {
        [JsonObject]
        class SomeContract
        {
            [JsonProperty(PropertyName = "foo")]
            public string Foo { get; set; }

            [JsonExtensionData]
            public IDictionary<string, JToken> AdditionalData { get; set; }
        }

        public static void Main(string[] args)
        {
            Console.WriteLine(JsonConvert.SerializeObject(new SomeContract
            {
                Foo = "good",
                AdditionalData = new Dictionary<string, JToken> { { "foo", "bad" } }
            }));             
        }
    }
}
```
Output:
{"foo":"good","foo":"bad"}

A more realistic example that we encountered is:
1. Deserialize to type with JsonExtensionData
2. Construct other type with JsonExtensionData (possibly a derived type), copying extension data
3. Serialize other type

**Comment by JamesNK** [comment]
I'm ok with it working like this. To change this behavior the serializer would need to keep track of each property being written and I don't think the overhead is worth it.

**Comment by zarenner** [comment]
Noted, thanks. At least the behavior is now documented here, although updating the official docs probably wouldn't hurt either.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/59618df631c10be4d25cfa7224bb18bdbde72a9b
