### ISSUE TITLE
Refactor #ifdefs to be by feature

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json#1018]
Right now there is an #ifdefs per platform, e.g. NET20, NET40, NETSTANDARD1_0. This is a pain when a new platform is added because the new platform needs to be added everywhere throughout the source.
# ifdefs should be refactored to be via feature, e.g. BIGINTEGER, NETCORE_REFLECTION, XML, etc. When a new platform is added then the appropriate #ifdefs can be added to it.

**Comment by fgreinacher** [comment]
Is this up for grabs @jamesnk? I'd be interested in giving it a try.

**Comment by fgreinacher** [comment]
OK, I'll wait for the async changes. Thanks for the hint :)

**Comment by fgreinacher** [comment]
This can be closed now
