### ISSUE TITLE
Boolean values are deserialized as string with lowercase instead of capital letter

### ISSUE THREAD

**Issue by twsouthwick** [JamesNK/Newtonsoft.Json#1019]
I recently upgraded a component to use 9.0.1 from 6.0.8, and found some test cases that started failing. The repro is this:

```csharp
[TestMethod]
public void SerializeBool()
{
  var obj = new { A = true };
  var serialized = JsonConvert.SerializeObject(obj);
  var type = new { A = "" };
  var deserialized = JsonConvert.DeserializeAnonymousType(serialized, type);
  Assert.AreEqual("True", deserialized.A);
}
```

**Expected**
`deserialized.A == "True"`

**Actual**
`deserialized.A == "true"`

**Comment by JamesNK** [comment]
That was an intentional change. Previously the JSON boolean was being converting to a .NET bool and then ToString was being called on it. Now it is read directly to a string.
