### ISSUE TITLE
Classes which inherit from Dictionary do not write the subclass' fields upon serialization

### ISSUE THREAD

**Issue by lostromb** [JamesNK/Newtonsoft.Json#1020]
I have a schema class which inherits from Dictionary<string, object>, and has the following construction:
```csharp
public class map : Dictionary<string, object>
{
    [JsonProperty("@")]
    public string type_name { get { return "map"; } }
}
```

Then, for example, we have some code that does this;
```csharp
var testObject = new map();
testObject["key1"] = "val1";
Console.WriteLine(JsonConvert.SerializeObject(testObject));
```

The output comes out as just "{ "key1"; "val1" }", and the type_name { "@": "map" } is not serialized.

I was not _entirely_ sure if this was by design or an oversight in the serializer for generic dictionaries, either way, someone correct me if I'm wrong

**Comment by JamesNK** [comment]
By design. Put a [JsonObject] attribute on your class if you want the property.
