### ISSUE TITLE
Use FastDtoa for number serialization

### ISSUE THREAD

**Issue by sebastienros** [JamesNK/Newtonsoft.Json#1025]
I maintain Jint which is a Javacript interpreter in C#. To be ecma compliant the serialization of numbers has to be very specific. The best implementation I could find is from Google, who hired the engineer who invented a very fast algorithm for floating point number serialization. Google ported it to Java and it's now what is used in Chrome. I ported it in C# and wondered if it might be useful for performance/accuracy reasons. In case you care, here is the port: https://github.com/sebastienros/jint/tree/master/Jint/Native/Number/Dtoa

There are many unit tests for it, including the ones from ECMA.

**Comment by khlitoshi** [comment]
I would assume a project's dead because some people haven't received a response to their questions for several days(13 days for example). This project's been around for over 10 years doesn't mean cannot die one day.

**Comment by sebastienros** [comment]
I wouldn't ;) Sometimes it takes me way more time to answer some questions on my projects, and I can tell you they are very well alive and taken care of. It's just that there are periods when you can't put that much effort, or too many questions, or just that you don't have an opinion and take more time to know what to answer.

If you care about this question though, please +1 it, that might help ;)

**Comment by JamesNK** [comment]
I deleted your other comments. Take bad manners and be a douche somewhere else. Thanks.

**Comment by JamesNK** [comment]
Previous attempts to do custom double serialization and deserialization was rolled back because it is pretty much impossible to match exactly what .NET does. I'm going to wait until there is a faster offical library from Microsoft.

**Comment by sebastienros** [comment]
To confirm this, the resulting serialized value is definitely different than the one from .NET. It matches the JavaScript one instead as it's more precise.

Example in default .NET which would perfectly match with the suggested algorithm:

```csharp
Console.WriteLine(14.915832707045631); // => 14.9158327070456
Console.WriteLine(0.2388906159889881); // => 0.238890615988988
```
