### ISSUE TITLE
Deserializing Bson to 3D array of doubles.

### ISSUE THREAD

**Issue by katsuragi545** [JamesNK/Newtonsoft.Json#1027]
I've seen several examples of deserializing BSON to a custom class type (Product, Event, Person, etc.), but I haven't seen any examples deserializing BSON to something like an array. Am I missing something in the documentation? Is this impossible or is there some specific way to get deserialization to an an array (or multidimensional array) to work?

Right now, I'm trying to deserialize some BSON back into a 3D array of doubles. 
Here's some of my code:

```
//Array declaration
double[,,] array = new double[4, 2, 3];
```

I have a function that sends that array to this helper method that converts an object to BSON:
```
public string ConvertToBson(object o)
{
    //Serialize the object to bson format
    MemoryStream ms = new MemoryStream();
    using (BsonWriter writer = new BsonWriter(ms))
    {
        JsonSerializer serializer = new JsonSerializer();
        serializer.Serialize(writer, o);
    }
    string serializedData = Convert.ToBase64String(ms.ToArray());
    return serializedData;
}
```

Next, I try to deserialize the returned BSON back into its original form with:
```
public void DeserializeBSON()
{
        byte[] data = Convert.FromBase64String(x);
        MemoryStream ms = new MemoryStream(data);
        using(BsonReader reader = new BsonReader(ms))
        {
            JsonSerializer serializer = new JsonSerializer();
            double[, ,] d = serializer.Deserialize<double[, ,]>(reader);
            Console.WriteLine("Array: " + d + " " + d.Length);
        }
}
```

When I try to deserialize, I get the following error:
`Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Double[,,]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.`

I've read through the error and I'm confused as to what exactly I'm supposed to do codewise to resolve this.  I've tried doing what the error fix suggests - I've tried passing in a serialized json string to ConvertToBson() instead of the raw 3D double array but then ConvertToBson fails. I've also tried deserializing to a List with 'var d = serializer.Deserializer<List<double>>(reader);' which gives me the same error.

Sorry if this is a noob question - I've just started learning how to use BSON.

**Comment by khlitoshi** [comment]
I would assume a project's dead because some people haven't received a response to their questions for several days(10 days for example). This project's been around for over 10 years doesn't mean cannot die one day.

**Comment by JamesNK** [comment]
http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Bson_BsonReader_ReadRootValueAsArray.htm
