### ISSUE TITLE
Date serialization doesn't follow ISO 8601 exactly

### ISSUE THREAD

**Issue by DieterLi** [JamesNK/Newtonsoft.Json#1029]
In my test, although the default date format claimed for ISO 8601, but after serialization, the milliseconds part is missing, when this part is zero. 
And on other side, it's deserialized by Joda DateTime ISO format, which complains the missing of the millisecond part. 
The temporary solution is that I have to override the default ISO 8601 one, by DateFormatString, "yyyy-MM-ddTHH:mm:ss.fffzzz"

**Comment by JamesNK** [comment]
I'm pretty sure the precision of fractions of seconds isn't mandated by ISO 8601.
