### ISSUE TITLE
Make docs on using serializer in a non-static way easier to find

### ISSUE THREAD

**Issue by togakangaroo** [JamesNK/Newtonsoft.Json#1034]
After spending a few minutes, I was unable to find docs on how to use this library without using the static `JsonConvert` helper class.

It's not a huge deal since for most applications; `JsonConvert` is absolutely sufficient, and you can always check its source for the non-static equivalent, but it *is* frustrating that the documentation on what should be a fairly simple thing is not readily available.

**Comment by JamesNK** [comment]
What is wrong with http://www.newtonsoft.com/json/help/html/SerializingJSON.htm ?

**Comment by togakangaroo** [comment]
@JamesNK that's pretty much exactly what I would like to see...but I didn't find it :(

I think that its beneath the `JsonConvert` example and scrolled off the page initially is the problem. Could be addressed simply by adding two shortcuts at the top something like

* Simple static serialization with `JsonConvert`
* More complex serialization with `JsonSerializer`

# JsonConvert

 .....

# JsonSerializer

....

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/b7e77700acb288f596ba13b64fb1bc419f69dce5
