### ISSUE TITLE
Possible bug on internal method CoerceEmptyStringToNull

### ISSUE THREAD

**Issue by wizzar** [JamesNK/Newtonsoft.Json#1036]
Hi,
I was having trouble making JsonNet convert empty strings to null so I decided I would dig into the code.
As it turns out, ther is a method called CoerceEmptyStringToNull, line 343 on JsonSerializerInternalReader.cs file.

I expected this method to convert empty strings to null, but its implementation seems to be faulty.

`

        private static bool CoerceEmptyStringToNull(Type objectType, JsonContract contract, string s)

        {
            var a = string.IsNullOrEmpty(s);

            var b = objectType != null;

            **var c = objectType != typeof(string);**

            var d = objectType != typeof(object);

            var e = contract != null;

            var f = contract.IsNullable;

            return a && b && c && d && e && f;
        }
`

Condition **c** seems out of place because I suppose we are expecting a string to be converted no null, but if it is a string, **c** will fail, thus not letting any string ever be converted to null.

**Comment by JamesNK** [comment]
The empty string to null coercion is for nullable non-string types (e.g. int?). Actual strings should still be able to have an empty string value.

**Comment by wizzar** [comment]
Thank you, that makes a lot of sense. I wish there was a way to make simple empty strings be coerced to null too.
