### ISSUE TITLE
Install script not working properly.

### ISSUE THREAD

**Issue by TheNiels1997** [JamesNK/Newtonsoft.Json#1037]
Software: Visual Studio 2015 Community Edition
Newtonsoft.Json version: 9.0.1

Today I tried to add the Json.Net package to my new application but I got an error about Execution Policies instead.

I have already set my ExecutionPolicy to Unrestricted to test if that helped but it really didn't help at all.

[UPDATE] The libraries are added to my project though but I don't know if the policy error has any effect on the behavior of Visual Studio.

This is the log from the output window in VS 2015:

> Attempting to gather dependency information for package 'Newtonsoft.Json.9.0.1' with respect to project 'WeatherApp', targeting '.NETFramework,Version=v4.5.2'
> Attempting to resolve dependencies for package 'Newtonsoft.Json.9.0.1' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Newtonsoft.Json.9.0.1'
> Resolved actions to install package 'Newtonsoft.Json.9.0.1'
> Adding package 'Newtonsoft.Json.9.0.1' to folder 'c:\users\niels\documents\visual studio 2015\Projects\WeatherApp\packages'
> Added package 'Newtonsoft.Json.9.0.1' to folder 'c:\users\niels\documents\visual studio 2015\Projects\WeatherApp\packages'
> Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
> Executing script file 'c:\users\niels\documents\visual studio 2015\Projects\WeatherApp\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
> & : File C:\users\niels\documents\visual studio 2015\Projects\WeatherApp\packages\Newtonsoft.Json.9.0.1\tools\install.p
> s1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Polic
> ies at http://go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:45
> + ... rgs+=$_}; & 'c:\users\niels\documents\visual studio 2015\Projects\Wea ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
> Successfully installed 'Newtonsoft.Json 9.0.1' to WeatherApp
> ========== Finished ==========

**Comment by day01** [comment]
Hi,
You have set executionPolicy for PS as restricted. 
It is ok if you dont trust for scripts created by another person :)

It is a reason why install.ps1 for json.net was not executed at all.
System blocked it.

But if we will look into install.ps1 we can see :
if ($installMatch)
{
    $dte2.ItemOperations.Navigate($url) | Out-Null
}
where url:
$url = "http://www.newtonsoft.com/json/install?version=" + $package.Version

So, install.ps1 will show you better message output and at the end script will open newtonsoft website.

D

**Comment by JamesNK** [comment]
This is a NuGet issue. You should raise it on their repo - github.com/nuget
