### ISSUE TITLE
Deserializing unclosed object succeeds when the object has a parameterized constructor.

### ISSUE THREAD

**Issue by dbc2** [JamesNK/Newtonsoft.Json#1038]
This issue comes from [Newtonsoft.Json parses incorrect json](https://stackoverflow.com/questions/39943346/newtonsoft-json-parses-incorrect-json) from [Łukasz](https://stackoverflow.com/users/5123895/%C5%81ukasz).

Consider the following type:

    public class CompletionDataRequest
    {
        public CompletionDataRequest(string text, int cursorPosition, string dataSource, string project)
        {
            Text = text;
            CursorPosition = cursorPosition;
            DataSource = dataSource;
            Project = project;
        }

        public string Text { get; }
        public int CursorPosition { get; }
        public string DataSource { get; }
        public string Project { get; }
    }

And the following JSON:

    {"text":"s","cursorPosition":189,"dataSource":"json_northwind",

This JSON is syntactically invalid as it is missing a closing brace.  However, If I attempt to deserialize it, `JsonConvert.DeserializeObject` succeeds without throwing a `JsonSerializationException`:

    var s = @"{""text"":""s"",""cursorPosition"":189,""dataSource"":""json_northwind"",";
    var request = JsonConvert.DeserializeObject<CompletionDataRequest>(s);

However, if I redefine the object to have a nonparameterized constructor, deserialization throws an exception as expected:

    public class CompletionDataRequest
    {
        public CompletionDataRequest(string text, int cursorPosition, string dataSource, string project)
        {
            Text = text;
            CursorPosition = cursorPosition;
            DataSource = dataSource;
            Project = project;
        }

        [JsonConstructor]
        private CompletionDataRequest()
        {
        }

        [JsonProperty]
        public string Text { get; private set; }
        [JsonProperty]
        public int CursorPosition { get; private set; }
        [JsonProperty]
        public string DataSource { get; private set; }
        [JsonProperty]
        public string Project { get; private set; }
    }

The specific problem is as follows.  When creating an object with a parameterless constructor, Json.NET first constructs the object, then populates it with [`JsonSerializerInternalReader.PopulateObject()`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2291).  This method has the following (simplified) logic:

        private object PopulateObject(object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, string id)
        {
            bool finished = false;
            do
            {
                switch (reader.TokenType)
                {
                    case JsonToken.PropertyName:
                    {
                        // Read and process the property.
                    }
                    case JsonToken.EndObject:
                        finished = true;
                        break;
                    case JsonToken.Comment:
                        // ignore
                        break;
                    default:
                        throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
                }
            } while (!finished && reader.Read());

            if (!finished)
            {
                ThrowUnexpectedEndException(reader, contract, newObject, "Unexpected end when deserializing object.");
            }

            return newObject;
         }

As you can see, there is logic `if (!finished)` to verify that the object is actually closed.

However, when creating an object with a parameterized constructor, the properties are read before the object is constructed, using [`JsonSerializerInternalReader.ResolvePropertyAndCreatorValues()`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2115):

        private List<CreatorPropertyContext> ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
        {
            List<CreatorPropertyContext> propertyValues = new List<CreatorPropertyContext>();
            bool exit = false;
            do
            {
                switch (reader.TokenType)
                {
                    case JsonToken.PropertyName:
                        // Read and process the property.
                        break;
                    case JsonToken.Comment:
                        break;
                    case JsonToken.EndObject:
                        exit = true;
                        break;
                    default:
                        throw JsonSerializationException.Create(reader, "Unexpected token when deserializing object: " + reader.TokenType);
                }
            } while (!exit && reader.Read());

            return propertyValues;
        }

There's no equivalent check for `exit` being true, which is the cause of the issue.

**Comment by JamesNK** [comment]
Nice issue! Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/0721bd4decd1d48f22e12c2cb881b0af91b05ca1
