### ISSUE TITLE
Deserializar JSON; list with string key.

### ISSUE THREAD

**Issue by eliezeralmeida** [JamesNK/Newtonsoft.Json#1041]
I not found documentation or similar questions on the use of lists mapped without using dictionary.

Example json:
`{"key1": { "atributo1": "valor1", "atributo2": "valor2" }, "key2": { "atributo1": "valor1", "atributo2": "valor2"}}`

Exemple of class:
`public class Class1 {`
`public string atributo1 {get; set;}`
`public string atributo2 {get; set;}`
`}`

Using dictionary would look like this:
`var d = JsonConvert.DeserializeObject<Dictionary<string, Class1>>(res.Body);`

But I would like to create a list, the key would be an attribute of the class of my choice.

How I wish:

Exemple of class:
`public class Class1 {`
`public string key {get; set;}` -> **Here would the key to json**
`public string atributo1 {get; set;}`
`public string atributo2 {get; set;}`
`}`

Deserialize:
`var d = JsonConvert.DeserializeObject<IList<Class1>>(res.Body);`

Has anyone used it?

**Comment by manuelmdn** [comment]
Hi, recently i worked on a project that use json, and I implemented this code for put my class into list, I hope that give you an idea.

`public class Class1 {`
`public string atributo1 {get; set;}`
`public string atributo2 {get; set;}`
`}`
`public class ClassList`
`{`
`    public IList<Class1 > dataClass { get; set; }`
`}`

`var _CLassJSON = new ClassList();`
`var strJSON = String.Empty;`
`Request.InputStream.Position = 0;`
`using (var reader = new StreamReader(Request.InputStream))`
`{`
`strJSON = reader.ReadToEnd();`
`}`
`var d = JsonConvert.DeserializeObject<IList<Class1>>(strJSON );`
`_CLassJSON = d;`

`Class1 class1 = new Class1();`
`foreach (var item in _CLassJSON .dataClass )`
`{`
       `class1 .atributo1 = item.atributo1;`
       `class1 .atributo2 = item.atributo2;`
`}`

**Comment by eliezeralmeida** [comment]
Hi, thanks for your idea.

I thought I would have some alternative use annotations to solve my problem, I have not found anything yet, more I solved my problem by setting the keys after deserialize JSON.

Thanks for sharing.
