### ISSUE TITLE
JObject.Value<Guid>("") --> System.InvalidCastException 

### ISSUE THREAD

**Issue by beckma** [JamesNK/Newtonsoft.Json#1048]
The following Code throws an System.InvalidCastException:

//Guid-Value
var __json = "{Id: \"00000000-0000-0000-0000-000000000000\"}";
var __jobject = Newtonsoft.Json.JsonConvert.DeserializeObject<JObject>(__json);
var __id = __jobject.Value&lt;Guid&gt;("Id");

![image](https://cloud.githubusercontent.com/assets/6991499/19411155/5633b0f8-92fc-11e6-9528-d69a424c99fc.png)

This could easy be fixed for example with this Code (in /Linq/Extensions.cs; Line 293):

                if (targetType == typeof(Guid))
                {
                    //Bugfix for Guid
                    var guidvalue = (string)System.Convert.ChangeType(value.Value, typeof(string), CultureInfo.InvariantCulture);
                    return (U)System.ComponentModel.TypeDescriptor.GetConverter(typeof(U)).ConvertFromInvariantString(guidvalue);
                }

![image](https://cloud.githubusercontent.com/assets/6991499/19411186/37bc2280-92fd-11e6-8a1e-62e5cac01eeb.png)

Is it possible to add this modification?

**Comment by JamesNK** [comment]
Hmmm, does this work:

```
Guid g = (Guid)__jobject["id"];
```

The cast operators are generally better than the Value method.

**Comment by KaineVarley** [comment]
I have to share the views of @beckma, having the generic method [JToken.Value<T>() method](https://www.newtonsoft.com/json/help/html/m_newtonsoft_json_linq_jtoken_value__1.htm) suggests that the output should be returned as that type. Especially given that Guid's are universally used. This should be supported, of the [documentation](https://www.newtonsoft.com/json/help/html/m_newtonsoft_json_linq_jtoken_value__1.htm) updated to downgrade expectations.

Instead, I find myself having to resort to parsing the values as strings and using my own parse extension method to convert these. I've been using this generic method for several years now without issue. Perhaps it could be implemented into the `JToken.Value<T>()` method?

```csharp
        public static T Parse<T>(this string value, bool useDefault = true)
        {
            try { return (T)TypeDescriptor.GetConverter(typeof(T)).ConvertFromInvariantString(value); }
            catch
            {
                if (useDefault) { return default; }      // Swallow the exception and return the object default.
                throw;                                   // Bubble the exception.
            }
        }
```

This can be called:
```csharp
        myGuid = myToken.Value<string>().Parse<Guid>();
```

I hope that's of some benefit.
