### ISSUE TITLE
JSON.NET serialisation of nullable structs and TypeNameHandling.Auto

### ISSUE THREAD

**Issue by DaveVdE** [JamesNK/Newtonsoft.Json#1050]
The following program:

    using System;
    using Newtonsoft.Json;
    
    namespace JsonPlayground
    {
        public class Program
        {
            private struct Message
            {
                public string Value { get; }
    
                [JsonConstructor]
                public Message(string value)
                {
                    if (value == null) throw new ArgumentNullException(nameof(value));
    
                    Value = value;
                }
            }
    
            private class ObjectWithOptionalMessage
            {
                public Message? Message { get; }
    
                public ObjectWithOptionalMessage(Message? message)
                {
                    Message = message;
                }
            }
    
            public static void Main(string[] args)
            {
                var objWithMessage = new ObjectWithOptionalMessage(new Message("Hello!"));
    
                var serializerSettings = new JsonSerializerSettings
                {
                    TypeNameHandling = TypeNameHandling.Auto,
                    Formatting = Formatting.Indented
                };
    
                Console.WriteLine(JsonConvert.SerializeObject(objWithMessage, serializerSettings));
            }
        }
    }

Gives me the following output:

    {
      "Message": {
        "$type": "System.Nullable`1[[JsonPlayground.Program+Message, JsonPlayground]], System.Private.CoreLib",
        "Value": "Hello!"
      }
    }

And I can't think of a reason why `$type` should be included for what is clearly a well declared property. If I declare the `Message` property to not be nullable, the `$type` property is not included.

Why is that?

**Comment by WiredUK** [comment]
Worth noting that adding this to the `Message` property fixes the issue, but it doesn't explain the reason why it happens:

    [JsonProperty(TypeNameHandling = TypeNameHandling.None)]

**Comment by JamesNK** [comment]
Fixed by @TylerBrinkley

It will be in the next release.
