### ISSUE TITLE
Make JsonSerializer.ApplySerializerSettings public

### ISSUE THREAD

**Issue by BalassaMarton** [JamesNK/Newtonsoft.Json#1052]
Since `JsonSerializer` is not sealed, and there are some corner cases (see below) when one might do so, it would be extremely useful if `JsonSerializer.ApplySerializerSettings` was a public method. Currently, if I inherit from `JsonSerializer`, there is no convenient way to use a `JsonSerializerSettings`, since there is no base constructor accepting it, or any means to apply it. Copy-pasting the code from `ApplySerializerSettings` does not work either, because it uses internal fields from both classes.

#### Background
I stumbled on this problem when trying to pass a custom object in `Context` on .NET Core. The .NET Core version of `StreamingContext` does not have a `Context` property, which makes it impossible to pass down any additional data to converters during serialization/deserialization. My last resort solution would be a custom serializer class that contains the additional data, but subclassing `JsonSerializer` in a way that only some properties are added, and it works as the base class otherwise, seems impossible with these limitations.

**Comment by JamesNK** [comment]
Sorry but JsonSerializer isn't designed to be subclassed and I don't want to encourage it. With .NET Standard 2.0 the context should be added back to StreamingContext
