### ISSUE TITLE
Allow getter-only properties to serialize as references if they're constructor parameters

### ISSUE THREAD

**Issue by TylerBrinkley** [JamesNK/Newtonsoft.Json#1053]
To formalize PR #1022, consider the following code.

    [JsonObject(IsReference = true)]
    private class Condition
    {
        public int Value { get; }

        public Condition(int value)
        {
            Value = value;
        }
    }

    private class ClassWithConditions
    {
        public Condition Condition1 { get; }

        public Condition Condition2 { get; }

        public ClassWithConditions(Condition condition1, Condition condition2)
        {
            Condition1 = condition1;
            Condition2 = condition2;
        }
    }

    [Test]
    public void SerializeIsReferenceReadonlyProperty()
    {
        Condition condition = new Condition(1);
        ClassWithConditions value = new ClassWithConditions(condition, condition);

        string json = JsonConvert.SerializeObject(value, Formatting.Indented);
        StringAssert.AreEqual(@"{
      ""Condition1"": {
        ""$id"": ""1"",
        ""Value"": 1
      },
      ""Condition2"": {
        ""$ref"": ""1""
      }
    }", json);
    }

The current json output is

    {
      "Condition1": {
        "Value": 1
      },
      "Condition2": {
        "Value": 1
      }
    }

but should be

    {
      "Condition1": {
        "$id": "1",
        "Value": 1
      },
      "Condition2": {
        "$ref": "1"
      }
    }

This test currently fails because `ClassWithConditions` `Condition1` and `Condition2` are getter only properties but since they're constructor parameters it should still serialize the references. Adding a setter to these properties results in the expected json output.

**Comment by JamesNK** [comment]
Fixed. Thanks
