### ISSUE TITLE
SelectTokens and nodes with dots in the name

### ISSUE THREAD

**Issue by vincentlabatut** [JamesNK/Newtonsoft.Json#1059]
Hi,
`SelectTokens("..Node1..['My.Child.Node']..TargetNode")` => works and returns the exact number of TargetNodes I want
`SelectTokens("..['My.Child.Node']")` => returns null, I think it should find the node

note: Node1 is the parent of My.Child.Node

I have the feeling I need to select the exact parent of a node with dots in its name in order to go through it in a query...  I wish I could just do 
`SelectTokens("$..['My.Child.Node']")`
just as with any other node or at least, not to have to point to the exact parent in my query...

nb :
`SelectTokens("..TargetNode")`   => works and returns far too many TargetNode(s) for my need
`SelectTokens("..Node1..TargetNode")`   => works and returns less but still too many, I want to filter according to "My.Child.Node"

**Comment by JamesNK** [comment]
Where is your JSON?

**Comment by vincentlabatut** [comment]
Hi, here is the JSON, the code, and attached the corresponding project to repro. best regards.
```
{
    "Node1": {
        "Child1": {
            "Name": "IsMe",
            "TargetNode": {
                "Prop1": "Val1",
                "Prop2": "Val2"
            }
        },
        "My.Child.Node": {
            "TargetNode": {
                "Prop1": "Val1",
                "Prop2": "Val2"
            }
        }
    },
    "Node2": {
        "TargetNode": {
            "Prop1": "Val1",
            "Prop2": "Val2"
        }
    }
}
```
```
            JObject models = JObject.Parse(File.ReadAllText("myjson.json"));
            // finds 1 as expected
            int result1 = models.SelectTokens("..Node1..['My.Child.Node']..TargetNode").Count();
            // same as above
            int result1b = models.SelectTokens("..Node1.['My.Child.Node']..TargetNode").Count();
            // finds 3 as expected 
            int result2 = models.SelectTokens("..TargetNode").Count();
            // finds 2 as expected
            int result3 = models.SelectTokens("..Node1..TargetNode").Count();
            
            // finds 0, but should find 1
            int result4 = models.SelectTokens("..['My.Child.Node']").Count();
```
[ConsoleApplication3.zip](https://github.com/JamesNK/Newtonsoft.Json/files/555414/ConsoleApplication3.zip)

**Comment by JamesNK** [comment]
Thanks. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/ae074a3469c031a344f21fb0864c38a6a92a6a3e

This will be in the next release.
