### ISSUE TITLE
Guid becomes string in JObject.ToString + JObject.Parse

### ISSUE THREAD

**Issue by vvnurmi** [JamesNK/Newtonsoft.Json#1060]
If I convert a JObject that contains a Guid field into string and parse it back, the field can no longer be read as a Guid.

This is from Visual Studio 2015 C# Interactive window using Json.Net 9.0.1:

    > var ob = JObject.FromObject(new { id = Guid.NewGuid() });
    > JObject.Parse(ob.ToString())["id"].Value<Guid>()
    Invalid cast from 'System.String' to 'System.Guid'.
      + System.Convert.DefaultToType(System.IConvertible, System.Type, System.IFormatProvider)
      + string.System.IConvertible.ToType(System.Type, System.IFormatProvider)
      + System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
      + Newtonsoft.Json.Linq.Extensions.Convert<T, U>(T)
      + Newtonsoft.Json.Linq.Extensions.Value<T, U>(IEnumerable<T>)
      + Newtonsoft.Json.Linq.Extensions.Value<U>(IEnumerable<Newtonsoft.Json.Linq.JToken>)

Looks like the Guid degrades into string in (de)serialization:

    > var ob = JObject.FromObject(new { id = Guid.NewGuid() });
    > ob["id"].Type
    Guid
    > JObject.Parse(ob.ToString())["id"].Type
    String

I expect the Guid to remain a Guid after deserialization.

This looks similar to an older, fixed bug in BSON serialization: https://github.com/JamesNK/Newtonsoft.Json/issues/303

**Comment by JamesNK** [comment]
That's because there is no way for Json.NET to know that it should be a GUID. It's just a string when parsing.

Cast instead of using `Value<Guid>()`, e.g. `(Guid)obj["id"]`

**Comment by vvnurmi** [comment]
The functionality I request already exists for `DateTime`. I don't see how `Guid` is different.

    > var ob = JObject.FromObject(new { date = DateTime.UtcNow });
    > JObject.Parse(ob.ToString())["date"].Value<DateTime>()
    [31.10.2016 11.21.31]

What I'm looking for is to be able to write a generic method that could read any reasonable type T (such as `int`, `double`, `DateTime`, `Guid`) out of a certain field of a `JObject`. Given how Json.Net currently works, I can use the `Value` extension method directly for all the other reasonable types except `Guid` which needs a wrapper to handle correctly, like this:

    T ValueReally<T>(this JToken token) {
        return typeof(T) == typeof(Guid)
            ? (dynamic)Guid.Parse(token.ToString())
            : token.Value<T>();
    }

In particular, while `(Guid)obj["id"]` works, `(T)obj["id"]` doesn't.

**Comment by SMoni** [comment]
I also ran into this strange phenomenon, especially that in some projects `Value<Guid>()` works, in some it doesn't and I can't figure out the difference of them.

I followed the Stacktrace down to [DefaultToType](https://referencesource.microsoft.com/#mscorlib/system/convert.cs,d804414ae6829e79,references) and couldn't make out a conversion to `GUID`.

So I guess, it's not a bug in Newtonsoft.Json.
