### ISSUE TITLE
Extra ".0" while parse int number of scientific notation to string

### ISSUE THREAD

**Issue by SkiTiSu** [JamesNK/Newtonsoft.Json#1062]
For example, there's a int in json like "1.0839045e+07", when I parse it as string, it would become "10839045.0". When it directly convert to int, it will throw exception.
I'm using version 9.0.1. It's OK in version 8.0.3.

**Comment by JamesNK** [comment]
What does your JSON and code look like?

**Comment by SkiTiSu** [comment]
@JamesNK Hi, here's the struct

> 
{
    "code": 0,
    "data": {
        "aid": 6.658793e+06,
        "attribute": 540672,
        "duration": 115,
        "pubdate": 1.476350493e+09,
balabala...
        },
balabala...
    },
    "message": ""
}

code:

> public class BiliVideoModel
    {
        public int code { get; set; }
        public object data { get; set; }
        public string aid { get; set; }
        public string pubdate { get; set; }
balabala...
}
VideoModel model = JsonConvert.DeserializeObject<VideoModel>(result);
VideoModel InfoModel = JsonConvert.DeserializeObject<VideoModel>(model.data.ToString());
long lTime = long.Parse(InfoModel.pubdate + "0000000"); // throw here

**Comment by JamesNK** [comment]
I'm not sure what the old behavior was, I haven't got time to go back and check it, but the 9.0.1 behavior looks reasonable.

Why don't you change your last line to something like:

```long lTime = long.Parse(double.Parse(InfoModel.pubdate) + "0000000");```

**Comment by SkiTiSu** [comment]
Thanks a lot. Just confirm it is not a bug, it may make people puzzled after directly upgrade to 9.0.1(like me). It took me some time to find out what went wrong.

**Comment by SkiTiSu** [comment]
Thanks a lot. Just confirm it is not a bug, it may make people puzzled
after directly upgrade to 9.0.1(like me). It took me some time to find out
what went wrong.

2016年10月27日 17:32，"James Newton-King" <notifications@github.com>写道：
