### ISSUE TITLE
Support for Xamarin(.iOS) not present

### ISSUE THREAD

**Issue by Fryhstyxei** [JamesNK/Newtonsoft.Json#1063]
http://www.newtonsoft.com/json claims that Json.NET supports the Xamarin platform.
This is not completely true for the current version; three classes (ILGeneratorExtensions, DynamicReflectionDelegateFactory, DynamicConcreteTests) depend on `System.Reflection.Emit`.

Version 7.0.1 works; did not try it using version 8.0.1.

**Comment by JamesNK** [comment]
Use the portable or netstandard assemblies.
