### ISSUE TITLE
Object hierarchy with property of name 'StartPosition' deserializes incorrectly

### ISSUE THREAD

**Issue by bhedia** [JamesNK/Newtonsoft.Json#1068]
I have an object hierarchy that I send as a HttpResponseMessage serialized using the Newtonsoft Json MediaTypeFormatter and is deserialized by another service using the same formatter. One of the objects in the hierarchy has 2 'int' properties: one called 'StartPosition' and another called 'Length'. In my case, the value of these 2 properties in the in the SERIALIZED payload were 169 and 6 respectively.
On the other end, the payload shows the correct values BEFORE deserialization, but AFTER deserialization the value of the 'StartPosition' property in the object is 0. The 'Length' property is correctly deserialized to a value of 6.
When I rename the property from 'StartPosition' to 'StartPos', the problem goes away.

**Comment by JamesNK** [comment]
Are you able give steps to reproduce this outside of Web API? As far as I know there is no reason that Json.NET by itself should have this issue.

**Comment by bhedia** [comment]
Will try it out shortly and let you know. Thanks.
