### ISSUE TITLE
Cannot deserialize objects with multiple generic types

### ISSUE THREAD

**Issue by einord** [JamesNK/Newtonsoft.Json#1070]
Serializing an object containing a `Dictionary<string, int>` like this:
```c#
class Foo
{
  public Dictionary<string, int> Bar { get; set; }
}
```
Outputs the correct json like this (using `TypeNameHandling.All`):
```json
{
  "$type": "Foo",
  "Bar": {
    "$type": "Dictionary<String, Int32>"
  }
}
```
But when trying to deserialize using a custom binder overriding `BindToType` the type name is incorrect (`Dictionary<String`):
```c#
public override Type BindToType(string assemblyName, string typeName)
{
  if (typeName == "Dictionary<String, Int32>")
  {
    // I never get here because typeName is "Dictionary<String"
    return typeof(Dictionary<string, int>);
  }
  // ...
}
```

It seems like the comma disrupts the typeName.

**Comment by JamesNK** [comment]
A comma is used to delimit the assembly and type names, unless enclosed in square brackets.

```
System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Int32, mscorlib]], mscorlib
```
