### ISSUE TITLE
Json.net wrongly favoring case insensitive match over exact match.

### ISSUE THREAD

**Issue by tomlor** [JamesNK/Newtonsoft.Json#1074]
Version 9.0.1

Json.Net is choosing the wrong name/value pair when trying to deserialize some json where the name of two elements different in case only.  Specifically, the case insensitive match is being chosen over the case sensitive match.
 
This reproduces the problem in Linqpad yielding the wrong value:
`JsonConvert.DeserializeAnonymousType("{a:1, A:2}", new { a = 0 })`

(Edited for readability)

**Comment by JamesNK** [comment]
This issue is that during deserialization a is being to set to 1, and then it is being set to 2, because A will match a when there is no exact match.

Keeping track of what properties is being set - and that a has be set exactly and shouldn't be set inexactly, would negatively effect performance.
