### ISSUE TITLE
Consider caching for ReflectionUtils.SplitFullyQualifiedTypeName

### ISSUE THREAD

**Issue by thesourcerer** [JamesNK/Newtonsoft.Json#1079]
It seems that when we use fully qualified names, SplitFullyQualifiedTypeName contributes a lot of memory allocations for each object deserialization, which adds some stress to the GC.

Is there a reason why the code won't cache the mapping between the fullyQualifiedTypeName string and the TypeNameKey result? it will save quite a bit of string manipulations & memory allocation.

Normally types we deserialize will return over and over again, and are not likely to disappear during runtime.
The memory footprint of the cache should be relatively small compared to the continues allocations.. 

I ran a simple test with a small code change:
for non portable code, added a ConcurrentDictionary from fullyQualifiedTypeName string to TypeNameKey result, and made these allocations completely disappear from PerfView after running a few ms. 

I wonder how such change will be accepted if I submit a pull request for it...

**Comment by JamesNK** [comment]
The problem is that the SerializationBinder API expects the type parts as separate strings:

```
public abstract Type BindToType(string assemblyName, string typeName);
```

**Comment by dbc2** [comment]
Caching aside, it would be easy to reduce the number of memory allocations in `SplitFullyQualifiedTypeName()` by up to 1/2 (but more likely by 1/3) by combining the `Trim()` and `Substring()` calls.  Currently, even with `Formatting.None`, there seems to be a space inserted between the type and assembly names, e.g.:

    {"$type":"Issue1079.RootObject, Issue1079"}

The fact that the space is there means that the [following line](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs#L877) actually does two allocations:

    assemblyName = fullyQualifiedTypeName.Substring(assemblyDelimiterIndex.GetValueOrDefault() + 1, fullyQualifiedTypeName.Length - assemblyDelimiterIndex.GetValueOrDefault() - 1).Trim();

You could eliminate one of the two allocations by combining the substring and trim operations:

        public static void SplitFullyQualifiedTypeName(string fullyQualifiedTypeName, out string typeName, out string assemblyName)
        {
            int? assemblyDelimiterIndex = GetAssemblyDelimiterIndex(fullyQualifiedTypeName);

            if (assemblyDelimiterIndex != null)
            {
                typeName = fullyQualifiedTypeName.Trim(0, assemblyDelimiterIndex.GetValueOrDefault());
                assemblyName = fullyQualifiedTypeName.Trim(assemblyDelimiterIndex.GetValueOrDefault() + 1, fullyQualifiedTypeName.Length - assemblyDelimiterIndex.GetValueOrDefault() - 1);
            }
            else
            {
                typeName = fullyQualifiedTypeName;
                assemblyName = null;
            }
        }

using an extension method such as:

    public static class StringExtensions
    {
        public static string Trim(this string s, int start, int length)
        {
            // References: https://referencesource.microsoft.com/#mscorlib/system/string.cs,2691
            // https://referencesource.microsoft.com/#mscorlib/system/string.cs,1226
            if (s == null)
                throw new ArgumentNullException();
            if (start < 0)
                throw new ArgumentOutOfRangeException("start");
            if (length < 0)
                throw new ArgumentOutOfRangeException("length");
            var end = start + length - 1;
            if (end >= s.Length)
                throw new ArgumentOutOfRangeException("length");
            for (; start < end; start++)
            {
                if (!Char.IsWhiteSpace(s[start])) 
                    break;
            }
            for (; end >= start; end--)
            {
                if (!Char.IsWhiteSpace(s[end]))
                    break;
            }
            return s.Substring(start, end - start + 1);
        }
    }

**Comment by JamesNK** [comment]
Thanks. I had a similar thought.

**Comment by JamesNK** [comment]
Added I don't want to add this but I improved allocations here https://github.com/JamesNK/Newtonsoft.Json/commit/ba04246a16c66c532598df3f072f7e7ccba7d5ac
