### ISSUE TITLE
Incluude out of box IArrayPool implementation with JsonSerializerSettings flag to enable it.

### ISSUE THREAD

**Issue by IlyaGrebnov** [JamesNK/Newtonsoft.Json#1087]

**Comment by IlyaGrebnov** [comment]
It would be also nice if out of box implementation support older  (4.5.2+) .net versions. This could be implemented as a fall back implementation if there is no .net core ArrayPool<char>.Shared available.

**Comment by JamesNK** [comment]
I don't want to do this because I don't think I have the necessary skills to create something that is high perf and thread safe. I recommend wrapping the .NET array pooling implementation.
