### ISSUE TITLE
Want to change Dictionary and List type from $ to ^ sign for MongoDB

### ISSUE THREAD

**Issue by Ahmed310** [JamesNK/Newtonsoft.Json#1090]
I want to change in NewtonSoft.Json library. As in my case, the backend is of C# and have to save and retrieve data from MongoDB which don't consider the **$** sign as the type in Dictionary and List. So, we have to change that **$** sign to **^**  sign. 

As we did this change in the old library of NewtonSoft.JSON library, but now we again have to change it in updated code base. So can you tell me in which file(s) and where I make this change?

My sample JSON style is following

`{"Variables": {
    "^type": "Model.Data.GamePlayVariables, Assembly-CSharp",
    "QuestionMultpliers": {
      "^type": "Model.Data.QuestionMultipliers, Assembly-CSharp",
      "Easy": 1.75,
      "Medium": 3,
      "Hard": 5.25,
      "Impossible": 2
    },
    "QuizGold": 100,
    "QuizThreshold": 60,
    "_id": "gameplayVariables"
  }}`

Otherwise, I'm getting the following error when I switched my Unity Standalone project into Unity iOS project. 

```
Could not convert string '^type' to dictionary key type 'TutorialNames'. Create a TypeConverter to convert from the string to the key type object. Path 'Data.Tutorials.Tutorials.^type', line 1, position 267.
StackTrace:   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary (IDictionary dictionary, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonDictionaryContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00000] in <filename unknown>:0
```

**Comment by JamesNK** [comment]
I would suggest loading JSON into a JObject after serializing it and using LINQ to replace any properties that start with a $ with a ^, and vice versa.

**Comment by Ahmed310** [comment]
@JamesNK can you suggest it with the code snippet. 
I think it would be better if I do this in Serialize and Deserialize functions. What do you say?
