### ISSUE TITLE
TypeConverter with dictionary keys not working in .net core

### ISSUE THREAD

**Issue by ItsVeryWindy** [JamesNK/Newtonsoft.Json#1093]
Ran into an issue using a TypeConverter when trying to deserialize into a dictionary with a key that is not a string.

The error I got was "Could not convert string '{0}' to dictionary key type '{1}'. Create a TypeConverter to convert from the string to the key type object."

I was able to track down the issue to a method ConvertUtils.TryConvertIntarnal not executing the code that uses TypeConverter because it's not included in the published version that .net core uses. 

It would be good if there was a version that targeted a higher version of .net standard.

**Comment by skarllot** [comment]
The package "System.ComponentModel.TypeConverter" is available since NETStandard 1.0, it could be used by Newtonsoft.Json.

Reference: https://www.nuget.org/packages/System.ComponentModel.TypeConverter/

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/2e7b24e9b1873a615bbc8ae2302fd3d174cdb9f2
