### ISSUE TITLE
IEnumerable and ISerializable conflict

### ISSUE THREAD

**Issue by skarllot** [JamesNK/Newtonsoft.Json#1094]
If a type implements both `ISerializable` and `IEnumerable` the former is ignored. The `ISerializable` implementation should overwrite any other type inference.

**Comment by dbc2** [comment]
For a workaround using a custom contract resolver, see [How to serialize an ISerializable object into SOAP or Json or Xml](https://stackoverflow.com/questions/38188639/how-to-serialize-an-iserializable-object-into-soap-or-json-or-xml/38192997#38192997).

**Comment by JonHanna** [comment]
Prioritising `ISerializable` over `IEnumerable` would break uses of `HashSet<T>`, and perhaps other common enumerable types, but that one comes to mind immediately.

**Comment by skarllot** [comment]
I think that using a custom contract resolver is a better approach. I'm closing this issue.
