### ISSUE TITLE
JsonConverters to create abstract implementations cause double allocations

### ISSUE THREAD

**Issue by heaths** [JamesNK/Newtonsoft.Json#1095]
We have an abstract type - `IPackage`, in this case - that can be created based on the value of a "type" property contained within the JSON document. A common pattern is to use `JObject.Load(JsonReader)`, get the "type" (if present), create that type, then call `JsonSerializer.Populate`. The problem is that this causes double the allocations (roughly) for tokens within the object because `JObject.Load` did it to create all its tokens, then `Populate` did it to populate the actual object.

When we have very large JSON documents, this is causing a lot of GC pressure. We can't always guarantee that this "type" property is first (could even be last), and since advancing the `JsonReader` means we lose all data to that point (even if we remembers, we couldn't easily take advantage of `Populate` since several properties might also use converters) and effectively would have to do all the deserialization ourselves.

What could help is if we could clone a reader at the current location. It would be easy enough to loop through the tokens looking for what we want. I realize that does still create some allocations, but as soon as we find our "type" property and get it's value, we can dispose that clone and use the reader to populate the correct type.

Happy to do the work if this is acceptable, but given we're using 8.0.3 was wondering if I could expect a change on that (and would port to master as well) to reduce risk given our timeframe.

**Comment by JamesNK** [comment]
You can't clone a JsonReader because it could have any implementation. JsonTextReader for example reads over a TextReader which is forward only and has the same issue that it could be any kind of TextReader, e.g. a forward only StreamReader over a file or network stream.

**Comment by heaths** [comment]
`Clone` would be abstract on `JsonReader`, of course (much like `Read` since it varies). As for seekability (meant to mention that original and forgot), if the `TextReader` is a `StreamReader` (probably is in most cases) and `StreamReader.BaseStream.CanSeek`, `Clone` could work for a `JsonTextReader`, or throw `InvalidOperationException` or `NotSupportedException`. It should also work easily for a `JTokenReader`.

**Comment by heaths** [comment]
Another possibility may be to implement peek-like functionality, which can work with forward-only streams by caching what was done from the original position up to the current position. That could be done on the `JsonTextReader` with a secondary, as-needed buffer (since the `JTokenReader` should already be seekable). This, say, `Peek` method could work like `Read` except it wouldn't allocate (both could call private methods that take a `bool` to allocate or not) but store what was read into this secondary buffer that would be used, if populated, by `Read` until its exhausted.

**Comment by JamesNK** [comment]
Cloning is pointless when you can't reliably clone the underlying source, and there is no way to do that via the JsonReader.

What is the difference between Peek and Read? At least in JsonTextReaders case they are both going to need to read over the content and load it into memory because you can't go backwards over the TextReader and what is read has to be stored.

If you need to read over something multiple times then you're already doing the best way: you're loading the JSON into memory and then creating JTokenReader.

**Comment by heaths** [comment]
`Read` advanced the position with no way of going back. `Peek` would not, by way of caching what has been read. Some streams in the .NET Framework do this to simulate a forward seek on underlying streams that are forward-only. The point is to avoid the allocations when `JsonReader` starts parsing into allocated types. If we use `JObject.Load` that is one set of allocations (say, for a class with a dozen strings, several integers, and a few bools) just to read the "type", then we allocate our class and call `Populate` which allocates a second set of allocations. Over several thousand objects that adds up very quickly.

**Comment by JamesNK** [comment]
Sounds like you want a rewindable JsonReader. There is no reason you couldn't implement one that wraps another JsonReader, and lets you step backwards. It is too niche for the core library but share it as a NuGet package for other people to use.
