### ISSUE TITLE
Serializing Dictionary: Value was either too large or too small for a Double.

### ISSUE THREAD

**Issue by pergerch** [JamesNK/Newtonsoft.Json#1096]
Serializing and then deserializing a Double value in a Dictionary doesn't work as expected. Double.MaxValue results in this exception:

> Could not convert string '1.79769313486232E+308' to dictionary key type 'System.Double'. Create a TypeConverter to convert from the string to the key type object. Path '['1.79769313486232E+308']

Sample Code (throwing the exception above):

```
Dictionary<double, int> dictionary = new Dictionary<double, int> {{Double.MaxValue, 1}};
Console.WriteLine("1: " + dictionary.First());

string output = JsonConvert.SerializeObject(dictionary);
Console.WriteLine("2: " + output);

Dictionary<double, int> deserializedValue = JsonConvert.DeserializeObject<Dictionary<double, int>>(output);
Console.WriteLine("3: " + deserializedValue.First());
```
Output:
> 1: [1.79769313486232E+308, 1]
> 2: {"1.79769313486232E+308":1}

Whereas doing the same with a plain Double value works fine.

Sample Code (working!):

```
double doubleValue = Double.MaxValue;
Console.WriteLine("1: " + doubleValue);

string output = JsonConvert.SerializeObject(doubleValue);
Console.WriteLine("2: " + output);

double deserializedValue = JsonConvert.DeserializeObject<double>(output);
Console.WriteLine("3: " + deserializedValue);
```
Output:
> 1: 1.79769313486232E+308
> 2: 1.7976931348623157E+308
> 3: 1.79769313486232E+308

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/133bbc2d3802ff5126df692291c19a3301f59308
