### ISSUE TITLE
Clean up XML documentation comments

### ISSUE THREAD

**Issue by stakx** [JamesNK/Newtonsoft.Json#1097]
I was working with Json.NET earlier today and a typo showed up in an IntelliSense tooltip. I thought I'd take a look at the source code's XML documentation comments and see if there were any more spelling errors or irregularities.

In general, the XML documentation comments are pretty good. I'll enter a pull request (#1098) that fixes several details that I expect don't require any further discussion.

There are a few points that might require a decision by the code owners before any changes are made to the comments:

* There's inconsistency in how other code elements are referred to. Sometimes they are referenced with `<see cref="…"/>`, sometimes using code formatting `<c>…</c>`; sometimes no markup is applied at all. The proper solution would seem to use `<see cref="…"/>` everywhere where it can be applied. (In VS 2015, this triggers syntax highlighting in IntelliSense tooltips. But it makes the comments horrible in the Object Browser. No idea what difference it makes with Sandcastle help files etc.)

* Since XML documentation comments are not inherited from base classes, there are quite a few copy & paste errors. Perhaps at some point, changes in base classes' / interfaces' comments should also be applied to inherited / implementing types so that the documentations match up again.

* The results of the JSON de-/serialization process are described with different terms. I might possibly be lacking understanding of Json.NET's architecture to appreciate these differences; but it appears to me that vocabulary such as "JSON object", "JSON text", "JSON string", is used interchangeably. In order to avoid any unnecessary confusion, it might be a good idea to decide on one term and use it consistently throughout the whole code base.

* No conceptual distinction is made between `TextReader` & `TextWriter` and `Stream`. The documentation comments assume that the former are backed by `Stream`, which might be true in the general case, but it is not true by necessity (see e.g. `StringReader` & `StringWriter`). Json.NET appears to deal primarily with `TextReader` and `TextWriter`, so inappropriate references to underlying `Stream` objects (which might not actually exist at all!) should be carefully removed.

* Null references are mentioned in an inconsistent manner. I've seen `null`, `<c>null</c>`, `null reference`, and `null value`. It's a detail, but one that could potentially confuse non-C# programmers. (For example, in VB.NET, `null` doesn't mean anything; The null reference is referred to as `Nothing`.) Any confusion could be ruled out by always writing out "null reference" (but that'd often sound a little clunky).

* Types on the non-JSON-serialized side are called ".NET types" and "Common Language Runtime (CLR) types". Both names .NET and CLR refer to Microsoft's implementation(s) of [the Common Language Infrastructure (CLI) standard](http://www.ecma-international.org/publications/standards/Ecma-335.htm "ECMA-335"). If Json.NET is meant to also run on e.g. Mono, a more neutral term (perhaps "runtime type"?) should be chosen.

* The comments for the few (obsolete) asynchronous methods in the library explain that de-/serialization will "happen on a new thread". Mentioning threads here is not a good idea, since  the methods in question return `Task` objects, which are an abstraction over multi-threading. All that should be said is that de/-serialization will run *as a new `Task` (not thread)*.

I'd be willing to help fix all of these issues.

**Comment by JamesNK** [comment]
> The proper solution would seem to use <see cref="…"/> everywhere where it can be applied.

I agree

> Perhaps at some point, changes in base classes' / interfaces' comments should also be applied to inherited / implementing types so that the documentations match up again.

I agree

> "JSON object", "JSON text", "JSON string"

JSON object means a { ... }, JSON array means a [ ... ].

JSON string could be standardized to JSON text.

> so inappropriate references to underlying Stream objects (which might not actually exist at all!) should be carefully removed.

Yes.

> "Common Language Runtime (CLR) types"

That has probably come across from comments I have copied and pasted from MSDN. I like the term ".NET types" more.

> Mentioning threads here is not a good idea, since the methods in question return Task objects, which are an abstraction over multi-threading.

The way the async methods are implemented isn't a good practice. The comments mention threads to warn people what is happening internally.

**Comment by stakx** [comment]
Cheers for the quick response. So, if you're OK with it, I'll go ahead and prepare another, or rather expand my current pull request with the things you agreed to above.

> I like the term ".NET types" more.

Understood. I would then replace occurrences of "CLR types" with ".NET types".

> JSON object means a { ... }

Sure. JSON "object", when it refers to a `{ … }`, is not to be thrown in the same basket as other generic terms "text", "string", etc.

> The comments mention threads to warn people what is happening internally in the task.

I see. Technically, it's still not entirely accurate — creating a `Task` does not imply any *new* thread, due to thread pooling — but I take your hint: the comments serve a purpose in steering people away from these obsoleted methods.

**Comment by stakx** [comment]
@JamesNK, I currently have more edits to XML doc comments ready (approx. 800 changed lines of code in approx. 80 files). I could either...

1. Split these up into maybe 5-6 PRs, where each of these focuses on one and only one issue (which probably makes them easier to review).

2. Or I could deliver all changes as one rather large PR and be done with it.

What's your preference?

**Comment by stakx** [comment]
@JamesNK, I'm about to start work on all those **`<see cref="…"/>`** references. This could turn into a rather large PR, so I'd first like to ask about your preferences regarding the following:

### Prefixes of the form `T:`, `F:`, `P:`, etc. ###
Do you have a prefererence for either `<see cref="T:System.Single"/>` or `<see cref="System.Single"/>`?

I suggest dropping the prefix. References become shorter & easier on the eyes, and regular C# naming rules apply. (Type keywords can be used, and namespaces can be omitted given the presence of `using` statements.) Most importantly, the C# compiler will check whether the referenced entites actually exist, which is valuable since your library targets multiple platforms.

### Target-specific comments using `#if` blocks? ###
(I don't feel quite up to that, but I can let you know where this might be necessary, if you want.)

Say a comment references `<see cref="T:System.ISerializable"/>`, a type that doesn't exist e.g. for Portable Class Libraries. This should not cause any problems as long as the `T:` prefix is there, but when it's removed, the compiler will emit a warning when compiling a PCL and cause the CI build to fail.

This can be a good thing since it tells you which comments might not make any sense for certain targets. One possible solution would be to write target-specific comments using `#if` blocks.

### Fully-qualified vs. abbreviated type names. ###
Do you have a prefererence for either `<see cref="System.Single"/>` or `<see cref="Single"/>`?

For brevity's sake, I would recommend abbreviated names **if** that can be done without introducing ambiguity or additional `using` statements at the beginning of the file.

(Or would you even go so far as allowing additional `using`s just for the XML documentation comments?)

### .NET BCL type names vs. C# type keywords. ###
Do you have a prefererence for either `<see cref="Single"/>` or `<see cref="float"/>`?

Again, I recommend the latter: It's shorter, it's less confusing when comparing the comment with the code that they document, and Visual Studio's IntelliSense will automatically transform .NET type names to type keywords anyway (at least in the C# code editor).

### References to closed generic types ###
References such as `<see cref="IEnumerable{JToken}"/>` don't actually work as expected. Visual Studio will just display them as `IEnumerable<T>` in tooltips. And I'm pretty sure Sandcastle will also just substitute a link to the open generic type, `IEnumerable<T>`. (See also [this online API refence page](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JObject_PropertyValues.htm).)

I suggest doing what some code files in the Linq subfolder already do: replace `<see cref="IEnumerable{JToken}"/>` with `<see cref="IEnumerable<T>"/> of <see cref="JToken"/>`.

### Adding references where they are currently missing. ###
We already discussed that above. However, one remaining question is how far this should go. For example, given a parameter documentation, `A string containing JSON text.`, should this be turned into `A <see cref="string"/> containing JSON text.`? To be honest, I don't see much added value in that.

**Comment by stakx** [comment]
@JamesNK, I'm preparing another PR that cleans up the formatting of `true`, `false`, `null` literals in comments. This can be done several ways:

* By marking them up with `<c>…</c>`. Simple enough.
* By using the more semantic [`<see langword="…"/>`](http://stackoverflow.com/q/693196/240733). Using this would be nice because the literals will be highlighted in VS IntelliSense tooltips, but they might possibly have consequences with Sandcastle Help File Builder. Your Sandcastle project or templates might possibly have to be modified a little... I cannot check whether that's necessary.

Do you have a preference?

**Comment by JamesNK** [comment]
2 please. If it ever needs to change then doing a fine and replace on `<c>true</c>`, et al shouldn't be difficult.

**Comment by stakx** [comment]
OK, that sounds reasonable.

**Comment by stakx** [comment]
@JamesNK, we're getting there. The next PR's goal will be to add missing `<see cref="..."/>` references, or fixing incorrect ones. I need your feedback on three issues here.

### `<see cref="Nullable{Decimal}"/>` vs. <br> `<see cref="Nullable{T}"/> of <see cref="Decimal"/>` ###

Referencing closed generic types with `<see cref="..."/>` is impossible. `Nullable{Decimal}` will be rendered as "**Nullable&lt;T&gt;**". (`Decimal` gets interpreted as the generic type parameter name, not as the type argument, and it's the original type parameter name that is used in the output).

Are you OK with having these changed to `<see cref="Nullable{T}"/> of <see cref="Decimal"/>` &mdash; which would be rendered as "**Nullable&lt;T&gt; of decimal**"?

(You're already doing this in some `Newtonsoft.Json.Linq` files; MSDN does something similar, see e.g. [`String.Concat(IEnumerable<string>)`](https://msdn.microsoft.com/en-us/library/dd784338.aspx): "**IEnumerable&lt;T&gt; whose generic type argument is string**".)

### `<see cref="T:System.Object>"` vs. <br> `<see cref="System.Object"/>` ###

The former notation with `T:`, `M:`, etc. prefixes are called [member ID strings](https://msdn.microsoft.com/en-us/library/fsbx0t7x.aspx), and they are not checked for correctness by the compiler.

In a few cases, actively evading compiler checks can helpful (such as when referencing `ISerializable` which is only available in the full .NET Framework, but not in e.g. Portable Class Libraries). But in the general case, it would seem good to have the compiler check references.

Replacing member ID strings with proper, checked references (where it can be done without any risk) is not strictly necessary, but I'm happy to do this. May I go ahead, or should I do only the required minimum?

### `<see cref="long"/>` vs. <br> `<see cref="Int64"/>` ###

This isn't strictly necessary, either &mdash; the rendered output will be the same &mdash;, but using C# type keywords would make it less confusing to look at the source code:


```csharp
/// ...
/// <param name="value">The <see cref="Int64"/> value to write.</param>
public override void WriteValue(long value)
{
    base.WriteValue(value);
}
```

It would be easier to see `long` everywhere, instead of seeing `long` in one place and `Int64` in the other. May I go ahead and replace .NET type names with C# keywords (where possible)?

**Comment by JamesNK** [comment]
1. Generic type crefs

I like `<see cref="Nullable{T}"/> of <see cref="Decimal"/>`. I took a look around MSDN and I found a slightly different ways of doing it in a few places, e.g. https://msdn.microsoft.com/en-us/library/bb342604, but I think having it consistent with other generic comments would be good.

2. Sure go ahead. If any changes create errors when building docs with Sandcastle then I'll undo those particular changes.

3. I like .NET type names in crefs.

**Comment by stakx** [comment]
OK cheers. That's how I'll do it then.

**Comment by stakx** [comment]
OK, I submitted a PR with changes in the manner requested.

I would have one last PR afterwards, which would remove the references to "underlying streams" in the `JsonReader` / `JsonWriter` (and derived) classes' comments. Apart from simply shortening the comments, I can see two alternative wordings here:

* **"(underlying) source"** (in the case of the reader classes) & **"(underlying) sink"** (for the writer classes). This sounds very generic, but would be correct in all instances.
* **"underlying reader"** / **"underlying writer"**. This is more specific and usually correct, except for the `JTokenReader` & `JTokenWriter` classes, which work on top of `JToken` instead of `TextReader`/`TextWriter`.

Do you find one of these alternatives acceptable?

**Comment by JamesNK** [comment]
For JsonReader and JsonWriter I think source and destination are best. They could be anything in an implementation. Reader and writer only makes sense in the context of JsonTextReader/JsonTextWriter.

**Comment by stakx** [comment]
The PR I have just submitted is possibly the last one for now, and I'm happy to close this issue afterwards. However, if you have anything else that needs to be checked, made more consistent, rephrased, etc., please let me know. I'd be happy to contribute more work to Json.NET.

**Comment by JamesNK** [comment]
Sure. You've already thought of more fixes that I could ever have. If you think of any other changes run them by me. I'm probably happy to merge them.

**Comment by stakx** [comment]
Cheers... will do if I find anything else!
