### ISSUE TITLE
Any breaking changes in 9.0.1?

### ISSUE THREAD

**Issue by memark** [JamesNK/Newtonsoft.Json#1099]
As I understand it, this project now uses semantic versioning (yey!), suggesting that a new major version means breaking changes. Is this correct?

I'm currently upgradering a large number of projects from version 7 to version 9.
In the release notes for 8.0.1 I see a number of items labeled `Change`, which I then assume means a breaking change. For version 9.0.1, however, there are no such items. Does this mean there are no breaking changes? (And in that case, why was the major version bumped?)

**Comment by JamesNK** [comment]
Major version was bumped because of the .NET standard build. There is no rule that you can't increase the major version without a breaking change.

**Comment by memark** [comment]
Thank you for your reply. I'm sorry if my last question offended you in any way. You are absolutely correct, an author is free to bump the major version whenever they like. You can bump it on every build if you like. (But that would of course defy the whole purpose of SemVer in the first place.)

With that out of the way, could you please confirm that no breaking changes were introduced in version 9?

**Comment by JamesNK** [comment]
I'm not offended. Some people take semver Seriously.

No breaking changes.

**Comment by memark** [comment]
Thanks. Keep up the good work!
