### ISSUE TITLE
X.Parse() parse some invalid JSON

### ISSUE THREAD

**Issue by dehghani-mehdi** [JamesNK/Newtonsoft.Json#1103]
Hi,
First thanks for your amazing job.

Imagine following data: `{A:{"B": 1}}`

If you try to `Parse` that using `JSON.Parse` _in browser's console_ or using [jsonlint](http://jsonlint.com/), you can see both return __error__, but `JContainer.Parse` or `JObject.Parse` can parse that without any error.

This is not bad (maybe), but it's not sync with `JavaScript` parser and maybe you should do same as them done.

Thank you.
Mehdi

**Comment by JamesNK** [comment]
Json.NET is liberal in what it accepts.

**Comment by dehghani-mehdi** [comment]
I think it's not good enough reason, JSON is for JS & browser & what Json.NET can parse, they can not.
