### ISSUE TITLE
JsonConvert double precision using ToString("R") vs. ToString("G17")

### ISSUE THREAD

**Issue by jharonfe** [JamesNK/Newtonsoft.Json#1104]
Msdn reports that there can be double precision loss using ToString("R") when compiled under x64 or anycpu. Read [here](https://msdn.microsoft.com/en-us/library/kfsatb94(v=vs.110).aspx). 

Would it be preferable in the JsonConvert ToString(double value) methods to use ToString("G17") ? See the code snip below.

```cs
        public static string ToString(double value)
        {
            return EnsureDecimalPlace(value, value.ToString("R", CultureInfo.InvariantCulture));
        }

        internal static string ToString(double value, FloatFormatHandling floatFormatHandling, char quoteChar, bool nullable)
        {
            return EnsureFloatFormat(value, EnsureDecimalPlace(value, value.ToString("R", CultureInfo.InvariantCulture)), floatFormatHandling, quoteChar, nullable);
        }
```

**Comment by JamesNK** [comment]
If "R" isn't used then round tripping a double.MaxValue will cause an error on deserialization.

**Comment by jharonfe** [comment]
@JamesNK When I test roundtripping in Json.NET with double.MaxValue but replace ToString format "R" with "G17" I did not encounter an issue. 

Can you be more specific about the error you encountered ?

**Comment by tarekgh** [comment]
@JamesNK, I have a question regarding what can break in the Json.NET if changed to use G17 instead of "R"? I am asking this question because there are some thoughts from the Net Core to have "R" always format the string with 17 significant digits (instead of 15). We want to evaluate if such change can break Json.NET or any other serialization.

Look at https://github.com/dotnet/coreclr/pull/13140 if you want to see the discussion there

**Comment by JamesNK** [comment]
Json.NET converts doubles to a string with ToString("R"). If its output can no longer be parsed with double.TryParse then it will break a lot of people

**Comment by JamesNK** [comment]
At least I believe so. I haven't done extensive testing.

**Comment by tarekgh** [comment]
double.TryParse should parse the output of ToString("R") even after changing it to use 17 significant digits. so the concern is not about the parsing back.

Is there a way from your side to experiment changing "R" to G17 and run your tests with this change and look if there is anything can break there?
if you don't have time for that, you may tell me how I can do this change, build and run the tests and I'll try to do it.

**Comment by JamesNK** [comment]
Fork and change the ToString("R")'s here - https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonConvert.cs#L256-L299
