### ISSUE TITLE
Enum is not correctly deserialized with TypeNameHandling.Auto

### ISSUE THREAD

**Issue by leonsoft** [JamesNK/Newtonsoft.Json#1107]
When there is an enum field in an object, and the converter's setting is TypeNameHandling.Auto, I am expecting it to be deserialized correctly. But it's returned as integer. 

If I specifiy StringEnumConverter, it's deserialized as string instead of enum.

Basically, I think it should be serialized as string (with namespace info) and deserialized as enum like some java json solutions like gson/jackson does. This is a muture approach.

The test class is (note it's declared as object):
```
    public class Animal
    {
        public object name = "Animal";
        public object type = Type.DOG;
    }
```

**Comment by JamesNK** [comment]
Sorry this will never change for backwards compatibility reasons
