### ISSUE TITLE
Add support for tokens attributes comparison for JPath parsing and SelectToken/SelectTokens methods

### ISSUE THREAD

**Issue by dalligieri** [JamesNK/Newtonsoft.Json#1108]
This code:

`var path = "$..products[?(@.price > @.old_price)].price";
 var token = new JArray();
 var selected= token.SelectTokens(path);`

causes 'Newtonsoft.Json.JsonException' with message "Could not read query value." in JPath.ParseValue
After inspection of JPath code for ParseExpression/ParseValue seems they lacks support for such attributes comparison while current JSONPath syntax and implementation for other languages (e.g. JavaScript) supports such feature well.

While such filtration possibly may be implemented via LINQ Where() extension method on tokens, there are cases when we use pure JSONPath and lack of this feature is huge problem.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/4099870390838843ea562ed8d662c03ee8d59201
