### ISSUE TITLE
Update CodePlex Home page to mention the move to GitHub

### ISSUE THREAD

**Issue by JamesMGreene** [JamesNK/Newtonsoft.Json#111]
I was busy adding to discussions and filing new issues over on the [CodePlex site for JSON.NET](https://json.codeplex.com/) when I finally looked at the commit history, then peaked at the README to discover that the codebase had been moved over to GitHub (good choice, by the way).

Anyway, please update the CodePlex Home page as well to mention that the project has been moved here so that others can avoid the same confusion if they don't seek out the README file.

Thanks!

**Comment by JamesMGreene** [comment]
Ping! :point_up:

**Comment by JamesNK** [comment]
Done :metal:
