### ISSUE TITLE
DateTimeOffset not parsed correctly when using Parse method

### ISSUE THREAD

**Issue by yorek** [JamesNK/Newtonsoft.Json#1110]
using the Parse method the DateTimeOffset offset value is discarded and instead the local offset is used.

Here's a repro using v 9.0.1

```
static void Main(string[] args)
        {
            string dateTimeOffsetToTest = "2016-08-12T15:00:00-05:00";

            string json = "{ 'datetimeoffset' : '" + dateTimeOffsetToTest  + "' }";
            var jo = JObject.Parse(json);

            DateTimeOffset dto = DateTimeOffset.ParseExact(dateTimeOffsetToTest, "yyyy-MM-dd'T'HH:mm:ss.FFFK", CultureInfo.InvariantCulture);

            Console.WriteLine($"Parsed DateTimeOffset {jo.ToString()}");
            Console.WriteLine($"Parsed Json DateTimeOffset {dto.ToString()}");

            Console.ReadLine();
        }
```

**Comment by yorek** [comment]
It works correctly when using JsonConvert.DeserializeObject with correct JsonSerializerSettings for

**Comment by JamesNK** [comment]
You need to configure date text to be read as DateTimeOffset when loading the JObject

**Comment by yorek** [comment]
Yes, using the 

`JsonConvert.DeserializeObject<Jobject>(...)`

right? I'm doing that, and it works fine, still using .Parse results into an unexpected behavior IMHO: if have  datetimeoffset data into JSON I would expect it to be correctly parsed by default and not only if I specifically ask so.
Anyway, if this is the expected behavior my suggestion is to mention it in documentation is it is really tricky.
Thanks!

**Comment by boyarincev** [comment]
Currently, you can use the `JsonObject.Load()` method by passing a correctly configured JsonRider into it. Here, for example, is a corrected version of the [Parse method](https://github.com/JamesNK/Newtonsoft.Json/blob/13.0.3/Src/Newtonsoft.Json/Linq/JObject.cs#L468):

```
static JObject ParseWithDateTimeOffset(string json, JsonLoadSettings? settings)
{
    using (JsonReader reader = new JsonTextReader(new StringReader(json)))
    {
        reader.DateParseHandling = DateParseHandling.DateTimeOffset;
        JObject o = JObject.Load(reader, settings);

        while (reader.Read())
        {
            // Any content encountered here other than a comment will throw in the reader.
        }

        return o;
    }
}
```
