### ISSUE TITLE
Dictionary serialization ignores CamelCasePropertyNamesContractResolver for keys

### ISSUE THREAD

**Issue by KevinDockx** [JamesNK/Newtonsoft.Json#1115]
**Version info**: ASP.NET Core with JSON.NET 9.0.1, default options (so CamelCasePropertyNamesContractResolver is used)

**Issue**: when returning an IActionResult from IDictionary<string,object> or from an ExpandoObject (which casts to that) from an action, the serializer doesn't camelCase the field names.  Eg, an entry with key "Name" and value "Kevin" comes out as { Name: "Kevin" }.  I'd expect this to come out as { name: "Kevin" }, as it would when serializing a regular object with a Name property. Am I missing something, is this by default/can I override it, or is this a bug?

**Comment by JamesNK** [comment]
ASP.NET Core doesn't use CamelCasePropertyNamesContractResolver

**Comment by KevinDockx** [comment]
Thanks - I didn't realize that.  Changing the default converter to the CamelCasePropertyNamesContractResolver works :)
