### ISSUE TITLE
Expected BEGIN_OBJECT but was BEGIN_ARRAY

### ISSUE THREAD

**Issue by mateusleonardi** [JamesNK/Newtonsoft.Json#1116]
Hello,

I'm working with API written in ASP .NET C# but my Android application is getting this error: "Expected BEGIN_OBJECT but was BEGIN_ARRAY".

Is there anyway to set some configuration in the convert and add the class type name to the json?

Thanks in advance.

**Comment by JamesNK** [comment]
That doesn't look like a Json.NET error, also ask questions like this on SO.
