### ISSUE TITLE
Enum is not correctly deserialized with TypeNameHandling.Auto

### ISSUE THREAD

**Issue by liweys** [JamesNK/Newtonsoft.Json#1117]
Reopened.  Note this is not a compatibility issue. It's a bug that does not work at all.

When there is an enum field in an object, and the converter's setting is TypeNameHandling.Auto. After serializing,  it should be able to be deserialized correctly back, especially for a primitive type (enum).  But it's deserialized as integer now. If I specifiy StringEnumConverter, it's deserialized back as string.

The test class is (note it's declared as object):

```
    public class Animal
    {
        public object name = "Animal";
        public object type = Type.DOG;
    }
```

**Comment by leonsoft** [comment]
So theare are 2 issues, 1st is to deserialize what you serialized correctly.   This is a minimal requirement.

Let's fix the first one firt.

But I do not agree with the back compatibility reason either. (1) If some one has legacy data serialized by json.net, he can use the old version to do serialization. Or write an adapter with the new version. That's not a problem.  (2)  Keeping it may be compatible with legacy data serialized by json.net, but it's not compatiable with other system (like javascript, or jackson etc). 

So there are 2 principles whether you do change it or not, firstly, what is the correct thing. 2ndly, which gives user more benefits. Both asnwer is: change it.

**Comment by svdHero** [comment]
Any progress on this? I want to use `TypeNameHandling.Auto` or `TypeNameHandling.All` for backup/restore functionality in my software. However, when using `StringEnumConverter`, the enums are not deserialized properly but end up as `string` variables instead.

What's the easiest way to fix this?
