### ISSUE TITLE
JsonConvert.DeserializeObject  error

### ISSUE THREAD

**Issue by icecooly** [JamesNK/Newtonsoft.Json#1123]
//my testcase 
//
public class ResponseMessage{
		public int ri;
		public string si;
		public long d;
		public int sc;
		public string sm;
		public Dictionary<string,object> rsp;
}
//
public class ZjhAccount {
	public int id;
	public string name ;
	public long createTime ;
}
//
public class JSONUtil {
		public static string ToJson(object obj){
			return JsonConvert.SerializeObject(obj);
		}
		public static T FromJson<T>(string json){
			return (T)JsonConvert.DeserializeObject<T>(json);
		}
}
//Unity3d Scene

void Start () {
  ResponseMessage rsp = new ResponseMessage ();
  rsp.ri = 1;
  rsp.sc = 2;
  rsp.sm="";
  rsp.rsp = new Dictionary<string, object> ();
  ZjhAccount account = new ZjhAccount ();
  account.id = 1;
  account.name="test";
  rsp.rsp.Add ("account", account);
  //
  string json = JSONUtil.ToJson (rsp);//it's ok
  //
  ResponseMessage newRsp = JSONUtil.FromJson<ResponseMessage>(json);// mac pc is ok.but running  from iphone error happen
 exception:
   
![image](https://cloud.githubusercontent.com/assets/3367934/21576811/4942b34e-cf79-11e6-8cfa-5f96511829de.png)

}

**Comment by icecooly** [comment]
i am using Json90r1/Bin/Net20/Newtonsoft.Json.dll

**Comment by JamesNK** [comment]
I honestly don't know, I've never done any iphone development. I suggest asking on StackOverflow.

**Comment by icecooly** [comment]
solved   need add link.xml    thanks
