### ISSUE TITLE
Incorrect ISO Datetime handling when deserializing with XmlNodeConverter

### ISSUE THREAD

**Issue by wzychla** [JamesNK/Newtonsoft.Json#1129]
One of the infrastructure components we use uses Newtonsoft's serializer internally on elements of **XElement** type. It seems that the **XmlNodeConverter** incorrectly parses datetimes - it doesn't preserve the ISO format but only under certain conditions.

The issue has been narrowed to a simple code:

```c#
    public class Program
    {
        public static void Main( string[] args )
        {
             Model model = new Model();

            // this works
            model.Document = new XElement( "Value" )
            {
                Value = "2001-01-01T11:11:11"
            };

            // this doesn't work as intented, comment out the above and uncomment this
            // description of the issue below the code
            //model.Document = new XElement( "Value", new XAttribute( "foo", "bar" ) )
            //{
            //    Value = "2001-01-01T11:11:11"
            //};

            var serializer = JsonSerializer.Create( new JsonSerializerSettings
            {
                Converters = new List<JsonConverter>( new[] { new XmlNodeConverter() } )
            });

            var json = new StringBuilder( 1024 );

            using (var stringWriter = new StringWriter( json, CultureInfo.InvariantCulture ))
            using (var jsonWriter = new JsonTextWriter( stringWriter ))
            {
                jsonWriter.Formatting = Newtonsoft.Json.Formatting.None;
                serializer.Serialize( jsonWriter, model );

                // debug output to see the json
                Console.WriteLine( json.ToString() );
            }

            using (var stringReader = new StringReader( json.ToString() ))
            using (var jsonReader = new JsonTextReader( stringReader ))
            {
                var document = (XDocument)serializer.Deserialize( jsonReader, typeof( XDocument ) );

                // debug output to see the xml
                Console.WriteLine( document.ToString() );
            }

            Console.ReadLine();
        }
    }

    public class Model
    {
        public XElement Document { get; set; }
    }

```

When run this one produces expected output

```
{"Document":{"Value":"2001-01-01T11:11:11"}}
<Document>
  <Value>2001-01-01T11:11:11</Value>
</Document>
```

Note that the DateTime format is preserved correctly after deserializing.

However, when the XElement **contains any attributes of text type**, the deserializer incorrectly infers to the node's value type, treating the value as text, regarding of the actual type.

To reproduce, comment out the section marked as "this works" and uncomment the section "this doesn't work" below. This time the XElement contains a single attribute, **foo : bar**.

When run, the code now produces

```
{"Document":{"Value":{"@foo":"bar","#text":"2001-01-01T11:11:11"}}}
<Document>
  <Value foo="bar">2001-01-01 11:11:11</Value>
</Document>
```

Note the attribute is parsed correctly (**foo : bar**), however node's value is now treated as text (**#text**) and falling into wrong clause in the xml node appending section, the clause that uses a default **.ToString()**. And instead of **2001-01-01T11:11:11** we get **2001-01-01 11:11:11**.

Unfortunately, this is critical for us at the moment. In our case the attribute is automatically generated by an external serializer and it just defines the value type (**xsi:type="xsd:dateTime"**) which, together with datetime of incorrect format (**2001-01-01 11:11:11** without the ISO's **T** between the two segments) makes the data unusable by the default .NET's XML deserializer.

A temporary yet costly workaround for us would be to rewrite the code around the deserializer to not to use the faulty **XmlNodeConverter**. 

I would however be grateful for a confirmation of the issue and a fix in near future. 
Regards, 
Wiktor

**Comment by dbc2** [comment]
A similar problem was reported on stackoverflow: [Newtonsoft.Json JsonConvert to XmlDocument date formatting inconsistent when elements have attributes](http://stackoverflow.com/q/40589721/3744182).  

A partial workaround was included in the answer, as well as an analysis of the cause of that problem in [`XmlNodeConverter.DeserializeValue()`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/XmlNodeConverter.cs#L1497).  I don't think the questioner ever reported the problem here though.

**Comment by wzychla** [comment]
Great, exactly the same issue and it seems it hasn't been officially reported here, has it?

Anyway, the recommended workaround sounds great with the only trouble for me that I don't use the serializer directly from my code but rather, I use a third party stack (MassTransit) which uses the serializer internally. By just swapping the faulty Newton with a correct one and rebinding the assembly in my stack I could get the correct behavior for free. Now, even with the possible workaround at hand, I'd have to dig into internals of the third party library to find a way to work around this simple issue. And still, I'd have to keep in my mind to possibly remove the workaround when a fix is officially applied here.

Interesting thing is that in your SO post you even seem to have a working solution. Any chances for an officiall pull request to close this issue then? (or maybe James just reads this :)

Regards.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/56e3d7575bc075cb7c5d1809607d98c81d49ad12
