### ISSUE TITLE
Provide a way of not closing brackets when an exception occurs during serialization.

### ISSUE THREAD

**Issue by kichalla** [JamesNK/Newtonsoft.Json#1134]
Related to https://github.com/aspnet/Mvc/issues/5413
On investigating the above issue we found that not closing the json writer in case of exceptions would result in any rented buffers to be not returned to the array pool. And any workarounds on MVC side to fix this seems to be dealing with internal details of Json.NET which feels incorrect.

Proposal:
Could `JsonSerializerSettings` expose an option to either close(default)/not-close the brackets on exception? Based on the option, could  `JsonSerializerInternalWriter` poison the state of the writer it's using so that the writer knows not to close the brackets since an exception has occurred?

@Eilon

**Comment by JamesNK** [comment]
I don't want to add a setting to `JsonSerializerSettings` for something so niche but I could add a flag to `JsonTextWriter`.

**Comment by kichalla** [comment]
That sounds good!

**Comment by Eilon** [comment]
@JamesNK cool. Do you see this feature making its way in at any point in the near future? Anything we can do to help?

**Comment by JamesNK** [comment]
It isn't difficult, just a bool property to control what happens when JsonTextWriter is disposed/closed.

I don't know when the next release will be - the number of changes is turning out to be huge and there isn't a pressing need. I'll probably wait until after VS2017 is out and I can move over to the csproj.

**Comment by JamesNK** [comment]
Done - https://github.com/JamesNK/Newtonsoft.Json/commit/55afb9aa72a07494aa35015dd2a29f7e9643127f

FYI I might change the property name if I can think of something I like more

**Comment by Eilon** [comment]
@JamesNK very cool, thanks!
