### ISSUE TITLE
Provide a Way to overwrite TypeInfo written to Json

### ISSUE THREAD

**Issue by jogibear9988** [JamesNK/Newtonsoft.Json#1135]
I use Json.Net for Serialization in a WCF Replacement. Works very well, but I Functions wich use IEnumerable Types. These are Serialized with a TypeInfo like this: System.Linq.Enumerable+WhereSelectListIterator`2

Now it would be good if I have a Callback, where I could change the Type written to the String.

I could fix it like this:

            s = Regex.Replace(s, "\"\\$type\"\\s*:\\s*\"System.Linq.Enumerable\\+WhereArrayIterator(.+?), System.Core\",", "\"$type\": \"System.Collections.Generic.List$1, mscorlib\",", RegexOptions.Singleline);
            s = Regex.Replace(s, "\"\\$type\"\\s*:\\s*\"System.Linq.Enumerable\\+WhereSelectListIterator`2\\[\\[.*\\],(.+?)\\], System.Core\",", "\"$type\": \"System.Collections.Generic.List`1[$1], mscorlib\",", RegexOptions.Singleline);

but I want to Fix the write, so I got a better Performance

**Comment by JamesNK** [comment]
http://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm
