### ISSUE TITLE
Readonly Objects and PreserveReferencesHandling issue.

### ISSUE THREAD

**Issue by BenJury** [JamesNK/Newtonsoft.Json#1140]
The serialisation of readonly objects seems to not work properly with the PreserveReferencesHandling.All setting.

The serialiser won't check for the duplication of a reference to an object until it encounters a reference that is read/write. I believe the intended functionality is that the serialiser should understand duplicate object references even if the reference is readonly, and that any ordering shouldn't effect the serialisation.

Using 9.0.0.0 from nuget, we see the following.. (We saw this in v7 also and upgraded to check.)

a_ReadWrite_a, b_ReadWrite_a2 and c_Read_a are all set correctly.

However d_Read_b and e_Read_b2 appear to have been ignored by the serialiser, while f_ReadWrite_b and g_ReadWrite_b2 are fine.

Edit: This is using PreserveReferencesHandling = PreserveReferencesHandling.All

C# Classes:

    public class Example
    {
        private static Referenced _referencedA = new Referenced("Static-A");
        private static Referenced _referencedB = new Referenced("Static-B");

        public Referenced a_ReadWrite_a = _referencedA;
        public Referenced b_ReadWrite_a2 = _referencedA;
        public readonly Referenced c_Read_a = _referencedA;

        public readonly Referenced d_Read_b = _referencedB;
        public readonly Referenced e_Read_b2 = _referencedB;
        public Referenced f_ReadWrite_b = _referencedB;
        public Referenced g_ReadWrite_b2 = _referencedB;
    }

    public class Referenced
    {
        public Referenced(string name) { Name = name; }
        public string Name { get; set; }
    }

JSON:

	{
		"$id": "1",
		"Data": {
			"$id": "2",
			"a_ReadWrite_a": {
				"$id": "3",
				"Name": "Static-A"
			},
			"b_ReadWrite_a2": {
				"$ref": "3"
			},
			"c_Read_a": {
				"$ref": "3"
			},
			"d_Read_b": {
				"Name": "Static-B"
			},
			"e_Read_b2": {
				"Name": "Static-B"
			},
			"f_ReadWrite_b": {
				"$id": "4",
				"Name": "Static-B"
			},
			"g_ReadWrite_b2": {
				"$ref": "4"
			}
		}
	}

**Comment by BenJury** [comment]
Had a quick look in the code and there is a comment that seems to specifically mention readonly fields. 

You can see why readonly fields that had previously been parsed fall through here.

However should the ability to be deserialised change how we serialise an object? If so, surly all readonly fields should be ignored. (Obviously that would not ideal...)

My guess is the member.Writable in the if should be removed?

Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:

        private void WriteObjectStart(JsonWriter writer, object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
        {
            writer.WriteStartObject();

            bool isReference = ResolveIsReference(contract, member, collectionContract, containerProperty) ?? HasFlag(Serializer._preserveReferencesHandling, PreserveReferencesHandling.Objects);
            // don't make readonly fields that aren't creator parameters the referenced value because they can't be deserialized to
            if (isReference && (member == null || member.Writable || HasCreatorParameter(collectionContract, member)))
            {
                WriteReferenceIdProperty(writer, contract.UnderlyingType, value);
            }
            if (ShouldWriteType(TypeNameHandling.Objects, contract, member, collectionContract, containerProperty))
            {
                WriteTypeProperty(writer, contract.UnderlyingType);
            }
        }

**Comment by JamesNK** [comment]
Basically non-writable JSON will be skipped which is why $id is only included on the first writable property, and only instances after that will be referenced with $ref. That is why the member.Writable test is required.

With PreserveReferencesHandling the order matters, and the serialized JSON affects the deserialized result.

**Comment by BenJury** [comment]
I don't understand what 'non-writable JSON' means, JSON doesn't have the notion of anything being 'non-writable'.

Besides, read-only objects are not skipped, they still gets serialised. So the result is a less efficient serialisation.

**Comment by BalassaMarton** [comment]
@JamesNK Please consider changing this to the expected behavior. Read-only properties should be serialized the same way. This bug breaks every use case when the produced JSON is deserialized into a type that is different from the serialized type, in our case, a JavaScript object or a generated proxy type. I don't see the point in serializing these properties, but only breaking the references.
