### ISSUE TITLE
Is there an equivalent to MongoDB's BSON class map in Newtonsoft's Json.NET?

### ISSUE THREAD

**Issue by gh3x78E** [JamesNK/Newtonsoft.Json#1160]
(I have asked this question on stackoverflow, but I guess this might be the better place to post...)

I am using heavily `[JsonConstructor]` because it enables me to deserialize values into read-only or private members. Yet, I don't really like that approach because it makes my data classes depend on Json.NET which actually is no good architecture. 

Even though MongoDB offers as well an attribute called `[BsonConstructor]`, it additionally has a feature called [Class Map](http://mongodb.github.io/mongo-csharp-driver/2.0/reference/bson/mapping/) Registration which allows for declaring what to call on deserializing to .NET types without the need of annotating them with specialized attributes:

    BsonClassMap.RegisterClassMap<Person>(cm =>
    {
      cm.MapCreator(p => new Person(p.FirstName, p.LastName));
    });

Is there a way to do something alike in Newtonsoft's Json.NET?

**Comment by JamesNK** [comment]
No there isn't. You could create something that hooks into DefaultContractResolver to avoid attributes though.

**Comment by gh3x78E** [comment]
Can you provide an exmple, please?
