### ISSUE TITLE
Only allow async methods on readers and writers from factory methods.

### ISSUE THREAD

**Issue by JonHanna** [JamesNK/Newtonsoft.Json#1161]
As mentioned at https://github.com/JamesNK/Newtonsoft.Json/pull/1137#issuecomment-271442023

Currently we're taking the same approach to async versions of virtual methods as framework `TextReader` and `TextWriter` implementations; check if the class has been overridden and default to calling the non-async if it has been.

`XmlReader` and `XmlWriter` takes a different approach.

```C#
var xr = new XmlTextReader(streamReader); 
// Any async call will throw NotImplementedException() (NotSupported would be better IMO);

var xr = XmlReader.Create(streamReader); 
// Create was introduced with 2.0. Any async call call InvalidOperationException

var xr = XmlReader.Create(streamReader, new XmlReaderSettings{Async = false}); 
// Async property introduced with 4.5. Async methods work.
```

This wouldn't have been as reasonable for `TextReader` with many different implementations living in many different assemblies and the base class having to know about them to produce them from a factory, but it seems a reasonable approach to take in `Newtonsoft.Json`. It would enable all of the checks for being overridden to be removed, since the type returned would be `internal`.

Switching to this approach would have to be done soon though, before anyone has dependencies on the current behaviour.

**Comment by JamesNK** [comment]
Hmmm, I don't have a problem with the current implementation. I like the async methods just working.
