### ISSUE TITLE
Why does Deserialize<> allow for malformed JSON (with repro)?

### ISSUE THREAD

**Issue by dornstein** [JamesNK/Newtonsoft.Json#1162]
I am stunned -- but perhaps because I am uninformed -- that `JsonConvert.Deserialize<>()` will parse this malformed JSON without complaint:

    {"Items":  ["hello" "goodbye",]}

It appears to use some set of heuristics to make this work and in this one case I think did "the right thing."  But the fact that it did so silently is quite concerning as I don't know what I can trust for behavior.

Older versions of JSON.NET (6.x) throw an error, but newer versions (9.x) DO NOT.  Also, just using the non-generic version of Deserialize() will complain about the syntax error -- it's just the generic one that doesn't.

I tried to post a repro on dotnetfiddle but that doesn't work because dotnetfiddle always loads version 6.x of JSON.NET even if you ask for a different version.  (See https://dotnetfiddle.uservoice.com/forums/228764--net-fiddle-ideas/suggestions/10782315-load-the-specified-version-of-json-net-rather-than).  

So, here is a full repro (including code that prints out the version of Netwonsoft.Json.Dll being used).  It prints 2 (because it "successfully" parses the JSON) under the 9x versions of JSON.NET.  Under the 6.x ones it throws an error (as I think it should).

    using System;
    using Newtonsoft.Json;

    public class Program
    {
        public static void Main()
        {

            Console.WriteLine(typeof(JsonConvert).Assembly.GlobalAssemblyCache);
            Console.WriteLine(typeof(JsonConvert).Assembly.FullName);

            // I think this JSON is invalid because (1) it is missing a comma between the two values and (2) there is an extra comma at the end
            string json = @"{""Items"":  [""hello"" ""goodbye"",]}";

            // This deserialize is successful and produces an object with two values for Items
            Container result = JsonConvert.DeserializeObject<Container>(json);

            Console.WriteLine(result.Items.Length + " items");
        }
    }

    public class Container
    {
        public string[] Items { get; set; }
    }

Is this behavior documented and/or common practice?

Is there a way to force errors in this case?

**Comment by JamesNK** [comment]
JsonTextReader accepts trailing commas. There isn't a setting to change it up but you could role your own stricter JsonReader implementation.
