### ISSUE TITLE
Centralize feature <> platform mapping

### ISSUE THREAD

**Issue by fgreinacher** [JamesNK/Newtonsoft.Json#1165]
(Left-over from #1146)

I do not like how we have to list each and every constant in each csproj. It would be great to have something like a shared props file that lists all available features and the platform each of them is supported on. Will do a quick prototype so that you see what I'm thinking of.

@JamesNK I'll take care of that, can you assign the issue to me?

**Comment by JamesNK** [comment]
I don't understand what you mean. Could you go into a little more detail?

**Comment by fgreinacher** [comment]
I do not like how we have to list each and every constant in each csproj. It would be great to have something like a shared props file that lists all available features and the platform each of them is supported on. Will do a quick prototype so that you see what I'm thinking of.

**Comment by JamesNK** [comment]
Ok. Ideally the projects will be able to be merged into one csproj with VS2017. I think it is best to wait until we can see what that will look like before getting too fancy with msbuild.

**Comment by fgreinacher** [comment]
I think this is not relevant anymore :)
