### ISSUE TITLE
Get rid of csproj <-> project.json duplication (for pcls)

### ISSUE THREAD

**Issue by fgreinacher** [JamesNK/Newtonsoft.Json#1166]
(Left-over from #1146)

@JamesNK I'll take care of that, can you assign the issue to me?

**Comment by JamesNK** [comment]
I don't understand what you mean. As soon as VS2017 is RTM then I'll switch from project.json back to csproj.

**Comment by fgreinacher** [comment]
For the PCLs we currently have to define the constants in the pjs and in the csprojs. But of course this won't be necessary when everything is csproj again. Closing this.
