### ISSUE TITLE
Cascade of usings of StringReader and JsonTextReader throws CA2202 warning

### ISSUE THREAD

**Issue by gh3x78E** [JamesNK/Newtonsoft.Json#1167]
I am getting the managed code analysis warning [CA2202: Do not dispose objects multiple times](https://msdn.microsoft.com/en-us/library/ms182334.aspx) for the following code:

    using (var stringReader = new StringReader(jsonRepresentation))
    using (var jsonTextReader = new JsonTextReader(stringReader))
    {
      JsonSerializer serializer = new JsonSerializer();
      serializer.DateParseHandling = DateParseHandling.DateTimeOffset;
      return serializer.Deserialize(jsonTextReader, type);
    }

The error message says: Object 'stringReader' can be disposed more than once in method 'Json.Deserialize(string, Type)'. To avoid generating a System.ObjectDisposedException you should not call Dispose more than one time on an object.

Is this some internal problem of JsonTextReader?

**Comment by fgreinacher** [comment]
No, this rule is mostly considered useless: http://stackoverflow.com/questions/3831676/ca2202-how-to-solve-this-case/3839419#3839419
