### ISSUE TITLE
Additional information: Unexpected character encountered while parsing value: j. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Offnix** [JamesNK/Newtonsoft.Json#1169]
It fails to deserialize/prase this json, ive tried multiple combinations with different methods to try and make this work but nothing seems to do it...

The code im using
`WebClient wc = new WebClient();
            var json = (JObject)JsonConvert.DeserializeObject(wc.DownloadString("http://services.runescape.com/m=website-data/playerDetails.ws?names=[%22" + Username.Replace(" ", "%20") + "%22]&callback=jQuery000000000000000_0000000000&_=0"));`

the json its trying to deserialize...
`jQuery000000000000000_0000000000([{"isSuffix":true,"recruiting":false,"name":"Sudo Bash","clan":"Linux Overlord","title":"the Troublesome"}]); `

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#question
