### ISSUE TITLE
JsonTextWriter does not expose access to the TextWriter

### ISSUE THREAD

**Issue by kccarter76** [JamesNK/Newtonsoft.Json#1170]
I am trying to implement a solution that would serialize a circular reference to a specific depth. I have tried the other solutions but it makes the problem worse with the object substitution. if the JsonTextWriter could expose public access to the base text writer.  I could easily wrap the JsonWriter object with a JsonTextWriter that was aware of the current depth.

**Comment by JamesNK** [comment]
Not exposing the internal reader/writer is intentional. If you want to have a reference to the internal reader/writer then you will have to capture it when JsonTextReader/JsonTextWriter is created.

**Comment by kccarter76** [comment]
after trying a few things and failing. I succeeded with the implementation of a JsonConverter. the depth is controlled via the serializer settings maxdepth property with a default of 1. That has worked out very well and is a solution for resolving circular reference serialization.
