### ISSUE TITLE
JsonConvert.ToString(DateTime) returns quoted string

### ISSUE THREAD

**Issue by tpluscode** [JamesNK/Newtonsoft.Json#1173]
Calling `JsonConvert.ToString()` with most (all?) kinds of primitive types returns a string representation thereof. 

The weird exceptions are `DateTime` and `DateTimeOffset`, which are encased in double quotes (at least when setting `DateFormatHandling = DateFormatHandling.IsoDateFormat`

It strikes me as odd. Is this behavior by design?

**Comment by JamesNK** [comment]
Yes. It is a JS string.
