### ISSUE TITLE
JsonSerializerSettings.CheckAdditionalContent is fooled by comments followed by further content.

### ISSUE THREAD

**Issue by JonHanna** [JamesNK/Newtonsoft.Json#1182]
If `JsonSerializerSettings.CheckAdditionalContent` is `true` then any real content (that is, not a comment or insignificant whitespace) in the JSON read after an object that was deserialised should throw an exception.

However, if there is a comment between the JSON for the object deserialised and such erroneous content, the check does not find the content and the exception isn't thrown.

**Comment by matkoch** [comment]
I still see this behavior in 10.0.3. My understanding is, that if I would have a typo like "Prperty" but it's called "Property", then the deserialization should throw. Or not?

**Comment by liven-maksim-infotecs** [comment]
Can u provide an example?
