### ISSUE TITLE
Error with all versions after 6.0.8: "FindRibbons task failed unexpectedly"

### ISSUE THREAD

**Issue by Lux44** [JamesNK/Newtonsoft.Json#1187]
Project is a VSTO add-in for Excel that syncs data with Azure using MobileApps backend and offline sync capability. Newtonsoft.Json version 6.0.8 works and gives no errors. When I upgrade to any newer version, I get an error "FindRibbons task failed unexpectedly".

Is there a hope for a fix if I prepare a test case/project?

**Comment by JamesNK** [comment]
I don't know anything about the add-in. You should log a bug with that project.
