### ISSUE TITLE
Cannot parse JSON Date to .NET DateTime (MaxDate)

### ISSUE THREAD

**Issue by almeidaalex** [JamesNK/Newtonsoft.Json#1188]
Hello guys, I'´m in trouble and I need a help :)
I set the last valid date 9999-12-31 23:59:59 UTC, and when I send my json to the WebApi server, I got a invalid date in the object.

To simplify
I typed at browser console:
`var dt = new Date('9999-12-31 23:59:59')`
`Fri Dec 31 9999 23:59:59 GMT-0200 (E. South America Daylight Time)`
Look at the GMT above
So, when I type dt.toJSON() I got this result:
`+010000-01-01T01:59:59.000Z`

On the server side I got {1/1/0001 12:00:00 AM}, I believe that JSON Deserialize is unable do to that

And if I change the UTCHour like this `dt.setUTCHours(-1)` I've got a successful parsed DateTime, except by the hours, because I changed it.

I setup the Formatters with this settings:
`JsonFormatter.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Local;`
`JsonFormatter.SerializerSettings.DateParseHandling = DateParseHandling.DateTimeOffset;`
`JsonFormatter.SerializerSettings.DateFormatHandling = DateFormatHandling.IsoDateFormat;`

I don't know what I need to do.

**Comment by JamesNK** [comment]
DateTime doesn't support dates that big https://msdn.microsoft.com/en-us/library/system.datetime.maxvalue(v=vs.110).aspx
