### ISSUE TITLE
Split BSON out into Newtonsoft.Json.Bson

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json#1189]
Should be done after #1190 so the new repo can share common build script pattern.

- [x] Setup Newtonsoft.Json.Bson repo
- [x] Split BSON out into its own project + NuGet package + build
- [x] Mark Newtonsoft.Json.Bson classes as obsolete

**Comment by TylerBrinkley** [comment]
It does seem more natural that Bson related things be separated into its own package. Am I correct in assuming that Newtonsoft.Json.Bson will retain the MIT licensing?

**Comment by JamesNK** [comment]
Yes

**Comment by SchranzBulkGH** [comment]
00491722290229@webproxy.li
