### ISSUE TITLE
Consider adding SerializeObject/DeserializeObject direct support for Stream and byte[]

### ISSUE THREAD

**Issue by paulomorgado** [JamesNK/Newtonsoft.Json#1192]
To avoid creating a string that will only be used to create a `StreamReader` over it.

**Comment by JamesNK** [comment]
JsonConvert is only for converting to and from strings. Use JsonSerializer

**Comment by paulomorgado** [comment]
That's what I'm using. But `JsonConvert` provides one-liners where `JsonSerializer` doesn't.

It would be a way for developers to fall into the pit of success.

**Comment by JamesNK** [comment]
My view is if someone wants to use a stream directly then they are probably a power user and they should be able to figure out JsonSerializer. I don't want too many helper methods.
