### ISSUE TITLE
JsonTextReader.ParseNumber leads to error after ThrowReaderError

### ISSUE THREAD

**Issue by h-h-** [JamesNK/Newtonsoft.Json#1194]
I have the following test code:

	[TestClass]
	public class TestJsonDeserialize
	{
		public class MyClass
		{
			[JsonProperty("myint")]
			public int MyInt { get; set; }
			[JsonProperty("Mybool")]
			public bool Mybool { get; set; }
		}

		[TestMethod]
		public void Test1()
		{
			var errors = new List<string>();
			var json1 = "{\"myint\":1554860000,\"Mybool\":false}";
			var json2 = "{\"myint\":3554860000,\"Mybool\":false}";
			var i = JsonConvert.DeserializeObject<MyClass>(json2, new JsonSerializerSettings
			{
				Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
				{
					Debug.WriteLine(args.ErrorContext.Error.Message);
					errors.Add(args.ErrorContext.Error.Message);
					args.ErrorContext.Handled = true;
				}
			});
			Assert.IsTrue(errors.Count <= 1);
		}
	}

The call to JsonConvert.DeserializeObject produces 2 errors. One of them is expected, but the other not.
The errors are:

 - JSON integer 3554860000 is too large or small for an Int32. Path 'myint', line 1, position 19.
 - Unexpected token when deserializing object: Boolean. Path 'Mybool', line 1, position 34.

Why is there a 2nd error although the 1st error is marked as handled.
I already updated from Newtonsoft.Json 8.0.2 to 9.0.1 but it remains.
When passing the first string (json1 instead of json2), then no errors at all occur.

There is already an [answer](http://stackoverflow.com/a/41936844/1051244) on [Stackoverflow](http://stackoverflow.com/q/41935806/1051244) to this issue

**Comment by dbc2** [comment]
As shown in the referenced [answer](http://stackoverflow.com/a/41936844/1051244) this does look to be a bug in `JsonTextReader.ParseNumber(ReadType readType, char firstChar, int initialPosition)`.

**Comment by JamesNK** [comment]
I ran your test and it passed - a change since the last release has fixed the bug.

https://github.com/JamesNK/Newtonsoft.Json/commit/4d0545fe0e672ef2bb8f0d937e657ead97af0d4b
