### ISSUE TITLE
Customise number of decimals in ISO 8601 dates

### ISSUE THREAD

**Issue by joakimskoog** [JamesNK/Newtonsoft.Json#1197]
It seems like Newtonsoft is not following the ISO 8601 specification correctly when it comes to decimals. According to the [specification](https://en.wikipedia.org/wiki/ISO_8601#Times): 
> There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places *needs to be agreed to by the communicating parties.*

When we check how ISO dates are [handled](https://github.com/JamesNK/Newtonsoft.Json/blob/6d7c94e69fa2f52b91fb22972321cb9b51b9abed/Src/Newtonsoft.Json/Utilities/DateTimeUtils.cs#L682) we can see that trailing zeros are removed. As an example the date `2014-12-16T14:54:48.250` would be serialised into `2014-12-16T14:54:48.25` which can cause errors in the client application if it expects a certain number of decimals.

It would therefore be nice to have a way to set the number of decimals so that the communicating parties can agree on the number of decimal places.

**Comment by JamesNK** [comment]
Sure you can. JsonWriter.DateFormatString
