### ISSUE TITLE
Tips for a better JContainer Merge function

### ISSUE THREAD

**Issue by highfield** [JamesNK/Newtonsoft.Json#1198]
Just my two cents about the JContainer Merge method...
Let's say I have N JSONs (as JContainers). I can't alter them, but I need to merge them sequentially in order to get another JContainer. That is, if the "+" operator were as the merging one:
R = A+B+C+...
Now, if the given objects are from a list/enumeration, the currently implemented Merge method suits perfectly the goal. I could write something like:
```
            JObject o1 = JObject.Parse(@"{
                'FirstName': 'John',
                'LastName': 'Smith',
                'Enabled': false,
                'Roles': [ 'User' ]
                }");

            JObject o2 = JObject.Parse(@"{
                'Enabled': true,
                'Roles': [ 'User', 'Admin' ]
                }");

            var list = new[] { o1, o2 };
            var jresult = new JObject();
            foreach (var o in list)
            {
                jresult.Merge(o);
            }
```
However, it seems to me that the given objects are typically not in an iterable form, and that's getting the code as follows:
```
            var jresult = new JObject();
            jresult.Merge(o1);
            jresult.Merge(o2);
```
So, my first suggestion is to alter the Merge method's signature so that it will return the container itself. In that way, the code could be written "fluently" as follows:
```
            var jresult = new JObject();
            jresult.Merge(o1).Merge(o2);
```
However, I don't figure myself how much a similar change might impact with the existent code out there.

My second tip is about a static method for the JObject class, which could conveniently provide a compact way to merge one or more objects.
`            JObject jmerged = JObject.Merge(o1, o2);`
That is, the related signature should be the following, and the implementation is basically the loop seen above:
`public static JObject Merge(params object[] contents)`
I believe this second tip could be enough for a decent improvement without any dangerous interface changing as in the first tip.
Again, nothing important: just my personal tips for improving your awesome library.

**Comment by TylerBrinkley** [comment]
Changing `Merge` to a fluent method would be a breaking change as existing calls to `Merge` would fail to find the `Merge` method that returns `void` as the return type is part of the method signature.

As for the `params` `Merge` overload that would be possible but what if you want to specify the `JsonMergeSettings`. Would the `JsonMergeSettings` parameter be listed first?

**Comment by highfield** [comment]
Okay, let's drop the first tip.
About the second one...well, good catch! I totally forgot the optional settings as overload.
Well, as the `string.format` pattern, placing the settings as the very first argument of the signature might be a solution...but...honestly not so nice. I personally don't like it.
Moreover, what if the user need different settings along the array?

At this point, we should rethink completely the problem or drop it at all.
Question: is there a particular "settings" which could be considered as default for the quick-merge (but I honestly wouldn't able to bet a single cent on it)? I mean as the lodash's "merge" function behavior: https://lodash.com/docs/4.17.4#merge

At the moment I don't have any better idea. If you have anything in mind useful, otherwise let's drop the thread at all.

**Comment by TylerBrinkley** [comment]
Yeah, I don't like putting the `JsonMergeSettings` parameter first either as it doesn't reflect the same ordering as the single `object` parameter `Merge` methods.

**Comment by JamesNK** [comment]
I don't want to make it fluent because it is inconsistent with other methods that modify JTokens which all return void.

A params array of tokens to merge would be nice but the settings parameter makes it impossible.

**Comment by highfield** [comment]
I can only agree.
The only suitable way is making an extension method, or something similar off the official library.
Thanks anyway.
