### ISSUE TITLE
Release date for 9.0.2 ?

### ISSUE THREAD

**Issue by chrisdunelm** [JamesNK/Newtonsoft.Json#1200]
Do you have a planned release date for v9.0.2 (non-beta)?

I ask because we'd like to use the v9.0.2 support for BigInteger parsing of numbers in the NetStandard target within [Google.Cloud.Metadata.V1](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.Metadata.V1) and [Google.Api.Gax](https://github.com/googleapis/gax-dotnet/tree/master/src/Google.Api.Gax), but we really need a non-prerelease version to do so.

Thanks :)

**Comment by JamesNK** [comment]
> Do you have a planned release date for v9.0.2 (non-beta)?

\no

**Comment by chrisdunelm** [comment]
OK, thanks for the quick answer.
