### ISSUE TITLE
F# - Discriminated Union as Map key incorrectly serialized

### ISSUE THREAD

**Issue by chadunit** [JamesNK/Newtonsoft.Json#1201]
When using a discriminated union type as a map key in F#, it appears to get serialized incorrectly. Instead of the expected "Case" values like when DUs are serialized in other contexts, it just gets a generic type string.

Here is a script that can run in F# Interactive to show this behavior:
```
#r "packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
open Newtonsoft.Json
type Keys = Key1|Key2|Key3 ;;

printfn "DU standalone: %s" (JsonConvert.SerializeObject(Key3)) ;;
printfn "DU list: %s" (JsonConvert.SerializeObject([Key3;Key1])) ;;
printfn "DU set: %s" (JsonConvert.SerializeObject([Key3;Key1;Key3] |> Set.ofList)) ;;
printfn "DU map keys: %s" (JsonConvert.SerializeObject([(Key3,333);(Key1,111)] |> Map.ofList)) ;; // INCORRECT
printfn "DU map values: %s" (JsonConvert.SerializeObject([(333,Key3);(111,Key1)] |> Map.ofList)) ;;
```
And here are the output lines; notice the incorrect DU map keys on the 4th line:
```
DU standalone: {"Case":"Key3"}
DU list: [{"Case":"Key3"},{"Case":"Key1"}]
DU set: [{"Case":"Key1"},{"Case":"Key3"}]
DU map keys: {"FSI_0002+Keys":111,"FSI_0002+Keys":333}
DU map values: {"111":{"Case":"Key1"},"333":{"Case":"Key3"}}
```

**Comment by JamesNK** [comment]
Think about it: a key is just a string. You can't have JSON in it.

**Comment by chadunit** [comment]
Ok, I normally think of keys as any object supporting equality comparison, hence we have Dictionary<'TKey,'TValue> and Map<'TKey,'TValue> (as opposed to <string,'TValue>).

Previous experience with the .NET DataContractJsonSerializer handled this case fine (at the expense of more verbose JSON representation): 

```
val it : string =
  "{"serializedData":[{"key":{"_tag":0},"value":111},{"key":{"_tag":2},"value":333}]}"
```
 
…so it caught me off guard.

I understand this library has presumably made the design decision to support only the simple string key syntax of JSON itself for map-like objects which I can accept, I see now I can potentially try overriding ToString() and look into custom converters.
