### ISSUE TITLE
Json array without comma 

### ISSUE THREAD

**Issue by wjzhou** [JamesNK/Newtonsoft.Json#1202]
It seems the following invalid json array is accepted by the json.net.

``` json
[0 1 2] //note: no comma between the numbers
``` 

The following c# code doesn't throw, it returns a list.
``` csharp
JsonConvert.DeserializeObject<List<int>>("[0 1 2]")
```

For me this is a good thing. But I can't find any document that describes this behavior.

**Comment by JamesNK** [comment]
Good catch. Fixed

https://github.com/JamesNK/Newtonsoft.Json/commit/c9bbe2f18871ced7cd25f2d3be1abbe0537aee02
