### ISSUE TITLE
TypeNameHandling.Auto support for main entry type.

### ISSUE THREAD

**Issue by malylemire1** [JamesNK/Newtonsoft.Json#1203]
Is it possible to add main entry object type support in TypeNameHandling.Auto.

For now I have to add a wrapper only for the main entry object if it's runtime type is different from the declared type.

```
public class ValueWrapper<T>
{
    public ValueWrapper()
    {
    }
    public ValueWrapper(T value)
    {
        Value = value;
    }
    public T Value { get; set; }
}

public static TResult JsonClone<TResult>(this TResult input)
{
    if (input != null && typeof(TResult) != input.GetType())
    {
        return JsonConvert.DeserializeObject<ValueWrapper<TResult>>(JsonConvert.SerializeObject(new ValueWrapper<TResult>(input), jsonSettings), jsonSettings).Value;
    }

    return JsonConvert.DeserializeObject<TResult>(JsonConvert.SerializeObject(input, jsonSettings), jsonSettings);
}
```

**Comment by TylerBrinkley** [comment]
Join the crowd, #634, #990, and #1128. @JamesNK given how often this is reported would you reconsider adding generic serialize methods?

**Comment by JamesNK** [comment]
No because after adding generic serialize methods this code...

```
public string SerializeJson(object o)
{
    return JsonConvert.SerializeObject(o);
}
```

...will still always call the non-generic method and no output $type and confuse the 99% of .NET devs who don't have expert knowledge of overload resolution.

**Comment by TylerBrinkley** [comment]
Your argument makes a lot of sense and I was able to validate that your scenario would cause an issue for those expecting the `$type` to be serialized in that situation. That said I think adding the generic versions would prevent way more reports of this issue than any additional reports of the issue you described. I respect your decision either way and will not further comment.
