### ISSUE TITLE
Json.Parse causing duplicate items

### ISSUE THREAD

**Issue by CodeLiftSleep** [JamesNK/Newtonsoft.Json#1205]
I'm not sure if this is an issue with the object itself or with the parse, because it happens in both Json.net and in Javascript using JSON.parse.  

Basically, the string is fine, having the correct items in it, but then when it gets parsed, the items all appears twice---it parses the whole string, then parses it again after the last item in the first array. So if I have an array that should be 32, it ends up being 64, if its supposed to be 3000, its end up 6,000, etc...

I mean in JS it's easy enough to just use splice(start, end) after the parse to remove the duplicates, but I am wondering why it is happening.   I am parsing items from a DataTable using JsonConvert.SerializeObject(DataTable)...

**Comment by JamesNK** [comment]
I need a repro of the bug.
