### ISSUE TITLE
JContainer and static method MergeEnumerableContent, proposing new MergeArrayHandling Type.

### ISSUE THREAD

**Issue by israelito3000** [JamesNK/Newtonsoft.Json#1209]
I want to extend/modify a merging algorithm and I found in JContainer the method MergeEnumerableContent is static and internal also: MergeItem is internal, so no way to extend it? Do you think that is possible to open those methods to allow extend?

The merge implementation I want to do is merging arrays elements by a key instead of the index, I would prefer to add a new MergeArrayHandling Type, I dont know if you would accept that, Currently in the mind time I already implemented in this way, but I preffer to not fork. Any suggestion?

            case MergeArrayHandling.Merge:
                    int i = 0;
                    foreach (object targetItem in content)
                    {
                        // ********************************
                        // Here the new implementation
                        // ********************************
                        if (((JObject)targetItem)["$key"] != null)
                        {
                            string key = ((JObject)targetItem)["$key"].Value<string>();
                            JToken sourceItem = target.SelectToken("[?(@.$key=='" + key + "')]");
                            JContainer existingContainer = sourceItem as JContainer;
                            if (existingContainer != null)
                            {
                                existingContainer.Merge(targetItem, settings);
                            }
                            else
                            {
                                if (targetItem != null)
                                {
                                    JToken contentValue = CreateFromContent(targetItem);
                                    if (contentValue.Type != JTokenType.Null)
                                    {
                                        target.Add(contentValue);
                                    }
                                }
                            }
                            continue;
                        }
                        // ********************************

                        if (i < target.Count)
                        {
                            JToken sourceItem = target[i];

                            JContainer existingContainer = sourceItem as JContainer;
                            if (existingContainer != null)
                            {
                                existingContainer.Merge(targetItem, settings);
                            }
                            else
                            {
                                if (targetItem != null)
                                {
                                    JToken contentValue = CreateFromContent(targetItem);
                                    if (contentValue.Type != JTokenType.Null)
                                    {
                                        target[i] = contentValue;
                                    }
                                }
                            }
                        }
                        else
                        {
                            target.Add(targetItem);
                        }

                        i++;
                    }
                    break;

**Comment by JamesNK** [comment]
Merge isn't design to be infinitely customizable. For customize code like this you should have a custom merge function.
