### ISSUE TITLE
Pretty slow first Deserialize() on Xamarin.Android

### ISSUE THREAD

**Issue by monostefan** [JamesNK/Newtonsoft.Json#1216]
Hey there!

We use Newtonsoft.Json all over the place in our App and love it! However, we recently wanted to optimize our App startup time and found out by measuring various things that whenever for the first time we deserialize some JSON, there's a huge lag of about 800ms to 1s. It doesn't really matter if we use JsonConver.DeserializeObject() or a new JsonSerializer, the lag is always noticeable on the first time.

I made a small repo case here: https://github.com/monostefan/json.net_android_slow_start

My guess is this has something to do with internal initialization. However, does anybody know why this is so slow on Xamarin.Android (Xamarin.iOS seems not affected)?

**Comment by JamesNK** [comment]
I don't know, I've never used Xamarin.Android. The same code executes on both platforms. I suggest you raise this issue with the Xamarin guys.
