### ISSUE TITLE
Support for immutable structs

### ISSUE THREAD

**Issue by jnm2** [JamesNK/Newtonsoft.Json#1218]
Please support immutable structs out of the box.

Today we have mutable struct support:
```c#
var result = JsonConvert.DeserializeObject<MutableStruct>("{ \"Value\": \"working\" }");
var test = result.Value; // is "working" as expected

struct MutableStruct
{
    public MutableStruct(string value)
    {
        Value = value;
    }

    public string Value { get; set; }
}
```

And immutable class support:
```c#
var result = JsonConvert.DeserializeObject<ImmutableClass>("{ \"Value\": \"working\" }");
var test = result.Value; // is "working" as expected

class ImmutableClass
{
    public ImmutableClass(string value)
    {
        Value = value;
    }

    public string Value { get; }
}
```

It would be awesome to have immutable struct support. This currently fails at all levels of an object graph, not just the root:

```c#
var result = JsonConvert.DeserializeObject<ImmutableStruct>("{ \"Value\": \"working\" }");
var test = result.Value; // should be "working", but was null

struct ImmutableStruct
{
    public ImmutableStruct(string value)
    {
        Value = value;
    }

    public string Value { get; }
}
```

**Comment by JamesNK** [comment]
There is support but by default Json.NET will call the implicit default constructor on a struct. Adding an attribute to the constructor forces Json.NET to call it instead:

```
public struct ImmutableStructWithConstructorAttribute
{
    [JsonConstructor]
    public ImmutableStructWithConstructorAttribute(string value)
    {
        Value = value;
    }

    public string Value { get; }
}
```

**Comment by jnm2** [comment]
So what's my recourse when I can't apply an attribute? I am not willing to reference Newtonsoft.Json or put persistence implementations in the class library where the model is defined.

**Comment by jnm2** [comment]
Here's the most logical way I can think that resolver should work by default:

 1. List each immutable constructor-initialized property. (I.e., properties that are not writable and that appear as a parameter in any constructor.)
 2. List each constructor which initializes all the properties in the list from step 1 and where the remaining constructor parameters (if any) either are optional parameters or map to writable properties.
 3. If there is exactly one constructor in the list from step 2, this is the only constructor that anyone would ever want to use. It is the only constructor which initializes all the immutable properties which could be initialized from any constructor.
    If there are more or fewer than 1 candidate in the list, it is not clear which is better to use so no decision should be made.

Here's an implementation of this: https://gist.github.com/jnm2/df1355ad95b4da118c83ee711604cf62

Usage:

```c#
var result = JsonConvert.DeserializeObject<ImmutableStruct>("{ \"Value\": \"working\" }", JsonImmutableDeserialization.DefaultSettings());
var test = result.Value; // should be "working", but was null
```

@JamesNK What do you think? Does this make sense for Newtonsoft.Json in general?

**Comment by JamesNK** [comment]
Ok, I've done something similar https://github.com/JamesNK/Newtonsoft.Json/commit/b5f1b8319133ab63dcd155f12922c37a8c9b7185

**Comment by jnm2** [comment]
This is awesome, thank you!

**Comment by tdaniely** [comment]
Seems related, don't you think `JsonConvert.PopulateObject` should have an overload that takes `ref object`?
