### ISSUE TITLE
`StringEnumConverter` cannot be constructed on Mono 4.5

### ISSUE THREAD

**Issue by ikeough** [JamesNK/Newtonsoft.Json#1223]
See this post on S.O.: http://stackoverflow.com/questions/37776866/json-net-8-0-error-creating-stringenumconverter-on-mono-4-5-mac

I was able to make this work on Mono by forking and building, on Mono. But I'd much prefer to use the NuGet package.

**Comment by JamesNK** [comment]
You're going to need to raise this with the Mono team. I don't spend time on Mono compatibility.

**Comment by wangyblzu** [comment]
mute the thread



wangyb_10@163.com
 
From: James Newton-King
Date: 2017-02-23 08:41
To: JamesNK/Newtonsoft.Json
CC: Subscribed
Subject: Re: [JamesNK/Newtonsoft.Json] `StringEnumConverter` cannot be constructed on Mono 4.5 (#1223)
Closed #1223.
