### ISSUE TITLE
Feature request: Ability to identify differences between two JObjects

### ISSUE THREAD

**Issue by Prosserc** [JamesNK/Newtonsoft.Json#1225]
[`JToken.DeepEquals()`](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_DeepEquals.htm) allows a user to compare two `JObject`s which can be quite useful for unit tests. Unfortunately, when you compare objects that are more than a few lines it can be tricky to spot the differences when they are not equal.

I would like to propose a new method (or alternative signature e.g. with an out parameter) which would help users to identify any keys that are present in one but not the other and any differences within values.

**Comment by JamesNK** [comment]
It sounds kind of useful but pretty niche. I think that is something that can be part of a third party helper library.
