### ISSUE TITLE
TypeConverter for custom struct is ignored (.NET Core)

### ISSUE THREAD

**Issue by rcollina** [JamesNK/Newtonsoft.Json#1227]
Hello everyone,
It seems that custom TypeConverters are now ignored for custom structs.
Additional info: I am using NUlid (see PR to include the TypeConverter: https://github.com/RobThree/NUlid/pull/7 - https://github.com/rcollina/NUlid/blob/2bd8b3ad648cafa9bb8dc4159a62739f73cab48d/NUlid/UlidTypeConverter.cs).

Works in .NET Framework:
![image](https://cloud.githubusercontent.com/assets/699839/23309878/aebc4f70-fab0-11e6-901d-02e9e5af04df.png)

Doesn't seem to work anymore in .NET Core:

![image](https://cloud.githubusercontent.com/assets/699839/23312186/18b73c5c-fab9-11e6-83d1-3252ec874639.png)

Is there anything I'm missing / something I might be overlooking?
Thanks in advance.

**Comment by JamesNK** [comment]
It wasn't supported in 9.0.1

Get that latest pre-release version off NuGet and try again.

**Comment by rcollina** [comment]
Thank you.
