### ISSUE TITLE
JObject.Parse adding extra one day with extra minutes and seconds with my given json input

### ISSUE THREAD

**Issue by ShahriatHossain** [JamesNK/Newtonsoft.Json#1228]
I have json output from api is like below:
2017-02-27T23:59:59+00:00

but when I use JObject.Parse method to parse my json then the date outcome is like below:
2017-02-28T05:59:59+06:00

it seems that it is adding extra one day with some extra time. 

can any body suggest me how can I solve this problem?

**Comment by haakoo** [comment]
The two times you have there are the same. +00:00 and +06:00 is the difference from UTC time.

The json output is in UTC, while your DateTime.ToString uses your local time zone (+6 hours).

**Comment by JamesNK** [comment]
You need to create a `JsonTextReader` and configure it to read DateTimeOffset instead of DateTime. It is something like `DateTimeHandling`. Load the JObject from the reader.
