### ISSUE TITLE
Naming convention ignored in JsonPropertyAttribute

### ISSUE THREAD

**Issue by VDBorovikov** [JamesNK/Newtonsoft.Json#1229]
Hello!
When I specify naming convention in WebApi configuration it doesn't take effect on properties marked with `JsonPropertyAttribute` with manually set `PropertyName`.
Configuring like this:
```C#
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        //some configuration
        config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new DefaultContractResolver() {NamingStrategy = new SnakeCaseNamingStrategy()};
    }
}
```

Sample class:
```C#
public class Sample
{
    //some fields
    [JsonProperty(PropertyName = "CreationTimeIso")]
    property DateTime CreationTime { get; set; }
    [JsonProperty(PropertyName = "CreationTime")]
    property int CreationTimestamp { get; set; }
   //...
}
```
Even specifying `NamingStrategyType = typeof(SnakeCaseNamingStrategy)` in `JsonPropertyAttribute` doesn't take effect. The output would be:

```JSON
{
   "CreationTimeIso": "",
    "CreationTime": 123456,
}
```

**Comment by JamesNK** [comment]
Please ask questions about using Json.NET on Stackoverflow

**Comment by VDBorovikov** [comment]
Sorry, I don't think it's about using but about unexpected or unclear behavior of Json.NET.

**Comment by JamesNK** [comment]
It is expected.
