### ISSUE TITLE
Error converting doubles Version 10.0.1-beta1

### ISSUE THREAD

**Issue by doktrova** [JamesNK/Newtonsoft.Json#1231]
Input string '.24736062369174900' is not a valid double. Path 'Roots[0].Coefficients[0]', line 116, position 26.

This works fine in version 9.0.1

CONVERTER STATEMENT

`JsonConvert.DeserializeObject<Root>(sr.ReadToEnd());`

JSON FILE
```
....
"Coefficients": [
        .24736062369174900' ,
        .04411141058386060,
        -.35110749264922600
]
....

```
TARGET C# POCO
```
        public class Root
        {
            public IList<double> Coefficients { get; set; }
            public double Constant { get; set; }
           ...
        }
```

**Comment by JamesNK** [comment]
That's intentional. Your JSON isn't valid. A number must have a zero before the decimal point.

**Comment by doktrova** [comment]
Nonetheless it is a breaking change.
