### ISSUE TITLE
Bug Casting JValue Integer to boolean

### ISSUE THREAD

**Issue by jakubozga** [JamesNK/Newtonsoft.Json#1232]
Hello,

Lately I found a weird behavior of this library. To be more precise, below assert is not included in tests `JTokenTests.cs`
```
Assert.AreEqual(false, (bool)(new JValue(2)));
```
Also if you try to add it, it`s gonna fail.

**Comment by JamesNK** [comment]
That's correct. Any int value over zero is true.
