### ISSUE TITLE
ISO datetime string format changes when deserializing to string property 

### ISSUE THREAD

**Issue by engenb** [JamesNK/Newtonsoft.Json#1233]
I am deserializing this json:
```javascript
{
  "foo": "2017-01-17T17:24:12.9538487Z"
}
```
into this poco:
```csharp
public class Model
{
    public string Foo { get; set; }
}
```
here is a unit test that reproduces the issue:
```csharp
public class Model
{
	public string Foo { get; set; }
}

[Fact]
public void DeserializeISOString()
{
	var expectedIso = "2017-01-17T17:24:12.9538487Z";
	var token = JToken.Parse($"{{\"foo\":\"{expectedIso}\"}}");
	var obj = token.ToObject<Model>();

	// obj.Foo == "01/17/2017 17:24:12"
	Assert.Equal(expectedIso, obj.Foo); // assertion fails
}
```

When debugging this, I noticed `token` has "foo" mapped to a `JProperty` with a `DateTime` value.  I'm assuming the `JToken.Parse(...)` detected a matching date format and assumed we were dealing with a `DateTime`.  This would be fine, except my target type is a string that is just coincidentally also an ISO date formatted value.

That aside, I would assume this `JProperty` `DateTime` value be converted back to an ISO formatted string anyway based on documentation regarding Newtonsoft.Json's [default behavior when serializing DateTime](http://www.newtonsoft.com/json/help/html/DatesInJSON.htm) for v4.5+, so I'm a little perplexed.

While I'm open to supplying any ISO formatting options to get around this, should I have to?  Should this be doing any date conversion before knowing the target property type?

Thanks in advance for any suggestions for working around this issue!

**Comment by JamesNK** [comment]
You need to create a JsonTextReader and configure it to read None instead of DateTime. It is something like `DateTimeHandling`. Load the JObject from the reader.
