### ISSUE TITLE
License file is not included in nuget package

### ISSUE THREAD

**Issue by trevorpower** [JamesNK/Newtonsoft.Json#1237]
From my understanding of the MIT license and similar, the license text needs to be "included in all copies or substantial portions of the Software". I was hoping this didn't apply to compiled binaries but I cannot find and references to that effect.

Probably nobody really cares about this stuff but it wouldn't hurt to include the `LICENSE.md` in the nuget package.

Ideally in a way the it gets copied along with DLLs but as long as it is there somewhere it means a separate non-nuget download is not needed.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/2e18e592fd8081027d0b1bf69d5b112af6b0ec0d
