### ISSUE TITLE
Deserialization error with PreserveReferencesHandling.Objects

### ISSUE THREAD

**Issue by ddavyd0v** [JamesNK/Newtonsoft.Json#124]
When $id properties in input Json are last properties of an object, i.e.

``` js
{'number':'1','$id':'1'}
```

references are not resolved at all, properties with `{'ref':'1'}` in json are null in C# objects.

**Comment by uberclops** [comment]
What should one do when serializing objects from JavaScript and sending this to an app using JSON.NET?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify says:

> Properties of non-array objects are not guaranteed to be stringified in any particular order. Do not rely on ordering of properties within the same object within the stringification.

What I've done is to restructure an object before calling `JSON.stringify()` by removing all properties, adding the "$id" value, and then adding the properties back to the again. This works (I haven't encountered a situation yet where it has failed), but according to the Mozilla page it is likely to fail at some point.

**Comment by wizarrc** [comment]
@JamesNK 

Using Chrome Version 53.0.2785.143 m (64-bit) I have repeated what @uberclops has suggested and it works most of the time, however, it does fail on occasion (and repeatedly, given an exact nested structure), no matter what I do, I can't get chrome to make it first in the list using the built-in stringify. I have found a sorting version of stringify on npm that does the trick, assuming that $id is always alphabetically first (which might not always be the case).

Do you have any guidance on how to best play nice together? Maybe a filter on the .NET side that can sort $id to the top before processing is in order or better compat.

**Comment by JamesNK** [comment]
There is a new setting that allows metadata properties to appear anywhere in an object

http://www.newtonsoft.com/json/help/html/DeserializeMetadataPropertyHandling.htm

There is a small performance cost for turning this on.

**Comment by wizarrc** [comment]
@JamesNK 

Thanks, that's exactly what I was looking for. There is a balance between trying to figure it out on the client side vs. performance on the server side. This will allow me to get it working till I can optimize the client side.

Thanks for the quick feedback!
