### ISSUE TITLE
Validation of Dictionaries

### ISSUE THREAD

**Issue by DominikHerold** [JamesNK/Newtonsoft.Json#1243]
I have following json:

    {
      "Type": "Foo",
      "Connections": {
        "Bar": {
          "Endpoint": "http://bar.com",
          "Timeout": "00:30:00"
        },
        "Bar": {
          "Endpoint": "http://foobar",
          "Timeout": "00:30:00"
        }
      }
    }

Whereby *Connections* is a *Dictionary<string, Connection>*. Is it possible to add a new parameter to *JsonPropertyAttribute* which validates Keys and throws an Exception if the Key is already in the Dictionary?

**Comment by JamesNK** [comment]
Nope. You could deserialize to a dictionary that rows an error when a value is set to a key that already exists.

**Comment by DominikHerold** [comment]
But I'm deserializing into a _Dictionary<string, Connection>_ and it does not throw any exception. So what do I wrong?
