### ISSUE TITLE
JSON Serializer To Change Json String To Object Output 

### ISSUE THREAD

**Issue by ange1ann** [JamesNK/Newtonsoft.Json#1244]
I have some datas save json string to database.
When I use ORM to read from db to Dictionary<string,object>

After Serializer,It's output like this:
`{
  "config": "{\"viewrules\":\"A\",\"validrules\":\"B\"}",
  "version": 1
}`

Could there any way to change the output to this when meet a string is a json string:
{
  "config": {
    "viewrules": "A",
    "validrules": "B"
  },
  "version": 1
}

**Comment by ange1ann** [comment]
Could Any One Give Some Help?

**Comment by Solybum** [comment]
In some projects I have, I use this to format the serializer output

```
public static string JsonSerialize(object data, bool format = false)
{
    StringBuilder sb = new StringBuilder();
    JsonTextWriter jw = new JsonTextWriter(new StringWriter(sb));
    JsonSerializer js = new JsonSerializer();

    if (format)
    {
        jw.Formatting = Formatting.Indented;
        jw.Indentation = 4;
        jw.IndentChar = ' ';
    }

    js.Serialize(jw, data);
    
    return sb.ToString();
}
```

**Comment by JamesNK** [comment]
Use Stackoverflow for questions.
