### ISSUE TITLE
JsonSerializerSettings defaults documentation

### ISSUE THREAD

**Issue by jminer** [JamesNK/Newtonsoft.Json#1245]
Reading the documentation, I don't see what the `JsonSerializerSettings` defaults are. I started at the `JsonConvert` class, and it doesn't mention what settings it uses if you don't specify any. Going to the `JsonSerializerSettings` class, it doesn't seem to say what the defaults are either. Without trial and error, one can't know what settings need to be changed without knowing what the defaults are. For example, `CheckAdditionalContent`, `DateFormatHandling`, and `MissingMemberHandling` are some settings that don't say what their default is. It would be helpful having this information in the documentation.

**Comment by JamesNK** [comment]
They're here - http://www.newtonsoft.com/json/help/html/SerializationSettings.htm

Feel free to create a PR adding them to JsonSerializerSettings properties.

**Comment by JamesNK** [comment]
Done - https://github.com/JamesNK/Newtonsoft.Json/commit/be032b562e05192c6ca7feb634a3fee11810ef3a

Thanks to @sebasrp
