### ISSUE TITLE
how do define jsonproperty order by predefined list

### ISSUE THREAD

**Issue by uhdyi** [JamesNK/Newtonsoft.Json#1246]
I know in general I can define it by specify the field in a list:

@JsonPropertyOrder({"field1", "field2", "field3"})
public class ReportRow extends Row {
  private String field1;
  private String field2;
  private String field3;
}
but is possible I predefine an list of field name and pass the reference to that list in the @JsonPropertyOrder like this:

List<String> orders = Lists.newArrayList("field1", "field2", "field3");

@JsonPropertyOrder(orders)
public class ReportRow extends Row {
      private String field1;
      ...

**Comment by JamesNK** [comment]
The documentation has a sample of ordering properties.
