### ISSUE TITLE
Do not serialize enum as int when it should be string

### ISSUE THREAD

**Issue by alenkacz** [JamesNK/Newtonsoft.Json#1248]
On this line https://github.com/JamesNK/Newtonsoft.Json/blob/b8e60c773bfbd765b9131694a01569e067b37d99/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs#L99 StringEnumSerializer has a fallback to serialize enum as int when value is unknown

I would argue that when consumer of that message expects string, it should not serialize the value as int - never. I would personally put null there instead

If you agree, I will submit merge request

**Comment by JamesNK** [comment]
I like the idea. I was just doing some cleanup so I added it myself. An error will be thrown if AllowIntegerValue on StringEnumConverter is false.

https://github.com/JamesNK/Newtonsoft.Json/commit/7673a18e55c2b30a69ce0cf972b12d8a7c42d5d3#diff-5e0582b968883a35253f261a8d5a67a2
