### ISSUE TITLE
Exception Binary Serialization is not working on version 10.0.1

### ISSUE THREAD

**Issue by fefedimoraes** [JamesNK/Newtonsoft.Json#1251]
Every exception fails to be binary serialized (in platforms that support Binary Serialization) in Newtonsoft.Json 10.0.1 due to the fact that they are not marked with `Serializable` attribute.

The reason for this is that the `HAVE_BINARY_EXCEPTION_SERIALIZATION` flag is not being supplied during compilation. I could not figure it out whether it should be provided by the [`build.ps1`](https://github.com/JamesNK/Newtonsoft.Json/blob/49aa983af062b30ece759aff938be97c8a192fb4/Build/build.ps1) script as a additional constant or manually provide this flag in each affected `csproj` file.

**Comment by JamesNK** [comment]
Ok. How do you go about binary serializing exceptions? I'd like to add a unit test for it so the problem doesn't turn up again.

**Comment by fefedimoraes** [comment]
I can reproduce the issue with the following code snippet:
```csharp
var exception = new JsonReaderException();
using (var memoryStream = new MemoryStream())
{
	var binaryFormatter = new BinaryFormatter();
	binaryFormatter.Serialize(memoryStream, exception);
}
```
My test is a little more complex, which revolved around serializing an exception, which had a `JsonReaderException ` as its inner exception, between `AppDomains`, but I guess the snippet below is enough for guaranteeing the exception is binary serializable.

**Comment by JamesNK** [comment]
Thanks. There will be a new version in a week or two and I'll include this fix in it. Stick with 9.0.1 until then.

**Comment by fefedimoraes** [comment]
Glad to help. :)
Thanks for the information.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/c9060682a1798fd5b5edf7071160e46cf9548051
