### ISSUE TITLE
Json.NET 10.0 Release Notes: Async example doesn't open the files for asynchronous I/O

### ISSUE THREAD

**Issue by justinvp** [JamesNK/Newtonsoft.Json#1253]
The [release notes for 10.0](http://james.newtonking.com/archive/2017/03/21/json-net-10-0-release-1-async-performance-documentation-and-more) includes an example of using the new async support. Note that `File.OpenRead` and `File.OpenWrite` will open the files for synchronous I/O, **not** asynchronous I/O.  In order to take advantage of asynchronous I/O, the `FileStream` constructor with the `useAsync` parameter should be used instead. It may be useful to update the example in the release notes to use this constructor so it does real asynchronous I/O.

https://msdn.microsoft.com/en-us/library/7db28s3c(v=vs.110).aspx

**Comment by JamesNK** [comment]
I did not know that. Fixed.

The `File` helper class really needs async overloads.
