### ISSUE TITLE
An doubt About DynamicObject Serialize

### ISSUE THREAD

**Issue by NodeGIS** [JamesNK/Newtonsoft.Json#1254]
on JsonSerializerInternalWriter.cs line 903, note:“ only write non-dynamic properties that have an explicit attribute”. and the code is:
` if (property.HasMemberAttribute){
  xxxxxxxx
}`

I want to know why do that?

**Comment by JamesNK** [comment]
For the same reason that properties on a dictionary aren't serialized: it isn't what most people would expect.
