### ISSUE TITLE
Xamarin iOS broken

### ISSUE THREAD

**Issue by curia-damiano** [JamesNK/Newtonsoft.Json#1260]
Hi,
I have a Xamarin iOS app that used Newtonsoft.Json 9.
When updating to version 10, I get the following warning on Visual Studio 2017:
- Found conflicts between different versions of the same dependent assembly that could not be resolved.
Additional info:
1>  Dependency "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>      Could not resolve this reference. Could not locate the assembly "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>          For SearchPath "c:\_Works\BingSpellChecker_iOS\packages\Newtonsoft.Json.10.0.1\lib\netstandard1.3".

The same project, compiled on Xamarin Studio (latest stable channel), gives this compile time error:
- The type 'System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The same project built with Newtonsoft.Json version 9 compiles correctly on both systems

**Comment by hegelsu** [comment]
I use Portable40 in Newtonsoft.Json 9,but i can't find Portable40 in Newtonsoft.Json 10.

**Comment by JamesNK** [comment]
It was removed. You will have to use Portable or a netstandard build.

**Comment by hegelsu** [comment]
![1](https://cloud.githubusercontent.com/assets/6879123/24390596/8e5b2704-13bc-11e7-95c7-28d7ab18694f.png)
I wan't to know whitch can use in MonoTouch And MonoDroid.
"portable-net45+win8+wpa81+wp8" not remark in up.

**Comment by curia-damiano** [comment]
Hi,
indeed the NuGet package gets downloaded from Visual Studio, so indeed it means that it supports MonoTouch and MonoDroid.
But when compiling, you get a warning in Visual Studio and a compile time error in Xamarin Studio.
It's a bug that should be fixed. Meanwhile I need to use the v9.

**Comment by JamesNK** [comment]
That readme.txt file is very out of date.

I can't know exactly which version to use on Xamarin. Try the Portable version, or the netstandard1.0.

**Comment by JamesNK** [comment]
The Portable40 assembly is back in 10.0.2.

**Comment by koww** [comment]
Hello, I'm very new to committing issue. I met the same error on Xamarin Studio / VS for Mac preview 4 saying I need to add a reference, and what I can find is the VS for Mac is using System.Runtime version 4.3 by default while I'm asked to add reference to a 4.0.20.0 version. Could that be the point?

**Comment by JamesNK** [comment]
If it is still broken then you'll need to raise the issue with Xamarin.

**Comment by curia-damiano** [comment]
Great, thank you very much for fixing this issue!
