### ISSUE TITLE
Json.Portable throw an exception on deserialization UInt64.MaxValue

### ISSUE THREAD

**Issue by sovist** [JamesNK/Newtonsoft.Json#1263]
Hi,
Add to project Newtonsoft.Json.Portable, and run bellow code

    class Program
    {       
        static void Main(string[] args)
        {
            //works fine
            var uInt64MaxValueStr = JsonConvert.SerializeObject(UInt64.MaxValue);

            //an exeption JSON integer 18446744073709551615 is too large or small for an Int64.
            JsonConvert.DeserializeObject<UInt64>(uInt64MaxValueStr); 
        }
    }

I found that HAVE_BIG_INTEGER wasn't defined for the Newtonsoft.Json.Portable project. 
In ParseReadNumber method, call of ConvertUtils.Int64TryParse returns ParseResult.Overflow because UInt64.MaxValue.ToString() has length of 20 chars, and this value couldn't parse as BigInteger (HAVE_BIG_INTEGER not defined).

**Comment by JamesNK** [comment]
Portable doesn't support BigInteger and long.MaxValue is the largest that can be serialized without it

**Comment by sovist** [comment]
But on Json.Portable serialization for UInt64.MaxValue works fine.
I updated my example, please, have a look.
Why it couldn't use UInt64 for parsing instead Int64?

**Comment by JamesNK** [comment]
Reading != writing

It isn't supported.
