### ISSUE TITLE
Xamarin Android really working ?

### ISSUE THREAD

**Issue by feldti** [JamesNK/Newtonsoft.Json#1264]
I got compiler warning like:

"Found conflicts between different versions of the same dependent assembly that could not be resolved."

when adding Newtonsoft.Json via nuget to my solution (which is a pcl) library and an Android application.

It seems to be, that Newtonsoft.Json is referencing "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", but this could noit be found - instead a "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" found.

3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Microsoft.CSharp.dll", but its name "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" didn't match.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Microsoft.CSharp.exe", but it didn't exist.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\Microsoft.CSharp.winmd", but it didn't exist.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\Microsoft.CSharp.dll", but it didn't exist.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\Microsoft.CSharp.exe", but it didn't exist.
3>          For SearchPath "{AssemblyFolders}".
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\Microsoft.CSharp.winmd", but it didn't exist.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\Microsoft.CSharp.dll", but it didn't exist.
3>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\Microsoft.CSharp.exe", but it didn't exist.
3>          For SearchPath "bin\Debug\".
3>          Considered "bin\Debug\Microsoft.CSharp.winmd", but it didn't exist.
3>          Considered "bin\Debug\Microsoft.CSharp.dll", but it didn't exist.
3>          Considered "bin\Debug\Microsoft.CSharp.exe", but it didn't exist.
3>      Required by "C:\projects\webcati_cs\webcati_cs\bin\Debug\webcati.dll".
3>  There was a conflict between "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
3>      "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
3>      References which depend on "Microsoft.CSharp, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Microsoft.CSharp.dll].
3>          C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Microsoft.CSharp.dll
3>            Project file item includes which caused reference "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Microsoft.CSharp.dll".
3>              Microsoft.CSharp
3>      References which depend on "Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
3>          C:\projects\webcati_cs\webcati_cs\bin\Debug\Newtonsoft.Json.dll
3>            Project file item includes which caused reference "C:\projects\webcati_cs\webcati_cs\bin\Debug\Newtonsoft.Json.dll".

**Comment by JamesNK** [comment]
I don't know. I can't have Xamarin on my computer. Ask Xamarin guys.

**Comment by feldti** [comment]
A workaround is to download Newtonsoft.Json 7.0.1 from Xamarin directly and work with that version. I was able to deploy and execute my app at once on an Android device ... with that version.

**Comment by JamesNK** [comment]
The Portable40 assembly is back in 10.0.2. Use that.

**Comment by duzenko** [comment]
How do I use the Portable40 assembly in Xamarin? It uses portable-net45+win8+wp8+wpa81\Newtonsoft.Json.dll by default.
