### ISSUE TITLE
Error Code: 'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.

### ISSUE THREAD

**Issue by Philosophaie** [JamesNK/Newtonsoft.Json#1265]
I tried to install NewtonSoft Json.net.

It will not install the package.

Error Code:'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.

How do you fix the dependency defined for 'Microsoft.CSharp' so I can install the package?

**Comment by JamesNK** [comment]
What kind of project are you using it with?

**Comment by JamesNK** [comment]
The Portable40 assembly is back in 10.0.2. It doesn't have a dependency on Microsoft.CSharp.

**Comment by niknah** [comment]
I'm getting this message also.  Using monodevelop 5.10.  Trying to install 10.0.2 via nuget...

Adding Newtonsoft.Json...
Downloading Newtonsoft.Json 10.0.2...
'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.

**Comment by JamesNK** [comment]
You'll have to bring it up with the monodevelop people. I don't have it.

**Comment by niknah** [comment]
Thanks for the quick response!   I installed the other JSON package from nuget instead.

**Comment by evil-shrike** [comment]
I had such error when I installed some package which depends on Newtonsoft.Json 6.0.3 into a project then updated Newtonsoft.Json to 10.0.2 in the project. On restore with NuGet 3.5 CLI I started getting `'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'`.

Result dependency graph:
```
project
 -> package1
   -> Newtonsoft.Json 6.0.3
 ->
   -> Newtonsoft.Json 10.0.2
 ```

**Comment by billzhuang** [comment]
i have similar problem, i use vs2012, and project target to .net 4.5, when try to upgrade from 9.x to 10.0.2, it show same error msg
_'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'._

**Comment by JamesNK** [comment]
As far as I know it isn't a bug in Json.NET. I've raised an issue in the NuGet repo.

**Comment by JamesNK** [comment]
Alright, so y'alls problem is the old version of NuGet in VS 2012. It doesn't support netstandard and that is causing the error.

You'll have to stick with Json.NET 9 until you update to a newer NuGet version. The next version of Json.NET will include a minimum NuGet client version so the warning is clearer.

**Comment by KoalaBear84** [comment]
Indeed. We had nuget.exe version 2.8.60717.93. After using the current recommeded version 3.5, it worked!

Download it here: https://dist.nuget.org/index.html

**Comment by rboy1** [comment]
I"m using VS2010 and can't upgrade to a newer version of VS which means I'm limited to NuGet 2.8.3
How do I install Json.NET 10.x ?

**Comment by JamesNK** [comment]
Ask the Nuget team. There is nothing I can do.

**Comment by JamesNK** [comment]
Ask the Nuget team. There is nothing I can do.

**Comment by rboy1** [comment]
Is there anything you can do to make it compatible with NuGet 2.x instead of just 3.x?

**Comment by JamesNK** [comment]
Only having a max of one netstandard target would make it compadible, but netstandard 1.3 is required to enable features like serializing/deserializing BigInteger, and removing netstandard 1.0 would break some other projects. I'm not going to remove either.

Ball is in MS's court to fix the issue, or your court to update to a newer version of VS.

**Comment by rboy1** [comment]
thanks, interesting choices, getting MS to fix something is like google's moonshots project ;)
