### ISSUE TITLE
Unexpected error when deserializing unknown types

### ISSUE THREAD

**Issue by thethuthinnang** [JamesNK/Newtonsoft.Json#1266]
In the following code, I serialize an object using Json.Net. This Json has type names embedded. I then change one of the type names to induce an error. When I deserialize the Json, I expect to get an object back that has a null value for the property with the fiddled type name. Instead the serializer craps out and returns null for the root object. The second error that I get suggests that there is a bug in the serializer.

    static public class JsonTest
    {
        static public void Test()
        {
            // Create test object
            A a = new A
            {
                MyTest = new MyTest(),
            };
          
            // Serialize it. 
            string json = JsonConvert.SerializeObject(a, new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Auto
            });

            // Fiddle class name to induce error
            json = json.Replace("+MyTest", "+MyTest2"); 

            // Before: {"MyTest":{"$type":"<Namespace>.JsonTest+MyTest, <Assembly>"}}
            // After: {"MyTest":{"$type":"<Namespace>.JsonTest+MyTest2, <Assembly>"}}

            // Deserialize
            A a2 = JsonConvert.DeserializeObject<A>(json, new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Auto,
                Error = (object sender, ErrorEventArgs e) =>
                {
                    e.ErrorContext.Handled = true; // Should have only one error: the unrecognized Type
                }
            });

            // A second error occurs: Error = {Newtonsoft.Json.JsonSerializationException: Additional text found in JSON string after finishing deserializing object....
            // a2 is null
        }

        public class A
        {
            public ITest MyTest { get; set; }
        }

        public interface ITest { }
        public class MyTest : ITest { }
    }

(This was posted as a [question](http://stackoverflow.com/questions/43104683/unexpected-error-when-deserializing-unknown-types-with-json-net) on stackoverflow.)

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/f88ae288bc00836760ee8dfab526e4b944a191bb
