### ISSUE TITLE
Support for immutable structs with multiple constructors

### ISSUE THREAD

**Issue by TAGC** [JamesNK/Newtonsoft.Json#1268]
It would be nice if JSON.NET supported immutable structs with multiple constructors. Using the latest stable release of JSON.NET (10.0.1), the following works as expected:

```
struct ImmutableStruct
{
    public ImmutableStruct(int id, byte[] payload)
    {
        Id = id;
        Payload = payload;
    }

    public int Id { get; }

    public byte[] Payload { get; }
}

var result = JsonConvert.DeserializeObject<ImmutableStruct>("{ \"id\": 10, \"payload\":[1,2,3] }");

// result.Id = 10
// result.Payload = [1,2,3]
```

However, adding another constructor will lead to unintended deserialisation:

```
struct ImmutableStruct
{
    public ImmutableStruct(int id, byte[] payload)
    {
        Id = id;
        Payload = payload;
    }
    
    public ImmutableStruct(int id)
    {
        Id = id;
        Payload = new byte[] { };
    }

    public int Id { get; }

    public byte[] Payload { get; }
}

var result = JsonConvert.DeserializeObject<ImmutableStruct>("{ \"id\": 10, \"payload\":[1,2,3] }");

// result.Id = 0
// result.Payload = null
```

I would prefer that JSON.NET uses a "best effort" deserialisation process here, trying to find the constructor with the most parameters that it can fill, and falling back to constructors with fewer parameters on failure.

Since both the ID and payload are specified in the JSON string in the above example, I would expect JSON.NET to deserialise using the first constructor. If I had just specified the ID, I would expect JSON.NET to use the second constructor leading to a struct with `ID=10` and `payload=[]`.

This issue is an extension of #1218.

**Comment by JamesNK** [comment]
I don't want that. The rules to find the most approprate constructor would be complex and hard to describe.

If there are multiple constructors and you want one then place a `[JsonConstructor]` attribute on the one you want used, like a normal class in Json.NET
