### ISSUE TITLE
Investigate removing dependency on Microsoft.CSharp

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json#1270]
`DynamicUtils.GetMember` and `DynamicUtils.SetMember` use two methods from `Microsoft.CSharp`. Json.NET only needs to get and set simple properties.

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/DynamicUtils.cs#L115-L140

It might be possible to remove dependency on Microsoft.CSharp and implement required functionality in Json.NET itself.

**Comment by Ermesx** [comment]
Dependency on Microsoft.CSharp cause issues on old versions of VisualStudio like 2012 and you cannot update JSON.net to version 10.0.x max is 9.0.x

![image](https://cloud.githubusercontent.com/assets/5731890/25433684/84213d9e-2a89-11e7-9f66-d3f20ec8fab8.png)

**Comment by tbayart** [comment]
Same here, forced to stick with 9.0.x because of Microsoft.CSharp dependency issue

**Comment by JamesNK** [comment]
Your issue is old Nuget clients merging dependencies from netstandard together. Microsoft.CSharp just happens to be the first one. If it was removed then you would just get another package name in the error.

**Comment by tbayart** [comment]
Do you have a tip to help me fix this or should I stick with 9.0.x ?

**Comment by JamesNK** [comment]
There is nothing I can do

**Comment by eriove** [comment]
If you can't update NuGet in VS2012 you could probably check in a later version of of NuGet with your code and run a pre-build task to restore packages. I did something similar when we were running TFS2013.

**Comment by JamesNK** [comment]
Not really possible. There is too much code in the Microsoft.CSharp to internalize.
