### ISSUE TITLE
Json.NetMF 1.3.0.0 installed successfully, but complains of missing some assembly when loading

### ISSUE THREAD

**Issue by JB16** [JamesNK/Newtonsoft.Json#1272]
Json.NetMF was installed via PM (command-line) on NetMF 4.4. There are no dependencies listed for this version of NetMF, so assumed all was good until I tried loading onto target (the special chars in the error statement are as they appear and haven't been modified).

Does anyone have an idea of what might be the missing assembly here? (mscorlib 4.4.0.0 is present)
-----------------
   Assembly: Json.NetMF (1.3.0.0)  Attaching deployed file.

   Assembly: System.IO (4.4.0.0)  Attaching deployed file.

   Assembly: AP200NetMFApplication (1.0.0.0)  Resolving.

Link failure: some assembly references cannot be resolved!!

Assembly: Json.NetMF (1.3.0.0) needs assembly '~�(B��+' (4.3.1.0)

Assembly: AP200NetMFApplication (1.0.0.0) needs assembly 'Json.NetMF' (1.3.0.0)

Error: a3000000

Waiting for debug commands...

The program '[5] Micro Framework application: Managed' has exited with code 0 (0x0).

**Comment by JamesNK** [comment]
I didn't write Json.NetMF.

https://github.com/mweimer/Json.NetMF

**Comment by JB16** [comment]
Sorry about that and thank you! The issue has been raised now in the correct forum.
