### ISSUE TITLE
This construct is deprecated. BSON reading and writing has been moved to its own package

### ISSUE THREAD

**Issue by draganjovanovic1** [JamesNK/Newtonsoft.Json#1277]
I am using BsonWriter in my project and since update to 10.* I am getting this warning:
This construct is deprecated. BSON reading and writing has been moved to its own package. See https://www.nuget.org/packages/Newtonsoft.Json.Bson for more details.

I installed Newtonsoft.Json.Bson package but can't find the way to get rid on the warning. Any example would be appreciated. Thanks.

**Comment by JonHanna** [comment]
You need to use the new types equivalent to the old. E.g. instead of using the old `BsonWriter` use the new `BsonDataWriter`. (Perhaps the warnings should suggest the type in each case).

**Comment by draganjovanovic1** [comment]
Thanks, it worked. I think that changing warnings would be good idea to avoid these kind of issues as I had :)

**Comment by alvarezdaniel** [comment]
Thanks!

**Comment by ppumkin** [comment]
Please update the documentation
https://www.newtonsoft.com/json/help/html/SerializeToBson.htm

**Comment by oxayotl** [comment]
@JonHanna 's suggestion from 2017 is great, I hope it will be implemented!

**Comment by maczkowski-bartlomiej** [comment]
@p10tyr It is 2025 and documentation still points to obsolete code.
