### ISSUE TITLE
JSON Deserialize has a new issue regarding decimals with non leading zeros.

### ISSUE THREAD

**Issue by thyams** [JamesNK/Newtonsoft.Json#1278]
Maybe working as intended now, but '.30' was accepted by v9.x.x.x as decimal type in .NET.

Current status with 10.0.0.2:
Exception Thrown: Input string '.30' is not a valid decimal.

Can we get clarity on whether officially a change, bug, or other?

**Comment by JamesNK** [comment]
.30 isn't a valid number according to the JSON spec. The previous behavior was a bug.

**Comment by thyams** [comment]
That's what I gathered. We went and repaired our data the day I opened the ticket but I appreciate the confirmation. I will share this with my team.
