### ISSUE TITLE
Newtonsoft.Json 10.0.2 and .NET Core 1.1 looks like its not copatible

### ISSUE THREAD

**Issue by AXS-RickardPettersson** [JamesNK/Newtonsoft.Json#1281]
Building my first .Net Core application and have some problem with the reference to the Nuget of Newtonsoft Json, the reference can not be find.

Any ideas ?

![newtosoft not working in net core](https://cloud.githubusercontent.com/assets/26087003/25001465/f16c0058-2045-11e7-80ba-ded36340aafc.PNG)

I have tried to add it manually and not get it to work:

![newtosoft not working in net core2](https://cloud.githubusercontent.com/assets/26087003/25001585/77ce2d24-2046-11e7-9e86-72ca4e7d29de.PNG)

**Comment by JamesNK** [comment]
I know that it is because the unit test project for Newtonsoft.Json is .NET Core 1.1. I suggest you ask on https://github.com/dotnet/project-system

**Comment by nbarbettini** [comment]
@AXS-RickardPettersson I've successfully used JSON.NET 9.x and 10.x in .NET Core projects. What does your `csproj` file look like?
