### ISSUE TITLE
not compatible with framework(Windows UWP)

### ISSUE THREAD

**Issue by mathisloge** [JamesNK/Newtonsoft.Json#1285]
`Das Paket "Newtonsoft.Json 10.0.2" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf "native,Version=v0.0" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.	
`

The above error message comes, when trying to install this package with nuget and a windows uwp app. 
Using Visual Studio 2017.

**Comment by JamesNK** [comment]
This error is coming from NuGet. I've created copied your issue here - https://github.com/NuGet/Home/issues/5292
