### ISSUE TITLE
.net 2.0 assemblies target .net 3.5

### ISSUE THREAD

**Issue by FernandoG2** [JamesNK/Newtonsoft.Json#1287]
The issue is simple, I paste the files on /bin/net20 to my assets folder on Unity and the editor say that the dll targets NET 3.5

P.S.
Because of this, i guess im receiving runtime errors when running on android devices.

**Comment by JamesNK** [comment]
If you open Newtonsoft.Json.dll you'll see that it references .NET 2 framework dlls. You'll need to ask the unity people what is going on with their editor.
