### ISSUE TITLE
Cannot Camel Case Anonymous Object Within JsonExtensionData Property

### ISSUE THREAD

**Issue by hershize** [JamesNK/Newtonsoft.Json#1289]
I am using JSON.NET v10.0.2 and trying to serialize this JSON:
`{ "id": 1, "Name": "Foo 1", "Description": "Foo 1 Description", "MyObject": { "Property1": "Value1" }, "MyArray": [{ "Property1": "Value1" }] }`

Using this model:
```
[JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy), NamingStrategyParameters = new object[] { true, true, true }]
public class MyClass
{
  [JsonProperty(PropertyName = "id")]
  public int Id { get; set; }
  [JsonExtensionData]
  public Dictionary<string, object> Data { get; set; }
}
```

The result that's coming back is:
`{ "id": 1, "name": "Foo 1", "description": "Foo 1 Description", "myObject": { "Property1": "Value1" }, "myArray": [{ "Property1": "Value1" }] }`

When I expected the result to be:
`{ "id": 1, "name": "Foo 1", "description": "Foo 1 Description", "myObject": { "property1": "Value1" }, "myArray": [{ "property1": "Value1" }]  }`

This seems to be a bug within the JsonSerializer. Any assistance?

**Comment by JamesNK** [comment]
This isn't a bug. Ask on Stackoverflow for help.

**Comment by morozenkomv** [comment]
Have the same issue.

On Stackoverflow said ask here.
