### ISSUE TITLE
StackOverflowException Deserializing Xml from Json with JsonConvert.DeserializeXmlNode

### ISSUE THREAD

**Issue by mtrichards26** [JamesNK/Newtonsoft.Json#1290]
I'm getting a StackOverflow when trying to deserialize invalid Json.  I was expecting a JsonSerializationException.  Noticed this after upgrading from v6 to v10 of Json.NET

Thanks!

### Source/destination types

```csharp
//Fails for deserializing both XNode's and XmlDocuments
XNode node;
XmlDocument xDoc;
```

### Source/destination JSON

```javascript
{'Row' : 
```

### Expected behavior

I was expecting a JsonSerializationException to be thrown

### Actual behavior

A StackOverflowException killed nUnit

### Steps to reproduce

```csharp
[Test]
public void FailOnInvalidJSON( )
{
    string json = @"{'Row' : ";

    Assert.Throws<JsonSerializationException>(()=>JsonConvert.DeserializeXmlNode(json, "ROOT"));
}
```

**Comment by dbc2** [comment]
There's an analysis of the problem on stackoverflow in [this answer](https://stackoverflow.com/a/43552519/3744182).  This appears to be a regression from 7.0.1 to 8.0.1.

**Comment by JamesNK** [comment]
Fixed

https://github.com/JamesNK/Newtonsoft.Json/commit/822c3f00dd8e49c6dbe762012272a70ab78dc70d
