### ISSUE TITLE
Feature request: Support for "DefaultMemberAttribute"

### ISSUE THREAD

**Issue by WildCard65** [JamesNK/Newtonsoft.Json#1292]
It would be nice if Json.NET takes into account the "System.Reflection.DefaultMemberAttribute" for serialization/deserialization.

Note: This should only apply for json objects.

Implementation:
1. New property for JsonObjectAttribute, JsonSerializer and JsonSerializationSettings called "DefaultMemberHandling"
2. Associated values for "DefaultMemberHandling" enum should be: "Default" and "Include" where default is to ignore the attribute and include to take it into account.

Note: Reason for "Default" being the ignore state is to preserve existing functionality.

Example of "DefaultMemberHandling" set at "Include":
``` csharp
[JsonObject(MemberSerialization.Fields, DefaultMemberHandling = DefaultMemberHandling.Include)]
[DefaultMember(nameof(MyInt))]
class ValueWrapper
{
    public int MyInt;

    public string MyAlias;
}
```

For above example class, the following json is valid for deserialization:
"50"
"{ \"MyAlias\": \"HI!\" }"
"{ \"MyInt\": 10 }"
"{ \"MyInt\": 10, \"MyAlias\": \"HI!\" }"

Current operation would disqualify the first json example (the "50") from being valid for deserialization.

Implementing this would open new possibilities for serialization/deserialization within Json.Net.

Example:
Object instance -> Value serialization (requires appropriate property combination)
Object instance -> Object serialization (requires appropriate property combination)
Value -> Object instance deserialization (requires appropriate property combination)
Object -> Object instance deserialization (requires appropriate property combination)

**Comment by JamesNK** [comment]
This seems like kind of a niche feature. I'm not sure how useful it is, I've never seen anyone ask for something like this before.

**Comment by WildCard65** [comment]
Basically, it should allow types to be serialized/deserialized as other types (like a class can be deserialized/serialized by a value type like ulong if it's the default member AND the only required property (everything else is defaulted).

**Comment by JamesNK** [comment]
Sorry but I don't think this is useful enough to be added as a new feature.
