### ISSUE TITLE
bug when test in intellitest

### ISSUE THREAD

**Issue by jonnysu** [JamesNK/Newtonsoft.Json#1303]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```
hello i am try to use intellitest to analysis my project with newtonsoft.json.the problem is i only get result of "invalidprogramexception" nothhing else. i think it is a bug, please check it 

i am using the simple console mode to build
////////////////////////////////////////////////////////////
public static object WeChatLogin(string js = "sdfsdf")
        {
            JsonSerializer serializer = new JsonSerializer();

            //System.IO.StringReader sr = new System.IO.StringReader(js);
            //object obj = serializer.Deserialize(new JsonTextReader(sr));
            return js;
        }
/////////////////////////////////////////////////////////////

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior

actually i ididn't use the json thinks. so it should pass the test ,but it didn't pass the test

### Actual behavior

invalidProgramException

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by jonnysu** [comment]
and ps when i use newtonsoft.json 3.5.8, it works fine,the but started since 4.0.1

**Comment by jonnysu** [comment]
is anyone here?

**Comment by JamesNK** [comment]
This isn't enough information for me to repo the bug. What is the stacktrace?

There is no reason this code shouldn't work:

```
JsonSerializer serializer = new JsonSerializer();

System.IO.StringReader sr = new System.IO.StringReader(@"{""message"":""Place your serialized or deserialized JSON here""}");
object obj = serializer.Deserialize(new JsonTextReader(sr));
```
