### ISSUE TITLE
Add an option to use decimal type to represent numeric values parsed

### ISSUE THREAD

**Issue by strangeattr** [JamesNK/Newtonsoft.Json#1305]
In many cases (especially when handling mission-critical financial/medical/scientific/engineering/etc data or data meant to be pre-processed and passed forward introducing the least amount of unnecessary value distortions possible) a developer may be willing to store an exact value read from the source while binary floating-point data types like `float `and `double `are not meant for this by design. It would be nice to have an option of getting `decimal ` type representation of exactly the values represented by the source literals parsed instead of floating-point approximations for non-integer (or, perhaps, integer as well - this will hardly hurt as long as it's optional) numeric fields.

**Comment by JamesNK** [comment]
You can already http://www.newtonsoft/json/help/html/T_Newtonsoft_Json_FloatParseHandling.htm
