### ISSUE TITLE
JsonSerializer.SerializationBinder documentation incorrect

### ISSUE THREAD

**Issue by johnseghersmsft** [JamesNK/Newtonsoft.Json#1306]
At both of these documentation pages, the name of the property is given as **SerializationBinder**. However, the actual name of this property is **Binder**. Also the Type of the property is listed as **ISerializationBinder** instead of the actual **SerializationBinder**.

http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_SerializationBinder.htm
http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_SerializationBinder.htm

**Comment by JamesNK** [comment]
They were added in v10. The old properties and types are still there, but obsoleted

http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_Binder.htm
