### ISSUE TITLE
Json.NET doesn't support the same JsonPath as the original implementation

### ISSUE THREAD

**Issue by nvivo** [JamesNK/Newtonsoft.Json#1308]
I'm coming from this [question on so](http://stackoverflow.com/questions/43855083/what-is-the-jsonpath-syntax-used-by-json-net), maybe this is a bug or by design.

Given this input:

```json
{
    "a": [
        {
            "id": 1
        }
    ],
    "b": [
        {
            "id": 2
        },
        {
            "id": 3,
            "c": {
                "id": 4
            }
        }
    ],
    "d": [
        {
            "id": 5
        }
    ]
}
```

Goessner's parser allows me to extract the ids of top level objects `a` and `b` using this query:

```
$.[a,b].*.id
```

Json.NET doesn't seem to support commas or asterisk this way. 
Json.NET supports `[*]` for a single attribute, but it gives different results as the reference implementation. For example, on goessner's parser, [*] seems to look into children too.

`$.b.[*].id` on goessner returns `[2, 3, 4]` while Json.NET returns [2,3].

This can be tested here: http://www.jsonquerytool.com/#/JSONPath or here: http://jsonpath.com/

**Comment by JamesNK** [comment]
> $.[a,b].*.id

Properties in square brackets should be quoted.

> $.b.[*].id on goessner returns [2, 3, 4] while Json.NET returns [2,3].

IMO goessner is wrong. `[*]` is equivalent to `*` which is suppose to be equivalent to asterisk in XPath, which is only on children. `$.b..[*].id` or `$.b..*.id` would search all children.
