### ISSUE TITLE
Error while convert JArray with large number

### ISSUE THREAD

**Issue by gorserg** [JamesNK/Newtonsoft.Json#1309]
### Source/destination types

```csharp
public class DemoClass
{
    public decimal maxValue;
}
```

### Source/destination JSON

```javascript
[
  { 
    maxValue : 10000000000000000000 
  }
]
```

### Expected behavior

Convert to list of DemoClass items

### Actual behavior

System.InvalidCastException  is thrown.
{"Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.IConvertible'."}

### Steps to reproduce

```csharp
using System.Collections.Generic;

public class DemoClass
{
    public decimal maxValue;
}
class Program
{
    static void Main(string[] args)
    {
        var jArray = Newtonsoft.Json.Linq.JArray.Parse("[{ maxValue:10000000000000000000 }]");
        var list = jArray.ToObject<List<DemoClass>>();
    }
}
```

**Comment by JamesNK** [comment]
Thanks for reporting this. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/1535268ab8a4a452d19a5a72cf740471a4072b4d
