### ISSUE TITLE
InvalidCastException when reading BigInteger via JsonReader.ReadAs{Type} 

### ISSUE THREAD

**Issue by GureevLeonid** [JamesNK/Newtonsoft.Json#1313]
I have issue with reading a large number while population jObject via methods JsonReader.ReadAsDecimal() and JsonReader.ReadAsInt32().
Same problem was fixed there https://github.com/JamesNK/Newtonsoft.Json/issues/885 for JsonReader.ReadAsDouble().

Looks like same code from commit https://github.com/JamesNK/Newtonsoft.Json/commit/5b04a61dd9b5782af45842da254f15bf3cbfd0b7  with check for BigInt type should be in method .ReadAsDecimal(), but i dont sure about .ReadAsInt32(), maybe it should throw JsonReaderException then?

How to reproduce:
```
void Main()
{
	var jObject = JObject.Parse("{ decimalValue:10000000000000000000}");
	var serializer = new JsonSerializer();
	var target = new Foo();
	serializer.Populate(jObject.CreateReader(), target);
}

class Foo
{
	public decimal DecimalValue { get; set; }
}
```

Exception details:

> System.InvalidCastException: Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.IConvertible'.
> at System.Convert.ToDecimal(Object value, IFormatProvider provider)
>    at Newtonsoft.Json.JsonReader.ReadAsDecimal()
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
>    at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)

**Comment by JamesNK** [comment]
I'm pretty sure I fixed that a couple of days ago here: https://github.com/JamesNK/Newtonsoft.Json/commit/1535268ab8a4a452d19a5a72cf740471a4072b4d
