### ISSUE TITLE
No endpoints compatible with Windows Store apps were found

### ISSUE THREAD

**Issue by usefulBee** [JamesNK/Newtonsoft.Json#1314]
I get this warning when attempting to install Newtonsoft.Json version 10.0.1 or higher in a UWP app, and in turn the package fails to install.

> Custom tool warning: No endpoints compatible with Windows Store apps were found

**Comment by JamesNK** [comment]
There is a netstandard1.0 target in the NuGet package. That should be compatible. I've added a copy of the issue to NuGet issues
