### ISSUE TITLE
Add support of Json5

### ISSUE THREAD

**Issue by AlenPelin** [JamesNK/Newtonsoft.Json#1316]
It would be great to extend Json.NET to support [Json5](json5.org) as well as standard json. There is a .NET
library on GitHub, but it does not have many features that Json.NET can offer:
https://github.com/json5/json5-dotnet

**Comment by JamesNK** [comment]
Json.NET already supports most of Json5, especially the parts people care about: comments and trailing commas.

There is no reason someone couldn't create a NuGet package with an implementation of JsonReader that has full support for Json5, i.e. Json5TextReader. I don't have time to write it.

**Comment by AlenPelin** [comment]
Thanks @JamesNK! I didn't realise that it already partially supports json5, I will check this out and try to implement missing json5 features myself. 

Would you consider it a good idea to mention supported html5 features in documentation?

**Comment by dylanh724** [comment]
> Json.NET already supports most of Json5, especially the parts people care about: comments and trailing commas.
> 
> There is no reason someone couldn't create a NuGet package with an implementation of JsonReader that has full support for Json5, i.e. Json5TextReader. I don't have time to write it.

> No reason

Maintenance. They'll likely update it and leave it to die.
