### ISSUE TITLE
Allow access to JPath logic for custom converters

### ISSUE THREAD

**Issue by SaltyDH** [JamesNK/Newtonsoft.Json#1317]
### Expected behavior

I'd like the JPath functionality to provide a way to determine if the current JToken's path matches a provided JPath filter. This functionality would be exposed publically so that it can be used in custom converters.

Basically I'm using a JsonReader inside of a custom converter, I'm extracting the path off the current position and I'd like to match that based on a JPath that includes wildcards.

### Actual behavior

JPath is internal :(

Hope I haven't missed this elsewhere in the codebase.
Is this something you'd accept as a pull request?

**Comment by JamesNK** [comment]
I don't want to make JPath public.

JsonReader has a Path property on it that is a valid JPath.

**Comment by SaltyDH** [comment]
Json reader has a string property, Path. Given a second string representing a Json path e.g. "Property1.*.child" is there a way to execute a comparison which tells me if the Json reader's Path property matches the Json path?

**Comment by JamesNK** [comment]
You could read the JSON into a JToken and use the path with wildcards. If the results contains a JToken with the more specific path then they were a match.

A feature just to test whether a JSON Path is more specific version of another path is pretty niche. You'd need to see whether there is another .NET JSON Path library that does it or write it yourself.
