### ISSUE TITLE
Deserialize multiple json files

### ISSUE THREAD

**Issue by Jafnhor** [JamesNK/Newtonsoft.Json#1320]
Hi !
I try to use Newtonsoft.json in order to deserialize an assemble of json files.
I have my CSharp classes corresponding to the schema that working great.
If i put all my json files in one, it deserialize without any problems, but i want to have some readable files, to do that i separate them in multiple files. When i do that, even with a link between them, Newtonsoft.json can't create a complete model with the corresponding schema.

For example, i have the CSharp classes Application and DataModel like that : 
class Application
    {
         [JsonProperty("dataModel", NullValueHandling = NullValueHandling.Ignore)]
         public DataModel dataModel { get; set; }
    }
class DataModel
    {
          [JsonProperty("id", Required = Required.Always)]
          public String id { get; set; }
    }

and my json to deserialize is : 
application.json : 
{
    "dataModel": {"$ref":"data.json"}
}
data.json : 
{
    "$id": "dataModel",
    "id": "dataModel",
}

I execute the code line to deserialize : 
JsonConvert.DeserializeObject<Aplication>(
    File.ReadAllText(@"application.json"),
    new JsonSerializerSettings {
        PreserveReferencesHandling = PreserveReferencesHandling.None,
        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
    });

After that i just check if my Application have a DataModel, but i get an exception that tell me that DataModel is null.

I don't know if the problem is because Newtonsoft can't make the link between simple json file or if it's something else.
A little bit of help will be welcome :-)

Thanks,
Jafnhor

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#question
