### ISSUE TITLE
JsonConvert.DeserializeObject doesn't throw an exception for an invalid array

### ISSUE THREAD

**Issue by Francisco-Gamino** [JamesNK/Newtonsoft.Json#1321]
Hi,

When calling JsonConvert.DeserializeObject with an invalid array as input an exception should be thrown, bu this is not the case. However, JArray.Parse does throw an exception. Is there a reason why does but not the other?

Thanks,
Francisco

### Steps to reproduce

```csharp
obj = JsonConvert.DeserializeObject('["1",', new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.None, MaxDepth = 1024 });
```

### Expected behavior
A JsonException is thrown since '["1",' is not a valid array.

### Actual behavior
No exception is thrown

**Comment by JamesNK** [comment]
Thanks for the detailed bug report. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/1a0ae2a42ddd69f2584424731ae3212363a2bd5c
