### ISSUE TITLE
JsonConvert.DeserializeObject formats date inside a string field of a KeyValuePair

### ISSUE THREAD

**Issue by IonutStef** [JamesNK/Newtonsoft.Json#1322]
### Source types

```csharp
IList<KeyValuePair<string, string>> values = new List<KeyValuePair<string, string>>
{
      new KeyValuePair<string, string>("123", "2017-05-19T11:00:59")
};
```

### Destination JSON

```javascript
[
   {
      ""Key"": ""123"",
      ""Value"": ""2017-05-19T11:00:59""
   }
]
```

### Expected behavior

I expected the value of the deserialized KeyValuePair element to be "2017-05-19T11:00:59", since it was a string to begin with.

### Actual behavior

The value is "2017/05/19 11:00:59"

From my tests, this happens only for KeyValuePair elements, but the tests were not complete, so there might be other types that behave the same.

```csharp
Expected: "2017-05-19T11:00:59"
But was:  "05/19/2017 11:00:59"
```

My test:
I created a class with the same structure as KeyValuePair and the result was the expected one.

### Steps to reproduce

```csharp

[Test]
public void SerializeDateTimeUsingInternalConverter()
{
      IList<KeyValuePair<string, string>> values = new List<KeyValuePair<string, string>>
      {
            new KeyValuePair<string, string>("123", "2017-05-19T11:00:59")
      };

      string json = JsonConvert.SerializeObject(values, Formatting.Indented);

      IList<KeyValuePair<string, string>> v1 = JsonConvert.DeserializeObject<IList<KeyValuePair<string, string>>>(json);
  
      Assert.AreEqual("123", v1[0].Key);
      Assert.AreEqual("2017-05-19T11:00:59", v1[0].Value);
}
```

**Comment by JamesNK** [comment]
Thanks for the detailed bug description. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/7726b5109160abbd05e7f1352e00fd4d1398f470
