### ISSUE TITLE
IsoDateTimeConverter  bug

### ISSUE THREAD

**Issue by chinacoolboyzz** [JamesNK/Newtonsoft.Json#1323]
### Steps to reproduce

```csharp
IsoDateTimeConverter timeConverter = new IsoDateTimeConverter { DateTimeFormat = "yyyy'/'MM'/'dd hh:mm:ss" };
var dt = Convert.ToDateTime("2017-05-23 00:16:20");
 var json = JsonConvert.SerializeObject(new { dt },Formatting.Indented, timeConverter);
```

### destination JSON

```javascript
{
  "dt": "2017/05/23 00:16:20"
}
```

### Expected behavior

```javascript
{
  "dt": "2017/05/23 00:16:20"
}
```

### Actual behavior
```javascript
{
  "dt": "2017/05/23 12:16:20"
}
```

**Comment by WildCard65** [comment]
It's not a bug, it's the time format string your using that's incorrect (logic error): you need "HH" instead of "hh" for hours (double lower 'h' is in 12 hour format, double capital 'h' is in 24 hour format)

**Comment by WildCard65** [comment]
@JamesNK I think it's safe for this to be closed.
