### ISSUE TITLE
Object With XMLProprieties Serializing Correctly but not deserializing

### ISSUE THREAD

**Issue by vinogmca** [JamesNK/Newtonsoft.Json#1327]
Hi,
  We have objects with huge number of XmlProperties(XmlNode,XmlNodelist) during deserialization we are getting error say "XmlNodeConverter only supports deserializing XmlDocuments" . Issue is during serialization my xml properties are converted to json string why not during deserialization.(i.e) i know XmlNodeConverter() is available but xmlproperties inside a class should deserialized if serialization happens correctly right?

Note: We implemented Custom Serialization (using C# Iserializable Interface using reflection) everythign working fine but it's very costly interms of CPU.

Ex:
   ```
Class Person
    {
      public XmlNode TestXml
        {
            get; set;
        }
      public string Name
        {
            get { return name; }
            set { name = value; }
        }
        public int IdNumber
        {
            get { return id; }
            set { id = value; }
        }
    }
```

Serialized Json String:  
       ```
   {
  "TestXml": {
    "orders": {
      "order": {
        "id": "550268",
        "name": "vinoth"
      }
    }
  },
    "Name": "Kumar",
  "IdNumber": 990268
}
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/7af0e223c01a8bf6aadfaabec13579ece88a66e7

**Comment by vinogmca** [comment]
Thanks for fixing this in a short period !!! 
If the library supports XMLNode property type in POCO object then it should support XmlNodeList also right? But by seeing your changes (https://github.com/JamesNK/Newtonsoft.Json/commit/7af0e223c01a8bf6aadfaabec13579ece88a66e7) For XMLNodeList properties we might face the issue again? Am i?

```
 Public Class Employee 
{
   public Int32 EmployeeId { get; set; }
   public String Name { get; set; }
   private XmlNodeList _emails;
        public XmlNodeList Emails
        {
            get  { return _emails;  }
            set { _emails = value; }
        }	
	public Int32 IdNumber { get; set; }
}

```

JSON:

```
{
  "EmployeeId": 100,
  "Name": Vinoth Kumar G,
  "Emails": [
    {
      "Email": {
        "EmailTypeID": "27",
        "TypeName": "xxx",
        "EmailID": "2000",
        "EmailAddress": "xxx1@test.com"
      }
    },
    {
      "Email": {
        "EmailTypeID": "28",
        "TypeName": "RelocateFromKC",
        "EmailID": "2001",
        "EmailAddress": "xxx2@test.com"
      }
    },
    {
      "Email": {
        "EmailTypeID": "5",
        "TypeName": "Customer Care",
        "EmailID": "9166223",
        "EmailAddress": "xxx3@test.com"
      }
    },
    {
      "Email": {
        "EmailTypeID": "20",
        "TypeName": "Real Estate Career Seminar",
        "EmailID": "9170882",
        "EmailAddress": "xxx4@test.com"
      }
    },
    {
      "Email": {
        "EmailTypeID": "25",
        "TypeName": "Find A Renter",
        "EmailID": "9170883",
        "EmailAddress": "xxx5@test.com"
      }
    }     
  ],
  "IdNumber": 1
  }
  }
```

Again Serialization is fine but during De-Serialization we are getting below exception from your library.

Cannot create and populate list type System.Xml.XmlNodeList. Path 'Emails', line 1, position 38.

**Comment by JamesNK** [comment]
Change the property to a IList<XmlNode> and it should work. I don't see a need for supporting XmlNodeList.

**Comment by vinogmca** [comment]
Cool. When we can expect this change (7af0e22)  to be in live? do we need wait for next version release?
