### ISSUE TITLE
Problem with deserializing Xamarin.Forms.Color class/type

### ISSUE THREAD

**Issue by boguslawski-piotr** [JamesNK/Newtonsoft.Json#1328]
Hello

Here is a sample code ilustrating problem.

 ```c#
Color c = Color.Red;
string d = JsonConvert.SerializeObject(c);
Color cd = JsonConvert.DeserializeObject<Color>(d);
 ```
After running test (Visual Studio for Mac) here are results (from debugger).
As you can see Color is not deserialized correctly.

c:
```c#
Color R=255, G=0, B=0, A=255
```

cd:
```c#
Color R=0, G=0, B=0, A=0
 ```

Best regards
Piotr Boguslawski

**Comment by JamesNK** [comment]
https://developer.xamarin.com/api/type/Xamarin.Forms.Color/

It is immutable and has multiple constructors so Json.NET doesn't know how to deserialize values into it. You'll need to write a JsonConverter or serialize your own type.

**Comment by boguslawski-piotr** [comment]
Hi

Thank you for quick reply 😀

P
