### ISSUE TITLE
[Bug] References are not preserved during serialization of collection if the property is read-only

### ISSUE THREAD

**Issue by BalassaMarton** [JamesNK/Newtonsoft.Json#1329]
### Scenario

Consider the following type:
```csharp
public class MyObject
{
    public List<string> List { get; } = new List<string>();
}
```
Now serialize this class with references preserved:

```csharp
var obj = new MyObject();
obj.List.Add("a");
obj.List.Add("b");
obj.List.Add("c");
var settings = new JsonSerializerSettings
{
    PreserveReferencesHandling = PreserveReferencesHandling.All
};
var json = JsonConvert.SerializeObject(obj, Formatting.Indented, settings);
```

### Expected JSON after serialization
```javascript
{
  "$id": "1",
  "List": {
    "$id": "2",
    "$values": [
      "a",
      "b",
      "c"
    ]
  }
}
```

### Actual JSON
```javascript
{
  "$id": "1",
  "List": [
    "a",
    "b",
    "c"
  ]
}
```

**Comment by JamesNK** [comment]
It isn't possible to preserve the reference of a read-only property because the serializer has no control over it. It is read-only.

**Comment by BalassaMarton** [comment]
@JamesNK What do you mean the serializer has no control over it? In this case, the serializer only reads the property, and retrieves the reference from the `ReferenceResolver`. The resulting JSON will not be deserialized with JSON.NET.

**Comment by JamesNK** [comment]
It has no control over deserializing it because it can't set the property. If you want Json.NET to handle creating or setting the reference it needs a setter.

**Comment by BalassaMarton** [comment]
This has nothing to do with deserializing. The resulting JSON will >>> NOT <<< be deserialized with Json.NET. In our case, we only use Json.NET to serialize an object graph, and the JSON will be deserialized in a JavaScript application. We want to preserve the references so that the deserialized object has the original relationships. I'm sure Json.NET does not need to write the property in order to serialize (not deserialize) its value.

**Comment by JamesNK** [comment]
I'm pretty sure someone in the past requested that objects that couldn't be deserialized by reference not include the $id in the JSON output. You can't both be happy.

Add a setter and you'll be fine. If you really don't want a public setter then make it private and place [JsonProperty] on it. That should work as well.

**Comment by BalassaMarton** [comment]
Except that I don't want to place JSON related attributes on the class, because JSON serialization is in a different abstraction layer. Would this be a breaking change? When deserializing, Json.NET will not attempt to deserialize a read-only property anyway. Or this could be controlled with a setting.
