### ISSUE TITLE
System.Exception loses Message value during serialization/deserialization

### ISSUE THREAD

**Issue by tarekgh** [JamesNK/Newtonsoft.Json#1336]
This issue originally reported by @eric-davis on https://github.com/dotnet/corefx/issues/20776. Moving it to here as it looks a Newtonsoft.Json issue than .Net Framework issue. Feel free to report it on https://github.com/dotnet/corefx/ if you think otherwise.

System.Exception appears to have some serialization issues. If I perform the following simple test utilizing Newtonsoft.Json for serialization, it fails:

            var ex = new Exception("Something bad happened!!!");
            var json = JsonConvert.SerializeObject(ex);
            var obj = JsonConvert.DeserializeObject<Exception>(json);
            Assert.AreEqual(ex.Message, obj.Message);

The custom message value is lost during deserialization and replaced with the default exception message: "Exception of type 'System.Exception' was thrown."

This was tested against System.Runtime version 4.1.0.0

**Comment by JamesNK** [comment]
Will be fixed in .NET Core 2 when Exception supports ISerializable.
