### ISSUE TITLE
Adding multiple custom converters causes significant perf degredation

### ISSUE THREAD

**Issue by jskeet** [JamesNK/Newtonsoft.Json#1337]
In the `NodaTime.Serialization.JsonNet` package, we have extension methods for `JsonSerializer` and `JsonSerializerSettings` which add converters for a bunch of Noda Time types. There are 11 converters added in all.

We've had an [issue filed](https://github.com/nodatime/nodatime.serialization/issues/12) indicating that even when *not* dealing with Noda Time types, this causes a significant performance problem, with the `CanConvert` implementation being a bottleneck.

I've [attempted to fix this](https://github.com/nodatime/nodatime.serialization/pull/13) and certainly improved things by optimizing `CanConvert`, but it's still a significant perf issue (follow the link for benchmark results in the comments and the benchmarks in the PR). Reducing the number of converters I'm adding definitely improves things.

Now I *could* build a single `NodaTimeConverter` which "knows" about all the other converters. Its `CanConvert` method could first filter by "is the target type's assembly NodaTime?" and reject things very quickly that way... and otherwise walk down its own list of converters. That feels like a bit of a kludge to me though - and it makes it harder to users to remove or replace individual converters.

Any suggestions here? It would be nice if Json.NET could cache the results of which converter to use for a particular type, but I assume there are good reasons to not do that.

**Comment by JamesNK** [comment]
Place a JsonConverter attribute on the type and it will get cached

**Comment by willdean** [comment]
@JamesNK Is there a way to do the equivalent at run-time?  I think @jskeet is going to say that he doesn't want to fill the core NodaTime library with 3rd-party dependencies / attributes.

**Comment by TylerBrinkley** [comment]
Perhaps the `DefaultContractResolver` should be updated to store `JsonConverter`s that only have their `CanConvert` method called when constructing each type's contract.

**Comment by JamesNK** [comment]
@willdean You can override DefaultContractResolver and set the converter property on the JsonContract. The problem with that is DefaultContractResolver doesn't compose well.
