### ISSUE TITLE
Robustness

### ISSUE THREAD

**Issue by Korporal** [JamesNK/Newtonsoft.Json#1338]
Hi,

For some reason we frequently get abstruse, bewildering assembly load failures with the Newtonsoft.Json assembly.

We have lots of library assemblies and some of these directly or indirectly reference Newtonsoft.Json. Many of these have been built and deployed many times, independently over the years (we have lots of MVC apps, WCF, REST etc) 

Today we're seeing assembly load failure for v 10.0.0.0 (This is the underlying exception that causes the app to fail).

A version 5.00.8.16617 (as seen in VS Modules window) has already been loaded by the AppDomain.

Its incredibly bewildering trying to understand what the actual cause is, because a library assembly (which is trying to load v 10.0.0.0) has a project file HintPath for the assembly that refers to v 10.0.2 in the solution's packages folder.

And the project's packages file is also referring to v 10.0.2 as well.

I'm already frustrated by the fragility of Nuget itself (it sometimes messes up project file hint paths, version overrides and other stuff, very hard to pin down) but this Newtonsoft.Json load issue is adding to the mix.

This may be due to buggy Nuget or it may not, the problem is that the combination of Nuget version mixing, legacy project file updates (accumulated by years and years of updates to Nuget itself) and complicated assembly dependency trees is almost impossible to fix sometimes.

I have some 15 years of .Net and CLR expertise (I don't claim to be superman but I am far from novice I assure you).

So after that intro - does anyone have any idea:

1. Why it is almost always Newtonsoft.Json that causes  us grief (not other assemblies)?
2. Why Microsoft have themselves published assemblies that reference Newtonsoft.Json?
3. Why Microsoft cannot write a Json support library themselves?
4. Has Newtonsoft released breaking changes/fixes over the years?

Thx

**Comment by JamesNK** [comment]
1. Because Newtonsoft.Json is strong named, have multiple version, is referenced by many projects and libraries
2. Because it is popular
3. DataContractJsonSerializer
4. Yes. Look at the release notes.

**Comment by Korporal** [comment]
Thank you for you very helpful reply, it is greatly appreciated.

1. Many assemblies in the .Net framework are referenced and we don't get this issue for them.

If this is all you can offer then I guess that's it - I was hoping for some clue as to why we experience this problem with Newtonsoft.Json far more than anything else.

I thought my original post was polite, I was striving to detail a real problem as best I can and hoping that someone might have some idea or may have experienced something similar.

Sorry to have bothered you James.

**Comment by Korporal** [comment]
@JamesNK - You may be interested in seeing the results of a Google search for "dependency issues Newtonsoft" you may be unaware but there is a theme here...

**Comment by reddyBell** [comment]
@Korporal I think that at this point it is highly unlikely that anything meaningful can be changed on this front considering the huge install-base of the library (assuming that there is indeed something wrong to fix). But more often than not, this simply forces you to have accurate and clean assemblyBinding sections and to give it some thoughts (which isn't necessarily a bad thing - I've gotten into this healthy habit mainly thanks to JSON.NET).

Now with regards to James, do not worry you said nothing wrong. I too have been surprised by the rudeness of his answers when I first posted here - as were many others.  But to be totally fair, I do not think that he his being rude, he is simply being careless with the tone of his answers. This produces the same perceived result, but I think the difference is meaningful.  For example, he always addresses the gist of the questions, and does so in a prompt manner, and at the end of the day this is what matters. But this also makes the fact that he alienates people even more unfortunate (he does the hard part and messes up on the easy part - as if he doesn't want us to like him).

**Comment by Korporal** [comment]
@reddyBell - Something else of interest. I have an app that's reporting assembly load failures (trying to load version 8.0.0.0) so I am attempting to change the version used in the app from 9.0.1 to 8.0.0.0 but in VS in the Manage Packages for Solution the dropdown list for versions goes down to 8.0.1 then 7.0.1 - no 8.0.0.0 or 8.0.0.

This is an example of the bewildering nature of this Json package.

Frankly it is not fit for purpose.

**Comment by TylerBrinkley** [comment]
I always thought the versioning scheme of starting with X.0.1 was kind of odd but ultimately insignificant as with further minor and patch updates the AssemblyVersion must remain the same due to issues with StrongNaming.
