### ISSUE TITLE
Default JsonSerializer throws for obsolete Binder

### ISSUE THREAD

**Issue by shahabhijeet** [JamesNK/Newtonsoft.Json#1340]
Since Newtonsoft.json 10.0 we are seeing default behavior for JsonSerialize.Binder is throwing InvalidOperationException.
Since Binder is obsolete, we still have lot of legacy code base where we do not assign any Binder and rely on Default Binder (DefaultSerializationBinder)
We also shallow copy JsonSerializer via reflection and hence during copying Binder throws.

Repro Step:
var serializer = JsonSerializer.Create();
Assert.NotNull(serializer.Binder);

Expected:
JsonSerializer.Binder should not throw if not initialized.
JsonSerializer.Binder should throw only when newly introduced property ISerializationBinder SerializationBinder is set by the user.

We have two approaches:
Approach 1
1) Start assigning default Binder (to avoid exception at runtime during shallow copy)
2) When Binder property is completely removed, also stop assigning Binder (to avoid compile error)

Approach 2 (PR #1341)
1) Bring back default behavior (JsonSerializer.Binder should not throw if not assigned)
2) When Binder property is completely removed, no changes are required (apart from adjusting for compile error if any for the removed property)

**Comment by JamesNK** [comment]
Thanks for reporting this. I didn't intend it to throw an error by default.

Merged with some simplification: https://github.com/JamesNK/Newtonsoft.Json/commit/64a092ee64df93f669be6d880f780f34b76b3208#diff-af4fbfe6e482e1bfbe69ae45a3eb1ddf

**Comment by shahabhijeet** [comment]
@JamesNK any idea when a new version that includes this fix will be released?

**Comment by JamesNK** [comment]
I don't know. Could be a week, could be a month. There are a couple more bugs I want to fix before releasing a new version.

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/releases/tag/10.0.3

**Comment by shahabhijeet** [comment]
@JamesNK thanks for speeding this up, much appreciated.

**Comment by shahabhijeet** [comment]
@JamesNK any reason the Binder property was not initialized to DefaultSerializationBinder in 11.x.x?
I was hoping legacy behavior will continue to work until you completely remove Binder property out of JsonSerializerSettings.
Any idea what version are you planning to take out all deprecated properties out of JsonSerializerSettings (TypeNameAssemblyFormat, ReferenceResolver, Binder)?

**Comment by JamesNK** [comment]
Binder has always been null in JsonSerializerSettings until set.

I don't know.
