### ISSUE TITLE
Values for Long data type deserialize to wrong value

### ISSUE THREAD

**Issue by jsytniak** [JamesNK/Newtonsoft.Json#1342]
I have created a simple C# sample that runs within LINQPad. You will see the UPC property of the Product class has the wrong value after deserializing. I cannot imagine that any special options would be needed to deserialize something this simple.

If I change the data type of UPC to string it deserializes fine.

Sample is here....
[http://share.linqpad.net/mb59os.linq](url)

**Comment by JamesNK** [comment]
A long doesn't start with leading zeros.
