### ISSUE TITLE
Serializing a DataSet with empty data tables loses all column information

### ISSUE THREAD

**Issue by harrisonbs** [JamesNK/Newtonsoft.Json#1343]
We have introduced some optimisations at work to a web service to imrpove the speed. The aim here is to serialize some data to a file to avoid going to the database if we have already made a call to the same Stored Proc with the same arguments within a cache timeout window

```
ds = DataAccess.ExecuteDataSet

Try
   If fileCache.CacheFilePath IsNot Nothing AndAlso Not File.Exists(fileCache.CacheFilePath) Then
          ds.Serialize(fileCache.CacheFilePathTemp)
          fileCache.RenameTemp()
    End If
Catch ex As Exception
    ' couldn't write to the cache? Don't want this to affect the report, so just write to the output
    ' and move on
    Debug.Print("Could not write to report cache: " + ex.Message)
End Try
```
Now consider that the DataSet contains two tables, but the tables are empty
When serialized, we get the following JSON
```
{
  "Table": [],
  "Table1": []
}
```
We have lost the following information

- The name of the table
- The name of any columns and their associated data type

The fix is as follows
1) Before outputting the Rows for each table, output the table name and columns/column data types
2) When reading the data back, add the columns and set the table name _before_ attempting to create the rows.

**Comment by harrisonbs** [comment]
Example (simplified - data types haven't been included)

```
<DataSet>
	<DataTable>
		<Name>Table</Name>
		<Columns>
			<Column>A1</Column>
			<Column>B1</Column>
			<Column>C1</Column>
			<Column>D1</Column>
			<Column>E1</Column>
		</Columns>
		<Rows></Rows>
	</DataTable>
	<DataTable>
		<Name>Table1</Name>
		<Columns>
			<Column>A2</Column>
			<Column>B2</Column>
			<Column>C2</Column>
			<Column>D2</Column>
			<Column>E2</Column>
		</Columns>
		<Rows></Rows>
	</DataTable>
</DataSet>
```
would be

```
{
  "DataSet": {
    "DataTable": [
      {
        "Name": "Table",
        "Columns": {
          "Column": [
            "A1",
            "B1",
            "C1",
            "D1",
            "E1"
          ]
        }
      },
      {
        "Name": "Table1",
        "Columns": {
          "Column": [
            "A2",
            "B2",
            "C2",
            "D2",
            "E2"
          ]
        }
      }
    ]
  }
}
```

**Comment by harrisonbs** [comment]
We need a fix by tomorrow, so I am going to write a custom class in my code. I'm hoping I can use that code to provide a fix here.

**Comment by harrisonbs** [comment]
I implemented a custom converter for dataset/datatable. Due to the fact I write out the JSON and read it back in, I was able to rely on the property order which is probably something to avoid if possible. A few thoughts on this

1) Need to create the columns BEFORE adding the rows if you want to preserve column data types.
2) To maintain backwards compatibility, there should be an option for preserving column specifications that is off by default (i.e. by default does current behavior).
3) I wanted to use a number of the existing methods be inheriting from the current class. However a number of the methods (e.g. reader.ReadAndAssert();) were unavailable to me as the methods were marked internal. If you intend to allow people to create custom converters, you should make the supporting methods used in the default implementations available to them to avoid them having to re-implement.

FTI, my output JSON was as follows

```
{
  "TestTableName": {
    "Columns": [
      {
        "Name": "Col1",
        "Type": "System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
      },
      {
        "Name": "Col2",
        "Type": "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
      }
    ],
    "Rows": [
      {
        "Col1": 1,
        "Col2": "Row1"
      },
      {
        "Col1": 2,
        "Col2": "Row2"
      }
    ]
  }
}
```

**Comment by JamesNK** [comment]
The indention of Json.NET's built in DataSet and DataTable converters is to provide a relatively idiomatic representation of JSON, and not to fully round trip all possible column information. I think you should make the changes you've made open source - I think a gist for other people to copy and reuse would be ideal - but I want the Json.NET converters to stay relatively basic.

**Comment by harrisonbs** [comment]
With all due respect, I don't think this issue should be closed. It should be fixed in the manner I said above -
 use a setting to determine if you want to preserve column information. Serializing the ROWS data only can lead to a lossy deserialization which caused a serious issue for my client because the object that was serialized and then deserialzed again was NOT equal to the original object.

> Serialization is the process of converting an object into a stream of bytes in order to store the object or transmit it to memory, a database, or a file. Its main purpose is to save the state of an object in order to be able to recreate it when needed.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/

Saying it's supposed to be near enough is good enough is not actually good enough. And if I have a solution, why wouldn't you include it back into the code in the manner highlighted?

**Comment by JamesNK** [comment]
Because I prefer the form of the current JSON, I don't have an issue with losing some data, and because it is a breaking change to anyone who expects the current JSON structure.

Some people care about clean JSON, some people care about exactly round-tripping data. Just because round-tripping is important to you doesn't mean it should be the default.

Put your converters on the web somewhere and if someone wants to perfectly round-trip a dataset then they can use what you've written.

**Comment by harrisonbs** [comment]
I never said it should be the default. I suggested that there be an option to output my format (i.e. include column data). I actually went looking for that option on settings when I first investigated the bug and was surprised it didn't exist. This should be a relatively easy change to make that won't break the existing structure.

**Comment by dleonardNetalytics** [comment]
We also are having the exact same issue.  Our application expects at least an empty data table back with the column definitions.  I agree that this should at least be an option...

**Comment by harrisonbs** [comment]
dleonardNetalytics - how are you going to address this issue?

**Comment by Kableado** [comment]
This is bullshit!
The serialization of a DataSet/DataTable to JSON should contain schema. That's the cruft of using that data structures.

**Comment by dleonardNetalytics** [comment]
We decided to move that particular WebAPI controller to XML Serialization, which does include the schema even if the table has no rows.
Its unfortunate, but we needed to get it up and running and didn't have time to write a custom converter.
We may eventually go back and do that though, just so everything is consistent.

**Comment by Kableado** [comment]
For what is worth. Our solution was to serialize to binary and transmit the data as byte[].
We see it as a dirty hack, and hope to revisit it with a better solution.

**Comment by harrisonbs** [comment]
I still believe it is possible to create a solution that is backwards compatible by
1) outputting in the old format by default and requiring an option to use the "include schema" format; and
2) reading the data back in with the appropriate deserialization method depending on which format is detected.

I guess it comes down now to the question of whether @JamesNK will revisit his decision and reopen this issue based on the additional feedback people are providing?

**Comment by JamesNK** [comment]
Add your functionality to a JsonConverter, put the package on [NuGet](https://www.nuget.org/packages?q=jsonconverter), and people who want it can use the package.

**Comment by harrisonbs** [comment]
So they have to know to go and download a different JSON Converter because the inbuilt one doesn't exhibit expected behavior for an empty data table? How is the simpler than adding a configuration based option to the existing code base which has people maintaining and extending it?

**Comment by robinsmh** [comment]
I can't believe that this is still a problem - but it is. Even more so in ASP .Net Core where use of the session state requires everything to be serialised.

We don't serialise to json because we want 'nice' clean json, we serialise because we want a json representation of ALL the relevant data. For a datatable, this must absolutely include the column names and types even if there are no rows, and it must be reversible back to an equivalent datatable when de-serialized.

PLEASE PLEASE PLEASE add an option to include the table schema in the json, otherwise what's the point of supporting DataSet/DataTable at all? It it simply not fit for purpose currently.
