### ISSUE TITLE
Slow ResolveContract with large class

### ISSUE THREAD

**Issue by heldersepu** [JamesNK/Newtonsoft.Json#1344]
ResolveContract is very slow with large classes, here is an example:
https://github.com/heldersepu/csharp-proj/tree/master/Newtonsoft_ResolveContract
On that project I have 
```c#
    public class HugeClass
    {
        public bool var10000;
        public bool var10001;
        public bool var10002;
        public bool var10003;
        public bool var10004;
//      ...
        public bool var30997;
        public bool var30998;
        public bool var30999;
    }

```
There are more than 20K of those ```bool var10000```
and it takes more than a minute to execute the ResolveContract

**Comment by WildCard65** [comment]
Resolve contract for objects iterates throw all the property and fields of the type, that iteration is probably where the slowdown is (especially if it's 20k items).

**Comment by heldersepu** [comment]
@WildCard65 
Did you look at my example?
My example also iterates through all the properties using reflection... 
and it is significantly faster (milliseconds)

**Comment by WildCard65** [comment]
@heldersepu My statement still stands as non-value types are serialized/deserialized as JSON objects, I forgot the iteration also includes creating instances of Newtonsoft.Json.Serialization.JsonProperty

**Comment by heldersepu** [comment]
@WildCard65 are you saying that is OK to take more than a minute to do such a task?

**Comment by heldersepu** [comment]
Just for kicks I added a ```new JsonProperty``` to my loop: 
https://github.com/heldersepu/csharp-proj/commit/14e351ee4378556b0d1120f1a0cb30970b0aa50b?diff=unified

...it makes almost no difference, the reflection loop runs in 6 miliseconds

```
11:52:03.703
Reflection GetProperties
11:52:03.709
ResolveContract
11:52:55.360

```

**Comment by WildCard65** [comment]
ResolveContract detects if a Contract for the type already exists, if not, it calls CreateContract.

CreateContract deduces the type of the contract, for your example, it's JsonObjectContract and calls CreateObjectContract

CreateObjectContract creates an instance of JsonObjectContract, eventually it gets to CreateProperties and calls it.

CreateProperties calls a private utils method of Json.Net to get an enumerable containing both Fields and Properties of the type.

CreateProperties iterates the obtained enumerable (for your example, it will have 20k public fields) and creates a JsonProperty instance to handle the field.

Your slowdown is in CreateProperties at that iteration moment.

**Comment by WildCard65** [comment]
Here's a screenshot of me running your example: http://prntscr.com/fk5mkx

**Comment by TylerBrinkley** [comment]
Yeah, you're not iterating through the fields.

**Comment by WildCard65** [comment]
Another thing I forgot to mention, CreateProperties also calls OrderBy and ToList which also does iteration.

**Comment by TylerBrinkley** [comment]
After profiling the biggest culprit is when Json.NET tries to find a corresponding *IsSpecified field. In my test it accounts for 62% of the time spent resolving the contract. This could be optimized by searching the type's already retrieved fields. See [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1597) for where it is in the code.

The second biggest culprit accounting for 31% of the time spent resolving the contract is that the `ThreadSafeStore` continues to create new dictionaries every time a new item is added for thread safety. See [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ThreadSafeStore.cs#L84) for where it is in the code.

**Comment by heldersepu** [comment]
Awesome work @TylerBrinkley , thanks!
I hope there are not many of those:
```csharp
Dictionary<TKey, TValue> newStore = new Dictionary<TKey, TValue>(_store);
```

<br><br>
...now the question is: Who is sending the PR? 

I can do it, I just have to setup an environment for this solution, my VS2015 did not load the Newtonsoft.Json projects, it might take me some time ...

**Comment by heldersepu** [comment]
I think that in the ```ThreadSafeStore``` the poor performance could be solved with this: 
https://github.com/heldersepu/Newtonsoft.Json/commit/ae8141279ed528d8ebe27f8d68e31669bda4de2d?diff=split

Cases where the code hits a HAVE_MEMORY_BARRIER should be a minority

**Comment by TylerBrinkley** [comment]
Perhaps the best solution for the ThreadSafeStore is for platforms that support it to use ConcurrentDictionary instead.

**Comment by heldersepu** [comment]
Looking (for the first time) at ConcurrentDictionary, very nice but it seem that it was introduced on .NET Framework 4.0 ... I think that will require additional ```#if``` statements

**Comment by heldersepu** [comment]
@TylerBrinkley 
I got my VS2017 up and running with all the dependencies for this project...
The ```ConcurrentDictionary``` is already in use in the tests:
https://github.com/JamesNK/Newtonsoft.Json/search?q=ConcurrentDictionary

But when I try adding it to the ```ThreadSafeStore.cs``` I get some issues with the 
```c#
using System.Collections.Concurrent;
```
Do we need something on the project dependencies  to use that?

**Comment by TylerBrinkley** [comment]
@heldersepu I just submitted the pull request #1346 to add support for `ConcurrentDictionary` where available which helps address this issue.

As for finding a corresponding *Specified field I don't think we'll be able to optimize that in `DefaultContractResolver` as the `CreateProperty` method cannot access the already retrieved fields and properties and as it's protected and virtual we cannot update the input parameters. The best thing that could be done is add a flag to `DefaultContractResolver` to ignore checking for *Specified fields and properties.

**Comment by heldersepu** [comment]
Thank you @TylerBrinkley 

About optimising ```DefaultContractResolver``` the retrieved fields and properties I believe are stored on [JsonPropertyCollection properties](https://github.com/JamesNK/Newtonsoft.Json/blob/8eecadd0ef5dc5ddb153a6a6f9d36f46f11ec68a/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1317) why not make that global and accessible from ```CreateProperty```

**Comment by TylerBrinkley** [comment]
`JsonPropertyCollection` is being populated by the results of `CreateProperty` so that's not an option.

**Comment by TylerBrinkley** [comment]
I just made another PR to add an `IgnoreIsSpecifiedMembers` property to `DefaultContractResolver`.

With #1346 and #1347 implemented it takes about 2 seconds to resolve the contract for your test class on my machine.

**Comment by heldersepu** [comment]
That is awesome!
But who has to set the IgnoreIsSpecifiedMembers ?

**Comment by TylerBrinkley** [comment]
Whoever is actually making calls to Json.NET's methods.

**Comment by heldersepu** [comment]
Ok let me give you a bit of background ...
This issue started when someone reported that [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) was timing out with large classes... 
I was under the impression that once this fix was in place all I needed was to get latest on Newtonsoft.Json and that was all, but I think there will be some changes needed on Swashbuckle as well... 

What will be the side effects of always having the flag IgnoreIsSpecifiedMembers = true?

**Comment by TylerBrinkley** [comment]
It simply will not conditionally serialize members with corresponding *Specified members. If you don't use the feature then it shouldn't cause any issues.

**Comment by TylerBrinkley** [comment]
Both changes were merged so I believe this issue can be closed.

**Comment by heldersepu** [comment]
@TylerBrinkley 
I wanted to add unit test for the changes but AppVeyor does not seem to have any:
https://ci.appveyor.com/project/JamesNewtonKing/newtonsoft-json/build/1.0.1246/tests
https://ci.appveyor.com/project/JamesNewtonKing/newtonsoft-json/build/1.0.1247/tests

On my local tests without the ```IgnoreIsSpecifiedMembers = true``` it was taking more than 8 seconds and after enabling it, it completes under 400 MiliSecs!

**Comment by heldersepu** [comment]
Has this been release to Nuget?

**Comment by JamesNK** [comment]
I don't know. 10.0.3 was recent so it will be months away most likely

**Comment by heldersepu** [comment]
Is the 10.0.4 in the works?
