### ISSUE TITLE
Error serializing datatable field that has value with null string

### ISSUE THREAD

**Issue by chispaK** [JamesNK/Newtonsoft.Json#1345]
Exception thrown when trying to serialize data table with a field that contains the value: "Knull Scheider". The error goes away once 'null' is removed from the string.

I am not seeing any notes on this in the documentation. Can this be fixed using some setting in the api.

### Source/destination types

Serializing System.Data.DataTable to Json

### Expected behavior

Serialize data table to Json

### Actual behavior

Error thrown
Message = "After parsing a value an unexpected character was encountered: \". Path '[5].NAME', line 1, position 9114."

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by JamesNK** [comment]
You need to include the code that reproduces the error.
