### ISSUE TITLE
How to use Surrogates with Json.NET?

### ISSUE THREAD

**Issue by EmpireWorld** [JamesNK/Newtonsoft.Json#1348]
How we can use Surrogates to serialize custom object like BinaryFormatter using Json.NET?

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#question

**Comment by EmpireWorld** [comment]
I can't ask question on Stackoverflow because i don't have enough reputation. please help me.
