### ISSUE TITLE
Add support for ModelMetadataType for dotnetcore like supported MetadataTypeAttribute in previous versions

### ISSUE THREAD

**Issue by tursoft** [JamesNK/Newtonsoft.Json#1349]
Currently it seems that **MetadataTypeAttribute** support is removed on **dotnetcore** versions but **ModelMetadataType**  is not added yet. Could you please add support for **ModelMetadataType**  to prevent backward compatibility.

Pull request is #1352

**Comment by tursoft** [comment]
As I see, only place that ModelMetadataTypeAttribute is used in **GetAssociatedMetadataType** method of **JsonTypeReflector.cs**.

Does following preprocessor **#if !(NET20 || DOTNET)** directive covers dotnetcore or not?

```c#
#if !(NET20 || DOTNET)
        private static Type GetAssociatedMetadataType(Type type)
        {
            return AssociatedMetadataTypesCache.Get(type);
        }

        private static Type GetAssociateMetadataTypeFromAttribute(Type type)
        {
            Attribute[] customAttributes = ReflectionUtils.GetAttributes(type, null, true);

            foreach (Attribute attribute in customAttributes)
            {
                Type attributeType = attribute.GetType();

                // only test on attribute type name
                // attribute assembly could change because of type forwarding, etc
                if (string.Equals(attributeType.FullName, "System.ComponentModel.DataAnnotations.MetadataTypeAttribute", StringComparison.Ordinal))
                {
                    const string metadataClassTypeName = "MetadataClassType";

                    if (_metadataTypeAttributeReflectionObject == null)
                    {
                        _metadataTypeAttributeReflectionObject = ReflectionObject.Create(attributeType, metadataClassTypeName);
                    }

                    return (Type)_metadataTypeAttributeReflectionObject.GetValue(attribute, metadataClassTypeName);
                }
            }

            return null;
        }
#endif
```

**Comment by JamesNK** [comment]
Hi

Thanks but I don't want to have dependencies on features in individual libraries. If MetadataTypeAttribute is added back to .NET Core then I will add support for it.

**Comment by tursoft** [comment]
Hi James,
Since current netcore version does not support ModelMetadataType (previously it was MetadataClassType and was supported in Newtonsoft.Json), Newtonsoft.Json library could not preserve backward compatibility. If you still do not want to add this support in dotnetcore version, at least you should add a mechanism to resolve associated metadata type (like it is in the name of the method within the library - GetAssociatedMetadataType). By this way, you still keep the library independent of external libraries (like MVC). For example, maybe we can register "AssociatedMetadataTypeRevolvers" to solve this issue?

What do you think about this solution?

Best regards..

**Comment by davidruhmann** [comment]
@JamesNK What do you think of @tursoft 's suggestion?

Sounds like a good compromise to make this library at least somewhat feature compatible across dotnet versions.

Not having the metadata attribute feature makes converter implementation much messier for partial classes.

**Comment by Albertyn** [comment]
+1

**Comment by NanoWar** [comment]
Any updates on this? We also need a way to serialize partial classes better with asp net core! 👍

**Comment by InsomniumBR** [comment]
+1
