### ISSUE TITLE
Exception: A different Id has already been assigned for value 

### ISSUE THREAD

**Issue by jogibear9988** [JamesNK/Newtonsoft.Json#1351]
I've the following Code:

    [TestFixture]
    public class Issue9999 : TestFixtureBase
    {
        public class Color
        {
            public Color()
            {
            }

            public Color(uint colorCode)
            {
                A = (byte)((colorCode & 0xff000000) >> 24);
                R = (byte)((colorCode & 0x00ff0000) >> 16);
                G = (byte)((colorCode & 0x0000ff00) >> 8);
                B = (byte)(colorCode & 0x000000ff);
            }

            public byte A { get; set; }
            public byte R { get; set; }
            public byte G { get; set; }
            public byte B { get; set; }
        }

        public static class Colors
        {
            public static Color White = new Color(0xFFFFFFFF);
        }

        [DataContract]
        public class TestClass
        {
            public TestClass()
            {
                Color = Colors.White;
            }

            [DataMember]
            public Color Color { get; set; }
        }

        [Test]
        public void Test()
        {
            var t = new List<TestClass>() {new TestClass() {Color = new Color()}, new TestClass() {Color = new Color()}};
            var settings = new JsonSerializerSettings {TypeNameHandling = TypeNameHandling.Auto, PreserveReferencesHandling = PreserveReferencesHandling.Objects};
            var json = JsonConvert.SerializeObject(t, settings);
            var obj = JsonConvert.DeserializeObject<List<TestClass>>(json, settings);
        }
    }

It fails with the following Exception: A different Id has already been assigned for value 'Newtonsoft.Json.Tests.Issues.Issue9999+Color'.

**Comment by jogibear9988** [comment]
The Problem is the Assignment of the default Value in the Constructor:

  Color = Colors.White;

**Comment by JamesNK** [comment]
Use ObjectCreationHandle.Replace

I've improved the error message https://github.com/JamesNK/Newtonsoft.Json/commit/ec10effd1ee521eb61b15a460ec80bebafbd846c

**Comment by apiovesantechgest** [comment]
Hi,
I receive that exception deserializating a complex object. the object signaled in the exception is used ONLY ONCE in the object. I can't figure out if I'm wrong or what...

I've created a test Visual Studio c#
[TestApp_JsonNetBug.zip](https://github.com/JamesNK/Newtonsoft.Json/files/2851315/TestApp_JsonNetBug.zip)
Newtonsoft not included :-)

In the solution you can find the JSON to test it separately.

Thanks,
Andrea
