### ISSUE TITLE
Xamarin: Local DateTime serialized as UTC by default

### ISSUE THREAD

**Issue by hardcodet** [JamesNK/Newtonsoft.Json#1360]
Xamarin client, Android, Json.Net 9.0.1: I have a simple DTO that contains both a `DateTime `and a `DateTimeOffset `property. The `DateTime`'s `Kind `property is `Local`. I didn't set any global serializer settings, so I would expect the `DateTime `object to be serialized without offset.

### Source/destination types

```csharp
public class TimeWindowDto
{
    public DateTime ReferenceTime { get; set; }

    public DateTimeOffset ReferenceTimeUtc { get; set; }

    public TimeWindowDirection Direction { get; set; }

    public int Minutes { get; set; }

    public void SetReferenceTime(DateTime timestamp)
    {
        ReferenceTime = timestamp;
        ReferenceTimeUtc = timestamp;
    }
}
```

### Source/destination JSON

`{"ReferenceTime":"2017-06-27T10:50:00+02:00","ReferenceTimeUtc":"2017-06-27T10:50:00+02:00","Direction":0,"Minutes":30}`

### Expected behavior

Local date time to be serialized as local date:
`"ReferenceTime": "2017-06-27T10:50:00"`

### Actual behavior

Local time serialized in UTC:
`"ReferenceTime": "2017-06-27T10:50:00+02:00"`

This means that on the receiving end, the timestamp is deserialized to a different local time (converted UTC time to the server's local time).

### Steps to reproduce

```csharp
var tw = new TimeWindowDto();
tw.SetReferenceTime(DateTime.Now);
string json = JsonConvert.SerializeObject(tw);
```

Also, I'm serializing the same DTO on the server when sent to the client. There, the JSON actually looks as I would expect it. The snippet also shows the issue this causes: Note that during deserialization on the server, the local time has been converted from 10:50 to 08:50 because of the offset.

```json
"DepartureTimeWindow": {
    "ReferenceTime": "2017-06-27T08:50:00",
    "ReferenceTimeUtc": "2017-06-27T08:50:00+02:00",
    "Direction": 0,
    "Minutes": 30
}
```

**Comment by hardcodet** [comment]
Btw, the result is the same with explicit serializer settings - I'm ending up with a UTC string just the same :/

```csharp
string json = JsonConvert.SerializeObject(w, new JsonSerializerSettings
{
    DateFormatHandling = DateFormatHandling.IsoDateFormat,
    DateTimeZoneHandling = DateTimeZoneHandling.Local
});
```

**Comment by JamesNK** [comment]
This is expected behavour.

"2017-06-27T10:50:00" isn't a local date, it is an unspecified one. Local dates are always serialized with an offset. Unspecified dates don't have an offset.
