### ISSUE TITLE
Double parsing

### ISSUE THREAD

**Issue by suntaurus** [JamesNK/Newtonsoft.Json#1362]
Hello Newtonsoft,

There is an issue parsing double array values for the number 2.5504, not sure why this number?
Try the below code and you will see 2.5504 parsed as 2.5503999999999998

         string js = "[2.8144, 2.8144, 2.6962, 2.6321, 2.5693, 2.5243, 2.5087, 2.5504, 2.535, 2.5506, 2.532, 2.491, 2.3533]";
         double[] values =(double[])JsonConvert.DeserializeObject(js, typeof(double[]));
         foreach (double dv in values)
            Console.WriteLine(dv.ToString());

//outputs
2.8144
2.8144
2.6962
2.6321
2.5693
2.5243
2.5087
2.5503999999999998
2.535
2.5506
2.532
2.491
2.3533

Regards
Sunil

**Comment by JamesNK** [comment]
Because floating point math. See http://floating-point-gui.de/

**Comment by suntaurus** [comment]
But this is straight forward parsing right? 
double.Parse("2.5504") just returns 2.5504

**Comment by JamesNK** [comment]
Are you using 10.0.1? Upgrade to the latest version and check whether it is still an issue

**Comment by suntaurus** [comment]
I am using the latest 10.0.3.21018

**Comment by JamesNK** [comment]
It works for me https://github.com/JamesNK/Newtonsoft.Json/commit/c21d2649ac748c39747c585f20572dfa76582516
