### ISSUE TITLE
Double parsing 

### ISSUE THREAD

**Issue by suntaurus** [JamesNK/Newtonsoft.Json#1363]
Hi Newtonsoft,

This is with respect to "Double parsing #1362" which is already closed. I went through the link and see what you meant with floating point calculations. But, I am bit confused.

Please can you explain? this is straight forward parsing right?
double.Parse("2.5504") just returns 2.5504. But, the below does not
string js = "[2.8144, 2.8144, 2.6962, 2.6321, 2.5693, 2.5243, 2.5087, 2.5504, 2.535, 2.5506, 2.532, 2.491, 2.3533]";
     double[] values =(double[])JsonConvert.DeserializeObject(js, typeof(double[]));
     foreach (double dv in values)
        Console.WriteLine(dv);

//outputs
2.8144
2.8144
2.6962
2.6321
2.5693
2.5243
2.5087
2.5503999999999998
2.535
2.5506
2.532
2.491
2.3533

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/1362
