### ISSUE TITLE
JsonProperty.Converter ignored during deserialization

### ISSUE THREAD

**Issue by guttley** [JamesNK/Newtonsoft.Json#1366]
Based on using 10.0.0.3

I have a use case to encrypt certain properties of a class based upon an attribute when serialized, which must also be deencrypted when deserialized.
When using a ContractResolver to detect which properties need a custom JsonConverter, serialization works very well and the correct properties are converted as expected.
However when trying to deserialize I have found that the Converter property set by the ContractResolvers is ignored.
JsonSerializerInternalReader.Deserialize line 2343 ignores the property's Converter property and attempts to create a converter based upon the property type.

**Comment by JamesNK** [comment]
JsonProperty.MemberConverter is now obsolete and JsonProperty.Converter works when serializing and deserializing https://github.com/JamesNK/Newtonsoft.Json/commit/bbbddf0031fdced348b08d2435eb2d4698f50ef3
