### ISSUE TITLE
Deserializing decimal -> removes trailing zero

### ISSUE THREAD

**Issue by FrankBirkmann** [JamesNK/Newtonsoft.Json#1367]
After migrating to Json.Net 10 the behaviour of deserializing decimals has changed.
In Json.Net 9 the trailing zeros also exists after deserialization. Not so in version 10.
The JSON string after serialization looks identical in versions 9 and 10.

### Expected behavior

I would expect that trailing zeros exists after deserialzation, e. g. 87.50

### Actual behavior

After deserialization the trailing zeros doesn't exists.

### Steps to reproduce

```csharp
var money1 = 87.50m;
Console.WriteLine($"Before Json-Serialization: {money1}");
var jsonString = JsonConvert.SerializeObject(money1);
Console.WriteLine($"Json-String: {jsonString}");
var money2 = JsonConvert.DeserializeObject<decimal>(jsonString);
Console.WriteLine($"After Json-Serialization: {money2}");
```
The console output lookes as follows:

> Before Json-Serialization: 87.50
> Json-String: 87.50
> After Json-Serialization: 87.5

With Json.Net 9 the output looks as follows:

> Before Json-Serialization: 87.50
> Json-String: 87.50
> After Json-Serialization: 87.50

**Comment by FrankBirkmann** [comment]
The place at which the decimal point is lost is the following:
Utilities/ConvertUtils.cs, line 1587

``
value /= decimalFactors[-exponent - 29];
``

e. g. value = 8750 / 100 results in 87.5

**Comment by TylerBrinkley** [comment]
I just created the PR #1368 to fix this.

**Comment by FrankBirkmann** [comment]
Thanks for the quick bug fix  :+1:

**Comment by JamesNK** [comment]
Looks good to me! Merged

**Comment by FrankBirkmann** [comment]
@JamesNK Do you know when this bugfix will be released?

**Comment by JamesNK** [comment]
In months. Stick with v9 until then.

**Comment by Brosten** [comment]
With version 11.0.2 I have a similiar issue.
"12.3" is deserialized to "12.30". 
In version 10.x this was NOT the case. (It was deserialized to 12.3)
Should I add a new issue about this?

**Comment by TylerBrinkley** [comment]
@Brosten The following results in `"12.3"` for me. Can you provide a simple repro and also include the runtime you're using?

```c#
var str = JsonConvert.DeserializeObject<decimal>("12.3").ToString();
```

**Comment by TylerBrinkley** [comment]
I'm afraid not. See [this StackOverflow question](https://stackoverflow.com/questions/34568963/how-can-i-force-a-minimum-number-of-decimal-places-in-json-net/49924144#49924144) for their implementation with a `JsonConverter`.

**Comment by abonard** [comment]
I am seeing similar truncation when using the JObject.  

using class:  
`   public class Money
		{
			public decimal Amount { get; set; }
		}`

 serializing / deserializing/ serializing
 
 
        var money1 = new Money() {Amount = 87.50m};

        Console.WriteLine($"Before Json-Serialization: {money1.Amount}");

        var jsonString = JsonConvert.SerializeObject(money1);

        Console.WriteLine($"Json-String: {jsonString}");

        var moneyJObject = JsonConvert.DeserializeObject<JObject>(jsonString);
        var amount = moneyJObject["Amount"].Value<decimal>();

        Console.WriteLine($"After Json-Serialization from JObject: {amount}");

Output:  
Before Json-Serialization: 87.50  
Json-String: {"Amount":87.50}  
After Json-Serialization from JObject: 87.5

**Comment by mvmurali5** [comment]
I am having have this issue with  when deserialize string to xmlDocument 

`XmlDocument doc = JsonConvert.DeserializeXmlNode(stringval, "Root");`
