### ISSUE TITLE
TypeNameHandling.None only effects first node

### ISSUE THREAD

**Issue by uknickwilliams** [JamesNK/Newtonsoft.Json#1376]
I am receiving some json from an external application (A). My application (B) knows nothing about any types from the A, but I do know that A serializes the classes with the `TypeNameHandling.All` setting.

I need to remove all the metadata from the json to push it out to another source, however it turns out the `TypeNameHandling.None` setting only effects the first node? Is this the expected behavior. 

This a sample to show what I mean:

    class Program
    {
        static void Main(string[] args)
        {
            JsonSerializerSettings withNamehandling = new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.All,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                PreserveReferencesHandling = PreserveReferencesHandling.All,
                Formatting = Formatting.Indented
            };

            var obj = new MyObj();

            //This is the json which my application will be receiving. My application does not know about MyObj or MyType.
            var json = JsonConvert.SerializeObject(obj, withNamehandling);
            Console.WriteLine(json);

            var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.None, Formatting = Formatting.Indented};
            var deser = JsonConvert.DeserializeObject(json, settings);
            var clean = JsonConvert.SerializeObject(deser, settings);

            Console.WriteLine(clean);

            Console.ReadLine();
        }
    }

    class MyObj
    {
        public List<MyType> Types { get; set; } = new List<MyType>()
        {
            new MyType()
            {
                Value = 5
            }
        };
    }

    class MyType
    {
        public int Value { get; set; }
    }

This will output:

```
{
  "$id": "1",
  "$type": "SerializationTest.MyObj, SerializationTest",
  "Types": {
    "$id": "2",
    "$type": "System.Collections.Generic.List`1[[SerializationTest.MyType, SerializationTest]], mscorlib",
    "$values": [
      {
        "$id": "3",
        "$type": "SerializationTest.MyType, SerializationTest",
        "Value": 5
      }
    ]
  }
}  


{
  "Types": {
    "$id": "2",
    "$type": "System.Collections.Generic.List`1[[SerializationTest.MyType, SerializationTest]], mscorlib",
    "$values": [
      {
        "$id": "3",
        "$type": "SerializationTest.MyType, SerializationTest",
        "Value": 5
      }
    ]
  }
}

```
Only the type information from the root node has disappeared

**Comment by JamesNK** [comment]
You didn't specify a type when you deserialized. It is just a raw JObject.
