### ISSUE TITLE
Make method ConvertUtils.ConvertOrCast() public available.

### ISSUE THREAD

**Issue by Horcrux7** [JamesNK/Newtonsoft.Json#1377]
JToken.ToObject(Type type) work only if the parsed result is an JToken. But there are many other cases to convert JSON primitives like string, Int32, null, etc. The method  ConvertUtils.ConvertOrCast() seems to do exact this Job. The alternative is to duplicate the code. The class JsonSerializer seems a good place for it.

Related stackoverflow question: https://stackoverflow.com/questions/45138511/how-to-convert-dynamically-in-c-sharp-the-parsed-json-result-from-json-net

**Comment by JamesNK** [comment]
If you want to use something that isn't a JToken with ToObject then convert it to a JToken first.

Json.NET is a JSON library, not a generalized object conversion library.
