### ISSUE TITLE
JSONPATH : Filter expression can't compare number properly

### ISSUE THREAD

**Issue by For2017Dev** [JamesNK/Newtonsoft.Json#1379]
Giving a JSON string :
{
  "persons": [
    {
      "name"  : "John",
      "age": "26"
    },
    {
      "name"  : "Jane",
      "age": "2"
    }
  ]
}

And a JSONPATH script :
$.persons[?(@.age > 3)]

The SelectTokens function can't find a record.

I know that age field should be a number but in practical we should be able to compare string with number like that. (Tested on http://jsonpath.com/)

Since I tried to write $.persons[?(3 < @.age)] and it doesn't work, could we just switch the comparison like 

                    case QueryOperator.GreaterThan:
                        if (rightValue.CompareTo(leftValue) < 0)
                        {
                            return true;
                        }
                        break;
 
It will have expected behavior 

Unit Test :

        [Test]
        public void BooleanExpressionTest_StringOnLeftHand_CompareWith_NumberOnRightHand()
        {
            BooleanQueryExpression e1 = new BooleanQueryExpression
            {
                Operator = QueryOperator.GreaterThan,
                Right = new JValue(3),
                Left = new List<PathFilter>
                {
                    new ArrayIndexFilter()
                }
            };

            Assert.IsTrue(e1.IsMatch(null, new JArray("2", "26")));
        }

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/ad1a13728a2f155d6b4f2ca39bcac4b9873e344a
