### ISSUE TITLE
.Net core build doesn't include DataTableConverter

### ISSUE THREAD

**Issue by steco** [JamesNK/Newtonsoft.Json#1383]
. . because of this line

#if HAVE_ADO_NET

yet I have a test .NET core project using the code from DataTableConverter which is working fine.

Is the correct fix to remove the #if, or is there something I am missing

**Comment by JamesNK** [comment]
It is in netstandard1.5 but netstandard1.3 is the highest that Json.NET supports. When a netstandard2.0 build is eventually added then I'll add support for it.

**Comment by oxxa** [comment]
Would you accept a PR to add support for netstandard2.0?  I can see how to add a new build defn to Newtonsoft.Json.csproj to support this, however, I can see it will take some research to establish which of the HAVE_XYZ constants can be added as compared to the netstandard1.3 entry.  I am interested in the DataTable support as @steco is so I could just fork and add the HAVE_ADO_NET constant as a quick fix for me but if I can help to add full netstandard2.0 support I would like to.

**Comment by JamesNK** [comment]
Hmmm, I'm not sure. I'd like to wait for a while before jumping into netstandard2.0

**Comment by oxxa** [comment]
Fair enough, I have found a couple of things have bitten me with netstandard2.0 thus far so I understand being an earlier adopter in a well used lib like yours might cause a shower of bugs you don't need yet.

**Comment by EvanCarroll** [comment]
Modern issue tracking this: https://github.com/JamesNK/Newtonsoft.Json/issues/1409
