### ISSUE TITLE
Javascript Client Library for parsing json formatted by Json.NET on client side

### ISSUE THREAD

**Issue by pmunin** [JamesNK/Newtonsoft.Json#1386]
This is feature request. If there is a duplicate please give a link in response.

Implement simple Javascript Client library that will parse Json received from server generated by Json.NET library and deserialize it to Javascript Object, supporting Class Type (resolving from .NET to JS class), references including cyclic references.

### Server code example

```csharp
public class GraphNode
{
    public List<GraphNode> Links = new List<GraphNode>();
    public string Title{get;set;}
    public int Id{get;set;}
}
//...

//MVC controller action
public ActionResult GetNodeById(int id)
{
   var node = FindNode(id);
   return Content(JsonConverter.Serialize(node, new JsonSerializationSettings(){ UseRefs=true, WriteType=true}), "application/json");
}

```

### Expected Behavior: (Client code example)

```javascript

function GraphNode()
{
    this.Id = undefined;
    this.Links=[]
    this.Title = undefined;
}

var DeserializableTypes = {
 GraphNode: GraphNode
};


$http.get("../url/getNodeById?Id=111").then(json=>Newtonsoft.Json.JsonConverter.Deserialize(json,{
resolveType: typeName=>DeserializableTypes[typeName], 
resolveReferences:true,
unknownReference: ref=>console.log("wrong reference:"+ref)
}))
.then(graphNodeWithLinks=>{
walkThroughGraph(graphNodeWithLinks);
})

```

### Actual behaviour
Developers have to find existing JS libraries, and none of those seem to have all the features in one lib.

**Comment by JamesNK** [comment]
I'm going to have to say no.

I don't have enough time for Json.NET as it is, let alone starting a new project with a new technology.

Also there is no reason I need to be the one to create this. If there is a desire for a JS library then someone else can create it independently.

**Comment by pmunin** [comment]
Fair enough. Hopefully someone can post here a link to an existing solution, I could not find any that's good enough.

**Comment by pluqueTheLuxe** [comment]
@pmunin are you looking for something like [Netflix's Falcor](https://netflix.github.io/falcor/video-tutorials/intro-to-json-graph.html)

It's not exactly like json.net serialize $ref but it's the same principle. Maybe you can extend Falcor or implement your own json.net server side IReferenceResolver 

... keep me posted

**Comment by ChainReactive** [comment]
What's the best solution to this, currently?  My quick search turned up:

- [Json-Schema-Ref-Parser.js](https://www.npmjs.com/package/json-schema-ref-parser) but it may not provide the sort of reference resolution we need.
- [dcerialize](https://www.npmjs.com/package/dcerialize) is an inactive project but seems to include needed functionality.
- [jsonreferenceresolver](https://www.npmjs.com/package/jsonreferenceresolver) deals with specific issue.  Lightweight is good, but not sure it has needed functionality.

I just started looking into this - not yet sure which may actually work.  Could anyone with experience lend some insight?
