### ISSUE TITLE
Adding int to Boolean converter 

### ISSUE THREAD

**Issue by egorikas** [JamesNK/Newtonsoft.Json#1387]
Hi! Great library!
I am using Newtonsoft.Json for a long time and I want to offer a new type of converter.
Often third-party api returns not false or true, but 1 or 0, so I face off a problem with parsing int to bool. 
I tend to think, that this is not my problem.

So, my suggestion is about adding BooleanConverter,

Will PR be welcomed?

**Comment by JamesNK** [comment]
I would prefer additional JsonConverters that don't need to be part of the core library were in separate NuGet packages. Keeping Json.NET to a reasonable size is important.

There is nothing stopping you shipping a boolean converter in your own NuGet package.
