### ISSUE TITLE
Cannot parse field with Double.MaxValue

### ISSUE THREAD

**Issue by smbecker** [JamesNK/Newtonsoft.Json#1388]
The following code fails with an exception stating "Input string '1.79769313486232E+308' is not a valid number. Path 'field', line 1, position 30".

```c#
var json = $"{{\"field\":{double.MaxValue}}}";
var obj = JObject.Parse(json);
```

Ideally, I would just change the code to format `double.MaxValue.ToString("r")`, which works without issue. Unfortunately this is an excerpt from a server that I do not control and have no power to change.

I don't suppose a special case could be put in [here](https://github.com/JamesNK/Newtonsoft.Json/blob/403470d59ad7f6e00dbfcdfafee8dce2ec43a46a/Src/Newtonsoft.Json/JsonTextReader.cs#L2152) to account for `double.MaxValue.ToString()` and `double.MinValue.ToString()`? I am happy to submit a PR for that if it is something that you would consider.

**Comment by JamesNK** [comment]
The problem is that string has to rounded so that it is no longer valid. I want to avoid changing parsing of floating point numbers. Every change opens up unknown cans of worms.
