### ISSUE TITLE
First Member of Enum is skipped while serialization

### ISSUE THREAD

**Issue by JayeshBhanderi** [JamesNK/Newtonsoft.Json#1389]
**First member of Enum is skipped while serializing Class to json.**
**For example**
              public enum TestEnum
              {
                   Value1,
                   Value2
              }
        public class Sample
        {
            public string FirstItem { get; set; }
            [JsonConverter(typeof(StringEnumConverter))]
            public TestEnum SecondItem { get; set; }
        }
          . . . 
             Sample s = new Sample();
             s.FirstItem = "first item value";
             s.SecondItem = TestEnum.Value1;

           string json = JsonConvert.SerializeObject(s, Formatting.Indented, new JsonSerializerSettings { 
                                 DefaultValueHandling = DefaultValueHandling.Ignore });

             Console.Write(json);
       . . .
       

Output:
{
"FirstItem": "first item value"
}

**here, SecondItem member of Sample class  is  assigned with  first member of  TestEnum and ignored in resulted json string.**

**This happens with First Member of Enum. If i want to use first member of than i have to add dummy member at first position in Enum declaration.**

**is there any issue ?**

**Comment by TylerBrinkley** [comment]
It's that you're using `DefaultValueHandling.Ignore` which since you didn't explicitly give `TestEnum.Value1` a value it has the value of 0 which is the default and so is ignored.

**Comment by JayeshBhanderi** [comment]
Thanks.
i understand the problem.
it is little bit confusing to use DefaultValueHandling. i want to use both Enum and  `DefaultValueHandling.Ignore` for other class member so i have changed the declaration of my Enum as of now to overcome my problem with following:
`public enum EnumValue
        {
            Value1=1,
            Value2=2
        }`
now it works perfactly!

DefaultValueHandling also ignores member that contains default value which is assigned explicitly.

**What is the alternative to DefaultValueHandling  to ignore any member during serialization **only**  if it is not explicitly assigned?** (i have tried to find solution on http://www.newtonsoft.com/json/help but didn't get solution)

**for example:** in above case it should ignore `TestEnum.Value1` in resulted json string only if `s.SecondItem = TestEnum.Value1;` is not assigned.

**Comment by JamesNK** [comment]
The solution is DefaultValueHandling. You need to not use zero as an enum value, because that is the default value.

**Comment by JayeshBhanderi** [comment]
```
public class Sample
{
  public string Optional {get; set;}
  public bool Flag{ get; set;}
}
```
but suppose i want to ignore `Optional` in resulted json if it is not provided and `objSample.Flag = false;`  than how it could be achieved ?

If i use  `DefaultValueHandling = DefaultValueHandling.Ignore ` than **Flag is also ignored**. 
**Is there any way that member is not ignored if it is assigned explicitly with default value ?**

**Comment by JamesNK** [comment]
No

**Comment by JayeshBhanderi** [comment]
thanks for providing your valuable time to type No

i found the solution to my problem.
 `[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]` instead of DefaultValueHandling
