### ISSUE TITLE
"{\"IsComplete\":\"1\"}"

### ISSUE THREAD

**Issue by KenneyChen** [JamesNK/Newtonsoft.Json#1392]
right："{\"IsComplete\":1}"
error：{\"IsComplete\":\"1\"}

can  the string type to type bool

public static T FromJsonTo<T>(string jsonString)
        {
            if (string.IsNullOrEmpty(jsonString))
                return default(T);
            var json = new JsonSerializer
            {
                NullValueHandling = NullValueHandling.Ignore,
                ObjectCreationHandling = ObjectCreationHandling.Replace,
                MissingMemberHandling = MissingMemberHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            using (MiniProfiler.Current.Step("T FromJsonTo#T(string jsonString)"))
            {
                using (var sr = new StringReader(jsonString))
                {
                    using (var reader = new JsonTextReader(sr))
                    {
                        var result = json.Deserialize<T>(reader);
                        return result;
                    }
                }
            }
        }

**Comment by JamesNK** [comment]
You would need to write a JsonConverter to go from "1" to a boolean.
