### ISSUE TITLE
Json.net duplicate field when use JsonExtensionData + DefaultValueHandling.Ignore

### ISSUE THREAD

**Issue by crab312** [JamesNK/Newtonsoft.Json#1394]
Hello
I have following input json: {\"Sum\":1.0,\"Premium\":0}
And I got following output json: {"Sum":200.0,"Premium":340.0,"Premium":0.0}
Expected result: {"Sum":200.0,"Premium":340.0}

Json.Net version 10.0.2

I hope my code explains issue sufficiently

```
        class Policy
        {
            public decimal Sum { get; set; }

            public decimal Premium { get; set; }

            [JsonExtensionData]
            public IDictionary<string, JToken> JsonExtensionData { get; set; }
        }

        static void Main(string[] args)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                DefaultValueHandling = DefaultValueHandling.Ignore,
            };

            string policyJson = "{\"Sum\":1.0,\"Premium\":0}";

            var policyJObj = JObject.Parse(policyJson); 
            var policy = policyJObj.ToObject<Policy>();  //field "Premium" contained in extension data. WHY?
            policy.Sum = 200;
            policy.Premium = 340;

            var policyJson_v1 = JsonConvert.SerializeObject(policy); //{"Sum":200.0,"Premium":340.0,"Premium":0.0}
            var policyJson_v2 = JObject.FromObject(policy).ToString(); 

            Debugger.Break();
        }
```

JsonExtensionData filled only if setted DefaultValueHandling = DefaultValueHandling.Ignore
If i comment out //DefaultValueHandling = DefaultValueHandling.Ignore then issue disappears

**Comment by JamesNK** [comment]
This is expected behavour. Extension data contains anything that isn't set to a property.

DefaultValueHandling.IgnoreAndPopulate might work.

http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm
