### ISSUE TITLE
JsonTextReader handling undefined tokens when supporting multiple content

### ISSUE THREAD

**Issue by venkatgct** [JamesNK/Newtonsoft.Json#1396]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
        public static void HandleInvalidTokens()
        {
            using (var stringReader = new StringReader(","))
            using (var jsonReader = new JsonTextReader(stringReader))
            {
                jsonReader.SupportMultipleContent = true;
                while (jsonReader.Read())
                {
                    Console.WriteLine("line: {0}, position: {1}, tokenType: {2}", jsonReader.LineNumber, jsonReader.LinePosition, jsonReader.TokenType);
                }
            }
        }
```

### Expected behavior
Throw a JsonReaderException

### Actual behavior
The code went into a infinite loop and the line number and position never changes.
If you replace the input string to "true false", then you get exactly two tokens.

### Steps to reproduce
Run the snippet above.

**Comment by JamesNK** [comment]
Since 10.0.3 I improved SupportMultipleContent. Your sample already runs on the latest source code - https://github.com/JamesNK/Newtonsoft.Json/commit/725e808db919afb781dbf2cc842fae39568e9b95

**Comment by KevinWrightCatDaddy** [comment]
I am using 10.0.3 and I'm getting the infinite loop mentioned above.  

            string json = @"{'name':'Joe','job':'admin'},{'name':'steve','job':'publisher'}";
            IList<Role> roles = new List<Role>();
            using (var stringReader = new StringReader(","))  {
                using (var jsonReader = new JsonTextReader(new StringReader(json)))   {
                    jsonReader.SupportMultipleContent = true;
                    while (true)   {
                        if (!jsonReader.Read())  {
                            break;
                        }
                        while (jsonReader.TokenType == JsonToken.Undefined)  {
                            jsonReader.Read();
                        }
                        JsonSerializer serializer = new JsonSerializer();
                        Role role = serializer.Deserialize<Role>(jsonReader);
                        roles.Add(role);
                    }
                }
            }
