### ISSUE TITLE
Proposal to consolidate csproj files to a single .NET SDK style project

### ISSUE THREAD

**Issue by AArnott** [JamesNK/Newtonsoft.Json#1402]
With VS 2017 (and the dotnet CLI) comes the ability to have a single project target multiple frameworks and have a far simpler project file.

I'm preparing a change to this repo to migrate to it. Would you entertain a PR?

**Comment by TylerBrinkley** [comment]
This was already done for Json.NET [here](https://github.com/JamesNK/Newtonsoft.Json/commit/64124e6edd10ac672fc754596baadce490e66091). Maybe this was posted in the wrong repo?

**Comment by AArnott** [comment]
Ah! Thanks. I was looking at the 9.0.1 release's source code.
