### ISSUE TITLE
Yielding property with extension data will throw on deserialization

### ISSUE THREAD

**Issue by ayende** [JamesNK/Newtonsoft.Json#1406]
This looks like a regression of: https://github.com/JamesNK/Newtonsoft.Json/issues/701

When we have a contract that specify ExtensionDataSetter, it breaks deserialization. 

### Source/destination JSON

`{"Age":0,"Foo":{"$type":"Item+<get_Foo>d__5, Tryouts","$values":["foo","bar"]}}`

### Expected behavior

Should not throw

### Actual behavior

An exception is thrown

`Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error setting value in extension data for type 'Item'. Path 'Foo.$values', line 1, position 65. ---> Newtonsoft.Json.JsonSerializationException: Cannot create and populate list type Item+<get_Foo>d__5. Path 'Foo.$values', line 1, position 65.`

### Steps to reproduce

```csharp

public class TestCase
{
    public class MyContractResolver : DefaultContractResolver
    {

        protected override JsonObjectContract CreateObjectContract(Type objectType)
        {
            var jsonObjectContract = base.CreateObjectContract(objectType);
            jsonObjectContract.ExtensionDataSetter += (o, key, value) =>
            {
                Console.WriteLine(key);
            };
            return jsonObjectContract;
        }
    }
    public class Item
    {
        public int Age { get; set; }
        public IEnumerable<string> Foo
        {
            get { yield return "foo"; yield return "bar"; }
        }
    }

    [Fact]
    public void ShouldBeAbleToUseExtensionDataOnYieldingProperties()
    {
        var jsonSerializer = new JsonSerializer
        {
            TypeNameHandling = TypeNameHandling.Auto
        };
        jsonSerializer.ContractResolver = new MyContractResolver();
        var stringWriter = new StringWriter();
        jsonSerializer.Serialize(stringWriter, new Item());
        var str = stringWriter.GetStringBuilder().ToString();
        jsonSerializer.Deserialize<Item>(new JsonTextReader(new StringReader(str)));
    }
}
```

**Comment by ayende** [comment]
For reference, this can be worked around in the contract resolver with:

`jsonObjectContract.ExtensionDataValueType = typeof(JToken);`

This is just fine for my purposes, I'm leaving the issue open so it can be reviewed for whatever this is expected behavior or not.

**Comment by JamesNK** [comment]
I don't think this is a regression. You are using Json.NET differently compared to the other issue. Using the delegate means that Json.NET doesn't know what to convert the type to, so it uses the $type which fails because that type can't be created. Your workaround is what the contract resolver in the other example is doing automatically by looking at the collection.

It isn't ideal but I think this is expected behavior.
