### ISSUE TITLE
Possible NullReferenceException

### ISSUE THREAD

**Issue by SanSYS** [JamesNK/Newtonsoft.Json#1414]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/JavaScriptUtils.cs#L258-L266

![image](https://user-images.githubusercontent.com/5781038/29882691-436d7816-8dc7-11e7-9473-05ca30aea6ae.png)

**Comment by JamesNK** [comment]
It will never be null because of this - https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/JavaScriptUtils.cs#L228-L236

I've added an assert to make it clearer - https://github.com/JamesNK/Newtonsoft.Json/commit/f1d721d86920fb1502dd75de9df4fb717f4f1a57
