### ISSUE TITLE
OverrideSpecifiedNames seems to be ignored during serialization

### ISSUE THREAD

**Issue by mlowijs** [JamesNK/Newtonsoft.Json#1424]
### Source/destination types

```csharp
class MyObject
{
    public int Id { get; set; }

    [JsonProperty("DeCoRatEd_proPerTY")]
    public string DecoratedProperty { get; set; }
}
```

### Source/destination JSON

```javascript
{"id":123,"deCoRatEd_proPerTY":"hello there"}
```

### Expected behavior

I expect the serialized JSON to ignore the `JsonProperty` attribute and serialize the `DecoratedProperty` property as `decoratedProperty`.

### Actual behavior

See destination JSON above.

### Steps to reproduce

```csharp
var myInstance = new MyObject { Id = 123, DecoratedProperty = "hello there" };

var settings = new JsonSerializerSettings
{
    ContractResolver = new CamelCasePropertyNamesContractResolver // or DefaultContractResolver
    {
        NamingStrategy = new CamelCaseNamingStrategy(true, true)
    }
};

var result = JsonConvert.SerializeObject(myInstance, settings);
```

**Comment by JamesNK** [comment]
OverrideSpecifiedNames isn't ignored. The setting controls whether the naming standard is applied to DeCoRatEd_proPerTY.

True: *d*eCoRatEd_proPerTY
False: *D*eCoRatEd_proPerTY

Remove the [JsonProperty] if you don't want that name when serializing.

**Comment by mlowijs** [comment]
I see. The summary on that property confused me a little, because:

```csharp
/// A flag indicating whether explicitly specified property names,
/// e.g. a property name customized with a <see cref="JsonPropertyAttribute"/>, should be processed.
```
...to me indicates that the attribute is not processed at all during serialization.

I do need the `JsonProperty` during deserialization, but I could implement my own `NamingStrategy` instead.
