### ISSUE TITLE
Add ItemNullValueHandling to JsonContainerAttribute

### ISSUE THREAD

**Issue by TylerBrinkley** [JamesNK/Newtonsoft.Json#1429]
Most of the time I use `NullValueHandling.Ignore` globally as I don't have a need for `null` to be represented in the json. However, now working on an api client library which needs `null`s I find it inconvenient to have to specify `NullValueHandling.Ignore` on each property of whole classes that can't have serialized `null` properties. I would appreciate it if an `ItemNullValueHandling` property was added to `JsonContainerAttribute` that controls the `NullValueHandling` for each property. I would suppose it should work for collections as well.

### Current

```csharp
class ClassWithNoSerializedNulls
{
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public string A { get; set; }
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public ConsoleColor? B { get; set; }
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public DateTime? C { get; set; }
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public Version D { get; set; }
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public Uri E { get; set; }
}
```

### Would Like

```csharp
[JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
class ClassWithNoSerializedNulls
{
    public string A { get; set; }
    public ConsoleColor? B { get; set; }
    public DateTime? C { get; set; }
    public Version D { get; set; }
    public Uri E { get; set; }
}
```

**Comment by JamesNK** [comment]
That would be a worthwhile feature. Should also add ItemNullValueHandling to JsonPropertyAttribute at the same time.

**Comment by mdg1019** [comment]
I'm working on a large project and would save me a lot of pain.

**Comment by paulirwin** [comment]
+1 for this. Wouldn't naming it `NullValueHandling` rather than `ItemNullValueHandling` help it match the same property on `JsonSerializerSettings` and `JsonPropertyAttribute`? I don't think the `Item` prefix is necessary as since the attribute is at the class level that would imply that the setting applies to its members. (In other words, if the object itself were null, the attribute wouldn't apply anyways.)

And @JamesNK - `JsonPropertyAttribute` already has `NullValueHandling`. What would the difference of `ItemNullValueHandling` be?

**Comment by TylerBrinkley** [comment]
@paulirwin The name `ItemNullValueHandling` refers to the `NullValueHandling` of the items or properties of a type and matches the existing `ItemTypeNameHandling` and `ItemReferenceLoopHandling` properties. Naming it `NullValueHandling` would imply that when serializing objects of the given type the serializer would use the specified `NullValueHandling`.

**Comment by paulirwin** [comment]
@TylerBrinkley I disagree with the last sentence but the first one about consistency makes sense and is good justification for the name. I'll update the PR.
