### ISSUE TITLE
Improve behaviour of reference handling when $id node was not deserialized

### ISSUE THREAD

**Issue by aKzenT** [JamesNK/Newtonsoft.Json#1434]
Currently deserialization with $id / $ref only seems to work correctly, when the node containing the $id was actually deserialized to a .NET object (e.g. not skipped because property didn't exist, etc.). If this is not the case, all later $refs will not resolve (see below for example).

This can lead to subtle errors. For example consider a client/server scenario where objects are transferred between server and client using JSON.NET and where object graphs using $id/$ref are necessary. Addings a new property on the server side can suddenly make older clients fail if the new property happens to contain the first instance of an object used elsewhere in the tree.

Since creation of $id/$ref happens automatically during serialization and we can't really know in advance which instance will be the first one ($id) and which are the other ones ($ref), successfull deserialization is really undeterministic.

My suggestion is to make the deserializer smart enough to detect this situation by remembering $id nodes which have been skipped during deserialization. When encountering a matching $ref tag, deserialization should use the original node instead for deserialization.

Alternatively there should at least be some way to implement this behavior using the extension mechanisms of JSON .NET.

### Source/destination types

```csharp
public class Test
{
	//public Item ItemA { get; set; }
	public Item ItemB { get; set; }
}

public class Item
{
	public string Message { get; set; }
}
```

### Source/destination JSON

```javascript
{ "ItemA": { "$id": "test", "message": "hello" }, "ItemB": { "$ref": "test" } }
```

### Expected behavior
ItemB should be set to an instance with message "hello", even if ItemA was not mapped.

### Actual behavior
ItemB is null

**Comment by JamesNK** [comment]
This feature isn't possible because Json.NET doesn't save the content it ignores to maybe serialize it later. Once it is read past then it is gone.

I would suggest loading JSON into a JObject and resolve references yourself before passing the content to the serializer.
