### ISSUE TITLE
setting MemoryTraceWriter with reader.SupportMultipleContent = true  raise an exception: No token to close. Path ''.

### ISSUE THREAD

**Issue by moh-hassan** [JamesNK/Newtonsoft.Json#1436]
Running the example: [Read Multiple Fragments With JsonReader](https://www.newtonsoft.com/json/help/html/ReadMultipleContentWithJsonReader.htm)  of setting the serializer  `reader.SupportMultipleContent = true` , is working fine

In case of setting the serializer with TraceWriter as given below:

				JsonSerializer serializer = new JsonSerializer();
				//the next line raise an exception
				serializer.TraceWriter = traceWriter;

an exception ' is raised 
**Error Thrown**

> No token to close. Path '.

If I comment the line of TraceWriter, the exception disappear.

**You can produce the exception error using the next code:**

		public class Program
		{
			public static void Main()
			{
				Console.WriteLine("reader.SupportMultipleContent=true with MemoryTraceReader");
				string json = @"{ 'name': 'Admin' }{ 'name': 'Publisher' }";
				IList<Role> roles = new List<Role>();
				JsonTextReader reader = new JsonTextReader(new StringReader(json));
				reader.SupportMultipleContent = true;
				ITraceWriter traceWriter = new MemoryTraceWriter();
				while (true)
				{
					if (!reader.Read())
					{
						break;
					}
					JsonSerializer serializer = new JsonSerializer();
					//the next line raise an exception
					serializer.TraceWriter = traceWriter;
					Role role = serializer.Deserialize<Role>(reader);
					roles.Add(role);
				}
				foreach (Role role in roles)
				{
					Console.WriteLine(role.Name);
				}
				// Admin
				// Publishe
			}
		}

		class Role
		{
			public string Name {get;set;}
		}
		
check online  [fiddler](https://dotnetfiddle.net/DDHXIc)
version used: v10.0.3

**Comment by JamesNK** [comment]
Thanks for reporting this. Fixed - https://github.com/JamesNK/Newtonsoft.Json/commit/6057d9b83126315e441711b5672776f36bdc3afa
