### ISSUE TITLE
WritePropertyName() method in JsonWriter disregard parameter

### ISSUE THREAD

**Issue by ie-zero** [JamesNK/Newtonsoft.Json#1441]
### Source/destination types
The implementation of the method ```WritePropertyName(string name, bool escape)``` in ```JsonWriter``` completely disregard the escape parameter. 

### Source/destination JSON
[Not Relevant]

### Expected implementation
```csharp
public virtual void WritePropertyName(string name, bool escape) {
  // Change the behaviour of the method based on the value of the escape parameter.
}
```
Otherwise, the method might be removed as it signals a contract which can never be fulfilled. 

### Actual implementation 
```csharp
public virtual void WritePropertyName(string name, bool escape) {
  WritePropertyName(name);
}
```

**Comment by JamesNK** [comment]
The flag doesn't mean anything on the base writer. It is virtual so implementations of JsonWriter can choose whether to escape the name, e.g. JsonTextWriter

https://github.com/JamesNK/Newtonsoft.Json/blob/55afb9aa72a07494aa35015dd2a29f7e9643127f/Src/Newtonsoft.Json/JsonTextWriter.cs#L281-L305
