### ISSUE TITLE
Newtonsoft dependencies incompatible with latest Xamarin.Android.Support.*

### ISSUE THREAD

**Issue by Enoges** [JamesNK/Newtonsoft.Json#1443]
### Expected behavior
Install Newtonsoft.Json in a Xamarin.Forms PCL project with the version of Xamarin.Android.Suport.* v25.4.2 without problem

### Actual behavior
When I try to install Newtonsoft.Json in a XamarinForms PCL project whith latest version of Xamarin.Android.Support.* I received an error of dependencies incompatibility.

### Steps to reproduce
Install Xamarin.Android.Support.* 25.4.2 from Nugget package.
Try to instal Newtonsoft.Json version 10.0.3.

Thanks a lot.

**Comment by JamesNK** [comment]
Newtonsoft.Json supports .NET Standard 1.0 so it is likely support missing in Xamarin Forms. I've copied this issue to their project.
