### ISSUE TITLE
SerializeObject object[][] don't execute : "Operation is not supported on this platform."

### ISSUE THREAD

**Issue by haijiandong** [JamesNK/Newtonsoft.Json#1445]
My operating environment:
- .Net Core Version: 2.0
- VS Version : 2015.3.3
- OS : Windows 10 Pro 1703
- Newtonsoft Version : 10.0.0.0

I want to a `string[][]` to serialize the `string`, but i got a error:"Operation is not supported on this platform."
![image](https://user-images.githubusercontent.com/12838659/30899462-8ba39dc8-a392-11e7-817d-e2349d10f1b4.png)
![image](https://user-images.githubusercontent.com/12838659/30899637-4036c5b2-a393-11e7-9900-9c60a3d267ac.png)
![image](https://user-images.githubusercontent.com/12838659/30899567-f43c3412-a392-11e7-9ad9-5df9eb0c5cd2.png)
Isn't Newtonsoft support .net core 2.0?
I need help.

**Comment by haijiandong** [comment]
I am using a clumsy  way:
```cSharp
public static class Extensions
{
        public static string[][] AsStringArrays(this object[][] objs)
        {
            var strs = new string[objs.Length][];
            for (var i = 0; i < objs.Length; i++)
            {
                strs[i] = new string[objs[i].Length];
                for (var j = 0; j < objs[i].Length; j++)
                {
                    try
                    {
                        var flag = objs[i][j].GetType().Name == "DBNull";
                        strs[i][j] = flag ? null : objs[i][j].ToString();
                    }
                    catch (Exception)
                    {
                        return strs;
                    }
                }
            }
            return strs;
        }
}
```
```cSharp
var jsonStr = JsonConvert.SerializeObject(objArray.AsStringArrays());
```
Can work temporarily.

**Comment by JamesNK** [comment]
This will be fixed in the next version - https://github.com/JamesNK/Newtonsoft.Json/commit/4494e523d52e4f81deece295431c7fe3ba8b27c0
