### ISSUE TITLE
why .net core not support DataTableConverter

### ISSUE THREAD

**Issue by lxdong** [JamesNK/Newtonsoft.Json#1447]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by moh-hassan** [comment]
.netcore 2 reference .netstandard1.3 which doesn't support DataTable /DataSet converters.
You can find a workaround solution in [#1409](https://github.com/JamesNK/Newtonsoft.Json/issues/1409)

**Comment by JamesNK** [comment]
It will be fixed with a netstandard20 assembly - https://github.com/JamesNK/Newtonsoft.Json/commit/ab3315f1d5e57c70203c904be79d8e951bf09794
