### ISSUE TITLE
Please add appropriate `import` directive on the main page

### ISSUE THREAD

**Issue by pkese** [JamesNK/Newtonsoft.Json#1448]
It is unclear what needs to be imported in order to use `JsonConvert`

Is it `import Json.Net` or `import Json.NET` or is it `import Newtonsoft` or `import Newtonsoft.Json` or just `import Json`?

There's plenty space on the https://www.newtonsoft.com/json samples to add another line and make it clear.

**Comment by JamesNK** [comment]
If you're lost at that level then go to https://www.newtonsoft.com/json/help/html/R_Project_Documentation.htm
