### ISSUE TITLE
Some JTokenTypes are not Differentiable

### ISSUE THREAD

**Issue by timeracers** [JamesNK/Newtonsoft.Json#1449]
JTokenTypes like Guid and Uri is not distinguishable from String when serialized, as such they should be removed.

The problem is you will get differing results from deployment and testing if you don't realize that when deserialized it changes to the more general type even though it was more specific.

#### Steps to reproduce

```csharp
var payload = new JObject();
payload["sub"] = Guid.Empty;
var serializedPayload = payload.ToString();
var deserializedPayload = JsonConvert.DeserializeObject<JObject>(serializedPayload);

var result1 = payload["sub"].Type == JTokenType.Guid;
var result2 = deserializedPayload["sub"].Type == JTokenType.Guid;

Assert.IsTrue(result1 == result2);
```

**Comment by moh-hassan** [comment]
>That's because there is no way for Json.NET to know that it should be a GUID. It's just a string when parsing.
>Cast instead of using Value<Guid>(), e.g. (Guid)obj["id"]

Reference: [Guid becomes string in JObject.ToString + JObject.Parse #1060 ](https://github.com/JamesNK/Newtonsoft.Json/issues/1060#issuecomment-256472299)

**Comment by JamesNK** [comment]
> JTokenTypes like Guid and Uri is not distinguishable from String when serialized, as such they should be removed.

So is date. So it decimal and double. But if that information isn't kept then errors, especially to do with floating point numbers, creep in when values are cast back to their original type.
