### ISSUE TITLE
SelectTokens result difference when using a filter in the JsonPath

### ISSUE THREAD

**Issue by softeering** [JamesNK/Newtonsoft.Json#1453]
Hi,

Any idea / explanation about why these 2 selectors do not return the same kind of objects?
I thought they would both return the objects under the "entries" item, filtered or not depending on the json path passed to the SelectTokens method.

Thanks in advance

```
string json = @"
{
    ""entries"": [
	{
		""id"": ""idoftheenableditem"",
		""enabled"": true
	},
        {
		""id"": ""idofthedisableditem"",
		""enabled"": false
	},
        {
		""id"": ""idofanotherenableditem"",
		""enabled"": true
	}
    ]
}";

// itemsWithoutFilter contains 3 items (all json object found under entries array)
var itemsWithoutFilter = JToken.Parse(json).SelectTokens("$.entries", false).Children().ToArray();
// itemsWithFilter contains the attributes of the 2 enabled objects instead of the objects themselves
var itemsWithFilter = JToken.Parse(json).SelectTokens("$.entries[?(@.enabled == true)]", false).Children().ToArray();
```

**Comment by daivdqiu** [comment]
When you do a filter, it traverses into the children already so you do not need to call the .children when selecting the tokens. 
var itemsWithFilter = JToken.Parse(json).SelectTokens("$.entries[?(@.enabled==true)]", false).ToArray();
This will return the same objects

**Comment by softeering** [comment]
Thanks @daivdqiu 
Got your point and also realized that I was wrong with my Json Path in the first place. Should have been this to be consistent and not call .Children() at all:

```csharp
// itemsWithoutFilter contains 3 items (all json object found under entries array)
var itemsWithoutFilter = JToken.Parse(json).SelectTokens("$.entries[*]", false).ToArray();
// itemsWithFilter contains the attributes of the 2 enabled objects instead of the objects themselves
var itemsWithFilter = JToken.Parse(json).SelectTokens("$.entries[?(@.enabled == true)]", false).ToArray();
```

**Comment by JamesNK** [comment]
I'm guessing not a bug

**Comment by softeering** [comment]
Sure not 
Thanks guys
