### ISSUE TITLE
Parse CultureInfo no longer supported in .NET Core

### ISSUE THREAD

**Issue by viktor-morin** [JamesNK/Newtonsoft.Json#1457]
Hi,

We are now chaning to .NET Core and we get following error when trying to parse a following class:

`Dictionary<CultureInfo,string>`

> ArgumentException: Could not cast or convert from System.String to System.Globalization.CultureInfo.
Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)

> JsonSerializationException: Error converting value "en-US" to type 'System.Globalization.CultureInfo'. Path 'Name.en-US', line 1, position 17.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)

> JsonSerializationException: Could not convert string 'en-US' to dictionary key type 'System.Globalization.CultureInfo'. Create a TypeConverter to convert from the string to the key type object. Path 'Name.en-US', line 1, position 17.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, string id)

This is working in .NET Framwork.
I have written my own JsonConverter meanwhile, but wonder if the support will be available again?
Greetings

**Comment by viktor-morin** [comment]
Example of object trying to parse:

`{
	"Name": {
		"en-US": "Hi",
		"sv-SE": "Hej"
		}
}
`

**Comment by JamesNK** [comment]
I investigated this and Newtonsoft.Json is successfully getting the TypeConverter for CultureInfo but the converter in .NET Core doesn't support converting from a string. You should raise an issue with Microsoft.

**Comment by viktor-morin** [comment]
Thanks for the response. 
In the meanwhile we are usign a `Dictionary<string,string>` instead where we return values as `Dictionary<CultureInfo,string>`.
I will try find a forum to ask Microsoft about this.
Greetings

**Comment by JobaDiniz** [comment]
Has this been fixed? I'm getting the same error
```
Message: 
    Newtonsoft.Json.JsonSerializationException : Error converting value "pt-BR" to type 'System.Globalization.CultureInfo'. Path '[0].language', line 3, position 23.
    ---- System.ArgumentException : Could not cast or convert from System.String to System.Globalization.CultureInfo.

  Stack Trace: 
    JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
    JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
    JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
    JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
    JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
    JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
    JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    JsonSerializer.Deserialize(JsonReader reader, Type objectType)
    JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
    JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
    JsonConvert.DeserializeObject[T](String value)
    JsonFileDataAttribute.GetData(MethodInfo testMethod) line 29
    ----- Inner Stack Trace -----
    ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
    ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
    JsonSerializerInternalReader.EnsureType(JsonReader reader, Obje
```
