### ISSUE TITLE
Why do I need binding redirects when I use backward compatible methods?

### ISSUE THREAD

**Issue by bhedia** [JamesNK/Newtonsoft.Json#1458]
I have a few internal company nugets of my own which use Newtonsoft.Json for serialization. I recently updated the references of all those Nugets/DLLs to use Newtonsoft 10, however they only use the following method (which has existed in version 9 too), so they should work with Newtonsoft 9 too.

```csharp
JsonConvert.SerializeObject(object)
```

Now when I use these Nugets in other applications which have Newtonsoft 9 installed, the execution fails with the following exception:

System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

When I add a binding redirect, the app works fine.

```xml
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
```
Why do I need a binding redirect in this case? I'm using backward compatible functions of Newtonsoft 10, and Newtonsoft ends up being a secondary reference for the final application, so it should be ok with whatever version I give it as long as the method exists.

**Comment by JamesNK** [comment]
An explanation here - https://stackoverflow.com/questions/29717340/when-do-i-have-to-use-binding-redirects

**Comment by bhedia** [comment]
Thanks, I didn't realize the version of the dependency is written into the DLL. Apologies for creating the issue.
