### ISSUE TITLE
Throw System.NullReferenceException when I serializing a DataSet

### ISSUE THREAD

**Issue by qtzheng** [JamesNK/Newtonsoft.Json#1460]
### MySQL Table Script
```sql
CREATE TABLE `user` (
`sys_id`  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`user_id`  varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`sap_id`  char(8) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`user_name`  varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`password`  char(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`salt`  char(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`status`  tinyint(2) NOT NULL ,
`org_id`  int(6) NOT NULL ,
`std_id`  varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`last_login`  datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ,
`login_count`  int(11) NOT NULL ,
`create_time`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`create_user_id`  varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`create_user_name`  varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`update_time`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`update_user_id`  varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`update_user_name`  varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
PRIMARY KEY (`sys_id`, `user_id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_bin
ROW_FORMAT=DYNAMIC
;
```
### Source/destination types

```csharp
            DataSet ds = new DataSet();
            using (DbConnection conn = this.EfContext.Database.Connection)
            {
                conn.Open();
                DbCommand cmd = conn.CreateCommand();
                cmd.CommandText = "select * from user";
                cmd.CommandType = CommandType.Text;
                cmd.Parameters.AddRange(parameters);
                MySqlDataAdapter da = new MySqlDataAdapter(cmd as MySqlCommand);
                da.Fill(ds);
                conn.Close();
                cmd.Parameters.Clear();
            }
            var json=JsonConvert.SerializeObject(ds);
```
### Exception
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Newtonsoft.Json.JsonWriter.CreateUnsupportedTypeException(JsonWriter writer, Object value)
   在 Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   在 Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(JsonWriter writer, Object value, JsonPrimitiveContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal(JsonWriter jsonWriter, Object value, Type rootType)
   在 Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   在 Newtonsoft.Json.Converters.DataTableConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   在 Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.SerializeObject(Object value)

**Comment by JamesNK** [comment]
Thanks for reporting this. I think it is fixed - https://github.com/JamesNK/Newtonsoft.Json/commit/90976eb6ededdd07c34293c325ed32462745da4c
