### ISSUE TITLE
TraceWriter breaks serialization

### ISSUE THREAD

**Issue by volak** [JamesNK/Newtonsoft.Json#1461]
Ran into an issue where setting a TraceWriter on my serialization settings breaks serialization.
Similar to issue #793 

I setup a small repoducable repo here as requested: https://github.com/volak/jsonNetIssue

Exception: Token String in state Object would result in an invalid JSON object. Path ''.

I found reproducing the issue is dependent on defining a TraceWriter AND the custom json converter.  In my project I use this Id class to represent a string, guid, or long id value - and I added a json converter to help json.net serialize it.  
Without the TraceWriter it serializes fine - with TraceWriter and without the custom converter it serializes but obviously doesn't properly handle the Id field.

**Comment by JamesNK** [comment]
Thanks for the repo. I have fixed this issue - https://github.com/JamesNK/Newtonsoft.Json/commit/64f6fd7b39f9371122144eba0bed5eb19e061ec0
