### ISSUE TITLE
Bug: ContractResolver.ResolvePropertyName overrides JsonPropertyAttribute property name

### ISSUE THREAD

**Issue by Nick-Lucas** [JamesNK/Newtonsoft.Json#1463]
### Context

I am developing an app, against the Jira API, where the vast majority of property names are fully lower case, with a few exceptions. I have therefore implemented a `LowercaseContractResolver` which overrides `ResolvePropertyName` to convert all names to lower as a standard serialisation approach.

When applying a `JsonPropertyAttribute` on a property which breaches the standard approach, the attribute is ignored, and the property is converted to all lowercase. Jira is notoriously fussy over correct case so this breaks the API request.

### Research

It appears that under [normal circumstances](https://github.com/JamesNK/Newtonsoft.Json/blob/6057d9b83126315e441711b5672776f36bdc3afa/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1476), JSON.NET will use the following precedence for serialising properties:
1. JsonProperty
2. NamingStrategy
3. Property name

This is not honoured with a custom `ContractResolver`, and I believe it should be. As it stands, it feels unintuitive, since fine grain control is disabled when using the approach which the API encourages us to use for applying a base strategy over serialisation.

The following line is to blame, since it does not check `hasSpecifiedName` before applying the contract resolver:
https://github.com/JamesNK/Newtonsoft.Json/blob/6057d9b83126315e441711b5672776f36bdc3afa/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1480

### Workaround

Since the above code is switching on a NamingStrategy being provided, it is possible to work around the issue by creating a custom NamingStrategy and applying it in a custom ContractResolver's constructor. Like below:

```C#
    class LowercaseContractResolver : DefaultContractResolver {
        public LowercaseContractResolver() {
            this.NamingStrategy = new LowercaseNamingStrategy();
        }

        protected override string ResolvePropertyName(string propertyName)
            => throw new Exception("this will now never be called");

        class LowercaseNamingStrategy : NamingStrategy {
            protected override string ResolvePropertyName(string name)
                => name.ToLower();
        }
    }
```

**Comment by JamesNK** [comment]
It was done this way for backwards compatibility reasons. Use a `NamingStrategy` instead of overriding `ResolvePropertyName` for that additional control.

**Comment by Nick-Lucas** [comment]
I'm afraid I'm failing to see why this behaviour is backwards compatible, and not a long-standing bug? I can't seem to find an [Issue](https://github.com/JamesNK/Newtonsoft.Json/issues/) where this was decided, so I may be missing some context, but the reasoning I would apply is below:

## Scenario:
* Let's say: JSON.NET has always overridden JsonPropertyAttribute names when the equivalent of a contract resolver is applied to naming. This is the implied scenario by suggesting this behaviour exists for backward compatibility.
* So: users have always lost fine-grain control of their naming when they apply a base rule to serialisation
* So: users may have applied attributes thinking the base rule is being overridden and had to
  * A: work around the issue, using a counter-intuitive API, like I have
  * B: not realised their overrides are not working, because applications are not case-sensitive, and it's purely cosmetic
* So: certainly no user would have applied an attribute and provided a name, knowing the base rule would take control; the attribute doesn't enforce providing a name so there's no advantage to doing so.
* In which case: this is a long-time design flaw which should be corrected; and would not be a breaking change or cause behaviour not originally intended by users.

This behaviour actually introduces a counter-intuitive bug which could never provide an advantage to users. There is a good rule of thumb in APIs that broad behaviour should be overridden by fine-grain behaviour, and not the other way around; imagine if implementing an abstract class didn't let you override methods on the base class, wouldn't that make inheritance sort of useless?

**Comment by JamesNK** [comment]
> certainly no user would have applied an attribute and provided a name, knowing the base rule would take control

Sure they could. They might be serializing with no contract resolver is some places and then using camel case via WebAPI. Json.NET is used everywhere with every permutation of scenarios that you could imagine.

> this is a long-time design flaw which should be corrected

With NamingStrategy.

You don't understand how important backwards compatibility is.

**Comment by Nick-Lucas** [comment]
> They might be serializing with no contract resolver is some places and then using camel case via WebAPI. Json.NET is used everywhere with every permutation of scenarios that you could imagine.

Using multiple serialisation approaches on the same classes within the same application sounds like the edge case to me. The common case is going to be the expectation of a logical inheritance->override of settings, and separation of classes between domains. Though I now have a clearer picture of why you would call this a breaking change.

This is the scenario in the application I discovered this issue in. We're sending some objects to Jira and some are returned via WebApi. But they're different classes because they're different domains, and having crossover between domain objects is surely very rare (and inviting a mess)

> You don't understand how important backwards compatibility is.

I would make the argument that this is what major versions are for. If we don't work to ensure the JSON.NET api stays clean well into the future, and redesign portions of the API which are become un-intuitive over time; it's eventually going to become the kind of legacy software that we all dread using, but is so pervasive we can't avoid it (and this project **is** pervasive). Backwards compatibility at all costs only hurts users in the long run.
