### ISSUE TITLE
The horrible "Install failed. Rolling back" on Visual Studio 2015

### ISSUE THREAD

**Issue by JohnAtFenestra** [JamesNK/Newtonsoft.Json#1464]
I have placed all version information below. Attempting a simple install of Newtonsoft.json 10.0.3 from NuGet into a Visual Studio solution. The target framework is 4.5.2.

I have searched Bing and Google and turned up nothing of use. Any suggestions of what to try next?

Package manager output
-----------
Attempting to gather dependency information for package 'Newtonsoft.Json.10.0.3' with respect to project 'AspUnitTests', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Newtonsoft.Json.10.0.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Newtonsoft.Json.10.0.3'
Resolved actions to install package 'Newtonsoft.Json.10.0.3'
Attempting to gather dependency information for package 'Newtonsoft.Json.10.0.3' with respect to project 'AspUnitTestLibrary', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Newtonsoft.Json.10.0.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Newtonsoft.Json.10.0.3'
Resolved actions to install package 'Newtonsoft.Json.10.0.3'
Adding package 'Newtonsoft.Json.10.0.3' to folder 'E:\code\ASPTesting\AspTesting\packages'
Added package 'Newtonsoft.Json.10.0.3' to folder 'E:\code\ASPTesting\AspTesting\packages'
Install failed. Rolling back...
Package 'Newtonsoft.Json.10.0.3' does not exist in project 'AspUnitTests'
Removing package 'Newtonsoft.Json.10.0.3' from folder 'E:\code\ASPTesting\AspTesting\packages'
Removed package 'Newtonsoft.Json.10.0.3' from folder 'E:\code\ASPTesting\AspTesting\packages'
Failed to add reference to 'Newtonsoft.Json'.
========== Finished ==========

Versions
-----------
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA733
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-20000-00000-AA733
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA733
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA733
Microsoft Visual C++ 2015

Visual F# 2015   00322-20000-00000-AA733
Microsoft Visual F# 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1701.8
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1701.8

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by JamesNK** [comment]
This looks like a NuGet issue. I have logged an issue with them here - https://github.com/NuGet/Home/issues/6031

**Comment by MichielBlotwijk** [comment]
Not sure if I was just lucky or whether this is a solution. I ran into the same problem when using VS2015 in admin mode. I closed VS and opened it again in normal mode and nuGet installed Newtonsoft.Json.10.0.3 without complaining.
