### ISSUE TITLE
NullValueHandling.Ignore is not working with expando object.

### ISSUE THREAD

**Issue by kumarsathishD** [JamesNK/Newtonsoft.Json#1466]
Program -

//

dynamic patientInfo = new ExpandoObject();
            patientInfo.FirstName = "Sathish";
            patientInfo.LastName = "Kumar";
            patientInfo.Location = null;

            patientInfo.Courses = new List<String>() { "Maths", "Science", "English" };

            JsonSerializer serialize = new JsonSerializer();
            serialize.Formatting = Formatting.Indented;
            serialize.NullValueHandling = NullValueHandling.Ignore;
            using (StreamWriter write = new StreamWriter(@"D:\Test.json"))
            {
                using (JsonWriter jwrite = new JsonTextWriter(write))
                {
                    serialize.Serialize(jwrite, patientInfo);
                }
            }

//

Actual Output -

{
  "FirstName": "Sathish",
  "LastName": "Kumar",
  "Location": null,
  "Courses": [
    "Maths",
    "Science",
    "English"
  ]
}

Expected Output -

{
  "FirstName": "Sathish",
  "LastName": "Kumar",
  "Courses": [
    "Maths",
    "Science",
    "English"
  ]
}

**Comment by JamesNK** [comment]
That is expected behavior. `NullValueHandling` only applies to actual object properties. `ExpandoObject` is basically a dictionary.
