### ISSUE TITLE
Setting missing values dynamicly

### ISSUE THREAD

**Issue by nimanzd** [JamesNK/Newtonsoft.Json#1468]
### destination type

```csharp
public class TestCommand : ICommand
{
    public TestCommand(int anotherId, int testId)
    {
        TestId = testId;
        AnotherId = anotherId;
    }
    public int TestId { get; }
    public int AnotherId { get; }
}
```

### Source JSON

```javascript
{ "AnotherId" : 20} 
```

### Expected behavior
TestId should dynamically sets from a datasource like dictionary

**Comment by JamesNK** [comment]
What? Why? How?

**Comment by twhitson** [comment]
This sounds like something outside the scope of this JSON.NET imo

However, you could achieve this easily yourself if you have a dictionary to match it against.
```cs
var dict = new Dictionary<int, int> {
    { 20, 48 }
};

value.TestId = dict.FirstOrDefault(x => x.Key == value.AnotherId)?.Value;
```

**Comment by nimanzd** [comment]
@JamesNK I'm working on a REST framework and Input model of endpoints have to deserialize from both posted data and route data. Route data stored in a dictionary and and posted data stored in StreamReader. 

@twhitson AnotherId should pass to constructor along with TestId

Anyway, I used ContractResolver to set DefaultValue of properties that return by CreateProperties method! 
I'm not sure it's the best way but it works  so far! :)

PS: It seems DefaultContractResolver violating Single Responsibility Principal ;)

Thanks  for replay :)

**Comment by JamesNK** [comment]
I'm happy that this isn't something that will be built into Json.NET but there are extension points available for people to do it if they wish.
