### ISSUE TITLE
Create StreamConverter class

### ISSUE THREAD

**Issue by xaviergxf** [JamesNK/Newtonsoft.Json#1470]
I'm trying to serialize a class that contains a property Stream with Newtonsoft.Json but i get the following exception error because Newtonsoft.Json cannot serialize/deserialize a stream:

Error getting value from 'ReadTimeout' on 'System.IO.FileStream'.

Is it possible to create a StreamConverter class that does what BinaryConverter class does? Perhaps using a temporary file like: 

var fileStream = new FileStream(filename, FileMode.Create, FileAccess.ReadWrite, FileShare.ReadWrite, 4096, FileOptions.DeleteOnClose);

What do you think about this idea?

Thanks!

**Comment by JamesNK** [comment]
Sure, it is something that could be done, but I'd rather it was added in a separate package. I'm trying to keep Newtonsoft.Json small and extra things like that don't need to be in the same package.
