### ISSUE TITLE
Constructor on type System.ComponentModel.ReferenceConverter not found.

### ISSUE THREAD

**Issue by bunkerbilly** [JamesNK/Newtonsoft.Json#1472]
Xamarin
IOS 9.3

Hi,

When i run JsonConvert.DeserializeObject<[Customer Class]> i get the Exception

"Constructor on type 'System.ComponentModel.ReferenceConverter' not found."

Any ideas on what i can do to solve this?

**Comment by ormedo** [comment]
Some problem here.

**Comment by navirius** [comment]
any update here?

**Comment by faizworks** [comment]
In my case it was occurring at JsonConvert.Serialize(obj) and it was because I had the following property definition in my class

```
[JsonProperty("AssistantAssociateId")]
public int? AssistantAssociateid { get; set; }
```

It seems that the issue arises when you set propertyName in JsonProperty similar to the property name. I fixed it by removing JsonProperty

```
//[JsonProperty("AssistantAssociateId")]
public int? AssistantAssociateId { get; set; }
```

**Comment by JamesNK** [comment]
Newtonsoft.Json supports .NET Standard so it is likely that Xamarin on iOS is missing the ctor from their implementation. I've copied this issue to their project.

**Comment by dalexsoto** [comment]
@bunkerbilly / @faizworks I've tried to reproduce this issue without luck, if you guys could provide some help would really appreciate it :) see xamarin/xamarin-macios#3144

**Comment by dalexsoto** [comment]
Mystery solved :) https://github.com/xamarin/xamarin-macios/issues/3144#issuecomment-361303109
