### ISSUE TITLE
Json.net Typenamehandling give preference to JsonSerializerSettings than JsonProperty setting

### ISSUE THREAD

**Issue by ankgupta067** [JamesNK/Newtonsoft.Json#1473]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
public class DomainResource {
        [JsonProperty( ItemTypeNameHandling = TypeNameHandling.Auto)]
        public List<Extension> Extensions { get; set; } 
    }
```

### Expected behavior

i want to ignore ItemTypeNameHandling in certain scenarios during serialization,but i am not able to find a way to do that. 
I tried using JsonSerializerSettings with TypeNameHandling.None as input for jsonconvert in scenario i do not want typename handling like below -
```
public static string SerializeObject(object value) {
            JsonSerializerSettings jsonSettings = new JsonSerializerSettings {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore,
                TypeNameHandling = TypeNameHandling.None,

            };
            jsonSettings.Converters.Add(new StringEnumConverter {
                CamelCaseText = true
            });
            return JsonConvert.SerializeObject(value, Formatting.None, jsonSettings);
        }
```

I Expect json to look -
`{"extensions":[{"valueInteger":3,"url":"ewwer"}]}
`
### Actual behavior

but it looks like -
`{"extensions":[{"$type":"DicomtoJsonConverter.IntegerExtension, DicomtoJsonConverter","valueInteger":3,"url":"ewwer"}]}
`

**Comment by JamesNK** [comment]
Attributes taking precedence is by design.
