### ISSUE TITLE
Property for the WriteIndentSpace-Char

### ISSUE THREAD

**Issue by MysticEmpires** [JamesNK/Newtonsoft.Json#1474]
### Expected behavior

It would be cool if the JsonWriter/JsonTextWriter would get an property for the Char used in "[WriteIndentSpace](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonTextWriter.cs#L376)".

I know it sound maybe dump. But i have to work with an very old service that dont use a json-parser. It use an own writen regex for reading the json (i know its stupid but its not my service^^) and also its expect an "\t" after an property. 👎 

Actual i have to do something like this:

`.Replace("\": ", "\":\t")`

But i guess it should be easy to add this property without any harm. And also its the only char in the JsonWriter/JsonTextWriter that is not configurable.

Also json.net can read an json with an '\t' instant of an ' ' so i guess its also valid json :)

### Actual behavior

Actual its not possible to config the "IndentSpace" after a property name.

**Comment by dbc2** [comment]
[`WriteIndentSpace()`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonTextWriter_WriteIndentSpace.htm) and [`WriteIndentSpaceAsync()`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonTextWriter_WriteIndentSpaceAsync.htm) are both declared as `protected override void`, so couldn't you just subclass `JsonTextWriter`, subclass the two methods, and write the desired character?

**Comment by JamesNK** [comment]
I recommend either subclassing `JsonTextWriter` or copying its source and making changes to it. What you want to do is too niche for its own setting.
