### ISSUE TITLE
Workaround for using Binder property on JsonSerializerSettings 

### ISSUE THREAD

**Issue by rnagpal** [JamesNK/Newtonsoft.Json#1475]
I've the following code where the serializationBinder is of type System.Runtime.Serialization.SerializationBinder

```
var jsonSerializerSettings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };
jsonSerializerSettings.Binder = serializationBinder;
```
and it's erroring with v10.0.2 saying that Binder is obsolete.

Is there a way to workaround this based on the code above?

If I use SerializationBinder property on JsonSerializerSettings, it expects the value to be of ISerializationBinder type.

**Comment by JamesNK** [comment]
Help questions go on stackoverflow.
