### ISSUE TITLE
Incorrect handling of invalid Json properties

### ISSUE THREAD

**Issue by wledfor2** [JamesNK/Newtonsoft.Json#1477]
### Source/destination JSON

```javascript
{null:1}
```

### Expected behavior
An error, as null is not a valid property. Alternatively, the property is not converted to a string and simply becomes an object with the value null.

### Actual behavior
The property is converted to the string "null".

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<object>("{null:1}");
```

If this is intentional, I think adding a setting to control this behavior would be desirable. This also occurs for any invalid property. For instance, {1:1} is converted to {"1":1}

**Comment by JamesNK** [comment]
`JsonTextReader` accepts unquoted property names. If you want to error in that situation then I recommend creating a new implementation of `JsonReader` that is strict with the JSON it accepts.
