### ISSUE TITLE
Breaking Bug: Randomly appends additional } when serializing and writing to textfile

### ISSUE THREAD

**Issue by tomek-i** [JamesNK/Newtonsoft.Json#1478]
Hi,

I have a basic class with some properties which I use as Configuration files for my Windows Forms App. 
I have written a configuration manager which deals with serialization and deserialization
of the configuration files. 
In the constructor of this manager, i will load the configuration, then write it back to the harddrive
to update the JSON again. I do this so if my class introduced new properties to have them within the JSON file and default values.

Randomly the app crashes because of invalid format of the JSON object due to an extra closing } at the end of the file.

I haven't managed to  reproduce this problem in a controlled scenario, it is sometimes randomly 10 out of 10 times it may work and then sometimes it fails twice in the row (after fixing the json  and restarting the app).

```csharp
//The constructor 
internal ConfigurationManager()
        {
            IConfiguration temp = new MasterConfig();
            Refresh(ref temp);
            MasterConfig = temp;
        }
public T Read<T>(bool rewriteIfExists=true) where T : class, IConfiguration
        {
            T defaultInstance = Activator.CreateInstance<T>();
            return Read(defaultInstance, rewriteIfExists) as T;
        }
        
        public bool Write<T>(T instance) where T : IConfiguration
        {
            string filepath = instance.CreateDirectoryIfNotExist();

            var serialized = Serializer.Serialize(instance);

            using (TextWriter writer = new StreamWriter(File.OpenWrite(filepath)))
                writer.Write(serialized);

            return true;
        }

        private void Refresh(ref IConfiguration cfg)
        {
            cfg = (IConfiguration)Read(cfg);
        }
private object Read(IConfiguration instance, bool rewriteIfExists = false)
        {
            var filepath = instance.GetFilePath();
            if (File.Exists(filepath))
            {
                var content = File.ReadAllText(filepath);
                var loadedCfg = (IConfiguration)Serializer.Deserialize(content, instance.GetType());
                var b = loadedCfg as ConfigurationBase;
                b.PropertyChanged += (sender, property) => {
                    ConfigChanged(b);
                };
                //forces to write new properties which havent been written to cfg yet
                if (rewriteIfExists)
                    Write(loadedCfg);

                return loadedCfg;
            }
            else
            {
                
            }

            if (!Write(instance))
                throw new Exception("Could not write configuration.");

            return instance;
        }
        
```

The serializer class which is just a wrapper:

```csharp
public class JsonSerializer : Serializer
    {
        #region Overrides of Serializer

        public override string Serialize(object obj)
        {
            return Serialize(obj, Format.Indented);
        }
        public  string Serialize(object obj, Format format)
        {
            Formatting form = Formatting.None;
            if(format == Format.Indented)
                form = Formatting.Indented;

            return JsonConvert.SerializeObject(obj, form);
        }
        public override T Deserialize<T>(string json)
        {
            if (typeof (T).IsInterface || typeof (T).IsAbstract)
            {
                throw new ArgumentException("You cannot use an interace nor an abstract class as a type",nameof(T));
                //var obj = Deserialize(json);
               // return obj as T;
            }

            return JsonConvert.DeserializeObject<T>(json);
        }

        public override object Deserialize(string json, Type type=null)
        {
            return type==null ? JsonConvert.DeserializeObject(json) : JsonConvert.DeserializeObject(json, type);
        }

        #endregion
    }
```

I assume the problem is the refresh function on the Manager call but I am not doing anything async or parallel so i am wondering why the serialization of the class randomly ends up with an additional } at the end for example and other times it just works:

```json
{
"name":"test"
}}
```
or sometimes also:

```json
{
"name":"test"
}
}
```

i tried re-running the final application several times in visual studio but there i haven't had any luck reproducing this. This mystery happens randomly on 3 devices.

The actual json string, this one does not change between APP restarts however it gets overwritten on each app start to update potential configuration when new settings have been introduced.
```json

{
  "DatabaseConnectionString": "Data Source=SOURCE;Initial Catalog=NAME;Persist Security Info=True;User ID=USER;Password=NAME",
  "Emails": [
    "test@email.com"
  ],
  "ExceptionEmails": [
    "test@email.com"
  ],
  "LocalPath": "C:\\",
  "ServerPath": "C:\\",
  "SourcePath": "C:\\",
  "TrendPath": "C:\\",
  "Name": "GeneralAppConfiguration",
  "Created": "2017-11-01T08:41:29.9736683+11:00"
}
```

**Comment by JamesNK** [comment]
You're using File.OpenWrite - https://msdn.microsoft.com/en-us/library/system.io.file.openwrite(v=vs.110).aspx

Bet you $10 you're writing to a file that already exists which is why you have multiple `}`'s

**Comment by tomek-i** [comment]
Yes, in the cases when it happens it does already exist, however, the content did not change and if, it would get longer which means the original content should be overwritten. In the current case the setting class contains the exact same properties & values which should mean it is the exact same JSON string.
So randomly on app start the format gets corrupted, then I manually fix it and then it might be OK for another X amount of app-starts until the format breaks again.

I can write a workaround and clear the content first, reposition and rewrite it or separate the code if the file exists or if it has to be created first.

**Comment by JamesNK** [comment]
Just write to the file in such a way that it is recreated. Writing to the start of a file that already exists is a fundamentally bad idea.
