### ISSUE TITLE
Unable to search using Newtonsoft.Json

### ISSUE THREAD

**Issue by satyababu** [JamesNK/Newtonsoft.Json#1486]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{"message":"{"values":{"value":[{"name":"Dictionary.CustomerName","value":"LOS ANGELES COUNTY ISD"},{"name":"Search_Dictionary.SearchCustomer","value":"LOS ISD"}]}}"}

JsonPath Query = $.values.value[?(@ && @.name && CustomerName.test(@.name))].value

```

### Expected behavior

Result should be: 
[
  "LOS ISD"
]

http://jsonpath.com/
Used same json string with json path query in the above website. It is extracting exact value. But when we use Newtonsoft.Json api, it is not working in c#
JsonPath Query = $.values.value[?(@ && @.name && CustomerName.test(@.name))].value

### Actual behavior

"Unexpected character while parsing path query: /"
at Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide()\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression()\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery(Char indexerCloseChar)\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer(Char indexerOpenChar, Boolean scan)\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List`1 filters, Int32 currentPartStartIndex, Boolean query)\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()\r\n   at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)\r\n   at Newtonsoft.Json.Linq.JToken.SelectTokens(String path)
### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here

string test = "{ \"values\": { \"value\": [ { \"name\": \"Dictionary.CustomerName\", \"value\": \"LOS ISD\" }, { \"name\": \"Search_Dictionary.SearchCustomer\", \"value\": \"LOS ANGELES ISD\" } ] } }";

JObject jsonTest = JObject.Parse(test);
IEnumerable<JToken> shuJson = jsonTest.SelectTokens("$.values.value[?(@ && @.name && /CustomerName/.test(@.name))].value");

```

**Comment by JamesNK** [comment]
`$.values.value[?(@ && @.name && /CustomerName/.test(@.name))].value`

That isn't a valid JSON Path according to anything on http://goessner.net/articles/JsonPath/index.html

**Comment by satyababu** [comment]
Hi James,

Thanks for your response.
Is there any equivalent path to this ($.values.value[?(@ && @.name && /CustomerName/.test(@.name))].value )  extract that value? 

Please let me know. 
Thank you

**Comment by JamesNK** [comment]
I think you will have to use LINQ instead of a string query
