### ISSUE TITLE
System.Data.DataTable instance Serialized with different results between .net framework 4 and .NetCore 2.0 while using Newtonsoft.Json

### ISSUE THREAD

**Issue by JasonGLYao** [JamesNK/Newtonsoft.Json#1489]
Do not know whether it is correct to post this issue here.....

### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior
DotNet4.0
 [
{
"ID": "2CD297F1338F473EB3A532ACC976DD3C",
"PARAM_CODE": "NO_FINISHED_BY_MO",
"PARAM_DESC": "NO_FINISHED_BY_MO",
"PARAM_GROUP_ID": "017dfbc924c811e787ddfa163e3e120a",
"PARAM_ALIAS": "NO_FINISHED_BY_MO",
"PARAM_VALUE": "Y",
"PARENT_PARAM_ID": null,
"STATE": "A",
"USER_CREATED": "MGE",
"DATETIME_CREATED": "2017-11-07T09:33:52",
"DATETIME_MODIFIED": null,
"USER_MODIFIED": null,
"ORG_ID": "dc7b73bb81f644d4b9ef58445130505d",
"SEQ": 2,
"IS_SYS": "N",
"Parent_Param_Code": null,
"PARAM_GROUP_DESC": null
}
]

### Actual behavior
DotNet Core 2.0
{"DataTable.RemotingVersion":{"Major":2,"Minor":0,"Build":-1,"Revision":-1,"MajorRevision":-1,"MinorRevision":-1},"XmlSchema":"<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<xs:schema xmlns=\"\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">\r\n  <xs:element name=\"RECORDSET\">\r\n    <xs:complexType>\r\n      <xs:sequence>\r\n        <xs:element name=\"ID\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_CODE\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_DESC\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_GROUP_ID\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_ALIAS\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_VALUE\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARENT_PARAM_ID\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"STATE\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"USER_CREATED\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"DATETIME_CREATED\" type=\"xs:dateTime\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"DATETIME_MODIFIED\" type=\"xs:dateTime\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"USER_MODIFIED\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"ORG_ID\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"SEQ\" type=\"xs:int\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"IS_SYS\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"Parent_Param_Code\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n        <xs:element name=\"PARAM_GROUP_DESC\" type=\"xs:string\" msdata:targetNamespace=\"\" minOccurs=\"0\" />\r\n      </xs:sequence>\r\n    </xs:complexType>\r\n  </xs:element>\r\n  <xs:element name=\"tmpDataSet\" msdata:IsDataSet=\"true\" msdata:MainDataTable=\"RECORDSET\" msdata:UseCurrentLocale=\"true\">\r\n    <xs:complexType>\r\n      <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\" />\r\n    </xs:complexType>\r\n  </xs:element>\r\n</xs:schema>","XmlDiffGram":"<diffgr:diffgram xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\" xmlns:diffgr=\"urn:schemas-microsoft-com:xml-diffgram-v1\">\r\n  <tmpDataSet>\r\n    <RECORDSET diffgr:id=\"RECORDSET1\" msdata:rowOrder=\"0\">\r\n      <ID>2CD297F1338F473EB3A532ACC976DD3C</ID>\r\n      <PARAM_CODE>NO_FINISHED_BY_MO</PARAM_CODE>\r\n      <PARAM_DESC>NO_FINISHED_BY_MO</PARAM_DESC>\r\n      <PARAM_GROUP_ID>017dfbc924c811e787ddfa163e3e120a</PARAM_GROUP_ID>\r\n      <PARAM_ALIAS>NO_FINISHED_BY_MO</PARAM_ALIAS>\r\n      <PARAM_VALUE>Y</PARAM_VALUE>\r\n      <STATE>A</STATE>\r\n      <USER_CREATED>MGE</USER_CREATED>\r\n      <DATETIME_CREATED>2017-11

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by JasonGLYao** [comment]
May be not the library issue,if it is ,I will open it later.

**Comment by JamesNK** [comment]
The current .net standard version of json.net doesn't support it. The next version will

**Comment by EvanCarroll** [comment]
Probably worth referencing the issue: https://github.com/JamesNK/Newtonsoft.Json/issues/1409
