### ISSUE TITLE
JsonConvert.SerializeObject returns indented json when called with Formatting.None

### ISSUE THREAD

**Issue by lajjne** [JamesNK/Newtonsoft.Json#149]
When `JsonConvert.SerializeObject(object value, Formatting formatting, JsonSerializerSettings settings)` is called with `Formatting.None` and settings that have `Formatting.Indented` I would expect the formatting to override the value in settings, but that is not the case. See the following failing test.

```
var obj = new { Formatting = "test"};

var settings = new JsonSerializerSettings { Formatting = Formatting.Indented };
string indented = JsonConvert.SerializeObject(obj, settings);

string none = JsonConvert.SerializeObject(obj, Formatting.None, settings);
Assert.AreNotEqual(indented, none);
```

**Comment by ulibarri** [comment]
it worked great!!
