### ISSUE TITLE
I am not able to Parse string with [ ] in value

### ISSUE THREAD

**Issue by ArunGust** [JamesNK/Newtonsoft.Json#1495]
I am not able to Parse below json string

string test = "[{\"key\":[\"xxx@gmail.com;\",\"Approve test\"],\"value\":1},{\"key\":[\"xxx@gmail.com;\",\"Approve test\"],\"value\":4},{\"key\":[\"xxx@gmail.com;\",\"Approve test\"],\"value\":1},{\"key\":[\"xxx@gmail.com;\",\"Approve test\"],\"value\":2}]";

JObject someresult = JObject.Parse(test);

**Comment by wizofaus** [comment]
Use
JArray someresult = JArray.Parse(test);
JObject is only

**Comment by ArunGust** [comment]
worked, thank you
