### ISSUE TITLE
Deserialization adding to a static read only field each time

### ISSUE THREAD

**Issue by Swellenator** [JamesNK/Newtonsoft.Json#1496]
### Source/destination types

```csharp
public class Page
{
	public List<int> AvailablePageSizes 
	{
		get { return Constants.PageSizes; }
	}	
}

public static class Constants
{
	public static readonly List<int> PageSizes = new List<int> { 10, 20, 50, 75, 100 };
}
```

### Source/destination JSON

```javascript
{'AvailablePageSizes':[ 10, 20, 50, 75, 100 ]}
```

### Expected behavior

(Assuming the default behavior of `ObjectCreationHandling.Auto`)
The result would be an array of 10 objects {10, 20, 50, 75, 100, 10, 20, 50, 75, 100}

### Actual behavior

The result increases by 5 each time you deserialise, increasing indefinitely. 

**The readonly property is being updated by a getter.**

### Steps to reproduce

```csharp
void Main()
{ 
	var requestString = "{'AvailablePageSizes':[ 10, 20, 50, 75, 100 ]}";

	Debug.WriteLine($"Page sizes: {Constants.PageSizes.Count()}");
	var result = JsonConvert.DeserializeObject<Page>(requestString);
	
	Debug.WriteLine($"Page sizes: {Constants.PageSizes.Count()}");
	result = JsonConvert.DeserializeObject<Page>(requestString);
	
	Debug.WriteLine($"Page sizes: {Constants.PageSizes.Count()}");
}
```

**Comment by wizofaus** [comment]
readonly only makes the object reference readonly, not the list itself.
If you use a ReadOnlyCollection (or anything implementing IReadOnlyList) this shouldn't be an issue.

**Comment by JamesNK** [comment]
Set ObjectCreationHandling to Replace.

**Comment by Swellenator** [comment]
Thanks for your help, i guess that's my ignorance of C# and what `readonly` means. 

I'm also guessing that just because I defined only a `get` on my property doesn't mean you can't change the values inside the object returned.

I think that in the future if I have a `Constants` class with collections I will use `ReadOnlyCollection` to make the value actually constant.

I am also of the opinion that the default behavior should be `ObjectCreationHandling.Replace`, now that I look closer I can see many issues raised by it. But then again, I guess you can't change the default on a widely used library like this without making people unhappy!

Cheers

**Comment by JamesNK** [comment]
I agree, but it is too late to change.
