### ISSUE TITLE
Any plans to support netcoreapp2.0?

### ISSUE THREAD

**Issue by mrpmorris** [JamesNK/Newtonsoft.Json#1498]
Also, any idea when NuGet will be updated? I want _[JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]_ but it doesn't seem to be in the 10.0.3 release.

**Comment by ralsu091** [comment]
Json.Net targets netstandard 2.0 and other netstandards https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L3. There is no need to target netcoreapp2.0. See here for more information about netstandard https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by nbsoftware** [comment]
.netstandard 2.0 is indeed in the source code but, if I'm correct, still
not yet released

**Comment by ralsu091** [comment]
@nbsoftware right, the latest on Nuget doesn't target netstandard2.0 but targets netstandard1.3. My understanding is that an app targeting netcoreapp2.0 should be able to reference lower netstandard packages.

I guess you will have to wait for a new release if you really want the netstandard2.0 targeting.

**Comment by JamesNK** [comment]
There will never be an assembly targeting netcoreapp2.0. The next release will have a netstandard2.0 target.
