### ISSUE TITLE
How to Capitalize initial letters to lowercase?

### ISSUE THREAD

**Issue by mokeyish** [JamesNK/Newtonsoft.Json#1501]
![image](https://user-images.githubusercontent.com/16131917/32889939-bb3b5598-cb07-11e7-9d15-c1f533456ef2.png)

**Comment by wizofaus** [comment]
I believe ContractResolver = new CamelCasePropertyNamesContractResolver { NamingStrategy = null } will do it. Also can I strongly recommend pasting your source code as text so others can copy and paste it.

**Comment by wizofaus** [comment]
Sorry, what are you asking? Your example code (which, by the way, please do as text rather than an image in future) seems to already do exactly what you're looking for.

**Comment by mokeyish** [comment]
@wizofaus I want to change the json key 'Name' to 'name',But I can't find the way to do this.

**Comment by wizofaus** [comment]
Ah, I hadn't tried your whole code sample, yes that is odd, it seems to be something to do with the way it read the object in the first place (it works fine if you just use new { Name: "Lily", Age: 15 }).

**Comment by JamesNK** [comment]
Your issue is you're deserializing to a `JObject` which doesn't use the camel case resolver when it is serialized. Deserialize to an `IDictionary<string, object>` instead.

**Comment by mokeyish** [comment]
![default](https://user-images.githubusercontent.com/16131917/32987283-038ea766-cd22-11e7-8140-17e0d20d180f.png)
![default](https://user-images.githubusercontent.com/16131917/32987285-14622d9c-cd22-11e7-99c6-f3c04344d210.png)

@JamesNK @wizofaus Here is my final solution to solve it.

**Comment by wizofaus** [comment]
Unfortunately as far as I can tell once you've used JsonSerializer.Deserialize( ) (non-generic version) and hence created a JObject, the only way to then override the property names is to declare your own Json(Text)Writer class that overrides WritePropertyName( ), and there's no way of configuring JsonConvert.Serialize( ) to use a custom JsonWriter class.  You could deserialize using:

            dynamic o= JsonConvert.DeserializeObject<ExpandoObject>(a, new ExpandoObjectConverter());

instead, and the contract resolver setting is honoured as expected.

**Comment by wizofaus** [comment]
BTW @JamesNK do you know why JsonConvert.DeserializeObject<dynamic>( ) still deserializes into a object using JTokens as properties and hence doesn't use the contract resolver?

**Comment by mokeyish** [comment]
@wizofaus My aim is to transfer json string‘s key from PascalCase to CamelCase.It may be Jobject or JArray.So 
`JsonConvert.DeserializeObject<ExpandoObject>(@"[{""Name"":""Lily"",""Age"":19}]")`  could not works as expected.

**Comment by wizofaus** [comment]
If you already have a JObject that was deserialized with PascalCase names then as far as I can tell you'll need a customer JsonWriter that overrides WritePropertyName.   You should be able to use new CamelCaseNamingStrategy().GetPropertyName(name, false) to convert to camelCase.

**Comment by mokeyish** [comment]
@wizofaus Thankyou ,I'll_ try late.

**Comment by julienroubieu** [comment]
I stumbled across this same issue when trying to convert to camelCase messages coming from Hangfire (which uses Json.Net to serialize parameters).
This was solved by an ugly extra serialization and deserialization, using @wizofaus 's suggestion:

```
dynamic objHonoringResolver = JsonConvert.DeserializeObject<ExpandoObject>(JsonConvert.SerializeObject(obj));
```

... but I would happily accept a better way of doing this.
