### ISSUE TITLE
Not serializing to RFC339 date format correctly

### ISSUE THREAD

**Issue by alexl0gan** [JamesNK/Newtonsoft.Json#1502]
### Source/destination types

```csharp
DateTime
```

### Source/destination JSON

```csharp
new { date = DateTime.Now };
```

### Expected behavior

String value of date to be "2017-11-17T12:34:10.123456Z"

### Actual behavior

String looks like "YYYY-11-DDT12:24:54.uuuuuuZ"

### Steps to reproduce

```csharp
var settings = new JsonSerializerSettings
{
    DateFormatString = "YYYY-MM-DDThh:mm:ss.uuuuuuZ"
};
var date = DateTime.Now;
var destination = JsonConvert.SerializeObject(date, settings);
```

**Comment by TylerBrinkley** [comment]
You'll want to look [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) for the `DateFormatString`.

**Comment by alexl0gan** [comment]
That string works with `myDate.ToString("YYYY-MM-DDThh:mm:ss.uuuuuuZ")` so is there a reason why it doesn't work here?

**Comment by TylerBrinkley** [comment]
It doesn't work for me. I believe you want the following `DateFormatString`, `"yyyy-MM-ddThh:mm:ss.ffffffZ"`.

**Comment by alexl0gan** [comment]
Yes you are correct, `yyyy-MM-ddThh:mm:ss.ffffffZ` is the solution. Thank you
