### ISSUE TITLE
Newtonsoft.Json.JsonException: 'Unexpected character while parsing path indexer: /'

### ISSUE THREAD

**Issue by sjblom** [JamesNK/Newtonsoft.Json#1508]
Hi there,

Hope someone can assist.

When doing a SelectTokens("$..['referenceListObjects'][?(@.name!=null && @.name.match(/USD|GBP|EUR/))]") I get the following exception: Newtonsoft.Json.JsonException: 'Unexpected character while parsing path indexer: /'

![image](https://user-images.githubusercontent.com/3727732/33005194-753e336c-cdcd-11e7-8e50-97b8d72738e2.png)

Maybe someone can assist, or, provide me with alternatives on how to get around this problem.

According to http://jsonpath.com/, using the same JSONPath expression "$..['referenceListObjects'][?(@.name!=null && @.name.match(/USD|GBP|EUR/))]" as above, I do get the expected results.

![image](https://user-images.githubusercontent.com/3727732/33005214-84242bde-cdcd-11e7-9aa0-af96c8646acf.png)

Thank you very much

**Comment by JamesNK** [comment]
Json.NET doesn't support match or regexes in paths.
