### ISSUE TITLE
StringEnumConverter case sensitivity

### ISSUE THREAD

**Issue by Jericho** [JamesNK/Newtonsoft.Json#1516]
Up until Json.net v9, the StringEnumConverter class was case insensitive and it was changed in v10. Here's the [discussion](https://github.com/JamesNK/Newtonsoft.Json/issues/1067) explaining why it was changed and here's the [commit](https://github.com/JamesNK/Newtonsoft.Json/commit/b2afa9d674f4dc0d5137ce6f175e06e565fc66f5) released in v10 that changed the behavior to case-sensitive.

I can't argue with the reasoning behind this change but I find myself in a situation where case-insensitivity is desired and it seems like I can't change the comparison behavior. I'm stuck, as far as I can tell.

I was wondering if we could make case-sensitivity configurable? We could ensure the default behavior is to be case-sensitive to match the current behavior and also allow developers to indicate they want a different behavior. 

Does that sound reasonable? I'm willing to submit PR with this improvement.

**Comment by Jericho** [comment]
To be clear, what I'm trying to achieve is to ensure the following three scenarios are successful:

```csharp
enum MyEnum 
{ 
    [EnumMember(Value = "first")] 
    First, 
    [EnumMember(Value = "second")] 
    Second
} 

[Test] 
public void () 
{ 
    MyEnum e1 = JsonConvert.DeserializeObject<MyEnum>(@"""first""", new StringEnumConverter()); 
    Assert.AreEqual(MyEnum.First, e1); 

    MyEnum e2 = JsonConvert.DeserializeObject<MyEnum>(@"""First""", new StringEnumConverter()); 
    Assert.AreEqual(MyEnum.First, e2); 

    MyEnum e3 = JsonConvert.DeserializeObject<MyEnum>(@"""FIRST""", new StringEnumConverter()); 
    Assert.AreEqual(MyEnum.First, e3); 
} 
```

**Comment by Jericho** [comment]
This discussion is very similar to issue #1426 and sounds like PR #1480 would solve the scenarios I'm presenting.

**Comment by Jericho** [comment]
What would be ideal, IMHO, would be to be able to specify is the conversion is case sensitive or not. Something like this:

```
[JsonConverter(typeof(StringEnumConverter), caseSensitive: false)]
```

**Comment by Jericho** [comment]
During my investigation, I discovered an interesting fact: If you use the `EnumMember` value ("first_value" in my example), the conversion is case sensitive and you must match *exactly*, which means that the following unit tests fail:

```csharp
[Test]
public void DeserializeEnumCaseIncensitive_ByEnumMemberValue_UpperCase()
{
    var e = JsonConvert.DeserializeObject<EnumMemberDoesNotMatchName>(@"""FIRST_VALUE""", new StringEnumConverter());
    Assert.AreEqual(EnumMemberDoesNotMatchName.First, e);
}

[Test]
public void DeserializeEnumCaseIncensitive_ByEnumMemberValue_MixedCase()
{
    var e = JsonConvert.DeserializeObject<EnumMemberDoesNotMatchName>(@"""First_Value""", new StringEnumConverter());
    Assert.AreEqual(EnumMemberDoesNotMatchName.First, e);
}
```

However, if you the enum item name ("First" in my example), the conversion is case insensitive which means that the following unit tests are successful:

```csharp
[Test]
public void DeserializeEnumCaseIncensitive_ByName_LowerCase()
{
    var e = JsonConvert.DeserializeObject<EnumMemberDoesNotMatchName>(@"""first""", new StringEnumConverter());
    Assert.AreEqual(EnumMemberDoesNotMatchName.First, e);
}

[Test]
public void DeserializeEnumCaseIncensitive_ByName_UperCase()
{
    var e = JsonConvert.DeserializeObject<EnumMemberDoesNotMatchName>(@"""FIRST""", new StringEnumConverter());
    Assert.AreEqual(EnumMemberDoesNotMatchName.First, e);
}
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/51c9547dbcc6877c2e63d61d2e15a43038b96b71
