### ISSUE TITLE
Bug:SelectToken when using JsonPath filter 

### ISSUE THREAD

**Issue by winnyrain** [JamesNK/Newtonsoft.Json#1518]
there is a bug when the path digital value with "" 
example:
string statusJson = "{\"usingmem\": \"214376\"}";//214,376

var aa = jObj.SelectToken("$..[?(@.usingmem>10)]");//found,10
var bb = jObj.SelectToken("$..[?(@.usingmem>27000)]");//null, 27,000
var cc = jObj.SelectToken("$..[?(@.usingmem>21437)]");//found, 21,437
var dd = jObj.SelectToken("$..[?(@.usingmem>21438)]");//null,21,438

why ? Is the last char of the json right value  being cut ?

**Comment by JamesNK** [comment]
Works for me https://github.com/JamesNK/Newtonsoft.Json/commit/977884d779f69adf3dc075ca1d860617b95803f2
