### ISSUE TITLE
Unity: ArgumentNullException: Argument cannot be null

### ISSUE THREAD

**Issue by 155martinmoreno** [JamesNK/Newtonsoft.Json#1521]
I'm having a issue parsing a json message using Unity.

When running the build on the editor (Mac) everything works perfect, but on the Android device, it blows up when trying to parse the QuestionDto list.

I'm I doing something wrong or is this a legit bug?

Thanks in advance!

### Source/destination types

```csharp
public class GameDetails {
		public string id;
		public SagaMechanic mechanic;
		public IList<QuestionDto> questions;
		public Dictionary<string, object> definitions;

		public GameDetails(string Id, IList<QuestionDto> questions, SagaMechanic mechanic,
			Dictionary<string, object> definitions)
		{
			id = Id;
			this.questions = questions;
			this.mechanic = mechanic;
			this.definitions = definitions;
		}
	}

public class QuestionDto {
		
		public string id ;
		public string gameId ;
		public string category ;
		public string questionAsked ;
		public List<AnswerDto> answers ;
		public int correctAnswer ;

		public QuestionDto(string id, string gameId, string category, string questionAsked, List<AnswerDto> answers,
			int correctAnswer)
		{
			this.id = id;
			this.gameId = gameId;
			this.category = category;
			this.questionAsked = questionAsked;
			this.answers = answers;
			this.correctAnswer = correctAnswer;
		}
	}

	public class AnswerDto {
		public string text { get; private set; }
		public bool enabled { get; private set; }

		public AnswerDto(string text, bool enabled = true)
		{
			this.text = text;
			this.enabled = enabled;
		}
	}
```

### Source/destination JSON

```javascript
{
  "id": "some_game",
  "mechanic": 0,
  "questions": [
    {
      "Id": "12",
      "Category": 5,
      "QuestionAsked": "Some Question?",
      "Answers": [
        {
          "Text": "first",
          "Enabled": true
        },
        {
          "Text": "second",
          "Enabled": true
        },
        {
          "Text": "third",
          "Enabled": true
        },
        {
          "Text": "fourth",
          "Enabled": true
        }
      ],
      "CorrectAnswer": 1
    }
  ]
}
```

### Actual behavior

Error path: 
questions[0].answers

Error message:
ArgumentNullException: Argument cannot be null.
Parameter name: method
  at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull (System.Object value, System.String parameterName) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateParameterizedConstructor (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper (System.Object list) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Boolean& createdFromNonDefaultCreator) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingVal

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<GameDetails>(body.ToString())
```

**Comment by Thaina** [comment]
Maybe it because `QuestionDto` and `GameDetails` has no public empty constructor?

Could you try make public constructor with no parameter to let it have default constructor?

**Comment by 155martinmoreno** [comment]
I've done many tests, when adding a empty constructor, the _PopulateObject_ call does not affect the object (all values are null/0/etc).

**Comment by 155martinmoreno** [comment]
I did find a solution making all _Lists_ parameters concrete (vs _IList_) in constructors.

Are _IList_ supported?

**Comment by Thaina** [comment]
I see. surely not. We can't deserialize interface because interface cannot `new`

**Comment by 155martinmoreno** [comment]
weird, because It does work with IEnumerable... anyways if you think is not an issue, we can close it.

**Comment by Thaina** [comment]
I don't know I'm not contributor just try to help solve problem

**Comment by WAMMI** [comment]
Sorry for commenting on such an old issue, but just wanted to leave a comment and let you know that we faced the same issue with some swagger-generated code. It used ICollection as generic arrays. Our app did not work on Android (Oculus Quest 2) but did so in the Unity Editor. 

For us, changing ICollection to List fixed the issue.

**Comment by eKoopmans** [comment]
Also sorry to resurrect, but this symptom had a different solution for me. For context, I didn't have any IList/ICollection/etc, and empty constructors weren't required.

I was getting this error in **Unity** when compiling to Oculus (Android), specifically when deserializing `HashSet<int>`. Turns out it was caused by the [ahead-of-time (AOT) compilation in IL2CPP](https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-compilation-errors) - as described in [one of the solutions](https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-using-link.xml):

> the constructor has been long gone removed by IL2CPP's bytecode stripping

I used the [AotHelper solution](https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-using-AotHelper) which solved things for me, specifically `AotHelper.EnsureList<int>()` (EnsureList applies to HashSets).

**Comment by VanIseghemThomas** [comment]
@eKoopmans, how did you manage to figure out which type was causing the problem? I'm having the same problem with quite a large datamodel and unable to pinpoint the exact type causing it. I'm using dictionaries at some points, do they need some special treatment for this? Also this is error was caused by updating from Unity 2021.3.14f1 -> 2022.3.8f1. I do however convert to a ExpandoObject at a certain point, maybe that can contribute to something?

**Comment by eKoopmans** [comment]
Haha I don't remember, sorry - I think I just tried process of elimination, removing fields until it worked then adding things back until it broke again. I was on a 2020 version of Unity so it sounds like you might be having a different problem than I did.

**Comment by VanIseghemThomas** [comment]
No problem! Was able to resolve it by not using ExpandoObjects.
