### ISSUE TITLE
GetImmutableConstructor should iterate through all constructors

### ISSUE THREAD

**Issue by dee-see** [JamesNK/Newtonsoft.Json#1523]
Is it deliberate that [`DefaultContractResolver.GetImmutableConstructor` ](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L578) works only if there is one constructor instead of only if there is one constructor _that matches_? I'm not sure if this is a bug or feature...

I would expect the following test to pass but it doesn't:

```
[Test]
public void GetImmutableConstructorTest()
{
	var before = new A( 1, 2 );
	var after = (A)JsonConvert.DeserializeObject( JsonConvert.SerializeObject( before ), typeof( A ) );

	Assert.AreEqual( 1, after.B );
	Assert.AreEqual( 2, after.C );
}

public struct A
{
	public int B { get; }
	public int C { get; }

	public A( int b, int c )
	{
		B = b;
		C = c;
	}

	public A( int x )
	{
		B = x;
		C = x;
	}
}
```

The implicit parameterless constructor (working with a struct here) ends up being called.

I changed the implementation of [`DefaultContractResolver.GetImmutableConstructor` ](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L578) locally and it did not break any unit tests for what it's worth.

If you consider this a bug I'll gladly submit a PR changing the behavior.

Thanks

**Comment by JamesNK** [comment]
Yes it is a feature but if I did it again I would ignore the default constructor on structs and use the single defined constructor. Unfortunately changing that now could potentially break a lot of existing code. Use the `[JsonConstructor]` attribute on your ctor.
