### ISSUE TITLE
MergeNullValueHandling.Ignore does not ignore null strings

### ISSUE THREAD

**Issue by yufeih** [JamesNK/Newtonsoft.Json#1525]
### JContainer.Merge

```csharp
var a = new JObject { ["a"] = 1 };
var b = new JObject { ["a"] = false ? "2" : null };
a.Merge(b);
```

### Expected behavior

{"a": 1}

### Actual behavior

{"a": null}

**Comment by JamesNK** [comment]
Thanks for the simple example. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/d0d01f2a365898b86bfb424608888ac2fce51857
