### ISSUE TITLE
Newtonsoft.Json 11.0.1-beta1 is broken for netstandard1.6 with NU1605

### ISSUE THREAD

**Issue by yyjdelete** [JamesNK/Newtonsoft.Json#1526]
### Expected behavior

Build successful.

### Actual behavior

Build failed with `NU1605`
```
error NU1605: Detected package downgrade: NETStandard.Library from 2.0.0 to 1.6.1. Reference the package directly from the project to select a different version.
error NU1605:  x1 -> Newtonsoft.Json 11.0.1-beta1 -> NETStandard.Library (>= 2.0.0)
error NU1605:  x1 -> NETStandard.Library (>= 1.6.1)
```

### Steps to reproduce

1. `dotnet new classlib` (already with dotnet sdk >=2.0.0)
2. modify `TargetFramework` to `netstandard1.6`, and add an reference to `Newtonsoft.Json` `11.0.1-beta1`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1-beta1" />
  </ItemGroup>

</Project>
```
3. `dotnet build` and failure.

---
May relate to this. Is there any reason for not just let dotnet-sdk choose the best version?
https://github.com/JamesNK/Newtonsoft.Json/blob/ab3315f1d5e57c70203c904be79d8e951bf09794/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L27

**Comment by jnm2** [comment]
See https://github.com/dotnet/standard/issues/606 and https://github.com/dotnet/standard/issues/601.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/fde0fef06fdb5853a34ee1b108a2a66eaf243e29
