### ISSUE TITLE
Issues referencing Json.NET in JavaScript based UWP project via Windows Runtime Component

### ISSUE THREAD

**Issue by michael-hawker** [JamesNK/Newtonsoft.Json#1527]
### Expected behavior
Build to include proper reference for Json.NET to work.

### Actual behavior
FileNotFound exception.

### Steps to reproduce
Create a blank Universal JavaScript project.  Then add a C# based Windows Runtime Component with a Json.NET reference.  Expose a class to the JavaScript and try and call a Json.net api in the component, calling that method from JavaScript will fail, see this project with the basic setup:

[JSJSONTest.zip](https://github.com/JamesNK/Newtonsoft.Json/files/1529243/JSJSONTest.zip)

```
0x80070002 - JavaScript runtime error: The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
```

However, If I copy the Json.NET dll into the AppX output folder it will work.  Is this an issue with the Json.Net package or the UWP build process?  I get the same issue if I try and put the Json.Net reference in a .NET Standard library and then reference that library instead in the Windows Runtime Component.

**Comment by DexterWoo** [comment]
I have encountered the same problem.

**Comment by JamesNK** [comment]
You'll need to report the issue to the UWP teaam. This isn't a bug in Newtonsoft.Json
