### ISSUE TITLE
Add more specialized version of DiscriminatedUnionConverter for F# Option< 'T>

### ISSUE THREAD

**Issue by wegry** [JamesNK/Newtonsoft.Json#1528]
Since there is already a [DiscriminatedUnionConverter](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/DiscriminatedUnionConverter.cs), it might be a good idea to include a more specialized optional converter for F#'s Option type? Option usage is pretty pervasive in F#.

[This code seems to work](https://github.com/haf/Newtonsoft.Json.FSharp/blob/master/src/JsonNet/Converters/OptionConverter.fs) but the project looks dead.

### Source/destination types

```fsharp
type Foo = {
    bar: Option<int>
}

let x = [ { bar = Some 1 };
              { bar = None } ]
```

### Source/destination JSON

```json
[
  { "bar": 1 },
  { "bar": null }
]
```

### Expected behavior

Ideally, an F# `None` would get converted to null on writing out to JSON.

### Actual behavior

Type information is explicitly included (because of the default DiscriminatedUnionConverter) which doesn't play nicely with a C# service consuming the F# generated JSON.

**Comment by bartelink** [comment]
FYI https://github.com/jet/FsCodec/blob/master/src/FsCodec.NewtonsoftJson/OptionConverter.fs works and is interoperable with the OOTB behavior in System.Text.Json (FsCodec also has interoperable UnionConverter impls for STJ and Newtonsoft that have a better story for versioning, i.e. handling adding/removing fields etc)

**Comment by wegry** [comment]
🙏 @bartelink. I've used that in the past after creating this. I was cleaning house with old issues.
