### ISSUE TITLE
Accept year 0000 as 1BC

### ISSUE THREAD

**Issue by schani** [JamesNK/Newtonsoft.Json#1529]
According to ISO 8601 the year `0000` should decode to 1BC, but it's rejected as invalid.

**Comment by JonHanna** [comment]
`DateTime.MinValue` and `DateTimeOffset.MinValue` both represent midnight on the First of January 1CE in the Proleptic Gregorian calendar. What are you hoping to represent 1BCE in?

**Comment by schani** [comment]
Oh well.

**Comment by JonHanna** [comment]
Incidentally, strictly speaking ISO 8601 doesn't allow any value below 1583 unless using a derived standard or other agreement to do so. Between RFC 3339 allowing it, and W3C DTF just being taken as allowing it by most users, we're probably safe though 😄

**Comment by JamesNK** [comment]
Nodatime might support a greater date range
