### ISSUE TITLE
Setting DateTimeZoneHandling works differently for JsonConvert.DeserializeObject and JObject.ToObject 

### ISSUE THREAD

**Issue by crab312** [JamesNK/Newtonsoft.Json#1531]
I have a json with DateTime field. In case when date value provided without timezone I want to use the setting DateTimeZoneHandling.Local.
But this setting works differently for JsonConvert.DeserializeObject and JObject.ToObject

JsonConvert.DeserializeObject - creates local DateTime from string "2017-12-05T21:59:00" 
JObject.ToObject - creates unspecified DateTime from the same string "2017-12-05T21:59:00"

This behaviour seems as bug

            var test1 = jobj.ToObject<Test1>(JsonSerializer.Create(new JsonSerializerSettings {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            }));

            var test3 = JsonConvert.DeserializeObject<Test1>(jobj.ToString(), new JsonSerializerSettings()
            {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            });

Enviroment: local timezone +00:03
  
      static void Main(string[] args)
        {
            var json = "{\"dt1\":\"2017-12-05T21:59:00\"}";
            var jobj = JObject.Parse(json);

            var test1 = jobj.ToObject<Test1>(JsonSerializer.Create(new JsonSerializerSettings {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            }));

            var test2 = JsonConvert.DeserializeObject<Test1>(json, new JsonSerializerSettings()
            {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            });

            var test3 = JsonConvert.DeserializeObject<Test1>(jobj.ToString(), new JsonSerializerSettings()
            {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            });

            var d1 = test1.dt1.ToLocalTime(); //kind - unspecified
            var d2 = test2.dt1.ToLocalTime(); //kind - local
            var d3 = test3.dt1.ToLocalTime(); //kind - local

            Debugger.Break();
        }

### Expected behavior

Property test1.dt1 should have local kind 

### Actual behavior

Property test1.dt1 has unspecified kind

### Steps to reproduce

Run the code above and compare test1.dt1 with other tests

**Comment by HApolonio** [comment]
I'm having this issue in my project too - Dates parsed by JObject.ToObject do not respect the DateTimeZoneHandling parameter that is set on the serializer.

Could you please review and approve @medinarkhov pull request #1632.

**Comment by JamesNK** [comment]
Fixed - https://github.com/JamesNK/Newtonsoft.Json/pull/1865
