### ISSUE TITLE
Exception while deserializing in Silverlight 5 with Json

### ISSUE THREAD

**Issue by darkkilltec** [JamesNK/Newtonsoft.Json#1536]
[JsonTest.zip](https://github.com/JamesNK/Newtonsoft.Json/files/1550938/JsonTest.zip)
This Construct works fine with mono but when trying the same in Silverlight 5 it throws an exception. The reason seems to be a protetected int Property which is in a generic class.

We have for test purposes an empty message for deserialization, the exception happens while json is trying to process the class.

it throws a "Sequence contains more than one element" Exception.

### Source/destination types

```csharp
using System.Windows;
using Newtonsoft.Json;

namespace JsonTest
{
   public class GenericBase<TUid>
   {
      protected virtual TUid Prop { get; }
   }

   public class TestBase : GenericBase<int>
   {
      protected override int Prop => 0;
   }

   public class Test : TestBase
   {
   }

   public partial class App
   {
      public App()
      {
         Startup += Application_Startup;
         InitializeComponent();
      }

      private void Application_Startup(object sender, StartupEventArgs e)
      {
         RootVisual = new MainPage();

         JsonConvert.DeserializeObject<Test>("");
      }
   }
}
```

### Source/destination JSON
Source is empty ""

### Expected behavior

It should deserialize without throwing an exception

### Actual behavior

It did throw a "Sequence contains more than one element" Exception.

### Steps to reproduce

```csharp
Just run the Code within the JsonTest application provided, it will throw the Exception.
```

**Comment by JamesNK** [comment]
Sorry but I just don't have the resources to support SL. I suggest changing your type so that it doesn't throw an error.
