### ISSUE TITLE
Xamarin Android - JsonSerializationException: Error getting value from '[FIELD]' on '[METHOD]'

### ISSUE THREAD

**Issue by lorisgiglio** [JamesNK/Newtonsoft.Json#1537]
### Environment

Visual Studio 2015
Xamarin 4.8.0.754
Xamarin Android 8.1.0.13
Xamarin Android SDK 8.1.1.1
Newtonsoft.Json 10.0.3

### Source/destination types

        public class c1
        {
            public string field1 { get; set; }
        }

### Expected behavior

It has to serialize the simple object

### Actual behavior

12-13 10:49:28.412  9122  9122 I MonoDroid: UNHANDLED EXCEPTION:
12-13 10:49:28.419  9122  9122 I MonoDroid: Newtonsoft.Json.JsonSerializationException: Error getting value from 'field1' on 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'. ---> System.MissingMethodException: **Method 'System.Reflection.Emit.DynamicMethod.set_ProfileAPICheck' not found.**
12-13 10:49:28.419  9122  9122 I MonoDroid:   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile (System.Linq.Expressions.LambdaExpression lambda, System.Runtime.CompilerServices.DebugInfoGenerator debugInfoGenerator) [0x0000f] in <bfedf5c3cdd04d14a8bd94e62f153ad8>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at System.Linq.Expressions.LambdaExpression.Compile () [0x00000] in <bfedf5c3cdd04d14a8bd94e62f153ad8>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet[T] (System.Reflection.PropertyInfo propertyInfo) [0x0007c] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateGet[T] (System.Reflection.MemberInfo memberInfo) [0x0000a] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue (System.Object target) [0x0000e] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:    --- End of inner exception stack trace ---
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue (System.Object target) [0x00054] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContainerContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract& memberContract, System.Object& memberValue) [0x00066] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b0] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <c19705166c7c4a608e182e859c4de6d2>:0
12-13 10:49:28.419  9122  9122 I MonoDroid:   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <c19705166c7c4a608e182e859c4de6d2>:0

### Steps to reproduce

        public static string GetData(string s1)
        {
           if (string.IsNullOrWhiteSpace(s1)) return null;

            c1 c = new c1();

            c1.field1 = s1;

            string res = JsonConvert.SerializeObject(c1);
            
            return res;
       }

**Comment by JamesNK** [comment]
The error is happening inside Xamarin code. I've copied the issue to their github issues.
