### ISSUE TITLE
Differences in the debug mode and the final result (for Culture)

### ISSUE THREAD

**Issue by sasiano** [JamesNK/Newtonsoft.Json#1551]
I use PersianCulture class for convert AD date to Persian Date in **Web Api**.

```C#
    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {
            var persianCulture = new PersianCulture();
            Thread.CurrentThread.CurrentCulture = persianCulture;
            Thread.CurrentThread.CurrentUICulture = persianCulture;
        }
}
```

in my Controller:
_(for example in News Model, there is "DateTime CreateDate" peroperty)_
```C#
return Ok(news.CreateDate);
```

In debug mode, I see that this change has been applied.
I see date is Persian: 
_`8/18/1396 08:12:00 ب.ظ`_

**BUT** when the answer is received from Fiedler, the date is AD!
_`2017-11-09T20:12:00.177`_

NOTIC:
if I convert it to string before sending, there will be no problem and date is persian.

```C#
string date = news.CreateDate.ToString();
return Ok(date);
```

so we result problem is in converting datetime to string in Newtonsoft.Json

what's the solution?

**Comment by JamesNK** [comment]
This code has nothing to do with Json.NET:

`string date = news.CreateDate.ToString();`
