### ISSUE TITLE
Exception when serializing ref fields/properties

### ISSUE THREAD

**Issue by Sergio0694** [JamesNK/Newtonsoft.Json#1552]
### Source/destination types

```csharp
private readonly int _SomeField;

[JsonProperty(nameof(InputInfo))]
public ref readonly int SomeField => ref _SomeField;
```

### Expected behavior

It'd be great to be able to serialized reference fields/properties, but right now the library throws an exception saying it can't get the target value for the target field/property in question.

The workaround right now is to duplicate the value with another field/property, but that's not a good solution and it forces the developer to duplicate multiple fields/properties when there are multiple references that should serializes that point to a single field/property.

The library should automatically get the value of the target field/property as if it was a normal field/property, without problems caused by the `ref` modifier.

### Actual behavior

The serialization crashes saying it can't get the target value.

### Steps to reproduce

```csharp
[JsonObject(MemberSerialization.OptIn)]
public class TestClass
{
    private readonly int _SomeField;

    [JsonProperty(nameof(InputInfo))]
    public ref readonly int SomeField => ref _SomeField;
}

public static void Main()
{
    TestClass test = new TestClass();
    String test = JsonConvert.SerializeObject(test, Formatting.Indented);
}
```

### StackOverflow original question

See here:
https://stackoverflow.com/questions/47952489/how-to-serialize-a-c-sharp-ref-field-with-newtonsoft-json

**Comment by JamesNK** [comment]
I've improved the error message to make it clear that ref properties are not supported https://github.com/JamesNK/Newtonsoft.Json/commit/b49f6bc0ec8e6e04ccf506692b25ae687ac2540f

**Comment by Sergio0694** [comment]
@JamesNK Hello, thanks for your answer! Is there any chance we'll see this feature being implemented in the future? Any workarounds other than duplicating the local field we can use?
Thanks again, keep up the good work! 😊
