### ISSUE TITLE
Bool type in the use of serialization problems

### ISSUE THREAD

**Issue by JHeLiu** [JamesNK/Newtonsoft.Json#1553]
Bool type in the use of serialization problems,
Conversion code:
```
           JsonSerializerSettings jsetting = new JsonSerializerSettings();
            jsetting.DefaultValueHandling = DefaultValueHandling.Ignore;
            var b = JsonConvert.SerializeObject(user, jsetting)
```
I try to use it to filter the value type of null, a single object is the right choice, but when a class attribute is another class will not work, for example:

The normal conversion of the entity
```
 public class User
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime? DateTime { get; set; }

        public bool IsBool { get; set; }
    }
```

The wrong conversion entity, UserList this property is a class, and this class has a bool below
```
 public class User
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime? DateTime { get; set; }

        public bool IsBool { get; set; }

        public User UserList { get; set; }
    }
```

I'm not quite sure if this is a bug or an unknown process, please help me. Thank you

**Comment by JamesNK** [comment]
false is the default value for ignore and will be filtered out by `DefaultValueHandling.Ignore`

**Comment by JHeLiu** [comment]
If I want to keep, what should I do?
