### ISSUE TITLE
Unexpected behavior when adding the same JObject variable multiple times to a JArray

### ISSUE THREAD

**Issue by atoader** [JamesNK/Newtonsoft.Json#1560]
### Scenario
I am iterating through a collection and for each member of the collection I am building state in the same JObject variable, adding the JObject to a JArray, and calling RemoveAll on the JObject. When serializing the JArray to a string, I see that it does not contain the values added to the JObject in the first iteration of the loop.

### Steps to reproduce

```csharp
namespace ConsoleApp
{
    using Newtonsoft.Json.Linq;
    using System;

    internal class Program
    {
        private static void Main(string[] args)
        {
            var jobject = new JObject();
            var jarray = new JArray();

            foreach (var customer in new[] { new { No = 1, Name = "Test", Balance = 1.2m }, new { No = 2, Name = "Test2", Balance = 2.2m } })
            {
                jobject.Add("No", customer.No);
                jobject.Add("Name", customer.Name);
                jobject.Add("Balance", customer.Balance);
                jarray.Add(jobject);
                jobject.RemoveAll();
            }

            Console.WriteLine(jarray.ToString());
        }
    }
}
```

### Expected output
```json
[
  {
    "No": 1,
    "Name": "Test",
    "Balance": 1.2
  },
  {
    "No": 2,
    "Name": "Test2",
    "Balance": 2.2
  }
]
```

### Actual output
```json
[
  {},
  {
    "No": 2,
    "Name": "Test2",
    "Balance": 2.2
  }
]
```

### Investigation Results
As far as I can see, the first time the JObject is added to the JArray, the JArray is set as its parent. The JObject variable and the first slot of the JArray will reference the same value for the execution of the program.
On subsequent iterations, any mutations done on the JObject value will be seen in the first member of the JArray. Subsequent calls to *Add* on the JArray will add a copy of the JObject to the array. I would have expected that the JObject variable always references the last slot of the array.

Is this expected behavior? If yes, what was the reasoning behind it?

**Comment by JamesNK** [comment]
That's expected behavior. A copy of the `JObject` is made if it is added again because `Previous`, `Next`, `Parent`, etc, are unique on the instance and where it exists in the document.
