### ISSUE TITLE
Is json fingerprinting possible?

### ISSUE THREAD

**Issue by nopara73** [JamesNK/Newtonsoft.Json#1563]
Does Newtonsoft serialize json exactly the same way on every platform?

**Comment by JamesNK** [comment]
No. Types deserialize slightly differently depending on what the platform supports, e.g. some platforms support TypeConverters and ISerializable, while others don't.

**Comment by nopara73** [comment]
Thank you @JamesNK ! @NicolasDorier, was this the issue you were talking about back then?

**Comment by nopara73** [comment]
Thank you! Do you think the best way to avoid this is to create custom `JsonConverter` for every single type those serialization is privacy critical?
@NicolasDorier, did you solve this issue back then?

**Comment by knocte** [comment]
> e.g. some platforms support TypeConverters

What platforms don't support TypeConverters? I'm using them with .NET Standard across Linux|Mac|Windows|iOS|Android.

**Comment by JamesNK** [comment]
Most portable class library targets don't because of Silverlight and Windows Store.

**Comment by knocte** [comment]
Ah well,  as for me, I don't care about Silverlight, and AFAIK with .NET Standard you can now target the Windows Store? (Xamarin Forms has a UWP backend.)

**Comment by NicolasDorier** [comment]
@nopara73 to prevent fingerprinting I dropped HTTP and JSON for TCP and binary. (Replace IServer implementation of .NET Core by my own TCPServer)

**Comment by knocte** [comment]
@NicolasDorier why go one layer down instead of going one up? (e.g. gRPC or HTTP2)

**Comment by NicolasDorier** [comment]
@knocte one layer up would introduce more fingerprinting, not less. gRPC in C# is not easily cross plateform (rely on native binaries) and probably have sources of fingerprinting (would take me time to know if true or not). Binary/TCP is just easier.

**Comment by nopara73** [comment]
@knocte It took me a month to rewrite the essential parts of HTTP/1.1 protocol from scratch. It's probably one of the most abused/extended/hotfixed protocol in the World.

**Comment by knocte** [comment]
Interesting :)
