### ISSUE TITLE
Serializing Array values in one line

### ISSUE THREAD

**Issue by RafaeldelM** [JamesNK/Newtonsoft.Json#1565]
Hi,
I'm trying to serialize an array of floats in one line? Not all the document, just the arrays.

`  
   "values": [
          576.272461,
          -305.837036,
          56.18925,
          583.095459,
          -305.837036,`

Now the result is a line per value, and it is complicated to analyze in big files.

"values": [
          576.272461,
          -305.837036,
          56.18925,
          583.095459,
          -305.837036,

Thanks

**Comment by JamesNK** [comment]
No the formatting is either all or nothing. To customize it you could implement your own JsonReader.

**Comment by FreyaHolmer** [comment]
I solved this by temporarily setting the `JsonWriter.Formatter` to `None` instead of `Indented`. I've created a helper function to make this relatively clean to implement

Example use in a `JsonConverter`:

```cs
public class Converter_quaternion : JsonConverter<quaternion> {
	public override void WriteJson( JsonWriter writer, quaternion q, JsonSerializer serializer ) {
		using( new JsonArrayWriterInlineScope( writer ) ) { // <- this is the important bit
			writer.WriteValue( q.x );
			writer.WriteValue( q.y );
			writer.WriteValue( q.z );
			writer.WriteValue( q.w );
		}
	}
}
```

Code for `JsonArrayWriterInlineScope`:
```cs
public readonly struct JsonArrayWriterInlineScope : IDisposable {
	readonly Formatting prev;
	readonly JsonWriter writer;

	public InlineScope( JsonWriter writer ) {
		this.writer = writer;
		this.prev = writer.Formatting;
		writer.Formatting = Formatting.None;
		writer.WriteStartArray();
	}

	public void Dispose() {
		writer.WriteEndArray();
		writer.Formatting = prev;
	}
}
```
