### ISSUE TITLE
Non-Async Call in Async Method

### ISSUE THREAD

**Issue by Kevin-Andrew** [JamesNK/Newtonsoft.Json#1569]
Shouldn't the following

https://github.com/JamesNK/Newtonsoft.Json/blob/2c90c2740dfb0a2a1b826cb1ffd365d7f04a0bb6/Src/Newtonsoft.Json/JsonTextReader.Async.cs#L365

be 
```
await ParseNumberAsync(ReadType.Read, cancellationToken).ConfigureAwait(false);
```
instead?

(I have a program in which I implemented my own `Stream` object that only supports `ReadAsync`.  For my `Read` overload, I throw a `NotImplementedException`.  While parsing a lot of Json, I came across this because my exception was being thrown.

I hope there isn't a technical reason for using `ParseNumber` instead of `ParseNumberAsync`.  If so, perhaps a code comment would be appropriate here stating the reason for it.)

Thanks.

**Comment by JamesNK** [comment]
99% sure it isn't using the async call only because it was overlooked

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/c445141fc6de2fe39c178018414a7bc66c7bc843

**Comment by Kevin-Andrew** [comment]
Awesome, James.  Thanks.  You put together a Unit Test and everything.  Keep up the good work.

**Comment by JonHanna** [comment]
> 99% sure it isn't using the async call only because it was overlooked

As the author of that method, I'm 100% sure it was only because I overlooked it.
