### ISSUE TITLE
Feature request: Serialization attributes without adding Json.NET as a dependency

### ISSUE THREAD

**Issue by safakgur** [JamesNK/Newtonsoft.Json#1570]
Although some data contract attributes can be used as substitutes for Json.NET specific attributes, there are some, like `[JsonConstructor]`, that requires the Json.NET to be added as a dependency.

#### Why is this a problem?

Most core/dto/model/etc projects tend to expose types that are required to be serializable without doing any serialization themselves. This makes adding a serialization library as a dependency redundant since many of these types can get away with using the data contract attributes. Data contract attributes can be found in this lightweight, [System.Runtime.Serialization.Primitives][1] package and are already included in the full .NET framework.

So if I were to create a library with a class that has multiple constructors and want my users to be able to serialize it using Json.NET, I need to depend on Json.NET because I need the `[JsonConstructor]`. This is an unnecessary dependency for my users that don't use Json.NET and an even worse one for my users that do, because now they need to wait for me to update my library in order to update their Json.NETs.

#### What can be done?

Json.NET can compare attribute names instead of doing full type checks. For example, [this line][2] in the `DefaultContractResolver` can check if the constructor has an attribute named "JsonConstructor" without minding which assembly it comes from, so the users can create and use their own `[JsonConstructor]`s. I've seen this approach work with ReSharper annotations and some Redgate utilities.

Unfortunately, `[JsonConstructor]` is the only Json.NET specific attribute I know that doesn't accept a parameter. Letting the users define their own attributes would involve more reflection for attributes like `[JsonObject]`.

One other option I can think of is the .NET route. The attributes can be refactored into another package (e.g. Newtonsoft.Json.Primitives) that is also a dependency of the Json.NET itself. Consisting only of annotations, it can have a much slower release cycle while being considerably smaller in size.

#### What should be done?

I think reading the properties of a user-defined attribute via reflection (each time, or by using cached expression trees) may increase the project's complexity a little too much, and introducing a new dependency in the form of a primitives package may be considered overkill.

Allowing user-defined `[JsonConstructor]`s, on the other hand, seem easy enough and that is the one Json.NET specific attribute I find myself using the most (To compare, I needed to use the `[JsonObject]` only once in my life). For me, the only thing that the data contract attributes lack is a way to choose a constructor. It is somewhat understandable though, since the `DataContractSerializer` does not call any constructor.

[1]: https://www.nuget.org/packages/System.Runtime.Serialization.Primitives
[2]: https://github.com/JamesNK/Newtonsoft.Json/blob/3274b9ab67f8a7d18b26832fcaf84037c4f926d7/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L571

**Comment by dropsonic** [comment]
I faced the same problem, so I'd like to share my 5 cents here.
If your objects are immutable, they don't have a parameterless constructor, but often they have a constructor that accepts all or some of the property values.
In this case, it would be nice if we can instruct JSON.NET to use the most specific constructor available without adding any attribute. E.g. it can be done by adding a new value to the `ConstructorHandling` enumeration.

**Comment by safakgur** [comment]
This sounds like a useful addition, but extending the `ConstructorHandling` would require an opt-in from the user who will actually serialize the type. I'd much prefer to be able to write the type in a way so it can be serialized/deserialized properly with the default JSON.NET serializer.

Some thoughts about extending `ConstructorHandling`:

* It has an option to prefer the default constructor even if it's not public (`AllowNonPublicDefaultConstructor` ). A `PreferMostSpecificConstructor` would also come with a an accompanying option to mirror this functionality.
* If `AllowNonPublicDefaultConstructor` had a more generic name (like `AllowNonPublic` or `AllowNonPublicConstructor`), `ConstructorHandling` could be used as a flag enum to allow prefer-most-specific and allow-non-public to be specified together with only one additional member.

**Comment by dropsonic** [comment]
Seems that this already works in version 12.0.1:

```
public class TestEntity
{
	public TestEntity(int id, string value)
	{
		Id = id;
		Value = value;
	}

	public int Id { get; set; }
	public string Value { get; set; }
}

...
var entity = new TestEntity(5, "Test");
string json = JsonConvert.SerializeObject(expected);
var dsEntity = JsonConvert.DeserializeObject<TestEntity>(json); // works fine
```

**Comment by safakgur** [comment]
Isn't it supposed to? That class has only one constructor, not much to choose from.

**Comment by dropsonic** [comment]
@safakgur yes, my bad
It doesn't work if there are several constructors with parameters.

Right now the desired behavior can be achieved by using a custom ContractResolver:

```
public class MostSpecificConstructorContractResolver : DefaultContractResolver
{
	protected override JsonObjectContract CreateObjectContract(Type objectType)
	{
		var contract = base.CreateObjectContract(objectType);
		
		if (!objectType.IsAbstract && !objectType.IsInterface 
			&& contract.DefaultCreator == null && contract.OverrideCreator == null)
		{
			var constructor = objectType.GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
				.OrderBy(c => c.GetParameters().Length)
				.LastOrDefault();

			if (constructor != null)
			{
				contract.OverrideCreator = a => constructor.Invoke(a);
				foreach (var parameter in CreateConstructorParameters(constructor, contract.Properties))
				{
					contract.CreatorParameters.AddProperty(parameter);
				}
			}
		}

		return contract;
	}
}
```

Usage:
```
JsonConvert.DeserializeObject<TestEntity>(json,
			    new JsonSerializerSettings()
			    {
				    ContractResolver = new MostSpecificConstructorContractResolver()
			    });
```

**Comment by safakgur** [comment]
So turns out the best way to customize serialization/deserialization without adding Json.NET as a dependency is to implement [ISerializable][1] and add the deserialization constructor (see: [Remarks][2]).

[1]: https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iserializable
[2]: https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iserializable#remarks
