### ISSUE TITLE
Case-insensitive property match overwrites Case-sensitive property match

### ISSUE THREAD

**Issue by toddsharpe** [JamesNK/Newtonsoft.Json#1571]
Recently ran into this scenario:

### Source/destination types

```csharp
class Test
{
public OrderType o { get; set; }
}
enum OrderType
{
LIMIT,
MARKET
}
```

### Source/destination JSON

```javascript
{"o":"LIMIT", "O":-1}
```

### Expected behavior

Test objects' o property should be LIMIT.

### Actual behavior

Test object's o property was -1.

### Steps to reproduce

```csharp
Test t = JsonConvert.DeserializeObject<Test>(json);
```

My assumption is Newtonsoft.Json.Serialization.JsonPropertyCollection::GetClosestMatchProperty matches o exact, then the match for O misses on exact then goes to case-insensitive and matches.

### Fix

I fixed this by adding a dummy property to Test with name O to provide match.

**Comment by JamesNK** [comment]
They both match, so the last value is taken.

What you want isn't possible because it would require tracking state - every property that has been set would need to be stored somewhere, and then checked for - which would hurt performance and memory usage.

**Comment by toddsharpe** [comment]
Thanks for the quick response, that makes sense. Sounds like this issue is well reported, hope this helps somebody :)

**Comment by WeihanLi** [comment]
Can I do something to match the Uppercase property only?
