### ISSUE TITLE
How to handle ReadJson if field is missing in json?

### ISSUE THREAD

**Issue by joshidp** [JamesNK/Newtonsoft.Json#1572]
Hi,

Thanks for the effort.

Lets say our json can have a id property, but sometimes it can be missing in json.  How do we handle that null scenrio? 

Using below piece of code doesn't work.

` var id = jToken[Constants.IDToken].ToObject<string>();`

It will throw null pointer exception.  Do we have to create a extension method to handle it?

Thanks

**Comment by cmpute** [comment]
The resolution is quite intuitive here, you can just check whether `jToken[Constants.IDToken]` is null here. (i.e `var id = jToken[Constants.IDToken]?.ToObject<string>();`)
Furthermore, if you use `JsonSerializer`, the field will be ignored if it is missing in json text.
