### ISSUE TITLE
UWP [JsonIgnore] attribute not working on some IEnumerable's

### ISSUE THREAD

**Issue by Noemata** [JamesNK/Newtonsoft.Json#1574]
This is the only way to prevent ServerTypes from being serialized in the code snippet below:

        public enum ServerType { STUN, TURN };

        /// <summary>
        /// Make the enumerable available in XAML.
        /// </summary>
        // MP! Note: [JsonIgnore] does not work on this field when public,
        //           so we tried the [NonSerialized] attribute on backing field,
        //           this also fails to remove the property from serializaiton.
        //           The only working option is to mark the property
        //           as protected.
        protected IEnumerable<ServerType> ServerTypes
        {
            get
            {
                return Enum.GetValues(typeof(ServerType)).Cast<ServerType>();
            }
        }

This:

        [JsonIgnore]
        public IEnumerable<ServerType> ServerTypes
        {
            get
            {
                return Enum.GetValues(typeof(ServerType)).Cast<ServerType>();
            }
        }

does not prevent ServerTypes from being serialized.

**Comment by JamesNK** [comment]
It is ignored in this test - https://github.com/JamesNK/Newtonsoft.Json/commit/4f7fc7957121bf22dd059bb1e2b9c2bbfc1cc573
