### ISSUE TITLE
Value cannot be null exception message

### ISSUE THREAD

**Issue by KennethWKZ** [JamesNK/Newtonsoft.Json#1587]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Actual behavior

I got an error exception:
{"Message":"An error has occurred.","ExceptionMessage":"Value cannot be null.\r\nParameter name: value","ExceptionType":"System.ArgumentNullException","StackTrace":" at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)\r\n at Newtonsoft.Json.JsonWriter.WriteToken(JsonToken token, Object value)\r\n at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAd [TRUNCATED]
### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

Possible to find out this cause from which part of the method?

**Comment by JamesNK** [comment]
Dunno. I need a repo
