### ISSUE TITLE
Lite version for Xamarin

### ISSUE THREAD

**Issue by Cloze** [JamesNK/Newtonsoft.Json#1588]
First of all thank you for your amazing works on this great tools.

As you might know we can use json.net on xamarin platform. but our main problem is the size of the dll file. the final size of the xamarin packages is already big and we cannot put bigger dll in it. 

json.net dll is almost 600KB and its big. we may never use a lot of options and methods. just Serialize and Deserialze. and other methods is useless in here.

so, is it possible to have a liter version of the final dll?

**Comment by JamesNK** [comment]
At some point the deprecated Schema and Bson functionality classes will be removed which will make the DLL about 100KB smaller.

I don't plan to make a lite version that removes anything else in it.

**Comment by Genbox** [comment]
Related #707
