### ISSUE TITLE
Please add extension method DeepEqualsTo

### ISSUE THREAD

**Issue by Thaina** [JamesNK/Newtonsoft.Json#1590]
Just

```C#
public static bool DeepEqualsTo(JToken left,JToken right) => JToken.DeepEquals(left,right);

////

new JObject().DeepEqualsTo(new JObject());
```

**Comment by JamesNK** [comment]
I think the current DeepEquals method is perfectly fine. An extension method just increases the assembly size for no real benefit.

**Comment by Thaina** [comment]
@JamesNK The current `DeepEquals` as it being static method but not extensions. Means we must `using NewtonSoft.Json.Linq` in a file that we just need to use that method for compare JToken in another class

The real benefit is shorter code and having intellisense recommend this method instead of guessing that it would be a static method for comparison in some class

```C#
var left = new JObject();
var right = new JObject();
if(JToken.DeepEquals(left,right));
if(left.DeepEqualsTo(right));
// or if possible
if(left.DeepEqual(right));
```

In fact I think it just not **perfectly fine** to have `DeepEquals` being static method, it fine, but not perfect. This method should be extension, it just have been created since the time we don't have extension method. But now we have
