### ISSUE TITLE
System.Data.DataSet deserialisation throws exception.

### ISSUE THREAD

**Issue by dancrn** [JamesNK/Newtonsoft.Json#1591]
### Source/destination types

```csharp
System.Data.DataSet
```

### Source/destination JSON

```javascript
{"Table1":[{"id":0,"item":"item 0"},{"id":1,"item":"item 1"}]}
```

### Expected behavior

Running the example from [here](https://www.newtonsoft.com/json/help/html/DeserializeDataSet.htm) should behave as documented.

### Actual behavior

Exception thrown during deserialisation;

```
System.Runtime.Serialization.SerializationException: Member 'XmlSchema' was not found
```

### Steps to reproduce

```csharp
var json = "{\"Table1\":[{\"id\":0,\"item\":\"item 0\"},{\"id\":1,\"item\":\"item 1\"}]}";
DataSet dataSet = JsonConvert.DeserializeObject<DataSet>(json);
```

**Comment by JamesNK** [comment]
Are you using .NET Core? If so then use 11.0.1-beta3. It supports DataSets in .NET Core.

**Comment by dancrn** [comment]
Yes, using .NET core.

As this is just a version thing, I'll close this! Perhaps though, it might be good to add a "supported from" indicator on the examples page :)

Thanks,
