### ISSUE TITLE
JsonPath generated by JsonReader is incorrect

### ISSUE THREAD

**Issue by hajnicovaci** [JamesNK/Newtonsoft.Json#1592]
Hi,

My scenario is as follows:  I use the JsonReader to read from a file (which contains  text in JSON), while reading I keep the jsonPath of all property names; next I use the stored jsonPaths to select properties from the json input and update them. 
The problem is, that the jsonPath generated by the JsonReader is incorrect, so when I try to use the path to select a property and update it, I get null instead of a jsonToken.

### Input JSON 
{
  "test customer's": "testing"
}

input file: [test.txt](https://github.com/JamesNK/Newtonsoft.Json/files/1668067/test.txt)

### Helper method to reproduce 

```csharp
 private static List<string> _paths = new List<string>();

 static void Main(string[] args)
        {
            var fileStream = File.OpenRead("test.txt");
            using (var streamReader = new StreamReader(fileStream, Encoding.UTF8))
            {
                //read through the file and store jsonPath for each property
                var reader = new JsonTextReader(streamReader);
                StoreJsonPath(reader);

                //reset stream
                fileStream.Seek(0, SeekOrigin.Begin);

                //read through file and update each property with a new value
                JsonReader r = new JsonTextReader(streamReader);
                var jToken = JToken.Load(r);
                foreach (var path in _paths)
                {
                    var token = jToken.SelectToken(path);
                    //here the toke is null
                    //next I want to use the token to update it's value
                }
            }
        }
        private static void StoreJsonPath(JsonReader jsonReader)
        {
            while (jsonReader.Read())
            {
                if (jsonReader.Value == null) continue;

                switch (jsonReader.TokenType)
                {
                    case JsonToken.PropertyName:
                        break;
                    case JsonToken.String:
                        _paths.Add(jsonReader.Path);
                        break;
                }
            }
        }
```

### Expected behavior

The path I expected to get from the JsonReader is : ['test customer\\\\'s']
as  documented here (https://www.newtonsoft.com/json/help/html/QueryJsonSelectTokenEscaped.htm),  this is how the generated path should look like

### Actual behavior
But JsonReader.Path property returns ['test customer's']

### Steps to reproduce
Run the attached code and check the jsonPaths which are collected.

**Comment by JamesNK** [comment]
Thanks for the repo. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/6360cc4c4b4a45f7a82ad6c060cddd9cdb3c7d02
