### ISSUE TITLE
Add support to access current Contract Resolver inside a custom Converter

### ISSUE THREAD

**Issue by ravensorb** [JamesNK/Newtonsoft.Json#1594]
This is more of a feature request.  I am looking at creating a conditional JsonCoverter that uses the value of a property to determine which object type to read/write.  I am looking to access the current active contract resolver within the CanCovert method so that I can double check that any interfaces that i might need are registered for the current life cycle.

Example of what I am thinking
```
private List<Types> _knownTypes; // this is a list of known interface types that my convert should work work
public override ConConvert(Type objectType)
{
   var validType = _knownTypes.FirstOrDefault(x=> base.ContractResolver.ResolveContract(x)); // This would actually be cached in any real code :)

   return validType != null ? type.IsAssignableFrom(validType) : false;
}
````

Then inside the Read override I would actually extract the property and value I am going to key off of to do the dynamic determination of which object to create.

Note: this is a simple use case.  A more complex one would be where I would need to retrieve a list of all registered implementations for a specific contract and then based on a dynamic property create the correct implementation.  The issue here is the ContractResolver class would need a "ResolveAllContracts" concept that would return a list of types that are registered for the specified interface.

**Comment by JamesNK** [comment]
By default converters are stateless and reusable so a property isn't appropriate. You can already access the contract resolver in write and read. If you want to access it from CanConvert then you will have to add your own `ContractResolver` property and initialize it when you create your `JsonConverter` before serializing.
