### ISSUE TITLE
EnumMemberAttribute in dictionary conversion

### ISSUE THREAD

**Issue by cmpute** [JamesNK/Newtonsoft.Json#1597]
Hi, I planned to deserialize json object (which is just a field of the whole json) into a dictionary but I found that EnumMemberAttribute dosen't take effect here.

The field of json object looks like
```json
{
	"wish": 264,
	"collect": 7498,
	"doing": 385,
	"on_hold": 285,
	"dropped": 221
}
```
and I am going to deserialize the object into `IReadOnlyDictionary<CollectionStatus, uint>` instance using `JsonSerializer` where `CollectionStatus` is defined as below
```csharp
public enum CollectionStatus
{
	Wish,
	Collect,
	Doing,
	On_Hold, 
	Dropped
}
```
It works like a charm, however, it cannot be achieved if I edited the enum as following
```csharp
public enum CollectionStatus
{
	Wish,
	Collect,
	Doing,
	[EnumMember(Value = "on_hold")]
	OnHold, 
	Dropped
}
```

[I found here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L958) that the dictionary generation is not going to consider `EnumMemberAttribute` while [`StringEnumConverter` does consider](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs#L146).

Please add handling of `EnumMemberAttribute` here when `EnsureType` method is used.

**Comment by JamesNK** [comment]
Thanks for reporting this and the sample. Fixed here https://github.com/JamesNK/Newtonsoft.Json/commit/c90e6e871ae39cd4686dac6fa64a780e527123a8
