### ISSUE TITLE
Lightweight version

### ISSUE THREAD

**Issue by ygoe** [JamesNK/Newtonsoft.Json#1603]
There should be a lightweight version of Json.NET. Over 600 kB is too much to be used in a tool application of just 30 kB. I certainly don't need all of the features Json.NET provides. And I'd prefer to include the source code rather than pulling a separate DLL file along.

**Comment by JamesNK** [comment]
Checkout https://github.com/facebook-csharp-sdk/simple-json

**Comment by ygoe** [comment]
That's where I came from. It fails on pretty formatting and dictionaries.

Here's what I've just found and tested succesfully, much better: https://www.codeproject.com/Articles/159450/fastJSON

**Comment by rasterknight** [comment]
Thanks ygoe. Same here looking for lightweight json, newton is awesome but way to much functionnalities.
