### ISSUE TITLE
unexpected character encountered while parsing value: <. Path", line 0 position 0

### ISSUE THREAD

**Issue by yalamandarao** [JamesNK/Newtonsoft.Json#1610]
I'm using POST method and passing below parameters
Post Parameter : {"id":6,"status":2}

Every post request i'm getting below error.
"unexpected character encountered while parsing value: <. Path", line 0 position 0"

Do you have any idea? What is the issue

**Comment by JamesNK** [comment]
Ask on stackoverflow.
