### ISSUE TITLE
Cannot deserialize the current JSON  IAsyncEnumerable 

### ISSUE THREAD

**Issue by HeMinzhang** [JamesNK/Newtonsoft.Json#1611]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here

>  JsonConvert.DeserializeObject<GroupObject>(result);

> public class GroupObject
>     {
>         public string context { get; set; }
>         public IAsyncEnumerable<Group> value { get; set; }
>     }

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior

> An unhandled exception occurred while processing the request.
> JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.IAsyncEnumerable`1[Zop.Core.Domain.B2C.Group]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
> To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
> Path 'value', line 1, position 139.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
> 

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by JamesNK** [comment]
Json.NET doesn't know what to deserialize it as. Have a different type or write a JsonConverter
