### ISSUE TITLE
Just set JObject indexer cause "Property with the same name already exists on object"

### ISSUE THREAD

**Issue by Thaina** [JamesNK/Newtonsoft.Json#1614]
This error is not always happen but sometimes it pop up in the very normal code

```C#
var json = await JObjectFromSomeWhere();

json["dirty"] = true;
```

It can throw error "Property with the same name already exists on object". Like it try to insert dictionary, not just override

I suspect that the code I write is multithread and might be a problem of thread race but I'm not very sure. I'm sorry I forgot to copy the stack trace and it does not thrown out again after 2 times this day. But I remember that it have method name insert in the stack while I debug it and it have this `dirty` property already set

Are there anything else can cause this problem?

I use NewtonSoft.Json 10.0.3 on Windows 10 and run the code with nunit debugger

edit : Got the new one so now I could get stack trace

```
Exception has occurred: CLR/System.ArgumentException
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll: 'Can not add property dirty to JObject. Property with the same name already exists on object.'
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.set_Item(String propertyName, JToken value)
```

**Comment by JamesNK** [comment]
JObject isn't thread safe. Multiple threads changing a JObject could have this error.
