### ISSUE TITLE
Custom JsonConverter for FileInfo and DirectoryInfo no longer works

### ISSUE THREAD

**Issue by kimbirkelund** [JamesNK/Newtonsoft.Json#1619]
I have two JsonConverters handling FileInfo and DirectoryInfo objects respectively - serializing to FullName and vice versa.

They worked as expected in version 10.0.3, but after upgrading to version 11.0.1 the CanConvert method is no longer called for FileInfo and DirectoryInfo. But only for .NET Core projects.

I've attached a zip ([ReproduceDirectoryInfoJsonConverterIssue.zip](https://github.com/JamesNK/Newtonsoft.Json/files/1743712/ReproduceDirectoryInfoJsonConverterIssue.zip)) that reproduces the problem.

Note that the solution has two projects: one for .NET Core that prints an exception when run, and one for .NET Framework that prints the expected JSON. The .NET Framework version references the Program.cs file from the .NET Core project so the code is by definition the same.

Downgrading the version of Newtonsoft.Json used to 10.0.3 makes the .NET Core version work.

I've included the code here for easier reading:

```csharp
using System;
using System.IO;
using Newtonsoft.Json;

namespace ReproduceDirectoryInfoJsonConverterIssue
{
    public class Program
    {
        public static void Main()
        {
            var value = new Foo
                        {
                            Bar = new DirectoryInfo(@"c:\temp")
                        };

            try
            {
                var json = JsonConvert.SerializeObject(value, new DirectoryInfoJsonConverter());

                // Expected behavior is to print this
                // This works in .NET Framework app
                Console.WriteLine(json);
            }
            catch (Exception ex)
            {
                // Actual behavior in .NET Core 2.0 app
                Console.WriteLine(ex);
            }

            Console.ReadLine();
        }
    }

    public class Foo
    {
        public DirectoryInfo Bar { get; set; }
    }

    public class DirectoryInfoJsonConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(DirectoryInfo);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.Value is string s)
            {
                return new DirectoryInfo(s);
            }

            throw new ArgumentOutOfRangeException(nameof(reader));
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            if (!(value is DirectoryInfo directoryInfo))
            {
                throw new ArgumentOutOfRangeException(nameof(value));
            }

            writer.WriteValue(directoryInfo.FullName);
        }
    }
}
```

**Comment by JamesNK** [comment]
Ah ok. Stick with 10.0.3 and there will be a new version with a fix in a week or so.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/8bb337debb338179a64cfdd366d764ce57492aef
