### ISSUE TITLE
WritePropertyName doesn´t respect NamingStrategy on custom resolver

### ISSUE THREAD

**Issue by CheloXL** [JamesNK/Newtonsoft.Json#1621]
I have created a custom contract resolver that inherits from DefaultContractResolver. The NamingStrategy is set to CamelCaseNamingStrategy and in the CreateContract method I'm setting custom converters on the .Converter property of the JsonContract.

When using WritePropertyName inside my custom JsonConverter, I would expect the property name to respect the convention set on the NamingStrategy, but that's not happening. The property name is being written as-is.

Is there a way that can be done?

**Comment by JamesNK** [comment]
That's by design. WritePropertyName has no knowledge of the serializer and its settings.

What you can do is this - https://github.com/JamesNK/Newtonsoft.Json/blob/92d170a0783bc962f52faf02acfcecbe21d3b683/Src/Newtonsoft.Json/Converters/DataTableConverter.cs#L73
