### ISSUE TITLE
Previously serialized data can no longer be read in v11.0.1

### ISSUE THREAD

**Issue by jonreis** [JamesNK/Newtonsoft.Json#1626]
Hello JamesNK, it could be that my original classes were not constructed properly for serialization and v10.0.3 let me get away with it. Any help/direction you can give me on this will be greatly appreciated. 

I am running into an issue with the v11.0.1 that works fine in v10.0.3. I have quite a bit of data stored that is in this in the serialized output that can no longer be read. The exception I receive when reading this data is:

Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Additional information: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Newtonsoft.Test.ProcessingEventCollection' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '[0].Events', line 1, position 12. occurred

Data serialized in v10.0.3 looks as follows:

      var newtonsoft10_0_3 = "[{\"Events\":[{\"EventDateTime\":\"0001-01-01T00:00:00\",\"Message\":\"Test Message\"}]}]";

If I serialize the same object in v11.0.1 it comes out as:

      var newtonsoft11_0_1 = "[{\"Events\":{}}]";

A stripped down version of the classes and a unit test follow:

```javascript

 [TestFixture]
  class SerializeEventHistoryTest
  {
    [Test]
    public void DeviceHistorySerializesAndDeserializes_Bug()
    {
      var histories = new List<DeviceHistory>();
      var result = new DeviceHistory();
      result.Events.Add(new ProcessingEvent { EventDateTime = DateTime.MinValue, Message = "Test Message" });
      histories.Add(result);

      var newtonsoft11_0_1 = "[{\"Events\":{}}]";
      var newtonsoft10_0_3 = "[{\"Events\":[{\"EventDateTime\":\"0001-01-01T00:00:00\",\"Message\":\"Test Message\"}]}]";

      var deserializedResult = JsonConvert.DeserializeObject<List<DeviceHistory>>(newtonsoft10_0_3);
      Assert.AreEqual(histories[0].Events[0].ToString(), deserializedResult[0].Events[0].ToString());
    }
  }

  [DataContract]
  public class ProcessingEvent
  {
    [DataMember]
    public DateTime EventDateTime { get; set; }

    [DataMember]
    public string Message { get; internal set; }
  }

  [DataContract]
  public class DeviceHistory
  {
    private readonly ProcessingEventCollection m_ProcessingEvents = new ProcessingEventCollection();

    [DataMember]
    public ProcessingEventCollection Events
    {
      get { return m_ProcessingEvents; }
    }
  }

  [DataContract]
  public class ProcessingEventCollection : IList<ProcessingEvent>
  {
    private readonly List<ProcessingEvent> m_ProcessingEvents = new List<ProcessingEvent>();

    public bool Remove(ProcessingEvent item)
    {
      return m_ProcessingEvents.Remove(item);
    }

    public int Count
    {
      get
      {
        return m_ProcessingEvents.Count;
      }
    }

    public bool IsReadOnly
    {
      get { return false; }
    }

    public void Add(ProcessingEvent pe)
    {
      m_ProcessingEvents.Add(pe);
    }

    public void Clear()
    {
      m_ProcessingEvents.Clear();
    }

    public bool Contains(ProcessingEvent item)
    {
      return m_ProcessingEvents.Contains(item);
    }

    public void CopyTo(ProcessingEvent[] array, int arrayIndex)
    {
      m_ProcessingEvents.CopyTo(array, arrayIndex);
    }

    public IEnumerator<ProcessingEvent> GetEnumerator()
    {
      return m_ProcessingEvents.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
      return GetEnumerator();
    }

    public int IndexOf(ProcessingEvent item)
    {
      return m_ProcessingEvents.IndexOf(item);
    }

    public void Insert(int index, ProcessingEvent item)
    {
      m_ProcessingEvents.Insert(index, item);
    }

    public void RemoveAt(int index)
    {
      m_ProcessingEvents.RemoveAt(index);
    }

    public ProcessingEvent this[int index]
    {
      get
      {
        return m_ProcessingEvents[index];
      }
      set
      {
        m_ProcessingEvents[index] = value;
      }
    }
  }

**Comment by JamesNK** [comment]
This will be changed back in 11.0.2 https://github.com/JamesNK/Newtonsoft.Json/commit/c72f785b9c20328af42aa58ac1e99f32c0c0de52

**Comment by jonreis** [comment]
@JamesNK Great. Thank you.

Could you please also reconsider fixing: https://github.com/JamesNK/Newtonsoft.Json/issues/1622?

**Comment by JamesNK** [comment]
That's a legitimate bug fix that needs to happen. Using ISerializable with a type that doesn't have Serializable attribute is not correct.
