### ISSUE TITLE
IEnumerables with DataContract, are not Enumerated any more in V11

### ISSUE THREAD

**Issue by jogibear9988** [JamesNK/Newtonsoft.Json#1627]
If you have an Enumerable Class wich has a dataContract, it's not enumerated any more in V11.

This is a breaking change from V10.

It's in this commit: https://github.com/JamesNK/Newtonsoft.Json/commit/e9e2d006a50d6b54f14c28dff856ff2b105ddb9e

It did break my application. Can we change this?

Maybe we can serialize the Properties and the Collection Elements? I know this will not work with normal JSON, but when we use the "$values" property for the return value, we could serialize both!

**Comment by jogibear9988** [comment]
maybe related to #1626

**Comment by jogibear9988** [comment]
It is another bug, it has nothing to do with "IQueryable", it's because of the DataMember Attribute!

But it does return another result in V11 then in V10!

**Comment by jogibear9988** [comment]
And I think also, if the "$values" return method is used, we can include the properties AND the collection elements!

**Comment by jogibear9988** [comment]
@JamesNK 
any comment about this issue?

**Comment by JamesNK** [comment]
This will be changed back in 11.0.2 https://github.com/JamesNK/Newtonsoft.Json/commit/c72f785b9c20328af42aa58ac1e99f32c0c0de52
