### ISSUE TITLE
JObject.GetPropertyOwner() returns null, breaking JPropertyDescriptor.GetValue for PropertyGrid

### ISSUE THREAD

**Issue by richard-fine** [JamesNK/Newtonsoft.Json#1630]
When using a `JObject` instance with a `System.Windows.Forms.PropertyGrid`, the names of properties are correctly displayed, but fetching the values produces a `NullReferenceException`.

The reference source for `PropertyGrid` does the following in `GridEntry.GetPropEntries` when retrieving the value for each entry:

```csharp
object owner = obj;
if (obj is ICustomTypeDescriptor)
{
    owner = ((ICustomTypeDescriptor)obj).GetPropertyOwner(pd);
}
pd.GetValue(owner);
```

`JObject` implements `ICustomTypeDescriptor`, so the if-clause is executed; however, the implementation of `JObject.GetPropertyOwner()` always returns `null`. This means that the owner object passed to `JPropertyDescriptor.GetValue` is always `null`, causing it to throw a `NullReferenceException`.

I *think* the solution here is to change `JObject.GetPropertyOwner` to return `this` rather than `null`.

**Comment by richard-fine** [comment]
I can confirm that wrapping `JObject` in my own class that forwards the `ICustomTypeDescriptor` methods _except_ `GetPropertyOwner`, which I make return the `JObject` itself, appears to work around the problem for me.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/c72f785b9c20328af42aa58ac1e99f32c0c0de52
