### ISSUE TITLE
CamelCasePropertyNamesContractResolver resolution changed

### ISSUE THREAD

**Issue by dbegent** [JamesNK/Newtonsoft.Json#1635]
We have just upgraded to the latest version (11 from 4.5) of Newtonsoft.Json and broken heaps of tests since the camel casing has changed. Aside from changing all of our tablet code to change, say, rTN to rtn which isn't feasible is there a way of setting the CamelCasePropertyNamesContractResolver to do exactly as it used to do? ie, RTN produces rTN not rtn

I imagine we can create our own implementation of DefaultContractResolver and do almost the same as CamelCasePropertyNamesContractResolver but change just the first character of each property. Am I right there?

Cheers,

Dan.

**Comment by JamesNK** [comment]
You can create your own version of `NamingStrategy` if you want the older camel casing logic.

https://www.newtonsoft.com/json/help/html/NamingStrategySkipSpecifiedNames.htm
