### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by ronfluegge** [JamesNK/Newtonsoft.Json#1636]
Jason.net is installed as a NuGet package in one of my solutions in VS 2017 version 15.6.0.

I was notified by VS that there is an update to version 11.0.1 from 10.0.3 available

When VS processes the update, I get this error from the Package Manager:

Attempting to gather dependency information for multiple packages with respect to project 'ReportOutput', targeting '.NETFramework,Version=v4.5.2'

Gathering dependency information took 543.71 ms

Attempting to resolve dependencies for multiple packages.

**Unable to resolve dependencies. 'Newtonsoft.Json 11.0.1' is not compatible with 'Microsoft.Graph 1.7.0 constraint: Newtonsoft.Json (>= 6.0.1 && < 11.0.0)', 'Microsoft.Graph.Core 1.7.0 constraint: Newtonsoft.Json (>= 6.0.1 && < 11.0.0)'.**

ReportOutput is my project in the solution.

Ron Fluegge

![image](https://user-images.githubusercontent.com/6014965/37009126-2001de0e-20ab-11e8-8f52-bd623c209e45.png)

**Comment by JamesNK** [comment]
The issue is in the error description: Microsoft.Graph doesn't allow Newtonsoft.Json 11.

You will want to bring it up with them.

**Comment by ronfluegge** [comment]
Ok ... thanks

Ron
