### ISSUE TITLE
StringEnumConverter throws with F# internal enum in 11.0.1

### ISSUE THREAD

**Issue by csmager** [JamesNK/Newtonsoft.Json#1642]
### Source/destination types

```fsharp
module private Types =
    
    [<JsonConverter(typeof<StringEnumConverter>)>]
    type Foo =
        | Bar = 0
    
    type Baz =
        { [<JsonProperty>]Foo : Foo }
```

### Expected behavior

In 10.0.3, when I serialize an instance of `Baz` I get this:
```javascript
{"Foo":"Bar"}
```

### Actual behavior

In 11.0.1, I get a null reference exception.

### Steps to reproduce

```csharp
JsonConvert.SerializeObject({Foo = Foo.Bar})
```

On some digging, it seems this occurs because of the way F# compiles this enum combined with a change in [`EnumUtils.InitializeValuesAndNames`](https://github.com/JamesNK/Newtonsoft.Json/blob/cfdd84ef799e79fc50e60286afa222ae27365a4b/Src/Newtonsoft.Json/Utilities/EnumUtils.cs#L48-L80) between 10.0.3 and 11.0.1. The offending line is this:

```csharp
FieldInfo f = enumType.GetField(name, BindingFlags.Public | BindingFlags.Static);
```

It returns `null`. I believe this is because of a difference in how F# compiles this enum. Although the IL decompiled to C# looks like you'd expect:
```csharp
internal enum Foo
{
    Bar
}
```
The IL for `Bar` looks like this:
```
.field assembly static literal valuetype Program/Types/Foo Bar = int32(0)
```
Where if you were to compile the same enum in C#, this would include the `public` modifier:
```
.field assembly public static literal valuetype Program/Types/Foo Bar = int32(0)
```
The fix is pretty trivial, we can change the line to:
```csharp
FieldInfo f = enumType.GetField(name, 
    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
```
Happy to open a PR if this change is acceptable.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/c4af75c8e91ca0d75aa6c335e8c106780c4f7712
