### ISSUE TITLE
dictionary<string,object> convert by defaulkt in int64

### ISSUE THREAD

**Issue by manojnctks** [JamesNK/Newtonsoft.Json#1646]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```
Hi, 
I have a dictionary<string,object> and I store some value say
Dictionary<string,object> obj=new Dictionary<string,object>{
{"MyKey",123}
}
when I serialze this and desrialize it convert the value i.e 123 to default int64 type whereas I want it to be in int32, how to handle.

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by JamesNK** [comment]
There is no type information so there is no way for Json.NET to know what you want so integers are deserialized as Int64.
