### ISSUE TITLE
Deserialization of ginormous object silently returns null

### ISSUE THREAD

**Issue by TonyValenti** [JamesNK/Newtonsoft.Json#1647]
Hi Newtonsoft,
I have a really large JSON object (900MB - 2million objects) that I need to deserialize.  When I try to deserialize from a stream, no exceptions get thrown and the serializer simply returns null.  Why would this be?  What do I need to do in order to deserialize this giant object?

**Comment by JamesNK** [comment]
I don't know why that would happen. You haven't enabled error handling at all? Errors should be thrown out of the deserialize method.

**Comment by TonyValenti** [comment]
Figured it out.  It was a bad stream.
