### ISSUE TITLE
Case insensitive works incorrect

### ISSUE THREAD

**Issue by mikasoukhov** [JamesNK/Newtonsoft.Json#1648]
{"o":"v","O":-1}

Trying to deserialize into

```
class Type1
{
  [JsonProperty("o")]
  public string Prop1 {get;set;}
}
```

In result Type1.Prop1 override by -1 value. Reason - https://stackoverflow.com/a/34637862/8029915

You can do the more elegant way to deserialize. If the property was already set by json it should be ignore from search algo.

**Comment by WeihanLi** [comment]
meet the same problem

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/1571
