### ISSUE TITLE
Consider making UnixDateTimeConverter configurable with respect to units

### ISSUE THREAD

**Issue by dls314** [JamesNK/Newtonsoft.Json#1652]
It would be nice if UnixDateTimeConverter were configurable so that it worked for values in the input expressed as milliseconds since the Unix epoch (not just seconds as current).

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/UnixDateTimeConverter.cs#L113

**Comment by JamesNK** [comment]
A Unix timestamp is always seconds since 1970, so configuring it doesn't make sense. There isn't much code there to copy and paste if you want to customize it.

**Comment by dls314** [comment]
Every timestamp I get out of AWS apis is milliseconds since the epoch. But yes, easily copied.

**Comment by CZEMacLeod** [comment]
On embedded devices Epoch can vary a bit and times may be internally stored as seconds, milliseconds or even microseconds.
If this was EpochDateTimeConverter with epoch date and units it would be helpful and have UnixDateTimeConverter inherit with fixed parameters. But as @JamesNK said, it is not a lot of code to copy/paste.

**Comment by wind-rider** [comment]
:+1: for a configurable EpochDateTimeConverter!

**Comment by rockstardev** [comment]
I don't have access to some of the classes/methods, here is best I could do with standalone class:

```
	/// <summary>
	/// Converts a <see cref="DateTime"/> to and from Unix epoch time
	/// </summary>
	public class UnixMillisecondsConverter : DateTimeConverterBase {
		internal static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

		public override bool CanConvert(Type objectType) {
			return objectType == typeof(DateTime) || objectType == typeof(DateTimeOffset);
		}

		/// <summary>
		/// Writes the JSON representation of the object.
		/// </summary>
		/// <param name="writer">The <see cref="JsonWriter"/> to write to.</param>
		/// <param name="value">The value.</param>
		/// <param name="serializer">The calling serializer.</param>
		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			long milliseconds;

			if (value is DateTime dateTime) {
				milliseconds = (long)(dateTime.ToUniversalTime() - UnixEpoch).TotalMilliseconds;
			}
            else if (value is DateTimeOffset dateTimeOffset)
            {
                milliseconds = (long)(dateTimeOffset.ToUniversalTime() - UnixEpoch).TotalMilliseconds;
            }
			else {
				throw new JsonSerializationException("Expected date object value.");
			}

			if (milliseconds < 0) {
				throw new JsonSerializationException("Cannot convert date value that is before Unix epoch of 00:00:00 UTC on 1 January 1970.");
			}

			writer.WriteValue(milliseconds);
		}

		/// <summary>
		/// Reads the JSON representation of the object.
		/// </summary>
		/// <param name="reader">The <see cref="JsonReader"/> to read from.</param>
		/// <param name="objectType">Type of the object.</param>
		/// <param name="existingValue">The existing property value of the JSON that is being converted.</param>
		/// <param name="serializer">The calling serializer.</param>
		/// <returns>The object value.</returns>
		public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) {
			bool nullable = Nullable.GetUnderlyingType(objectType) != null;
			if (reader.TokenType == JsonToken.Null) {
				if (!nullable) {
					throw new JsonSerializationException($"Cannot convert null value to {objectType}.");
				}

				return null;
			}

			long milliseconds;

			if (reader.TokenType == JsonToken.Integer) {
				milliseconds = (long)reader.Value;
			} else if (reader.TokenType == JsonToken.String) {
				if (!long.TryParse((string)reader.Value, out milliseconds)) {
					throw new JsonSerializationException($"Cannot convert invalid value to {objectType}.");
				}
			} else {
				throw new JsonSerializationException($"Unexpected token parsing date. Expected Integer or String, got {reader.TokenType}.");
			}

			if (milliseconds >= 0) {
				DateTime d = UnixEpoch.AddMilliseconds(milliseconds);

                Type t = (nullable)
                    ? Nullable.GetUnderlyingType(objectType)
                    : objectType;
                if (t == typeof(DateTimeOffset))
                {
                    return new DateTimeOffset(d, TimeSpan.Zero);
                }
				return d;
			} else {
				throw new JsonSerializationException($"Cannot convert value that is before Unix epoch of 00:00:00 UTC on 1 January 1970 to {objectType}.");
			}
		}
	}
```

**Comment by jderose9** [comment]
Thanks @rockstardev ! This was helpful. Yes, many of the types used in the existing implementation are marked internal.

**Comment by lezar44** [comment]
If you need to allow date before 1970, you can use this (based on @rockstardev answer) :

    /// <summary>
    /// Converts a <see cref="DateTime"/> to and from Unix epoch time
    /// </summary>
    public class UnixMillisecondsConverter : DateTimeConverterBase
    {
        internal static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        /// <summary>
        /// Gets or sets a value indicating whether the dates before Unix epoch
        /// should converted to and from JSON.
        /// </summary>
        /// <value>
        /// <c>true</c> to allow converting dates before Unix epoch to and from JSON;
        /// <c>false</c> to throw an exception when a date being converted to or from JSON
        /// occurred before Unix epoch. The default value is <c>true</c>.
        /// </value>
        public bool AllowPreEpoch { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnixMillisecondsConverter"/> class.
        /// </summary>
        public UnixMillisecondsConverter() : this(true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnixMillisecondsConverter"/> class.
        /// </summary>
        /// <param name="allowPreEpoch">
        /// <c>true</c> to allow converting dates before Unix epoch to and from JSON;
        /// <c>false</c> to throw an exception when a date being converted to or from JSON
        /// occurred before Unix epoch. The default value is <c>true</c>.
        /// </param>
        public UnixMillisecondsConverter(bool allowPreEpoch)
        {
            AllowPreEpoch = allowPreEpoch;
        }

        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(DateTime) || objectType == typeof(DateTimeOffset);
        }

        /// <summary>
        /// Writes the JSON representation of the object.
        /// </summary>
        /// <param name="writer">The <see cref="JsonWriter"/> to write to.</param>
        /// <param name="value">The value.</param>
        /// <param name="serializer">The calling serializer.</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            long milliseconds;

            if (value is DateTime dateTime)
            {
                milliseconds = (long)(dateTime.ToUniversalTime() - UnixEpoch).TotalMilliseconds;
            }
            else if (value is DateTimeOffset dateTimeOffset)
            {
                milliseconds = (long)(dateTimeOffset.ToUniversalTime() - UnixEpoch).TotalMilliseconds;
            }
            else
            {
                throw new JsonSerializationException("Expected date object value.");
            }

            if (!AllowPreEpoch && milliseconds < 0)
            {
                throw new JsonSerializationException("Cannot convert date value that is before Unix epoch of 00:00:00 UTC on 1 January 1970.");
            }

            writer.WriteValue(milliseconds);
        }

        /// <summary>
        /// Reads the JSON representation of the object.
        /// </summary>
        /// <param name="reader">The <see cref="JsonReader"/> to read from.</param>
        /// <param name="objectType">Type of the object.</param>
        /// <param name="existingValue">The existing property value of the JSON that is being converted.</param>
        /// <param name="serializer">The calling serializer.</param>
        /// <returns>The object value.</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            bool nullable = Nullable.GetUnderlyingType(objectType) != null;
            if (reader.TokenType == JsonToken.Null)
            {
                if (!nullable)
                {
                    throw new JsonSerializationException($"Cannot convert null value to {objectType}.");
                }

                return null;
            }

            long milliseconds;

            if (reader.TokenType == JsonToken.Integer)
            {
                milliseconds = (long)reader.Value;
            }
            else if (reader.TokenType == JsonToken.String)
            {
                if (!long.TryParse((string)reader.Value, out milliseconds))
                {
                    throw new JsonSerializationException($"Cannot convert invalid value to {objectType}.");
                }
            }
            else
            {
                throw new JsonSerializationException($"Unexpected token parsing date. Expected Integer or String, got {reader.TokenType}.");
            }

            if (AllowPreEpoch || milliseconds >= 0)
            {
                DateTime d = UnixEpoch.AddMilliseconds(milliseconds);

                Type t = (nullable)
                    ? Nullable.GetUnderlyingType(objectType)
                    : objectType;
                if (t == typeof(DateTimeOffset))
                {
                    return new DateTimeOffset(d, TimeSpan.Zero);
                }
                return d;
            }
            else
            {
                throw new JsonSerializationException($"Cannot convert value that is before Unix epoch of 00:00:00 UTC on 1 January 1970 to {objectType}.");
            }
        }
    }
