### ISSUE TITLE
order of "$type" in json does matter...

### ISSUE THREAD

**Issue by jogibear9988** [JamesNK/Newtonsoft.Json#1653]
try to desrialize the following json:

	{
	  "Id": "4989b523-2dcc-11e8-b7de-31b14dfbca5a",
	  "ServiceName": "CommonService",
	  "FunctionName": "CommitObjects",
	  "Parameters": {
		"sessionInformation": {
		  "SessionId": "ccbf0a3c-8e98-4307-8e7d-48ab6621a565",
		  "ClientMachineName": "ML-N-WS-106.mlog.ads"
		},
		"values": {
		  "$values": [
			{
			  "$type": "MCC.Common.ServiceInterfaces.DTO.UserDTO, MCC.Common.ServiceInterfaces",
			  "Id": "44cfd69a-2dcc-11e8-b7dd-31b14dfbca5a",
			  "MccEntityState": 1,
			  "Name": "Neuer User",
			  "FriendlyName": "Neuer User",
			  "IsActive": true,
			  "Groups": [
				
			  ],
			  "Roles": [
				
			  ],
			  "Password": ""
			}
		  ],
		  "$type": "MCC.Common.ServiceInterfaces.DTO.UserDTO[], MCC.Common.ServiceInterfaces"
		}
	  }
	}

to this class:

        internal class WebSocketCallDTO
        {
            public Guid Id { get; set; }

            public string ServiceName { get; set; }

            public ServiceType? ServiceType { get; set; }

            public string FunctionName { get; set; }

            public Dictionary<string, object> Parameters { get; set; }
        }

it will not work. if you move the second "$type" before the array, it works...

**Comment by CZEMacLeod** [comment]
I had a similar issue in an app I was writing, and found that it would deserialize to a JObject rather than the expected type if $type was not the first property.

My solution was to catch the JObject and explicitly deserialize it to the correct type...

My code:
```
var msg = serializer.Deserialize(jsonReader);
var jo = msg as Newtonsoft.Json.Linq.JObject;
if (jo != null)
{
	var jtype = jo.Value<string>("$type");
	if (jtype != null)
	{
		var type = serializer.SerializationBinder.BindToType(null, jtype);
		if (type != null)
		{
			try
			{
				var msg2 = jo.ToObject(type, serializer);
				if (msg2 != null)
				{
					msg = msg2;
				}
			}
			catch (Exception e)
			{
				// Report error
			}
		}
	}
}
```

If you change the lines `var jo = msg as Newtonsoft.Json.Linq.JObject;` to `var jo = msg.Parameters["values"] as Newtonsoft.Json.Linq.JObject;` and `msg = msg2;` to `msg.Parameters["values"] = msg2;` I think it would cover your case.

**Comment by CZEMacLeod** [comment]
@dbc2 Thank-you for that pointer. I worked around the issue as I didn't find that option! I'm going to add that to our code as see if it resolves our problem.

**Comment by dbc2** [comment]
<i>I haven't yet checked what the actual implementation does.<i> I think it does roughly what you do, which is to pre-load into a `JObject`.  See [`JsonSerializerInternalReader.CreateObject()`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L424) around line 424.  So the performance hit might be roughly on par with what you are doing now.  Definitely profile it however.

**Comment by JamesNK** [comment]
ReadAhead is what you want.
