### ISSUE TITLE
Throw errors on blank strings or empty objects when checking for missing member handling

### ISSUE THREAD

**Issue by michaeloyer** [JamesNK/Newtonsoft.Json#1655]
### Source/destination types

```csharp
 public class MyObj
 {
     public string Prop { get; set; }
 }
```

### Source/destination JSON

```javascript
(blank)
OR
{}

```

### Expected behavior

An exception to be thrown

### Actual behavior

Returned null value

### Steps to reproduce

```csharp
using Newtonsoft.Json;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var settings = new JsonSerializerSettings
            {
                MissingMemberHandling = MissingMemberHandling.Error
            };

            //unexpected
            JsonConvert.DeserializeObject<MyObj>("", settings); //returns null
            JsonConvert.DeserializeObject<MyObj>("{}", settings); //returns null

            //expected
            JsonConvert.DeserializeObject<MyObj>(null, settings); //throws System.ArgumentNullException
            JsonConvert.DeserializeObject<MyObj>("[]", settings); //throws Newtonsoft.Json.JsonSerializationException
            JsonConvert.DeserializeObject<MyObj>("{'Test': 'Test'}", settings); //throws Newtonsoft.Json.JsonSerializationException
            JsonConvert.DeserializeObject<MyObj>("{'Prop': 'Test'}", settings); //returns MyObj instance
        }
    }

    public class MyObj
    {
        public string Prop { get; set; }
    }
}
```

This is a minor issue I can code around, but it seemed like a bug.

**Comment by michaeloyer** [comment]
Thanks for the suggestion! That does throw an error for empty brackets '{}' so it's nice to have that as a work around it still wouldn't with the empty string however (it still returns null).

Technically the attribute is more concerned with the value then it is with the key/property. The Required attribute will throw if you try to parse a null value: 
```cs
JsonConvert.DeserializeObject<MyObj>("{'Prop':null}"); //Error
```

But it won't with the MissingMemberHandling (without the required attribute):

```cs
JsonConvert.DeserializeObject<MyObj>("{'Prop':null}", new JsonSerializerSettings { MissingMemberHandling = MissingMemberHandling.Error }); //valid (which makes sense)
```

I'd still say that it would be unexpected that you wouldn't be getting an error since the 'Prop' member is missing in both the '{}' and '' JSON strings. Actually I'd put one more issue in that I would expect the following line to also throw an error but instead returns a null value:

```cs
JsonConvert.DeserializeObject<MyObj>("null", settings); //returns null
```

I discovered that when someone mentioned 'null' as being valid json in [this stackoverflow answer](https://stackoverflow.com/a/30621997). According to this page it looks like an empty string isn't valid json at all, so perhaps an empty string should be throwing with or without the MissingMemberHandling settings?

**Comment by JamesNK** [comment]
An empty object shouldn't throw. Properties aren't required by default. An empty string should throw but fixing it would be a breaking change. It's simple enough to throw an error yourself if you don't want an empty string.

**Comment by michaeloyer** [comment]
> An empty object shouldn't throw. Properties aren't required by default.

Wouldn't properties be required when using the MissingMemberHandling.Error setting? I may be confusing what you mean by that. 

> An empty string should throw but fixing it would be a breaking change.

That makes sense. Kind of too bad but that was the scenario I coded around.

Thanks for your consideration!

**Comment by JamesNK** [comment]
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Required.htm

**Comment by michaeloyer** [comment]
It finally clicked for me where I had it wrong when I read again the following link. MissingMemberHandling is for properties missing on the object, Required is for properties missing in the JSON (like in the empty json object example). I was treating MissingMemberHandling as missing in either the object OR the JSON. Thank you both for helping me to understand!

https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_MissingMemberHandling.htm

> Gets or sets how missing members **(e.g. JSON contains a property that isn't a member on the object)** are handled during deserialization.

**Comment by alex-valchuk** [comment]
I also interested in throwing serialization exceptions in cases when a user provides a key (for a not required property) for which a relevant value is supposed to be a complex object e.g:

invalid json - exception is thrown:
```
{
    "user_info": ""
}
```

valid json - no exceptions:
```
{
    "user_info": {
         "first_name": "John",
         "last_name": "Smith"
    }
}
```

Does anybody know how it can be achieved

**Comment by vladd** [comment]
@alex-valchuk Your example can be further simplified to deserializing `""` (i. e,, an text containing a string) into an instance of `UserInfo` class. `JsonConvert.DeserializeObject<UserInfo>("\"\"")` returns `null` instead of throwing an exception. I believe this to be a bug.
