### ISSUE TITLE
Serialize DynamicObject and ISerializable in version 11.0.3

### ISSUE THREAD

**Issue by ianselmi** [JamesNK/Newtonsoft.Json#1660]
Hi we try to serialize an object derived from DynamicObject, in version 10.X the method ISerializable.GetObjectData was called correctly, in latest version this method was not calling.

Follow an examples:
**Base class**
```
[Serializable]
        public class DynamicDTOObject : DynamicObject, ISerializable
        {
            private IDictionary<string, object> _dynamicValues;
            public DynamicDTOObject()
            {
                _dynamicValues = new Dictionary<string, object>();
            }

            public override bool TryGetMember(GetMemberBinder binder, out object result)
            {
                if (_dynamicValues.ContainsKey(binder.Name))
                {
                    result = _dynamicValues[binder.Name];
                    return true;
                }
                result = null;
                return false;
            }

            void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
            {
                //Serializza le proprietà dell'oggetto
                foreach (PropertyInfo pi in this.GetType().GetProperties())
                {
                    info.AddValue(pi.Name, pi.GetValue(this));                  
                }

                if (_dynamicValues == null) return;

                //Serializza le proprietà dinamiche
                foreach (var kvp in this._dynamicValues)
                {
                    info.AddValue(kvp.Key, kvp.Value);
                }
            }

            /// <summary>
            /// Aggiunge un dizionario di proprietà dinamiche
            /// </summary>
            /// <param name="values">Dizionario di proprietà aggiuntive</param>
            public void AddDynamicPropeties(IDictionary<string, object> values)
            {
                _dynamicValues = values;
            }
            public void AddPropertyValue(string key, object data)
            {
                _dynamicValues.Add(key, data);
            }
        }
```
**Test to reproduce the problem**
 ```
string json =
                JsonConvert.SerializeObject(
                    new MyDTO
                    {
                        Prop1 = "dddd",
                        Prop2 = "fff"
                    },
                    Formatting.Indented,
                    new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() }
                    );
```
In version 10.X that works in 11.X return an empty "{}" object. Is this a bug?

**Comment by konstantint** [comment]
Not sure whether it relates, but I just had a possibly related problem - an `ISerializable` class was `JsonConvert`-ed via `GetObjectData` in version 10 (as I wanted it to) but ceased to do so in version 11.

After a lengthy debugging process I found out that the new version, besides checking for a class being an instance of `ISerializable`, also makes sure the `[Serializable]` attribute is set on the class. (The relevant line of code is [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1200), compare with the [previous version](https://github.com/JamesNK/Newtonsoft.Json/blob/10.0.3/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1182)).

Does your `MyDTO` class have that attribute?

**Comment by ianselmi** [comment]
Hi konstantint, thanks for reply. My class MyDTO does not have [Serializable] attribute beacause DynamicDTOObject already has.
I try to add Serializable and verify.

**Comment by CedricDumont** [comment]
I had the same problem on a class and adding the `[Serialisable] `attribute solved this issue

**Comment by ianselmi** [comment]
With Serialisable attribute I solved the problema but I have more and more entities and I can't add the attribute on each it.
