### ISSUE TITLE
memory utilization keeps rising over time.

### ISSUE THREAD

**Issue by oscarcabrero** [JamesNK/Newtonsoft.Json#1661]
### Source/destination types

we generate hundreds of dynamic generated emited types into a an assembly at runtime

### Expected behavior

memory collected by GC

### Actual behavior

memory utilization keeps rising, profiler shows multiple dictionary entries of jsonconverters and attributes that keeps a reference to DynamicValueProvider which keeps references to system.reflection.DynamicMethods->DynamicILGenerator-> system.Byte[] 

we have around 2.7 million instances of byte[] and 529k entries of system.reflection.Emit.MethodBuilder instances this two accolunts for like 2

### Steps to reproduce

```csharp
JsonConvert.Deserialize
JsonConvert.Serialize
```
![newton](https://user-images.githubusercontent.com/20215173/38045490-c41cc83c-3271-11e8-8b9f-efa3a4458c69.png)

**Comment by danielzhe** [comment]
Can you provide a more specific example so I can try to reproduce? Even if you run an GC.Collect() (for debug purposes) the memory is not freed? I think that you may have some references to DefaultContractResolver (or one of it's subclasses) in your application that it's preventing GC to clear.
"system.reflection.DynamicMethods->DynamicILGenerator-> system.Byte[]" it's just the last chain of references.

**Comment by JamesNK** [comment]
A contract resolver will cache reflection information to improvement performance. If you are generating a lot of dynamic objects and serializing them then you can either use a new contract resolver with each serialization, or periodically replace it.
