### ISSUE TITLE
Error in the List<int> 

### ISSUE THREAD

**Issue by olavorn** [JamesNK/Newtonsoft.Json#1663]
### This code should return a serialized List<int>

```csharp
Newtonsoft.Json.JsonConvert.DeserializeObject<List<int>>("[034,007,021,100,127,183,78,169,117,009,99,97,128,174]")
```

But the fact the the "009" is an integer written with 0 throws exception, 

> Input string '009' is not a valid integer. Path '[9]', line 1, position 39.

but the result should be serialized as expected.

This works:
```csharp
Newtonsoft.Json.JsonConvert.DeserializeObject<List<int>>("[034,007,021,100,127,183,78,169,117,9,99,97,128,174]")
```
(Without the "00" in front of the 9 int. (10th element)

**Comment by TylerBrinkley** [comment]
Json.NET treats integers that start with 0 as octal, ie. have digits from 0-7. Since 9 is not a valid digit in the octal number system you get the error. Technically, valid json should not contain preceding zero's except if it starts as "0."
