### ISSUE TITLE
No PDBs

### ISSUE THREAD

**Issue by ZebraFlesh** [JamesNK/Newtonsoft.Json#1666]
There are no PDBs available on symbolsource.org after June 2015 (release 7.0.1). Where do we obtain PDBs for the more recent releases?

**Comment by JamesNK** [comment]
I've been pushing PDBs to symbolsource.org with every release...

**Comment by ZebraFlesh** [comment]
Am I looking in the wrong place? This page only shows PDBs up to v7.0.1: https://www.symbolsource.org/Public/Metadata/NuGet/Project/Newtonsoft.Json/

**Comment by krassx** [comment]
Probably folks have already discovered that, but will post fo those who still looking for an answer. According to https://tripleemcoder.com/2015/10/04/moving-to-the-new-symbolsource-engine/ symbolsource.org is not maintained any more. All the packages are now available at https://nuget.smbsrc.net/

Here is the deprecation notice at the SymbolSource repo: https://github.com/SymbolSource/SymbolSource#project-introduction

**Comment by MagicAndre1981** [comment]
If [SourceLink](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#why-source-link) gets[ enabled](https://github.com/JamesNK/Newtonsoft.Json/pull/1746). the PDB is embedded and includes a JSON to fetch the source here from github to allow easy debugging.

**Comment by JamesNK** [comment]
When Newtonsoft.Json.csproj was switched to the new SDK it started producing portable PDBs, and symbolsource.org doesn't support the new portable format.

For future debugging PDBs will be in the main Newtonsoft.Json package and SourceLink will be enabled https://github.com/JamesNK/Newtonsoft.Json/pull/1746
