### ISSUE TITLE
Serializing a StructureMapBuildException doesn't work anymore

### ISSUE THREAD

**Issue by AlexEndris** [JamesNK/Newtonsoft.Json#1669]
Due to an mistake in our code where something threw an exception while resolving an instance through StructureMap we discovered that there is a serialization problem in version 11.*. In our AspNetCore Application this results in a StackOverflowException.

When using version 10.* the StructureMapBuildException object serializes as expected and very fast.

You can reproduce it with the following code in a console app.

Program.cs:
```csharp
using System;
using System.Threading;
using Newtonsoft.Json;
using StructureMap;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            TestMethod();
        }

        private static void TestMethod()
        {
            var container = new Container(
                x =>
                    x.For<ITest>()
                        .Use(y => ThrowException()));

            try
            {
                container.GetInstance<ITest>();
            }
            catch (Exception e)
            {
                string serializedObject = JsonConvert.SerializeObject(e); // Will get stuck here using newtonsoft.json version 11.0.2
                Console.WriteLine(serializedObject); // Reaches this with no problem in version 10
            }
        }

        private static Test ThrowException()
        {
            throw new NotImplementedException();
        }
    }

    interface ITest { }
    class Test : ITest { }
}
```

ConsoleApp.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="StructureMap" Version="4.6.1" />
  </ItemGroup>

</Project>
```

**Comment by jeroenheijmans** [comment]
I can reproduce this in a .NET Core Console application. Hooked it up to the JSON.Net source, my debugger gets stuck on the `_serializeStack.Contains(value` call inside `CheckForCircularReference` for this kind of `value`:

> `{Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null}`

Wasn't yet able to further pin down this issue though, but perhaps this helps someone.

**Comment by danielzhe** [comment]
I found the change that breaks this. It was on [this commit](https://github.com/JamesNK/Newtonsoft.Json/commit/48be21d4cebda1e849508efe816719223dbef238). 
Previous in this case example that @AlexEndris shows, the contract resolve was ISerializableContract. 
After this change, it is ObjectContract, which for some reason let the execution reach the line that @jeroenheijmans described crashing the serialization.

**Comment by mzagel** [comment]
Are there any updates on this issue?
Can we expect a fix in the next version?

**Comment by AlexEndris** [comment]
Do we have any new information on this issue?

**Comment by JamesNK** [comment]
My guess is StructureMapBuildException isn't marked as `[Serializable]`.
