### ISSUE TITLE
Stackoverflow with Vector3

### ISSUE THREAD

**Issue by Mispon** [JamesNK/Newtonsoft.Json#1670]
Good day!

In newest version I faced with next problem:
when I try do `JsonConvert.SerializeObject(new Vector3(1, 1, 1))`
I have stackoverflow exeption

**Comment by danielzhe** [comment]
Is it Vector3 from System.Numerics.Vectors or is it your code? If is it your code, probably you have some loop reference (circular reference).

**Comment by Mispon** [comment]
It from other developers API, but when I used version 10.0.3 all works fine. After packet update I got exemptions and revert update.

**Comment by jeroenheijmans** [comment]
I tried to reproduce this, with these steps:

1. Using VS2017 15.6.5 on Windows 10 created a new .NET Core (2.0) Console App
2. ` Install-Package Newtonsoft.Json -Version 11.0.2`
3. Replace hello world `WriteLine` call with this:

```csharp
Console.WriteLine(
    Newtonsoft.Json.JsonConvert.SerializeObject(
        new System.Numerics.Vector3(1, 1, 1)));

Console.ReadKey();
```

4. Run it.

Result: output of `{"X":1.0,"Y":1.0,"Z":1.0}

Which is as expected.

@Mispon Could you tell us what we need to different to reproduce your issue?

**Comment by Mispon** [comment]
@jeroenheijmans I think problem in custom API Vector3 realization. Thank you!
