### ISSUE TITLE
Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat'

### ISSUE THREAD

**Issue by VladimirAkopyan** [JamesNK/Newtonsoft.Json#1671]
The UWP library Template 10 v1.1.12 relies on Newtonsoft.Json and since v11.0.1 throws the exception: 

`System.MissingMethodException: 'Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.'`

When 'NavigationServiceFactory' is used. Like Such: 
` var navService = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude, shell.GetContentFrame);`
Last parameter is just a UWP Frame, so nothing interesting happening there. 

Newtonsoft versions: 
10.0.1 -> ok
10.0.3 -> ok
11.0.1 -> crash
11.0.3 -> crash
UWP 6.0.8

Please advise if this is best place to report this

**Comment by JamesNK** [comment]
`TypeNameAssemblyFormat` is obsolete because it could cause this error on some platforms. You should use `TypeNameAssemblyFormatHandling` instead.
