### ISSUE TITLE
Compatibility with openstack.net

### ISSUE THREAD

**Issue by rivdiv** [JamesNK/Newtonsoft.Json#1673]
I'm having an issue updating json.net due to incompatibility with openstack:
Nuget throws this issue when updating json.net:

Unable to find a version of 'openstack.net' that is compatible with 'Newtonsoft.Json 11.0.2'.

I have other packages which rely on json.net 10> that need to be updated by tomorrow but can't be due to this issue.

How can I resolve this?

**Comment by JamesNK** [comment]
Hi

I'm not responsible for openstack.net. Ask them.
