### ISSUE TITLE
Documentation: clearly indicate Breaking Changes

### ISSUE THREAD

**Issue by Dunken** [JamesNK/Newtonsoft.Json#1674]
I would like to pick up on https://github.com/JamesNK/Newtonsoft.Json/issues/985: it would be very nice if the [Release Notes](https://github.com/JamesNK/Newtonsoft.Json/releases) would clearly indicate if a breaking change has been made. If I'm not wrong `Changes` don't necessarily mean breaking changes.

**Comment by JamesNK** [comment]
Anything under changes could be a breaking change to someone. Even some of the things under fixed bugs are breaking changes if you're depending on the broken behavior.

**Comment by JamesNK** [comment]
I don't know what you're asking for. There is no definition for what a breaking change is on that website.

Changes are already listed as **Change** in release notes and in my opinion Json.NET already follows semver as closely as practically possible.
