### ISSUE TITLE
ToObject - readonly Enum

### ISSUE THREAD

**Issue by mpcarlos87** [JamesNK/Newtonsoft.Json#1676]
### Source/destination types
```csharp
    public class ScriptIO 
    {
        public readonly ScriptVarType Type;

        public ScriptIO(ScriptVarType varType)
        {
            Type = varType;
        }

    }

    public enum ScriptVarType
    {
        TypeA,
        TypeB,
        TypeC
    }
```
### Source/destination JSON
{  "Test": {    "Type": 2  }}

### Expected behavior
 When calling JObject.ToObject<ScriptIO>() convert back the enum into the correct value (TypeC)

### Actual behavior

If the enum is **readonly**, it converts back the value as the first value of the enumeration (in this case is TypeA) while the right value was TypeC.

If the enum is **not readonly** the returned value is the expected.

### Steps to reproduce
```csharp
        static void Main(string[] args)
        {
            JObject baseObj=new JObject();
            baseObj.Add("Test",JObject.FromObject(new ScriptIO(ScriptVarType.TypeC)));
            string t = baseObj.ToString();
            Console.WriteLine(t);
            JObject retBaseObj = JObject.Parse(t);
            ScriptIO _retInputs= retBaseObj["Test"].ToObject<ScriptIO>();
            Console.WriteLine("type read: "+ _retInputs.Type);
            Console.ReadLine();
        }
```

**Comment by TylerBrinkley** [comment]
If you change the constructor parameter to match the name of the field it will work.

**Comment by mpcarlos87** [comment]
Interesting... thanks!!
