### ISSUE TITLE
Support for I-JSON

### ISSUE THREAD

**Issue by cyberphone** [JamesNK/Newtonsoft.Json#1686]
A limited research effort validated my suspicions that platform architects have created (or are in the process of creating), their own proprietary solutions for supporting data types which doesn't naturally fit into the number universe limited by IEEE-754 double precision.

https://tools.ietf.org/html/rfc7493

Related:
#845
javaee/jsonb-spec#80 (comment)
dotnet/corefx#29271
json-iterator/go#267

Is there anybody out there who might be interested in co-authoring an Internet-Draft addressing this topic?

**Comment by cyberphone** [comment]
It seems possible using the `Formatting` parameter for this purpose.  Using the https://github.com/JamesNK/Newtonsoft.Json/issues/1688 proposal you would end-up with:
`None`, `Indented`, `IJson`, `IJsonIndented`, `Sorted`, `SortedIJson`

**Comment by JamesNK** [comment]
I don't want to embed logic about another spec into the low level JsonReader/JsonWriter.

Json.NET is a general purpose library for working with JSON. If you want to use JSON in a specific way .NET then you can make another library that uses Json.NET.
