### ISSUE TITLE
Json.Net does not work with Squirrel package creator

### ISSUE THREAD

**Issue by thatsumoguy** [JamesNK/Newtonsoft.Json#1693]
I am building an app and using Squirrel for my package creation and updating. It seems there is some issue between Squirrel and Json.net. I tested this over and over and it seems to not be a problem when using OneClick or just launching the exe from the solution folder, and the issue goes away when using the Microsoft provider JSON serializer namespace.
### Source/destination types

Any type of serialization, deserialization, or parsing. No matter is used.

### Source/destination JSON

Doesn't matter what JSON you are using.

### Expected behavior

Should work with no issue, and does so when just launching the exe, or using OneClick

### Actual behavior

No serialization or parsing occurs, no errors, just nothing happens.

### Steps to reproduce

Just use any Json.net function with Squirrel.

**Comment by JamesNK** [comment]
I don't know anything about Squirrel. You will need to ask them.

There isn't anything special about the Newtonsoft.Json NuGet package or DLL.
