### ISSUE TITLE
exception using PreserveReferencesHandling with object with non default constructor

### ISSUE THREAD

**Issue by tomstaijen** [JamesNK/Newtonsoft.Json#17]
When object that is created with a non-default constructor and reference-resolving is used (with the default reference resolver), an exception is thrown in Serializer.ReferenceResolver.AddReference function: duplicate first or second (from the underlying bidirectional dictionary obviously).

For the created object, ReferenceResolver.AddReference is in fact invoked twice:
- First, in JsonSerializationInternalReader on line 1042 (CreateObjectFromNonDefaultConstructor)
- Second, in JsonSerializationInternalReader on line 1258 (PopulateObject)

Not sure if the Add in CreateObjectFromNonDefaultConstructor can simply be removed (guess it's there for a reason).

**Workaround**: don't use non-default constructors ^^

**Comment by KrustyMactavish** [comment]
Has this issue really been fixed? - I'm still getting it while trying to serialize/deserialize a generic dictionary and specifying PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.All

I believe I am using v4.5.5.14908

**Comment by bartelink** [comment]
A link to a repro PR and/or info as to whether you believe it works on the latest release is the least that can be expected when you are literally talking about a 10yo issue!
