### ISSUE TITLE
Feature request: Convert XML content for known escaped/encoded values.

### ISSUE THREAD

**Issue by askids** [JamesNK/Newtonsoft.Json#1705]
hi,

When we convert XML to JSON, is it possible to add an option where in the content within XML is also converted to standard format? The content in XML may have been escaped to prevent XML error. 
For example: XML could be <MYNODE>A & gt ; B</MYNODE>. But the converted JSON text can be A > B.  Currently this does not happen and &gt; is retained. There will be many other such conversions applied to prevent the XML from becoming invalid. So if this can be added as an option feature, that would be great!

Below, is the sample that I use (C# .Net FW v4.5.2, running 10.3). So if overloaded method is made available for SerializeXNode to accept this option, that would be a good feature to have.
```
XDocument doc = XDocument.Parse(strXmlData);
string jsonText = JsonConvert.SerializeXNode(doc);
```
Thanks!

PS: Ignore the space between "& gt ;"

**Comment by JamesNK** [comment]
This already worked for me:

```cs
XElement e = new XElement("root", "A > B");

string json = JsonConvert.SerializeXNode(e);

Assert.AreEqual(@"{""root"":""A > B""}", json);
```
