### ISSUE TITLE
Incompatibility with ECMAScript's JSON.parse()

### ISSUE THREAD

**Issue by cyberphone** [JamesNK/Newtonsoft.Json#1706]
I understand that you can write your own serializers but that seems little odd:
https://github.com/cyberphone/I-JSON-Number-System#jsonnet

This is related to https://github.com/JamesNK/Newtonsoft.Json/issues/1686

**Comment by JamesNK** [comment]
I don't know how exactly JSON.parse() is implemented and don't much care. Newtonsoft.Json targets handling the JSON 404 spec (and various extras like comments and trailing commas)

**Comment by cyberphone** [comment]
@JamesNK I think you were a little bit hot on the trigger here 😂

What I'm saying is that Json.NET's output by default is incompatible with browsers for applications needing anything beyond what's fitting in an IEEE-754 double precision number including 64-bit integers and monetary sums (Decimal type in C#).  The latter are practically always expressed as "7676.444".

**Comment by JamesNK** [comment]
I can't improve JSON.parse. Losing precision is a fact of life in a JavaScript floating point world. And if need be someone wants to they can customize what Json.NET outputs on serialization with a JsonConverter.

**Comment by cyberphone** [comment]
> I can't improve JSON.parse. Losing precision is a fact of life in a JavaScript floating point world. 

Well, if you look into the link I provided, the Oracle/JDK folks have addressed this topic in another way (using _Adaptive Notation_), making them by default compatible with Node.js and Browsers for applications needing "non-standard" numbers.

I'm rather proposing a global config (https://github.com/JamesNK/Newtonsoft.Json/issues/1686) which would address this as well as another issue.

**Comment by JamesNK** [comment]
JsonConverters exist for this reason.
