### ISSUE TITLE
Using JsonConverter to keep all datetime values formatted the same - how?

### ISSUE THREAD

**Issue by bdcoder2** [JamesNK/Newtonsoft.Json#1709]
Please see this issue which I have posted on StackOverflow at:

[https://stackoverflow.com/questions/50427493/using-jsonconverter-to-keep-all-datetime-values-formatted-the-same](https://stackoverflow.com/questions/50427493/using-jsonconverter-to-keep-all-datetime-values-formatted-the-same)

So far, no answers -- all I want to do is have date/times serialized in a CONSISTENT format, specifically:

`"yyyy-MM-ddTHH:mm:ss.fffffff"`

In other words, ALL date/time values will produce a 27 character date/time value (as above).  This is NOT currently the case with Newtonsoft.Json.   For example:

```
System.DateTime.MinValue will format as "0001-01-01T00:00:00"
System.DateTime.MaxValue will format as "9999-12-31T23:59:59.9999999"
new System.DateTime( 2018, 05, 16, 10, 0, 0, 0, DateTimeKind.Utc ) will format as "2018-05-16T10:00:00Z"
```

In all of the above, the DateTime values produce DIFFERENT date/time formats -- my use case REQUIRES all date/time values be formatted consistently.

Thanks in advance.

**Comment by bdcoder2** [comment]
Issue closed on StackOverflow -- HOWEVER...

Can the NEXT release of this library PLEASE include some sort of global "consistent" setting for date/time handling that uses the format in the original post for serializing all date/time values?, i.e.:

`"yyyy-MM-ddTHH:mm:ss.fffffff"`

A global setting that will cause all DateTime values to be serialized in the above format WITHOUT the need for any binding redirects would be a HUGE benefit to many other systems / libraries that make use of Json.Net to produce JSON -- ESPECIALLY schema-less databases such as CosmosDB where date/time values NEED to be stored in a consistent format across multiple documents within the database.

**Comment by JamesNK** [comment]
https://www.newtonsoft.com/json/help/html/SerializeDateFormatString.htm

?

**Comment by bdcoder2** [comment]
The issue was when you passed a document (object) to a system such as CosmosDB for serialization; which, under the hood uses Json.Net to serialize the object...

For example, the following will produce a JSON document with 4 datetime values, each formatted DIFFERENTLY (I have confirmed this with Microsoft):

Define a document to be saved in a schema-less database:

```
      public class datetime_doc
      {

         public System.DateTime uninitialized_utc;
         public System.DateTime min_utc;
         public System.DateTime max_utc;
         public System.DateTime specific_utc;

      }
```

Now set the some date/time values:

```
         dt_doc = new datetime_doc();

         dt_doc.min_utc = System.DateTime.MinValue;

         dt_doc.max_utc = System.DateTime.MaxValue;

         dt_doc.specific_utc = new System.DateTime( 2018, 05, 16, 10, 0, 0, 0, DateTimeKind.Utc );
```

And attempt to save the document in the database:

`   doc_client.CreateDocumentAsync( collection_uri, doc, request_opts );`

By default, Json.Net will serialize the document, but each date will be formatted DIFFERENTLY, i.e.:

```
{
"uninitialized_utc":"0001-01-01T00:00:00",
"min_utc":"0001-01-01T00:00:00",
"max_utc":"9999-12-31T23:59:59.9999999",
"specific_utc":"2018-05-16T10:00:00Z"
}
```
And the best part, now that all dates are in a different format, if you try to query the database using a query with a STANDARD date/time format such as:

`SELECT * FROM c WHERE c.min_utc = "0001-01-01T00:00:00.0000000'`

Queries will either fail (no results) or return incorrect results because the date/time values in the database documents are all formatted differently ! -- It really is a nightmare!

What is needed, is the date/time values to be serialized CONSISTENTLY, i.e.:

```
{
"uninitialized_utc":"0001-01-01T00:00:00.0000000",
"min_utc":"0001-01-01T00:00:00.0000000",
"max_utc":"9999-12-31T23:59:59.9999999",
"specific_utc":"2018-05-16T10:00:00.0000000"
}
```

Preferably, with a single, global setting.

Hope that clears up the original issue.
