### ISSUE TITLE
Serializing a .Net Core ClaimsIdentity with claims causes PlatformNotSupportedException

### ISSUE THREAD

**Issue by nd-srogers** [JamesNK/Newtonsoft.Json#1713]
I am in the process of upgrading my application to use .Net Core 2 and .NetStandard. In several areas I am serializing a `ClaimsIdentity` for logging and transmission purposes.

Whenever I try to serialize a `ClaimsIdentity` that contains at least one claim, I get a `PlatformNotSupportedException`. I suspect this is due to the Binary Serialization changes introduced in .Net Core 2 (https://github.com/dotnet/corefx/issues/23415). This appears to have been addressed previously (https://github.com/JamesNK/Newtonsoft.Json/issues/1404) however I am still getting this error in 11.0.2.

Using a decompiler, the error occurs in the `OnSerializingMethod` method in `ClaimsIdentity`, and only occurs when the identity has 1 or more claims attached:

```csharp
[OnSerializing]
private void OnSerializingMethod(StreamingContext context)
{
    if (this is ISerializable)
    {
        return;
    }

    _serializedNameType = _nameClaimType;
    _serializedRoleType = _roleClaimType;
    if (_instanceClaims != null && _instanceClaims.Count > 0)
    {
        throw new PlatformNotSupportedException(SR.PlatformNotSupported_Serialization); // BinaryFormatter would be needed
    }
}
```

### Source/destination types

```csharp
System.Security.Claims.ClaimsIdentity
```

### Expected behavior

A fully serialized object with all claims intact.

### Actual behavior

`PlatformNotSupportedException: This instance contains state that cannot be serialized and deserialized on this platform.`

### Steps to reproduce

```csharp
var identity = new ClaimsIdentity();
identity.AddClaim(new Claim("test", "test"));
var serializedIdentity = JsonConvert.SerializeObject(identity);
```

**Comment by JamesNK** [comment]
That looks like the expected behavior of `ClaimsIdentity`. Raise it with the corefx team.

**Comment by vikpai** [comment]
did we get a resolution for this?

**Comment by tb-mtg** [comment]
Was this resolved?

**Comment by EngRajabi** [comment]
This issue has not been resolved

**Comment by ronaldpschutte** [comment]
in .Net 5 this still is a problem

**Comment by saxahan** [comment]
Still a problem

**Comment by Misiu** [comment]
in .Net 6 this is still an issue

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: This instance contains state that cannot be serialized and deserialized on this platform.
   at System.Security.Claims.ClaimsPrincipal.OnSerializingMethod(StreamingContext context)
```

**Comment by Sergey-PrudentDev** [comment]
Annoyingly only solution seems to be is to create DTOs

**Comment by senglory** [comment]
Experiencing the same issue (net 7.0). What's the fix?

**Comment by andreyshiryaev** [comment]
I had the same problem.
And I found that sometimes google does not return **family_name**  and when i removed the code `userClaims.FindFirstValue(ClaimTypes.Surname).?Value` my application starts works fine

**Comment by Geoffrey-FleetCheck** [comment]
net8.0 still a problem
