### ISSUE TITLE
TypeNameHandling works only when $type element is first element of JSON Object.

### ISSUE THREAD

**Issue by piodabro** [JamesNK/Newtonsoft.Json#1716]
### Source/destination types

Object with property that has multiple child types.
It has [JsonProperty(TypeNameHandling = TypeNameHandling.All)] annotation.

### Source/destination JSON

Child type of C# in JSON with $type property.

### Expected behavior

Newtonsoft.Json accepts $type porperty and deserializes to desired type.

### Actual behavior

Newtonsoft.Json accepts $type only if it is the first property of deserialized object.
If $type property is not first, then object is treated as base class (as defined in C# class).

### Steps to reproduce

1. Create some base and child classes. Use base as property of JsonObject.
2. Create new child class in JS and add $type of that child to JSON (but not on first place).
3. Serialize it and send to MVC controller.
4. Decoded child has base class type instead $type defined child.

PS, cant add actual code because NDA.

**Comment by piodabro** [comment]
If $type is on first place it works OK. But its pain to add this in JS instead just write obj["$type"] = "Types.Child, Types"

**Comment by kasparkallas** [comment]
[MetadataPropertyHandling.ReadAhead](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_MetadataPropertyHandling.htm)?

**Comment by piodabro** [comment]
Ok, didn't seen that. But Maybe ill try to make converter that choose the Type by Enum value of decoded object property (objects already have that enum).

**Comment by JamesNK** [comment]
It is already talked about quite clearly in the documentation  - https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#TypeNameHandling

**Comment by Pzixel** [comment]
Written in doc and easy-to-spot is different things. I read this doc before posting my example but I didn't see the sentence about metadata. For example, [this docs](https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html) are very easy to spot that I have to know a newtype pattern. If it would be a plain text as it is I probably wouldn't see it or [this docs](https://doc.rust-lang.org/beta/std/ffi/struct.CStr.html#methods), where note is actually a note, not a terse mentioning in the middle of the text.

Just as suggestion though. If you have people that creates such a issues then documentation _**is**_ unclear even if you think the opposite.
