### ISSUE TITLE
XmlNodeConverter failing on invalid XML element names with ':'

### ISSUE THREAD

**Issue by wasabii** [JamesNK/Newtonsoft.Json#1729]
When converting a JSON object containing properties which are not compatible as XML element names, `XmlNodeConverter` errors: `The ':' character, hexadecimal value 0x3A, cannot be included in a name.'`

Edit:

Upon research, it looks like `XmlConvert.EncodeName` is being used. However, this doesn't consider : characters, and it leaves them untouched so they could potentially be valid prefixes. `XmlConvert.EncodeLocalName` is probably what should be used.

**Comment by JamesNK** [comment]
I've fixed this with a new setting called `EncodeSpecialCharacters`.

```cs
const string initialJson = @"{""Be:fore:After!"":""Value!""}";

XDocument xmlNode = JsonConvert.DeserializeXNode(initialJson, null, false, encodeSpecialCharacters: true);

Assert.AreEqual("<Be_x003A_fore_x003A_After_x0021_>Value!</Be_x003A_fore_x003A_After_x0021_>", xmlNode.ToString());

string json = JsonConvert.SerializeXNode(xmlNode);

Assert.AreEqual(initialJson, json);
```
When it is set to true, all special characters in JSON property names are ignored and are encoded into the XML element name.

**Comment by biryazilim** [comment]
"root" instead of null will prevents another error message...

`XDocument xmlNode = JsonConvert.DeserializeXNode(initialJson, _"Root"_, false, encodeSpecialCharacters: true);`
