### ISSUE TITLE
Feature Request: option for StringEnumConverter to converts Flags to array of string

### ISSUE THREAD

**Issue by YairHalberstadt** [JamesNK/Newtonsoft.Json#1730]
Currently the `StringEnumConverter` converts a flags enum to a string. Since a flag really represents a collection of enums, it might be more appropriate in many cases to represent it as an array of enums.

As such I suggest a property be added to StringEnumConverter 
`public bool ConvertFlagsToArray { get; set; } = false //false by default so not breaking change`

Which when set to true would convert an enum with the flags attribute to an array.

Point to consider:
A Flags enum sometimes has flags which combine a sum of other flags eg:
```
[Flags]
enum Access
{
None =0, Read = 1, Write =2, Full =3
}
```
So how should `Access.Full` be serialised? 
as 
```
[
Read,
Write,
]
```

or as
```
[
Read,
Write,
Full
]
```
?

**Comment by JamesNK** [comment]
I don't want to do that because the converter is designed to read and writes strings, not arrays of strings. Feel free to write your own converter to do this.
