### ISSUE TITLE
Cannot use Microsoft.AspNetCore.SignalR with Microsoft.NET.Sdk.Functions due to NewtonSoft.Json version incompatibilites

### ISSUE THREAD

**Issue by ImageQC** [JamesNK/Newtonsoft.Json#1739]
Please can we have a version of NewtonSoft.Json that can be used for both Microsoft.AspNetCore.SignalR  and Microsoft.NET.Sdk.Functions?

Microsoft.AspNetCore.SignalR 1.0.0-rc1-final has a dependency on Newtonsoft.Json (>= 11.0.2), but Microsoft.NET.Sdk.Functions 1.0.13 -> Newtonsoft.Json (= 10.0.3).

What's in Newtonsoft.Json 11.0.2 that might break Microsoft.NET.Sdk.Functions? If there's nothing then let's push the SDK.Functions team to update the dependency. This issue is causing lots of problems for developers like me.

**Comment by JamesNK** [comment]
> What's in Newtonsoft.Json 11.0.2 that might break Microsoft.NET.Sdk.Functions?

I don't know. I'm not familiar with how they use Newtonsoft.Json.

> If there's nothing then let's push the SDK.Functions team to update the dependency.

They are completely separate from me. There is nothing I can say that will push them to do anything. You should open an issue with them.

**Comment by ImageQC** [comment]
much as I suspected, but thanks anyway. I have raised issues with the respective Microsoft teams so hopefully they with resolve soon. It's a clear case of the left hand not knowing what the right hand is doing ;-)
