### ISSUE TITLE
No JsonConvert.SerializeObject overload method taking both JsonSerializerSettings & JsonConverter's.

### ISSUE THREAD

**Issue by ironhide91** [JamesNK/Newtonsoft.Json#1740]
There is no JsonConvert.SerializeObject overload method taking both JsonSerializerSettings & JsonConverter's as arguments.

Can this be added.

**Comment by JamesNK** [comment]
Converters are on the JsonSerializerSettings

https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_Converters.htm
