### ISSUE TITLE
Wrong targetFramework selected for UWP apps with MinVersion <= 10.0.15063

### ISSUE THREAD

**Issue by martinsuchan** [JamesNK/Newtonsoft.Json#1743]
### Introduction, .NET Standard support in UWP apps

Starting with Windows 10 Fall Creators Update, version 1709 or 10.0.16299, it's possible to use .NET Standard 2.0 APIs in C# UWP apps.
But if my UWP app is targeting previous OS versions as well using the MinVersion parameter, it's not possible to use .NET Standard 2.0 APIs in my app. This is a common scenario for many apps that want to support older Windows 10 versions or Windows 10 Mobile as well. The last SDK version supported on Windows 10 Mobile is 10.0.15063.

### The problem with targetFramework precedence

Newtonsoft.Json package version 10.0.1 added .NETStandard1.3 targetFramework to the list of supported frameworks. This caused one unwanted problem - because how the [NuGet Framework Precedence system](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/framework-precedence?framework=.NETCore5.0&exludedIdentifiers=) works. This .NETStandard1.3 framework is now selected as the best version for UWP apps. This causes need for **referencing NETStandard.Library version 1.6.1, in other words 120+ new or updated dependencies.** This all just to have Newtonsoft.Json in the app.

Newtonsoft.Json package version 11.0.1 added .NETStandard2.0 targetFramework to the list of supported frameworks. If my UWP app is targeting MinVersion 10.0.16299 or newer, Newtonsoft.Json NuGet works fine, because the .NETStandard2.0 version is used. But if I use MinVersion <= 10.0.15063, again .NETStandard1.3 framework is selected and NuGet forces to install NETStandard.Library version 1.6.1 dependency to my app.

This is how it looks when including latest Newtonsoft.Json in my UWP app that is targeting MinVersion 10.0.14393:
![includes](https://user-images.githubusercontent.com/3041397/41706038-0ab1df56-753b-11e8-8aa1-16830ee376cc.PNG)

### Expected behavior

**There should be no need to install NETStandard.Library version 1.6.1 if I just want to use Newtonsoft.Json in my UWP app.** This could be easily solved by adding another targetFramework="UAP10.0" or ".NETCore5.0". This target framework id has better precedence than .NETStandard1.3 in UWP apps.

If you check the microsoft.netcore.universalwindowsplatform.nuspec file, you can see how Microsoft solved this conundrum:

```
<dependencies>
  <group targetFramework=".NETCore5.0">
	<!-- standard UWP NuGet references -->
	<dependency id="Microsoft.Net.Native.Compiler" version="1.7.3" />
	<dependency id="Microsoft.NETCore" version="5.0.2" />
	<dependency id="Microsoft.NETCore.Portable.Compatibility" version="1.0.2" />
	<dependency id="Microsoft.NETCore.Runtime.CoreCLR" version="1.0.3" />
	<dependency id="Microsoft.NETCore.Targets" version="1.0.2" />
	<dependency id="Microsoft.Win32.Primitives" version="4.0.1" />
	<dependency id="System.Collections.NonGeneric" version="4.0.1" />
	<dependency id="System.Collections.Specialized" version="4.0.1" />
	<dependency id="System.ComponentModel.EventBasedAsync" version="4.0.11" />
	<dependency id="System.Data.Common" version="4.1.0" />
	<dependency id="System.Diagnostics.Contracts" version="4.0.1" />
	<dependency id="System.Diagnostics.StackTrace" version="4.0.2" />
	<dependency id="System.IO.IsolatedStorage" version="4.0.1" />
	<dependency id="System.Net.Http.Rtc" version="4.0.1" />
	<dependency id="System.Net.NameResolution" version="4.0.0" />
	<dependency id="System.Net.Requests" version="4.0.11" />
	<dependency id="System.Net.Sockets" version="4.1.0" />
	<dependency id="System.Net.WebHeaderCollection" version="4.0.1" />
	<dependency id="System.Net.WebSockets" version="4.0.0" />
	<dependency id="System.Net.WebSockets.Client" version="4.0.2" />
	<dependency id="System.Numerics.Vectors.WindowsRuntime" version="4.0.1" />
	<dependency id="System.Reflection.Context" version="4.0.1" />
	<dependency id="System.Runtime.InteropServices.WindowsRuntime" version="4.0.1" />
	<dependency id="System.Runtime.Serialization.Json" version="4.0.3" />
	<dependency id="System.Runtime.Serialization.Primitives" version="4.1.1" />
	<dependency id="System.Runtime.Serialization.Xml" version="4.1.2" />
	<dependency id="System.Runtime.WindowsRuntime" version="4.0.11" />
	<dependency id="System.Runtime.WindowsRuntime.UI.Xaml" version="4.0.1" />
	<dependency id="System.ServiceModel.Duplex" version="4.0.2" />
	<dependency id="System.ServiceModel.Http" version="4.1.1" />
	<dependency id="System.ServiceModel.NetTcp" version="4.1.1" />
	<dependency id="System.ServiceModel.Primitives" version="4.1.1" />
	<dependency id="System.ServiceModel.Security" version="4.0.2" />
	<dependency id="System.Text.Encoding.CodePages" version="4.0.1" />
	<dependency id="System.Threading.Overlapped" version="4.0.1" />
	<dependency id="System.Xml.XmlDocument" version="4.0.1" />
	<dependency id="System.Xml.XmlSerializer" version="4.0.11" />
  </group>
  <group targetFramework="UAP10.0.15138">
	<!-- .NET Standard 2.0 is used for MinVersion higher than 15138 -->
	<dependency id="Microsoft.Net.Native.Compiler" version="2.1.8" />
	<dependency id="Microsoft.Net.UWPCoreRuntimeSdk" version="2.1.2" />
	<dependency id="Microsoft.NETCore.Platforms" version="2.0.0" />
	<dependency id="NETStandard.Library" version="2.0.2" />
  </group>
</dependencies>
```

Note this ticket is a follow up of #1291 and also possible fix for dependency warnings in #1702.

**Comment by JamesNK** [comment]
I don't want to create platform specific TFMs, there is a lot of work involved in maintaining and testing them.
