### ISSUE TITLE
Value is Null After Casting With "as" Operator

### ISSUE THREAD

**Issue by mdavisJr** [JamesNK/Newtonsoft.Json#1748]
```
dynamic dynamicObj = new ExpandoObject();
dynamicObj.Test = "TestText";

string var1 = dynamicObj.Test as string; 
string var2 = (string)dynamicObj.Test;    

dynamicObj = JsonConvert.DeserializeObject<dynamic>("{'Test' : 'TestText'}");

string var3 = dynamicObj.Test as string;  
string var4 = (string)dynamicObj.Test; 

Console.WriteLine(var1);
Console.WriteLine(var2);
Console.WriteLine(var3);
Console.WriteLine(var4);
```
#### Prints
TestText
TestText
(null) 
TestText

 
#### I expected var3 to have a value of "TestText" but it is actually null.  Why does var1, var2, and var4 have the correct value of "TestText" but var3 is null?

**Version:** 11.0.2
**C# Version:** netcoreapp2.0

**Comment by mdavisJr** [comment]
Any thoughts on this?  This seems like a bug to me because casting with "(string)" works but casting with "as string" doesn't work in the example above for var3 and var4.  If casting as "(string)" works, I would expect "as string" to work.

**Comment by JamesNK** [comment]
It is because the underlying type for dynamic is JToken, and JToken overrides the cast operator that is used here:

```
string var4 = (string)dynamicObj.Test; 
```

Meanwhile `as` returns null because JToken isn't a string.
