### ISSUE TITLE
JToken.DeepEquals(string, string) is order-dependent for JSON fields

### ISSUE THREAD

**Issue by ChrisMaddock** [JamesNK/Newtonsoft.Json#1750]
JToken.DeepEquals(string, string) is order-dependent for JSON fields. This is inconsistent with JToken.DeepEquals(JToken, JToken) - I would expect both overloads to behave in the same way. 

Running on netcoreapp2.0.

### Expected behavior

JToken.DeepEquals(string, string) to return true when fields are in different orders.

### Actual behavior

JToken.DeepEquals(string, string) returns false

### Steps to reproduce

See following test code. I would expect both statements to print true.

```csharp
public static void Example()
{
    JObject o1 = new JObject
    {
        { "Integer", 12345 },
        { "String", "A string" }
    };

    JObject o2 = new JObject
    {
        { "String", "A string" },
        { "Integer", 12345 }
    };

    Console.WriteLine(JToken.DeepEquals(o1, o2));
    // TRUE - AS EXPECTED

    string s1 = JsonConvert.SerializeObject(o1);
    string s2 = JsonConvert.SerializeObject(o2);

    Console.WriteLine(JToken.DeepEquals(s1, s2));
    // FALSE - EXPECT TRUE
}
```

### Live Test
https://dotnetfiddle.net/AcMSLa

Thanks for a great tool - and apologies if I've misunderstood the intention of the API here!

**Comment by ChrisMaddock** [comment]
Ahhh, I wondered if there was something like that going on.

That's a little confusing - but I'm not sure I can come up with anyway to 'improve' this, without breaking backwards compatibility.

I'll close. Thanks for the insight @dbc2 :+1:

**Comment by CedricPump** [comment]
```
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
					
public class Program
{
	public static void Main()
	{
		var o = JToken.DeepEquals(JsonConvert.DeserializeObject<JToken>("{'a': 'a', 'b': 'b'}"),JsonConvert.DeserializeObject<JToken>("{'b': 'b', 'a': 'a'}"));
		Console.WriteLine(o);
	}
}
```
workes for me
