### ISSUE TITLE
PopulateObject not populating base class properties

### ISSUE THREAD

**Issue by grahamehorner** [JamesNK/Newtonsoft.Json#1751]
1. create a base class with properties
2. decorate properties with JsonPropery attribute
3. create a second class that inherits from base class
4. add some properties with JsonProperty attribute
5. create instance of the class created in step 4.
6. call populate object using that instance

*: base class properties not populated

**Comment by TylerBrinkley** [comment]
I'm unable to reproduce this. Please provide the classes and json as the issue template prompts.
