### ISSUE TITLE
JSON - deserialization of empty array returns null

### ISSUE THREAD

**Issue by raV720** [JamesNK/Newtonsoft.Json#1752]
In the following situation the deserializer returns the same result:

```
var settings = new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.Auto };

var s0 = JsonConvert.SerializeObject(new Test(), settings);
var s1 = JsonConvert.SerializeObject(new Test() { Obj = new byte[] { } }, settings);

var t0 = JsonConvert.DeserializeObject<Test>(s0, settings);
var t1 = JsonConvert.DeserializeObject<Test>(s1, settings);


class Test
{
    public object Obj { get; set; }
}

```

s0 = {"Obj":null}
s1 = {"Obj":{"$type":"System.Byte[], System.Private.CoreLib","$value":""}}
The Obj property of t0 and t1 is null after deserialization while in my opinion t1 should contain empty array.

**Comment by TylerBrinkley** [comment]
This looks to be an issue with the handling of deserializing byte arrays as empty base 64 strings.
