### ISSUE TITLE
UnixDateTimeConverter feature JsonToken.Date

### ISSUE THREAD

**Issue by marioleed** [JamesNK/Newtonsoft.Json#1758]
Would it be OK if `UnixDateTimeConverter `returned the DateTime object on `ReadJson `if the `reader.TokenType` is `JsonToken.Date`? Instead of throwing an exception?

Or should it be handled in some other way?

**Comment by JamesNK** [comment]
It is intended to convert a Unix timestamp integer to a date. Allowing a date string wouldn't be expected.

You could copy the source code and customize your own converter.
