### ISSUE TITLE
Wrong type of a property on an object makes DeserializeObject hang endlessly

### ISSUE THREAD

**Issue by nuc134r** [JamesNK/Newtonsoft.Json#1766]
I'm using Newtonsoft.Json NuGet package version 11.0.2.

### Source/destination types

Here are `Audio` object and `Collection` wrapper class which I use to meet the format of API response. 

Notice that the `Url` field type is `int` which is my own mistake but it causes `DeserializeObject` to hang.

```csharp
[JsonObject(MemberSerialization.OptIn)]
public class Audio
{
	[JsonProperty]
	public string Artist { get; set; }

	[JsonProperty]
	public string Title { get; set; }

	[JsonProperty]
	public int Duration { get; set; }

	[JsonProperty]
	public int Url { get; set; }

	public string DurationString
	{
		get
		{
			var minutes = Duration / 60;
			var seconds = Duration - minutes * 60;
			return $"{minutes}:{seconds}";
		}
	}
}

public class Collection<T>
{
	public CollectionRoot<T> Response;

	public class CollectionRoot<TT>
	{
		public int Count;
		public List<TT> Items;
	}
}
```

### Source/destination JSON
The `url` field is obviously a string, not an integer.
```javascript
{
  "response": {
    "count": 1,
    "items": [
      {
        "id": 456240676,
        "owner_id": 52672892,
        "artist": "The Chemical Brothers",
        "title": "Do It Again",
        "duration": 333,
        "date": 1530422624,
        "url": "https://cs1-71v4.vkuseraudio.net/p24/0e0bf10c8716f8.mp3",
        "is_hq": true
      }
    ]
  }
}
```

### Expected behavior

Deserialize the data properly and leave `Url` field on `Audio` object with it's default value (0).

### Actual behavior

`DeserializeObject` function starts executing and doesn't stop. It never hits the second line in a code below.

If this code was running in UI thread I guess it would hang the whole application.

### Steps to reproduce

```csharp
var obj = JsonConvert.DeserializeObject<Collection<Audio>>(response);
return obj.Response.Items;
```

**Comment by JamesNK** [comment]
Hi

I ran your sample and this exception was thrown:

```
Newtonsoft.Json.JsonReaderException: 'Could not convert string to integer: https://cs1-71v4.vkuseraudio.net/p24/0e0bf10c8716f8.mp3. Path 'response.items[0].url', line 12, position 72.'
```
