### ISSUE TITLE
StringEnumConverter fails to process nullable enum

### ISSUE THREAD

**Issue by Faithfinder** [JamesNK/Newtonsoft.Json#1774]
### Source/destination types

```csharp
[JsonConverter(typeof(StringEnumConverter))]
public FlagColor? Flag_color { get; set; }
```
FlagColor is an `enum`

### Expected behavior

When Flag_color set to `null`, resulting field in Json is set to `null`

### Actual behavior
Sorry about Russian. Even with my Studio set to English errors are still in Russian for some reason.
> в System.Enum.ToObject(Type enumType, Object value)
>    в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
> Result Message:	
> System.AggregateException : Произошла одна или несколько ошибок.
>   ----> Newtonsoft.Json.JsonSerializationException : Error converting value {null} to type 'YNABConnector.YNABObjectModel.FlagColor'. Path 'data.transaction.flag_color', line 1, position 172.

I've seen something similar in #708, if that helps

**Comment by Faithfinder** [comment]
My bad. Everything works fine

**Comment by ironman1964** [comment]
what did you change to let it work ??
