### ISSUE TITLE
Customize DateTimeOffset deserialization with unspecified time zone

### ISSUE THREAD

**Issue by dermeister0** [JamesNK/Newtonsoft.Json#1775]
### Source/destination types

```csharp
    internal class Data
    {
        public DateTimeOffset Time { get; set; }
    }
```

### Source/destination JSON

```javascript
{ "Time": "2018-07-23T05:00:00.000" }
```

### Expected behavior

Need a possibility to handle unspecified time zone.

### Actual behavior

`TryParseDateTimeOffsetIso` assumes that unspecified time zone means local time.

----

`TryParseDateTimeOffsetIso` has following logic:

```csharp
            DateTimeParser dateTimeParser = new DateTimeParser();
            if (!dateTimeParser.Parse(text.Chars, text.StartIndex, text.Length))
            {
                dt = default(DateTimeOffset);
                return false;
            }

            DateTime d = CreateDateTime(dateTimeParser);

            TimeSpan offset;

            switch (dateTimeParser.Zone)
            {
                case ParserTimeZone.Utc:
                    offset = new TimeSpan(0L);
                    break;
                case ParserTimeZone.LocalWestOfUtc:
                    offset = new TimeSpan(-dateTimeParser.ZoneHour, -dateTimeParser.ZoneMinute, 0);
                    break;
                case ParserTimeZone.LocalEastOfUtc:
                    offset = new TimeSpan(dateTimeParser.ZoneHour, dateTimeParser.ZoneMinute, 0);
                    break;
                default:
                    offset = TimeZoneInfo.Local.GetUtcOffset(d);
                    break;
            }
```

I would like to handle the `default` case differently (use UTC time zone).

There are possible ways to allow it:

- Introduce a new setting.
- Reuse DateTimeZoneHandling setting.
- Allow to use custom class/struct instead of DateTimeParser.

**Comment by dermeister0** [comment]
Actually, `ISO 8601` describes that empty time zone means local time.

> The zone designator is empty if use is made of local time in accordance with 4.2.2.2 through 4.2.2.4, it is the UTC designator [Z] if use is made of UTC of day in accordance with 4.2.4 and it is the difference-component if use is made

**Comment by EricGriffith** [comment]
Please consider reopening this.  While the standard may specify it is local time, that's not useful if the JSON document is moved into a different time zone and the data in it needs to be interpreted correctly.  With the current implementation, there's no option but to preprocess the data before deserializing because there's no way, afterwards, to know that the timezone was not specified.
