### ISSUE TITLE
Nullable DateTime Value throwing error

### ISSUE THREAD

**Issue by ramkumarxpo** [JamesNK/Newtonsoft.Json#1778]
### Source/destination types

Nullable DateTime datatype of C#

### Source/destination JSON

"enddate":-1

### Expected behavior

null value is not allowed.

### Actual behavior

Getting error as 

"An unhandled exception occurred while processing the request.

InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.DateTime]'.
Newtonsoft.Json.JsonTextReader.ReadAsDateTime()"

### Steps to reproduce

I am having C# class with one data member as below 

public DateTime? EndDate { get; set; }

Whenever i am trying to invoke with a below value from postman i am getting the error message

{
"enddate":-1
}

**Comment by JamesNK** [comment]
A number cannot be converter to a `DateTime`. I've improved the error message.
