### ISSUE TITLE
Solution not opening in VisualStudio 2015

### ISSUE THREAD

**Issue by khannaprashant** [JamesNK/Newtonsoft.Json#1779]
I downloaded the source code and was opening in visual studio 2015, but is is giving the issue "The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format"

kindly help i need to build it for 64bit

**Comment by NathanMCarlson** [comment]
You can't open and build a VS 2017 project in 2015- there are unsupported targets in there. I thought it might build in VS Code (dotnet CLI) but that doesn't seem to work either. It builds fine in VS 2017 Community Edition though, so depending on what you're doing, you could try that.

**Comment by JamesNK** [comment]
Use VS2017
