### ISSUE TITLE
JsonConvert.DeserializeObject function throws errors when pass the obsolete enum properties

### ISSUE THREAD

**Issue by manikandan05** [JamesNK/Newtonsoft.Json#1788]
I want to mark my existing Enum property as obsolete and add the new one for same functionality. So, two enums (new one and obsolete marked one) available in my project.

While using the jsonconvert.deserializeobject function to serialize this enums value throws the below errors **only from the Newtonsoft 11.0 above version**. 

`InvalidOperationException: Enum name 'stringedit' already exists on enum 'EditingType'.
Newtonsoft.Json.Utilities.EnumUtils.InitializeValuesAndNames(Type enumType)
JsonSerializationException: Error converting value "boolean" to type 'Student.Models.EditingType'. Path 'columns[0].editType', line 1, position 3997.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)`

If there is any changes need to do in my project or if there is any plan to resolve this new error from serialization function.

Regards,
Manikandan

**Comment by JamesNK** [comment]
Can you add the source code for the enum here?

**Comment by manikandan05** [comment]
Hi @JamesNK ,

Please find the code block for my new and obsolete enum property declarations.

`[DataContract]
    public enum EditingType
    {
        [Obsolete("String property has been deprecated. Use StringEdit property instead")]
        [EnumMember(Value = "stringedit")]
        String,
        [EnumMember(Value = "stringedit")]
        StringEdit
    }`

Regards,
Manikandan

**Comment by manikandan05** [comment]
Hi @JamesNK ,

I have attached my sample project in GitHub for showcase the issue.

https://github.com/manikandan05/NewtonsoftIssue/tree/master/WebApplication3

My code block is mentioned below. Any possible to overcome this issue?

`[DataContract]

    public enum EditingType

    {

        [Obsolete("String property has been deprecated. Use StringEdit property instead")]

        [EnumMember(Value = "stringedit")]

        String,

        [EnumMember(Value = "stringedit")]

        StringEdit

    }

    public class JsonPropertyAttribute : Attribute

    {
        public JsonPropertyAttribute(string argName)
        {
            PropertyName = argName;
        }

        public string PropertyName { get; set; }
    }

    public class JsonConverterAttribute : Attribute
    {
        public Type ConverterType
        {
            get; set;
        }
        public string ValueType
        {
            get; set;
        }
        public JsonConverterAttribute(Type type, string valueType)
        {
            this.ConverterType = type;
            this.ValueType = valueType;
        }
        public JsonConverterAttribute(Type type)
        {
            this.ConverterType = type;

        }

    }
    public abstract class Converter
    {
        protected internal abstract IDictionary<string, object> BuildJsonDictionary(object value);

        public abstract string SerializeToJson(object inputObject);
    }
    public class StringEnumConverter : Converter
    {
        protected internal override IDictionary<string, object> BuildJsonDictionary(object value)
        {

            IDictionary<string, object> jsonDictionary = new Dictionary<string, object>();
            Type objectType = value.GetType();

            FieldInfo member = objectType.GetField(value.ToString(), BindingFlags.Static | BindingFlags.Public);

            var attrList = member.GetCustomAttributes(typeof(EnumMemberAttribute), true);
            var enumMember = attrList.OfType<EnumMemberAttribute>().FirstOrDefault();

            string val = enumMember != null ? enumMember.Value : value.ToString();

            jsonDictionary.Add(value.GetType().Name, val);

            return jsonDictionary;
        }


        public override string SerializeToJson(object inputObject)
        {
            var attrList = inputObject.GetType().GetCustomAttributes(false);
            var listAttr = attrList.ToList();
            FlagsAttribute flagAttr = attrList.Count() != 0 ? (FlagsAttribute)listAttr.Find(item => item.GetType() == typeof(FlagsAttribute)) : null;
            bool flag = (flagAttr != null) ? true : false;
            if (flag)
            {
                int value = (int)inputObject;
                return value.ToString();
            }
            else
            {
                IDictionary<string, object> enumDictionary = BuildJsonDictionary(inputObject);
                object enumValue = enumDictionary.First().Value;
                string enumstring = "\"" + enumValue.ToString() + "\"";
                return enumstring;
            }
        }
    }

    [Serializable]
    public class TestClass
    {
        private EditingType _editingType = EditingType.StringEdit;

        [JsonProperty("editType")]
        [DefaultValue(EditingType.StringEdit)]
        [JsonConverter(typeof(StringEnumConverter))]
        public EditingType EditType
        {
            get { return _editingType; }
            set { _editingType = value; }
        }
    }
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
           // This function will throws the error
            JsonConvert.DeserializeObject("{\"editType\":\"string\"}", typeof(TestClass));
            return View();
        }
   }
`

**Comment by JamesNK** [comment]
I looked into this and it is expected behavior. Json.NET now always cares about EnumMember and you have duplicate values.

Implement a JsonConverter if you want to customize its serialization. I don't know what you're trying to do with the conversion classes in your sample but Json.NET doesn't care about them.
