### ISSUE TITLE
Trailing zeros cut from serialized date time offset

### ISSUE THREAD

**Issue by borrrden** [JamesNK/Newtonsoft.Json#1797]
### Source/destination types

```csharp
new DateTimeOffset(15000, new TimeSpan(0));
new DateTimeOffset(15, new TimeSpan(0));
```

### Source/destination JSON

```javascript
"0001-01-01T00:00:00.0015+00:00"
"0001-01-01T00:00:00.0000015+00:00"
```

### Expected behavior

15,000 ticks were specified in the first type, so I'd expect the JSON to be "0001-01-01T00:00:00.0015000+00:00"

### Actual behavior

"0001-01-01T00:00:00.0015+00:00" was the resulting JSON, which is identical to the second date time with 15 ticks instead of 15,000.

### Steps to reproduce

```csharp
var dto1 = new DateTimeOffset(15000, new TimeSpan(0));
var dto2 = new DateTimeOffset(15, new TimeSpan(0));
var serialized1 = JsonConvert.SerializeObject(dto1); // Incorrect?
var serialized2 = JsonConvert.SerializeObject(dto2);
```

**Comment by JamesNK** [comment]
The default date format string doesn't serialize trailing zeros because it is unnecessary. You can change it like is shown here: https://www.newtonsoft.com/json/help/html/SerializeDateFormatString.htm
