### ISSUE TITLE
Unexpected assemblies loading when deserialize Type class from string

### ISSUE THREAD

**Issue by OlegUfaev** [JamesNK/Newtonsoft.Json#1809]
### Source/destination types

Source: String with some type full name
Destination: System.Type class

### Source JSON

```javascript
"System.Windows.Forms.Button, System.Windows.Forms, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089"
```

### Expected behavior
JsonSerializationException when assembly not loaded into process

### Actual behavior
System.Windows.Forms assembly is loaded into process and also linked libraries

### Steps to reproduce

Create new Console Application project
![project](https://user-images.githubusercontent.com/1725876/44798128-6cf38c00-abb9-11e8-98a8-f6d7abf7248c.png)

Copy, paste and run this code:
```csharp
using System;
using Newtonsoft.Json;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string source = "\"System.Windows.Forms.Button, System.Windows.Forms, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089\"";

            Console.WriteLine("Assemblies BEFORE deserialization:");
            PrintAssemblies();

            Type destination = JsonConvert.DeserializeObject<Type>(source);

            Console.WriteLine("Assemblies AFTER deserialization:");
            PrintAssemblies();
        }

        public static void PrintAssemblies()
        {
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            foreach (var assembly in assemblies)
            {
                Console.WriteLine(assembly.GetName());
            }

            Console.WriteLine();
        }
    }
}
```
Output:
![output](https://user-images.githubusercontent.com/1725876/44798147-7bda3e80-abb9-11e8-805f-cd050faa4aba.png)

**Comment by OlegUfaev** [comment]
I believe this is a potential security threat, while there is no way to prohibit such behavior, at least I have not found a way to do it.

**Comment by JamesNK** [comment]
You are choosing to deserialize to `Type` in your application. If you don't want an assembly is loaded then take a string and then validate whether you want to convert it to a `Type`.

**Comment by OlegUfaev** [comment]
@JamesNK, thank for the reply.
I agree with you and I blame myself for using the type, BUT :)

I also use the TypeNameHandling.Auto mechanism and I implement the interface ISerializationBinder for type validation. In this way, I can control which types of objects can be created during deserialization (and which assemblies are loaded). I believe that this mechanism can also be used for deserializing a type, well, or at least something similar.

Maybe it will be convenient to do type validation through the implementation of the interface ISerializationBinder or something similar?

**Comment by JamesNK** [comment]
If you care you could write a JsonConverter that called the binder

**Comment by OlegUfaev** [comment]
@JamesNK, thanks for the help.
The `JsonConverter` custom implementation for `Type`, that called the binder, works very well and solves my problem.
