### ISSUE TITLE
Implicit conversion from string for JToken should Parse()?

### ISSUE THREAD

**Issue by arrkaye** [JamesNK/Newtonsoft.Json#1810]
More of a question.

I was recently caught out by this behaviour where a method was expecting a JToken but accepted a string due to the implicit operator.

I would suggest removing the implicit operators to prevent confusion. What do you think?

**Comment by JamesNK** [comment]
The implicit conversions are used heavily in many situations, e.g.

```cs
JObject o = new JObject
{
   ["name"] = "James"
}
```
The string here is automatically converted to a JValue.

**Comment by vkradio** [comment]
I just spent an hour just to figure out a piece of my C# code became a non-refactorable JavaScript because of that. Wow......
(Just a feedback. Your lib is great nonetheless.)
