### ISSUE TITLE
JsonTextWriter doesn't dispose TextWriter.

### ISSUE THREAD

**Issue by samrueby** [JamesNK/Newtonsoft.Json#1812]
Maybe there's a good reason for this, but I couldn't find a clear answer. I had to view the source code to see that JsonTextWriter doesn't dispose the TextWriter given to it in its constructor.

### Expected behavior

This was confusing to me because some .NET Framework types, such as StreamWriter, automatically dispose of the underlying Stream. JsonTextWriter is given an instance of StreamWriter, so I expected it to dispose the the StreamWriter, and thus the underlying Stream. 

### Actual behavior

JsonTextWriter does not dispose the SreamWriter.

### Steps to reproduce

Because of this, using StreamWriter with JsonTextWriter must currently always look like this:
    using( var streamWriter = new StreamWriter( File.Open( file ) ) ) {
        using( var writer = new JsonTextWriter( streamWriter ) ) {
    		jobject.WriteTo(writer);
    	}
    }	

Perhaps even this was intended, there could be a comment on the JsonTextWriter indicating that you must dispose your own TextWriter.

**Comment by Dispersia** [comment]
This is how IDisposable works, I'm confused. StreamWriter will not dispose unless Dispose() or Closed() is called on it. using() is just a wrapper for try { } finally { writer.Close(); }. JsonTextWriter mimics this behavior [here](https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/JsonTextWriter.cs#L190).

 You can test this yourself with [this](https://gist.github.com/Dispersia/75b0c011aea4b82428b3fa819cd7f166). You don't have to wrap the streamwriter to close it, the Dispose() in JsonTextWriter will chain down. But regardless, when working with disposable objects, your code in Steps to reproduce is the usual way you should write it anyway.

**Comment by JamesNK** [comment]
JsonTextWriter does close its inner TextWriter by default. There is property called CloseOutput to disable it.
