### ISSUE TITLE
Formatting of JavaScriptDateTimeConverter is incorrect

### ISSUE THREAD

**Issue by RickStrahl** [JamesNK/Newtonsoft.Json#1814]
When using formatted output for JSON generated with the JavaScriptDateTimeConverter results in extra spacing that's undesirable. 

Use case: Used for code generating a JavaScript object block and using the JavaScriptDateTimeConverter so that the code can execute as JavaScript.

### Source/destination types

```csharp
[TestMethod]
public void DateFormattingProblem()
{
    var value = new
    {
        name = "Rick",
        entered = DateTime.UtcNow
    };
    var result = JsonConvert.SerializeObject(value, Formatting.Indented, new JavaScriptDateTimeConverter());

    Console.WriteLine(result);
}
```
### Source/destination JSON

```javascript
{
  "name": "Rick",
  "entered": new Date(
    1535917951180
  )
}
```

### Expected behavior
Date should be formatting without breaking the parenthesis onto separate lines.

```javascript
{
  "name": "Rick",
  "entered": new Date(1535917951180)
}
```

**Comment by JamesNK** [comment]
That's the built-in way JsonTextWriter will write constructors. If it really bothers you you could copy+paste the source code for JavaScriptDateConverter and try setting Formatting = Formatting.None before writing the date and resetting it back afterwards. I haven't tried it but it might give you what you want.
