### ISSUE TITLE
No definition for 'SerializeXNode' in v11.0.2?

### ISSUE THREAD

**Issue by chrisban** [JamesNK/Newtonsoft.Json#1815]
### Source/destination types
Attempting to serialize XNodes > JSON. 

Json.NET version: 11.0.2
.NET version: 4.6.1

### Expected behavior
Build successfully using the [JsonConvert.SerializeXNode method](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_SerializeXNode.htm).

### Actual behavior
Using newest version (11.0.2), the below snippet causes the following build error:
_Error CS0117: 'JsonConvert' does not contain a definition for 'SerializeXNode'_

Reverting to Json.NET version 11.0.1 fixes this issue. 
Alternatively, Visual Studio also recommends using [SerializeXmlNode](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_SerializeXmlNode.htm) instead.

### Steps to reproduce
```csharp
IEnumerable<XElement> desc = ...
...
foreach (XElement element in desc) {
     ...
     JsonConvert.SerializeXNode(element);  // <= build error
}
```

I skimmed through the changelog between releases but didn't see anything specific to SerializeXNode being removed/deprecated. Is this an intentional change?

**Comment by JamesNK** [comment]
SerializeXNode is still there. Do you know what target of Newtonsoft.Json you're using? SerializeXNode isn't in all of them, eg it is missing from net20 target.

**Comment by chrisban** [comment]
@JamesNK Thanks for the quick response. The target framework is 'net461'

packages.config:
` 
<package id="Newtonsoft.Json" version="11.0.2" targetFramework="net461" />
`

.csproj:
`
<Reference Include="Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>packages\Newtonsoft.Json.11.0.2\lib\net45\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
</Reference>
`


To be clear, 11.0.1 works fine, just updating to 11.0.2 causes the error (via NuGet).

**Comment by JamesNK** [comment]
I don't know. It is still there 🤷‍♂️

**Comment by chrisban** [comment]
Weird, must be something with my dev environment. Thanks anyway!
