### ISSUE TITLE
Line info missing for JsonSerializationException

### ISSUE THREAD

**Issue by live1206** [JamesNK/Newtonsoft.Json#1816]
When `JsonSerializationException` is thrown, there is line info within the error message, but not in the exception itself. So we need to parse the error message to get the line info.

If we take a look at `JsonReaderException`, line info is presented in the error message, and also exposed in the exception properties.

Much appreciated if we can have the similar implementation of `JsonReaderException` for `JsonSerializationException`.

**Comment by JamesNK** [comment]
Good suggestion. Done
