### ISSUE TITLE
Allow inheritance from JsonPropertyAttribute

### ISSUE THREAD

**Issue by WillGunn** [JamesNK/Newtonsoft.Json#1821]
https://github.com/JamesNK/Newtonsoft.Json/blob/18fef752f3ab05692b7af47aa23d875f7783449b/Src/Newtonsoft.Json/JsonPropertyAttribute.cs#L35

We were looking to create a custom property that setup some well used (but not default) values in the project I am working on, but ran into the issue that JsonPropertyAttribute is sealed.  If there is a good workaround for this that I haven't been able to find, please let me know.  Otherwise, is there a good reason why we shouldn't unseal this class?

**Comment by TylerBrinkley** [comment]
For what purpose do you need this to be unsealed? Can you give an example of what you're trying to do? In general it's recommended to seal attribute classes.

**Comment by WillGunn** [comment]
Sure. We have similar properties across objects that we want to not be serialized if null, but the vast majority of our properties we do want serialized if null. So the default fits the majority case, but for the minority it would be useful to create a strongly typed attribute that encapsulates [JsonProperty(NullValueHandling=NullValueHandling.Ignore)] so it’s easily reusable and easy to find using apiexplorer (which is used by Swashbuckle). That way Newtonsoft can still find the custom attribute because it inherits from a type it’s looking for, and it’s easy to find the null ignore properties from our documentation filters.

**Comment by Deni35** [comment]
I wanted to encapsulate the `Newtonsoft.Json` in a separate project. But I ran into this problem ((
And unfortunately `.NET` doesn't allow one attribute to provide other attributes.
I hope I can achieve this with your contract resolver.

**Comment by argelj289** [comment]
I need this to be overriden so that I dont have to call serialization again because that would be additional process that will stress the server. I want to control the serialization and deserialization only to specific objects where I applied JsonPropertyAttribute in each property

**Comment by argelj289** [comment]
I dont like the suggested ContractResolver as I mentioned before, it will be additional stress to the server. I hope you could provide a kind of setting in JsonPropertyAttribute when set, it will display the property name of the class instead of the one set in JsonPropertyAttribute.PropertyName
