### ISSUE TITLE
Passing "[]" to JObject.Parse Throws Exception

### ISSUE THREAD

**Issue by ccroy** [JamesNK/Newtonsoft.Json#1824]
### Source/destination types

```csharp
[]
```

### Source/destination JSON

```javascript
[]
```

### Expected behavior

Calling
```csharp
JObject.Parse("[]");
```
returns a JObject representing a JSON array (i.e. []).

### Actual behavior

Calling JObject.Parse("[]") throws the following exception:
```csharp
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.

   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JObject.Parse(String json)

   at TileScraperForm.TileScraperForm.<TileScraperForm_DragDrop>d__13.MoveNext() in D:\SVN\software\TileScraper\TileScraper GUI\trunk\TileScraperForm.cs:line 123
```
### Steps to reproduce
Simply make the following call somewhere in code:
```csharp
JObject.Parse("[]");
```

### Additional info

In contrast to the above, performing this call works:
```csharp
JObject.Parse("{}");
```
My interpretation of https://tools.ietf.org/html/rfc8259 is that [] as a root element should be considered valid JSON.

Though the example I've given to recreate the issue is trivial, I utilize complex JSON where the root is an array and would find it unnecessary/burdensome to have to wrap it inside an object (not just complaining for the sake of complaining).

Found in Newtonsoft.Json v11.0.2.

Thanks!

**Comment by TylerBrinkley** [comment]
If you're expecting an array then use `JArray.Parse`. If you're expecting any arbitrary json use `JToken.Parse`.

**Comment by ccroy** [comment]
My bad, thanks! I switched to using JToken.Parse and it works as expected. Closing now.

**Comment by omunoz90** [comment]
JArray.Parse para los objetos con formato [{},{},{}]
