### ISSUE TITLE
Serialized Array is wrapped in $values when TypeNameHandling.Auto while List is not

### ISSUE THREAD

**Issue by HampusLilja** [JamesNK/Newtonsoft.Json#1832]
### Source/destination types

```csharp

    public class SomeDataObject
    {
        public IList<string> ListArray => new[]
        {
            "one", "two", "three"
        };

        public IList<string> ListList => new List<string>()
        {
            "four", "five", "six"
        };
    }
```

### Source/destination JSON

```javascript
{
"ListArray":{"$type":"System.String[], System.Private.CoreLib","$values":["one","two","three"]},
"ListList":["four","five","six"]
}
```

### Expected behavior

ListArray should be serialized as ListList i.e. 
```javascript
{
"ListArray":["one","two","three"],
"ListList":["four","five","six"]
}
```

### Actual behavior

When using TypeNameHandling.Auto and returning an array instead of a list the serialized array is wrapped in a $type-$values object. I would expect that serializing an Array would look the same as a serialized List.

### Steps to reproduce

```csharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace jsonSerializer
{
    class Program
    {
        static void Main(string[] args)
        {
            var data = new SomeDataObject();
            var settings = new JsonSerializerSettings();
            settings.TypeNameHandling = TypeNameHandling.Auto;
            var json = JsonConvert.SerializeObject(data, settings);
            Console.ReadLine();

        }
    }

    public class SomeDataObject
    {
        public IList<string> ListArray => new[]
        {
            "one", "two", "three"
        };

        public IList<string> ListList => new List<string>()
        {
            "four", "five", "six"
        };
    }
}
```

**Comment by devilirium** [comment]
I have been thinking about this for a while now and I'm beginning to think that both of these properties should have a corresponding `$type` and `$values` in the serialized JSON.

The [documentation](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm) states the following for `TypeNameHandling.Auto`:
> Include the .NET type name when the type of the object being serialized is not the same as its declared type. Note that this doesn't include the root serialized object by default. To include the root object's type name in JSON you must specify a root type object with SerializeObject(Object, Type, JsonSerializerSettings) or Serialize(JsonWriter, Object, Type).

If the library adheres to that description then it means that:
```csharp
(typeof(IList<string>) == typeof(List<string>)) == false
```

and that:
```csharp
(typeof(IList<string>) == (new [] { "a", "b", "c"}).GetType()) == false
```

Thus both of them should have their corresponding types written down. Actually, if the declaring type is an _interface_ or a _generic interface_, it should always output the `$type` property to know what implementation should be chosen once deserialization starts (unless null).

I'm not sure why it's not like that, so I'll let others chime in as I just started out with reading the source of Newtonsoft.Json :)

**Comment by JamesNK** [comment]
The type name isn't included with `IList<string>` and `List<string>` because Json.NET defaults to creating a `List<T>` for `IList<T>`, hence it is not needed.

If you always want it then use a setting other than auto.
