### ISSUE TITLE
JsonExtensionData contains undesired values when using a JsonConstructor with parameters

### ISSUE THREAD

**Issue by blazcowicz** [JamesNK/Newtonsoft.Json#1834]
There seems to be a problem with the way JsonExtensionData is filled when I am using both a JsonConstructor with parameters and ```DefaultValueHandling.IgnoreAndPopulate``` or ```Required.Always```. I have confirmed it by creating two small classes in the tests of the solution, so anyone can try easily.

```csharp
public class ItemWithJsonConstructor
{
    [JsonExtensionData]
    public IDictionary<string, JToken> ExtensionData;

    [JsonConstructor]
    private ItemWithJsonConstructor(string foo)
    {
        Foo = foo;
    }

    [JsonProperty(PropertyName = "foo", Required = Required.Always)]
    public string Foo { get; set; }
}
```

```csharp
public class ItemWithJsonConstructorAndDefaultValue
{
      [JsonExtensionData]
      public IDictionary<string, JToken> ExtensionData;

      [JsonConstructor]
      private ItemWithJsonConstructor(string foo)
      {
           Foo = foo;
      }

      [JsonProperty("foo")]
      public string Foo { get; set; }

      [JsonProperty(PropertyName = "bar", Required = Required.Default, DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate)]
      [System.ComponentModel.DefaultValue("default")]
      public string Bar { get; set; }
}
```

Again, with the simplest JSON I could make:

```javascript
{ "foo": "test" }
```

### Expected behavior

It worked perfectly when I first used the library (v6.0.8), but we recently upgraded to v10.0.3 and I started getting errors on deserialization. In both cases, I simply expect the extension data to be empty, because the values are matched by properties.

### Actual behavior

With the first class, I get the following extension data: ```{[ExtensionData, ]}```
And with the second class: ```{[ExtensionData, ]}, {[bar, ]}```

The problem seems to be that ExtensionData is treated like a regular property. With a bit of debugging, I found that when you have a JsonConstructor with parameters, every value from the JSON that doesn't meet one of the parameters name is considered an extended data if the matching property is marked as required or default, and most surprisingly the extended data itself.

I think this behavior is enabled by this line of code in JsonSerializerInternalReader:
```bool trackPresence = (contract.HasRequiredOrDefaultValueProperties || HasFlag(Serializer._defaultValueHandling, DefaultValueHandling.Populate));```

I can understand why the required or default values need to be included in a constructor with parameters (even if the previous behavior seemed more practical to me), but clearly a JsonExtensionData cannot be a parameter, so I believe there's a bug here.

**Comment by JamesNK** [comment]
Thanks for the detailed information. It was actually two separate bugs. Fixed.
