### ISSUE TITLE
JsonSerializerInternalReader EnsureType shows confusing message

### ISSUE THREAD

**Issue by Yoztastic** [JamesNK/Newtonsoft.Json#1844]
The exception that is thrown in `JsonSerializerInternalReader` line 989 
```   c#  
....EnsureType....           
 catch (Exception ex)
  {
    throw JsonSerializationException.Create(reader, "Error converting value {0} to type '{1}'.".FormatWith(CultureInfo.InvariantCulture, 
     MiscellaneousUtils.FormatValueForPrint(value), targetType), ex);
  } 
```
would it not be more useful to change `targetType` to `targetType.FullName`? As things stand it always emits 'System.Type' which is not very informative?

**Comment by JamesNK** [comment]
What platform is this on? ToString on Type should return FullName.
