### ISSUE TITLE
Optionally ignore $schema and $comment declarations

### ISSUE THREAD

**Issue by heaths** [JamesNK/Newtonsoft.Json#1845]
Rather than having to implement `JsonConverter.ReadJson` to specifically ignore `$schema` or `$comment`, it would be optimal for performance (i.e. use default implementation) and more productive to be able to ignore these - perhaps all - meta properties.

At least in 9.0.0.0 (which doesn't seem to have changed in this repo), `MetadataPropertyHandling` only handles `$id`, `$ref`, `$type`, and `$values`, which given its intended use makes sense. Perhaps another property used within `JsonSerializerInternalReader.CheckPropertyName` could ignore `$schema`, `$comment`, or perhaps optionally any property starting with `$`.

### Source/destination JSON

```javascript
{
  "$schema": "./schema.json#",
  "key1": {
    "value": 1
  },
  "key2": {
    "tags": [ "example" ],
    "value": 2
  }
}
```

### Expected behavior

With new behavior, `$schema` is ignored.

### Actual behavior

When the type being deserialized is an `IDictionary<string, SomeType>`, an exception is thrown like,

```
Newtonsoft.Json.JsonSerializationException: Error converting value "./schema.json#" to type 'SomeType'. Path '$schema', line 2, position 46. ---> System.ArgumentException: Could not cast or convert from System.String to SomeType.
```

### Steps to reproduce

```csharp
public T Read(TextReader reader, CancellationToken cancellationToken = default(CancellationToken))
{
    Validate.IsNotNull(reader, nameof(reader));

    cancellationToken.ThrowIfCancellationRequested();

    using (var jsonReader = new JsonTextReader(reader))
    {
        var serializer = JsonSerializer.CreateDefault(this.Settings);
        return serializer.Deserialize<T>(jsonReader);
    }
}

// The resolver and converters below are insignificant; the only converter does not support reading in this repro.
private JsonSerializerSettings Settings => new JsonSerializerSettings
{
    ContractResolver = resolver,
    Converters = converters,
    DateTimeZoneHandling = DateTimeZoneHandling.Utc,
    DefaultValueHandling = DefaultValueHandling.Ignore,
    EqualityComparer = StringComparer.OrdinalIgnoreCase,
    MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
};   
```

**Comment by JamesNK** [comment]
`MetadataPropertyHandling.Ignore` doesn't prevent the properties from being read, it prevents them from being read as metadata properties.

**Comment by heaths** [comment]
This is during serialization, and as described in the bug I'm deserializing an `IDictionary<string, Valuetype>`, so I don't see how your suggestion would even work since dictionaries using different deserialization.

I realize that `MetadataPropertyHandling` doesn't do this, which is why I thought a different property could be used to get the deserializer to skip over metadata properties automatically. The alternative is that we have to implement `JsonConverter.ReadJson` to handle this case ourselves when putting a `$schema` or `$comment` property in JSON is a common scenario that should be supported out of the box.

**Comment by JamesNK** [comment]
This is the scenario that JsonConverters are designed for: customizing how JSON is deserialized.

This is the first time this has ever been asked for so it isn't common.
