### ISSUE TITLE
Invalid JToken.Path when using special characters

### ISSUE THREAD

**Issue by Remy-Burney-Powerfront** [JamesNK/Newtonsoft.Json#1846]
JToken.Path not returning a correct value when using special characters like `'`
It will add 2 backslash instead of one

For example the path `We're offline!` will return `We\\'re offline!` instead of `We\'re offline!`

I believe this issue was introduced in v 11.0.1 after the new feature :

> New feature - Improved performance of JToken.Path with a faster reverse

**Comment by JamesNK** [comment]
I'm not able to reproduce this.

```
JValue v = new JValue(1);
JObject o = new JObject();
o["We're offline!"] = v;

Assert.AreEqual(@"['We\'re offline!']", v.Path);
```
