### ISSUE TITLE
Different result from jsonpath.com and SelectTokens

### ISSUE THREAD

**Issue by luizfbicalho** [JamesNK/Newtonsoft.Json#1856]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

### Expected behavior

In the http://jsonpath.com/ if I put this jsonpath query i get this result
[
  "0",
  "1",
  "2",
  "3",
  "-"
]

### Actual behavior

the result is empty 

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
var j = JObject.Parse(json)
var tokens = j.SelectTokens("$.phoneNumbers[:1].number[0,1,2,3,4]");
```

**Comment by JamesNK** [comment]
That is indexing into the string. I also tested it on https://jsonpath.curiousconcept.com/ and https://codebeautify.org/jsonpath-tester and they didn't index into the string.

IMO I think that is unexpected behavior.
