### ISSUE TITLE
Support distinguish between undefined and null in poco's

### ISSUE THREAD

**Issue by lanwin** [JamesNK/Newtonsoft.Json#1859]
We have the scenario that we need to know the difference of client send no/undefined property between client send property with null value in our mapped poco's.

For this purpose we created the following classes.

```csharp
    [JsonConverter(typeof(OptionalConverter))]
    public struct Optional<T> : OptionalConverter.IGenericAccess
    {
        bool _isValuePresent;
        T _value;

        public bool IsValuePresent
        {
            get => _isValuePresent;
            set
            {
                _isValuePresent = value;
                if(!value)
                    Value = default;
            }
        }

        public T Value
        {
            get => _value;
            set
            {
                _value = value;
                _isValuePresent = true;
            }
        }

        Type OptionalConverter.IGenericAccess.GenericType => typeof(T);

        object OptionalConverter.IGenericAccess.Value
        {
            set => Value = (T)value;
            get => Value;
        }

        public static implicit operator Optional<T>(T value) => new Optional<T> {Value = value};

        public static explicit operator T(Optional<T> optional)
        {
            if(!optional.IsValuePresent)
                throw new InvalidOperationException("The optional value is not preset");
            return optional.Value;
        }

        public override string ToString()
        {
            if(!IsValuePresent)
                return "{no value}";
            if(Value == null)
                return "{null}";
            return Value.ToString();
        }
    }

    public class OptionalConverter : JsonConverter
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var genericAccess = (IGenericAccess)value;
            if (!genericAccess.IsValuePresent)
            {
                writer.WriteUndefined();
                return;
            }

            serializer.Serialize(writer, genericAccess.Value);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (existingValue == null)
                existingValue = Activator.CreateInstance(objectType);

            if (reader.TokenType != JsonToken.Undefined)
            {
                var genericAccess = (IGenericAccess)existingValue;
                genericAccess.Value = serializer.Deserialize(reader, genericAccess.GenericType);
            }

            return existingValue;
        }

        public override bool CanConvert(Type objectType) => true;

        public interface IGenericAccess
        {
            bool IsValuePresent { get; }
            Type GenericType { get; }
            object Value { set; get; }
        }
    }
```

This can be used like this:

```csharp
class Result 
{
   public Optional<string> Name {get;set;}
   public Optional<int?> Age {get;set;} 
}

var result = JsonConvert.Desereialize<Result>("{age:null}");

Console.WriteLine(result.Name.IsValuePresent); // false
Console.WriteLine(result.Age.IsValuePresent); // true
```

I did not saw a different way of doing it, so I would ask if something like this wouldnt be a nice addition to Json.Net itself?!

**Comment by JamesNK** [comment]
You will need to write a JsonConverter and read the JSON yourself. Then you can test if a value is undefined.

**Comment by lanwin** [comment]
@JamesNK Sorry I did not understand your answer. 

I have a working solution. Instead I ask, if something like the type above would be a good fit for the Json.Net codebase? Since I can not be the only one who need a simple way to distinguish between null or undefined in C# Objects.

**Comment by JamesNK** [comment]
You can with JsonReader. I don't want to add it to the serializer.

**Comment by fanliver** [comment]
@lanwin How to make *undefined* fields be skipped during serialization instead of writing *undefined* value?
Let say we have an input JSON string, after deserialization and then serialization steps, we get an output JSON string. 
With your implemenation, the input and output JSON strings are not the same.
**Input**
```
{
    "Name": "HaPham", 
    "Age":1, 
    "Address": { 
        "Street" : "The Long Street" 
    } 
}
```
**Output**
```
{
  "Name": "HaPham",
  "Age": 1,
  "Address": {
    "Number": undefined,
    "Street": "The Long Street"
  }
}
```

**Comment by fanliver** [comment]
Adding should ShouldSerializeNumber() method to Address class is a workable solution.
However, it is cumbersome to add a ShouldSerialize_ method for every optional property.

**Comment by lanwin** [comment]
> Adding should ShouldSerializeNumber() method to Address class is a workable solution.
> However, it is cumbersome to add a ShouldSerialize_ method for every optional property.

Thanks for your answer! But I think you misunderstood what I want to to. My problem is not the serialization side. 

I have an webservice which inputs like this.

```
{
    name: "Bill Gates"
}
```

and

```
{
  name: "Elon Musk",
  age: null
}
```

With a mapping like this:

```
public class Person
{
    public string Name { get; set; }
    public Optional<int> Age { get; set; }
}
```
(Strong simplified case) The first one means. Update only the Name Property and leave Age unchanged. The second means Update Name and set Age to null (unset).

For this case I need to distinguish if `Age=undefined` and `Age=null` which I think is not possible with Json.NET out of the box. This is why I suggested such a type like in my post above.

**Comment by fanliver** [comment]
Yes, I understood what you wanted. I was facing the same problem. And I also want to handle the serialization as well. 
Btw, I have done it by inheriting DefaultContractResolver
```
public class OptionalContractResolver : DefaultContractResolver
{
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        var prop = base.CreateProperty(member, memberSerialization);

        if (typeof(IOptional).IsAssignableFrom(prop.PropertyType))
        {
            prop.ShouldSerialize = instance =>
            {
                var propValue = prop.DeclaringType.GetProperty(prop.PropertyName).GetValue(instance);
                return ((IOptional)propValue).HasValue;
            };
        }

        return prop;
    }
}
```

**Comment by BlackRider97** [comment]
Is there known solution for this apart from writing custom serialization and de-serialization logic ?
Just curious, what was the reason of closing this issue ? @lanwin

**Comment by lanwin** [comment]
> Just curious, what was the reason of closing this issue ? @lanwin 

@BlackRider97 I did not closed the issue.

**Comment by vgb1993** [comment]
I have the same needs, his is usefull thanks
