### ISSUE TITLE
IOS DateTimeOffset deserialization reflection

### ISSUE THREAD

**Issue by byrcb** [JamesNK/Newtonsoft.Json#1863]
I develop Xamarin for ios platform. During deserialization dateTimeOffset? app crash.

https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations
"Property.SetInfo on a Nullable Type is not supported
Using Reflection's Property.SetInfo to set the value on a Nullable<T> is not currently supported."

Probably it is because of the fact that reflection is used by JSON serialize. But from the other hand for int? it works.

**Comment by JamesNK** [comment]
I don't know what I can do. It sounds like a limitation of Xamarin on iOS. You should talk with Xamarin about the issue.
