### ISSUE TITLE
Provide a way to configure how byte[] is serialized

### ISSUE THREAD

**Issue by chrischu** [JamesNK/Newtonsoft.Json#1869]
It would be awesome if there was an easy way to configure how `byte[]` is serialized. As far as I know by default byte[] is serialized as a Base64-encoded string, however, we would prefer if the `byte[]` is serialized as JSON array instead. We know we can use a custom JsonConverter, but it seems odd that this (at least in our mind) very peculiar behavior cannot be configured in an easier way.

There are several reasons for this wish:
- We like the symmetry with other array types
- If we omit the type name when having a property with a declared type of `IReadOnlyList<byte>` and an actual type of `byte[]` it would still work, while it does not work when the `byte[]` is serialized as string, since the deserializer cannot infer that the string actually represents bytes.

Is there already an easy way to configure the `byte[]` serialization behavior we don't know of?

**Comment by JamesNK** [comment]
JsonConverter is how you do this. Adding a setting to customize how every type is serialized isn't reasonable.

**Comment by chrischu** [comment]
Maybe not every type, but every type that is handled unexpectedly? There are settings for how DateTimes are serialized aren't there?

**Comment by infacto** [comment]
@JamesNK An array should be serialized in json as array. The convertion to base64 should be a configuration. An option set to `false` by default. No modifications to the type `number[]` (json) like `int[]` and `byte[]`. You can do base64 conversion to Blobs or other binary stuff. But not to a `number[]` (number array). - With this behavior we have to write more code. For example casts or base64 convertion and to array. It's annoying and confusing. I just have to transmit 8 bytes to a JavaScript application. ...
