### ISSUE TITLE
Bad deserializing will SKIP try/catch completely: No exception thrown!

### ISSUE THREAD

**Issue by dylanh724** [JamesNK/Newtonsoft.Json#1873]
[C#/Visual Studio 2017]

1 - Try to deserialize from json to obj
2 - Expected to throw to "catch" on try/catch
3 - Completely exits the entire function, which seems to escape the entire reason for a try/catch (how is this even possible?)

```csharp
// Something is wrong - it won't parse (which isn't the issue - it's fine it won't parse). 
// Instead of throwing err, it just skips the try/catch as if it wasn't wrapped.
try
{
    SomeClass sc = JsonConvert.DeserializeObject<SomeClass>(someJson);
}
catch(Exception e)
{
    // Never triggers - never seen the catch not trigger before O_o
    // NOT EVEN AN ERROR! It's spooky. Seems to break the entire function.
}
```

Expected: Catch on try/catch to trigger via an exception throw.

**Comment by JamesNK** [comment]
I don't know. I don't have enough information to reproduce your issue. There are many unit tests of exceptions being thrown from DeserializeObject so I think it is unlikely an issue in Json.NET
