### ISSUE TITLE
Continuing the subject: Fixed serializing abstract base class ISerializable on .NET Core #1712

### ISSUE THREAD

**Issue by sorgpro** [JamesNK/Newtonsoft.Json#1889]
Steps to reproduce:

Create empty test .net core 2.1 project.
Add nuget Newtonsoft.Json (11.0.2)
Add file Newtonsoft.Json\Src\Newtonsoft.Json.Tests\Issues\Issue1682.cs
Add file Newtonsoft.Json\Src\Newtonsoft.Json.Tests\TestFixtureBase.cs to project.

Issue1682::Test_Serialize result:
Message: System.InvalidOperationException : Can't compile a NewExpression with a constructor declared on an abstract class.

**Comment by JamesNK** [comment]
Umm... what? It is fixed in the latest source code.

**Comment by sorgpro** [comment]
There is an error. I can not continue to work.
I did the project in steps that I indicated above.

[JsonBug.zip](https://github.com/JamesNK/Newtonsoft.Json/files/2522677/JsonBug.zip)

**Comment by JamesNK** [comment]
And it is already fixed but not yet released.
