### ISSUE TITLE
JsonConvert.DeserializeObject<dynamic> issue

### ISSUE THREAD

**Issue by thdotnet** [JamesNK/Newtonsoft.Json#1890]
I'm facing a problem with JsonConvert.DeserializeObject<dynamic> on version 11.0.2. After converting a valid json to dynamic type, it's wrapping with another {} and making the navigation through obj.propertyName impossible. Anyone else is facing the same problem?

**Comment by JamesNK** [comment]
Ask questions like this on StackOverflow.
