### ISSUE TITLE
JToken.toString() issue with Boolean type

### ISSUE THREAD

**Issue by sunyutj** [JamesNK/Newtonsoft.Json#1894]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
JToken jt=JToken.FromObject(false);
string json = jt.toString();  // json="False"
try
{
    jt=JToken.Parse(json);
}
catch (Exception)
{ throw;}

```

### Expected behavior

string json could be successful parsed to JToken instance with type of JTokenType.Boolean.
### Actual behavior

throw an exception.
jt.toString() returns "False". However JToken.Parse() only accepts the lowercase word "false";

**Comment by JamesNK** [comment]
ToString on JValue returns the .NET representation.
