### ISSUE TITLE
Wrong error message: Newtonsoft.Json.JsonSerializationException: 'A member with the name 'X' already exists on 'Model.Y'

### ISSUE THREAD

**Issue by cloudybrain** [JamesNK/Newtonsoft.Json#1901]
I have the following class:

    public class Stuff
    {
        [JsonProperty("Thing1")]
        public double Thing1 { get; set; }
        [JsonProperty("Thing2")]
        public double Thing2 { get; set; }
    }

If I run the following:
var responseObj = new Stuff { Thing1 = 201.2, Thing2 = 1922.2 }
Object.FromObject(responseObj);  //this produces valid json

But if I do this:

    public class Stuff
    {
        [JsonProperty("Thing1")]
        _thing1 = 0;
        public double Thing1 { 
           get  => Math.Round(_thing1, 3);
           set => _thing1 = Math.Round(value, 3);
        }
        [JsonProperty("Thing2")]
        _thing2 = 0;
        public double Thing2 { 
           get  => Math.Round(_thing2, 3);
           set => _thing2 = Math.Round(value, 3);
        }
    }

then run the following:
var responseObj = new Stuff { Thing1 = 201.2, Thing2 = 1922.2 }
Object.FromObject(responseObj);  //this produces invalid json

I get an error that says:
Newtonsoft.Json.JsonSerializationException: 'A member with the name 'Thing1' already exists on 'Model.Stuff'. Use the JsonPropertyAttribute to specify another name.'

**Which is not true.**

The only way to fix this is by either editing the JSONProperty name to a different name, or the actual property name itself to a different name.. so either of these would work:

    public class Stuff
    {
        [JsonProperty("Thing1_Column")]
        _thing1 = 0;
        public double Thing1 { 
           get  => Math.Round(_thing1, 3);
           set => _thing1 = Math.Round(value, 3);
        }
        [JsonProperty("Thing2_Column")]
        _thing2 = 0;
        public double Thing2 { 
           get  => Math.Round(_thing2, 3);
           set => _thing2 = Math.Round(value, 3);
        }
    }

     //OR

    public class Stuff
    {
        [JsonProperty("Thing1")]
        _thing1 = 0;
        public double Thing1_Column { 
           get  => Math.Round(_thing1, 3);
           set => _thing1 = Math.Round(value, 3);
        }
        [JsonProperty("Thing2")]
        _thing2 = 0;
        public double Thing2_Column { 
           get  => Math.Round(_thing2, 3);
           set => _thing2 = Math.Round(value, 3);
        }
    }

The problem is, I have too much code relying on both of these properties, and it would take a TON of refactoring and a TON of extra testing.. And it's unfortunate that I can't serialize a class that has definition in the setter and getter for property names and JsonProperties both being the same name.. And on top of that, I get the weird and incorrect message about how there's a duplicated property, that made me lose about 2 hours of my time, thinking I really did have a duplicate property. I thought it was copying and pasting weird hidden characters, or visual studios was acting up, and I cleaned the project a few times, restarted visual studios, etc etc.

**Comment by JamesNK** [comment]
> Which is not true.

Yes it is. You have a property called `Thing1` and you have a field you are also mapping to `Thing1` because of the `[JsonProperty("Thing1")]` attribute on it. Either don't have the attribute on it or use a different name.

**Comment by cloudybrain** [comment]
Ah, I didn't know that. However, it works when you dont have a definition for getter though. As soon as you add a definition it breaks.

Because it has been working like that for almost a year, my backend is wired to use the property name, and my front end is used to json property name.. if I change any of those it breaks. I was expecting that it wouldnt matter if I added a body to the getter.

Ill see what I can do to removw the json property names, but it just seems a bit weird that it breaks due to the modified definition.
