### ISSUE TITLE
Reading decimal.MaxValue results in a System.OverflowException

### ISSUE THREAD

**Issue by maggo23** [JamesNK/Newtonsoft.Json#1904]
Writing of <code>decimal.MaxValue</code> to a JSON file is successful. But reading it back from the file results in a __System.OverflowException__. See the following example:

```
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			var path = "Test.json";
			var propName = "Value";
			using (var sw = new StreamWriter(path))
			using (var writer = new JsonTextWriter(sw))
			{
				writer.Formatting = Formatting.Indented;
				writer.WriteStartObject();
				writer.WritePropertyName(propName);
				writer.WriteValue(decimal.MaxValue);
				writer.WriteEndObject();
			}
			using (var sr = new StreamReader(path))
			using (var jr = new JsonTextReader(sr))
			{
				var serializer = new JsonSerializer();
				var jRoot = serializer.Deserialize<JObject>(jr);
				var v = jRoot[propName].Value<decimal>();
			}
		}
	}
}
```

Tested with:
- MS Visual Studio Pro 2017 Version 15.8.8
- .NET Frameweork 4.7.1
- Newtonsoft.Json 11.0.2

**Comment by TylerBrinkley** [comment]
It does not error if you specify a `FloatParseHandling.Decimal` on the `JsonTextReader`.

**Comment by maggo23** [comment]
Thank you for your quick response. Your fix will work with the example above. If I understand you correctly ```FloatParseHandling``` is a "global" setting to deserialize to ```JObject```. But I need to parse ```decimal``` __and__ ```double``` values from a JSON file. So I adjusted my example:
```
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;


namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			var path = "Test.json";
			using (var sw = new StreamWriter(path))
			using (var writer = new JsonTextWriter(sw))
			{
				writer.Formatting = Formatting.Indented;
				writer.WriteStartObject();
				writer.WritePropertyName("ValueDec");
				writer.WriteValue(decimal.MaxValue);
				writer.WritePropertyName("ValueDbl");
				writer.WriteValue(double.MaxValue);
				writer.WriteEndObject();
			}
			using (var sr = new StreamReader(path))
			using (var jr = new JsonTextReader(sr))
			{
				jr.FloatParseHandling = FloatParseHandling.Decimal;
				var serializer = new JsonSerializer();
				var jRoot = serializer.Deserialize<JObject>(jr);
				var vDec = jRoot["ValueDec"].Value<decimal>();
				var vDbl = jRoot["ValueDbl"].Value<double>();
			}
		}
	}
}
```
As expected, this example results into an error:
```
Newtonsoft.Json.JsonReaderException: 'Input string '1.7976931348623157E+308' is not a valid decimal. Path 'ValueDbl', line 3, position 37.'
```
Maybe there is a another solution to read a JSON file. Do you have an idea?

**Comment by TylerBrinkley** [comment]
If you can guarantee all the `double` values you're going to parse can be represented in a `decimal` value then just go with `FloatParseHandling.Decimal`. Otherwise you'll probably have to resort to creating C# classes to deserialize to with various `decimal` or `double` properties as opposed to deserializing to a `JObject`.

**Comment by JamesNK** [comment]
@TylerBrinkley's suggestion is the best one.

Or you could read the JSON manually with a JsonTextReader.

**Comment by maggo23** [comment]
I'm sorry that I did not comment this issue again. I implemented @TylerBrinkley's suggestion and it works fine. Thank you very much for the help.
