### ISSUE TITLE
Bad JSON escape sequence: \p. Path '[0].Annex', line 1, position 302

### ISSUE THREAD

**Issue by 188876662287** [JamesNK/Newtonsoft.Json#1906]
“Newtonsoft.Json.JsonReaderException”类型的未经处理的异常在 Newtonsoft.Json.dll 中发生 

其他信息: Bad JSON escape sequence: \p. Path '[0].Annex', line 1, position 302.

无法支持"Annex":"D:\plugs\setup.exe" ？

**Comment by JamesNK** [comment]
Sorry, I don't understand
