### ISSUE TITLE
FEATURE: Provide control to opt-in/opt-out of json path features

### ISSUE THREAD

**Issue by patrickcarnahan** [JamesNK/Newtonsoft.Json#1911]
The JToken.SelectToken/SelectTokens APIs do not currently provide any mechanism to control the supported feature set. For instance, we will be hosting user-provided path selectors on a service and would like to disable the ability to utilize regular expressions in the selectors. You might imagine this as a simple method overload which accepts an optional enumeration value of supported features.

**Comment by patrickcarnahan** [comment]
We are happy to contribute a PR which implements the feature if there is general agreement on the utility of such an API addition.

**Comment by Thaina** [comment]
I think it would be more easily if you just parse that query into `JPath` and validate it before querying then throw exception that you have forbidden specific feature, instead of having this library can opt-out feature dynamically
