### ISSUE TITLE
ContractResolver.DefaultMembersSearchFlags is obsolete: GetSerializableMembers seems non-trivial to override

### ISSUE THREAD

**Issue by isengrim613** [JamesNK/Newtonsoft.Json#1912]
My goal is to simply include setting properties with private setters during deserialization.

I've managed to figure out how to do it with help from [StackOverflow](https://stackoverflow.com/questions/4066947/private-setters-in-json-net).

However, `ContractResolver.DefaultMembersSearchFlags` is marked as obsolete with the recommendation to override `ContractResolver.GetSerializableMembers` instead.

Upon inspecting `ContractResolver.GetSerializableMembers`'s code, it seems non-trivial and even daunting to override the function. In the most risk-adverse scenario, I would copy and paste the whole code and only replace the DefaultMembersSearchFlags with the flags I want.

It shouldn't be this daunting / non-trivial to customize the serializer in such a simple sense, which makes me wonder why `DefaultMembersSearchFlags` is marked as obsolete.

**Comment by JamesNK** [comment]
Just call `base.GetSerializableMembers` then filter the result.

**Comment by isengrim613** [comment]
Oh, I can filter in private properties after they are filtered out without repeating the code in the original method?

Do you have some example code to do that?
