### ISSUE TITLE
Strange DeserializeAnonymousType()

### ISSUE THREAD

**Issue by Alex1080** [JamesNK/Newtonsoft.Json#1913]
https://github.com/JamesNK/Newtonsoft.Json/blob/d03963016e3d691950f19896178e6e8ea0de1b3b/Src/Newtonsoft.Json/JsonConvert.cs#L708

What does it mean? Why it's anonymouse if I specify the type T explicitly? Why this method still exists? That's ridiculous... (otherwise, explain me please, why it has a reason to live (not to be removed))

Thank you

**Comment by TylerBrinkley** [comment]
https://www.newtonsoft.com/json/help/html/DeserializeAnonymousType.htm

**Comment by Alex1080** [comment]
Thank you
