### ISSUE TITLE
OverrideSpecifiedNames and ProcessDictionaryKeys default value on CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by alexdawes** [JamesNK/Newtonsoft.Json#1920]
Hi,

I was just wondering whether there is a reason for defaulting the ProcessDictionaryKeys and OverrideSpecifiedNames settings in the CamelCasePropertyNamesContractResolver class to true:
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs#L49-L50

I recently discovered an issue in a messaging library that uses JSON.NET for json serialization/deserialization and was able to trace it to its use of the above class with the default options. The issue itself resulted in Dictionary<string,TValue> changing keys (all keys were camel-cased) after being sent through the message bus.

The decision to make these values true by default on the contract resolver seems unintuitive to me, as it means that serializing and then deserializing dictionaries does not get you back to where you started. Though I am not certain of the behaviour of OverrideSpecifiedNames, I imagine the same might be true when using custom serialization via JsonProperty attributes if deserialization then relies on a custom constructor.

Is there something I am missing?

Thanks,
Alex

**Comment by alexdawes** [comment]
To reproduce the issue:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace ConsoleApp
{
    class Program
    {
        static T SerializeAndDeserialize<T>(T obj, JsonSerializerSettings settings)
        {
            return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(obj, settings), settings);
        }

        static void Main(string[] args)
        {
            var dict = new Dictionary<string, string> {{"Foo", "Bar"}};

            var settingsWithDictKeysCamelCased = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };

            var settingsWithDictKeysUnchanged = new JsonSerializerSettings
            {
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                }
            };

            var result1 = SerializeAndDeserialize(dict, settingsWithDictKeysCamelCased);
            var result2 = SerializeAndDeserialize(dict, settingsWithDictKeysUnchanged);

            Console.WriteLine(string.Join(", ", result1.Select(kvp => $"{kvp.Key}: {kvp.Value}"))); // foo: Bar
            Console.WriteLine(string.Join(", ", result2.Select(kvp => $"{kvp.Key}: {kvp.Value}"))); // Foo: Bar

            Console.ReadLine();
        }
    }
    
}
```

**Comment by niemyjski** [comment]
I also am seeing this behavior where a `public Dictionary<string, bool> Blah { get; }` keys are being changed and I've tried setting `ProcessDictionaryKeys` to `false`.

**Comment by JamesNK** [comment]
They're set to true because that has always been the default behavior of `CamelCasePropertyNamesContractResolver`. I added naming strategies later and decided to make them behave differently, however I couldn't change the resolver for backwards compatibility reasons.

**Comment by kkriegkxs** [comment]
Yep. This should go into the documentation (pretty please). I would say this flag should be a part of the CamelCasePropertyNamesContractResolver constructor. I have never noticed this behavior as I rarely use this resolver (instead controlling naming via annotations).
I though I was insane and spent a lot of effort to figure it out (coming to the same root cause as @alexdawes). 
Once identified, the fix took 5m but oh do I wish I found this post sooner...

**Comment by hartmark** [comment]
The docs are a bit confusing regarding this setting.

https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_CamelCaseNamingStrategy.htm

Here the docs says its default value is false.

However it is set to true as default.
https://github.com/JamesNK/Newtonsoft.Json/blob/01e1759cac40d8154e47ed0e11c12a9d42d2d0ff/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs#L49-L50

**Comment by bartelink** [comment]
@hartmark the doc link is about the naming strategy. The code you link is the contract resolver, which is overriding that correctly documented default.

While it would be nice if that code provided more detailed documentation, the existing documentation is not actually wrong as you suggest?

**Comment by hartmark** [comment]
I agree with you, but the thing is that the default is overridden in CamelCasePropertyNamesContractResolver without mentioning it.

Only way to know it's been overridden is by checking the code.
