### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by Varorbc** [JamesNK/Newtonsoft.Json#1934]
version:12.0.1.0

JsonConvert.DeserializeObject<string>("123");  is ok 

JsonConvert.DeserializeObject<string>("f46f473532f55edd19167f22b267c376"); is error

**Comment by JamesNK** [comment]
That's not valid JSON

**Comment by JamesNK** [comment]
I don’t know what you are talking about. Newtonsoft.Json is a JSON library
