### ISSUE TITLE
Cannot turn off line info, creating major GC pressure

### ISSUE THREAD

**Issue by heaths** [JamesNK/Newtonsoft.Json#1938]
We are deserializing a fairly large JSON document - ~13MB - and ~11MB of `LineInfoAnnotation` is being allocated. Looking through the code (tagged 9.0.1, but master does not appear to be different in this matter), it appears there is no way to prevent this.

We need to be able to turn this off to decrease heap allocations, which in turn are causing GC pressure which can lead to hangs.

**Comment by JamesNK** [comment]
Either https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Linq_JsonLoadSettings_LineInfoHandling.htm

or

```cs
public class NoLineInfoJsonTextReader : JsonTextReader, IJsonLineInfo
{​
    public NoReaderInfo(TextReader reader) : base(reader)​
    {​
    }​
​
    bool IJsonLineInfo.HasLineInfo()​
    {​
        return false;​
    }​
}​
```
