### ISSUE TITLE
JsonWriter mis-handles control characters

### ISSUE THREAD

**Issue by radsolution** [JamesNK/Newtonsoft.Json#1942]
When using `JObject.FromObject()`, or a custom converter which has:

```
public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
{
if (value == null)
return;

string s = String.Join("\r\n", (string[]) value); // the writer messes up \r\n strings
writer.WriteValue(s);
}
```
the resulting piece of text withing the JSON string will be:
`String1\\r\\nString2\\r\\nString3`

It appears that the JsonWrite is 'escaping' the `\`
rather than treating the `\r` as a single control character.

**Comment by JamesNK** [comment]
That JSON is correct. Line breaks are supposed to be escaped.

http://json.org/

**Comment by radsolution** [comment]
James,

My point is that they are double-escaped.

Any normal line break is shown as \n or \r.

It appears that the \ is being escaped, resulting in a sequence of \\n

Dave
