### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: 'Input string '2.245E+34' is not a valid decimal

### ISSUE THREAD

**Issue by fuhongbo** [JamesNK/Newtonsoft.Json#1951]
Below code get a error message "Newtonsoft.Json.JsonReaderException: 'Input string '2.245E+34' is not a valid decimal. Path 'value', line 1, position 18.'"  Could you help that how to solve this problem?
I know if set FloatParseHandling is Double will be work. but the value2‘s precision will be loss.

            Newtonsoft.Json.JsonSerializerSettings setting = new Newtonsoft.Json.JsonSerializerSettings();
            JsonConvert.DefaultSettings = new Func<JsonSerializerSettings>(() =>
            {
                setting.NullValueHandling = NullValueHandling.Ignore;
                setting.FloatParseHandling = FloatParseHandling.Decimal;
                return setting;
            });

            string jsonStr = "{\"value\":2.245E+34,\"value2\":24444456655222.883838383381}";

            var obj=Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(jsonStr);

**Comment by JamesNK** [comment]
2.245E+34 doesn't fit in a decimal. Throwing an error is correct.

**Comment by fuhongbo** [comment]
@JamesNK Hello, ok, but how to setting float precision for json.net
