### ISSUE TITLE
Crash in C# Class Library when i use it...

### ISSUE THREAD

**Issue by Sakamaki-Izayoi** [JamesNK/Newtonsoft.Json#1953]
### Source/destination types

```csharp
public struct MyStruct
{
    public int FirstText { get; set; }
    public int SecondText { get; set; }
}
```

### Source/destination JSON

```javascript
{FirstText:1,SecondText:2}
```

### Expected behavior

```csharp
When i use it in a single exe demo:
1 - 2
```

### Actual behavior

```csharp
When i use it in a C# Class Library, it crash:

System.Reflection.TargetInvocationException: Exception has been thrown by the ta
rget of an invocation. ---> System.Security.SecurityException: Request failed.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOn
ly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Bo
olean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipChec
kThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean s
kipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.<>c__DisplayC
lass9`1.<CreateDefaultConstructor>b__7()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject
(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMem
ber, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCr
eator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Js
onReader reader, Type objectType, JsonContract contract, JsonProperty member, Js
onContainerContract containerContract, JsonProperty containerMember, Object exis
tingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInte
rnal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty mem
ber, JsonContainerContract containerContract, JsonProperty containerMember, Obje
ct existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Jso
nReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, Jso
nSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSeriali
zerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
```

### Steps to reproduce

```csharp
var test = Newtonsoft.Json.JsonConvert.DeserializeObject<MyStruct>("{FirstText:1,SecondText:2}");

System.Console.WriteLine("{0} - {1}", test.FirstText, test.SecondText);
```

**Comment by sup3rvis0r** [comment]
You are using Newtonsoft.JSON in a sandboxed AppDomain. `Activator.CreateInstance()`, which is used by the library, requires full trust for the immediate caller and cannot be used by partially trusted or transparent code. Newtonsoft.JSON has to be given full trust in the sandbox for it to work properly.

**Comment by Sakamaki-Izayoi** [comment]
> You are using Newtonsoft.JSON in a sandboxed AppDomain. `Activator.CreateInstance()`, which is used by the library, requires full trust for the immediate caller and cannot be used by partially trusted or transparent code. Newtonsoft.JSON has to be given full trust in the sandbox for it to work properly.

I use AppDomain.Load to load a new lib so the references of the new lib must be full trust？

**Comment by Sakamaki-Izayoi** [comment]
> You are using Newtonsoft.JSON in a sandboxed AppDomain. `Activator.CreateInstance()`, which is used by the library, requires full trust for the immediate caller and cannot be used by partially trusted or transparent code. Newtonsoft.JSON has to be given full trust in the sandbox for it to work properly.

I am a C# novice and I try to give the lib full trust but it still do not work.
This is my sandbox code:
domain = (SandboxDomain)Activator.CreateInstanceFrom(appDomain, Assembly.GetExecutingAssembly().Location, typeof(SandboxDomain).FullName).Unwrap()

**Comment by Sakamaki-Izayoi** [comment]
> You are using Newtonsoft.JSON in a sandboxed AppDomain. `Activator.CreateInstance()`, which is used by the library, requires full trust for the immediate caller and cannot be used by partially trusted or transparent code. Newtonsoft.JSON has to be given full trust in the sandbox for it to work properly.

I use gacutil to register Newtonsoft.Json.dll to GAC and it works.

But I want to finish this process in my code. Microsoft.Docs indicate that
 'Assemblies that are loaded into an AppDomain by using this overload can either have the specified grant set only, or can be fully trusted. The assembly is granted full trust if it is in the global assembly cache or listed in the fullTrustAssemblies (the StrongName) array parameter.'

I try to give Newtonsoft.Json.dll full trust by strong name but failed, maybe my operation is not correct. So I dk how to use Newtonsoft.Json.dll without register to GAC.

**Comment by Sakamaki-Izayoi** [comment]
> You are using Newtonsoft.JSON in a sandboxed AppDomain. `Activator.CreateInstance()`, which is used by the library, requires full trust for the immediate caller and cannot be used by partially trusted or transparent code. Newtonsoft.JSON has to be given full trust in the sandbox for it to work properly.

I got it. Json.NET should be loaded as fully trusted and it can be set when use AppDomain.CreateDomain. And I init StrongName with .dll cause the error that can not find it. Both registed in GAC and set with AppDomain.CreateDomain are work fine. Thanks for ur help!
