### ISSUE TITLE
Conditional deserialize

### ISSUE THREAD

**Issue by ShamblerBishop** [JamesNK/Newtonsoft.Json#196]
I implemented a contract resolver for conditional serializing (writing), using the ShouldSerialize predicate, but there is no equivalent for deserialization (reading).

This seems to be a strange omission, because there are a lot of cases where you want to both conditionally read/write a set of values - would be nice if this were added, in a similarly easy-to-use fashion as the ShouldSerialize predicate and function.

Also, it might be useful to try and autodetect and warn the programmer, when serialize-only contract resolver settings are used, with deserialization.

**Comment by mihaipanait** [comment]
+1

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/88468c4e6e6cef982e0f6d3ce57624fadff718ec
