### ISSUE TITLE
12.0.1 - Endless loop in JToken.ToObject<T> from JToken with comments at start

### ISSUE THREAD

**Issue by kae** [JamesNK/Newtonsoft.Json#1962]
### Source/destination types

```csharp
int[]
```

### Source/destination JSON

```javascript
// comment
[ 1, 2, 42 ]
```

### Expected behavior
obj set to array of ints.

### Actual behavior

Code hangs in endless loop inside Newtonsoft.Json.JsonReader.MoveToContent()

### Steps to reproduce

```csharp
var json = @"// comment
[ 1, 2, 42 ]";
var token = Newtonsoft.Json.Linq.JToken.Parse(json);
var obj = token.ToObject<int[]>();
```

**Comment by fhnaseer** [comment]
Expected behavior should be Exception instead of array of ints. Comments (// comment) are not allowed in json.

**Comment by kae** [comment]
@fhnaseer 
Not in standard, yes.
But Json.NET supports comments in JSON.
Both /**/ and //

**Comment by fhnaseer** [comment]
@kae Didn't know about that, thanks,

**Comment by dovisutu** [comment]
Confirmed still exist even in 12.0.3-beta1.
The reason it loops because somehow the program fall in a strangeplace where `TokenType` has only been assingned by `_root` which happens to be also `{ comment}`.

**Comment by JamesNK** [comment]
Fixed.

FYI, this code will actually result in obj being `null`.
```csharp
var json = @"// comment
[ 1, 2, 42 ]";
var token = Newtonsoft.Json.Linq.JToken.Parse(json);
var obj = token.ToObject<int[]>();
```

You want:
```csharp
var json = @"// comment
[ 1, 2, 42 ]";
var token = Newtonsoft.Json.Linq.JToken.Parse(json, new JLoadSettings { CommentHandling = CommentHandling.Ignore });
var obj = token.ToObject<int[]>();
```
