### ISSUE TITLE
Deserialize bug

### ISSUE THREAD

**Issue by LucaGabi** [JamesNK/Newtonsoft.Json#1973]
### Expected behavior

Correct object deserialization.

### Actual behavior

Missing array object 
DocSpec table is missing DocId column.

### Steps to reproduce

```JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Formatting = Newtonsoft.Json.Formatting.Indented,
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects
            };
            var jss = File.ReadAllText(@"o.json");
            var outobj = JsonConvert.DeserializeObject<DatabaseSchema>(jss);
[dbschema.zip](https://github.com/JamesNK/Newtonsoft.Json/files/2821931/dbschema.zip)


```

**Comment by LucaGabi** [comment]
[dbschema.zip](https://github.com/JamesNK/Newtonsoft.Json/files/2821938/dbschema.zip)

**Comment by danebou** [comment]
What is your DatabaseSchema class?

**Comment by LucaGabi** [comment]
In the attached files there is a way to reproduce the bug and all classes .. the problem is with any field named DocId there must be related to the word being treated as reserved for the json schema, maybe, not shure.

**Comment by LucaGabi** [comment]
This is the problem that I face: https://youtu.be/X_l72m45q4I

**Comment by LucaGabi** [comment]
My mistake, I used wrong setting: ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.**Ignore**
