### ISSUE TITLE
Deserialize fails with Overloaded Constructors  

### ISSUE THREAD

**Issue by niranjanbohra** [JamesNK/Newtonsoft.Json#1987]
public class Demo
    {
        string a;
        public Demo(string foo)
        {
            a = foo;
        }

        public Demo(int foo)
        {
            string a = foo.ToString();
        }
    }
For Above Class it fails in Deserializing, Is there any way or workaround to solve this issue ?

**Comment by JamesNK** [comment]
Add [JsonConstructor] to one of the constructors. Also the incoming JSON needs to map to the argument name for it to be used with the constructor.
