### ISSUE TITLE
Memory leak using enumeration in Newtonsoft.Json v12

### ISSUE THREAD

**Issue by mantasaudickas** [JamesNK/Newtonsoft.Json#1991]
Hello,

we have identified a memory leak when using Newtonsoft.Json v12.0.1.
There was a code written like this and executed multiple times:
```
var serialized = JsonConvert.SerializeObject(message, Formatting.None, new StringEnumConverter(true));
```

The code above was working without issues with v11, but consumes a lot of memory in v12.

Test code:
```csharp
[Fact]
public void SerializeManyTimes()
{
    var message = new Message();
    while (true)
    {
        JsonConvert.SerializeObject(message, Formatting.None, new StringEnumConverter(true));
    }
}

private class Message
{
    public string Content { get; set; } = "Sample";
    public MessageType Type { get; set; }
}

private enum MessageType
{
    Test
}
```

Same effect for both: serialize and deserialize methods.

Guessing that issue most likely is inside EnumUtils, which is adding items using key:
```
new StructMultiKey<Type, NamingStrategy>(enumType, namingStrategy) 
```

StructMultiKey has overridden Equals method:
```
return (Equals(Value1, other.Value1) && Equals(Value2, other.Value2));
```

But all `NamingStartegy` implementations does not have it..
That means test case:
```
Assert.True(Equals(new CamelCaseNamingStrategy(), new CamelCaseNamingStrategy()));
```
is failing and ConcurrentDictionary which is used in ThreadSafeStore is always creating (and keeping) new instances.

Workaround for us was to reuse StringEnumConverter as this is right thing to do anyway, but also this should be fixed inside serializer implementation.

**Comment by JamesNK** [comment]
Fixed with the merged PR.
