### ISSUE TITLE
NullValueHandling.Ignore doesn't ignore nulls

### ISSUE THREAD

**Issue by lcsondes** [JamesNK/Newtonsoft.Json#1997]
### Source/destination types

```csharp
System.Collections.Generic.Dictionary<string, object>
```

### Source/destination JSON

```javascript
{"exists":1,"doesnt":null}
```

### Expected behavior

That the null is not included.

### Actual behavior

The null is included.

### Steps to reproduce

```csharp
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Sample
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var obj = new Dictionary<string, object>
            {
                ["exists"] = 1,
                ["doesnt"] = null,
            };

            var json = JsonConvert.SerializeObject(obj, new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            });

            System.Console.WriteLine(json);
        }
    }
}
```

**Comment by mdalepiane** [comment]
I was able to reproduce this problem here. It seems to me that there is no check in [SerializeDictionary](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L1041) to see whether NullValueHandling is set to Ignore or not.

**Comment by mdalepiane** [comment]
Actually looking at https://github.com/JamesNK/Newtonsoft.Json/issues/1491 it seems that this behavior is by design. But why is this the expected behavior?

**Comment by Kamarey** [comment]
Same for me.

This example from documentation doesn't work: https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm

I tried it here: https://dotnetfiddle.net/5683os

**Comment by akytsun** [comment]
it still not fixed

**Comment by halex2005** [comment]
@Kamarey, you just have copy-pasted Console.WriteLine(included) and have not changed it:

```
Console.WriteLine(included);
Console.WriteLine("");
Console.WriteLine(included); //  <-- here you should change included to ignored
```

**Comment by JamesNK** [comment]
This setting is only for properties on objects. Not dictionaries.
