### ISSUE TITLE
JsonExtensionData ignores NamingStrategy for dictionaries

### ISSUE THREAD

**Issue by DalSoft** [JamesNK/Newtonsoft.Json#1998]
### Source

```csharp
public class Example
{
        public string Foo { get; set; }
       
        [JsonExtensionData]
        public IDictionary<string, object> Extensions { get; } = new Dictionary<string, object>();
}

var example = new Example  { ShouldBeSnakeCase1 = "..." } ;

example.Add("ShouldBeSnakeCase2", "...");

var jsonSerializerSettings = new JsonSerializerSettings
{
        ContractResolver = new DefaultContractResolver 
        { 
                NamingStrategy = new SnakeCaseNamingStrategy 
                { 
                        ProcessDictionaryKeys = true 
                } 
        }
}

JsonConvert.SerializeObject(example, jsonSerializerSettings);
```

### Destination JSON

```javascript
{
        "should_be_snake_case1": "...",
        "ShouldBeSnakeCase2": "..." // Expected should_be_snake_case2
}
```

### Expected behavior
JsonExtensionData should respect NamingStrategy for dictionaries when ProcessDictionaryKeys is set to true 

### Actual behavior
ProcessDictionaryKeys is ignored when for dictionaries using JsonExtensionData

### Steps to reproduce

See example Source and Destination.

**Comment by dbc2** [comment]
Have you tried setting [`NamingStrategy.ProcessExtensionDataNames = true`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_NamingStrategy_ProcessExtensionDataNames.htm)?

**Comment by dbc2** [comment]
Yes, [`ProcessExtensionDataNames`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_NamingStrategy_ProcessExtensionDataNames.htm) does what you want; the following unit test passes:

	var example = new Example();//  { ShouldBeSnakeCase1 = "..." } ;

	example.Extensions.Add("ShouldBeSnakeCase2", "...");

	var jsonSerializerSettings = new JsonSerializerSettings
	{
		ContractResolver = new DefaultContractResolver 
		{ 
			NamingStrategy = new SnakeCaseNamingStrategy 
			{ 
				//ProcessDictionaryKeys = true,
				ProcessExtensionDataNames = true
			} 
		}
	};

	var json = JsonConvert.SerializeObject(example, jsonSerializerSettings);
	
	// Prints {"foo":null,"should_be_snake_case2":"..."}
	Console.WriteLine(json);
	
	// The following does not fail
	Assert.IsTrue(json.Contains("should_be_snake_case2")); 

Demo fiddle: https://dotnetfiddle.net/uIIObX

Support for naming strategies for extension data was added in [10.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/10.0.1), so I'd suggest closing this issue.

**Comment by DalSoft** [comment]
Awesome thank you!
