### ISSUE TITLE
I want JsonConvert to be an object instance.

### ISSUE THREAD

**Issue by PMExtra** [JamesNK/Newtonsoft.Json#1999]
I want a JsonConvert instance to configure DefaultSettings for each module.

I used Newtonsoft.Json everywhere in my project.

And I have a module that used to communicate with client by tcp message.

I want to custom the serialization for this module and **only** for this module.

For now, I have to specific settings every time, like `JsonConvert.Serialize(message, messageConvertSettings)`.

So why don't we let `JsonCovert` be an object instance instead a static class?

**Comment by stv2pointo** [comment]
Couldn't you simply create a wrapper around JsonConvert to accomplish what you need?

**Comment by JamesNK** [comment]
Or use JsonSerializer. JsonConvert just creates one and passes values to it internally.
