### ISSUE TITLE
Why csproj is still at version 11.0.1 beta2?

### ISSUE THREAD

**Issue by teejay-87** [JamesNK/Newtonsoft.Json#2014]
Why csproj is still at version 11.0.1 beta2?

How am I supposed to compile from source?

Compiling either from VS or PowerShell result in errors:
>     Error: Unable to locate repository containing directory 'C:\Development\Components\Source\Newtonsoft.Json-12.0.1\Src\Newtonsoft.Json'. (1, 1)

**Comment by JamesNK** [comment]
There is a CI build that sets the version from outside the csproj.

There is nothing stopping you updating it to 12.0.1 if that is the version of the package you want to produce.

**Comment by teejay-87** [comment]
I ran the powershell script runbuild.ps but it gives me the above errors. Any ideas?
