### ISSUE TITLE
ShouldSerialize Runtime Exception Nullable Type

### ISSUE THREAD

**Issue by ddrdoubled** [JamesNK/Newtonsoft.Json#2017]
### Source/destination types

```
public class SomeClass
{
        public SomeEnum? EnumValue { get; set; }

        public bool ShouldSerializeEnumValue()
        {
            return this.EnumValue.HasValue;
        }
 }

public enum SomeEnum
    {
        Test = 1,

        Test2 = 2,
    }

```
### Expected behavior

Used DefaultContractResolver.ResolveContract(typeof(SomeClass)) to get JsonObjectContract.
Tried to Invoke on Property EnumValue "ShouldSerialize" predicate. Expected behaviour should be to return false

### Actual behavior

Null Reference Exception

### Steps to reproduce

```csharp
External:
var objectContract = ResolveContract(typeof(SomeClass)) as JsonObjectContract;
            foreach (var contractProperty in objectContract.Properties)
            {
                var propertyShouldSerialize = contractProperty.ShouldSerialize;
                if (propertyShouldSerialize != null)
                {
                    var shouldSerialize = contractProperty.ShouldSerialize.Invoke(null);
                    Console.WriteLine($"Should serialize: {shouldSerialize}");
                }
            }

Internal:
var someClassType = typeof(SomeClass);
            var memberInfo = someClassType.GetMember("EnumValue");
            var predicate = CreateShouldSerializeTest(memberInfo[0]);
            Console.WriteLine(predicate(null));

**Comment by dbc2** [comment]
I don't think you are calling the [`ShouldSerialize`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_ShouldSerialize.htm) predicate correctly.  It takes an *instance of the containing object* not the *property value*, and so should never get called with `null`.  Thus you should call it like so:

    contractProperty.ShouldSerialize.Invoke(new SomeClass());

(As [`ShouldSerialize`](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm#ShouldSerialize) is intented to be an instance method, the first (and only) argument to the predicate is the instance itself.)

**Comment by ddrdoubled** [comment]
Hi dbc2, thank you very much. It was not me :-) please see: https://github.com/RSuter/NJsonSchema/issues/929 
Thank you very much anyway, highly appreciated
