### ISSUE TITLE
JsonObjectAttribute.Id - What can it be used for?

### ISSUE THREAD

**Issue by sujayvsarma** [JamesNK/Newtonsoft.Json#2023]
The documentation simply states that it is inherited via the Container object. But it does not say what we can or cannot set this to. 

For example, what might be the side-effects of doing this:
```
[JsonObject( "fooObject", **Id = "hello"** )]
public class FooObject {
```

Am I supposed to use the Id property to point to a property/field name that behaves as the object's "Id" ? Or should this be set to a literal value?

**Comment by JamesNK** [comment]
It was used by JsonSchemaGenerator but that is deprecated.

**Comment by xmedeko** [comment]
Is it used by the Json.NET Schema currently? See this [SO answer](https://stackoverflow.com/a/59549224/254109)
