### ISSUE TITLE
Computed properties are serialized

### ISSUE THREAD

**Issue by bender2k14** [JamesNK/Newtonsoft.Json#2037]
I was surprised to realize that computed (i.e. get-only) properties are serialized.  Since such properties are read only, I was expecting that they would not be serialized.

Specifically, I was expecting that this test would pass.

```using Newtonsoft.Json;
using Xunit;
namespace TestNamespace {
  public class NoData { }
  public class NoDataAndGetOnlyProperty {
    public int CompuatedProperty => 0;
  }
  public class Tests {
    [Fact] // fails
    public void Serialize_NoData_And_NoDataAndGetOnlyProperty() {
      var expected = JsonConvert.SerializeObject(new NoData());                 // {}
      var actual = JsonConvert.SerializeObject(new NoDataAndGetOnlyProperty()); // {"CompuatedProperty":0}
      Assert.Equal(expected, actual);
    }
  }
}
```

Is this the intended behavior or a bug?

**Comment by dbc2** [comment]
This is intended behavior.  From https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Objects

 > By default a type's properties are serialized in opt-out mode. What that means is that **all public fields and properties with getters** are automatically serialized to JSON, and fields and properties that shouldn't be serialized are opted-out by placing JsonIgnoreAttribute on them. To serialize private members, the JsonPropertyAttribute can be placed on private fields and properties.

There is no documented restriction that the members must also have setters.

If you want to only serialize read/write members, you can do so with a custom contract resolver.  See e.g. [Is there a way to ignore get-only properties in Json.NET without using JsonIgnore attributes?](https://stackoverflow.com/q/18543482/3744182).
