### ISSUE TITLE
JToken.DeepEquals fails for JToken with TimeSpan, when converted to string and back

### ISSUE THREAD

**Issue by makotech222** [JamesNK/Newtonsoft.Json#2047]
### Source/destination types

```csharp
JToken t1 = JToken.FromObject(new { ts = new TimeSpan(0) });
JToken t2 = JToken.Parse(t1.ToString());
JToken.DeepEquals(t1, t2) == false
```
### Expected behavior

t1 and t2 should be equal

### Actual behavior

They are not equal, because when re-parsing to JToken, the TimeSpan gets switched to a String type.

Use case for this is writing unit tests. I have a complicated object with a lot of properties, which I convert from JToken to string, and store that in code. When the test runs, I parse the string to JToken as the expected value, and JTokenize the testing object, then compare with DeepEquals. This fails if one of the properties is a TimeSpan.

This may or may not be considered a bug, since it's probably not too easy to determine if the string is a TimeSpan or not, but perhaps DeepEquals can be customized somehow to handle this situation and others like it?

**Comment by JamesNK** [comment]
That's a known limitation. All JSON sees is a string. If you want to keep the type you will need to serialize/deserialize a .NET class. In that case the serialize knows you want a TimeSpan and will convert the string value to a TimeSpan.
