### ISSUE TITLE
Allow to serialize decimal property (and other number base primitive type) with double quote.

### ISSUE THREAD

**Issue by nmonet** [JamesNK/Newtonsoft.Json#206]
I would like to serialize an object with a decimal property to a json result with double quote (like below) and I think it is not "easily" possible in Json.Net.
Exemple : 

``` C#:
var obj = new { Id = 4, Decimal = 5.4m, Float = 45.689f, Double = 489.45d, Str = "String", Char = 'c' };
```

serialized to : 

``` JSON
{"Id":"4","Decimal":"5.4","Float":"45.689","Double":"489.45","Str":"String","Char":"c"}
```

instead of :

``` JSON
{"Id":4,"Decimal":5.4,"Float":45.689,"Double":489.45,"Str":"String","Char":"c"}
```

OData protocol uses this "specification" for decimal and number. See here : http://blogs.msdn.com/b/marcelolr/archive/2010/07/15/odata-decimal-and-json.aspx and here http://www.odata.org/documentation/odata-v2-documentation/json-format/#PrimitiveTypes

**Comment by Bouke** [comment]
I've created a JsonConverter to do this, see [my StringDecimalConverter gist](https://gist.github.com/Bouke/aa00f3952e9690223f51).
