### ISSUE TITLE
JsonConvert.DeserializeObject<MyClass> doesn't throw an exception when deserializing a completely different json that has no properties from the desired class

### ISSUE THREAD

**Issue by michaldivis** [JamesNK/Newtonsoft.Json#2080]
Hi,
I've come across a problem with JsonConvert.DeserializeObject<> recently. I have a class called ServerResponse for one kind of response I'm supposed to get from a web service, however, the web service can output another kind of response in case of an error (authentication error in this case). The problem is, that when I try to deserialize the error JSON, it still creates an instance of my ServerResponse class, which is not desirable (I hope). Maybe there is a setting I missed, but I didn't find any useful one for this kind of a problem.
### Source/destination types

```csharp
class ServerResponse{
    public int MinSupportedVersion {get;set;}
}
```

### Source/destination JSON

```javascript
{"error":true,"error_weight":200,"error_code":"USER_IS_NOT_LOGGED"}
```

### Expected behavior

I would expect the JsonConvert.DeserializeObject<ServerResponse>(json) to throw an Exception

### Actual behavior

The deserialize method creates a new instance of ServerResponse with default MinSupportedVersion value (0)

### Steps to reproduce

```csharp
var json = "{\"error\":true,\"error_weight\":200,\"error_code\":\"USER_IS_NOT_LOGGED\"}"; 
//I have a http client request here, that gets me this exact JSON
var result = JsonConvert.DeserializeObject<ServerResponse>(json);
```

**Comment by someone-with-default-username** [comment]
If there are any mandatory properties you have to annotate them with `JsonPropertyAttribute`  attribute, so exceptions will be thrown.

**Comment by michaldivis** [comment]
Thank you. I actually had it annotated before (forgot to include the attribute in the source type here), but once I added the Required = Required.Always to the attribute, it started throwing an exception just as I needed. Thank you again.
