### ISSUE TITLE
EnumMember attribute ignored by StringEnumConvertor if CamelCaseText = true

### ISSUE THREAD

**Issue by wizofaus** [JamesNK/Newtonsoft.Json#2082]
Using

```
new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver(), Converters = new[] { new StringEnumConverter { CamelCaseText = true } }
        }
```
I get enum values converted to "camelCase" strings as expected, even though the actual enum fields in the C# definition are PascalCase.

But in some cases I need to override the default name, and normally `[EnumMember(Value="UPPER_CASE_NAME")]` does the trick - but not when CamelCaseText is true.
As such I wrote my own resolver that overrides WriteJson and checks for the attribute itself, but is this really the expected behaviour, and if so, is there a case for having a way of overriding it?

**Comment by wizofaus** [comment]
BTW I've confirmed this problem is still in the latest version of Json.NET - even though CamelCaseNamingStrategy has a property "OverrideSpecifiedNames" which can be set via the constructor (and defaults to false), it completely ignores this property when resolving.

**Comment by JamesNK** [comment]
Thanks for the investigation. Fixed.

**Comment by wizofaus** [comment]
Gotta love github :-)

**Comment by bartelink** [comment]
You could just clone it? what happens if you change to a different serializer?
