### ISSUE TITLE
Snake-case naming strategy incorrectly deserialises JSONPath dictionary keys

### ISSUE THREAD

**Issue by alastairs** [JamesNK/Newtonsoft.Json#2088]
### Source/destination types

Source type (document being validated) is
```csharp
class Request
{
    IEnumerable<Foo> Foos { get; set; }
}

class Foo
{
    string Id { get; set; }
    IDictionary<string, string> Arguments { get; set; }
}
```

Destination type is [`ValidationProblemDetails`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validationproblemdetails?view=aspnetcore-2.2) and more specifically [`ModelStateDictionary`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary?view=aspnetcore-2.2).

### Source/destination JSON

Source (document being validated)
```json
{
  "foos": [
    {
      "id": "my.id",
      "arguments": {
        "bar": ""
      }
    },
    {
      "id": "my.other.id",
      "arguments": {
        "foo": "true",
        "baz": "123"
      }
    },
    {
      "id": "my.third.id",
      "arguments": {
        "qux": "ldjf"
      }
    }
  ]
}
```

Result (serialised `ValidateProblemDetails`):
```json
{
  "errors": {
    "foos[0]._arguments.bar": [
      "The argument has no value."
    ]
  },
  "title": "One or more validation errors occurred.",
  "status": 422
}
```

### Expected behavior

The JSONPath should be valid for the supplied document, i.e. `foos[0].arguments.bar`.

### Actual behavior

The JSONPath includes an invalid underscore prefix to `arguments`: `foos[0]._arguments.bar`. Adding `[JsonProperty("arguments")]` to that property has no effect. Similarly, the camel case naming strategy capitalises the a of arguments: `foos[0].Arguments.bar`.

### Steps to reproduce

In an ASP.NET Core MVC 2.2 app, add the following configuration:
```csharp
services.AddJsonOptions(options =>
{
    options.SerializerSettings.ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy
        {
            ProcessDictionaryKeys = true
        }
    };
})
```

I believe that the use of `ProcessDictionaryKeys` is correct here, as without that specified the result is `Foos[2].Arguments.bar`.

**Comment by dbc2** [comment]
I'm not sure there's any formal definition of what a snake case (or camel case) transformation *should* do for any possible sequence of Unicode characters, so I'm not sure whether this can be considered a bug in Json.NET.  (Love to know if such a formal definition exists somewhere though.)

As a workaround, you could use `PiecewiseNamingStrategy` from [this answer](https://stackoverflow.com/a/54384860/3744182) to [How to use JSON.Net CamelCasePropertyNamesContractResolver with dot separated names?](https://stackoverflow.com/q/54308041/3744182) to snake-case each individual portion of the dictionary keys:

    options.SerializerSettings.ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = PiecewiseNamingStrategy(new SnakeCaseNamingStrategy())
        {
            ProcessDictionaryKeys = true
        }
    };

That question is also specifically `ModelStateDictionary`.

**Comment by JamesNK** [comment]
There is no formal spec for how to do snake case. Or camel case.

You have two options here: set ProcessDictionaryKeys to false, or implement your own naming strategy. It's pretty self contained and simple to implement.

**Comment by alastairs** [comment]
@dbc2 @JamesNK Thank you so much for your replies. It sounds like the piecewise naming strategy is the approach we'll need to take; turning off `ProcessDictionaryKeys`, as far as I could tell, didn't resolve the issue.
