### ISSUE TITLE
JsonSerializer.Populate( jArray.CreateReader(), array ) doesn't fill array

### ISSUE THREAD

**Issue by Deni35** [JamesNK/Newtonsoft.Json#2094]
```
var jarray = JArray.Parse( "[ 0, 1, 2 ]" );
var serializer = new JsonSerializer();
var array = new int[3];
serializer.Populate( jarray.CreateReader(), array );
```
As a result `array` is {0, 0, 0}.

**Comment by DapremeeA** [comment]
Have you found the solution for this ? 
I am having the same issue right now..

**Comment by JamesNK** [comment]
That's expected behavior. Json.NET will only ever add items to a collection. An array is fixed size so nothing can be added to it.
