### ISSUE TITLE
CamelCaseResolver messing with upper case string containing underscore

### ISSUE THREAD

**Issue by L3Z4** [JamesNK/Newtonsoft.Json#2098]
### Expected behavior
The `ToCamelCase` method from `StringUtils` helper should handle all upper text containing underscore characters.
```csharp
Assert.AreEqual("UPPER_CASE", StringUtils.ToCamelCase("UPPER_CASE"));
```
### Actual behavior
This method incorrectly produce `uppeR_CASE`

I would like to solve this issue myself, but I do not know how to build the solution.

**Comment by bartelink** [comment]
What are you suggesting the result should actually be? `upper_Case`?  `upper_case`? I don't get how `UPPER_CASE` could be considered camel case ?

**Comment by L3Z4** [comment]
Checking the "rules" [here ](https://en.wikipedia.org/wiki/Camel_case) and [here ](http://wiki.c2.com/?CamelCase), we use lower Camel Case. Therefore, many unit tests are invalid. They expect spaces, not only letter, or multiple capitalized letters following each others.
UPPER_CASE should be upperCase in lower Camel Case.

This fix will change the way it works before. How should I handle it ?

**Comment by JamesNK** [comment]
This isn't a bug. The resolver assumes you are starting with pascal case and are going to camel case.

You will need to write your own NamingStrategy implementation that supports your initial standard.

**Comment by L3Z4** [comment]
Ok, not a bug !
Anyway, I have written some code in the unit test class to use TestCase. I will make a pull request about it.
