### ISSUE TITLE
$id doesn't round trip when deserializing with default options

### ISSUE THREAD

**Issue by johngallardo** [JamesNK/Newtonsoft.Json#2108]
### Source/destination types

```csharp
    public class Test
    {
        [JsonProperty(PropertyName ="$id")]
        [JsonRequired]
        public string Id { get; set; }
    }

```

### Source/destination JSON

```javascript
{"$id":"abc"}
```

### Expected behavior

```csharp
obj.ToObject<Test>();
```
Should create an instance of Test with the Id property having a value of "abc".

### Actual behavior

The object fails to deserialize due to a missing $id property.
Newtonsoft.Json.JsonSerializationException: Required property '$id' not found in JSON

### Steps to reproduce

```csharp
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using System;

namespace ConsoleApp7
{
    public class Test
    {
        [JsonProperty(PropertyName ="$id")]
        [JsonRequired]
        public string Id { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var foo = new Test();
            foo.Id = "abc";

            var json = JsonConvert.SerializeObject(foo);
            Console.WriteLine(json);

            var obj = JObject.Parse(json);

            // Succeeds
            var roundTripped = obj.ToObject<Test>(new JsonSerializer()
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore
            });

            // Throws
            try
            {
                _ = obj.ToObject<Test>();
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}

```

**Comment by JamesNK** [comment]
You need to set https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_MetadataPropertyHandling.htm to Ignored.

**Comment by johngallardo** [comment]
I get that one can use MetadataPropertyHandling.Ignore. However this makes it hard to have a $id field be:

1) Defined by the implementation, e.g. maybe it makes sense for the $id to be the actual entity identifier in the backing store.
2) Consumed by applications in a way which allows the data in $id to serve the purpose of object reassembly via $ref in addition to being available in the deserialized object.

Is there a mode that allows both of the above uses?
