### ISSUE TITLE
Typo in blog article: "WCF DataContractJsonSerializer"

### ISSUE THREAD

**Issue by DaveInCaz** [JamesNK/Newtonsoft.Json#2110]
In the blog article:
http://james.newtonking.com/archive/2010/02/07/json-net-performance-with-binary-data

In the final paragraph it says:

> "Finally as you can see the WCF DataContractJsonSerializer is by far the least efficient."

But I think this is a typo and "WCF JsonSerializer" was meant instead. There doesn't appear to be anything called "WCF DataContractJsonSerializer".

I couldn't find any other means to report this (quite minor) issue. But since that blog is somewhat of a documentation source for JSON.NET I thought mentioning it here would be OK.

Thanks

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.json.datacontractjsonserializer?view=netframework-4.8

?

**Comment by DaveInCaz** [comment]
My description maybe wasn't clear enough. What I meant was that the text & the chart seem to refer to slightly different sets of libraries...

The text includes the following:

- Json.NET
- DataContractSerializer
- Json.NET BSON 
- BinaryFormatter 
- WCF DataContractJsonSerializer (*)
- WCF JsonSerializer

The chart includes:
- Json.NET
- DataContractSerializer
- Json.NET BSON 
- BinaryFormatter 
- DataContractSerializer (*)
- WCF JsonSerializer

The ones with the (*) seem to be discrepancies.

**Comment by JamesNK** [comment]
Ehhh, it's almost 10 years old. I don't care enough to change it.
