### ISSUE TITLE
How to get rid of dll next to executable file?

### ISSUE THREAD

**Issue by SilverSilencer** [JamesNK/Newtonsoft.Json#2117]
I have Newtonsoft.Json at my References and when I compile my app it creates Newtonsoft.Json.dll next to my executable app. Is there any way to prevent this and include it just in main app, so that I don't need to have the dll next to this app?

**Comment by bartelink** [comment]
search for ILMerge or ILRepack - this is a generic question that's likely best asked on StackOverflow - i.e. its not a problem specific to json.net
