### ISSUE TITLE
Classes implementing IEnumerable are not serialized properly

### ISSUE THREAD

**Issue by sandimschuh** [JamesNK/Newtonsoft.Json#2121]
I have to serialize some classes from a vendor I can not change. Some of these types implement IEnumerable<T>. For these types, only the enumeration is serialized. All other class members are not serialized.

What can I do to make these classes completely serialized?

I mimicked this case with simple classes in a unit test.

### Classes to be serialized

```csharp
class Foo : IEnumerable<FooItem>
{
	public IList<BarItem> BarItems { get; set; }
	public IList<FooItem> FooItems { get; set; }
	public string Name { get; set; }

	public IEnumerator<FooItem> GetEnumerator()
	{
		return FooItems.GetEnumerator();
	}

	IEnumerator IEnumerable.GetEnumerator()
	{
		return FooItems.GetEnumerator();
	}
}

class FooItem
{
	public string Name { get; set; }
}

class BarItem
{
	public string Name { get; set; }
}
```

### Resulting JSON

```javascript
[
  {
    "Name": "Foo Item 1"
  },
  {
    "Name": "Foo Item 2"
  }
]
```

### Expected behavior

I expected all Foo members to be serialized.

### Actual behavior

Only the IEnumerable<FooItem> has been serialized. All the other members were not serialized.

### Steps to reproduce

```csharp
// arrange
var jsonSettings = new JsonSerializerSettings
{
	Formatting = Formatting.Indented,
	ReferenceLoopHandling = ReferenceLoopHandling.Serialize
};
var fooItems = new List<FooItem> {
	new FooItem { Name = "Foo Item 1" },
	new FooItem { Name = "Foo Item 2" }
};
var barItems = new List<BarItem> {
	new BarItem { Name = "Bar Item 1" },
	new BarItem { Name = "Bar Item 2" }
};
var foo = new Foo
{
	Name = "My Name is Foo",
	FooItems = fooItems,
	BarItems = barItems
};

// act
var json = JsonConvert.SerializeObject(foo, jsonSettings);

// assert
```

**Comment by TylerBrinkley** [comment]
Since you can't change the class I'd suggest recreating the class and and add the `JsonObjectAttribute` to the class which will then serialize and deserialize as you expect. The only other thing you could do is create a custom `IContractResolver` and ensure it handles this class as an object instead of an array.

**Comment by JamesNK** [comment]
You could inherit from DefaultContractResolver and force that type to be serialized as an object.

**Comment by mouaddjedidi** [comment]
@JamesNK Could you please provide un example on how to force the type to be serialized as an object using DefaultContractResolver

**Comment by patriksvensson** [comment]
@JamesNK I would also want to know how to make a class implementing `IEnumerable<T>` to be serialized as an object using a contract serializer 👍
