### ISSUE TITLE
JObject should implement non-generic IDictionary

### ISSUE THREAD

**Issue by oliverjanik** [JamesNK/Newtonsoft.Json#2123]
Like any good dictionary please implement IDictionary interface.

This is beneficial for general dump type situations. Say dumping a value of an object into a log file.

Testing for IDictionary is easy and helps dumping solutions to access members more easily.

At the moment they have to deal with with testing for generic `typeof(IDictionary<,>)` and use reflection to access values.

**Comment by JamesNK** [comment]
> Like any good dictionary please implement IDictionary interface.

Lots of dictionaries don't implement `IDictionary`. I don't want to add methods that take object to JObject.

**Comment by oliverjanik** [comment]
Which ones? I only know of JObject
