### ISSUE TITLE
System.Uri does not round trip properly when original string is UNC path

### ISSUE THREAD

**Issue by joelverhagen** [JamesNK/Newtonsoft.Json#2128]
Consider a path in this form:
```
//fileserver/Framework/NuGet/server.png
```

This is parsable by `System.Uri` constructor. In fact, it is parseable with any of the `UriKind` values. My understanding is that `Uri` should round trip safely through JSON serialization and deserialization. If this is a bad assumption, perhaps this should be called out in the documentation (or... maybe I missed it).

With the following bit of code, you can see that the `Uri` become relative after a round trip.

```csharp
using System;
using Newtonsoft.Json;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var before = new Uri("//fileserver/Framework/NuGet/server.png", UriKind.Absolute);
            Console.WriteLine("IsAbsoluteUri: " + before.IsAbsoluteUri);
            var json = JsonConvert.SerializeObject(before);
            Console.WriteLine("JSON: " + json);
            var after = JsonConvert.DeserializeObject<Uri>(json);
            Console.WriteLine("IsAbsoluteUri: " + after.IsAbsoluteUri);
        }
    }
}
```

Output:
```
IsAbsoluteUri: True
JSON: "//fileserver/Framework/NuGet/server.png"
IsAbsoluteUri: False
```

I think the crux of the issue is that a UNC path like this works on all forms of the `Uri` contrustor:
```csharp
new Uri(value);
new Uri(value, UriKind.Absolute);
new Uri(value, UriKind.RelativeOrAbsolute);
new Uri(value, UriKind.Relative);
```

... meaning this sort of string is kind of ambiguous given then following parse line:
https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs#L478

**Comment by TylerLeonhardt** [comment]
This also seems to happen on non-Windows file paths. I see the same behavior with a macOS path:

Here's a PowerShell example:
```pwsh
[Newtonsoft.Json.Linq.JObject]::FromObject(
    [hashtable]@{
        Uri = ([Uri]::new("/Users/tyler/Code/PowerShell/vscode/PowerShellEditorServices/test/PowerShellEditorServices.Test.E2E/bin/Debug/netcoreapp2.1/0b0jnxg2.kgh.ps1"))
    },
    [Newtonsoft.Json.JsonSerializer]::new())
.ToString()

# yields:
{
  "Uri": "/Users/tyler/Code/PowerShell/vscode/PowerShellEditorServices/test/PowerShellEditorServices.Test.E2E/bin/Debug/netcoreapp2.1/0b0jnxg2.kgh.ps1"
}
```

**Comment by JamesNK** [comment]
I don't see a fix here that would work for everyone. What you could do is write a JsonConverter that always uses `new Uri(s, UriKind.Absolute);` to get the result you want.

**Comment by TylerLeonhardt** [comment]
The thing I find odd is that, if I do:

```
new Uri("/Users/tyler/Code/PowerShell/vscode/PowerShellEditorServices/test/PowerShellEditorServices.Test.E2E/bin/Debug/netcoreapp2.1/0b0jnxg2.kgh.ps1")
```

.NET knows it's an absolute path and `IsAbsolute` is true.

However, through the serialization/deserialization of Newtonsoft, it's forced to be relative.

That leads me to believe that Newtonsoft is doing something extra here rather than simply creating a new Uri using the simple constructor.

I don't know the inner working of Newtonsoft, but it seems like it's trying to force relative paths rather than leaving the decision up to .NET.

**Comment by JamesNK** [comment]
Newtonsoft.Json always uses `new Uri(s, UriKind.RelativeOrAbsolute);` because it doesn't know whether the value should be relative or absolute.

**Comment by joelverhagen** [comment]
Can this be added as a setting on `JsonSerializerSettings` like `ParseUriKind` defaulting to `RelativeOrAbsolute`? This should be backwards compatible right?

**Comment by TylerLeonhardt** [comment]
Looks like the root issue is with .NET then... because:

```pwsh
[Uri]::new("/Users/tyler/").IsAbsoluteUri

# gives you

true

# and 

[Uri]::new("/Users/tyler/", [System.UriKind]::RelativeOrAbsolute).IsAbsoluteUri

#gives you

false
```

**Comment by TylerLeonhardt** [comment]
I've opened an issue on corefx to discuss this further https://github.com/dotnet/corefx/issues/40428
