### ISSUE TITLE
Inability to order the property with a [JsonExtensionData] tag

### ISSUE THREAD

**Issue by pgolebiowski** [JamesNK/Newtonsoft.Json#2130]
### Source type

```csharp
public class Example
{
    [JsonProperty(Order = 1)]
    [JsonExtensionData]
    public JObject First { get; set; }

    [JsonProperty(Order = 2)]
    public string Second { get; set; }
}
```

### Destination JSON

```javascript
{
    "second": "blah blah",
    "first": {
        "name": "value"
    }
}
```

### Expected behavior

I want to be able to order the properties, i.e.:

```javascript
{
    "first": {
        "name": "value"
    },
    "second": "blah blah"
}
```

It seems that `[JsonProperty(Order = x)]` does not apply to a property marked with `JsonExtensionData`.

Related: https://stackoverflow.com/questions/57495387/how-to-order-properties-with-json-net-if-a-class-has-jsonextensiondata

**Comment by JamesNK** [comment]
Extension data is always last. JsonProperty doesn't have an effect because extension data isn't serialized as a property. It is its own separate thing.
