### ISSUE TITLE
Unable to run SelectTokens() on attribute that has been converted from XML to JSON using JsonConvert.SerializeXNode() due to converted attribute key containing '@' identifer

### ISSUE THREAD

**Issue by gm-sg** [JamesNK/Newtonsoft.Json#2131]
### Source/destination types

```csharp
XML -> JSON -> XML
```

### Source/destination JSON
After converting my XML file to JSON using JsonConvert.SerializeXNode()
I receive something that resembles this:
```javascript
{
"Property": [
          {
            "@Name": "x",
            "@Value": "y",
            "@Type": "FindMe"
          }
   ]
}
```

Though I am unable to properly run a SelectTokens query that resembles this:
z.SelectTokens("$..[?(@._Type ==  'FindMe')]")
due to the addition of the attribute identifier '@'

### Expected behavior
Result should yield the next set of filtered data.

### Actual behavior
SelectTokens() is unable to return expected data due to attribute identifier.

Though when I do a find and replace for '@' to '_' and modify the query, it works as expected.

I've tried to find a way to change the attribute identifier programmatically from '@' to '_' in the Json.Net documentation but have not found it if it's there. 

### Steps to reproduce

```csharp
XDocument doc = XDocument.Load(path, LoadOptions.PreserveWhitespace);
var jsonC = JsonConvert.SerializeXNode(doc);
JObject jObject = JObject.Parse(jsonC);
jObject.SelectTokens("$..[?(@.@Type ==  'FindMe')]")
```

**Comment by JamesNK** [comment]
`SelectTokens("$..[?(@.['@Type'] == 'FindMe')]")`
