### ISSUE TITLE
JToken.ToString() does not always return JSON

### ISSUE THREAD

**Issue by logiclrd** [JamesNK/Newtonsoft.Json#2144]
### Description

The `JToken` type has a `ToString` overload that is documented as:

> Returns the indented JSON for this token.

For most `JToken` values this is true, such as simple numbers, booleans, `JArray` and `JObject` values. But, a `JToken` that contains a string literal returns the string itself, not a JSON representation of the string. Specifically, based on the documentation, I would _expect_ that you can take what `JToken.ToString` returns and pass it back into `JToken.Parse` and get more or less an equivalent `JToken` object. I am basing my reproduction on this assumption.

I suspect that when this was first written, it might have been reasonable to consider this an oversight in the implementation of `JValue` and fix it there. However, I imagine today there are millions of lines of code that assume `ToString` on a string `JToken` gives you back the raw string. Therefore, I think this needs to be considered a bug in the documentation at this point.

### Steps to reproduce

    var stringValue = "Test string.";

    JToken stringToken = new JValue(stringValue);

    var jsonForString = stringToken.ToString(); // per documentation this should be true, JValue is breaking the contract it inherits from its base class

    var equivalentStringToken = JToken.Parse(stringToken.ToString());

### Expected behavior

`jsonForString` should contain the value `"Test string."` (including double quotes)
`equivalentStringToken` should be a `JValue` whose string content is the string `Test string.`

### Actual behavior

`jsonForString` is given the value `Test string.` (no double quotes)
`JToken.Parse` throws a `JsonReaderException` instead of producing an object to assign to `equivalentStringToken`

**Comment by logiclrd** [comment]
Work-around: `JToken` has another overload of `ToString`:

    public string ToString(
    	Formatting formatting,
    	params JsonConverter[] converters
    )

This overload will always return JSON.

**Comment by JamesNK** [comment]
That's intended behavior. I've updated the docs - https://github.com/JamesNK/Newtonsoft.Json/commit/c5f210347055c43970199d4611993200d00977fd

**Comment by andyolivares** [comment]
First of all, great library and excellent work, but...

I've been banging my head for 2 days trying to figure this out. I really don't see the point of overriding ToString() on JValue to behave differently than all other JToken descendants.

```csharp
var jToken = JToken.Parse("\"hello world\"");
var json = jToken.ToString();
```

Something like the above leads to think that what you would get from that last ToString() call is the JSON representation of the JToken you just parsed. I now know that's not true, but at least that's what happens with JObject, JArray, and _most_ JValue's.

What is the rationale behind the "intended behavior" with JValue's ToString to do different when the JValue is of Type=String?

If JToken and it's descendants are meant to represent a JSON value/object/array/etc, why would you need to get .NET string representation of inner value when calling ToString instead of actual JSON value?

In that case, wouldn't it be cleaner to purposely call JValue's Value.ToString() if that is the intention?

Thank you!

**Comment by logiclrd** [comment]
My interpretation of this is that it is no longer important whether a string `JValue` was originally intended to return an encoded or unencoded string from `.ToString()`. The problem is that the library has been around for many years and I'm certain _many_ people have written code that depends on `.ToString()`ing a string `JValue`. If indeed it is a bug that `.ToString()` didn't return an encoded JSON string, well, it can't be fixed now without breaking tons of users' code. So, instead, the "fix" to bring the code and the contract into alignment must be to alter the contract, as unsatisfying as it is. The presence of a clear work-around means that you _can_ write code that depends on the behaviour the contract used to guarantee -- you just have to call a slightly different overload.

The work-around I suggested and the work-around added to the documentation both take a `converters` parameter, but it is a `params` parameter; it is valid syntax to supply no arguments for it. To get the alternate `JToken.ToString()` overload, thus, all you need to supply is one of the `Formatting` enum values.

The documentation suggests using `WriteTo()` to get the JSON. The `JToken.ToString()` overload that I suggested as a work-around just creates an in-memory buffer and calls `WriteTo`, so it amounts to the same thing.

```
  var x = new JValue("string value");

  var a = x.ToString(); // "string value"
  var b = x.ToString(Formatting.Indented); // "\"string value\""

  // And this is effectively what's going on behind the scenes of the calculation of 'b':
  var buffer = new StringWriter();
  var writer = new JsonTextWriter(buffer);

  writer.Formatting = ...; // (same value as passed into .ToString())

  x.WriteTo(new JsonTextWriter(buffer));

  var c = buffer.ToString(); // "\"string value\""
```

Using this `JToken.ToString` overload means that _any_ `JToken` value will be converted to a JSON representation, providing a generalized "Get me the JSON string" method.

Note that if you're just going to take that string and write it to a stream, you _should_ use `WriteTo` instead and avoid the intermediate string representation.
