### ISSUE TITLE
Changelog for 12.0.3-beta1?

### ISSUE THREAD

**Issue by MagicAndre1981** [JamesNK/Newtonsoft.Json#2147]
On Nuget we can find the version [12.0.3-beta1](https://www.nuget.org/packages/Newtonsoft.Json/12.0.3-beta1) if we include prerelease versions while checking for nuget updates.

I see no tag/release here, so what is changed/new for this version?

**Comment by JamesNK** [comment]
I don't make official releases for betas. Look at the commit log. It will be whatever was between the last tag and the pre-release.

**Comment by MagicAndre1981** [comment]
>  Look at the commit log. It will be whatever was between the last tag and the pre-release.

ok, took some time to get the link:

https://github.com/JamesNK/Newtonsoft.Json/compare/12.0.2...release/12.0.3
