### ISSUE TITLE
`CollectionUtils.ArrayEmpty<T>()` should be update for netcoreapp3.0

### ISSUE THREAD

**Issue by yyjdelete** [JamesNK/Newtonsoft.Json#2150]
Related to #2137, #2034 

Found this while try to debug #2148, it make all unit-test stops with `Process terminated. Assertion failed.` when hit the assert for Debug builds in netcoreapp3.0.
According to the assert and comments in `CollectionUtils.ArrayEmpty<T>()`, it should also be update to use `Array.Empty<T>()` for new platforms(maybe for `netstandard1.3` and `netstandard2.0`), since `netcoreapp3.0` switch to return `EmptyPartition<T>` now.

https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Utilities/CollectionUtils.cs#L369-L390

**Comment by JamesNK** [comment]
Thanks for reporting this. It is already fixed and will be in the next release - https://github.com/JamesNK/Newtonsoft.Json/commit/d75074f30c1c65d9101c11aec2ac4273d07b2fa4
