### ISSUE TITLE
Issue with Installing Newtonsoft

### ISSUE THREAD

**Issue by emrekilic3** [JamesNK/Newtonsoft.Json#2152]
**Hello,

I'm getting the error below when trying to install Newtonsoft.

PS: I use Visual Studio 2019**

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 5.2.0.6090

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package Newtonsoft.Json

Attempting to gather dependency information for package 'Newtonsoft.Json.12.0.2' with respect to project 'Client', targeting 'native,Version=v0.0'
Gathering dependency information took 9,71 ms
Attempting to resolve dependencies for package 'Newtonsoft.Json.12.0.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.12.0.2'
Resolved actions to install package 'Newtonsoft.Json.12.0.2'
Retrieving package 'Newtonsoft.Json 12.0.2' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.2/newtonsoft.json.12.0.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.2/newtonsoft.json.12.0.2.nupkg 100ms
Installing Newtonsoft.Json 12.0.2.
Install failed. Rolling back...
Package 'Newtonsoft.Json.12.0.2' does not exist in project 'Client'
Package 'Newtonsoft.Json.12.0.2' does not exist in folder 'C:\Users\emrek\Desktop\UDP\packages'
Executing nuget actions took 7,9 sec
Install-Package : Could not install package 'Newtonsoft.Json 12.0.2'. You are trying to install this package into a project that tar
gets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Newtonsoft.Json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:09.9875799
PM>

**Comment by JamesNK** [comment]
I don't know your native target is but Newtonsoft.Json doesn't support it.

If you think your platform should be supported then it is a bug with NuGet. I suggest you raise the issue with them.
