### ISSUE TITLE
JSONPath with bracket-notation and descendant axis returns more tokens than expected

### ISSUE THREAD

**Issue by Viorel** [JamesNK/Newtonsoft.Json#2156]
### Source JSON

```javascript
{
    "root": {
        "a": {
            "name": "John",
            "b": {
                "name": "Sarah"
            }
        }
    }
}
```

### Expected behavior

Using _SelectToken_ with JSONPath, I want to search for “a” recursively, then get the “name” non-recursively. I expect to find a single token: the “name” node, which is an immediate child of “a”.

### Actual behavior

When I use the dot-notation — “$..a.name” — it returns correctly the “name” token, which is a child of “a”.

However, when I use the alternative bracket-notation — “$..['a']['name']” — it returns both of the “name” tokens. The second “name” should not be returned, because it is not an immediate child of “a”.

### Steps to reproduce

```csharp
// In C Sharp, in a console application,
// using Newtonsoft.Json 12.0.2 and .NET Framework 4.8.

string json = @"
        {
            ""root"": {
                ""a"": {
                    ""name"": ""John"",
                    ""b"": {
                        ""name"": ""Sarah""
                    }
                }
            }
        }                 
        ";

JToken t = JToken.Parse( json );

int count1 = t.SelectTokens( "$..a.name" ).Count(); // result: 1, expected: 1
int count2 = t.SelectTokens( "$..['a']['name']" ).Count(); // result: 2, expected: 1


```

**Comment by JamesNK** [comment]
Thanks for the good repro. Fixed.
