### ISSUE TITLE
Add a KebabCaseNamingStrategy

### ISSUE THREAD

**Issue by DanVicarel** [JamesNK/Newtonsoft.Json#2160]
No idea how I'm the first person to request this...but can we please get a `KebabCaseNamingStrategy`? Requests sent to Apple Push Notification Service [require kebab-case](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943360) JSON fields...I'm sure there are other examples out there.

### Source types

```cs
[JsonObject(NamingStrategyType = typeof(KebabCaseNamingStrategy))]
public class MyType
{
    public string SomeString { get; set; }
    public bool SomeBool { get; set; }
    public int SomeInt { get; set; }
}
```

### Destination JSON

```javascript
{
  "some-string":"some string",
  "some-bool": true,
  "some-int": 5,
}
```

### Expected behavior

This would be possible

### Actual behavior

It's not, unless I derive from `NamingStrategy` myself, like one of [these](https://gist.github.com/amilos/9ec30c60bc50b40bf0cfabb8fdec4966) [examples](https://gist.github.com/duruld/a67a80f05cb610fd39f6c2e6ad03844d) on the internets.

**Comment by mattzink** [comment]
What would `IPAddress` and `OSName` return?

**Comment by DanVicarel** [comment]
Looking at similar test cases in [PR #2161](https://github.com/JamesNK/Newtonsoft.Json/pull/2161/files#diff-50bf7c16816e2a80649261c839530cc9R118), it looks like they will return `ip-address` and `os-name`, respectively.

**Comment by JamesNK** [comment]
Done.

**Comment by DanVicarel** [comment]
Wow, fantastic turnaround time. Thanks @TylerBrinkley and @JamesNK!
