### ISSUE TITLE
Trailing zeros are removed after parse & format

### ISSUE THREAD

**Issue by caioproiete** [JamesNK/Newtonsoft.Json#2162]
I'm using [**JSON .NET v12.0.2**](https://www.nuget.org/packages/Newtonsoft.Json/12.0.2) to "_beautify_" minified JSON tokens that are being written to a store by multiple applications. Sometimes these tokens have numbers with one or more trailing zeros, for example: `{"x":100.50,"y":200.400}`. The trailing zeros are removed in the indented JSON token.

I'm assuming this is caused by numbers being parsed to `decimal` and the information is being lost.

Is there any workaround?

### Expected behavior

```json
Minified:
{"x":100.50,"y":200.400}

Indented:
{
  "x": 100.50,
  "y": 200.400
}
```

### Actual behavior

```json
Minified:
{"x":100.50,"y":200.400}

Indented:
{
  "x": 100.5,
  "y": 200.4
}
```

### Steps to reproduce

```csharp
var jsonStringMinified = @"{""x"":100.50,""y"":200.400}";

var parsedJson = JToken.Parse(jsonStringMinified);
var jsonStringIndented = parsedJson.ToString(Newtonsoft.Json.Formatting.Indented);

Console.WriteLine("Minified:");
Console.WriteLine(jsonStringMinified);
Console.WriteLine();
Console.WriteLine("Indented:");
Console.WriteLine(jsonStringIndented);
```

Seems to be related to #1884 and #1367.

**Comment by TylerBrinkley** [comment]
You need to specify the `FloatParseHandling` as `Decimal` when parsing to a `JToken` as by default your floating point numbers are being parsed as `double`s.

**Comment by caioproiete** [comment]
Thanks @TylerBrinkley. Your reply pointed me in the right direction.

Unfortunately it is not possible to specify `FloatParseHandling`  when using `JToken.Parse`, as [it does not expose a way for configuring settings on the `JsonTextReader` that it creates internally](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JToken.cs#L2197).

[![image](https://user-images.githubusercontent.com/177608/64990690-aa9b8380-d8a6-11e9-8e0d-23b37356cf96.png)](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JToken.cs#L2197)

---

However, I can just use `JsonTextReader` directly to read the JSON file (as per the screenshot above), instead of using `JsonToken.Parse`, and that is an acceptable workaround.

**Comment by TylerBrinkley** [comment]
You can also use `JsonConvert.DeserializeObject<JToken>(json, new JsonSerializerSettings { FloatParseHandling = FloatParseHandling.Decimal })` instead of `JToken.Parse` if that's easier.
