### ISSUE TITLE
SerializeObjectInternal has a memory leak

### ISSUE THREAD

**Issue by CXTjuan** [JamesNK/Newtonsoft.Json#2207]
I believe that SerializeObjectInternal is causing a memory leak.  This appears in the 12.0.2 source code.  I did not do a search for other instances of StringWriter.

Here is how it is currently written:

`// Newtonsoft.Json.JsonConvert
private static string SerializeObjectInternal(object value, Type type, JsonSerializer jsonSerializer)
{
	StringWriter stringWriter = new StringWriter(new StringBuilder(256), CultureInfo.InvariantCulture);
	using (JsonTextWriter jsonTextWriter = new JsonTextWriter(stringWriter))
	{
		jsonTextWriter.Formatting = jsonSerializer.Formatting;
		jsonSerializer.Serialize(jsonTextWriter, value, type);
	}
	return stringWriter.ToString();
}
`

I believe that the StringWriter object should be enclosed within a using statement like this:

`// Newtonsoft.Json.JsonConvert
private static string SerializeObjectInternal(object value, Type type, JsonSerializer jsonSerializer)
{
	string result;
	using(StringWriter stringWriter = new StringWriter(new StringBuilder(256), CultureInfo.InvariantCulture))
	{
		using (JsonTextWriter jsonTextWriter = new JsonTextWriter(stringWriter))
		{
			jsonTextWriter.Formatting = jsonSerializer.Formatting;
			jsonSerializer.Serialize(jsonTextWriter, value, type);
			result = stringWriter.ToString();
		}
	}
	return result;
}`

NOTE:  I did a search through code for StringWriter, StringReader and MemoryStream objects that weren't enclosed in a using.  I found them in the following code files:

JsonConvert.cs
JsonSerializeInternalWriter.cs
JsonValidatingReader.cs
JsonSchema.cs
DeserializeComparisonBenchmarks.cs
SerializeComparisonBenchmarks.cs

I hope this helps.

**Comment by JamesNK** [comment]
You don't need to dispose those types because they don't use unmanaged resources. The memory and strings are GCed along with the streams.
