### ISSUE TITLE
Serialization/deserialization of an XmlDocument does not preserve document order

### ISSUE THREAD

**Issue by ptr-null** [JamesNK/Newtonsoft.Json#2236]
### Actual behavior

The following XML instance loaded into `XmlDocument` object

```xml
<actionList>
  <punch/>
  <jump/>
  <kick/>
  <punch/>
</actionList>
```

results to following JSON data upon serialization

```javascript
{
  "actionList": {
     "punch": [null, null],
     "jump": null,
     "kick": null
  }
}
```

Deserializing it back skews the original order of the `XmlDocument`

```xml
<actionList>
  <punch/>
  <punch/>
  <jump/>
  <kick/>
</actionList>
```

which is wrong, because of order of elements in XML does matter (see [here](https://stackoverflow.com/a/1131566/2523686) and [here](https://stackoverflow.com/a/26829193/2523686)).

### Expected behavior

Serialization and deserialization of an `XmlDocument` should preserve document order.

### Steps to reproduce

```csharp
var xmlDocToSerialize = new XmlDocument();
xmlDocToSerialize.LoadXml("<actionList><punch /><jump /><kick /><punch /></actionList>");

string json = JsonConvert.SerializeObject(xmlDocToSerialize);
var xmlDocDeserialized = JsonConvert.DeserializeObject<XmlDocument>(json);
// results to skewed document order:
// <actionList><punch /><punch /><jump /><kick /></actionList>
```

**Comment by JamesNK** [comment]
That's a limitation of Newtonsoft.Json. If you want to roundtrip XML exactly you should write it as a string to a field and just have the XML embedded in JSON.
