### ISSUE TITLE
Stuck with v9.0.1 (due to Azure Functions) and wanting to use changes from issue #1014

### ISSUE THREAD

**Issue by sixeyes** [JamesNK/Newtonsoft.Json#2242]
I'm wanting to use the changes you implemented as part of issue #1014. Unfortunately because we're using Azure Functions v1 we're stuck with v9.0.1 which doesn't have those changes. I thought perhaps I could just add a custom version of StringEnumConverter.cs to my project, so I tried copying the file StringEnumConverter.cs (from commit https://github.com/JamesNK/Newtonsoft.Json/commit/6b9f467e817854532ea31e6c08abe47c53ac8b5c).

However this code references internal classes / structs / methods. I was wondering if there were any suggestions how I could get this working.

**Comment by JamesNK** [comment]
You will need to copy the internal types as well.
