### ISSUE TITLE
Serialization fails on derived Serializable class that inherits from base class with ISerializable

### ISSUE THREAD

**Issue by JustinBerger** [JamesNK/Newtonsoft.Json#2257]
### Source types

```csharp
[Serializable]
public class BaseClass : ISerializable
{

    public string BaseField { get; set; } = "Value";

    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue("BaseField", BaseField);
    }
}
[Serializable]
public class DerivedClass : BaseClass
{
    public string DerivedField { get; set; } = "Value";
}
```

### Expected behavior
```javascript
{"BaseField":"Value", "DerivedField":"Value"}
```

### Actual behavior
```javascript
{"BaseField":"Value"}
```

### Steps to reproduce

```csharp
var myData = new DerivedClass();
var json = Newtonsoft.Json.JsonConvert.SerializeObject(myData);
```

I ran into this issue because some libraries add the [Serializable] attribute to their exceptions, and Exception implements ISerializable. Such as the Refit ApiException.

Using v12.0.3

**Comment by JamesNK** [comment]
It looks like the library is correctly using ISerializable for DerivedClass.

Why is `{"BaseField":"Value"}` wrong? Why do you expect it to include DerivedField?

**Comment by JustinBerger** [comment]
A more realistic example:
```csharp
[Serializable]
public class MyException: Exception
{
    public string DerivedField { get; set; } = "Value";
}
```
I would expect the Json to include my derived field. 
If I remove the [Serializable] attribute, it does include the derived field as expected.

**Comment by JamesNK** [comment]
No, that's not how ISerializable works.
