### ISSUE TITLE
how do you target multiple .NET Frameworks?

### ISSUE THREAD

**Issue by cole-acepph** [JamesNK/Newtonsoft.Json#2312]
Hi, can you point me to any resources of how do you manage to create builds for .NET Core and also .NET 2.0 (the version I'm using), I have the same use case here and would like to know how to do that! Thanks in advance

**Comment by ed6767** [comment]
Hi,

A GitHub bugs page is not the correct place to post a question. Maybe try StackOverflow?

**Comment by JamesNK** [comment]
This question isn't about json.net.
