### ISSUE TITLE
GetHashCode returns same HashCode for different JValue tokens 

### ISSUE THREAD

**Issue by zappysys** [JamesNK/Newtonsoft.Json#2340]
### Expected behavior

GetHashCode() method of JValue object must return Unique HashCode for each elements returned from JObject.SelectTokens method.

### Actual behavior

For some object it returned same HashCode. Due to this if you try to add JValue objects into Dictionary you will get error like below because internally it uses HashCode as Key in Dictionary<object, xxx> instance.

```
ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
```

### Steps to reproduce
Run below sample code online (dotnetFiddle) and you will see exception due to same HashCode returned for different JValue Tokens 
[Click Here to See full Source Code link](https://dotnetfiddle.net/AyOhJm)

```using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

public class Program
{
	public static void Main()
	{
		Console.WriteLine("Environment version: " + Environment.Version);
		Console.WriteLine("Json.NET version: " + typeof(JsonSerializer).Assembly.FullName);
		Console.WriteLine();

		try
		{
			JsonValueArray_GetHashCode_Test();
		}
		catch (Exception ex)
		{
			Console.WriteLine("Failed with unhandled exception: ");
			Console.WriteLine(ex);
			throw;
		}
	}

	public static void JsonValueArray_GetHashCode_Test()
	{
		var json = @"{
  a: {
    Item: [
      {
        SerialNumber: [
          {}
        ]
      },
      {
        SerialNumber: [
          12345698756,
          564564564
        ]
      },
      {
        SerialNumber: [
          12345698756,
          564564564
        ]
      }
    ]
  }
}";
		var list=SelectTokenList(json, "$.a.Item[*].SerialNumber[*]", true);

		var dict=new Dictionary<object,string>();
		Console.WriteLine("======================");
		foreach (var item in list)
		{
			//You will notice 2md amd 4th HashCode always same -539203130
			Console.WriteLine(item.GetHashCode());
		}
		Console.WriteLine("======================");
		//Lets add ... it will throw exception...
		foreach (var item in list){
			dict.Add(item,item.ToString());
		}
			
	}

	public static object[] SelectTokenList(object json, string filter, bool throwErrorIfNotFound)//, bool indent
	{
		var tokenList = SelectTokenListInternal(json, filter, throwErrorIfNotFound);
		return tokenList.Cast<object>().ToArray();
	}
	private static IEnumerable<JToken> SelectTokenListInternal(object json, string filter, bool throwErrorIfNotFound)
	{
		JObject jobj = null;
		var jsonStr = string.Empty;
		if (json is JObject)
			jobj = (JObject)json;
		else
		{
			jsonStr = json.ToString();
		}

		if (jobj == null)
			jobj = JObject.Parse(jsonStr);
		return jobj.SelectTokens(filter, throwErrorIfNotFound);
	}
}
```

**Comment by ClaytonHughes** [comment]
The contract for GetHashCode() does not guarantee unique values for unequal objects; only that equal objects have equal HashCodes. (See https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netcore-3.1#remarks for some cautions)

It can't, by the pigeonhole principle. For example, in an object composed of two int values, there are 2^64 different configurations of that object yet only 2^32 possible outputs for GetHashCode(). There will necessarily be overlap.

Perhaps Dictionary<JValue, T>is not an appropriate container for whatever it is you're trying to do.

**Comment by JamesNK** [comment]
> ### Expected behavior
> GetHashCode() method of JValue object must return Unique HashCode for each elements returned from JObject.SelectTokens method.
> 
> ### Actual behavior
> For some object it returned same HashCode. Due to this if you try to add JValue objects into Dictionary you will get error like below because internally it uses HashCode as Key in Dictionary<object, xxx> instance.

HashCode is not unique. Image a list containing int.MaxValue + 1 items. It is literally impossible for all of them to have a unique value.
