### ISSUE TITLE
IAsyncEnumerable support

### ISSUE THREAD

**Issue by logiclrd** [JamesNK/Newtonsoft.Json#2356]
I have created a converter to add support for `IAsyncEnumerable<T>` to Newtonsoft.Json. I explored doing this directly in the Newtonsoft.Json codebase, but because it targets much older framework versions, I deemed this to be infeasible. Instead, I have created a separate library that contains a converter that can be registered to provide bidirectional conversion. As a separate library, it can target .NET Standard 2.0 and use C# 8 and not have to worry about the older framework versions that the main library supports (implementing `IAsyncEnumerable` is impossible in pretty much everything in the list other than `netstandard2.0`).

I think it would be good to publish this as an easily-discoverable NuGet package, e.g. with the name Newtonsoft.Json.AsyncEnumerable. Is there any chance that it might be accepted into the Newtonsoft.Json codebase in order that it be published in this way?

If not, what would the etiquette be around publishing a NuGet package with that ID under my own ownership? Making it perfectly clear of course in all descriptions & documentation that I was not affiliated with James Newton-King or the .NET Foundation.

**Comment by logiclrd** [comment]
A note on the rationale behind this: ASP.NET Core currently has a work-around for serializers not supporting `IAsyncEnumerable<T>`, and its work-around is to buffer the entire enumeration in-memory before passing it to the serializer as a `List<T>` instead. Apart from being inefficient, this work-around also has a problem if you create a stream that has no logical end, which is something I bumped into; I made an ASP.NET Core endpoint that streams status updates for as long as the client chooses to stay connected. Using `IAsyncEnumerable<T>`, it never sends any data, because ASP.NET Core thinks it can find the end of the sequence. I want to help ASP.NET Core get rid of this work-around, and in order to do that, at least the two core formatters it comes bundled with support for are going to need to support `IAsyncEnumerable<T>`.

I have an API proposal to this effect in for System.Text.Json, just waiting to hear back on that, and I have proofed my proposal with a working implementation.

Newtonsoft.Json is the other standard fromatter supported by ASP.NET Core.

**Comment by logiclrd** [comment]
I have searched for other NuGet packages where someone other than the original developer has contributed a package to the ecosystem sharing the same base name. It is not super common, but there definitely seems to be precedent. Would anybody get upset if I published a `Newtonsoft.Json.AsyncEnumerable` package with a description explaining clearly that it was developed and maintained independently?

**Comment by logiclrd** [comment]
@JamesNK If I could draw your attention to this issue specifically -- if I get no response I will eventually come to the understanding that it is just fine to publish my `Newtonsoft.Json.AsyncEnumerable` and will proceed to do so. I just want to make sure that if for whatever reason you don't think I should do this, you have had the opportunity to let me know. :-)

https://github.com/logiclrd/Newtonsoft.Json.AsyncEnumerable

**Comment by JamesNK** [comment]
You're welcome to publish your own package. You'll need to choose a different name though, as only official packages can start with "Newtonsoft" prefix.

**Comment by logiclrd** [comment]
I feel that this would best serve the community by being as discoverable as possible. Is there any possibility of getting my package accepted into the main Newtonsoft.Json codebase, as a contribution rather than a stand-alone project, and published alongside other Newtonsoft.Json packages?

**Comment by logiclrd** [comment]
Further background information: I have decided I want to get ASP.NET Core to a point where it no longer automatically buffers all outbound `IAsyncEnumerable` values it sees. The reason it buffers them is that the JSON converters don't support it. I am independently looking into `System.Text.Json` changes to support `IAsyncEnumerable` natively. It seems to be that it is basically impossible to make `Newtonsoft.Json` _directly_ support `IAsyncEnumerable` because of the wide range of older framework versions it explicitly targets. Based on that, my proposal is to provide a converter that can be easily added to `Newtonsoft.Json`'s serializer settings during initialization. But, I have a feeling that ASP.NET Core isn't going to consider it a solved problem if there is a completely independent third-party library providing the solution.

**Comment by JamesNK** [comment]
The Newtonsoft.Json serialize is synchronous. Sync over async leads to a number of problems. I don't want to make it an official feature.

**Comment by logiclrd** [comment]
Then I fear ASP.NET Core will never properly support `IAsyncEnumerable`. :-( I'll have to think about whether there might be some architecture to make it discoverable whether a formatter properly supports `IAsyncEnumerable`.

**Comment by logiclrd** [comment]
I just Googled this, and found a site outlining the following scenario:

- The thread pool has a limited number of threads. On my system this limit is not tiny (4K for my memory/architecture) but it is nevertheless quite finite.
- With sync over async, the thread initiating the operation might itself be a thread pool thread. Each new operation that comes in pulls a thread from the pool.
- It invokes the async operation, which sets up an underlying I/O and then returns. When that I/O is completed, it queues up a thread pool action to process it.
- While the async operation is running, the sync part at the top has to wait for it, which means blocking that thread pool thread it is occupying.
- If you manage to get as many overlapping I/O operations as there are thread pool threads, then the entire thread pool will be occupied by those sync top ends blocking on the completion of the underlying I/O operations. When those I/O operations complete, their continuations won't ever get scheduled because there are no free threads.

Thus, a deadlock arises.

So, my converter is only a band-aid -- it works in constrained testing scenarios, but wouldn't be a reliable scenario in a service scenario.
