### ISSUE TITLE
Cannot deserialize into a non-public class

### ISSUE THREAD

**Issue by MikeBrunoCISSP** [JamesNK/Newtonsoft.Json#2358]
Not sure if this is by design or not, but I was unable to use JsonConvert.DeserializeObject<T>(string) to deserialize json into a class where the class itself and all properties were internal. I didn't receive an exception, but instead got back an object instantiated with the default constructor. Only when I made the entity class and all properties public was I able to deserialize into it.

**Comment by MikeBrunoCISSP** [comment]
The class needs to be public because it must be visible from outside the namespace of my project

**Comment by elgonzo** [comment]
The answer given is technically not correct, neither is the observed issue a bug.

Json.NET does not require you to make the class or properties public.
If you want to have non-public properties participating in (de)serialization with Json.NET, you can decorate those properties with Json.NET's own `[JsonProperty]` attribute. Or, alternatively, you might decorate the data model type(s) with the `[DataContract]` attribute, and all serializable properties (public or not) with the `[DataMember]` attribute.
