### ISSUE TITLE
JSON deserializer broken.

### ISSUE THREAD

**Issue by Tetragromaton** [JamesNK/Newtonsoft.Json#2362]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```
Object, placeholder from https://www.newtonsoft.com/json

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```
string json = @"{
  'Name': 'Bad Boys',
  'ReleaseDate': '1995-4-7T00:00:00',
  'Genres': [
    'Action',
    'Comedy'
  ]
}";
### Expected behavior

I'd like to print Name in to console.
### Actual behavior
Should display Bad Boys

Showed up nothing.
### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

My code
So after running app, you should see name Bad Boys in the console app, but instead of it to be showed up, nothing being echoed on. 
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            string json = @"{
  'Name': 'Bad Boys',
  'ReleaseDate': '1995-4-7T00:00:00',
  'Genres': [
    'Action',
    'Comedy'
  ]
}";

            Movie m = JsonConvert.DeserializeObject<Movie>(json);

            string name = m.Name;
            Console.WriteLine(name);
            System.Threading.Thread.Sleep(5000);
        }
    }

    internal class Movie
    {
        public string Name { get; internal set; }
        public string ReleaseDate { get; internal set; }
    }
}
`

**Comment by LeshaZholner** [comment]
Internal types or members are accessible only within files in the same assembly. Just remove the internal
