### ISSUE TITLE
F#-related utilities

### ISSUE THREAD

**Issue by 0-gravity** [JamesNK/Newtonsoft.Json#2379]
Since in DiscriminatedUnionConverter fields CasePropertyName and FieldsPropertyName are hardcoded and cannot be customized as well as it's default implementation is slightly different from what I needed, the question is:
Can F#-related functionality be exposed to user?

**Comment by JamesNK** [comment]
> Since in DiscriminatedUnionConverter fields CasePropertyName and FieldsPropertyName are hardcoded and cannot be customized as well as it's default implementation is slightly different from what I needed, the question is:
> Can F#-related functionality be exposed to user?

No, but it is OSS so you can copy and paste the source code.
