### ISSUE TITLE
Support for multidimensional arrays

### ISSUE THREAD

**Issue by mwpowellhtx** [JamesNK/Newtonsoft.Json#2385]
Just curious, how about the level of [multidimensional array](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays) support?

For instance, the most commonly documented example is for the [two dimensional array](http://james.newtonking.com/archive/2012/08/06/json-net-4-5-release-8-multidimensional-array-support-unicode-improvements), matrix, by far.

I have not studied the code in great depth, but it seems to me like if you can reason about two dimensions, being an array of arrays, right, then you should be able to reason to the Nth dimension, no?

Cheers and thank you.

**Comment by elgonzo** [comment]
I have serialized and deserilized arrays with more than 2 dimensions in the past with Newtonsoft.Json without any trouble. 

What makes you think Newtonsoft.Json does not support multi-dimensional arrays with more than 2 dimensions? Have you already tried serializing such an array? What was the result?

Your post is not having much detail about the problem you are having, so i am unfortunately not able to understand what you are really trying to ask. If you are just curious of how exactly the resulting Json of multi-dimensional array serialization looks like, you can always just try for yourself. If you don't feel like or are unable firing up an IDE with Newtonsoft.Json, then you can always hop over to dotfiddle.net and play around with Newtonsoft.Json there.

**Comment by mwpowellhtx** [comment]
Hello appreciate the response. I did not say it didn't support ths, was curious whether it did as so many of the examples I read about are the simpler case of two dimensions. But you're right, it would be simple to cook up a simple unit test around that question. Appreciate the suggestion.
