### ISSUE TITLE
Stackoverflow validating Draft 2019-09 schema

### ISSUE THREAD

**Issue by sprotty** [JamesNK/Newtonsoft.Json#2389]
I'm attempting to validate a json document, which happens to be a Draft 2019-09 schema.

If you run the following code it keeps attempting to resolve the schema at 'https://json-schema.org/draft/2019-09/schema' which contains a reference to schema 'https://json-schema.org/draft/2019-09/schema' which it then resolves again, it does this forever or until the stack blows.

            string json =
           @"{
                       ""title"": ""My schema"",
                       ""$schema"": ""https://json-schema.org/draft/2019-09/schema"",                   
                       ""additionalProperties"": false,
                       ""type"": ""object""
               }";

            JSchemaReaderSettings jrs = new JSchemaReaderSettings();
            jrs.ValidateVersion = true;
            jrs.Resolver = new JSchemaUrlResolver();

            using (Newtonsoft.Json.JsonReader reader = new JsonTextReader(new StringReader(json)))
            {
                JSchema schema = JSchema.Load(reader, jrs);
                if (schema == null)
                    throw new Exception("Error parsing schema.");

            }
        }

**Comment by JamesNK** [comment]
This issue should be raised on https://github.com/JamesNK/Newtonsoft.Json.Schema
