### ISSUE TITLE
Refactor JsonConvert - Remove dependancy of System.Xml

### ISSUE THREAD

**Issue by LukeTOBrien** [JamesNK/Newtonsoft.Json#2391]
Hello there,

I am creating an app with Blazor web assembly and I am trying to get my download size down.  
System.Xml is the third biggest download that I have in my app, and I don't even use XML!   
Newtonsoft.Json is also a pretty big download.

I think this is an important issue as going forward people are going to use Blazor more and more to create Web Assembly apps.

What would be involved to refactor System.Xml out?

![download-size](https://user-images.githubusercontent.com/16164373/93397658-f2fed000-f871-11ea-8d47-d73e3d2e3fd9.png)

**Comment by sungam3r** [comment]
```xml
 <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="$(SystemRuntimeSerializationFormattersPackageVersion)" />
    <PackageReference Include="System.Xml.XmlDocument" Version="$(SystemXmlXmlDocumentPackageVersion)" />
  </ItemGroup>
```

DateTimeUtils:
```
 public static XmlDateTimeSerializationMode ToSerializationMode(DateTimeKind kind)
```

XmlNodeConverter:
```
#if HAVE_XML_DOCUMENT
        [MethodImpl(MethodImplOptions.NoInlining)]
        private bool IsXmlNode(Type valueType)
        {
            return typeof(XmlNode).IsAssignableFrom(valueType);
        }
#endif

```

and some other places. It is technically possible to do without the dependency, but this is unlikely to be done due to backward compatibility.

**Comment by LukeTOBrien** [comment]
Hmm okay, I guess I will close then.
