### ISSUE TITLE
Serializing/Deserializing Arraylist Objects having Items of Type System.Uri

### ISSUE THREAD

**Issue by naikparesh1990** [JamesNK/Newtonsoft.Json#2399]
Hi Team,

Found an Issue while serializing / Deserializing an ArrayList object containing Items of Type System.Uri, it gets converted to type System.String. Even post adding custom serializer with Type Handling, not able to serialize items of Type System.Uri.

Normal Code snipplet below with default serialization.

 try
            {

                System.Collections.ArrayList arrList = new System.Collections.ArrayList();

                Uri urlValue1 = new Uri("http://www.url1.com");
                Uri urlValue2 = new Uri("http://www.url2.com");
                Uri urlValue3 = new Uri("http://www.url3.com");

                arrList.Add(urlValue1);
                arrList.Add(urlValue2);
                arrList.Add(urlValue3);

                //Serializing
                var result = Newtonsoft.Json.JsonConvert.SerializeObject(arrList,
                                                               new Newtonsoft.Json.JsonSerializerSettings
                                                               { Formatting = Formatting.Indented,
                                                                   TypeNameHandling = TypeNameHandling.All
                                                               }
                                                               );

                //Deserializing
                System.Collections.ArrayList resultArray =
                    Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.ArrayList>(result,
                                                               new Newtonsoft.Json.JsonSerializerSettings
                                                               {
                                                                   Formatting = Formatting.Indented,
                                                                   TypeNameHandling = TypeNameHandling.All
                                                               }
                                                               );

                foreach (Uri u in resultArray)
                {
                    //...do something
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }

Default Error : Unable to cast Object of Type System.String to System.Uri.

**Comment by JamesNK** [comment]
ArrayList doesn't have type information so the deserializer doesn't know you want Uri objects. Deserialize to `List<Uri>`.
