### ISSUE TITLE
Allow inheriting from JsonConverterAttribute

### ISSUE THREAD

**Issue by coder-mike** [JamesNK/Newtonsoft.Json#2415]
I would like to be able to create custom attributes to control the formatting of JSON properties. For example, it would be great if I could create an `Iso8601Attribute` for use like this:

```cs
public class ThingIWantToSerialize 
{
    [Iso8601]
    public DateTimeOffset SomeDate { get; set; }
}
```

I think this would require me creating my own `Iso8601Attribute` class deriving from `JsonConverterAttribute`. However, at present, it's not possible to do this because `JsonConverterAttribute` is sealed. The result is that the recommended way to do custom serialization is a lot more ugly and less readible, involving something like:

```cs
public class ThingIWantToSerialize 
{
    [JsonConverter(typeof(Iso8601Converter))]
    public DateTimeOffset SomeDate { get; set; }
}
```

(unless there's a better way?)

Please note that I'm not talking about dates specifically, but rather I just want the ability to create custom attributes to control serialization, for the purpose of making my classes easier to read.

**Comment by JamesNK** [comment]
I don't want to do this because it would allow multiple converter attributes to be placed on a property/type.
