### ISSUE TITLE
Implementing IEquatable cases false positiv loop detection

### ISSUE THREAD

**Issue by Toxantron** [JamesNK/Newtonsoft.Json#2419]
We noticed in our project, that Json.Net will detect loops based on `Equals` and not based on reference equality. We serialize a [class](https://github.com/PHOENIXCONTACT/MORYX-Platform/blob/dev/src/Moryx/Serialization/EntryConvert/Entry.cs) that represents configuration entries and the necessary information to modify and extend it.

Part of an entry can be prototypes, which descripe how a new value is generated by the client UI. If the current value is identical to the prototype, we get the Reference Loop Exception. See the example below for a reproducible example.

### Source/destination types

```csharp
private class SomeClass : IEquatable<SomeClass>
{
    public int Value { get; set; }

    public SomeClass Fallback { get; set; }


    public bool Equals(SomeClass other)
    {
        return Value == other.Value;
    }

    public override bool Equals(object obj)
    {
        return Equals((SomeClass) obj);
    }

    public override int GetHashCode()
    {
        return Value;
    }
}
```

### Expected behavior

While both objects are equal in value, they are not the same object and therefor not a loop. Modifiying our implementation of Equatable means I can not comfortably compare a received value with its Default/Fallback/Prototype.

I would expect Json.Net to detect loops based on reference, not value.

### Actual behavior

Reference Loop exception

### Steps to reproduce

```csharp
[Test]
public void TestLoop()
{
    // Arrange
    var some = new SomeClass
    {
        Value = 42,
        Fallback = new SomeClass
        {
            Value = 42
        }
    };

    // Act => Throws loop exception
    JsonConvert.SerializeObject(some);
}
```

**Comment by Toxantron** [comment]
Because this caused issues in production, we decided to drop `IEquatable` in PHOENIXCONTACT/MORYX-Platform#74. Therefore we are no longer affected by this, but I will leave this open for discussion, if this maybe affects others as well.

**Comment by sungam3r** [comment]
You can try `System.Text.Json` instead.

**Comment by Toxantron** [comment]
@sungam3r thank you for your reply. We figured `IEqutable` might cause other side effects as well. Never the less I noticed that this project, while heavily used, has gotten a little quiet. Probably because @JamesNK started working for MS and is busy with new tasks - no judgement, just an observation.

**Comment by sungam3r** [comment]
In fact this project not a little quiet, this project is dead.

**Comment by JamesNK** [comment]
There is a configuration to override the comparer used - https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_EqualityComparer.htm
