### ISSUE TITLE
Exception on serializing object containing uninitialized ImmutableArray

### ISSUE THREAD

**Issue by atykhyy** [JamesNK/Newtonsoft.Json#242]
For example, `JsonConvert.SerializeObject (new A ())` throws `NullReferenceException` when `A` is as below. This behavior appears with the new Microsoft.Bcl.Immutable.1.1.20-beta. To avoid the exception, the serializer needs to get the underlying array with `Foo.Array` and work with it, or check `Foo.IsDefault` before enumerating it, taking its length etc.

```
public class A
{
    public ImmutableArray<int> Foo ;
}
```

**Comment by Timovzl** [comment]
> that's up to Microsoft to decide.

@JamesNK Microsoft [decided to work around this](https://github.com/dotnet/runtime/issues/35160) for System.Text.Json. Apparently, they found that preferable to losing the performance optimization in the whole of `ImmutableArray<T>`.

However, this does mean that it is unlikely to change, i.e. users of Newtonsoft.Json will keep running into it indefinitely. It strikes me as a pretty big factor of astonishment.

As undesirable as a workaround in Newtonsoft.Json is, the current situation seems worse. Each user code base has to apply a workaround to each property of the type. I'm hoping you'll reopen this.

The least bad workaround I've come up with so far is this:

```cs
	[Newtonsoft.Json.JsonIgnore] // https://github.com/JamesNK/Newtonsoft.Json/issues/242
	public ImmutableArray<byte> ResponseBody { get; private set; }

	/// <summary>
	/// https://github.com/JamesNK/Newtonsoft.Json/issues/242
	/// </summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Newtonsoft.Json.JsonProperty(nameof(ResponseBody))]
	internal byte[] SerializableResponseBody => ImmutableCollectionsMarshal.AsArray(this.ResponseBody) ?? [];
```

(For a package, we can use internal with `EditorBrowsableState.Never`. For a regular application, that won't hide it, and `internal` will be too visible. We'll need `private` and the analyzer suppressions to go with it, making matters worse.)
