### ISSUE TITLE
How to check that JArrays contains a List of object or Values 

### ISSUE THREAD

**Issue by heizel184** [JamesNK/Newtonsoft.Json#2421]
Hey 
I have a json Array that Array could be a list of objects or values 
in case of objects 
[
{ username : ref ,
roll no : 1},
{ username:sed,
rollno: 2},
]
in case of values 
[ 123, 5688, 12]
so I want to check in JArray without any loop that of it containing list of objects or values 
Any solution

**Comment by elgonzo** [comment]
JArray is derived IEnumerable<JToken>.

The JToken enumeration of an JArray are the elements of the array. Query the Type property of every element JToken to see whether it is a value or an object.

Whether you use a loop or some Linq construct is up to you, but no matter what you have to enumerate the whole array to see whether it consists of objects only or values only...
