### ISSUE TITLE
Different outcome when serializing a double in .net 5 over .net core 2.2

### ISSUE THREAD

**Issue by dgiddins** [JamesNK/Newtonsoft.Json#2433]
### Source/destination types

```csharp
[Serializable]
    public class Position
    {
        public Position(double x, double y)
        {
            X = x;
            Y = y;
        }

        public double X { get; set; }
        public double Y { get; set; }
    }            
```

### Source/destination JSON

```javascript
{"X":30.316385382926356,"Y":50.49432903935046}
```

### Expected behavior

I expected that the serialized value of the Y (50.494329039350461) property would be exactly the same as the value provided which is what happens in .net core 2.2

### Actual behavior

It seems to round down the number when using .net 5.0 to 50.49432903935046. I can reproduce this behaviour with the the following numbers but not all doubles of the same length:

- 50.494328391915907
- 30.316339899700989
- 50.494128852095287

### Steps to reproduce
You get different results if you target .net core 2.2 vs .net 5.0. This is a problem as we generate hashes from our objects (which are more complex than this) to detect changes in objects we sync form one system to another. The data represents geographic coordinates so losing precision is not something we can tolerate. I don't know if this is a bug with Newtonsoft of with the Number formatting in .net 5

```csharp
var d = 30.316385382926356;
var d1 = 50.494329039350461;

var position = new Position(d, d1);

var serializedPosition = JsonConvert.SerializeObject(position);
```

I can reproduce this with System.Text.Json.JsonSerializer and have raised an issue on the dotnetcore project https://github.com/dotnet/core/issues/5665

**Comment by JamesNK** [comment]
This is because of a behavior change in .NET. I can't do anything about it.
