### ISSUE TITLE
Doubling elements

### ISSUE THREAD

**Issue by YuriPetskus** [JamesNK/Newtonsoft.Json#2435]
Elements are doubled during deserialization if List<TrickElement> is used instead of TrickElement[].
See TrickStat.cs --> Elements
[Json.NET.bug.zip](https://github.com/JamesNK/Newtonsoft.Json/files/5635808/Json.NET.bug.zip)

For verification:
PlayerModel profile = JsonConvert.DeserializeObject<PlayerModel>(json); //, new TrickElementJsonConverter());

**Comment by JamesNK** [comment]
https://www.newtonsoft.com/json/help/html/DeserializeObjectCreationHandling.htm
