### ISSUE TITLE
Feature Request: JProperty.Parse

### ISSUE THREAD

**Issue by jkindwall** [JamesNK/Newtonsoft.Json#2437]
I have a json blob that contains an array of "property strings".  It looks something like this:
```
[
    "\"key1\":\"val1\"",
    "\"key2\":\"val2\"",
    ...
]
```

I thought maybe I could convert this to a JObject, like so:
```
JArray arr = JArray.Parse(jsonBlob);
JObject jobject = new JObject(arr.Cast<JValue>().Select(t => JProperty.Parse((string)t.Value)));

```

However, since there is no JProperty specific parse method this just calls the base JToken.Parse method, which parses the first part of the string as a JValue, then throws a JsonReaderException ("Additional text encountered after finished reading JSON content: :...") when it gets to the colon character.

Now I can think of a couple ways to work around this, so it's not that big a deal, but it would be nice if the JProperty class implemented its own version of the static Parse method to handle cases like this.

**Comment by JamesNK** [comment]
A property is a name and a value. You're trying to parse just the value.

Usage questions like this should be asked on StackOverflow.

**Comment by jkindwall** [comment]
No, I'm trying to parse a string that is in the format of a key/value pair into a property.  Please take a look at my description of the feature request again.
