### ISSUE TITLE
BUG TypeName provided by SerializationBinder gets manipulated afterwards

### ISSUE THREAD

**Issue by omghb** [JamesNK/Newtonsoft.Json#2439]
### Source/destination types

https://github.com/omghb/JsonSerializationBinderBug/blob/main/JsonSerializationBinderBug/SerializationBinderBugDemo.cs

### Source/destination JSON

```javascript
{"$id":"1","Data":{"$id":"2","$type":"TestClass`3[Int32,Double]","Item1":42,"Item2":3.1415,"Item3":"Luke"}}
```

### Expected behavior

```javascript
{"$id":"1","Data":{"$id":"2","$type":"TestClass`3[Int32,Double,String]","Item1":42,"Item2":3.1415,"Item3":"Luke"}}
```

### Actual behavior

```
Assert.Equal() Failure
                                  ↓ (pos 24)
Expected: ···Class`3[Int32, Double, String]
Actual:   ···Class`3[Int32, Double]
                                  ↑ (pos 24)
```

### Steps to reproduce

I have published a sample xUnit test to reproduce this issue here:
https://github.com/omghb/JsonSerializationBinderBug

### Workaround

When the `KnownTypesBinder` uses other char than "[", "]" and "," then this works correct. It seems that Newtonsoft.Json does some post-processing with the typeName provided by the SerializationBinding and interprets the chars "," and "[", "]" in some way.

**Comment by TylerBrinkley** [comment]
You need to specify `TypeNameAssemblyFormatHandling.Full` so that the serializer doesn't try to strip out the assembly name which is what it's trying to do here.

**Comment by omghb** [comment]
Thanks for providing the correct setting. This fixed my issue.

This might even gain a little bit performance because `RemoveAssemblyDetails` will not be called - as it should not when a custom SerializationBinder takes over.

https://github.com/JamesNK/Newtonsoft.Json/blob/cdf10151d507d497a3f9a71d36d544b199f73435/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs#L157
