### ISSUE TITLE
Make the ReflectionUtils.GetTypeName(...) publically accessible

### ISSUE THREAD

**Issue by ivshch** [JamesNK/Newtonsoft.Json#2447]
_Sorry, but this is a non-standard issue, so the template is inapplicable here._
### Issue Description
When following the MS [guidance](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2326#how-to-fix-violations) of safe JSON deserialization we found that the type names were additionally processed by [ReflectionUtils.RemoveAssemblyDetails(...)](https://github.com/JamesNK/Newtonsoft.Json/blob/666d9760719e5ec5b2a50046f7dbd6a1267c01c6/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs#L183) method. Regular types are just serialized with the type's full name, while the more complex generic types are cleaned from the assembly information.
Our approach is to have a whitelist of type names allowed to be processed by the deserializer. Making it exactly match the names produced by the Newtonsoft.Json requires either calling the method [GetTypeName](https://github.com/JamesNK/Newtonsoft.Json/blob/666d9760719e5ec5b2a50046f7dbd6a1267c01c6/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs#L150) of an internal class (ReflectionUtils) or copy-pasting the method into our application. Both approaches are far from ideal, so please consider opening the ReflectionUtils.GetTypeName(...) method.
### The Proposed Change
Probably an additional accessor class would be a solution:
```csharp
public class ReflectionUtilsAccessor
{
    public static string GetTypeName(Type t, TypeNameAssemblyFormatHandling assemblyFormat, ISerializationBinder? binder)
    {
        return ReflectionUtils.GetTypeName(t, assemblyFormat, binder);
    }
}
```

**Comment by JamesNK** [comment]
I don't want to make internal, non-JSON functionality, public. You can copy the source code.
