### ISSUE TITLE
object[] DeserializeObject Object of type 'System.Int64' cannot be converted to type 'System.Int32'.

### ISSUE THREAD

**Issue by m839336369** [JamesNK/Newtonsoft.Json#2449]
### Source/destination types

```csharp
int k = 20;
object[] num = new object[]{ k };
Console.WriteLine(JsonConvert.DeserializeObject<object[]>(JsonConvert.SerializeObject(num)));
```

### Source/destination JSON
[20]
### Expected behavior

can convert to int32

### Actual behavior

Object of type 'System.Int64' cannot be converted to type 'System.Int32'.

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by bobbyalex** [comment]
There is no correlation between your code and the error you mentioned. If your intent is to deserialize the json to an array of ints then change the cast to `JsonConvert.DeserializeObject<int[]>`

**Comment by m839336369** [comment]
object is not sure what it is
I only use object[],


> There is no correlation between your code and the error you mentioned. If your intent is to deserialize the json to an array of ints then change the cast to `JsonConvert.DeserializeObject<int[]>`

thanks,it has already resolved.
