### ISSUE TITLE
Json assembly in SQL Server gets an error because of the static field _camelCaseNamingStrategy

### ISSUE THREAD

**Issue by Protecteric** [JamesNK/Newtonsoft.Json#2453]
I write a C# script to get data from a json source(webcall to a influx database) and convert this to a table in sql server with exactly the same columns and rows as in the JSON file. I want to make a CLR/ASSEMBLY with this code but the ASSEMBLY in SAFE permission dont accept static fields, so I changed my code, but I cant change the Newtonsoft.Json. 

**This is the error I get:
Msg 6211, Level 16, State 1, Line 117
CREATE ASSEMBLY failed because type 'Newtonsoft.Json.Utilities.EnumUtils' in safe assembly 'Newtonsoft.Json' has a static field '_camelCaseNamingStrategy'. Attributes of static fields in safe assemblies must be marked  readonly in Visual C#, ReadOnly in Visual Basic, or initonly in Visual C++ and intermediate language.**

Is there someone who knows how to fix this?

**Comment by bobbyalex** [comment]
Does this answer at Stackoverflow help? https://stackoverflow.com/a/27135828

**Comment by Protecteric** [comment]
I finally find the answer.
