### ISSUE TITLE
How to avoid Newtonsoft.Json.Linq.JObject and keep Object ?

### ISSUE THREAD

**Issue by nicoclau** [JamesNK/Newtonsoft.Json#2460]
Hello I have the following 

`    internal class A
    {
        public string B { get; set; }
        public object C { get; set; }
    }

    internal class D
    {
        public string E { get; set; }
    }`
    
    I try to use the D instance in A => C
    
    `var a = new A
            {
                B = "x",
                C = new D
                {
                    E = "x"
                }                
            };`

Then I want to serialize and deserialise 

`  var aser = JsonConvert.SerializeObject(a, Formatting.Indented);

            var ades = JsonConvert.DeserializeObject<A>(aser);

            var c = (D)ades.C;`

But I get the exception:

Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'D'

How can I keep the type Object instead of Newtonsoft.Json.Linq.JObject ?

Thanks

**Comment by nicoclau** [comment]
I found a setting : TypeNameHandling = TypeNameHandling.All

` var settings = new JsonSerializerSettings()
            {                
                TypeNameHandling = TypeNameHandling.Auto,
                Formatting = Formatting.Indented
            };`

It keeps the types for each property.
instead of getting:

`{
  "B": "x",
  "C": {
    "E": "x"
  }
}`

we get

`{
  "B": "x",
  "C": {
    "$type": "RPCServerConsole.D, MrFly.Connectivity.RabbitMQ.RPC.ClientConsole",
    "E": "x"
  }
}`

When we deserialize we get back the proper type

  | Name | Value | Type
-- | -- | -- | --
◢ | ades | {RPCServerConsole.A} | RPCServerConsole.A
  | B | "x" | string
  | ◢ C | {RPCServerConsole.D} | object {RPCServerConsole.D}
  | E | "x" | string

Question is it okay to do this?
I understand it detected the type Object and added the type in the json message.
it is not standard but can it cause problem for interaction with other language/framework in other client?

Thanks

**Comment by JamesNK** [comment]
> it is not standard but can it cause problem for interaction with other language/framework in other client?

Yes.
