### ISSUE TITLE
Why not add .NetFramework 4.8 to NewtonJson project?

### ISSUE THREAD

**Issue by Shirley-Ji-59** [JamesNK/Newtonsoft.Json#2469]
Hello, 
Since most of my projects have been upgraded to .NetFramework 4.8, I would like to ask why NewtonJSon has not upgraded the .NetFramework version. Will there be any exceptions when I upgrade when compiling?

Thanks a lot. Hope your reply.

**Comment by JamesNK** [comment]
A net45 target automatically supports .NET 4.8. There aren't any important new APIs requiring it to be targeted directly so there is no reason to.
