### ISSUE TITLE
[Suggestion] Add Extension methods

### ISSUE THREAD

**Issue by SaSiNO97** [JamesNK/Newtonsoft.Json#2474]
I suggest adding a namespace `Newtonsoft.Json.ExtensionMethods` that adds the following extension methods:

```csharp
public static string Json(this object obj) => JsonConvert.SerializeObject(obj);
public static T Unjson<T>(this string json) => JsonConvert.DeserializeObject<T>(json);
```

**Comment by JamesNK** [comment]
I don't like extension methods on built-in types like this. If you want them, add them to your own solution, or NuGet package.
