### ISSUE TITLE
JsonConvert.DeserializeObject<T> will converting a value like "[]" into a `new T`

### ISSUE THREAD

**Issue by StingyJack** [JamesNK/Newtonsoft.Json#2483]
This seems like a bug as I would expect an empty like `[ ]` to convert into null or be unconvertable. If there is a setting to make this happen that would be great, and sorry if this is a dupe (searching for `[]` is not producing any meaningful results.)

### Source/destination types

```csharp
public class MyType
{
    public string FirstName {get;set;}
    public string LastName {get;set;}
    public int MyId {get;set;}
}
```

### Source/destination JSON

Below is what displays in the Watch window when inspecting an properties of an instance of the `JToken`  named `resultJson` , the full inspection in the watch window being `resultJson["ouputData"]["data"].ToString()`
```javascript
[]
```
When inspecting `resultJson["ouputData"]["data"].HasValue` the result is `false`

### Expected behavior

I expect when I call  that either a null is returned or an exception is thrown. 

### Actual behavior

I get an instance of `MyType` with null string property values and a 0 for the integer. 

### Steps to reproduce

``` csharp
var value = JsonConvert.DeserializeObject<MyType>(resultJson["ouputData"]["data"].ToString());
```

**Comment by elgonzo** [comment]
No, attempting to deserialize the string `"[]"` to MyType will throw an exception.
Proof: https://dotnetfiddle.net/7NKoJb

I suggest you assign `resultJson["ouputData"]["data"].ToString()` to a string variable before invoking `JsonConvert.DeserializeObject` and inspect the string variable in the debugger. I suspect somewhere somehow you got confused during trouble-shooting about the actual result of `resultJson["ouputData"]["data"].ToString()`...

**Comment by StingyJack** [comment]
> got confused

This particular code is kind of a mess because its handling a few different payload structures trying to Deserialize<T> from different possible places. 
The STR example is consolidated, its actually several statements with checks to make sure the payload has the output data and data elements. The problem I think in this case had two contributing components - the wrong type was being passed in as T, and some of the T types had properties with internal setters.

**Comment by StingyJack** [comment]
It would be nice to have a serializer option that would throw an exception when a property could not be set, or some other easier diagnostic than debugging a library.
