### ISSUE TITLE
Deserializing "[]" as a JObject, returns a JArray instead

### ISSUE THREAD

**Issue by moabba** [JamesNK/Newtonsoft.Json#2484]
### Source/destination types

```csharp
JObject
```

### Source/destination JSON

```javascript
[]
```

### Expected behavior

Deserializing a `[]` into a `JObject` would fail, return null, or return an empty JObject.

### Actual behavior

`JsonConvert.DeserializeObject` returns a `JArray` which doesn't match the requested type. Which fails when the result is cast as `JObject`.

### Steps to reproduce

```csharp
var json = "[]";
var output = JsonConvert.DeserializeObject(json, typeof(JObject));

Console.WriteLine(output.GetType().FullName);
```

**Comment by elgonzo** [comment]
No. Read the method name carefully:

It is called DeserializeObject.
It is not called Deserialize**_J_**Object.

As the documentation says (https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConvert_DeserializeObject.htm):
> Deserializes the JSON to a **_.NET object_**

**Comment by JamesNK** [comment]
Thanks for reporting this. It has been fixed.
