### ISSUE TITLE
i want ignore the initialize-ListValue in DeserializeObject,what should i do

### ISSUE THREAD

**Issue by afunc233** [JamesNK/Newtonsoft.Json#2502]
### Source/destination types

```csharp
public class AClass
{
    private static List<string> DefaultList { get { return new List<string>() { "123654987" }; } }

    public List<string> List { get; set; } = DefaultList;
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");

        List<AClass> beforeList = new List<AClass>();

        var beforeA = new AClass();
        beforeList.Add(beforeA);

        var str = JsonConvert.SerializeObject(beforeList);

        List<AClass> afterList = JsonConvert.DeserializeObject<List<AClass>>(str);

        var afterA = afterList.FirstOrDefault();

        Console.ReadKey();
    }
}
```

### Source/destination JSON

```javascript
[{"List":["123654987"]}]
```

### Expected behavior
I think the count of the  in afterA.List is 1

### Actual behavior

it count is 2 Actual 
### Steps to reproduce
![image](https://user-images.githubusercontent.com/19919631/112431623-b5c44f00-8d7a-11eb-8b34-d77c2c939ec7.png)

```csharp
// i use Newtonsoft.Json 13.0.1
```

**Comment by elgonzo** [comment]
There is no need to change the library.

Just instruct the deserializer to not reuse existing object instances and instead always create new instances (default mode of operation of the deserializer is to reuse and populate existing instances - that includes using existing list instances when deserializing json arrays into them). https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_ObjectCreationHandling.htm

        List<AClass> afterList = JsonConvert.DeserializeObject<List<AClass>>(
			str,
			new JsonSerializerSettings { ObjectCreationHandling = ObjectCreationHandling.Replace }
		);

(dotnetfiddle: https://dotnetfiddle.net/NtyqPe)

**Comment by afunc233** [comment]
thanks

**Comment by afunc233** [comment]
thanks
