### ISSUE TITLE
False posiive with Malwarebytes

### ISSUE THREAD

**Issue by mtissington** [JamesNK/Newtonsoft.Json#2510]
We have an install using Newtonsoft.Json dll - all was great until the latest update.
In version 13.01 MalwareBytes is reporting the dll as a virus and then deleteing it.

What can be done?

**Comment by JamesNK** [comment]
Stop using MalwareBytes?

**Comment by mtissington** [comment]
This is a useless comment. We have little control over the software our clients use. But you do have control over the code that you generate and if it causes false positives in anti virus software. In the end we had to notify MalwareBytes and notify them that your dll was generating false positives. Thank you, your welcome.
