### ISSUE TITLE
Deserializing a Dictionary<string, string> throws JsonReaderException

### ISSUE THREAD

**Issue by bonk-dev** [JamesNK/Newtonsoft.Json#2511]
### Source/destination types

```csharp
Dictionary<string, string>
```

### Source/destination JSON

```javascript
{
  "FIRSTNAME": "First name"
}
```

### Expected behavior
I expected to get an instance of Dictionary<string, string>.

### Actual behavior
I got a JsonReaderException: 
"Error parsing boolean value. Path '', line 1, position 2."

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<Dictionary<string, string>>("translations.json");
```

**Comment by Toszxx** [comment]
ok
thanks
