### ISSUE TITLE
EscapeNonAscii setting does not work in SerializeObject or DeserializeObject

### ISSUE THREAD

**Issue by ArturChe** [JamesNK/Newtonsoft.Json#2513]
I am trying to get rid of any kind of control characters or non-printable characters while deserializing the request body JObject.
I try to put proper settings in SerializeObject or DeserializeObject, but it does not affect the result at all.
What is the proper way to handle such stuff?

```csharp
var settings = new JsonSerializerSettings
{
 StringEscapeHandling = StringEscapeHandling.EscapeNonAscii
};

dynamic t = JsonConvert.DeserializeObject<ExpandoObject>(JsonConvert.SerializeObject(j, settings), settings);
```

### Source/destination JSON

```javascript
{"x":"\u0000"}
```

### Expected behavior
```
t.x is "\u0000"
```

### Actual behavior
```
t.x is " " //"NUL"
```

**Comment by elgonzo** [comment]
`StringEscapeHandling` won't help you, as this setting is for writing / serializing into json, not the other way around. The derserializer itself does not have such a feature built-in, as the control sequences in question here are part of the json format spec and you are kind of asking for something that could be described as "not fully parsing json". However, Newtonsoft.Json is flexible enough to allow you to address your problem with some additional code.

However, not all control char sequences in json are representing non-printable control characters only, some control char sequences do or might represent printable characters (such as `\"`, `\\`, `\/`, or `\uXXXX with a value representing a printable char). Thus, it is unclear what you really want to get rid of: either all control char sequences in the source json or only specifically non-printable control characters.

I am going to speculate that it is the latter - only getting rid of non-printable control characters. If this is the case, you can achieve this with a custom JsonConverter which takes care of filtering out any control chars from the deserialized chars:

    public class StringsWithoutNonprintablesConverter : JsonConverter<string>
    {
        public override string ReadJson(JsonReader reader, Type objectType, string existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            if (reader.TokenType != JsonToken.String)
                throw new InvalidDataException("Json data is not a string value");

            var s = (string) reader.Value;
            return (s.Any(char.IsControl)) ? new string(s.Where(c => !char.IsControl(c)).ToArray()) : s;
        }

        public override void WriteJson(JsonWriter writer, string value, JsonSerializer serializer)
        {
            writer.WriteValue(value);
        }
    }

Dotnetfiddle example demonstrating the effect of this converter: https://dotnetfiddle.net/TLV85q

Depending on your needs, you might want to modify the exception handling and/or implement a char filtering routine that is filtering only whatever characters you really want to omit or is faster, leaner and meaner than my simple Linq+ToArray approach. :-)

Hope this helps. (Anyways, if you have further questions of how to use Newtonsoft.Json, Stackoverflow.com would probably be a better place to ask. You know, number of eyeballs seeing your question, and all that...)

**Comment by ArturChe** [comment]
Thanks, @elgonzo !
I have started looking at this option with custom converter after I find out that only 3 handlers apply to JsonReader (DateTimeZoneHandling, DateParseHandling, FloatParseHandling).
I just was confused that ```var s = JsonConvert.SerializeObject(jObject)``` gives me ```"{"x":"\u0000"}"``` and than ```dynamic d = JsonConvert.DeserializeObject<ExpandoObject>(s);``` gives a control char instead of string

**Comment by elgonzo** [comment]
Feeding `"{"x":"\u0000"}"` into `JsonConvert.DeserializeObject<ExpandoObject>(s)` will give you a string of length 1 (a string with a single character), with the single character in the string being the NUL character (`\u0000`). If you only get a `char` type value instead of a `string` type value , something else in your code is doing some string->char conversion.

**Comment by ArturChe** [comment]
That works, thanks a lot @elgonzo !
