### ISSUE TITLE
Question - Microsoft.AspNetCore.OData needs support for Newtonsoft.Json

### ISSUE THREAD

**Issue by omnilogix** [JamesNK/Newtonsoft.Json#2515]
@JamesNK - Can you possibly weigh in on this request to support Newtonsoft.Json in the Microsoft OData package?  Supporting your Json implementation would be a great benefit there.

[https://github.com/OData/AspNetCoreOData/pull/137](url)

**Comment by JamesNK** [comment]
What they do is up to them. I don't have an opinion.
