### ISSUE TITLE
DiscriminatedUnionConverter throws NullReferenceException under high parallelism

### ISSUE THREAD

**Issue by eulerfx** [JamesNK/Newtonsoft.Json#254]
I'm using JSON.NET v6.0.1 from F# project. Everything works fine under with a single thread. However, when I increase the degree of parallelism/concurrency I repeatedly get a NullReferenceException with the following stack trace:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert(Type objectType)
>    at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
>    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)

The types being serialized are not union types. Seems like a bug in this new converted? For my use case, it would be nice to exclude it all together since I've my own converters for union types.

**Comment by gaurav-krishna** [comment]
I have encountered this issue with 6.0.6 in C# as well.
