### ISSUE TITLE
Json pair '"obj":,'  deserializes without issue?

### ISSUE THREAD

**Issue by aaronggi** [JamesNK/Newtonsoft.Json#2560]
### Source/destination types

```csharp
internal class Test1
{
    internal class Test2
    {
        public string dummy { get; set; }
    }
    public Test2 obj { get; set; }
    public string obj2 { get; set; }
}
```

### Source/destination JSON

```javascript
{"obj":, "obj2":"hello world" }
```

### Expected behavior

I'm not sure if this is valid json or not(different linters/validators give me mixed messages), or if this is working as designed. 
I was **expecting there to be some sort of exception for this input, but it deserializes successfully**. 

Assuming this is invalid json, but the library is working as designed, is there JsonSerializerSettings option to control the strictness of the parsing? I looked through the docs and played around with the settings and didn't find anything of the sort.

### Actual behavior

Deserializing the above json succeeds, and produces `null` for `obj`. 

### Steps to reproduce

```csharp
string json = @"{""obj"":, ""obj2"":""hello world"" }";
var v = JsonConvert.DeserializeObject<Test1>(json);
```

Thanks!

**Comment by elgonzo** [comment]
Your souce json is not valid json, specifically this part: `"obj":,`. There is no zero-length value token in the json specification that would allow a comma to (semantically) follow directly after the `:` separator of a json property. (You can check the json spec for yourself: https://www.ecma-international.org/publications-and-standards/standards/ecma-404/)

Unfortunately, there is no strict parsing mode in Newtonsoft.Json. While such a feature has not been asked for very often, it has been asked for repeatedly over the years; see here: https://github.com/JamesNK/Newtonsoft.Json/issues/646. I am not sure whether Newtonsoft.Json will ever get a strict mode. But perhaps you could give System.Text.Json a try, whose parsing is stricter than Newtonsoft.Json.  (dotnetfiddle demo of STJ trying to parse your invalid json: https://dotnetfiddle.net/HpyBrC)

**Comment by ChuDawg** [comment]
string json = @"{""obj"":, ""obj2"":""hello world"" }";
var v = JsonConvert.DeserializeObject<Test1>(json);

**Comment by aaronggi** [comment]
@elgonzo Thanks for the info! Newtonsoft is definitely still my go-to, as this isn't a dealbreaker for my purposes by any means. Will close the issue
