### ISSUE TITLE
Add README to NuGet packages

### ISSUE THREAD

**Issue by loic-sharma** [JamesNK/Newtonsoft.Json#2571]
Hello!

I am from the NuGet team at Microsoft. We recently introduced support for embedding READMEs into NuGet packages ([blog](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/), [docs](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)), and we plan to place these READMEs front and center on nuget.org. Would you be willing to accept a contribution to add embedded READMEs to your packages?

**Comment by JamesNK** [comment]
Sure, go ahead.

**Comment by sungam3r** [comment]
fixed by #2596
