### ISSUE TITLE
Array with missing [ is considered a valid JSON

### ISSUE THREAD

**Issue by MangelMaxime** [JamesNK/Newtonsoft.Json#2585]
### Source/destination types

```csharp
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;
					
public class Program
{
	public static void Main()
	{
		var json = "\"SomeUnion\",\"foo\"]\"";
		var reader = new JsonTextReader(new StringReader(json)) {
			DateParseHandling = DateParseHandling.None
		};
		
		var res = JValue.ReadFrom(reader);
		
		Console.WriteLine(json);
		Console.WriteLine(res.ToString());
	}
}
```

### Source/destination JSON

```javascript
"SomeUnion","foo"]"
```

### Expected behavior

I am expecting an error similar to:

```
Unhandled exception. Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '', line 1, position 8.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   at Program.Main()
Command terminated by signal 6
```

Because according to https://jsonformatter.curiousconcept.com/# it is not a valid JSON:

![image](https://user-images.githubusercontent.com/4760796/132958510-6311aebf-0711-43ee-8ec7-c8f71d384df3.png)

### Actual behavior

No error

### Steps to reproduce

```csharp
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;
					
public class Program
{
	public static void Main()
	{
		var json = "\"SomeUnion\",\"foo\"]\"";
		var reader = new JsonTextReader(new StringReader(json)) {
			DateParseHandling = DateParseHandling.None
		};
		
		var res = JValue.ReadFrom(reader);
		
		Console.WriteLine(json);
		Console.WriteLine(res.ToString());
	}
}
```

**Comment by elgonzo** [comment]
Not really a bug...

There is no json array to be considered. The `]` is a red herring. There is a value there that is a valid string according to JSON syntax rules. And that string value `"SomeUnion"` is what `JToken.ReadFrom` reads, hence no error. (Btw, there is no specific _JValue.ReadFrom_ implementation; the compiler will simply resolve _JValue.ReadFrom_ to _JToken.ReadFrom_).

That _JToken.ReadFrom_ should attempt reading an JSON array when confronted with your "json" string is a misplaced expectation. It reads whatever token (or JSON data type, if you will) it detects, which in this case is just the JSON string `"SomeUnion"`, and it doesn't care whatever else follows after that token. In this sense, `"SomeUnion","foo"]"` would be no different than for example `"SomeUnion"this is totally not json anymore...` whether there is some bracket in the "tail" after `"SomeUnion"` or not.

If you expect your JSON data to be an array, you can attempt to load it as a _JArray_ by using the [JArray.Load method](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JArray_Load.htm), like:
```C#
var res = JArray.Load(reader);
```
This will then also throw an exception if no valid JSON array can be obtained from the reader.

**Comment by elgonzo** [comment]
If the reason you are using a JsonReader is to configure said JsonReader (and this excluding you from JToken.Parse) with varying input data that is not always an Json array, there is a third way of doing this: using the _JsonSerializer_. _JsonSerializer_ can actually deserialize into a JToken. The deserializer figures out the concrete JTtoken type (such as JValue, JArray, JObject) by itself:
```C#
var serializationSettings = new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.None,
    CheckAdditionalContent = true                     // <--- THIS IS VERY IMPORTANT, DO NOT FORGET TO SET THIS
};
var serializer = JsonSerializer.Create(serializationSettings);

var reader = new JsonTextReader(new StringReader(json));
var res = serializer.Deserialize<JToken>(reader);
```

Note that it is required for your use case to set **`CheckAdditionalContent`** in the serialization settings to **_true_**, otherwise this approach using the deserializer would just work like _JToken.ReadFrom_ (i.e., just reading `"SomeUnion"`). Dotnet fiddle example: https://dotnetfiddle.net/m1yAM2

**Comment by MangelMaxime** [comment]
Thank you for the explanations @elgonzo .

Your last answer is what solved my problem, as I don't know what is the form of the JSON in advance and so I don't know if I am expecting a string, object or an array, etc.
