### ISSUE TITLE
Deserialize bool bug

### ISSUE THREAD

**Issue by kelicto** [JamesNK/Newtonsoft.Json#2617]
### Source/destination types

```csharp
JsonConvert.DeserializeObject<bool>(default(T).ToString()); //default(T).ToString() is "False"
```

### Expected behavior
It's ok. Please fix it to replace user to convert `False` to `false`.

### Actual behavior
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll

**Comment by elgonzo** [comment]
What is `T` ?

**Comment by kelicto** [comment]
> This is not a bug. The true/false values in Json are lower-case. In other words, capitalized False or True do not represent boolean values in json.
> 
> Quoted from the the Json spec (http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf):
> 
> > These are the three literal name tokens:
> > true U+0074 U+0072 U+0075 U+0065
> > false U+0066 U+0061 U+006C U+0073 U+0065
> > null U+006E U+0075 U+006C U+006C
> 
> Note that the Json spec goes to even specify the ordinal character value of each of the characters in those value literals. A boolean false value in json must therefore be represented by all-lowercase `false` according to the json spec.
> 
> Having capitalized literals `True` or `False` in a json document violates the Json specification, thus technically such a json document isn't actually a proper json document to begin with.
> 
> I suggest to focus your engery on trying to convince the developer responsible for the producer of such invalid json documents to fix whatever it is that produces such broken json. If that is not feasible, i am afraid you will have to manually replace all those illegal value literals in the json string/document yourself (for example, by utilizing some regex replacement or some such), before feeding the repaired json document to the deserializer.

👍
