### ISSUE TITLE
Infinite loop sometimes when deserializing

### ISSUE THREAD

**Issue by Kirschi94** [JamesNK/Newtonsoft.Json#2623]
### Description
I am calling JsonConvert.DeserializeObject() from a module which I'm using to serialize and deserialize from and to my class DailyTask. It usually just worked without problems, but after a few days strange behavior surfaced. It seems all of the files are successfully serialized, but when deserializing, some files just don't work without a visible reason.
You can get my latest build with this bug and the associated files which cause the bug [here](https://we.tl/t-6nTpkM4QYY) and see the whole project (without the error causing files) [here](https://github.com/Kirschi94/DailyTask).

### The problem
When starting my program, it accesses the files and deserializes them. I've traced the problem back to the JsonHelper.vb file, explicitly the following code:
```vb.NET
response = If(jsonSettings Is Nothing,
                JsonConvert.DeserializeObject(Of T)(data),
                JsonConvert.DeserializeObject(Of T)(data, jsonSettings))
```
where it seems to get stuck in an infinite loop. No error messages, just an infinite loop. Not with all files though, some work, some don't and I have yet to find out the differences between them, in VS Code they look all the same. The file "Tasks/-1782142616.json" is one of the offenders, "The Past/-1332471505_10.12.2021.json" is another.

So the problems seems to lie in `JsonConvert.DeserializeObject(Of T)(data)`, since I've already tried removing the option for the jsonSettings to no avail. Since every file uses that same method and I am unable to find any problems in my files either, it has to be a bug in Newtonsoft.Json.
If I overlooked something I'd like to apologize in advance, but I've searched for hours now, trying everything I can and this is the last option I got.

**Comment by Kirschi94** [comment]
I don't know how I overlooked that blatantly obvious mistake on my part. I'm very sorry, especially for wasting your time with such a rookie mistake.

**Comment by elgonzo** [comment]
> I'm very sorry, especially for wasting your time with such a rookie mistake.
Don't worry, happens to everybody. :-D
