### ISSUE TITLE
Connect to TCP IP but why ? 

### ISSUE THREAD

**Issue by Itami-Youji** [JamesNK/Newtonsoft.Json#2647]
My AV detect this after i debug my project
![NVIDIA_Share_XWZSqTZ3EC](https://user-images.githubusercontent.com/96356067/153273068-12d60baa-6de3-498f-8450-12f9216d6695.png)

IP : http://93.184.220.29/0 
content : 0

What does that mean ?

**Comment by elgonzo** [comment]
This is the issue tracker for the Newtonsoft.Json library, not a discussion forum to ask about problems with your software or your development environment.

Unless you can make a _substantive_ claim that the Newtonsoft.Json library (i am speaking about the official library as offered by the author; not downloaded from some hokey 3rd-party web-site and not some cloned or duplicated nuget package from who-knows-who), i would suggest you close this issue report here.
