### ISSUE TITLE
Which branch is 'JSON .NET For Unity' built?

### ISSUE THREAD

**Issue by zhenlinyang** [JamesNK/Newtonsoft.Json#2648]
![image](https://user-images.githubusercontent.com/6052587/153365215-d5fc9038-cf84-4a18-8205-4a7339558ea2.png)

Hi, I downloaded the Unity version of the Json library from https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347 . But I am not sure which Git branch or tag it was built from. DLL version display is 8.0.0.0. Thank you so much!

**Comment by JamesNK** [comment]
It is unofficial build of Newtonsoft.Json. I don't know where its source code is located.
