### ISSUE TITLE
Add copy constructor for JsonSerializerSettings

### ISSUE THREAD

**Issue by senbar** [JamesNK/Newtonsoft.Json#2650]
Coming from this issue: https://github.com/dotnet/aspnetcore/issues/29532
Proposed solution was to implement copy constructor on JsonSerializerSetting because MVCs shallow copy triggers set flags even with null values

When adding using AddNewtonsoftJson in ASP.NET MVC and setting ```DateFormatHandling = DateFormatHandling.MicrosoftDateFormat``` it is not used by serializer because MVC's ShallowCopy function sets DateFormatString to null which triggers flag making serializer use date format string instead of given handler. 

I will be solving issue on MVC side with difference checks in ShallowCopy, but suggested ideal answer was to add copying constructor here in Newtonsoft.Json.

**Comment by MatthewSteeples** [comment]
I've made a start in #2584 

I'll see if I can finish it off this week

**Comment by senbar** [comment]
Sorry, haven't seen there's already created issue for this.
