### ISSUE TITLE
MissingMemberHandling does not work on inner properties. #974

### ISSUE THREAD

**Issue by JacksReacher** [JamesNK/Newtonsoft.Json#2660]
``This is not a duplicate as issue #974 has been closed. 

I found this same issue serializing and deserializing an object that inherited from Exception and had an InnerException populated.

Try it on a json string that is serialized from an object that inherited from Exception where InnerException is populated and then deserialize it back... In this case, it might be because InnerException is readonly and the deserialization process can't set it, while the serialization writes it to the json.

The issue happens during deserialization.

` 
```
JsonSerializerSettings JsonSerializerSettings = new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate,
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Ignore,
                MaxDepth = 10,
            };
```

            string healthReport = JsonConvert.SerializeObject(((ObjectResult)result.Result).Value, jsonSerializerSettings);

            /// this will fail because <see cref="MissingMemberHandling.Ignore"/> is not working for inner properties
            VwacHealthReportDetails detailsReport = JsonConvert.DeserializeObject<VwacHealthReportDetails>(healthReport, jsonSerializerSettings);
            Assert.IsNotNull(detailsReport);`

Here's the json:

`
{
  "SystemUpTime": "",
  "HealthDetails": [
    {
      "Name": " ",
      "Status": "Unhealthy",
      "Description": "",
      "Exception": {
        "StackTrace": "at HealthChecks.HealthCheckService.CheckHealthAsync(CancellationToken cancellationToken) in F:\\\HealthCheck\\HealthCheckService.cs:line 69",
        "Message": "",
        "Data": {},
        "InnerException": {
          "Message": "Exception of type 'HealthCheck.ReferenceLoopTestException' was thrown.",
          "Data": {},
          "HResult": -2146233088
        },
        "Source": "System.Private.CoreLib",
        "HResult": -2146233088
      }
    },
    {
      "Name": "Config",
      "Status": "Healthy",
      "Description": "Config"
    }
  ],
  "Name": "",
  "Status": "Healthy"
}`

**Comment by elgonzo** [comment]
The problem you are describing is unrelated to MissingMemberHandling.
Where exactly is a property/field missing in either the Json or the deserialization target type?

I am not saying that you are having not a problem, i am saying that you are barking up the wrong tree with regard to MissingMemberHandling and the issue https://github.com/JamesNK/Newtonsoft.Json/issues/974.

As you yourself already noted, the issue is not about some missing properties, but about a get-only property. I also fail to understand how you could possibly claim that your problem is same issue as #974. It very much is not. That issue #974 was specifically related to MissingMemberHandling.Error (not MissingMemberHandling.Ignore), properties with public setters and -- most importantly -- about a json property that is actually _missing_ in the deserialization target type. Nothing of that applies to your problem here... ¯\\(ツ)/¯

**Comment by JacksReacher** [comment]
The error message explicitly stated that there a member (InnerException) was missing.

It's ok, have a cup of coffee or a shot of whiskey and calm down.

This too shall pass.

Thanks for looking into this.

jp
________________________________

**Comment by elgonzo** [comment]
> The error message explicitly stated that there a member (InnerException) was missing

Yes. Look at ther serialized InnerException, itself a serialized Exception object. Note that the inner exception itself is missing the "InnerException" and other required properties :-)

**Comment by JacksReacher** [comment]
and I had set the Ignore for that.....
________________________________

**Comment by elgonzo** [comment]
> and I had set the Ignore for that.....

Once more: MissingMemberHandling is a Newtonsoft.Json setting.

You configured a **Newtonsoft.Json** setting. Configuring Newtonsoft.Json settings obviously only apply to Newtonsoft.Json behavior.

System.Exception and the implementation of its constructors is obviously **NOT** part of Newtonsoft.Json.

It doesn't make any sense to expect that configuring some Newtonsoft.Json setting would change the behavior of the System.Exception constructor.... ¯\\_(ツ)_/¯

**Comment by elgonzo** [comment]
In case you didn't notice the edit to my previous comment, i'll copy it here again:

> The error is not coming from Newtonsoft.Json, though. It's not Newtonsoft.Json complaining about a missing member (such you would be able to influence with MissingMemberHandling). It's coming from inside the Exception's streaming constructor (look at the stack trace), something that is outside the scope and control of Newtonsoft.Json, and thus cannot be influenced with the MissingMemberHandling setting...

To understand why the Newtonsoft.Json setting is not applicable here, it is crucial to understand that the error did not originate with Newtonsoft.Json, but is originating from within the System.Exception constructor, something Newtonsoft.Json has no control over...
