### ISSUE TITLE
Get PropertyType in ResolveReference

### ISSUE THREAD

**Issue by LeeVermeulen** [JamesNK/Newtonsoft.Json#2670]
Is there anyway to get the PropertyType or any other information in ResolveReference? 'Context' appears to be the internal serializer

My only solution right now is to add a 'ShouldDeserialize' method in the ContractResolver just to get the PropertyType and set it as a static field. But this won't work multithreaded

```        
        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            JsonProperty jsonProperty = base.CreateProperty(member, memberSerialization);

            jsonProperty.ShouldDeserialize = instance =>
            {
                LastAssetTypeDeserializing = jsonProperty.PropertyType;
                return true;
            };
            return jsonProperty;
        }
```

```
public class IsoReferenceResolver : IReferenceResolver
    {
        public object ResolveReference(object context, string reference)
        {
            // need to get the propertytype or name or anything...
            return AssetsSystem.GetAsset(reference, IsoEngineTypeContractResolver.LastAssetTypeDeserializing);
        }
    }
```

**Comment by elgonzo** [comment]
I have to admit having a hard time wrapping my head around what you are trying to achieve. Logically, the declared type of a property should have no bearing on the which object a reference refers to. The unambiguity of a reference should normally not rely on arbitrary meta-information external to the json data itself. Nor should the semantics of a reference normally change based on the declared property type (i.e., the same reference should still refer to the same object regardless of the property this object is being assigned to is declared as `IShape` or `Rectangle`, for example.)

Which leads me to the question (my apologies for my response essentially not being more than just some question being thrown back at you): Why would you need the type of some property to resolve references? (Asked differently: why exactly would your reference resolver have to rely on that _AssetsSystem.GetAsset_ method?) Or is the object referred to not an actual part of the json data being deserialized?

**Comment by LeeVermeulen** [comment]
This is in Unity and I am trying to store references made to Unity assets, so objects outside of the JSON data being serialized. I am trying to avoid assigning unique GUID string ids to each asset, and instead keep it readable.
My solution instead of the above was to include the type information in the string reference - so something like 'Sword-InventoryItem', then when parsed it checks 'InventoryItem' assets for that 'Sword' name.
My thought was definitely this shouldn't be needed though if I could just have the context give me some information on what's being deserialized. Especially when dealing with back compatibility as types / names of assets change.

**Comment by elgonzo** [comment]
Will _all_ the asset json objects in your json data ever be such references, or do you have deal with a mix of assets objects in the json data that are either fully serialized objects or just asset references?

In case of the asset objects in the json exclusively being string references, could you perhaps switch to a JsonConverter instead (while restricting this converter to your asset type(s))?

If you can't do that (or don't like to spend effort on writing such a converter), then i guess you your current approach is probably one of the simplest solutions. And making _LastAssetTypeDeserializing_ a [`ThreadLocal<Type>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1) should allow you to run deserialization jobs concurrently (or [`AsyncLocal<Type>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1), although Newtonsoft.Json's deserialization routine is not async) .

**Comment by LeeVermeulen** [comment]
Yeah I think switching to a JsonConverter is the right path then, that will give me the property type information I am looking for when deserializing
