### ISSUE TITLE
Crash in Windows 11 (last update)

### ISSUE THREAD

**Issue by valepe** [JamesNK/Newtonsoft.Json#2672]
### Source/destination types

    public class sidKey
    {
      private const string SID_VERSION = "2.0";

      [JsonProperty("SV")]
      public string sidVersion { get; private set; }
      [JsonProperty("AV")]
      public string AppVersion { get; set; }
      [JsonProperty("DT")]
      public string DateTime { get; private set; }
      [JsonProperty("CT")]
      public string Catalog { get; set; }
      [JsonProperty("UC")]
      public string UnitCode { get; set; }
      [JsonProperty("CC")]
      public string CommercialCode { get; set; }
      [JsonProperty("CF")]
      public object[][] Configurations { get; set; }
      [JsonProperty("AC")]
      public object[][] Accessories { get; set; }
      [JsonProperty("MX")]
      public string[] Messages { get; set; }

      public sidKey()
      {
        this.sidVersion = SID_VERSION;
        this.AppVersion = String.Empty;
        this.DateTime = System.DateTime.Now.ToString("u", System.Globalization.DateTimeFormatInfo.InvariantInfo);
        this.Catalog = String.Empty;
        this.UnitCode = String.Empty;
        this.CommercialCode = String.Empty;
        this.Configurations = new object[0][] { };
        this.Accessories = new object[0][] { };
        this.Messages = new string[0];
      }

      public string Encode()
      {
        if (String.IsNullOrEmpty(this.Catalog) || String.IsNullOrEmpty(this.UnitCode) || String.IsNullOrEmpty(this.CommercialCode))
          return String.Empty;

        string json = Newtonsoft.Json.JsonConvert.SerializeObject(this);

        return json;
      }

### Steps to reproduce
Calls to NewtonSoft.Json cause a crash in my application after the kb5012643 update in Windows 11.
Prior of this update application worked fine.
This error comes up both using a manual installation of Json or with the Nuget package.

This is the error thrown:
System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
Nome file: 'System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   in Newtonsoft.Json.Utilities.EnumUtils.InitializeValuesAndNames(StructMultiKey`2 key)
   in Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   in Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   in Newtonsoft.Json.Utilities.EnumUtils.GetEnumValuesAndNames(Type enumType)
   in Newtonsoft.Json.JsonWriter.BuildStateArray()
   in Newtonsoft.Json.JsonWriter..cctor()

**Comment by elgonzo** [comment]
Well, unfortunately, Newtonsoft.Json can't fix the mess MS is committed to make with its OS.

For the version number of the System.Runtime.Serialization assembly that could not be loaded (v3.0.0.0), i believe your project targets the older .NET Framework 3.0 or 3.5.

Either wait for Microsoft to fix this blunder, try repairing the .NET Framework 3.x installation (probably the Win11 update screwed up something with the GAC), or let your software project target a more recent .NET version (like .NET 5, for example).

**Comment by valepe** [comment]
> ...
> Failing to load it indicates something is broken in regard to the presence/installation of .NET Framework 3.0 or 3.5 on your machine.

I understand your point but the problem is that the issue isn't on my test machine only but in all our customers also.
I must found a workaround or disabling Newtonsoft component because now this problem causes the crash of the application.

**Comment by bitm0de** [comment]
Open your start menu to go to the "Turn Windows features on or off" dialog and remove ".NET Framework 3.5 (includes .NET 2.0 and 3.0)" restart as needed, then turn it back on again and download the necessary files from Windows update in the next dialog. Check with gacutil /l that `System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL` is once again listed, and you should be good on that machine that took the KB5012643 update.

**Comment by valepe** [comment]
> Open your start menu to go to the "Turn Windows features on or off" dialog and remove ".NET Framework 3.5 (includes .NET 2.0 and 3.0)" restart as needed, then turn it back on again and download the necessary files from Windows update in the next dialog. Check with gacutil /l that `System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL` is once again listed, and you should be good on that machine that took the KB5012643 update.
> 
> The issue stems from the fact that `System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` has been removed from the GAC for some unknown reason with this KB update. Turning that feature off then on again is an easy way to fix the installation and correct the missing entry in the GAC.
> 
> At the end of the day this is a Microsoft issue, they messed things up with this update.

System:Runtime.Serialization Version=3.0.0.0 doesn't exist anymore. Now there is a Version=4.0.0.0
Here the row:
System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL

And now? Any suggestions?

**Comment by bitm0de** [comment]
> > Open your start menu to go to the "Turn Windows features on or off" dialog and remove ".NET Framework 3.5 (includes .NET 2.0 and 3.0)" restart as needed, then turn it back on again and download the necessary files from Windows update in the next dialog. Check with gacutil /l that `System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL` is once again listed, and you should be good on that machine that took the KB5012643 update.
> > The issue stems from the fact that `System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` has been removed from the GAC for some unknown reason with this KB update. Turning that feature off then on again is an easy way to fix the installation and correct the missing entry in the GAC.
> > At the end of the day this is a Microsoft issue, they messed things up with this update.
> 
> System:Runtime.Serialization Version=3.0.0.0 doesn't exist anymore. Now there is a Version=4.0.0.0 Here the row: System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL
> 
> And now? Any suggestions?

I don’t think you had completely removed and reformed the files through the process above. v3.0 is part of .NET 3.5. The v4.0 entry is from another coexisting .NET. Framework installation on your machine.

**Comment by valepe** [comment]
> I don’t think you had completely removed and reformed the files through the process above. v3.0 is part of .NET 3.5. The v4.0 entry is from another coexisting .NET. Framework installation on your machine. The GAC had existed for this very reason of correct assembly version resolution (or rather, this was one of a few reasons).

How can I do instruct gacutil to search for a specified framework?
Obvliously the system has more frameworks and gacutil maybe pick up the newer one

**Comment by bitm0de** [comment]
%WINDIR%\Microsoft.NET\assembly

I’m on mobile right now, but this looks correct.

**Comment by valepe** [comment]
> %WINDIR%\Microsoft.NET\assembly
> 
> I’m on mobile right now, but this looks correct. MSIL folder. I’m on Win11 right now as well with a 3.0.0.0 entry after reinstalling it with the KB still applied. I can confirm tomorrow, however this was a verified fix for me.

I installed the patch, uninstalled and reinstalled the 3.5 framework but it reports me 4.0.0.0

**Comment by valepe** [comment]
> edit: https://support.microsoft.com/es-es/topic/security-only-update-for-net-framework-3-5-for-windows-8-1-and-windows-server-2012-r2-kb4552966-bc34e1f9-2010-1131-7a90-f2f701d4ade1
> 
> CVE update here shows v3.0 for a .NET 3.5 patch.

So you installed a 8.1 patch on Win11?

**Comment by bitm0de** [comment]
> > edit: https://support.microsoft.com/es-es/topic/security-only-update-for-net-framework-3-5-for-windows-8-1-and-windows-server-2012-r2-kb4552966-bc34e1f9-2010-1131-7a90-f2f701d4ade1
> > CVE update here shows v3.0 for a .NET 3.5 patch.
> 
> So you installed a 8.1 patch on Win11?

I was using that link to confirm the version information for System.Runtime.Serialization. You do realize that it’s the same .NET Framework that gets installed on the different Windows OS versions?

**Comment by valepe** [comment]
Any suggestions on this issue?

I uninstalled and reinstalled the framework but the version remains 4.0.0.0
And, anyway, even if it works, it isn't a doable solution for the end user.

**Comment by bitm0de** [comment]
> Any suggestions on this issue?
> 
> I uninstalled and reinstalled the framework but the version remains 4.0.0.0 And, anyway, even if it works, it isn't a doable solution for the end user.

You're likely not verifying the right GAC.

You need to look at the old GAC or use an older version of the VS dev command prompt for the gacutil that searches the old one.

Older: `%WINDIR%/assembly`
Newer: `%WINDIR%/Microsoft.NET/assembly`

Unfortunately, this is the only option you have unless Microsoft publishes a fix for it.

**Comment by valepe** [comment]
> Unfortunately, this is the only option you have unless Microsoft publishes a fix for it. I was assuming you had tested the fix though, and wasn't aware that you hadn't. However, I would argue that at least a good number of end users would be able to open up the features dialog from the start menu, uncheck, restart, check it again, and restart to confirm.

No, many many users are not so skilled to follow this procedure. 
Luckly my use of Json is very limited so I removed the Newtosoft package and I format the json string with manually formattings and some calls to JavascriptSerializer.  Problem gone, no more crashes.

**Comment by bitm0de** [comment]
> > Unfortunately, this is the only option you have unless Microsoft publishes a fix for it. I was assuming you had tested the fix though, and wasn't aware that you hadn't. However, I would argue that at least a good number of end users would be able to open up the features dialog from the start menu, uncheck, restart, check it again, and restart to confirm.
> 
> No, many many users are not so skilled to follow this procedure. Luckly my use of Json is very limited so I removed the Newtosoft package and I format the json string with manually formattings and some calls to JavascriptSerializer. Problem gone, no more crashes.

I think that is an assumption that would first have to be tested. Either way, I wouldn't see it as an excuse not to provide the option. This procedure isn't as dangerous as editing the Windows registry..

At least you have a temporary solution in the meantime. 👍🏼

**Comment by bitm0de** [comment]
> Update
> Microsoft just released the kb5013943 update. With this update they fixed the issue and JSON converter restarted to work without issues

It’s not an issue with Newtonsoft as I’ve explained above.

**Comment by valepe** [comment]
> > Update
> > Microsoft just released the kb5013943 update. With this update they fixed the issue and JSON converter restarted to work without issues
> 
> It’s not an issue with Newtonsoft as I’ve explained above.

I didn't write so. I wrote that Microsoft fixed their issue and now JSON works again.

**Comment by sbge0810** [comment]
Hello everyone, I have the same problem, has anyone been able to solve the problem with an update for Windows 11?

**Comment by elgonzo** [comment]
@sbge0810 how is that the same issue as explained and discussed in this thread here? Read the error/exception message you got - it is nothing like the error as in the original issue report. "_The manifest definition of the assembly does not match the reference to the assembly_" suggests that your program ended up with a different Newtonsoft.Json assembly DLL than the one used for building your program.

Please do **NOT hijack** existing issue threads when trying to seek help with your problem unless your problem matches **to the letter** the observations and error message(s) reported in the original issue report. Rather, create your own new issue.

There is no point asking about how that might have happened -- there are too many possibilities of how this could have happened. Troubleshoot and analyze your build configuration and the deployment scheme of your project. Particularly (but not exclusively) pay attention to the dependencies used by your project and check them on what they themselves depend on. It might be one or multiple of the direct or indirect dependencies pull in a different Newtonsoft.Json version than you are using for your project...

**Comment by sbge0810** [comment]
@elgonzo  Oh thanks My solution works on Windows 10, my problem with NewtonSoft is only on Windows 11, I'm so sorry you are bothered by my question

**Comment by elgonzo** [comment]
@sbge0810 didn't i ask you in my previous comment not to respond to it? Didn't i also ask you to to create a new issue report once you have more and actionable information about your problem to share? But apparently being joyfully unbothered by that, you keep posting here in this issue thread with comments that have nothing to do with the issue this issue thread is about. Real classy, keep going...
