### ISSUE TITLE
Issue About deserializing with type name handling on assemblies loaded with Assembly.Load(Byte[])

### ISSUE THREAD

**Issue by liuweilhy** [JamesNK/Newtonsoft.Json#2675]
I have some classes on assemblies loaded with Assembly.Load(Byte[]). However, I have to load these assemblies in memory buffer, but not from dll files. When I serializing these classes, my program worked well. But when I deserializing them, it crashed.
Therefor, I tried to load assemblies by Assembly.LoadFrom(string). It worked well in both serializing and deserializing.
Would you please tell me how should I do if I have to use Assembly.Load(Byte[])? Thank you very much!

**Comment by elgonzo** [comment]
I can't see how your problem is related to Newtonsoft.Json. Please be aware that this here is the issue tracker for Newtonsoft.Json, meant to report bugs in the Newtonsoft.Json library.

If you have difficulties in making your program behave correctly, i suggest asking on a site like stackoverflow.com.

**Comment by liuweilhy** [comment]
> I can't see how your problem is related to Newtonsoft.Json. Please be aware that this here is the issue tracker for Newtonsoft.Json, meant to report bugs in the Newtonsoft.Json library as well as asking/debating about features and functions of Newtonsoft.Json.
> 
> If you have difficulties in making your program behave correctly, i suggest asking on a site like stackoverflow.com.

I'm sorry that I haven't explain this issue clearly. It's just like this issue:
[https://github.com/JamesNK/Newtonsoft.Json/issues/675](https://github.com/JamesNK/Newtonsoft.Json/issues/675)
The issue 675 has been fixed. I'll reedit this my report as soon as posible.

**Comment by liuweilhy** [comment]
I found that the deserializing error appeared after changing Assembly.LoadFrom(string assemblyPath) to Assembly.Load(Byte[] buffer). But after I set JsonSerializerSettings.TypeNameHandling to None, the error disappeared. Maybe it's my problem. So sorry to trouble you.
