### ISSUE TITLE
Deserialise not respecting type passed in for JsonPatchDocument<T>

### ISSUE THREAD

**Issue by NonyLoberts** [JamesNK/Newtonsoft.Json#2682]
### Source/destination types

```csharp
    public class MyPatchModel
    {
        public string Name { get; set; }
        public string Notes { get; set; }
    }
```

### Source/destination JSON

```javascript
"[\r\n    {\r\n      \"op\": \"replace\",\r\n      \"path\": \"/NoneExistentProperty\",\r\n      \"value\": \"Some Value\"\r\n    }\r\n]"
```

### Expected behavior

I Expected either a deserialisation error telling me it couldnt deserialise, or a model with no operations

### Actual behavior

Instead i got a model with an operation that is not valid for the type passed in
![image](https://user-images.githubusercontent.com/64289046/169500885-a2e802f1-0b41-4980-b7b8-27625ab020d4.png)

### Steps to reproduce

```csharp
JsonConvert.DeserializeObject<JsonPatchDocument<MyPatchModel>>(myJson)
```

**Comment by elgonzo** [comment]
I don't understand your expectations. There is no issue/bug here.

You are deserializing a `JsonPatchDocument<T>`. You are **not** deserializing a _MyPatchModel_.

As such, the `JsonPatchDocument<PatchModel>` instance got all the data (i.e., operation) from the json data, as should be expected.

**Comment by NonyLoberts** [comment]
> I don't understand your expectations. There is no issue/bug here.
> 
> You are deserializing a `JsonPatchDocument<TModel>`. You are **not** deserializing a _MyPatchModel_.
> 
> As such, the `JsonPatchDocument<MyPatchModel>` instance got all the data (i.e., operation) from the json data, as should be expected.
> 
> Note that the _value_ property of _Operation<TModel>_ is of type `object` (it is inherited from the non-generic _Operation_ type). Thus, from the point of view of Newtonsoft.Json, having a _"Some Value"_ string (or anything else unrelated to _MyPatchModel_ for that matter) for the operation value is totally a-okay.
> 
> If that is a problem for you that you cannot work around, you will have to take this up with the ASP.NET Core team...

I guess I assumed that the deserialising would honour the object being used, either through reflection of properties compared against the paths of some other logic. 
I feel like how it is now is misleading as I could pass any object into the deserialisation and get a list of operations that have no bearing on that type

**Comment by elgonzo** [comment]
> I feel like how it is now is misleading as I could pass any object into the deserialisation and get a list of operations that have no bearing on that type

Yeah, it kinda is. But it is not related to Newtonsoft.Json functionality, bugs or limiations. Your problem is chiefly with ASP.NET's _Operation\<TModel\>_ and ASP.NET's _TypedJsonPatchDocumentConverter_.

I unfortunately don't know what would be considered best practices with regard to handling of inapplicable operators in ASP.NET's JsonPatchDocuments. It would probably be a good question for stackoverflow.com...

**Comment by NonyLoberts** [comment]
> > I feel like how it is now is misleading as I could pass any object into the deserialisation and get a list of operations that have no bearing on that type
> 
> Yeah, it kinda is. But it is not related to Newtonsoft.Json functionality, bugs or limiations. Your problem is chiefly with ASP.NET's _Operation<TModel>_ and ASP.NET's _TypedJsonPatchDocumentConverter_.
> 
> I unfortunately don't know what would be considered best practices with regard to handling of inapplicable operators in ASP.NET's JsonPatchDocuments. It would probably be a good question for stackoverflow.com...

No problem. I appreciate your time and patience! I'll try to find an alternative solution.
