### ISSUE TITLE
Should WriteValue(DateOnly/TimeOnly) be added to JsonWriter?

### ISSUE THREAD

**Issue by SimonCropp** [JamesNK/Newtonsoft.Json#2684]
In the recent beta, DateOnly and TimeOnly have been added. But they were not added to JsonWriter

So should these exist?

        public virtual void WriteValue(DateOnly value)
        {
            InternalWriteValue(JsonToken.DateOnly);
        }
        public virtual void WriteValue(TimeOnly value)
        {
            InternalWriteValue(JsonToken.TimeOnly);
        }

**Comment by SimonCropp** [comment]
@JamesNK would you like me to have a go at a PR for this?

**Comment by JamesNK** [comment]
Why should they be added? One benefit is avoiding an intermediary string allocation, but that means taking over creating the string generation for these types. It's a fair bit of work for one allocation. `JsonReader.ReadAsDateOnly`, `JsonReader.ReadAsTimeOnly` would then be needed to avoid the string allocation in the opposite directory.

There are many other primitive-ish types in newer .NETs, e.g. Int128, UInt128, Half. I don't want to invest a ton of time and add complexity in optimizing for every little thing.

**Comment by SimonCropp** [comment]
ok.
