### ISSUE TITLE
Break from 12.0.3 to 13.0.1 with [JsonExtensionData]

### ISSUE THREAD

**Issue by NickCraver** [JamesNK/Newtonsoft.Json#2708]
We're hitting an issue in production after a 13.0.1 upgrade unable to deserialize JSON. Though the actual code involved `JToken.ToObject<T>()` the repro is the same with a simplified `JsonConvert.DeserializeObject<T>()` so using that below. I've tested this scenario and our code is working up through 12.0.3 but it breaks in 13.0.1 and I can't find any release notes or issues that _seem_ to be the cause.

### Full repro
```csharp
void Main()
{
    string json = @"
{
  ""Name"": ""MyName"",
  ""ChildClassProp"": ""MyValue"",
}";

    // JsonSerializationException: 
    // Unexpected token when deserializing object: String. Path 'ChildClassProp', line 4, position 29.
    JsonConvert.DeserializeObject<MyRecord>(json);
}

[DataContract]
public abstract class RecordBase
{
    [JsonExtensionData]
    protected IDictionary<string, JToken> additionalData;

    public string Name { get; set; }
}

[DataContract]
public class MyRecord : RecordBase
{    
    public MyRecord(string childClassProp) => ChildClassProp = childClassProp;
    
    [DataMember]
    public string ChildClassProp { get; set; }
}
```

I have found that removing `[JsonExtensionData]` (needed for round-tripping) makes it behave as expected as does adding a default constructor to the `MyRecord` class (which would be a large number of locations and not desirable in the codebase). It also works adding a `[DataMember]` to `Name` in the base class (which makes sense, but the behavior change has broken us so filing here!)

I can also more minimally repro (left above in case base is important):

```csharp
[DataContract]
public class MyRecord
{
    public MyRecord(string _) {}

    [JsonExtensionData]
    protected IDictionary<string, JToken> additionalData;

    public string Name { get; set; }
}
```

Perhaps it can't tell without the `[DataMember]` on `Name` which items should be in the extension data? Hazarding a guess here.

### Expected behavior

Deserialization to work as it did in `<= 12.0.3`, producing a populated `MyRecord`.

### Actual behavior

Exception when calling `JsonConvert.DeserializeObject<MyRecord>(json)`:
> JsonSerializationException: Unexpected token when deserializing object: String. Path 'ChildClassProp', line 4, position 29.

cc @glennamanns

**Comment by JamesNK** [comment]
Thanks for the clear reproduction. Fixed.

**Comment by rghodki23** [comment]
@JamesNK - Do we know when the new Newtonsoft.JSON version will be available? Our CPLAT platform is on hold to update the package version to 13.0.1 because we are not sure of the impact when we start the rollout on production, so waiting for the next newtonsoft.JSON version.

**Comment by sam8dec** [comment]
@JamesNK Had the same question. Looks like 13.0.2 is in beta. Would you know when it would be officially released?

**Comment by Aishwarya-C-S** [comment]
@JamesNK, could you please share when this would be officially released?

**Comment by JamesNK** [comment]
In 6 months.

**Comment by Aishwarya-C-S** [comment]
> In 6 months.

thank you
