### ISSUE TITLE
Serialize and Deserialize to/from struct in net6+

### ISSUE THREAD

**Issue by david-c-stein** [JamesNK/Newtonsoft.Json#2734]
Feature Request:

The ability to serialize and deserialize to/from a struct in csharp net6+

**Comment by elgonzo** [comment]
Uh... it already can, since pretty much forever...

**Comment by david-c-stein** [comment]
Thank you for the clarification

**Comment by bartelink** [comment]
This is where you close the issue so people don't traverse it any longer ....
