### ISSUE TITLE
How to Custom Data-AttributesJsonConverter

### ISSUE THREAD

**Issue by fasteddys** [JamesNK/Newtonsoft.Json#2745]
In extending (but failed), I am unable to get the right data-attribute format, I tried to extend but the unable to get the data-attribute output, _so I can **embed** the string **inside a div tag with the attributes as property names/key, and values**_

> Can you please help:  in formatting `C#` objects `properties : values` to get output in HTML5` data attributes=values`, as example below

**From this:**
```
// sample instance with values of customer liz
public class Customer
{
    // deserialize the objects public properties & values ..  to HTML `data-key(or attribute) = [value]`
    Name = Liz;
    Type  =  Premium;
    Address =  Srilanka 12 st
}

//  --> to this JSON object

Id1 : { 
   // Name & Type are C# POCO the object property,
   data-Name="Liz" ,
    data-Type="Premium" },

Id2: { 
    data-Name="bell" ,
    data-Type="Gold" 
  }
...

```

**To this:**
I want to get it in the form of HTML5
 `data-property`=`[value]` needs to be  `data-Name`=`[Liz]` , but I am getting a nested list rather that a string... added to the `data-*` attributes in HTML5

> is there a json HTML stringify way to deserialize the object so that all the values into this format -> data-`property name`=["{`property-value`}"]

how to get this HTML ??

I want to embded the json string inside a div tag  `<div ...   data-Name="Liz" data-Type="Premium"> Your Order</>`?

______________

    public class DataAttributesJsonConverter : JsonConverter
    {
        private readonly Type[] _types;
    
        public DataAttributesJsonConverter (params Type[] types)
        {
            _types = types;
        }
    
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            JToken t = JToken.FromObject(value);
    
            if (t.Type != JTokenType.Object)
            {
                t.WriteTo(writer);
            }
            else
            {
                JObject o = (JObject)t;
                IList<string> propertyNames = o.Properties().Select(p => p.Name).ToList();
    
                o.AddFirst(new JProperty("data-", new JArray(propertyNames)));
    
                o.WriteTo(writer);
            }
        }

**Comment by elgonzo** [comment]
It is imo better to ask questions to the effect of "_how do i achieve this or that while using Newtonsoft.Json_" over on https://stackoverflow.com, as this here is Newtonsoft.Json's _issue_ tracker meant for reporting _issues_ / bugs with the library and related resources such as its documentation.
