### ISSUE TITLE
Documentation Page Seems to be Missing Info on Encoding

### ISSUE THREAD

**Issue by BlitzkriegSoftware** [JamesNK/Newtonsoft.Json#2756]
I did this search:
![image](https://user-images.githubusercontent.com/6732665/200417927-b5a1db64-41c5-4def-84a2-f98201a2af83.png)
And found nothing. Is there another keyword to use? Searching on UTF8 brings that up as data in an example. Some pages that discuss encoding UTF8, etc. would be greatly appreciated.

**Comment by elgonzo** [comment]
Why would the Newtonsoft.Json documentation need to discuss encodings like UTF-8 or others? It simply is not a concern of the library.

For Json, only strings or System.IO.TextReader/System.IO.TextWriter (either directly or through JsonReader/JsonWriter) are supported for input and output by the Newtonsoft.Json library. And text encoding is chiefly a concern and scope of System.IO.TextReader/System.IO.TextWriter (which have their own documentation over at learn.microsoft.com/en-us/dotnet/api).

With respect to BSON input/output (also supported by Newtonsoft.Json), text strings in BSON are UTF-8 as required by the BSON specification. As the BSON spec is publicly available (https://bsonspec.org/spec.html), there is not really a need for the Newtonsoft.Json documentation to repeat what is already written in the BSON spec.

**Comment by BlitzkriegSoftware** [comment]
Those are all excellent points, that could be added to an encoding page, with links to the standards you discussed here.

Having it in the documentation allows Corp. Compliance Orgs. to check the box and move on.

I would hope the level of effort would be minimal.

With deepest gratitude for my favorite library, and your time,


Stuart Williams
***@***.******@***.***>
________________________________
