### ISSUE TITLE
Support CSV with serializer

### ISSUE THREAD

**Issue by agowa338** [JamesNK/Newtonsoft.Json#2764]
### Source/destination types

```csharp
  public record RootGetResponse(
    [property: JsonProperty("data")] ServerCsvData Data
  );

  [Delimiter(",")]
  public record class ServerCsvData
  (
    [property: Name("Header001")] string Header001,
    [property: Name("Header002")] string Header002,
    [property: Name("Header003")] int Header003
  );
```

### Source/destination JSON

```javascript
{"data":"\"Header001\",\"Header002\",\"Header003\"\n\"Value001\",\"Value002\",\"3\""}
```

### Expected behavior

Interoperability with CSV parser from CSVHelper.

### Actual behavior

Newtonsoft.Json.JsonSerializationException "Error converting value"

### Steps to reproduce

```csharp
var response = httpClient.GetAsync("api/getData");
response.EnsureSuccessStatusCode();
RootGetResponse rootGetResponse = await response.Content.ReadAsAsync<RootGetResponse>();
```

**Comment by elgonzo** [comment]
A JSON serializer is not a CSV serializer, and in my honest opinion it seems to be rather outlandish to expect or ask for a JSON serializer to be able to deserialize CSV data that has been haphazardly "packaged" into a JSON string. (Disclaimer: I am not affiliated in any way or form with the Newtonsoft.Json project nor any of its maintainers.)

If you got a string in your json data that is basically CSV data, you will need to process that CSV text after the JSON deserialization. One way to do this could be a [custom JsonConverter](https://www.newtonsoft.com/json/help/html/CustomJsonConverterGeneric.htm) (which you will have to write, if you can't find one offered ready for use) applied to those properties of your C# models which contain CSV text strings in the respective JSON properties. The custom JsonConverter's task (specifically that of its ReadJson method) is then basically to read the string value, process it as CSV in whatever way you need/want, and create an object instance of the appropriate type and return it.

**Comment by agowa338** [comment]
> A JSON serializer is not a CSV serializer

But XML is part of a JSON serializer?
![image](https://user-images.githubusercontent.com/2544867/205465057-d2b26296-a71f-4795-8c96-4be5f2c22d95.png)

**Comment by elgonzo** [comment]
> But XML is part of a JSON serializer?

FYI: Newtonsoft.Json, does not de/serialize XML, neither standalone XML nor XML text put into JSON strings. All Newtonsoft.Json supports is conversion between JObject and XElement/XmlElement. (The latter two being types from the BCL.)

**Comment by elgonzo** [comment]
> But XML is part of a JSON serializer?

It's not what you seem to assume. All Newtonsoft.Json supports is JSON de/serialization of XElement/XmlElement object instances. Newtonsoft.Json does not de/serializize standalone XML text nor XML text embedded as strings in JSON data.
