### ISSUE TITLE
Polymorphic deserialization requires type discriminator to be at beginning of the object

### ISSUE THREAD

**Issue by ophirKatz** [JamesNK/Newtonsoft.Json#2770]
### Source/destination types

```csharp
abstract class A
{
    public int Num { get; set; }
}
class B : A
{
}
```

### Source/destination JSON

```javascript
{
    Num: 1,
    $type: 'B, JsonTest',
}
```

### Expected behavior

Deserializing a polymorphic object should consider the type discriminator where ever it appears in the object.
In the given example, an object of type B should be constructed successfully.

### Actual behavior

With the given example, the following exception is thrown:
Newtonsoft.Json.JsonSerializationException: 'Could not create an instance of type A. Type is an interface or abstract class and cannot be instantiated

### Steps to reproduce

```csharp
var settings = new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.Objects
};

var obj = JsonConvert.DeserializeObject<A>(jsonString, settings);
```

## Note:
If this is expected behavior, then it should be documented. I did not find any mention to this limitation in the docs.

**Comment by JamesNK** [comment]
https://www.newtonsoft.com/json/help/html/SerializationSettings.htm

![Uploading image.png…]()
