### ISSUE TITLE
Enum serialization inside class with DataContractAttribute

### ISSUE THREAD

**Issue by obourdagesbell** [JamesNK/Newtonsoft.Json#2776]
Hello, I try to understand why the Enum is excluded from the serialization when the class has DataContractAttribute. See test bellow. Using Newtonsoft.Json:13.0.1

### Expected behavior

Enum is serialized

### Actual behavior

Enum is excluded

### Steps to reproduce

```csharp
public class SerializationTest
{
        [Fact]
        public void Should_Serialize_Enum()
        {
          var test = new Test
          {
            Value = ValueEnum.Approved
          };
          var serialized = JsonConvert.SerializeObject(test);
  
          // current result is "{}";
          Assert.Equal("{\"value\":\"approved\"}", serialized);
        }
 }

    [DataContract]
    public class Test
    {
      [DataMember(Name="value",EmitDefaultValue=false)] 
      public ValueEnum Value { get; set; }
    }

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValueEnum
    {
      [EnumMember(Value = "approved")]
      Approved
    }
```

**Comment by obourdagesbell** [comment]
found out that the EmitDefaultValue=false is causing the issue. But I still don't understand why since the field is initialized.

**Comment by elgonzo** [comment]
Good to hear you solved your problem quickly. If you could be so kind, please close this issue here whenever it's convenient for you. (You as the creator of this issue thread should see a "Close" button at the bottom of the thread to do so.) Cheers!
