### ISSUE TITLE
DefaultDateFormatString should use fffffff instead of FFFFFFF

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [JamesNK/Newtonsoft.Json#2780]
### Overview
```csharp
DateTime earlierTime = DateTime.Parse("2017-11-21 05:55:27.064100").ToUniversalTime();
DateTime laterTime = DateTime.Parse("2017-11-21 05:55:27.064109").ToUniversalTime();

// Prints "2017-11-21T05:55:27.0641Z" (4 digits of fractional seconds)
Console.WriteLine(JsonConvert.SerializeObject(earlierTime));
// Prints "2017-11-21T05:55:27.064109Z" (7 digits of fractional seconds)
Console.WriteLine(JsonConvert.SerializeObject(laterTime));
```

If I sort the JSON dates in the above example, they'll sort incorrectly, because their fractional seconds are different lengths.

### Proposed fix
The issue seems to be that Newtonsoft uses `FFFFFFF` instead of `fffffff` in the date time formatter, and `FFFFFFF` drops trailing zeros: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#FFFFFF_Specifier

If we use `fffffff` instead of `FFFFFFF` in the date formatting string, the trailing zeroes are preserved, and the dates can be reliably sorted:

```csharp
DateTime dateTimeWithFractionalSeconds = DateTime.Parse("2017-11-21 05:55:27.064100").ToUniversalTime();

// Prints "2017-11-21T05:55:27.0641Z"
Console.WriteLine(JsonConvert.SerializeObject(dateTimeWithFractionalSeconds));

// Prints "2017-11-21T05:55:27.0641000Z"
Console.WriteLine(JsonConvert.SerializeObject(dateTimeWithFractionalSeconds, new JsonSerializerSettings{DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK"}));
```
(Fiddle: https://dotnetfiddle.net/b7jfah)

I'd like to propose that `JsonSerializerSettings::DefaultDateFormatString` be changed from `yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK` to `yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK`, so that the emitted time JSON are always the same length and can be reliably sorted 🙂

### Notes
This has been mentioned before a few times, but maybe it wasn't clear what those issues were asking for:
* https://github.com/JamesNK/Newtonsoft.Json/issues/1511
* https://github.com/JamesNK/Newtonsoft.Json/issues/1709

Thanks! 🙂

**Comment by elgonzo** [comment]
Why is it unsuitable for you to specify the desired DateTime format string in the [JsonSerializerSettings](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_DateFormatString.htm)?

**Comment by Bosch-Eli-Black** [comment]
After thinking about this some more, I now understand why the default time format string uses `FFFFFFF` instead of `fffffff`: Many datetimes don't have fractional seconds, and appending `.0000000` to datetimes that only have whole seconds would be unexpected.

For example:
```c#
DateTime dateTimeWithFractionalSeconds = DateTime.Parse("2017-11-21 05:55:27").ToUniversalTime();

// Prints "2017-11-21T05:55:27Z"
Console.WriteLine(JsonConvert.SerializeObject(dateTimeWithFractionalSeconds));

// Prints "2017-11-21T05:55:27.0000000Z", which is unexpected.
Console.WriteLine(JsonConvert.SerializeObject(dateTimeWithFractionalSeconds, new JsonSerializerSettings{DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK"}));
```

The upshot being that if you need your JSON datetimes to be sortable or comparable (e.g. they're being put into a JSON-backed DB, such as Azure Cosmos), you need to manually specify `fffffff` in your JSON settings:

```c#
var jsonSerializerSettings = new JsonSerializerSettings
{
    // The default JSON serializer uses this DateTime format string: yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK
    // Using FFFFFFF means that trailing zeros in fractional seconds are truncated, which can lead to JSON
    // with dates of different lengths being emitted.
    // e.g.
    // 2017-11-21T05:55:27.064Z
    // 2022-03-18T09:32:91.1028371Z
    // 
    // Having dates strings of different lengths can cause the dates to be sorted incorrectly,
    // so to get JSON dates with consistent lengths, we override the date format string and use fffffff instead of FFFFFFF.
    // 
    // See https://github.com/JamesNK/Newtonsoft.Json/issues/2780
    DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK"
};
```

**Comment by Bosch-Eli-Black** [comment]
Thanks for looking at this, @elgonzo 🙂

I've come to the same conclusion: Using `FFFFFFF` for the default time format string makes sense, and if we need to have sortable/comparable JSON datetimes, we should override the format string to use `fffffff`

Thanks again 🙂
