### ISSUE TITLE
当jtoken为数组时，while(await reader.ReadAsync())只能读取[0],也就是说只能循环一次

### ISSUE THREAD

**Issue by xiaomazz** [JamesNK/Newtonsoft.Json#2784]
foreach (JToken item in entry)
  {
      var reader = item?.CreateReader();
     //item为数组field_36:["xxxxxx","yyyyy"],应该是循环两次，但是循环一次后就直接进入了下一个token，并没有循环第二次
      while (await reader?.ReadAsync()!)
      {
      }
}
![image](https://user-images.githubusercontent.com/52307384/209917370-68d8b0c9-7fce-427d-b263-1aa27d0c4050.png)

**Comment by elgonzo** [comment]
You have to test for the **token type** (JsonReader.TokenType) first. Structural json symbols like `{`, `}`, `[` and `]` that mark the beginning and end of json objects and arrays are tokens that do _not_ have a value (hence _reader?.Value_ being _null_). See here for an example of how the JsonReader behaves: https://www.newtonsoft.com/json/help/html/ReadJsonWithJsonTextReader.htm

**Comment by xiaomazz** [comment]
![image](https://user-images.githubusercontent.com/52307384/210026048-2bd5a1fa-3f3a-4663-83e2-b3bfccb5845d.png)

**Comment by xiaomazz** [comment]
![image](https://user-images.githubusercontent.com/52307384/210026973-fcda0eae-ca3d-47e1-9eff-2c372ab77da6.png)
