### ISSUE TITLE
Serious loss of precision when converting a decimal inside a object[]

### ISSUE THREAD

**Issue by HypsyNZ** [JamesNK/Newtonsoft.Json#2854]
When serializing and deserializing an `object[]` that contains a decimal there is an insane loss of precision.

This decimal could have another `8` values after the decimal place but its already failing this simple test

I'm using version `13.0.3`

### Source/destination types

```csharp
public class SimpleType
{
    public object[] Test = new object[1] { 14235653456.34456456788999345345m };
}
```
![dec](https://user-images.githubusercontent.com/54571583/236657307-c996a194-f07d-48a8-bf08-f0cce775d114.png)

### Source/destination JSON

```javascript
{
  "Test": [
    14235653456.344564567889993453  //- Wrong and then the deserialized value is even worse
  ]
}
```

![wrong](https://user-images.githubusercontent.com/54571583/236657321-4859c67d-0b17-43b9-a484-f1530990f462.png)

### Expected behavior

The decimal `14235653456.34456456788999345345m` would be the output, 

`Decimals` end with an `m` and `Doubles` end with a `d` so I don't see any reason for the confusion.

### Actual behavior

A double that is a completely different value was in the output `14235653456.344564`

### Methods called

![completely wrong](https://user-images.githubusercontent.com/54571583/236656694-6682c127-234d-4fa7-acce-44718c3fd601.png)

```csharp
var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res); 
```

### Notes

Even if you change the decimal to something else like `14235653456.3445645678m` the behaviour will still be produced.

![test2](https://user-images.githubusercontent.com/54571583/236657684-7e4ad4d0-989d-4fdf-a174-fe3eeaeb1ed7.png)

## Reproduce

```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel;
	public static void Main()
	{		
		testViewModel = new SimpleType();
		
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
				
		if(simpleRight.Test[0].GetType() == typeof(double))
		{
			Console.WriteLine("This is a double now");
		}
		
		Console.WriteLine(simpleRight.Test[0].ToString());
	}

	public class SimpleType
	{
		public object[] Test = new object[1]{14235653456.34456456788999345345m};
	}
}

// This is a double now
// 14235653456.3446
```

You can even reproduce this with [`DotNetFiddle`](https://dotnetfiddle.net/Rxwofj)

**Comment by HypsyNZ** [comment]
![test2](https://user-images.githubusercontent.com/54571583/236657684-7e4ad4d0-989d-4fdf-a174-fe3eeaeb1ed7.png)

**Comment by sungam3r** [comment]
What if you set ` FloatParseHandling = FloatParseHandling.Decimal` ?

**Comment by HypsyNZ** [comment]
Irrelevant.

**Comment by HypsyNZ** [comment]
I wouldn't waste my time reporting this if it wasn't a bug.

**Comment by HypsyNZ** [comment]
`14235653456.3445645678m` - Decimal
`14235653456.34456456788999345345m` - Decimal

`14235653456.3446` - Double

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel;
	public static void Main()
	{
		testViewModel = new SimpleType();
		
		JsonSerializerSettings newSettings = new JsonSerializerSettings()
		{
			FloatParseHandling = FloatParseHandling.Decimal
		};
		
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
		
		if (simpleRight.Test[0].GetType() == typeof(double))
		{
			Console.WriteLine("This is a double now");
		}

		Console.WriteLine(simpleRight.Test[0].ToString());
	}

	public class SimpleType
	{
		public object[] Test = new object[1]{14235653456.34456456788999345345m};
	}
}
```

```cs
This is a double now
14235653456.3446
```

I wouldn't waste my time reporting this if it wasn't a bug, do you need any more information, 

its reproducible, its not just happening on my machine.

Without Settings: https://dotnetfiddle.net/Rxwofj

With Settings: https://dotnetfiddle.net/7SIEYf

**Comment by sungam3r** [comment]
`SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);`
->
`SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res, newSettings);`

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel;
	public static void Main()
	{
		testViewModel = new SimpleType();
		
		JsonSerializerSettings newSettings = new JsonSerializerSettings()
		{
			FloatParseHandling = FloatParseHandling.Decimal
		};
		
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
		
		if (simpleRight.Test[0].GetType() == typeof(double))
		{
			Console.WriteLine("This is a double now");
		}

		Console.WriteLine(simpleRight.Test[0].ToString());
	}

	public class SimpleType
	{
		public object[] Test = new object[1]{14235653456.34456456788999345345m};
	}
}
```

```cs
This is a double now
14235653456.3446
```

I wouldn't waste my time reporting this if it wasn't a bug, do you need any more information, 

its reproducible, its not just happening on my machine.

Without Settings: https://dotnetfiddle.net/Rxwofj

With Settings: https://dotnetfiddle.net/7SIEYf

**Comment by HypsyNZ** [comment]
```cs
var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res, newSettings);
```

Wow okay my bad.

**Comment by sungam3r** [comment]
`m` means _money_ as decimals numbers were designed to work with money.

**Comment by HypsyNZ** [comment]
> `m` means _money_ as decimals numbers were designed to work with money.

Oh that is interesting (and wrong) what do you imagine the `d` for Double and the `L` for long mean then?

**Comment by sungam3r** [comment]
`d` means _double_ and `L` means _long_ obviously

> this information was present before you destroyed it

I don't understand. I'm glad you managed to solve that issue.

**Comment by HypsyNZ** [comment]
> `d` means _double_ and `L` means _long_ obviously
> 
> > this information was present before you destroyed it
> 
> I don't understand. I'm glad you managed to solve that issue.

`123123123L` is a long
`123123123.0d` is a double
`123123123m` is a decimal

You wouldn't require special settings if you didn't destroy the information and don't call it an optimization because your serializer is slow.

**Comment by HypsyNZ** [comment]
I could report another 500 variations of this bug and you would still find excuses not to fix it.

**Comment by HypsyNZ** [comment]
I don't understand how this is a first party library when you deliberately destroy important data relevant to the type.

**Comment by sungam3r** [comment]
Sorry but it's not **my** serializer and I'm not destroying anything. Maybe @JamesNK may put some comments here about design.

**Comment by HypsyNZ** [comment]
You can't be sure what the type is inside of the `object[]` so you should be preserving the `m` `d` `L`

I'm not here to argue about anything, Its a fact.

**Comment by HypsyNZ** [comment]
123123123m is a decimal
123123123L is a long

Also you seem to think `int` is a `long` inside `object[]`

**Comment by HypsyNZ** [comment]
`123123123m` is a `decimal`
`123123123L` is a `long`
`123123123` is an `int`

You will say they are all longs inside `object[]`

**Comment by HypsyNZ** [comment]
You can't be sure what the type is inside of the `object[]` so you should be preserving the `m` `d` `L` `f` etc.

`123123123m` is a `decimal`
`123123123L` is a `long`
`123123123` is an `int`

You will say they are all longs inside `object[]`

**Comment by sungam3r** [comment]
@HypsyNZ Sorry, but it's rather hard to me to have a further coversation here because your comments are constantly changing. If you have questions about the design of NSJ, then you can address them to the authors of the project. Thanks.

**Comment by HypsyNZ** [comment]
You can't be sure what the type is inside of the `object[]` so you should be preserving the `m` `d` `L` `f` etc.

`123123123m` is a `decimal`
`123123123L` is a `long`
`123123123` is an `int`

You will say they are all `longs` inside `object[]`

**Comment by HypsyNZ** [comment]
You are making it impossible to report a serious flaw with the library and I don't find your input constructive at all.

**Comment by HypsyNZ** [comment]
Okay I'll make a new issue and maybe you'll understand this time.
