### ISSUE TITLE
Type not preserved correctly in `object[]`

### ISSUE THREAD

**Issue by HypsyNZ** [JamesNK/Newtonsoft.Json#2855]
You can't be sure what the type is inside of the `object[]` so you should be preserving the `m` `d` `L` `f` etc.

`123123123d` is a `double`
`123123123m` is a `decimal`
`123123123L` is a `long`
`123123123` is an `int`

```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
		Console.WriteLine(simpleRight.Simple[3].GetType());
	}

	public class SimpleType
	{
		// Int64
		// Int32
		// Double
		// Decimal
		public object[] Simple = new object[4] { 123123123L, 123123123, 123123123d, 123123123m };
	}
}
```
```cs
System.Int64
System.Int64
System.Double
System.Double
```

`FloatParseHandling = FloatParseHandling.Decimal`

```cs
System.Int64
System.Int64
System.Decimal
System.Decimal
```

**Comment by HypsyNZ** [comment]
```cs
// long
// int
// decimal
object simple = new object[3] { 123123123L, 123123123, 123123123d };
```

After serializing and then deserializing this object you will say all of the values are `longs`

**Comment by HypsyNZ** [comment]
```cs
// long
// int
// decimal
object[] simple = new object[3] { 123123123L, 123123123, 123123123d };
```

After serializing and then deserializing this object you will say all of the values are `longs`

**Comment by HypsyNZ** [comment]
```cs
public class SimpleType
{
    // long
    // int
    // decimal
    object[] Simple { get; set; } = new object[3] { 123123123L, 123123123, 123123123d };
}
```

After serializing and then deserializing this object you will say all of the values are `longs`

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		testViewModel = new SimpleType();
		JsonSerializerSettings newSettings = new JsonSerializerSettings()
		{FloatParseHandling = FloatParseHandling.Decimal};
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res, newSettings);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
	}

	public class SimpleType
	{
		// long
		// int
		// decimal
		public object[] Simple = new object[3]{123123123L, 123123123, 123123123d};
	}
}
```
```cs
System.Int64
System.Int64
System.Decimal
```

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		testViewModel = new SimpleType();
		JsonSerializerSettings newSettings = new JsonSerializerSettings()
		{FloatParseHandling = FloatParseHandling.Decimal};
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res, newSettings);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
	}

	public class SimpleType
	{
		// long
		// int
		// double
		public object[] Simple = new object[3]{123123123L, 123123123, 123123123d};
	}
}
```
```cs
System.Int64 - Correct
System.Int64 - Wrong should be int
System.Decimal - Wrong should be double
```

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		testViewModel = new SimpleType();
		JsonSerializerSettings newSettings = new JsonSerializerSettings()
		{FloatParseHandling = FloatParseHandling.Decimal};
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented, newSettings);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res, newSettings);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
	}

	public class SimpleType
	{
		// long
		// int
		// double
		public object[] Simple = new object[3]{123123123L, 123123123, 123123123d};
	}
}
```
```cs
System.Int64 - Correct
System.Int64 - Wrong should be int
System.Decimal - Wrong should be double
```

If I change the settings back to default

```cs
var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
```
```cs
System.Int64
System.Int64 - wrong should be Int32
System.Double
```

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		testViewModel = new SimpleType();
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
		Console.WriteLine(simpleRight.Simple[3].GetType());
	}

	public class SimpleType
	{
		// long
		// int
		// double
		// decimal
		public object[] Simple = new object[4] { 123123123L, 123123123, 123123123d, 123123123m };
	}
}
```
```cs
System.Int64
System.Int64
System.Double
System.Double
```

**Comment by HypsyNZ** [comment]
`FloatParseHandling = FloatParseHandling.Decimal`

```cs
System.Int64
System.Int64
System.Decimal
System.Decimal
```

**Comment by HypsyNZ** [comment]
This will cause an invalid cast exception

**Comment by HypsyNZ** [comment]
```cs
using System;
using Newtonsoft.Json;

public class Program
{
	public static SimpleType testViewModel = new SimpleType();
	public static void Main()
	{
		var res = JsonConvert.SerializeObject(testViewModel, Formatting.Indented);
		SimpleType simpleRight = JsonConvert.DeserializeObject<SimpleType>(res);
		Console.WriteLine(simpleRight.Simple[0].GetType());
		Console.WriteLine(simpleRight.Simple[1].GetType());
		Console.WriteLine(simpleRight.Simple[2].GetType());
		Console.WriteLine(simpleRight.Simple[3].GetType());
	}

	public class SimpleType
	{
		// long
		// int
		// double
		// decimal
		public object[] Simple = new object[4] { 123123123L, 123123123, 123123123d, 123123123m };
	}
}
```
```cs
System.Int64
System.Int64
System.Double
System.Double
```

**Comment by HypsyNZ** [comment]
This will cause `invalid cast exception`

**Comment by HypsyNZ** [comment]
This will cause `invalid cast exception` when consumed after deserialization.

**Comment by HypsyNZ** [comment]
This can also cause a loss of precision.

**Comment by elgonzo** [comment]
While there is a serializer setting for enabling type metadata (TypeNameHandling), it unfortunately doesn't apply to numeric value types. That would leave you currently (whether you like it or not) with the only option to write your own JsonConverter for not-strongly typed collections (such as object[] or List\<object\>, for example) that serializes each item in such a collection in a way that allows the converter to identify and reconstruct the proper .NET value instance for each item during deserialization.

By the way, expanding the typename handling to also cover numeric types has been asked for in the past [like here](https://github.com/JamesNK/Newtonsoft.Json/issues/728#issuecomment-459304455), but unfortunately it doesn't seem to have received any attention so far. :cry:

**Comment by HypsyNZ** [comment]
Are you trying to imply this isn't a serious flaw in the library.

**Comment by HypsyNZ** [comment]
Are you really going with "we don't support the most basic type in .NET"

**Comment by HypsyNZ** [comment]
Are you really going with "we don't support the most basic type in .NET" because if that is the case I think you should take `.NET` off the name if you are serious.

**Comment by HypsyNZ** [comment]
Are you really going with "we don't support the most basic type in .NET" 

I think you should take `.NET` off the name if you are serious.

**Comment by HypsyNZ** [comment]
> paraphrasing:  we don't support `object`, which is the most basic type in .NET

I think you should take `.NET` off the name if you are serious.

**Comment by HypsyNZ** [comment]
> paraphrasing:  we don't support `object`, which is the most basic type in `.NET`

I think you should stop calling it  `Json.NET` if you are serious.

**Comment by HypsyNZ** [comment]
This isn't just a bug.

Its a flaw.

You are destroying type information that previously existed.

**Comment by HypsyNZ** [comment]
This isn't just a bug.

Its a flaw.

You are destroying type information that previously existed and then pretending you just can't do it.

**Comment by HypsyNZ** [comment]
This isn't just a bug.

Its a flaw.

You are destroying type information that previously existed, There is no ambiguity except for the ambiguity you added.

You are not truly representing anything, you shouldn't even be calling them `long` `decimal` `double` or `long` the way you are representing them in the absence of type information is just simply incorrect.

**Comment by HypsyNZ** [comment]
This isn't just a bug.

Its a flaw.

You are destroying type information that previously existed, There is no ambiguity except for the ambiguity you added.

You are not truly representing anything, you shouldn't even be calling them `long` `decimal` `double` or `long` the way you are representing them in the absence of type information is just simply incorrect, this is exactly why `f` `m` `d` `L` exist.

**Comment by HypsyNZ** [comment]
Also change your namespace who do you think you are

**Comment by elgonzo** [comment]
Are you high? I am not the author of the library, nor otherwise associated with it. I just told you the current state of the library.
Perhaps take a walk and get some fresh air instead of being a primo arsehole and having a meltdown here in the Github issue tracker...

Also, JSON is a data format that is unrelated to .NET data types. The JSON syntax itself has no means to distinguish between different .NET data types for real numbers. Numeric values in JSON are either integer numbers or real numbers. No decimal, no float, no double, no Int32 or Int64. That's it. If you can't stomach that, stop using the JSON format and invent your own. Or bark at a tree. My gosh...

**Comment by JamesNK** [comment]
> This isn't just a bug.
> 
> Its a flaw.
> 
> You are destroying type information that previously existed, There is no ambiguity except for the ambiguity you added.
> 
> You are not truly representing anything, you shouldn't even be calling them `long` `decimal` `double` or `long` the way you are representing them in the absence of type information is just simply incorrect, this is exactly why `f` `m` `d` `L` exist.

It's a limitation. JSON isn't .NET. They use different types. For example, .NET's number suffixes don't exist in JavaScript/JSON. `100m` isn't a valid JSON number.

If you don't specify the type you want to deserialize to then the serializer has to do its best. If you don't like the result then there are many options, such as serializing numbers as strings, or writing a JSON converter, but serializers aren't magic. They can only do their best with the situation you give them.

This is expected behavior.

**Comment by HypsyNZ** [comment]
Its not a limitation, its part of the number and you are destroying it.

**Comment by HypsyNZ** [comment]
Its not a limitation, `f`, `L` `d` `m` are part of the number and you are destroying it, 

You could very easily write it into the string and read it you just don't want to, You are deliberately not supporting the most basic type in `.NET`

**Comment by HypsyNZ** [comment]
Its not a limitation, `f` `L` `d` `m` are part of the number and you are destroying it, 

You could very easily write it into the string and read it you just don't want to, You are deliberately not supporting the most basic type in `.NET`

**Comment by HypsyNZ** [comment]
I actually found this bug by writing my own serializer/deserializer and I found this bug trying to make a comparative test and thought I would point it out.

**Comment by HypsyNZ** [comment]
Your serializer is slow and you can't even handle objects change the name of your library please.

**Comment by elgonzo** [comment]
> Your serializer is slow and you can't even handle objects change the name of your library please.

Don't you have any trees outside you can howl at? A bush would do as well...

**Comment by HypsyNZ** [comment]
> > Your serializer is slow and you can't even handle objects change the name of your library please.
> 
> Don't you have any trees outside you can howl at? A bush would do as well...

Real professional.

**Comment by HypsyNZ** [comment]
@JamesNK imagine getting on to another github account to deny your mistakes what a pussy.

**Comment by elgonzo** [comment]
Calling the author of the library a pussy... get some help bro...

**Comment by HypsyNZ** [comment]
You are deliberately creating bad data.

**Comment by elgonzo** [comment]
>    Don't you have any trees outside you can howl at? A bush would do as well...
>
> Real professional @JamesNK

Look, you seem to be a real smart guy. And a smart guy like you should have certainly noticed that the comment you resonded to was not from JamesNK...

**Comment by HypsyNZ** [comment]
I'm glad you aren't taking this seriously, it makes things easier.

**Comment by HypsyNZ** [comment]
You are guessing at best and at worst malicious.

**Comment by elgonzo** [comment]
I know, let it all out. All the things you don't like about the library, let it all out. And while we are at it, you can also relieve yourself of any childhood traumas you are carrying with you. I am here and listening...

**Comment by HypsyNZ** [comment]
I use the library every day I was just trying to help you, I will be moving on to a library with an actually supporter asap.

**Comment by HypsyNZ** [comment]
I used to use the library every day I was just trying to help you

**Comment by HypsyNZ** [comment]
> I know, let it all out. All the things you don't like about the library, let it all out. And while we are at it, you can also relieve yourself of any childhood traumas you are carrying with you. I am here and listening...

Real professional @JamesNK

**Comment by HypsyNZ** [comment]
You know, This conversation proves malice and you can't avoid liability?

**Comment by elgonzo** [comment]
Oh my, you really think i am JamesNK? This is hilarious... You reeaaaallllyyy think i am just a sockpuppet account of James Newton-King? Oh my, that's funny... i just can't... Sure, whatever conspiracy theory you like, boy. Go on, sue James Newton King for _my_ posts.

**Comment by HypsyNZ** [comment]
Okay dude, have fun with that.

**Comment by HypsyNZ** [comment]
What I'm hearing is "unlike all my IL code I can't find anywhere to copy paste that from"

**Comment by HypsyNZ** [comment]
Its so funny that your excuse is "In broken ass javascript a decimal isn't a decimal, so I'm going to break c#"

**Comment by HypsyNZ** [comment]
Imagine basing your library on a language someone wrote on a napkin in 10 minutes.

**Comment by HypsyNZ** [comment]
I think I'm over it now.

**Comment by HypsyNZ** [comment]
This is a great idea for all versions of the library and you are just a bad lazy developer.

**Comment by HypsyNZ** [comment]
This isn't acceptable.

If you aren't going to fix it you should throw an exception.

**Comment by HypsyNZ** [comment]
This isn't acceptable.

If you aren't going to fix it you should throw an exception.

@JamesNK

**Comment by HypsyNZ** [comment]
Also closing this as completed instead of not planned is deceptive.

**Comment by HypsyNZ** [comment]
You shouldn't be pretending you have a solution, you should be throwing an exception.
