### ISSUE TITLE
ParseReadString OOM

### ISSUE THREAD

**Issue by ZLVincent** [JamesNK/Newtonsoft.Json#2907]
JsonConvert.DeserializeObject() OOM.
![image](https://github.com/JamesNK/Newtonsoft.Json/assets/8155380/72fa9398-49ae-4ecf-91f4-a2129f7b8305)

It seems that an error occurred when initializing string. But the overall memory of the service does not have OOM.Is this a .NET problem or a Newtonsoft.Json problem?

**Comment by liorsa8** [comment]
@ZLVincent  Why did you close it, what was the problem? 
I am facing a similar thing.
