### ISSUE TITLE
Ignoring JsonProperty Name

### ISSUE THREAD

**Issue by ahmetkoprulu** [JamesNK/Newtonsoft.Json#2964]
### Source/destination types

```csharp
    public class UserEvent
    {
        [JsonProperty("s")] public string ScheduleId { get; set; }
        [JsonProperty("i")] public string EventId { get; set; }
    }
```

### Source/destination JSON

```javascript
{ "s": "test", "I": "test" }
```

### Expected behavior

I want to ignore the JsonProperty attribute manually by passing serializer settings or something else. Is it possible to achieve this behavior? I could not find any resource about it.

**Comment by elgonzo** [comment]
Implement a custom contract resolver deriving from DefaultContractResolver. Override its [`CreateProperty` method](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Serialization_DefaultContractResolver_CreateProperty.htm) in such a way that it:
1. obtains the JsonProperty instance from the base CreateProperty method.
2. sets the [json property name of the obtained JsonProperty instance](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_PropertyName.htm) to the name of the MemberInfo passed into the CreateProperty method.
3. returns the modified JsonProperty instance.

This basically sets the json property names to the names of the respective .NET instance field/property names, effectively undoing any custom json property name taken from \[JsonProperty]. (Additionally, if necessary, make this dependent on the value of the `JsonProperty.DeclaringType` property to limit this behavior only to desired types.)

Then assign this custom contract resolver to the [`ContractResolver` property](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_ContractResolver.htm) of the JsonSerializerSettings used for (de)serialization, and Bob should be your uncle...

**Comment by ahmetkoprulu** [comment]
Thanks for the answer. It seems like that would work. I am closing the issue.
