### ISSUE TITLE
Problem with Deserialize number like 0...8 and 0...9

### ISSUE THREAD

**Issue by DSW-DWA** [JamesNK/Newtonsoft.Json#2970]
### Source/destination types

```csharp
public class Root
{
    public int id { get; set; }
}

Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
```

### Source/destination JSON

```javascript
{
        "id": 08
}
```

### Expected behavior

```csharp
// Outputs to the console 8
Console.WriteLine(myDeserializedClass.id)
```

### Actual behavior

Exception: Input string '08' is not a valid number. Path 'id', line 1, position 17.

### Steps to reproduce

Newtonsoft.Json version 10.0.3

```csharp
using Newtonsoft.Json;

void Main() 
{
    var myJsonResponse = "{\"id\":08}";
    Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
}

public class Root
{
    public int id { get; set; }
}
```

**Comment by bartelink** [comment]
See also #2035 (TL;DR technicaly this is not a bug, and this library is in a very low touch maintenance phase so all bets are off in terms of the library having an in-the-box answer for your problem)

**Comment by DSW-DWA** [comment]
Thanks
С уважением, Чупеев Андрей
Full-stack developer
Тел. +7 (922)-433-88-96
Telegram: http://t.me/dsw_dwa

чт, 4 июл. 2024 г., 18:29 Ruben Bartelink ***@***.***>:

**Comment by DSW-DWA** [comment]
Solve
