### ISSUE TITLE
No strong name nuget package

### ISSUE THREAD

**Issue by TactiTac0z** [JamesNK/Newtonsoft.Json#3001]
Any chance you guys can post an official variant of the Newtonsoft.json nuget package without it being strongly named. It causes various issues which as far as I know can't be disabled using msbuild.
re: https://github.com/dotnet/project-system/issues/9599
I have seen other nuget packages do this. Doing this as a github issue since this a question to the package contributors. (And I also strongly dislike stackoverflow)

**Comment by JamesNK** [comment]
No chance. But someone else could do that.
