### ISSUE TITLE
AutoWrapperExtension reprocesses JSON, converting zoned dates into the application's local timezone

### ISSUE THREAD

**Issue by derekm** [JamesNK/Newtonsoft.Json#3005]
This is related to issues #865 and #525, however the repeated suggestion to use `JsonConvert.DefaultSettings` and `DateParseHandling.None` DOES NOT work with AutoWrapperExtension and `UseApiResponseAndExceptionWrapper()`.

Even when doing:
```csharp
app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions()
{
    IgnoreWrapForOkRequests = true
});
```
AutoWrapper still reprocesses the outgoing JSON, changing the zones of any included date fields.

Documentation needs to be provided so that ASP.NET users can disable AutoWrapper's mutating of date fields.

**Comment by elgonzo** [comment]
> DOES NOT work with AutoWrapperExtension

And why is that a problem with Newtonsoft.Json and not with AutoWrapper, exactly?

If `JsonConvert.DefaultSettings` doesn't work, it means AutoWrapper is using Newtonsoft.Json functionality by defining/passing their own settings. Again, not a Newtonsoft.Json issue but an AutoWrapper limitation/issue. I suggest you file an issue report with the AutoWrapper project if you want this AutoWrapper problem being resolved.

> Documentation needs to be provided so that ASP.NET users can disable AutoWrapper's mutating of date fields.

Again, what has this to do with Newtonsoft.Json documentation? It's AutoWrapper documentation has to be concerned with features/functionality pertaining to AutoWrapper (regardless of what other underlying or 3rd-party libraries AutoWrapper uses). It's not Newtonsoft.Json documentation responsibility to document any other project that is using the Newtonsoft.Json library...

**Comment by derekm** [comment]
Oh, sorry! Got turned around and left the bug on the wrong repo! D'oh!
