### ISSUE TITLE
RuntimeBinderException when accessing dynamic object properties in version 6.0.4.17603

### ISSUE THREAD

**Issue by alexander-w** [JamesNK/Newtonsoft.Json#352]
A RuntimeBinderException is thrown when accessing dynamic object properties, depending on visual studio settings. 

Steps to reproduce:
1) Create a new winforms or console application and add Json.NET via Nuget
2) Go to debug> Exceptions  and tick 'CLR exceptions'

put this code in Main() or wherever and run.

```
dynamic jsonResponse = JsonConvert.DeserializeObject("{\"message\":\"Hi\"}");
  Console.WriteLine(jsonResponse.message); 
```

^^^Exception thrown here

**Comment by lprichar** [comment]
:) thanks @JamesNK.   For posterity: in other words if you're debugging with break on all exceptions turn on, turn it off for RuntimeBinderException and your program will continue running just fine.
