### ISSUE TITLE
JsonProperty.MemberConverter and JsonProperty.Converter documentation

### ISSUE THREAD

**Issue by asgerhallas** [JamesNK/Newtonsoft.Json#363]
I can't find any explanation of the difference between JsonProperty.MemberConverter and JsonProperty.Converter and when to set which. Could the documentation be elaborated?

**Comment by NinoFloris** [comment]
It seems MemberConverter is just used in InternalReader for overriding propertyContract behavior. So it does not seem to be overly useful.
I haven't found a reference to where JsonProperty.Converter is being used. maybe it is a user accessible pass through variable for a parent type Converter to use.

Example:
So say in a JsonContract, the properties of this parent type X have converter Y, and my (X) converter is Z.
In converter Z you would presumably be able to get to the state of the JsonProperties of parent type X and be able to read that their converter is Y.

I find the relation between these contracts and converters really unintuitive and sometimes inhibitive to get the behavior I like. But it's what it is.

**Comment by JamesNK** [comment]
MemberConverter is now obsolete https://github.com/JamesNK/Newtonsoft.Json/commit/bbbddf0031fdced348b08d2435eb2d4698f50ef3
