### ISSUE TITLE
CustomCreationConverter not use if type name embedded in JSON string

### ISSUE THREAD

**Issue by AlesRuzickaEu** [JamesNK/Newtonsoft.Json#378]
When I deserialize Json string which has type embedded in header (settings mode `TypeNameHandling = TypeNameHandling.All`), my `CustomCreationConverter` is not used.

It is searching for Converters for object instead.

It works only if type is explicit in conversion call, but I cannot use that.

Example (sorry for VB):

```
Dim s = New JsonSerializerSettings()
s.TypeNameHandling = TypeNameHandling.All
s.Converters = {New DictionaryStringObjectConverter()}

Dim json = "{""$type"":""System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib"",""a"":""b""}"

Dim obj = JsonConvert.DeserializeObject(json, s)
```

and converter

```
Public Class DictionaryStringObjectConverter
    Inherits CustomCreationConverter(Of Dictionary(Of String, Object))

    Public Overrides Function Create(objectType As Type) As Dictionary(Of String, Object)
        Return New Dictionary(Of String, Object)(StringComparer.OrdinalIgnoreCase)
    End Function

End Class
```

In this example DictionaryStringObjectConverter is never used. Is I overwrite `CanConvert` method, it's called with objecType = object.

**Comment by nmarler** [comment]
Ugh. I have this same problem. I have a collection of base class types populated with subclasses, so I need the TypeNameHandling functionality - AND I need to use a CustomCreationConverter for object creation (I use Unity IOC container to resolve instances). I can get both working individually, but not together.

I suppose you might update the TypeNameHandling and CustomCreationConverter docs to say they can't be used together - I spent a fair amount of time debugging/searching before finding this post.

I plan to dump TypeNameHandling and use a CustomCreationConverter as described in this post http://stackoverflow.com/q/8030538/1073908. It's more work, but looks like it should give the functionality I require.

**Comment by pmoorelegistek** [comment]
I have this problem too. I don't understand the explanation:
"You have to read into the JSON object to get the type name, but if you read into the JSON object you can't pass it to the converter.:"
In the absence of a custom converter, you're still creating the object based on the type. So you know the type before you create it. Why can't you then use the custom converter instead?
