### ISSUE TITLE
Additional content found in JSON reference object. A JSON reference object should only have a $ref property.

### ISSUE THREAD

**Issue by PeterZong** [JamesNK/Newtonsoft.Json#398]
Hi,

I have json file which contains the following object:

"user":
{
   "$ref":"User",
   "description":"The order owner"
}

When I use JsonConvert.DeserializeObject to deserialize the json file, I get the following error:

Additional content found in JSON reference object. A JSON reference object should only have a $ref property. Path 'models.Order.properties.user.description', line 1, position 3313.

Do you have any suggestion on this?

Thanks,
Peter

**Comment by JamesNK** [comment]
See MetadataPropertyHandling.
