### ISSUE TITLE
Can't use DateFormatHandling.MicrosoftDateFormat with JObject.FromObject

### ISSUE THREAD

**Issue by Saliba** [JamesNK/Newtonsoft.Json#404]
When I try to use DateFormatHandling.MicrosoftDateFormat on JObject it doesn't work, it just ignore the configuration, is that supposed to be correct ?

            var jsonSerializer = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.Ignore
                DateFormatHandling = DateFormatHandling.MicrosoftDateFormat
            };

            request.AddBody(new { candidateDataBean = JObject.FromObject(candidateDataBean, jsonSerializer) });

**Comment by JamesNK** [comment]
It isn't used because the FromObject isn't turning the object into text
