### ISSUE TITLE
Make SQL CLR safe mode compatible

### ISSUE THREAD

**Issue by mirhagk** [JamesNK/Newtonsoft.Json#407]
MSSQL server only supports working with XML and I've run into situations where I have JSON in the database (logging requests from a web Api for instance). It'd be great if it was possible to use newtonsoft with SQL CLR so I didn't have to resort to pulling data out in order to manipulate it.

The problem is that Newtonsoft uses static fields in a few locations, and these aren't allowed in safe SQL CLR assemblies. I took a look and it seems it's mostly just caching/optimisation. I removed the instances locally and rebuilt, but I'm wondering if I should do it properly with a compile time flag and submit a pull request. Would others use this as well or should I just have a local fork?

**Comment by jakubsuchybio** [comment]
Well I would be interested. I couldn't find your fork with the fix. Could you navigate me to it or would you publish it please?

**Comment by mirhagk** [comment]
@jakubsuchybio The fork isn't public, give me a couple days to clean up what I did and I'll make it public

**Comment by IanYates** [comment]
I haven't looked into in it in any depth, but SQL 2016 apparently includes support for JSON similar to what it offers for XML...  Now if only I could magically get all of my customers to upgrade? :)
