### ISSUE TITLE
Problem when deserializing enums with different names

### ISSUE THREAD

**Issue by ikaman** [JamesNK/Newtonsoft.Json#416]
I've noticed a problem when deserializing enums (and using different names) when deserializing enums

for instance if i have a value from json called value_a and in c# i have ValueA

public enum EnumA
{  
[EnumMember(Value = "value_a")]
ValueA
}

Enum member Value wont be used and deserialization will fail

on the other hand if its a normal value for instance

```
public class Address
{
    [DataMember(Name = "address_1")]
    public string AddressLine1 { get; set; }
```

}

This will work fine.

Upon investigation it seems that for enum json.net uses internally enum.tryparse which doesnt use the enummember attribute.

If json.net could be fixed in that manner so that enummember value could be used that would be great

**Comment by lennie857** [comment]
> Great this fixed my issue.
> 
> Thank you very much for this info!





https://lnkr.fun/b2b23e4
