### ISSUE TITLE
Add additional NuGet packages to improve version range selection

### ISSUE THREAD

**Issue by sharwell** [JamesNK/Newtonsoft.Json#417]
## Summary

Currently [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) is a single NuGet package, with several versions available. It is difficult (obviously not impossible) to install any version but the most recent into a project.

One way to solve this is to create two additional metadata-only NuGet packages:

1. **Newtonsoft.Json.5**: This package does not contain any assemblies, but it does declare a dependency on **Newtonsoft.Json** with the version specifier `[5.0.8,6.0)`.
2. **Newtonsoft.Json.6**: This package does not contain any assemblies, but it does declare a dependency on **Newtonsoft.Json** with the version specifier `[6.0.6,7.0)`.

## Background

Suppose you have three projects:

1. **Newtonsoft.Json**: This is this.
2. **LibFoo**: This is a library distributed through NuGet and available for applications to use. It depends on **Newtonsoft.Json** and is compiled against version 5.0.8.
3. **AppBar**: This is an application which is distributed to users. It depends on **LibFoo**.

### Current situation

Suppose **LibFoo** declares a dependency on **Newtonsoft.Json** version `5.0.8`. After using NuGet to install **LibFoo** into **AppBar**, the NuGet Package Manager will report the existence of a new version of the **Newtonsoft.Json** (`6.0.6`). If the user installs the update, the application will no longer run properly unless assembly binding redirection is used.

The authors of **LibFoo** can intentionally avoid this situation by instead declaring the dependency on **Newtonsoft.Json** version `[5.0.8,6.0)`, which the NuGet Package Manager will recognize and prevent the installation of the newer version. The problem with this situation is it *prevents* the user from making use of assembly binding redirection to use the new version of Json.NET.

### Proposed situation

In the proposed solution, **LibFoo** would declare a dependency on **Newtonsoft.Json** version `5.0.8`. The authors of **AppFoo** are given control over the specific version of Json.NET used in their application, because they can install either the **Newtonsoft.Json.5** or **Newtonsoft.Json.6** package to specify which version of Json.NET is used for the final application. If **Newtonsoft.Json.5** is chosen, the NuGet Package Manager will not allow a 6.x version of Json.NET to be added to the project, and assembly binding redirection will not be required. If **Newtonsoft.Json.6** is chosen, the application developer is responsible for configuring the assembly binding redirection.

**Comment by JamesNK** [comment]
I prefer to be conservative. If something like this is used by other popular packages and it improves user experience then I will consider it then.
