### ISSUE TITLE
Deserialize empty F# seq

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json#431]
http://stackoverflow.com/questions/27090943/newtonsoft-cannnot-deserialize-an-empty-f-sequence

**Comment by haf** [comment]
Try `Newtonsoft.Json.FSharp`.

You could bring those things into the core if you wanted.

**Comment by JamesNK** [comment]
http://stackoverflow.com/questions/27090943/newtonsoft-cannnot-deserialize-an-empty-f-sequence/30960866#30960866
