### ISSUE TITLE
Possible Suggestion/Feature for JSONIgnore

### ISSUE THREAD

**Issue by ghost** [JamesNK/Newtonsoft.Json#445]
Hi, 
I'm having a bit of a dillemma with something that uses Newtonsoft json in it's own code. I want to filter a property from it's use of the newtonsoft json serializer, but not mine:

https://github.com/basho-labs/CorrugatedIron/issues/222

I was thinking it'd be nice if there was a way to pass the typeof(class) where I want the JSONIgnore attribute to be used, though I'm trying to think of a way you could do that and I can't really unless you were to unwind the stack with System.Diagnostics.StackTrace or something awful. Hopefully they will come up with their own parser, I'm actually trying to make one but having trouble figuring out how to do it, I'll take a look at how you guys did it and see if thats any better, it'd be nice if I didn't have to rewrite the full blown JsonConverter abstract members though just to do something as simple as: 

```
if(value.GetType().GetCustomAttributes().All(a => a.GetType() != typeof(RiakIgnore)))
{

} 
```

**Comment by paigeadele** [comment]
Thanks, I guess that'll do :)
