### ISSUE TITLE
NullReferenceException crash on Xamarin.Android only in Release mode

### ISSUE THREAD

**Issue by patridge** [JamesNK/Newtonsoft.Json#451]
I'm seeing a `NullReferenceException` when I try to deserialize some JSON retrieved from an API. Oddly, it only happens for me in a release build on Xamarin.Android (debug builds work fine). I've been able to get things working again by rolling back to v6.0.5.

I put together a [Gist](https://gist.github.com/patridge/38beecbae5908589456b) with the code to reproduce the issue and the corresponding stack trace it produces. Here is the Json.NET call in question.

```
var x = "{\"Result\":{\"Location\":\"something\",\"Id\":180478}}";
var y = JsonConvert.DeserializeObject<ApiResult<Something>>(x);
```

Gist: https://gist.github.com/patridge/38beecbae5908589456b

**Comment by johndouglascm** [comment]
I hit this one as well.  I can confirm that it's on release only with Xamarin.  

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Linq.Expressions.Expression.CreateLambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, System.Collections.ObjectModel.ReadOnlyCollection`1 parameters) [0x00000] in <filename unknown>:0 
  at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.Linq.Expressions.ParameterExpression[] parameters) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateParametrizedConstructor (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonObjectContract.set_ParametrizedConstructor (System.Reflection.ConstructorInfo value) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <filename unknown>:0 
  at com.linkedteam.LinkedTeamHttpClient+<PostAbsence>d__ba.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0 
  at com.linkedteam.android.AbsenceActivity+<absencesubmitbtnClick>d__d.MoveNext () [0x00000] in <filename unknown>:0

**Comment by detroitpro** [comment]
Providing more feedback: running into the same problem; downgrading to 6.0.5 was not a solution.

**Comment by stephen-riley** [comment]
Can also confirm issue.  Running 6.0.8, linking set to "Link SDK".  No linking works just fine; seems that something is reflecting inside Newtonsoft.Json and its desired target is getting stripped?

I'm going to play with some more linking configurations; will keep you posted.

( And, @JamesNK , let me say I'm a big fan.  Your work is awesome! :+1: )

[monodroid-gc] GREF GC Threshold: 46800
[monodroid] Xamarin/Android Trial Mode Active
[InputTransport] Input channel constructed:  ashmemFd=39, receivePipeFd=40, sendPipeFd=41
[Adreno200-EGLSUB] <ConfigWindowMatch:2081>: Format RGBA_8888.
[memalloc] /dev/pmem: Mapped buffer base:0x5315a000 size:3092480 offset:2478080 fd:46
[memalloc] /dev/pmem: Mapped buffer base:0x535bd000 size:1863680 offset:1249280 fd:49
[x] Making Creator dynamically
[Google Maps Android API] Google Play services client version: 6587000
[App] Calling StartService
[App] Calling service binding
[App] Calling StartService
[LocationService] [2/10/2015 5:50:53 PM] Starting location updates
[InputTransport] Input channel constructed:  ashmemFd=60, receivePipeFd=61, sendPipeFd=62
[Adreno200-EGLSUB] <ConfigWindowMatch:2081>: Format RGBA_8888.
[memalloc] /dev/pmem: Mapped buffer base:0x551b2000 size:1249280 offset:634880 fd:65
[memalloc] /dev/pmem: Unmapping buffer base:0x5315a000 size:3092480 offset:2478080
[memalloc] /dev/pmem: Unmapping buffer base:0x535bd000 size:1863680 offset:1249280
[ServiceConnection] OnServiceConnected Called
[App] Service Connected
[MainActivity] ServiceConnected Event Raised
[memalloc] /dev/pmem: Mapped buffer base:0x55303000 size:3092480 offset:2478080 fd:48
[InputTransport] Input channel destroyed: ashmemFd=39, receivePipeFd=40, sendPipeFd=41
[LocationService] [2/10/2015 5:50:55 PM] Got location 29.4282174, -98.4921035
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at System.Linq.Expressions.Expression.CreateLambda (System.Type,System.Linq.Expressions.Expression,string,bool,System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>) <0x0032c>
[MonoDroid] at System.Linq.Expressions.Expression.Lambda (System.Type,System.Linq.Expressions.Expression,string,bool,System.Collections.Generic.IEnumerable`1<System.Linq.Expressions.ParameterExpression>) <0x00063>
[MonoDroid] at System.Linq.Expressions.Expression.Lambda (System.Type,System.Linq.Expressions.Expression,System.Linq.Expressions.ParameterExpression[]) <0x00033>
[MonoDroid] at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall<object> (System.Reflection.MethodBase) <0x000e7>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateShouldSerializeTest (System.Reflection.MemberInfo) <0x000d3>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty (System.Reflection.MemberInfo,Newtonsoft.Json.MemberSerialization) <0x001cb>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties (System.Type,Newtonsoft.Json.MemberSerialization) <0x000bb>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type) <0x00083>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type) <0x00263>
[MonoDroid] at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type) <0x000f3>
[MonoDroid] at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (object) <0x0004f>
[MonoDroid] at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter,object,System.Type) <0x000c3>
[MonoDroid] at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter,object,System.Type) <0x005bf>
[MonoDroid] at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter,object,System.Type) <0x00037>
[MonoDroid] at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (object,System.Type,Newtonsoft.Json.JsonSerializer) <0x000db>
[MonoDroid] at Newtonsoft.Json.JsonConvert.SerializeObject (object,System.Type,Newtonsoft.Json.Formatting,Newtonsoft.Json.JsonSerializerSettings) <0x00047>
[MonoDroid] at Newtonsoft.Json.JsonConvert.SerializeObject (object,Newtonsoft.Json.Formatting,Newtonsoft.Json.JsonSerializerSettings) <0x00027>
[MonoDroid] at BeaconApp.DataManagement.BackgroundTasks.PostLocation (Beacon.Geolocation.LocationUpdatedEventArgs) <0x00247>
[MonoDroid] at BeaconApp.DataManagement.BackgroundTasks.PostBestLocation () <0x00137>
[MonoDroid] at BeaconApp.DataManagement.BackgroundTasks.<OnLocationUpdated>m__4 () <0x00013>
[MonoDroid] at Xamarin.Forms.Forms/AndroidPlatformServices/<>c__DisplayClass6.<StartTimer>b__5 () <0x00023>
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () <0x0003f>
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) <0x0003b>
[MonoDroid] at (wrapper dynamic-method) object.2e31f37f-96a4-474b-8123-2e7cb5e07b83 (intptr,intptr) <0x0003b>
[mono] 
[mono] Unhandled Exception:
[mono] System.NullReferenceException: Object reference not set to an instance of an object
[mono]   at System.Linq.Expressions.Expression.CreateLambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, System.Collections.ObjectModel.ReadOnlyCollection`1 parameters) [0x00000] in <filename unknown>:0 
[mono]   at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
[mono]   at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.Linq.Expressions.ParameterExpression[] parameters) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall[Object] (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateShouldSerializeTest (System.Reflection.MemberInfo member) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty (System.Reflection.MemberInfo member, MemberSerialization memberSerialization) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties (System.Type type, MemberSerialization memberSerialization) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
[mono]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
[mono]   at BeaconApp.DataManagement.BackgroundTasks.PostLocation (Beacon.Geolocation.LocationUpdatedEventArgs bestLoc) [0x00000] in <filename unknown>:0 
[mono]   at BeaconApp.DataManagement.BackgroundTasks.PostBestLocation () [0x00000] in <filename unknown>:0 
[mono]   at BeaconApp.DataManagement.BackgroundTasks.<OnLocationUpdated>m__4 () [0x00000] in <filename unknown>:0 
[mono]   at Xamarin.Forms.Forms+AndroidPlatformServices+<>c__DisplayClass6.<StartTimer>b__5 () [0x00000] in <filename unknown>:0 
[mono]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00000] in <filename unknown>:0 
[mono]   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00000] in <filename unknown>:0 
[mono]   at (wrapper dynamic-method) object:2e31f37f-96a4-474b-8123-2e7cb5e07b83 (intptr,intptr)
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
[mono-rt]   at System.Linq.Expressions.Expression.CreateLambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, System.Collections.ObjectModel.ReadOnlyCollection`1 parameters) [0x00000] in <filename unknown>:0 
[mono-rt]   at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.String name, Boolean tailCall, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
[mono-rt]   at System.Linq.Expressions.Expression.Lambda (System.Type delegateType, System.Linq.Expressions.Expression body, System.Linq.Expressions.ParameterExpression[] parameters) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall[Object] (System.Reflection.MethodBase method) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateShouldSerializeTest (System.Reflection.MemberInfo member) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty (System.Reflection.MemberInfo member, MemberSerialization memberSerialization) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties (System.Type type, MemberSerialization memberSerialization) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
[mono-rt]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
[mono-rt]   at BeaconApp.DataManagement.BackgroundTasks.PostLocation (Beacon.Geolocation.LocationUpdatedEventArgs bestLoc) [0x00000] in <filename unknown>:0 
[mono-rt]   at BeaconApp.DataManagement.BackgroundTasks.PostBestLocation () [0x00000] in <filename unknown>:0 
[mono-rt]   at BeaconApp.DataManagement.BackgroundTasks.<OnLocationUpdated>m__4 () [0x00000] in <filename unknown>:0 
[mono-rt]   at Xamarin.Forms.Forms+AndroidPlatformServices+<>c__DisplayClass6.<StartTimer>b__5 () [0x00000] in <filename unknown>:0 
[mono-rt]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00000] in <filename unknown>:0 
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00000] in <filename unknown>:0 
[mono-rt]   at (wrapper dynamic-method) object:2e31f37f-96a4-474b-8123-2e7cb5e07b83 (intptr,intptr)

**Comment by stephen-riley** [comment]
@JamesNK , indeed this appears to be a Xamarin Android linking issue.  Per Tim Ricciardi's comment at https://components.xamarin.com/view/json.net/, excluding System.Core and System.Runtime.Serialization from linking fixes the issue.  I've got a ticket open with Xamarin on this.

Thanks again for your work!
