### ISSUE TITLE
Breaking change in support for F# DUs

### ISSUE THREAD

**Issue by akashchopra** [JamesNK/Newtonsoft.Json#459]
It looks like https://github.com/JamesNK/Newtonsoft.Json/commit/8eea549b0a43809b3c6f24b9009b785ad5d27a79 introduced a breaking change to the way that F# DUs are serialized. This means that clients that use an older version of Json.Net cannot deserialize DUs that have been serialized with version 6.0.5 or later. This is due to the Fields property being required for earlier versions.

My questions are:

  * Does Json.Net use SemVer? (I'm not trying to argue for/against it - I just want to know the official position).
  * If it does, then shouldn't this change have required a new major release? Or do you see SemVer only applying to the public API, not the wire format?
  * If it doesn't, then what is the suggested way for users to determine backward compatibility?

I realise that F# support is a small corner case for this library, and that you have to focus on the major use cases; I'd just like to understand the approach to backward compatibility so that I can make informed choices. Thanks!

**Comment by JamesNK** [comment]
It simply didn't occur to me that it would be a breaking change when I made it.
