### ISSUE TITLE
SerializerSettings.DefaultValueHandling doesn't work since version 4.5.8

### ISSUE THREAD

**Issue by gordey4doronin** [JamesNK/Newtonsoft.Json#46]
I have the following settings in my Global.asax.cs file

<pre><code>
configuration.Formatters.JsonFormatter.SerializerSettings.DefaultValueHandling 
    = DefaultValueHandling.Include;

configuration.Formatters.JsonFormatter.SerializerSettings.Formatting 
    = Formatting.Indented;
</code></pre>
With 4.5.8 version of Newtonsoft.Json libary i got this data with my ApiController:
<pre>
{
    "Id": 11,
    "Content": "iPhone 4S",
    "Type": 0,
    "DateCreated": "2012-09-28T21:29:41.117",
    "DateUpdated": "2012-09-29T17:23:59.303",
    "IsArchived": false,
    "IsPublished": false,
    "TypeValue": 0
}
</pre>

But with 4.5.9 or 4.5.10 version - i can't get default values in my JSON-serialized data (settings left the same):

<pre>
{
    "Id": 11,
    "Content": "iPhone 4S",
    "DateCreated": "2012-09-28T21:29:41.117",
    "DateUpdated": "2012-09-29T17:23:59.303"
}
</pre>

**Comment by JamieDixon** [comment]
I'm also having an issue very similar to this when setting up the `DefaultValueHandler` globally. In my case, default values (as specified using the `DefaultValueAttribute`) are never defaulted to.

My configuration looks like this:
```
GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new WebApiConfig.LowerCasePropertyNamesContractResolver(),
                DefaultValueHandling = DefaultValueHandling.Populate
            };
```
