### ISSUE TITLE
ArgumentNullException hit by JsonArrayContract.CreateWrapper (potential regresssion from v4.5.11)

### ISSUE THREAD

**Issue by madelson** [JamesNK/Newtonsoft.Json#460]
A LINQPad script which reproduces this can be found in my SO question:

http://stackoverflow.com/questions/27828350/argumentnullexception-in-json-net-6-0-7-when-deserializing-mailmessage-works-in

**Comment by JamesNK** [comment]
Fixed

**Comment by madelson** [comment]
Thanks! What was the resolution? Does Json.Net now fully support NameValueCollections as dictionaries or is the error message cleaner or what?

**Comment by JamesNK** [comment]
It now throws a descriptive error. If you want to deserialize NameValueCollection you will need to write a JsonConverter for it.
