### ISSUE TITLE
build fails on .net 2

### ISSUE THREAD

**Issue by sagivo** [JamesNK/Newtonsoft.Json#461]
get tons of errors on first build
![screen shot 2015-01-08 at 1 42 46 am](https://cloud.githubusercontent.com/assets/1484886/5658925/c0ee4f8e-96d7-11e4-806b-eab3afe0d5ae.png)

**Comment by JamesNK** [comment]
I don't see how those errors are possible because System.Func isn't available in .NET 2.0

**Comment by sagivo** [comment]
@JamesNK - i'm trying it from MonoDevelop (for unity) so i guess it's available there.

**Comment by JamesNK** [comment]
Guess Json.NET .NET 2 it won't compile on monodevelop then.
