### ISSUE TITLE
Private properties in inherited classes

### ISSUE THREAD

**Issue by tpluscode** [JamesNK/Newtonsoft.Json#462]
Hi. Here's a question I asked [on SO](http://stackoverflow.com/questions/27887787/jsonpropertyattribute-ignored-on-private-property-in-derived-class/27892664): 

> I have a problem with Json.Net when serializing derived objects, which have private properties. Sth like
> 
> public class Base
> {
>    [JsonProperty]
>    private string Type { get { return "Base"; } }
> }
> 
> public class Inherited : Base
> {
>    [JsonProperty]
>    private string Type { get { return "Inherited"; } }
> }
> When I serialize instances of Inherited, the Type property is always set to "Base". The only way I've found that work is that the property is protected or public and overriden in subclass.

I got an answer, which shows [where in the code this comes from](https://github.com/JamesNK/Newtonsoft.Json/blob/1497343173a181d678b4c9bbf60250a12f783f1c/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs) and apparently this is by design. However I fail to find any explanation as to why. If this is not going to change for some reason I think the docs could mention this behaviour. Unless I fail to realize whay this should be obvious?

**Comment by BrannonKing** [comment]
I vote that we don't ever support this. All serializers I've ever used including all the serializers in the .NET framework itself ignore private properties in the base class. I think we should keep it that way.
