### ISSUE TITLE
Compile Error :Friend access was granted to 'Newtonsoft.Json.Schema when I compile the code 

### ISSUE THREAD

**Issue by firasjust** [JamesNK/Newtonsoft.Json#464]
Hi James, 
I just downloaded the latest version of the code from https://github.com/JamesNK/Newtonsoft.Json.Schema/releases and when I tried to compile the solution I got an error “Friend access was granted to 'Newtonsoft.Json.Schema”  I am using VS 2013 . Any idea of how to fix it 

Error Details :
Error	1	Friend access was granted to 'Newtonsoft.Json.Schema, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f561df277c6c0b497d629032b410cdcf286e537c054724f7ffa0164345f62b3e642029d7a80cc351918955328c4adc8a048823ef90b0cf38ea7db0d729caf2b633c3babe08b0310198c1081995c19029bc675193744eab9d7345b8a67258ec17d112cebdbbb2a281487dceeafb9d83aa930f32103fbe1d2911425bc5744002c7', but the output assembly is named 'Newtonsoft.Json.Schema, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Try adding a reference to 'Newtonsoft.Json.Schema, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f561df277c6c0b497d629032b410cdcf286e537c054724f7ffa0164345f62b3e642029d7a80cc351918955328c4adc8a048823ef90b0cf38ea7db0d729caf2b633c3babe08b0310198c1081995c19029bc675193744eab9d7345b8a67258ec17d112cebdbbb2a281487dceeafb9d83aa930f32103fbe1d2911425bc5744002c7' or changing the output assembly name to match.	c:\Users\falswatreh\Downloads\Newtonsoft.Json.Schema-master\Newtonsoft.Json.Schema-master\Src\packages\Newtonsoft.Json.6.0.8\lib\net40\Newtonsoft.Json.dll	Newtonsoft.Json.Schema.Net40

**Comment by firasjust** [comment]
Hi James, 
 I just downloaded the latest version of the code from https://github.com/JamesNK/Newtonsoft.Json.Schema/releases and when I tried to compile the solution I got an error “Friend access was granted to 'Newtonsoft.Json.Schema” I am using VS 2013 . Any idea of how to fix it ?

Error Details :
 Error 1 Friend access was granted to 'Newtonsoft.Json.Schema, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f561df277c6c0b497d629032b410cdcf286e537c054724f7ffa0164345f62b3e642029d7a80cc351918955328c4adc8a048823ef90b0cf38ea7db0d729caf2b633c3babe08b0310198c1081995c19029bc675193744eab9d7345b8a67258ec17d112cebdbbb2a281487dceeafb9d83aa930f32103fbe1d2911425bc5744002c7', but the output assembly is named 'Newtonsoft.Json.Schema, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Try adding a reference to 'Newtonsoft.Json.Schema, PublicKey=0024000004800000940000000602000000240000525341310004000001000100f561df277c6c0b497d629032b410cdcf286e537c054724f7ffa0164345f62b3e642029d7a80cc351918955328c4adc8a048823ef90b0cf38ea7db0d729caf2b633c3babe08b0310198c1081995c19029bc675193744eab9d7345b8a67258ec17d112cebdbbb2a281487dceeafb9d83aa930f32103fbe1d2911425bc5744002c7' or changing the output assembly name to match. c:\Users\falswatreh\Downloads\Newtonsoft.Json.Schema-master\Newtonsoft.Json.Schema-master\Src\packages\Newtonsoft.Json.6.0.8\lib\net40\Newtonsoft.Json.dll Newtonsoft.Json.Schema.Net40

**Comment by JamesNK** [comment]
I'll look at fixing this. Should be fixed sometime in the next week.

**Comment by JamesNK** [comment]
This was fixed a while ago.
