### ISSUE TITLE
Add StartLine, StartColumn, EndLine, EndColumn to IJsonLineInfo

### ISSUE THREAD

**Issue by davidfowl** [JamesNK/Newtonsoft.Json#465]
This would make it easier to show errors in IDEs for ranges (for things like squiggles) within JSON files.

**Comment by JamesNK** [comment]
Would rarely be used and tracking that extra info would hurt performance.

**Comment by davidfowl** [comment]
Hurt performance how? Memory wise?

**Comment by JamesNK** [comment]
Yes, and it is something that would almost never be used by the average dev. Tracking start line and position is fine because they are used in error messages.

Also adding properties to an interface is a breaking change.
