### ISSUE TITLE
JsonSerializer public instance methods should be virtual

### ISSUE THREAD

**Issue by lencharest** [JamesNK/Newtonsoft.Json#466]
In my unit tests for a custom converter, I want to be able to verify that `JsonSerializer.Serialize` is being called. However, I am using [Moq](https://github.com/Moq/moq4) as my mocking library, and Moq does not support mocking of non-virtual methods. A proxy would not help in this case because the serializer is passed to `JsonConverter.WriteJson` as an instance of `JsonSerializer`.

For comparison, note that most of the public methods of `JsonWriter` are virtual.

**Comment by JamesNK** [comment]
There is no reason to ever inherit from JsonSerializer. Wrap it in your own abstraction if you want to test it.

Also this would be a huge breaking change.

**Comment by lencharest** [comment]
I don't want to inherit from `JsonSerializer`. I want to be able to mock the serializer when testing a custom converter, specifically the `JsonConverter.WriteJson` method, which mandates a serializer of type `JsonSerializer`, which has non-mockable public methods.

**Comment by JamesNK** [comment]
I'm not making a method virtual just so it can be mocked. Wrap the serializer in your own abstraction if that is what you want to do.
