### ISSUE TITLE
DateTimeOffset losing timezone offset with DateTimeZoneHandling.Utc

### ISSUE THREAD

**Issue by politician** [JamesNK/Newtonsoft.Json#471]
When deserializing a DateTimeOffset field, the offset is converted to local time when the serializer is configured with `DateTimeZoneHandling.Utc` instead of either (a) preserving the original offset, or (b) converting to UTC.

In my case, switching to `DateTimeZoneHandling.RoundTripKind` appears to have fixed my use case, but given https://github.com/JamesNK/Newtonsoft.Json/issues/45, perhaps there has been a regression or perhaps the documentation about what `DateTimeZoneHandling.Utc` is supposed to do is incomplete.

**Comment by JamesNK** [comment]
DateTimeZoneHandling is for datetimes, not datetimeoffsets.

**Comment by JamesNK** [comment]
Can you give a code example please

**Comment by GusSand** [comment]
I have a similar issue. I am getting from the server a datetime like:
"start_at":"2015-01-24T00:00:00-05:00",

when I use DatetimeZoneHandling.RoundtripKind I stll get:
startAt = {1/23/2015 7:00:00 PM}

which is not what I would expect. I am using version 6.0.8 on windows phone. 

Please advise. Thank you !

**Comment by GusSand** [comment]
I also tried parsing it by hand using JObject and strangely enough I get the same results.  here is the code. Any ideas ? 

            JObject jsonFullResponse = JObject.Parse(response);
                JObject jsonEventObject = jsonFullResponse["response"]["event"].Value<JObject>();

                var startString = (string) jsonEventObject["start_at"];
                var endString = (string) jsonEventObject["end_at"];

**Comment by politician** [comment]
@GusSand Are you sure that what's on the wire is correct?

**Comment by GusSand** [comment]
Yes.

**Comment by JamesNK** [comment]
@GusSand use DateTimeOffset if you care about keeping the timezone.

Closing because no code example.
