### ISSUE TITLE
InvalidCastException when Converting to IConvertible

### ISSUE THREAD

**Issue by Sicklinger** [JamesNK/Newtonsoft.Json#472]
When deserializing to property with type IConvertible I get an InvalidCastException in class JSonSerializerInternalReader on line 877.

return Convert.ChangeType(value, contract.NonNullableUnderlyingType, culture);

I suggest to change the line to:
return Convert.ChangeType(value, Type.GetTypeCode(contract.NonNullableUnderlyingType), culture);

Please check example code:
string value = "test";
IConvertible dest = (IConvertible)Convert.ChangeType(value, typeof(System.IConvertible), CultureInfo.InvariantCulture);

and solution:
string value = "test";
 IConvertible =dest = (IConvertible)Convert.ChangeType(value, Type.GetTypeCode(typeof(System.IConvertible)), CultureInfo.InvariantCulture);

**Comment by JamesNK** [comment]
IConvertible is not a concrete type to convert to. If you want to accept any value then use object.
