### ISSUE TITLE
Feature Request: Improve Self referencing loop Exception with recommendations to solve

### ISSUE THREAD

**Issue by b9chris** [JamesNK/Newtonsoft.Json#473]
Happy to write the code myself.

I'd like to propose the Exception text for a self referencing loop detection be improved with a recommendation for the most typical solution:

Current Exception:

A first chance exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll

Additional information: Self referencing loop detected for property 'Shipment' with type 'EpicFS.Models.Shipping.Shipment'. Path 'Shipment.Notes[0]'.

So the Exception text portion is:

Self referencing loop detected for property 'Shipment' with type 'EpicFS.Models.Shipping.Shipment'. Path 'Shipment.Notes[0]'.

I'd like to propose it be improved to make a recommendation:

Self referencing loop detected in Shipment.Notes[0]. Consider applying [JsonObject(ReferenceLoopHandling = ReferenceLoopHandling.Ignore] to property Shipment.

**Comment by b9chris** [comment]
Code for the above proposed change, including updated Tests:

https://github.com/JamesNK/Newtonsoft.Json/pull/474

**Comment by JamesNK** [comment]
The problem with this is there are multiple ways to fix the issue. An attribute on the object is one, an attribute on the property is another, a setting on the serializer is a third, overriding Object.Equals is a fourth. I don't think it is the sort of problem you can properly explain in an error message.

**Comment by b9chris** [comment]
I'd rather see a brief recommendation for the most common solution (the one in this proposal and code) with a link to docs explaining the other options, than to leave it as-is. A lot of novice coders run into this, that would never be aware of the options to cope with it. The Exception also isn't worded in a way that implies there's a good solution available. Even experienced coders green to this library would be likely assume the library is more likely to be limited than to have something built-in to resolve it.
