### ISSUE TITLE
ContractResolver  is bypassed for some types

### ISSUE THREAD

**Issue by buckleyGI** [JamesNK/Newtonsoft.Json#475]
Hi,

I would like to serialize CultureInfo.CurrentCulture

Not to deserialize it back though. Its more to capture the state of the object for logging reasons.

I found out that the default serialiser does not handle static properties (which makes since when deserializeing as it does not belong to the instance).

So I went and created a custom ContractResolver. Below is a full working sample.

For the type "HelloThere" the ContractResolver is called (tested it with a breakpoint).
But when I pass CultureInfo.CurrentCulture it does not get used.

I also installed a memory trace listener to get some more information and set it to verbose level. However, it does not show extra information.

Thanks for putting me on the right track

Kind Regards, Tom

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace ConsoleApplication2
{
    internal class Program
    {
        private static void Main()
        {
            HelloThere helloThere = new HelloThere {Prop1 = "Hi"};
            HelloThere.Prop2 = "rr";

            MemoryTraceWriter traceWriter = new MemoryTraceWriter();

            traceWriter.LevelFilter = TraceLevel.Verbose;

            string res = JsonConvert.SerializeObject(helloThere, Formatting.None, new JsonSerializerSettings {TraceWriter = traceWriter, ContractResolver = new Custom()});
            string res2 = JsonConvert.SerializeObject(CultureInfo.CurrentCulture, Formatting.None, new JsonSerializerSettings {TraceWriter = traceWriter, ContractResolver = new Custom()});
        }
    }

    [Serializable]
    internal class HelloThere
    {
        public string Prop1 { get; set; }
        public static string Prop2 { get; set; }
    }

    internal class Custom : DefaultContractResolver
    {
        protected override List<MemberInfo> GetSerializableMembers(Type objectType)
        {
            var defaultMembers = base.GetSerializableMembers(objectType);

            IEnumerable<MemberInfo> allPropsNotInDefault = objectType.GetProperties()
                .Cast<MemberInfo>()
                .Where(x => !defaultMembers.Contains(x));

            defaultMembers.AddRange(allPropsNotInDefault);

            return defaultMembers;
        }
    }
}

**Comment by JamesNK** [comment]
That method is not called because culture is convertable to string.
