### ISSUE TITLE
LateBoundReflectionDelegateFactory.CreateParametrizedConstructor - Breaks in Limited Trust

### ISSUE THREAD

**Issue by nicknow** [JamesNK/Newtonsoft.Json#476]
Prior to v6.0.4 JSON.NET could run in an AppDomain that did not require ReflectionPermission. In this case it was running in the Dynamics CRM Sandbox processor - which creates a separate AppPool having limited permissions

Starting with v6.0.4 (and still true at v6.0.8) a security exception is throw when Serializing an object using: JsonConvert.SerializeObject().

I can see the error is getting throw from the following function:
Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateParametrizedConstructor(System.Reflection.MethodBase method)

This method was added on May 7 2014 as part of the 6.0.4 release.

I've tested extensively and the exact statement that works in 6.0.3 throws an exception when compiled against 6.0.4 and the exception comes from CreateParametrizedConstructor(System.Reflection.MethodBase method).

**Comment by nicknow** [comment]
Specifically, the method in question Newtonsoft.Json/Serialization/JsonTypeReflector.cs checks for FullTrust and if FullTrust is not available returns an instance of LateBoundReflectionDelegateFactory. In this class the method CreateParametrizedConstructor uses ConstructorInfo.Invoke. According to MSDN ConstructorInfo.Invoke (https://msdn.microsoft.com/en-us/library/6ycw1y17(v=vs.110).aspx) requires Reflection permissions which it may not have.

**Comment by catester** [comment]
I confirm the same problem:
>When I replace v6.0.3 of Newtonsoft.Json.dll with a newer version (also checked latest v6.0.8) in a working project, the same code bombs out under partial trust. Here is an example stack trace:
```
[SecurityException: Request for the permission of type 'System.Security.Permissions.ReflectionPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]
   System.Delegate.DelegateConstruct(Object target, IntPtr slot) +0
   Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateParametrizedConstructor(MethodBase method) +140
   Newtonsoft.Json.Serialization.JsonObjectContract.set_ParametrizedConstructor(ConstructorInfo value) +142
   Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) +632
   Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) +726
   Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type) +218
   Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) +198
   Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) +936
   Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value) +18
```

**Comment by niteshluharuka** [comment]
I confirm this problem with v6.0.8 as well

**Comment by JamesNK** [comment]
I have fixed this so that you won't get an error when serializing an object with a parameterized constructor, or deserializing with a default constructor.
