### ISSUE TITLE
IsoDateTimeConverter.Culture defaults to CurrentCulure which, for some cultures, conflicts with the default serialization.

### ISSUE THREAD

**Issue by LarsBlaabjerg** [JamesNK/Newtonsoft.Json#478]
If using the default settings for IsoDateTimeConverter, the serialized format is "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK" which is great. However, when parsing DateTimes without having set an explicit format, the following is used to parse it: DateTime.Parse(dateText, Culture, _dateTimeStyles);
Culture having the default value of CultureInfo.CurrentCulture. Depending on what the current culture is, this may throw a parse exception with the default serialized format, which is culture independent.

I suggest either changing the default value of Culture to CultureInfo.InvariantCulture, which would work with the default format and a number of other formats, or to use ParseExact as if the format had been set explicitly.

A workaround for people experiencing this issue is, of course, to set the values explicitly.

Hope this helps :-)

Lars Blaabjerg

Edit: Seems like I was jumping to conclusions. After some more digging and reading, I actually found that the format itself is to blame. The uppercase 'F's in the format string means any trailing zeros will be skipped when serializing. When deserializing, it appears that it expects 7 digits after the period, like in the standard "o" format (https://msdn.microsoft.com/en-us/library/vstudio/az4se3k1(v=vs.90).aspx#Roundtrip) and will fail if there are only 6. The standard "o" format string corresponds to "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK". Note the lowercase 'f' - that does not omit trailing zeros.

I still think using the CurrentCulture property by default is a bad idea in a library such as this though.

**Comment by JamesNK** [comment]
It is a breaking change to make it invariant.

**Comment by JeroenBer** [comment]
Not defaulting to InvariantCulture introduced me some nasty bugs, after inheriting from IsoDateTimeConverter. In some cultures the "yyyy" format is not what you expect. E.g. in the year 2024 for Thai Culture the formatstring "yyyy" will lead to 2566! And for parsing this is of course the other way around
