### ISSUE TITLE
Newtonsoft.Json is not signed

### ISSUE THREAD

**Issue by cpgarg10** [JamesNK/Newtonsoft.Json#479]
Hi,

We found that Newtonsoft.Json.dll is not signed ? This is creating problem for us to ship. Please suggest what we can do ?

Thanks
Chandra

**Comment by JamesNK** [comment]
Newtonsoft.Json on nuget.org is signed: https://www.nuget.org/packages/Newtonsoft.Json

You can double check that there are no caching issues by clearing the cache through the NuGets options dialog in VS.

**Comment by cpgarg10** [comment]
Hi James,

I have cleared the cache in VS and tried
Install-Package Newtonsoft.Json -Version 6.0.5

Then i tried to verify signature using signtool verify /pa
Newtonsoft.Json.dll

Saw error. Can you check and confirm if signature is correct.

Thanks
Chandra Prakash

**Comment by JamesNK** [comment]
I check everytime I upload a release. If it wasn't signed then everything would break.

**Comment by IanYates** [comment]
@cpgarg10 - could you include the error message?  I must admit I just tried launching signtool on my PC using the switches you provided, and trying some other switches, and got this
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC>signtool verify /a c:\dev\[snipped]\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll

File: c:\dev\[snipped]\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll
Index  Algorithm  Timestamp
========================================
SignTool Error: WinVerifyTrust returned error: 0x00000057
        The parameter is incorrect.

Number of errors: 1
```
and (using /pa instead of /a)
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC>signtool verify /pa c:\dev\[snipped]\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll

File: c:\dev\[snipped]\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll
Index  Algorithm  Timestamp
========================================
SignTool Error: No signature found.

Number of errors: 1
```

I got signtool.exe by launching Visual Studio 2013 developer tools on Windows 8.1.  I tried both the x64 and x86 versions of the shortcut and also tried running as administrator.

I don't need strong naming but this post intrigued me so I thought I'd check it out myself.  Now I'm extra curious.  @cpgarg10 - did you get output similar to mine above?

**Comment by cpgarg10** [comment]
Yes , I got the output (error message) exactly like your.

**Comment by cpgarg10** [comment]
@IanYates : Thanks Ian
@JamesNK : Can you please double check if Newtonsoft.Json.dll (version 6.0.5) is correctly signed.

Below I am giving all the steps i followed.

(1) Installed Newtonsoft.Json.dll using VS 2013 Package Manager Console

PM> Install-Package Newtonsoft.Json -Version 6.0.5
Installing 'Newtonsoft.Json 6.0.5'.
Successfully installed 'Newtonsoft.Json 6.0.5'.
Adding 'Newtonsoft.Json 6.0.5' to ****.
Successfully added 'Newtonsoft.Json 6.0.5' to ****.


(2) Then tried to verify signature using signtool (got error)

C:\Program Files (x86)\Microsoft Visual Studio 12.0>signtool verify /pa D:\Newtonsoft.Json.6.0.5\lib\net40\Newtonsoft.Json.dll
File: D:\Newtonsoft.Json.6.0.5\lib\net40\Newtonsoft.Json.dll
Index  Algorithm  Timestamp
========================================
SignTool Error: No signature found.

Number of errors: 1

Let me know, if case the way i am verifying signature is wrong ?

**Comment by abkmr** [comment]
I believe using the strong naming tool to verify signature for .NET Assemblies is the right method. So by using the below method we are getting the assembly as having a valid signature:-
sn -vf Newtonsoft.Json.dll

I believe there would have been a convention change to use sn to sign and strongly name the DLL instead of signtool somewhere after the 6.0.1 timeframe.

**Comment by JamesNK** [comment]
Json.NET has been signed by the same key since 3.5.

**Comment by abkmr** [comment]
I understand that the same key has been used. I was thinking that you had modified the method used for signing, are you using SignTool or sn+al for signing the DLL? 

What would be the right method to verify the signature according to you?

**Comment by cpgarg10** [comment]
@JamesNK : Managed assemblies has Authenticode and StrongName signing. I think StrongName is correct but Authetication Code is not. Signtool seems to check Authcode and it is failing, (sn checks for Strong Name and that is passing). We need to check both in order to make sure that dll is authentic. Can you please run "signtool" and check at your end what is the problem ?

**Comment by JamesNK** [comment]
You're talking about authicode signing? I strong name sign json.net but I don't authicode sign.

**Comment by IanYates** [comment]
Yep - they're two different things.  Not sure why that wasn't my first thought the other day.  Coffee!  I don't think all that many packages on NuGet are signed with authenticode are they?

@cpgarg10 - what's the actual use case?  Is it to prove that the DLL hasn't been tampered with?  If so, would it suffice to download the source and compile yourself?

**Comment by cpgarg10** [comment]
@IanYates : Yes, it is to prove that dll is not tempered. We have indirect dependency on Newtonsoft.Json.dll. Downloading sources and compiling our self is not a solution, since every time dependent dll takes dependency on diff version of Newtonsoft.Json.dll, we have to accordingly sync them (then we have to maintain code base also, which is not desirable)

**Comment by wickiie** [comment]
@JamesNK : Hi James, we have the same problem. We need to sign all referenced DLLs as well. As you do not plan to authicode sign Newtonsoft.Json.dll, are we allowed to sign it ourselves to ship with our product?

**Comment by JamesNK** [comment]
I don't know. I'm guessing it wouldn't cause any issues.
