### ISSUE TITLE
Problem with MonoDroid in Release

### ISSUE THREAD

**Issue by ccarnero** [JamesNK/Newtonsoft.Json#480]
Hi, I have an strange behaviour running the release version of my application, seems that something is crashing at at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall , but I have no idea what is wrong, here is the stacktrace: 

https://gist.github.com/ccarnero/818c92c9c49b29f24ada

However, when I run my application in Debug, its working fine. Any ideas?

Thanks in advance, 
Christian

**Comment by JamesNK** [comment]
It looks like a NullReferenceException coming from inside Xamarin. You should raise a bug with them.
