### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException'

### ISSUE THREAD

**Issue by rkumar670** [JamesNK/Newtonsoft.Json#481]
Hi,

I am facing the error where Serializing the object containing approx 30,000 records.
An unhandled exception of type 'System.StackOverflowException' occurred in Newtonsoft.Json.dll

Please look into the attached image.
![capture](https://cloud.githubusercontent.com/assets/1597317/6065254/b74ba080-ad89-11e4-88cf-27a04ad6f835.PNG)

Please help me to resolve this issue
Thanks,
Rahul

**Comment by JamesNK** [comment]
Ask on stackoverflow

**Comment by rkumar670** [comment]
Thanks,
