### ISSUE TITLE
DeserializeXNode. Message: 'Value cannot be null'. @xsi:nil

### ISSUE THREAD

**Issue by alex1kirch** [JamesNK/Newtonsoft.Json#482]
v6.0.8 JSON.NET

There is the problem with attribute ```@xsi:nil``` during deserialization in XDocument. For example:
```c#
XDocument xdoc = JsonConvert.DeserializeXNode("{ A: { '@xsi:nil': true } }")
```
As a result: ArgumentNullException was unhandled. Additional information: Value cannot be null.

Workaround:
```c#
XmlDocument doc = JsonConvert.DeserializeXmlNode("{ A: { '@xsi:nil': true } }");
XDocument xdoc = XDocument.Load(new XmlNodeReader(doc));
```

**Comment by JamesNK** [comment]
Fixed
