### ISSUE TITLE
Serialization, Writer and Reader defaults to different cultures

### ISSUE THREAD

**Issue by redknightlois** [JamesNK/Newtonsoft.Json#483]
While JsonSerializer defaults to JsonSerializerSettings.Culture
JsonWriter and JsonReader defaults to InvariantCulture.

There should be a uniform default, because that can cause different interpretations when defaults are used. If a PR will be accepted I can do the change to use JsonSerializerSettings for all of them.

**Comment by JamesNK** [comment]
JsonSerializerSettings defaults to InvariantCulture - https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializerSettings.cs#L354

???

**Comment by redknightlois** [comment]
Reading it now, it looks like I was pretty unclear. 

Scenario:
I go and change the JsonSerializerSettings to something else.
I never change the other two. Now serializer is going to serialize with my custome and the other ones with Invariant. 

Unless of course there is something going on that I am not seeing.

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializer.cs#L906
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializer.cs#L722

???

**Comment by redknightlois** [comment]
That is what I was not seeing :)

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json.Tests/Serialization/JsonSerializerTest.cs#L7578-L7597

!!!!
