### ISSUE TITLE
Why is Portable40 targeting NET4.0 and not NET4.0.3

### ISSUE THREAD

**Issue by altima** [JamesNK/Newtonsoft.Json#484]
Hi,

why is the Portable40 build not targeting the framework 4.0.3? Since version 6.0.6 I cannot use SerializeXNode() method of JsonConvert class. Till the version 6.0.5 this works fine. I was wondering why it was removed or changed... 

Currently I cannot use the nuget packages so I have to add a reference to the other portable lib (net45) to get it working.

It is easily to reproduce:
- create a empty Windows Phone 8 Silverlight project (or a project that targets net40)
- add Newtonsoft.Json package via nuget (version 6.0.8)
- try to use JsonConvert.SerializeXNode() method to convert xml to json

Thanks in advance.

**Comment by JamesNK** [comment]
That PCL is the absolute lowest of everything. If you want SerializeXNode then use the .NET 4.5 PCL
