### ISSUE TITLE
JsonIgnore allow write

### ISSUE THREAD

**Issue by ahirmayur** [JamesNK/Newtonsoft.Json#488]
Hi Guys,

I am having an issue while using JsonIgnore,

Model is,
```
public class User
{
	public int Id { get; set; }

	[Required]
	public string Email { get; set; }

	[JsonIgnore]
	public string Password { get; set; }
}
```
and controller has a method for creating new user,
```
public IHttpActionResult PostUser(User user)
{
	Console.WriteLine(user.Email) // Works fine
	Console.WriteLine(user.Password) // NULL
}
```
Now ```[JsonIgnore]``` does its job when attaching user to other methods by omitting password in responses. However not it doesn't recognise ```user.password``` which is always NULL.

So is there any way to avoid this?

**Comment by JamesNK** [comment]
Look up ShouldSerialize
