### ISSUE TITLE
Issue with float.Epsilon when using DefaultValueHandling.Ignore

### ISSUE THREAD

**Issue by rdehooge** [JamesNK/Newtonsoft.Json#492]
When using serializer settings as "DefaultValueHandling = DefaultValueHandling.Ignore" properties with float.Epsilon are not decoded to correct value. The example below demonstrates the issue.

        public static class TestClass
        {
            public static void RunTest()
            {
                JsonConvert.DefaultSettings = () => new JsonSerializerSettings() { DefaultValueHandling = DefaultValueHandling.Ignore };
                TestClass instance = new TestClass() { Value = float.Epsilon };
                string output = JsonConvert.SerializeObject(instance);
                TestClass result = JsonConvert.DeserializeObject<TestClass>(output);

                if (result.Value != instance.Value)
                {
                    throw new Exception();
                }
            }

            public class TestClass
            {
                public float Value
                {
                    get;
                    set;
                }
            }
        }

**Comment by JamesNK** [comment]
This happens because epsilon is so close to zero, json.net assumes it is zero. The precision is too small.
