### ISSUE TITLE
Dynamic access to JObject in Xamarin.Droid

### ISSUE THREAD

**Issue by tempywritescode** [JamesNK/Newtonsoft.Json#493]
When accessing the fields of a JObject cast to dynamic on Xamarin.Android, I'll get a RuntimeBinderException saying that the field cannot be found. The code in question is running in a PCL, and works fine when accessed from other platforms. Interestingly, this problem only happens if the executable Xamarin.Android project references JSON.NET as well. If I remove the reference to JSON.NET from the Android project and only leave a reference in the PCL which has the dynamic code, everything works fine.

Cheers!
mike

**Comment by JamesNK** [comment]
Bring the error up with Xamarin.

**Comment by cschoede** [comment]
The code below works in a basic Console Application. But doesn't work in a Xamarin.Forms Application.
```
var token = await GetJwtTokenAsync();
var manager = new ManagementApiClient(token.AccessToken, new Uri(""));

User user = await manager.Users.GetAsync(userId);
if (user == null)
{
    return null;
}

var request = new UserUpdateRequest
{
    Password = pin,
};

if (user.UserMetadata != null)
{
    user.UserMetadata.pin = null;
    request.UserMetadata = user.UserMetadata;
}

var result = await manager.Users.UpdateAsync(user.UserId, request);
return new ResponseModel
{
    IsSuccess = true,
    ErrorMessage = null,
    Content = user,
};
```

# Debug Info

## Console App

* **.NET Version:** 4.5.2
* **Auth0:** 3.6.0
* **Auth0.AuthenticationAPI:**: 3.7.0
* **Auth0.Core:** 3.7.0
* **Auth0.ManagementAPI:** 3.7.0
* **Netwonsoft.JSON:** 9.0.1

## Xamarin.Forms App

* **.NET Version:** 4.5
* **ASP.NET Core:** 1.0
* **Windows 8**
* **Windows 8.1**
* **Xamarin.Android**
* **Xamarin.iOS**
* **Xamarin.iOS (Classic)**
* **Xamarin.Mac**

Bug Discovered while testing against

7" Kitkat (4.4) XHDPI Tablet (Android 4.4 - API 19)

When running the Console application and calling `user.UserMetadata.pin` in the `immediate window` produces the stacktrace below
```
{}
    First: '((Newtonsoft.Json.Linq.JToken)user.UserMetadata.pin).First' threw an exception of type 'System.InvalidOperationException'
    HasValues: false
    Last: '((Newtonsoft.Json.Linq.JToken)user.UserMetadata.pin).Last' threw an exception of type 'System.InvalidOperationException'
    Next: null
    Parent: {"pin": ""}
    Path: "pin"
    Previous: null
    Root: {{
  "name": "52",
  "pin": ""
}}
    Type: String
    Value: ""
    Results View: Expanding the Results View will enumerate the IEnumerable
    Dynamic View: Expanding the Dynamic View will get the dynamic members for the object
```
However when making that same call in the immediate window of the Xamarin Application gives `Unknown member: pin` and will throw an Exception. 

Taken from the Inspector when hovering over `user.UserMetadata` `{{\n  "name": "<name>",\n  "pin": "####"\n}}`

Xamarin Stacktrace
**Message** `Newtonsoft.Json.Linq.JObject does not contain a definition for pin`
**Stacktrace**
```
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object,object)
  at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1) [0x00132] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/dlr/Runtime/Microsoft.Scripting.Core/Actions/UpdateDelegates.Generated.cs:387 
  at Mobile.Services.ClassName+<MethodName>d__3.MoveNext () [0x0025a] in E:\Projects\mobile\Mobile\Mobile\Services\ClassName.cs:92 
```
