### ISSUE TITLE
JToken ToString doesn't output the token as a string

### ISSUE THREAD

**Issue by haf** [JamesNK/Newtonsoft.Json#494]
When doing `JToken.Parse("\"a string\"").ToString()` I get a string that doesn't contain tokens, but instead in this case contains the value `a string`. I would have expected a string containing `"a string"` because that's what the token's string representation is.

**Comment by haf** [comment]
Hmm, couldn't reproduce that easily as it turns out when writing unit tests. Unicorns.

**Comment by jsgoupil** [comment]
Oups, I am hitting this problem right now. Strange.
