### ISSUE TITLE
JsonConvert.DeserializeObject != JToken.Parse with date

### ISSUE THREAD

**Issue by lappkast** [JamesNK/Newtonsoft.Json#495]
Hi!

I'm trying to use JToken to deserialise my dates, but I get an error when doing so. JsonConvert.DeserializeObject works just fine, but I would like to continue with JToken.

2 reproducible tests within an .fsx -file  can be found here:
https://gist.github.com/4c8156066c7c99d77998

**Comment by JamesNK** [comment]
What is the error? Can you create a C# repro.

**Comment by skywalkery** [comment]
You can use the next workaround (c#):
```c#
var jsonOptions = new JsonSerializerSettings().ConfigureForNodaTime(NodaTime.DateTimeZoneProviders.Tzdb);
using (JsonReader reader = new JsonTextReader(new StringReader("\"2010-02-12T23:22:00Z\"")))
{
	reader.DateParseHandling = DateParseHandling.None;
	var instant = JToken.ReadFrom(reader).ToObject<Instant>(JsonSerializer.Create(jsonOptions));
	Assert.AreEqual(Instant.FromUtc(2010, 02, 12, 23, 22), instant);
}
```
or
```c#
var instant = JToken.FromObject("2010-02-12T23:22:00Z").ToObject<Instant>(JsonSerializer.Create(jsonOptions));
Assert.AreEqual(Instant.FromUtc(2010, 02, 12, 23, 22), instant);
```

**Comment by lappkast** [comment]
Thank you for the workaround @skywalkery.
We switched back to JsonConvert, but I'll try to create a C# repro for you shortly if the .fsx-file isn't doing it for you @JamesNK. :)
