### ISSUE TITLE
Circular references with non-default constructors

### ISSUE THREAD

**Issue by Ragzouken** [JamesNK/Newtonsoft.Json#496]
Just ran into this today, and whilst I really shouldn't have expected it to work, I feel that the library should have caught it happening and given up:

You have two object with circular references to each other, and both have non-default constructors - neither can be constructed until the other has been, because both need to pass each other into their constructors.

I ran into this with List elements being passed in as null rather than the object (which hadn't been constructed yet) - I think the parser should bail in this case!

**Comment by JamesNK** [comment]
This worked fine for me:

            [Test]
            public void CircularConstructorDeserialize()
            {
                CircularConstructor1 c1 = new CircularConstructor1(null)
                {
                    StringProperty = "Value!"
                };

                CircularConstructor2 c2 = new CircularConstructor2(null)
                {
                    IntProperty = 1
                };

                c1.C2 = c2;
                c2.C1 = c1;

                string json = JsonConvert.SerializeObject(c1, new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                    Formatting = Formatting.Indented
                });

                Assert.AreEqual(@"{
      ""C2"": {
        ""IntProperty"": 1
      },
      ""StringProperty"": ""Value!""
    }", json);

                CircularConstructor1 newC1 = JsonConvert.DeserializeObject<CircularConstructor1>(@"{
      ""C2"": {
        ""IntProperty"": 1,
        ""C1"": {}
      },
      ""StringProperty"": ""Value!""
    }");

                Assert.AreEqual("Value!", newC1.StringProperty);
                Assert.AreEqual(1, newC1.C2.IntProperty);
                Assert.AreEqual(null, newC1.C2.C1.StringProperty);
                Assert.AreEqual(null, newC1.C2.C1.C2);
            }

            public class CircularConstructor1
            {
                public CircularConstructor2 C2 { get; internal set; }
                public string StringProperty { get; set; }

                public CircularConstructor1(CircularConstructor2 c2)
                {
                    C2 = c2;
                }
            }

            public class CircularConstructor2
            {
                public CircularConstructor1 C1 { get; internal set; }
                public int IntProperty { get; set; }

                public CircularConstructor2(CircularConstructor1 c1)
                {
                    C1 = c1;
                }
            }
