### ISSUE TITLE
Deserialize to DataSet: Inferring numeric value type as System.Int64 is too aggressive in its assumptions.

### ISSUE THREAD

**Issue by janholstjensen** [JamesNK/Newtonsoft.Json#499]
JavaScript does not differentiate between integers and floats. Hence a browser may produce JSON where a float is represented by a number that looks exactly like an integer. When deserializing JSON to a .NET DataSet only the first row is apparently used to infer the data type and so a float field may be interpreted as an integer field with unfortunate rounding and data loss as a consequence.

See the following code for an example.

```
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;

using Npgsql;
using NpgsqlTypes;

using Newtonsoft.Json;

namespace DotNetTest
{
	class Program
	{
		static void Main(string[] args)
		{
			/** The JSON table data can be produced by the following JavaScript code:
			 * 
				var dataRows = [{'name': "Lars", 'weight': 78.0}, {'name': "Jan", 'weight': 85.6}];
				var dataTable = {'Table': dataRows};
				var jsonStr = JSON.stringify(dataTable);
			 * 
			 * This is in Firefox 35.0.1 and the same is seen in IE 11.
			**/
			string json = "{\"Table\": [{\"name\":\"Lars\",\"weight\":78},{\"name\":\"Jan\",\"weight\":85.6}]}";
			DataSet dataSet = JsonConvert.DeserializeObject<DataSet>(json);
			DataTable dataTable = dataSet.Tables["Table"];
			Console.WriteLine(dataTable.Rows.Count);
			Console.WriteLine(dataTable.Columns[1].ToString());
			foreach (DataRow row in dataTable.Rows)
			{
				string name = row["name"].ToString();
				Console.WriteLine(row["weight"].GetType().ToString());
				Double weight = Double.Parse(row["weight"].ToString());
				Console.WriteLine(name + " - " + weight.ToString());
			}
		}
	}
}
```
The code produces the following output with both JSON.NET 6.0.4 and 6.0.8.
```
2
weight
System.Int64
Lars - 78
System.Int64
Jan - 86
```
If Lars's weight is 78.1 the output becomes
```
2
weight
System.Double
Lars - 78.1
System.Double
Jan - 85.6
```
and no data is lost.

I would much prefer that the default behavior is to always make the safe assumption that numeric fields are Double. Trying to Infer integer fields would best be a behavior that you would need to explicitly activate.

My workaround for now is to always insert a first dummy row in my tables browser-side with numeric fields set to a value of 1.234. When the JSON data is received on the web server and deserialized to a DataSet, JSON.NET will then always construct Double fields.

**Comment by JamesNK** [comment]
Remember that Json.NET isn't just used from JavaScript. With DataSets it is much more likely the datasets are being sent between two .NET applications.

I don't want to default to double because it will loose precision with large integers. And Json.NET will automatically include a ".0" when serializing doubles which means that the type will be correctly detected when deserializing the dataset.

**Comment by janholstjensen** [comment]
Losing precision with large integers is a valid concern - I see your point.

I guess there is then no way around using a workaround like the one described above, at least when sending data from JavaScript to .NET. Going in the other direction will be safe.

Thanks for having a look at it.
