### ISSUE TITLE
Read-only properties are being read during deserialization

### ISSUE THREAD

**Issue by ebopensource** [JamesNK/Newtonsoft.Json#503]
As our domain objects are being serialized/deserialized, we have recently run into issues where non-primitive read-only properties are being accessed during the deserialization process.

We just ran into this recently when we upgraded the RavenDB client library which (presumably) has a fork of this project.

http://www.nuget.org/packages/RavenDB.Client/3.0.3528 - This one works
http://www.nuget.org/packages/RavenDB.Client/3.0.3599 - This one has the issue

We then pulled down the current source to see if we could reproduce the issue in a unit test. We were able to do this and have created this pull request to demonstrate the issue:

https://github.com/JamesNK/Newtonsoft.Json/pull/502

We can prevent the issue by changing the order of properties in our code, but that is obviously very brittle and dirty solution. We could also add check or try/catch, but since the class is designed to always be in a valid state, this would be code only necessary for serialization. Obviously our preference would be that the deserialization process not attempt to access getters on any properties that do not have setters.

Thanks!

**Comment by JamesNK** [comment]
You can stop this using the ObjectCreationHandling setting.

**Comment by ebopensource** [comment]
Thank you, James! It turns out that the RavenDB client library [changed their default](https://github.com/ravendb/ravendb/commit/3d59621453aa6a1ef924b259a256d680be5a424e) from .Replace to .Auto. That helped us track down the issue and address it.
