### ISSUE TITLE
self referencing loop detected with type

### ISSUE THREAD

**Issue by dmahar** [JamesNK/Newtonsoft.Json#510]
On get call I an getting an error self referencing loop detected with type.. . While I don't have any self refrencing loop.

Error: self referencing loop detected with type......

 self.$http.get('/api/Repair/Current').success(function (repairs: CurrentRepairDTO) {
                deferred.resolve(repairs);
            }).error(function (err, status) {
                deferred.reject(err);
            });

 // GET api/Repair/Current
        [Route("Current")]
        public CurrentRepairDTO GetCurrentRepairs()
        {
            ........
return currentRepairDTO;
}
[TypeScriptInterface]
    public class CurrentRepairDTO : TransferObject
    {
        public IList<RepairDTO> OtherRepairs { get; set; }   
}

 [TypeScriptInterface]
    public class RepairDTO : TransferObject
    {
        public string ShortDescription { get; set; }
        public string Status { get; set; }
        public int StatusCode { get; set; }
        public DateTimeOffset CreationDate { get; set; }
        public bool IsCompleted { get; set; }
        public string JobReference { get; set; }
    }

**Comment by JamesNK** [comment]
You have a circular reference. The exception will tell you the type and the path of the error. Post your complete JSON and types to StackOverflow.
