### ISSUE TITLE
Contract Resolver to convert underscore-separated properties to Pascal Cased

### ISSUE THREAD

**Issue by krillgar** [JamesNK/Newtonsoft.Json#511]
Would it all be possible to get a contract resolver similar to the CamelCasePropertyNamesContractResolver() that would take a JSON property like "created_on" and transform it to "CreatedOn"?

I would work on it myself, but I don't have the time to build it out right now. Would it be anything more complicated than using a Regex to remove all underscores and then capitalize the next character?

**Comment by JamesNK** [comment]
This can be in a separate package.
