### ISSUE TITLE
F# discriminated union deserialization bug

### ISSUE THREAD

**Issue by Horusiath** [JamesNK/Newtonsoft.Json#512]
I've discovered that default DiscriminatedUnionConverter fails when trying to deserialize a F# discriminated union instance with settings type name handling turned to `TypeNameHandling.All` (only with this configuration).

Exception message:
> An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll
> Additional information: Union fields must been an array. Path 'Fields', line 1, position 28.

Test code used to recreate an error:
```fsharp
let settings = JsonSerializerSettings()
settings.TypeNameHandling <- TypeNameHandling.All

let serialize o =
    let json = JsonConvert.SerializeObject(o, Formatting.None, settings)
    Encoding.Default.GetBytes json

let deserialize bytes t =
    let json = Encoding.Default.GetString bytes
    JsonConvert.DeserializeObject (json, t, settings)

type TestUnion =
    | CaseOne of string
    | CaseTwo of int

let a = CaseOne "hello"

let abin = serialize a
let ades = deserialize abin (a.GetType())
let a2 = ades :?> TestUnion
```

Serialized union JSON: `{"Case":"CaseOne","Fields":{"$type":"System.Object[], mscorlib","$values":["hello"]}}`

I've also tracked down source of an error in [Newtonsoft.Json source code](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/DiscriminatedUnionConverter.cs#L178).

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/a3278ccd6a7ac88c3c5ae85d46a3ec46a6f438ec#diff-cb3fb9511e571c94735be121f80b6fe5R133

**Comment by rogeralsing** [comment]
This only works if the type is known on the deserializing side.
if the discriminated union is stored in an object array, it still fails.

```fsharp
open Newtonsoft.Json
open System.Text;


let settings = JsonSerializerSettings()
settings.TypeNameHandling <- TypeNameHandling.All

let serialize o =
    let json = JsonConvert.SerializeObject(o, Formatting.None, settings)
    Encoding.Default.GetBytes json

let deserialize bytes t =
    let json = Encoding.Default.GetString bytes
    JsonConvert.DeserializeObject (json, t, settings)

type TestUnion =
    | CaseOne of string
    | CaseTwo of int

let ac = CaseOne "hello"
let a = [| ac :> System.Object |] 

let abin = serialize a
let ades = deserialize abin (a.GetType()) :?> System.Object[]
let a2 = ades.[0] :?> TestUnion  //fails as ades is JObject
```

**Comment by JamesNK** [comment]
It's implemented as a type converter and they don't support type names.

**Comment by rogeralsing** [comment]
Is the scenario where the DU is wrapped in an object array supported?
The answer isn't clear to me.
Is there anything else than adding the DU-Converter to the settings that I need to do?

Every setup that we try here results in a `JObject` instead of a DU on the deserialized side.

**Comment by JamesNK** [comment]
Maybe you could write a custom converter for the object array that includes the type in a wrapper object with type information on serialization and read that type information on deserialization?
