### ISSUE TITLE
use BaseIntermediateOutputPath

### ISSUE THREAD

**Issue by SimonCropp** [JamesNK/Newtonsoft.Json#515]
if you add `BaseIntermediateOutputPath` settings to the projects you will be able to have the solutions open concurrently and not have unintended side effect of VS re-using files in the bin obj directory

eg
```
<BaseIntermediateOutputPath>obj\Debug\WinRT\</BaseIntermediateOutputPath>
```

**Comment by JamesNK** [comment]
Done
