### ISSUE TITLE
BSON do not respect DateParseHandling when deserializing to object

### ISSUE THREAD

**Issue by vandop** [JamesNK/Newtonsoft.Json#519]
Hi,

with this settings:

Given this class:

    public class MyDate
    {
        public object Time { get; set; }
    }

and this settings:

 var settings = new JsonSerializerSettings()
                {
                    TypeNameHandling = TypeNameHandling.Auto,
                    ConstructorHandling =
                        ConstructorHandling.AllowNonPublicDefaultConstructor,
                    DateParseHandling = DateParseHandling.None
                };

serializing this object:

var obj = new MyDate() { Time = DateTimeOffset.Now };

using BSONWriter and Reader to get it back, then:

obj,Time.GetType() == typeof(DateTime) (instead of string)

If you use   DateParseHandling = DateParseHandling.DateTimeOffset

same result (DateTime instead of DateTimeOffset).

Doing exactly the same using regular JsonSerializer, it works as expected.

Tested on version: 6.0.8

(Let me know if you need working code to replicate)

**Comment by JamesNK** [comment]
That's because DateParseHandling is for converting from a string to a date. BSON serializes dates as its own data type.
