### ISSUE TITLE
Type Caching for IOS does not work from PCL library included in Xamarin project

### ISSUE THREAD

**Issue by MichaelRoop** [JamesNK/Newtonsoft.Json#523]
I have produced a PCL library to read and write to isolated storage strings that are serialized and desirealized using Newtonsoft.  In the windows version there is an overhead when serializing and/deserializing an object for the first time.  Afterwards, overhead drops to 0.

However, when I use the same PCL library in an IOS application under Xamarin, the overhead for serialization/deserialization is constant.  So it looks like caching never happens.

I attempted to use the manual Newtonsoft serialization/deserialization.  The overhead is less but still constant. No caching.

As a test I did my own manual serialization by overriding ToString() on the object.  I also added a constructor with a string parameter so it can initialise iteself by decoding the string.  In this case the overhead dropped to 0 after first use.

**Comment by JamesNK** [comment]
Reflection on Windows uses compiled IL to set and get values. iOS doesn't allow dynamic compilation and always uses late bound reflection. Does that explain the difference?

**Comment by MichaelRoop** [comment]
Yes thank you.  

Do you know of any scheme, short of rolling my own object marshalling through ToString() and constructor with string that could boost performance?

BTW, great job on the library

Michael Roop

**Comment by MichaelRoop** [comment]
After some experimentation I have found that under IOS you can save a 
lot of overhead by serializing and writing DateTime as a long (Ticks) to 
isolated storage

Here is an example of the object that I was testing with

[DataContract(Namespace = "http://www.lala.com/api")]
public class DataRunsStorageIndex {
    [DataMember] 
    public List<DataRunsStorageIndexItem> Runs { get; set; }

    public DataRunsStorageIndex() {
        this.Runs = new List<DataRunsStorageIndexItem>();
    }
}


[DataContract(Namespace = "http://www.masitek.com/api")]
public class DataRunsStorageIndexItem {
    [DataMember]
    public Guid ClientId { get; set; }
    [DataMember]
    public Guid RunId { get; set; }
    [DataMember]
    public string Description { get; set; }
    [DataMember]
    public long Start { get; set; }
    [DataMember]
    public long End { get; set; }
}

I originally had Start and End as DateTime then changed them to long and used Ticks. 

Here is a comparison. In the left column is the number of DataRunsStorageIndexItem in 
the list. These are followed by (storeTimeMs/RetrieveTimeMs). I did an initial run before
taking the timings

	DateTime    Long

   1 -  (8/8)              (6/6)  
  10 -  (28/27)         (10/10)	
 100 -  (225/218)     (47/46)
 250 -  (NA)              (115/82)
1000 -  (2198/2059) (415/300)

I assume that IOS is using reflection each time to resolve DateTime whereas it 
does not need to use reflection on primitive types or is able to cache those types

Michael Roop
