### ISSUE TITLE
Add support for a JsonAnyPropertyAttribute

### ISSUE THREAD

**Issue by thomaslevesque** [JamesNK/Newtonsoft.Json#524]
This would do the same thing as the [`XmlAnyElementAttribute`](https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlanyelementattribute) for XML serialization, i.e. act as a "catch all" for JSON properties that have no corresponding property.

Example:

```json
{
    "Id": 42,
    "Name": "test",
    "Description": "foo",
    "Category": "bar"
}
```

```csharp
public class MyClass
{
    public int Id { get; set; }
    public string Name { get; set; }

    [JsonAnyProperty]
    public IDictionary<string, object> OtherProperties { get; set; }
}
```

`OtherProperties` will contain the values of `Description` and `Category`, because the have no corresponding property in the class.

This would allow us to map only properties we care about, but without losing the other ones when we serialize back to JSON.

**Comment by JamesNK** [comment]
That already exists: JsonExtensionDataAttribute

**Comment by thomaslevesque** [comment]
Oh, right. I thought I remembered seeing this somewhere, but when I looked for it I couldn't find it. I think it should be mentioned on the [Serialization attributes](http://www.newtonsoft.com/json/help/html/SerializationAttributes.htm) page in the documentation, it would make it easier to find.

**Comment by JamesNK** [comment]
Good point. I added document with a sample for it, but didn't add it to that page.

**Comment by JamesNK** [comment]
Documentation++

**Comment by thomaslevesque** [comment]
Perfect :+1:
