### ISSUE TITLE
DateTimeOffset loosing Timezone info

### ISSUE THREAD

**Issue by oliverjanik** [JamesNK/Newtonsoft.Json#525]
Here's the test that fails:

```csharp
[Fact]
public void JTokenDateTest()
{
    var json = JToken.Parse(@"{ ""lastModifiedAt"": ""2015-04-30T23:59:02.465+12:00"" }");

    Assert.Equal("2015-04-30T23:59:02.465+12:00", json.Value<string>("lastModifiedAt"));

    var dto = (DateTimeOffset)json["lastModifiedAt"];

    Assert.Equal(12, dto.Offset.Hours);
} 
```

This fails both asserts. The question is WTF? Why does the parser even try to interpret the time information when it's actually a JSON string? I thought I was going crazy. The only interpretation should happen when I cast it to the DateTimeOffset.

**Comment by JamesNK** [comment]
JToken.Parse reads dates as DateTimes by default. Look at the DateParseHandling setting.

**Comment by oliverjanik** [comment]
What about the wrong timezone info? Do you not consider this an issue?

**Comment by JamesNK** [comment]
DateTime doesn't preserve the timezone.

**Comment by DaveVdE** [comment]
IMHO, I think it's a crazy default. Especially considering DateTime is such a bad fit for ISO8601.

**Comment by derekm** [comment]
@JamesNK said,
> JToken.Parse reads dates as DateTime by default. Look at the DateParseHandling setting.

Docs suck really bad, so it is hard to figure out how to configure `JToken` with `DateParseHandling.None` or `DateParseHandling.DateTimeOffset`, but you do it via `JsonConvert.DefaultSettings` as in:

```csharp
        JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
        {
            DateParseHandling = DateParseHandling.None
        };
```

Defaults come from `JsonSerializerSettings`'s default constructor, so you're getting stock `JToken` behavior plus the override on the `DateParseHandling` setting.
