### ISSUE TITLE
Problem deserializing Dictionary with nullable types on Android

### ISSUE THREAD

**Issue by Henkoglobin** [JamesNK/Newtonsoft.Json#527]
The following code works just fine when run in a Windows Console Application:

```c#
var failingJson = "{ \"something\": null }";

var failingConverted = JsonConvert.DeserializeObject<Dictionary<string, decimal?>>(failingJson);
```

however, when run on an Android emulator using Xamarin.Forms, it produces an exception:

> System.ArgumentException: not of type: System.Nullable`1[System.Decimal]
> 
> Parameter name: value

Stack trace:

> at System.Collections.Generic.Dictionary\`2[System.String,System.Nullable\`1[System.Decimal]].ToTValue (System.Object value) [0x00000] in <filename unknown>:0 
> at System.Collections.Generic.Dictionary\`2[System.String,System.Nullable\`1[System.Decimal]].System.Collections.IDictionary.set_Item (System.Object key, System.Object value) [0x00000] in <filename unknown>:0
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary (IDictionary dictionary, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonDictionaryContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) [0x00000] in <filename unknown>:0

The very same project, run on the Windows Phone emulator, runs perfectly fine again.

Running JSON.NET 6.0.8, Xamarin.Forms 1.3.1.6296, Xamarin.Android.Support.v4 19.0.2

**Comment by JamesNK** [comment]
This looks like a bug in Xamarin. Raise it with them.
