### ISSUE TITLE
Original Unmodified Source String

### ISSUE THREAD

**Issue by bradserbu** [JamesNK/Newtonsoft.Json#528]
I am deserializing a Json Object containing a "results" property that contains an array of Json Results.

My application is experiencing data corruption issues down stream when processing some records.  I have traced the issue to an errant "\u0001" character showing up downstream.  I am unable to determine if this comes from the source stream or as a result of serialization/deserialization - or reading and writing from disk.

Is there any way to access the original, unmodified, string that was used in a serialization process from a JObject?

I know there are otherways to track down the underlying issue I'm having, but I think this would be a nice feature/option and useful in many other ways.  It is not clear to me if calling ToString() on a JObject would be equal to the source string - and I suspect it is not.  

Thanks,
Brad Serbu

**Comment by JamesNK** [comment]
You cannot

**Comment by bradserbu** [comment]
James,

Thank you for the quick reply.

Brad
