### ISSUE TITLE
"null" and "undefined" token should not be ignore in the JObject.Merge process.

### ISSUE THREAD

**Issue by JasonMing** [JamesNK/Newtonsoft.Json#531]
```csharp
var source = JObject.FromObject(new
{
	x1 = "string",
	x2 = 0,
	x4 = (Object)null,
});

var patch = JObject.FromObject(new
{
	x1 = JValue.CreateNull(),
	x2 = JValue.CreateUndefined(),
	x3 = "added",
});

source.Merge(patch);

source["x1"].Type.ShouldEqual(JTokenType.Null); // Error: there is no any ways to set a property to null by JObject.Merge
source["x2"].ShouldBeNull(); // Error: there is no any ways to remove a property by JObject.Merge
source["x3"].ShouldNotBeNull();
source["x4"].ShouldNotBeNull();
```

When merging the `patch` to `source`, I'm expecting that set the `x1` to `null` but not remove it and remove the `x2` property.
But currently the `JObject.Merge` method ignores the `null` and `undefined` tokens.

I think the behavior of `JObject.Merge` should follow these rules:

0. add or replace the non-`undefined` property (includes `null`)
0. remove the `undefined` property (also matching the its own semantics "undefine")
0. recursive merge if the patching property is a container type.

**Comment by JamesNK** [comment]
I don't want to give undefined any special behavour but if someone wants to submit a PR which adds configuration to JsonMergeSettings for handling null then I would probably accept it.

**Comment by tmenier** [comment]
Curious on the status of this PR. We're using `JObject.Merge` to implement PATCH in a Web API project. The ability to clear values by explicitly passing null is crucial, so this feature would be extremely useful. Thanks!

**Comment by gautelo** [comment]
Please merge this in and release. It's a very typical scenario. Sure, a lot of time you want union style merging where you want the nulls to be ignored. But often the nulls carry meaning, and you actually want them to override an otherwise set value.

**Comment by tmenier** [comment]
@JamesNK Could you comment on whether this PR is on your roadmap? Again, for us, this is the one hangup preventing it from being the perfect way to implement PATCH in our Web API. We've had users raise the issue and we'll soon be forced to go a different direction if this doesn't make it into a release. Thank you!

**Comment by mlund01** [comment]
+1

**Comment by JamesNK** [comment]
Done

I have added MergeNullValueHandling https://github.com/JamesNK/Newtonsoft.Json/commit/a31c30d50a748cb57eaf4fdd76048c39af1010bc#diff-56073d7d426edd2456bd17888d838efaR574

**Comment by tmenier** [comment]
Awesome! Thanks so much James! :+1::+1::+1:

**Comment by JasonMing** [comment]
Awesome! Thanks a lot :+1:

**Comment by gautelo** [comment]
Thank you! :)
