### ISSUE TITLE
Consecutive JObject.Load() calls cause a JsonReaderException

### ISSUE THREAD

**Issue by nitrocaster** [JamesNK/Newtonsoft.Json#534]
`JsonReader` have property `SupportMultipleContent` that by design allows reading concatenated json objects. `JObject.Load(JsonReader)` does its work first time, but when it's called at the second time, it actually checks the last token read by previous call (instead of reading a new token). `JObject.Load(JsonReader)` expects `JsonReader.TokenType` to be `None`/`Comment`/`StartObject`, and since last token was `EndObject`, it throws a `JsonReaderException`:

    Additional information: Error reading JObject from JsonReader. Current JsonReader item is not an object: EndObject. Path '', line 1, position 37.

Simple workaround is to insert `JsonReader.Read()` between `JObject.Load(JsonReader)` calls, but I think it should be fixed somewhere inside `JObject.Load(JsonReader)`.

**Comment by JamesNK** [comment]
I don't like making this automatic. Automatically reading past a content would be unexpected if you were reading multiple primitive values. It would automatically read past the initial value.
