### ISSUE TITLE
Deserializing generic types with type metadata across multiple assemblies doesn't work

### ISSUE THREAD

**Issue by tystol** [JamesNK/Newtonsoft.Json#537]
Please see attached pull request for reproducing unit test: https://github.com/JamesNK/Newtonsoft.Json/pull/536

Note that it seems to be dependent on the order the assemblies are loaded. i.e. If you run the unit test by itself, it passes. But if you run all unit tests in the solution (so that the core test assembly loads first) it fails.

The exception is:

    Newtonsoft.Json.JsonSerializationException : Error resolving type specified in JSON 'Newtonsoft.Json.Tests.TestObjects.DocumentChanged`2[[System.Guid, mscorlib],[Newtonsoft.Json.Tests.AnotherAssembly.Foo, Newtonsoft.Json.Tests.AnotherAssembly]], Newtonsoft.Json.Tests'. Path '$type', line 2, position 195.
      ----> Newtonsoft.Json.JsonSerializationException : Could not find type 'Newtonsoft.Json.Tests.TestObjects.DocumentChanged`2[[System.Guid, mscorlib],[Newtonsoft.Json.Tests.AnotherAssembly.Foo, Newtonsoft.Json.Tests.AnotherAssembly]]' in assembly 'Newtonsoft.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by JamesNK** [comment]
I don't think it is the order that they're loaded, it is where they are loaded from. When the test is run by itself the Newtonsoft.Json.Tests assembly is in the AnotherAssembly directory, when they're run together then it is loaded from the main test project directory. I'm guessing the AnotherAssembly dll not being in that directory is why it fails.

I don't know anyway to fix this bug. It looks internal to the .NET framework.

**Comment by tystol** [comment]
I looked into this a little further, your spot on, it's to do with the assembly location of the inner generic types when using  `Assembly.GetType(typeName);`

I found someone having a similar problem on SO, with this answer: http://stackoverflow.com/a/662657/505457

Basically it avoids relying on `Assembly.GetType(typeName)` for generics, and instead parses and builds the generic types from its generic definition and constituent simple types.

I needed to tweak it slightly to work for both simple and full type name serialization.

Not sure if you want to take the dependency on all this extra code for a very rare edge case, but I've added it to this PR anyway:
https://github.com/JamesNK/Newtonsoft.Json/pull/538
