### ISSUE TITLE
Dynamic Json Parsing 

### ISSUE THREAD

**Issue by Hijdra** [JamesNK/Newtonsoft.Json#540]
Hi,

I had the problem that I could not parse Json to a dynamic.
After some research and the whole internet (except 1 stackoverflow answer) says it is possible I figured out that some builds indeed support parsing to dynamic but others fail to do it.
This answer on StackOverflow that helped me: http://stackoverflow.com/a/26305953/2843139

Is this feature disabled, removed or a bug?

Tested on the following versions:
6.0.5: Works
6.0.6: Fails
6.0.8: Fails
7.0.1-beta2: Fails

Code I am using:
var session = JsonConvert.DeserializeObject<dynamic>(content);
if (session.sessionInfo)
.. rest of the code

Exception being throwed on the if statement on the non working versions: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'sessionInfo'

Greetings,
Mark Hijdra

**Comment by JamesNK** [comment]
This works for me: https://github.com/JamesNK/Newtonsoft.Json/blob/841464d014a1d0a67a28f7d2a2fef65c19b3b9e9/Src/Newtonsoft.Json.Tests/Linq/DynamicTests.cs#L71-L83
