### ISSUE TITLE
CamelCasePropertyNamesContractResolver camel-cases dictionary keys.

### ISSUE THREAD

**Issue by erik-kallen** [JamesNK/Newtonsoft.Json#543]
When serializing a ```Dictionary<string, T>``` using a CamelCasePropertyNamesContractResolver, all keys in the dictionary are camel-cased. This might be what someone wants sometimes, but I think it is far more common to not want this behavior, as it will make the dictionary after deserialization different to what it was before serialization.

Is this possible to either change (maybe not for compatibility reasons) or to have a switch for it?

**Comment by JamesNK** [comment]
It can't change for compatibility reasons. I've added a new method to override it.

https://github.com/JamesNK/Newtonsoft.Json/commit/0929c2b4c3349ae1fb3d22c522504fbf57c8268e
