### ISSUE TITLE
OutOfMemoryException serializing big object-graph while tracer is activated.

### ISSUE THREAD

**Issue by Crusjiber** [JamesNK/Newtonsoft.Json#550]
Json.net Version 6.0.8:
We are writing 1GB of data during serialization. If we trace, we get an OutOfMemoryException. Following line 927 in the Method _SerializeInternal_ in file JsonSerializer.cs uses _GetJson()_ to write the log.:

            if (traceJsonWriter != null)
                TraceWriter.Trace(TraceLevel.Verbose, "Serialized JSON: " + Environment.NewLine + traceJsonWriter.GetJson(), null);

_GetJson()_ calls _StringWriter.ToString()_ causing the OutOfMemoryException to be thrown.

**Comment by JamesNK** [comment]
I've made some minor improvements but there will always be the potential for an out of memory exception. I recommend either turning down the trace level or disabling tracing.

**Comment by Crusjiber** [comment]
Thanks.
