### ISSUE TITLE
Conditional property serialization

### ISSUE THREAD

**Issue by berkayerkoy** [JamesNK/Newtonsoft.Json#554]
Hello,

I implemented custom JsonConverter by using JsonConverter abstract class and JsonConverterAttribute on some properties of object. In WriteJson abstract method, we can't access root object.So if we need to serialize or not serailize a property according to other property values of root object, we can't achieve this. I checked the SerializObject method of JsonSerializerInternalWriter.cs . In this method, root object was serialized property by property in a for loop. Is there a way send to value parameter to SerializeValue method call in line 407? Actually, i don't want to change source code of newtonsoft.json and build a custom version. Is there a any way to implement this requirement.

Regards

**Comment by JamesNK** [comment]
No. If there is conditional serialization then you'll need to do that at a higher level within a JsonConverter.
