### ISSUE TITLE
JObject.IsValid repeats error when validating against enum

### ISSUE THREAD

**Issue by ericbock** [JamesNK/Newtonsoft.Json#555]
The example below calls JObject.IsValid, testing that a property has a value defined in a Json Schema enum. Instead of getting one error back I get three. I thought that might be tied to the number of valid enum values but that's not the case.

We're just now upgrading from 4.5.11 where the expected one error was returned. It looks like this behavior started in 5.0.1. I understand the main Json Schema support has now been pulled out into its own release. Are there further bug fixes going into the Json Schema support in Json.Net proper?
```
var schema = @"
        {
          'type': 'object',

          'properties': {
            'example': {
              'type': 'array',
              'items': {
                'type': 'object',
                'properties': {
                  'change': { 'type': 'string', 'enum': ['create', 'update', 'delete'], 'required': true },
                 }
              }
            }
          }
        }
";

IList<string> errors;
var json = "{ 'example': [ { 'change': 'NOTVALID' } ] }";
var message = JObject.Parse(json);
var isValid = message.IsValid(JsonSchema.Parse(schema), out errors);
```
The errors:

```
Value "NOTVALID" is not defined in enum. Line 1, position 37.
Value "NOTVALID" is not defined in enum. Line 1, position 37.
Value "NOTVALID" is not defined in enum. Line 1, position 37.
```

**Comment by JamesNK** [comment]
I'm not working on it anymore. It is obsolete in the latest beta.
