### ISSUE TITLE
WinRT netcore45 support in package

### ISSUE THREAD

**Issue by weshaggard** [JamesNK/Newtonsoft.Json#557]
With change https://github.com/JamesNK/Newtonsoft.Json/commit/4bc6e27e729a412e163422875bc16fd4b34e9fdf#diff-95703670960dd65fdfc549b890c6c224 it looks like netcore45/WinRT support was removed from the package build but I couldn't find any explanation for it. Is there a reason it was removed?

**Comment by JamesNK** [comment]
There is a PCL that supports netcore45
