### ISSUE TITLE
Property Contract Resolution on JsonIgnore

### ISSUE THREAD

**Issue by Tydude4Christ** [JamesNK/Newtonsoft.Json#558]
I've encountered an issue where a property contract is trying to be resolved on a property with the JsonIgnore attribute. This is throwing a FileNotFoundException when trying to resolve the contract due to this property's type being within an outside library that is dynamically linked at runtime through an assembly resolver. It's throwing because it shouldn't need to resolve the dll for deserializing a JsonIgnore property that is not populated.

The problem is in the EndObject method of JsonSerializerInternalReader. I was able to get it to work if I changed this line

if (property.PropertyContract == null)
    property.PropertyContract = GetContractSafe(property.PropertyType);

to

if (property.PropertyContract == null && !property.Ignored)
    property.PropertyContract = GetContractSafe(property.PropertyType);

Thanks for the awesome library!

**Comment by JamesNK** [comment]
Interesting bug. FIxed.

**Comment by Tydude4Christ** [comment]
It was indeed. Thanks! You're awesome.
