### ISSUE TITLE
System.IO.FileNotFoundException on UAP projet

### ISSUE THREAD

**Issue by slouge** [JamesNK/Newtonsoft.Json#559]
Hi,
On a Windows Universal (UAP) project i'm getting this exception when using JsonConvert.DeserializeObject
=>
An exception of type 'System.IO.FileNotFoundException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Could not load file or assembly 'System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.

Works fine on Universal App (Windows 8.1 ans Windows Phone 8.1)

Thanks

**Comment by deltakosh** [comment]
Have the same issue

**Comment by JamesNK** [comment]
Can't help you, I don't have a computer with VS2015rc and hyperv to test on.

**Comment by mgbee8** [comment]
It's because JsonTextReader and JsonTextWrite use System.IO.TextReader and TextWriter respectively which are not supported in Dot Net Core.
These implementations, and any others using TestReaderWriter must be changed to using StringReader and StringWriter respectively for JSON.net to be fully compatible with coreClr

**Comment by JamesNK** [comment]
CoreCLR doesn't have TextReader?! Where did you see that. StringReader inherits from TextReader in normal .NET

**Comment by slouge** [comment]
When clone json.net workspace, the project Newtonsoft.Json.WinRT doesn't build. This one doesn't reference JsonRequiredAttribute.cs

**Comment by JamesNK** [comment]
Newtonsoft.Json.WinRT isn't used anymore. It has been replaced by Newtonsoft.Json.Portable.

**Comment by JamesNK** [comment]
For anyone who is getting this error:

1. Remove the DLL reference to NewtonsoftJson.dll in the portable-net40+sl5+wp80+win8+wpa81 directory
2. Add a reference to Newtonsoft.Json.dll in the portable-net45+wp80+win8+wpa81+dnxcore50 directory

Let me know if that works for you.

**Comment by Kornelis** [comment]
Manually Changing the Reference to the Newtonsoft.Json.dll in the portable-net45+wp80+win8+wpa81+dnxcore50 directory did the trick :) Thanks :)

**Comment by kamenlitchev** [comment]
Shouldn't this be fixed in Nuget?

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/602

**Comment by o0rebelious0o** [comment]
I can see the same issue in a windows 10 universal platform app with 7.0.1, downgrading to 6.0.8 works okay
