### ISSUE TITLE
Required Property Deserialization Error

### ISSUE THREAD

**Issue by Tydude4Christ** [JamesNK/Newtonsoft.Json#560]
I'm getting an error on a Required Property of a class that it wasn't present in the json though it is. Below is unit test code to reproduce.

    public void FooTest()
    {
        var foo1 = new Foo(new[] { "A", "B", "C" });
        var json = JsonConvert.SerializeObject(foo1);
        var foo2 = JsonConvert.DeserializeObject<Foo>(json); // Throws here.
        Assert.AreEqual(foo1.Bars.Count, foo2.Bars.Count);
        Assert.AreEqual(foo1.Bars[0], foo2.Bars[0]);
        Assert.AreEqual(foo1.Bars[1], foo2.Bars[1]);
        Assert.AreEqual(foo1.Bars[2], foo2.Bars[2]);
    }

    public class Foo
    {
        [JsonProperty(Required = Required.Always)]
        public List<string> Bars { get; private set; }

        public Foo(IEnumerable<string> bars)
        {
            Bars = new List<string>(bars);
        }
    }

It appears the issue is in the CreateObjectUsingCreatorWithParameters method in the JsonSerializerInternalReader class. I was able to get it to work if I changed

    // map from creator property to normal property
    JsonProperty presenceProperty = propertiesPresence.Keys.FirstOrDefault(p => p.PropertyName == property.PropertyName);

to

    // map from creator property to normal property
    JsonProperty presenceProperty = propertiesPresence.Keys.FirstOrDefault(p => string.Equals(p.PropertyName, property.PropertyName, StringComparison.OrdinalIgnoreCase));

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/6173ca1574de47075630f0ce52314778ab60e5bb

**Comment by Tydude4Christ** [comment]
Thank you!
