### ISSUE TITLE
PreserveReferencesHandling custom keys

### ISSUE THREAD

**Issue by redben** [JamesNK/Newtonsoft.Json#561]
PreserveReferencesHandling adds ``$id``s and references using ``$ref``. That is fine if you have control on the service and client code. 
But if you are using json.Net as a client consuming an external service on which you have no control and which uses references in its own way. For example ``@id`` instead of ``$id``, you need to be able to customise your (de)serializer so that it uses ``@id`` instead of ``$id``.

So can PreserveReferencesHandling be customized to support such a use case  ?

**Comment by JamesNK** [comment]
Nope

**Comment by redben** [comment]
Wow a dry nope. Is there any plans to support something like this ?

**Comment by JamesNK** [comment]
Nope. This is how the serializer works.
