### ISSUE TITLE
3.5 compact problem

### ISSUE THREAD

**Issue by hvolmer** [JamesNK/Newtonsoft.Json#562]
I am trying to work with 3.5 compact - I'm not entirely sure of the rev, since it's provided for us.  

Using JObject.Parse() on incomplete JSON like

{ "Note": 

Will return a JSON object when it should return null. This is troublesome when trying to verify that our incoming JSON is "complete" before we work on it.  I see this has been fixed in a version 6 release, but we are stuck in 3.5CF.  Can this be fixed?

I have tried building a separate project outside of our "sandbox" using downloaded 35r8, which I believe is the end of the CF line, and I experience the problem.  

Thank you for an otherwise outstanding project!

**Comment by JamesNK** [comment]
I don't support 3.5 compact anymore.
