### ISSUE TITLE
Unable to add nuget to a Xamarin.iOS project under Visual Studio 2015

### ISSUE THREAD

**Issue by jherby2k** [JamesNK/Newtonsoft.Json#563]
This is preventing me from using Azure Mobile Services, which has the Newtonsoft.Json nuget package as a dependency. Easily reproduced - just create a Xamarin iOS project and try to add Newtonsoft.Json via nuget. This is the error:

Could not install package 'Newtonsoft.Json 6.0.8'. You are trying to install this package into a project that targets 'Xamarin.iOS, Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

A new project under VS2013 can add this reference just fine. Seems to happen with every version of the nuget, although 6.0.8 is the one needed by Azure.

**Comment by JamesNK** [comment]
Sounds like a NuGet bug. Raise it with them

// @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Please let us know what version you are using rc or rc2? Nuget rc2 is currently available on nuget.codeplex.com
