### ISSUE TITLE
Unicode character with \U need to be handled JsonText

### ISSUE THREAD

**Issue by Poppyto** [JamesNK/Newtonsoft.Json#565]
In JsonTextReader.ReadInternal(), the parsing is ok if we have a unicode like this \uXXX but not ok with a \UXXX.

As it's described in the MSDN (https://msdn.microsoft.com/en-us/library/aa664669(v=vs.71).aspx) Unicode can be written with both u and U.

Thank for resolving.

**Comment by JamesNK** [comment]
That's in C#. In JSON the u is always lowercase.

**Comment by Poppyto** [comment]
Ok, I will contact my json provider
