### ISSUE TITLE
Required.Always doesn't stop the property from being deserialised as null

### ISSUE THREAD

**Issue by matburton** [JamesNK/Newtonsoft.Json#566]
The description against [Required.Always](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Required.cs#L44) says:
> The property must be defined in JSON and cannot be a null value.

At the moment the following test fails (tested against version 6.0.8 and 6.0.1)

```cs
[Test]
public void Required_always_properties_cannot_be_deserialised_as_null()
{
    var binding = JsonConvert.DeserializeObject<Binding>
        ("{requiredProperty:''}");

    Assert.That(binding.RequiredProperty, Is.Not.Null);
}

private sealed class Binding
{
    [JsonProperty(Required = Required.Always)]
    public Binding RequiredProperty { get; set; }
}
```

This isn't what I expected from the naming or the documentation. Is the current behaviour correct?

**Comment by matburton** [comment]
It looks like JsonSerializerInternalReader [treats empty strings as a magic value and coerces them to nulls](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L282) as a special case.

This coercion is done after the [place where JsonSerializerInternalReader decides whether a property has a value or not](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2002) so later [when the constraints specified by the attributes are checked](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L2084) it doesn't think there's been a violation because ```presence``` is ```PropertyPresence.Value``` even though the property on the actual object instance was set to ```null```.

There are few ways to fix this:
* Stop treating empty strings as magic values and remove the special case empty string to null coercion.
* Somehow change the ordering such that property ```presence``` is worked-out after coercion and takes into account coercion applied.
* Add more code around this special case coercion such that it changes the ```presence``` to ```PropertyPresence.Null```.

In my subjective opinion the former is preferable as special case coercion is _at best_ confusing. Empty strings are not equivalent to null and _especially_ not when we weren't even expecting a string. However whether existing consumers rely on this 'feature' might be the sticking point. Would removing the coercion be a bug fix or just a breaking change in behaviour?

**Comment by JamesNK** [comment]
Option 1 would be a breaking change.

I went with option 3 https://github.com/JamesNK/Newtonsoft.Json/commit/70521eea88c7e6a24c0446b9e0d20617c9a6fad2

**Comment by matburton** [comment]
@JamesNK you're totally awesome :+1: thanks
