### ISSUE TITLE
Json.net lite?

### ISSUE THREAD

**Issue by SimonCropp** [JamesNK/Newtonsoft.Json#568]
So firstly thanks for an awesome library. The large feature set and long history of bug fixes is indicative of the continued effort put into this project.

I wanted to ask if anyone had ever considered a "Json.net lite" that targets simply serializing and deserializing classes. 

### Reasoning

 * the currently pdb+dll are running at 995K which for many use cases is overly large
 * many people want to abstract away the use of an external json library and hence ILMerge json .net, adding 995K to their library. people are more likely to use json.net and ILMerge it if it is smaller. eg https://github.com/aspnet/Announcements/issues/24
 * very large surface area. for people starting on json.net it can be daunting
 * reduced assembly load time
 * possibly faster performance+less memory usage
 * smaller codebase means fewer bugs and fewer releases
 * smaller api surface area means breaking changes happen less often.

### Things that could (possibly) be removed

 * Linq support
 * immutable collections
 * support for sql types
 * expando objects+ dynamic
 * collection notification
 * property changed notification
 * bson. there are other better binary formats 
 * schemas
 * datatable and dataset
 * xml note conversion

### How would this work with the existing "full json.net"

It could be handled either through code file sharing between projects in VS or by doing an IL merge.

**Comment by JamesNK** [comment]
I'm planning in the far future to remove the schema stuff in Json.NET, but otherwise I don't want to make a lite version.

I recommend using SimpleJson.

**Comment by SimonCropp** [comment]
@JamesNK SimpleJson just isnt feature complete enough. i have tried. it would be less work forking json.net and removing stuff than attempting to bring SimpleJson up to an acceptable level. also SimpleJson seems to be abandoned. no commits in over a year, no traction on the multiple issues and PRs.

**Comment by JamesNK** [comment]
You'll have to use Json.NET then.

I don't want to make a lite version because it would be a whole new library to maintain and it would conflict with Json.NET. Nothing would be portable between them.

**Comment by SimonCropp** [comment]
@JamesNK ok thanks for considering this. since it is not going to happen I will close.
