### ISSUE TITLE
Change property value while converting from XML to JSON

### ISSUE THREAD

**Issue by IrvinDominin** [JamesNK/Newtonsoft.Json#569]
In a project I'm getting some data from DB using TSQL FOR XML. In all tables the minimun value for Date fields is set to 01/01/1900.

That's because null values are not permitted as an internal politic that cannot be changed

With the xml result I need to convert it to JSON and serialize it to a client.

For doing so I'm using:
```
string jSonString = Newtonsoft.Json.JsonConvert.SerializeXmlNode(xmlDoc, Newtonsoft.Json.Formatting.None, true);
```
Good; now I need to convert each 01/01/1900 date to DateTime.MinValue (01/01/0001) while converting into JSON; how can I handle this?

**Comment by JamesNK** [comment]
This isn't a bug. Ask on Stackoverflow.

**Comment by IrvinDominin** [comment]
Ok, thanks. Here is the question http://stackoverflow.com/q/30239402/975520, I can't find a way to handle this
