### ISSUE TITLE
Invaild Argument while trying to deserialize response object in MVC5

### ISSUE THREAD

**Issue by Chidananda03** [JamesNK/Newtonsoft.Json#571]
I am trying to deserialize a http message response object , but getting invalid argument ( the parameter is not correct error) in an ASP.NET MVC5 application. However i am able to see the json data of the response object in the fiddler. Below is the code that throws exception.

DeserializeAsync<MyObjectType>( response ).ConfigureAwait( false )

Moreover same piece of code works when i try to invoke the call from a console application.
In both the application I am using 6.0.8 version.

**Comment by JamesNK** [comment]
Ask on StackOverflow.
