### ISSUE TITLE
Could not create an instance of type X. Type is an interface or abstract class and cannot be instantiated

### ISSUE THREAD

**Issue by omatrot** [JamesNK/Newtonsoft.Json#572]
Using version 7.0.1 Beta3, I'm trying to serialize/deserialize a complex POCO with properties that are arrays of abstract classes. These arrays could contain instance of classes that are derived from abstract ones.

At serialization, everything seems OK. The Json fragment below shows that the type information is set correctly.

Json fragment :
"Items": [
          {
            "$type": "IVXB_TS, ...",
            "inclusive": true,
            "value": "20091231"
          }
        ]

But a deserialization it fails with the following error.

Could not create an instance of type QTY. Type is an interface or abstract class and cannot be instantiated. 

The class hierarchy is the following :
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_TS))]
public abstract partial class ANY : object, System.ComponentModel.INotifyPropertyChanged
{
}

[System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_TS))]
public abstract partial class QTY : ANY
{
}

[System.Xml.Serialization.XmlIncludeAttribute(typeof(IVXB_TS))]
public partial class TS : QTY
{
}

public partial class IVXB_TS : TS
{
}

The Items property :

[System.Xml.Serialization.XmlElementAttribute("high", typeof(IVXB_TS))]
[System.Xml.Serialization.XmlElementAttribute("low", typeof(IVXB_TS))]
public QTY[] Items

Is this a configuration issue ?

**Comment by JamesNK** [comment]
Ask on Stackoverflow

**Comment by omatrot** [comment]
http://stackoverflow.com/questions/30349695/could-not-create-an-instance-of-type-x-type-is-an-interface-or-abstract-class-a

**Comment by kushanfernando** [comment]
> http://stackoverflow.com/questions/30349695/could-not-create-an-instance-of-type-x-type-is-an-interface-or-abstract-class-a

thanks for deciding to come back and post the link here. and being supportive to the community.
