### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.Dynamic.ExpandoObject'.

### ISSUE THREAD

**Issue by MahmoudFawzy** [JamesNK/Newtonsoft.Json#576]
this my code and return the error on title
<code>
 Public Shared Function GetChannels() As ExpandoObject
        Dim rstClient As RestClient = New RestClient(Api_Url)

        Dim rstRequest As RestRequest = New RestRequest("channels", Method.GET)
        rstRequest.AddParameter("part", "contentDetails")
        rstRequest.AddParameter("forUsername", clsHelper.ConfigGet("Youtbue_User"))
        rstRequest.AddParameter("key", clsHelper.ConfigGet("Google_API_KEY"))

        Dim rstResponse As IRestResponse = rstClient.Execute(rstRequest)
        Return JsonConvert.DeserializeObject(rstResponse.Content)
    End Function
</code>

**Comment by JamesNK** [comment]
Ask on stackoverflow.
