### ISSUE TITLE
Extracting interfaces of JsonWriter, JsonReader and JsonSerializer in JsonConverter

### ISSUE THREAD

**Issue by Sindberg** [JamesNK/Newtonsoft.Json#579]
It would make testing alot easier if the parameters for the abstract methods in JsonConverter were of an interface instead of concrete types.

For an example if this was the signature of the WriteJson method:
public override void WriteJson(IJsonWriter writer, object value, IJsonSerializer serializer)

**Comment by JamesNK** [comment]
That's a breaking change. Wrap Json.NET in your own abstraction if you want to mock it.
