### ISSUE TITLE
[enhancement] Add JsonMigrationConverter concept 

### ISSUE THREAD

**Issue by eggapauli** [JamesNK/Newtonsoft.Json#580]
Versioning json data is currently a problem not solved by Json.Net. For example we have classes that look like this in our current production app:

    [DataContract]
    [Migratable("7b679a63ad7942c6e3374addfa8abc63f9717e7c")]
    public class MoineauMachinePathSolverDocumentConfiguration 
    {
        [DataMember]
        public double MachinePathTolerance { get; private set; }

        private static JToken Migrate_1(JObject data)
        {
            data["MachinePathTolerance"] = Moineau.MachiningTolerance.ToString();
            return data;
        }

        private static JToken Migrate_2(JObject data)
        {
            data.Remove("FlankSelection");
            return data;
        }
    }

We built a custom `JsonConverter` that runs all of the necessary migration methods on the data. Because it doesn't really deserialize the data it then delegates to the serializer to do the actual deserialization. Our implementation is:

    public class MigrationConverter : JsonConverter
    {
        protected IMigrateData<JToken> DataMigrator;

        readonly ThreadLocal<Dictionary<Type, bool>> _MigratedTypes =
            new ThreadLocal<Dictionary<Type, bool>>(() => new Dictionary<Type, bool>());

        public MigrationConverter(IMigrateData<JToken> dataMigrator)
        {
            DataMigrator = dataMigrator;
        }

        public override bool CanWrite { get { return false; } }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotSupportedException();
        }

        public static bool GetOrDefault
            (Dictionary<Type, bool> @this, Type type, bool def)
        {
            bool value;
            return @this.TryGetValue(type, out value) ? value : def;
        }

        public override bool CanConvert(Type objectType)
        {
            var isMigrated = GetOrDefault(_MigratedTypes.Value, objectType, false);
            var isMigratable = objectType.GetCustomAttribute<MigratableAttribute>() != null;
            return !isMigrated && isMigratable;
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var data = JToken.Load(reader);
            var migratedData = DataMigrator.TryMigrate(data, objectType);

            try
            {
                _MigratedTypes.Value[objectType] = true;
                return serializer.Deserialize(migratedData.CreateReader(), objectType);
            }
            finally
            {
                _MigratedTypes.Value[objectType] = false;
            }
        }

However the technique is a bit hacky because delegating to the serializer would normally yield in an endless loop (because the `MigrationConverter` is picked all the time). So it remembers which type it just migrated and ensures it's not picked again for the same instance.

Can you suggest a better way to integrate this into Json.Net or provide some pre and post serialization hooks to assist?

**Comment by JamesNK** [comment]
You could do this via extension data + serialization events.

**Comment by eggapauli** [comment]
Basically this works, however extension data + serialization events are not as powerful as we need them to be. For example, you can't change the property type only (you also have to change the name of the property). We also had one type which we started to serialize as an array and then switched to serializing it as an object (because we added some properties). Extension data + serialization events can't handle this case.

We figured out that the underlying problem is that extension data + serialization events work on the c# model whereas our current solution works on the raw json data (`JObject` and friends)
