### ISSUE TITLE
Unexpected character error

### ISSUE THREAD

**Issue by jenokizm** [JamesNK/Newtonsoft.Json#583]
error:
> "Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0."
on json text:
> ﻿{"ishavework":false,"num":null,"work":null}

**Comment by jenokizm** [comment]
I found the solution! it was a Byte Order Mark from utf-8...
It had only to remove this invisible character and it worked!
ps. please add in the next version of the processing of these symbols

**Comment by JamesNK** [comment]
They should be handled by the correct use of StreamReader.

**Comment by andresmoschini** [comment]
But it is not.
