### ISSUE TITLE
Nuget package for 6.0.8 is reporting wrong version

### ISSUE THREAD

**Issue by Adelaiglesia** [JamesNK/Newtonsoft.Json#584]
When adding package from nuget in Visual Studio the package is reporting v7.0.0.0 causing the solution not to compile.

**Comment by JamesNK** [comment]
Are you sure you're not adding one of the 7.0 betas?

**Comment by Adelaiglesia** [comment]
It's a nuget on Visual Studio 2015 RC Bug. I'll report to it's team. In VS 2013 Everything is working as expected. :)

Thank you.
