### ISSUE TITLE
Can't deserialize T as List<SomeClass> with TypeNameHandling.All

### ISSUE THREAD

**Issue by philippe-lavoie** [JamesNK/Newtonsoft.Json#586]
The following code worked with Json.Net 5, with version 6.0.8, it doesn't work. I raised a question on this on StackOverflow but no one can find a work around. I'm assuming it's a bug.

    namespace ShowingBug
    {
      public class InterestingResult
      {
        public string Information { get; set; }
      }

       public class Result<T> 
      {
        public T Data { get; set; }
        public int ResultCode { get; set; }
      }

    class Program
    {
        static void Main(string[] args)
        {
            var veryInteresting = new List<InterestingResult>();
            veryInteresting.Add(new InterestingResult() { Information = "Good" });

            Result<List<InterestingResult>> operationResult = new Result<List<InterestingResult>>();
            operationResult.Data = veryInteresting;
            operationResult.ResultCode = 1;

            JsonSerializerSettings serializerSettings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Auto
            };

            var json = JsonConvert.SerializeObject(operationResult, serializerSettings);
            dynamic result = JObject.Parse(json);
            string information = (string)result.Data[0].Information;

            Console.Out.WriteLine(information);

            //The above works, however after some digging... 
            // I found that the option we use is not Auto, but All

            serializerSettings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.All
            };

            json = JsonConvert.SerializeObject(operationResult, serializerSettings);
            result = JObject.Parse(json);

            // Now, you get an ArgumentException from Json.net 6.0.8 on the following line
            information = (string)result.Data[0].Information; 

            // It worked in previous version of Json.Net
            // I'm using .net 4.5.2 (if that makes a difference)
        }
      }
    }

**Comment by JamesNK** [comment]
I got the same result in Json.NET 5.0

**Comment by philippe-lavoie** [comment]
I'm curious, don't you agree it's a bug ? Shouldn't TypeNameHandling.All work?  

And I'll have to revert the library to an earlier version since It did work then.

**Comment by JamesNK** [comment]
TypeNameHandling.All does work, `(string)result.Data[0].Information;` is just wrong when using it.
