### ISSUE TITLE
wrapping objects with a named root

### ISSUE THREAD

**Issue by tpfkakey** [JamesNK/Newtonsoft.Json#588]
I recently was asked to provide a client web application with a JSON data string that follows a specific pattern.  Four distinct "recordsets", each one accessed by a root name.  within each "recordset", an object also accessed with a name (forgive syntax errors as I type this by hand from memory).  I created a simple DTO that gets populated from the data fetch and then serialzed (yes, each of the 4 recordsets has the same structure).  to simplify:

{"newOpportunities":{"1":{"id":"1","firstname":"tim", "lastname": "Pezzelle"},"2":{"id":"2","firstname":"john","lastname":"doe"}},
"newResponses":{...}},"managerAttention":{...}}.....

the idea being that the client code can access this data as result.newOpportunities.1.firstname.

I couldn't find a "native" way to do this, so I used JsonConvert to deserialize each object and then did some simple stringbuidler stuff to make it work.

it seems like it would be a nifty feature to allow the optional declaration of an object property to act as this "root wrapper" for the object as it is serialized.  

on the other hand, the tool may already do this and I just missed it in the docs!

thanks

**Comment by JamesNK** [comment]
Could be done with LINQ to JSON.
