### ISSUE TITLE
Decimal with no decimal point serialized as a Decimal with a decimal point

### ISSUE THREAD

**Issue by djluck** [JamesNK/Newtonsoft.Json#590]
When serializing a Decimal without a decimal point (e.g. 26m), it is serialized and deserialized as a Decimal with a decimal point (e.g. 26.0m). While this does not affected object equality, it does cause issues such as comparing the .ToString() results (e.g "26" vs "26.0").

Would it be possible when serializing and deserializing the Decimal type that the lack of a decimal point can be respected?

**Comment by Ch4rg3r** [comment]
If it's not implemented, you could use some small tricks to do so...
by using floor you get the next lower integer, you can then subtract this from your original decimal number and get the 0.XX number. jsut compare to zero. if false use decimal, if true convert to int and the decimal point is gone...

**Comment by JamesNK** [comment]
That's by design. All non-integer values have a decimal point added when serialized.

**Comment by djluck** [comment]
Thanks for replying James. I appreciate this is by design (I would have done exactly the same thing) but it seems that 26m and 26.0m are not exactly equal (even though EqualTo() returns true), as ToString() demonstrates. Perhaps there could be an option to control this behavior?
