### ISSUE TITLE
Getting array data using JObject.Values<T>("Field") fails to enumerate

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [JamesNK/Newtonsoft.Json#591]
Say I have an input string like this

```cs
{ \"Data\": [ \"item1\", \"item2\" ] }
```

If I do either of the following I get out an `IEnumerable` that when evaluated yields the two strings `item1` and `item2`. 

```cs
var s0 = data["Data"].Values<string>();
var s1 = data.Value<JArray>("Data").Values<string>();
```
However, if I do this:
```cs
var s2 = data.Values<string>("Data");
```
Then I get an exception when evaluating the `IEnumerable` saying `Cannot access child value on Newtonsoft.Json.Linq.JProperty.`.

In the first two cases the `IEnumerable` is `Convert<JToken, string>` but in the latter it is `Values<JToken, string>`.

Should the latter use `Convert` as well?

Thanks!

Henrik

**Comment by JamesNK** [comment]
`Values<T>(string)` is a bit weird. It gets the key name from objects in a collection with that key.

e.g. if the values in data were objects instead of strings and they had a key called "name" then this would get those strings:

    var s1 = data.Value<JArray>("Data").Values<string>("name");

**Comment by HenrikFrystykNielsen** [comment]
ah, I see. thanks!
