### ISSUE TITLE
JSONPath - Unexpected character while parsing path indexer: ?

### ISSUE THREAD

**Issue by skykarthick** [JamesNK/Newtonsoft.Json#593]
I've tried JSONPath example shown in http://james.newtonking.com/archive/2014/02/01/json-net-6-0-release-1-%E2%80%93-jsonpath-and-f-support and also in http://www.newtonsoft.com/json/help/html/QueryJsonSelectTokenJsonPath.htm. It throws me an error. 
![json net_unexpectederror](https://cloud.githubusercontent.com/assets/7643036/8249248/8b16d7d0-1668-11e5-9494-f237cc01cef2.png).

I'm using .NET 4.5 and Newtonsoft.Json.6.0.8

**Comment by JamesNK** [comment]
Works for me. And the code on the document page is executed in a unit test that runs each time Json.NET is released.
