### ISSUE TITLE
Error with array that contain empty array

### ISSUE THREAD

**Issue by franck-roland** [JamesNK/Newtonsoft.Json#595]
Hi back,

As you closed my issue faster I could imagine, let me to be more clear on my issue:
I would like your lib to accept arrays with empty arrays as describes here:

https://www.json.com/json-array#array-of-arrays

Is that so difficult to do?
Thanks for all

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#user-content--got-a-question-or-problem
