### ISSUE TITLE
Possible to filter nearest element with SelectToken?

### ISSUE THREAD

**Issue by TheOddler** [JamesNK/Newtonsoft.Json#597]
I'm making a game where some data is read from jsons. I'm allowing users to specify where in the json the data resides. I'm using SelectToken for that.

Some of the json files I get have arrays of objects, and I would like to select one of the element. Though it would be nice if I could select the one with its name closest to some give value.

So for instance:

    JObject o = JObject.Parse(@"{
      ""Manufacturers"": [
        {
          ""Name"": ""Acme Co"",
          ""Products"": [
            {
              ""Name"": ""Anvil"",
              ""Price"": 50
            }
          ]
        },
        {
          ""Name"": ""Contoso"",
          ""Products"": [
            {
              ""Name"": ""Elbow Grease"",
              ""Price"": 99.95
            },
            {
              ""Name"": ""Headlight Fluid"",
              ""Price"": 4
            }
          ]
        }
      ]
    }");
    
    // manufacturer with the name closest to 'Ocme Ca'
    var acme = o.SelectToken("$.Manufacturers[?(@.Name closest to 'Ocme Ca')]");
    // This would give Acme Co
    // or:
    var contoso= o.SelectToken("$.Manufacturers[?(@.Name closest to 'Conto')]");
    // would return Contoso.

Is something like this possible? Or is there a way I can define this as an additional filter my players can use?

Thanks!

Note: I also asked this on [stackoverflow](http://stackoverflow.com/questions/30962355/json-net-selecttoken-possible-to-filter-nearest-string), but though this might be a better place.

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/blob/master/CONTRIBUTING.md#question
