### ISSUE TITLE
Int64 overflow not working for certain ranges

### ISSUE THREAD

**Issue by Finglas** [JamesNK/Newtonsoft.Json#600]
When deserializing a string value that has been provided as a literal integer value then JSON.NET doesn't work in all cases. See the example below to reproduce.

I've added additional information at [StackOverflow.](http://stackoverflow.com/a/30903467)

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Sending in: \n43443333222211111117");
            var largeBrokenNumber = JsonConvert.DeserializeObject<Foo>("{\"Blah\": 43443333222211111117 }");
            Console.WriteLine(largeBrokenNumber.Blah);

            Console.WriteLine();

            Console.WriteLine("Sending in: \n53443333222211111117");
            var largeOddWorkingNumber = JsonConvert.DeserializeObject<Foo>("{\"Blah\": 53443333222211111117 }");
            Console.WriteLine(largeOddWorkingNumber.Blah);
        }
    }

    public class Foo
    {
        public string Blah { get; set; }
    }

A few points to note:

* This works correctly if the value is provided as a string, but we cannot control what the consumers of our external API will provide. 
* This also works if the property "Blah" is set as a decimal as the overflow does not occur.
* Prior to 5.0.4 this wasn't an issue, but WebAPI2 requires 6.x so we can't side step this.
* I have no idea why some values work in a greater range.
* We've determined with some basic test that the range is 40992764608243448034 to  46116860184273879040 that seems to be troublesome.

**Comment by JamesNK** [comment]
This has been fixed. It will be in next release.
