### ISSUE TITLE
Windows 10/UWP: "Could not load file or assembly 'System.Runtime.Serialization'" after upgrading to v7.0.1

### ISSUE THREAD

**Issue by robert-virkus** [JamesNK/Newtonsoft.Json#602]
Hi James and all,

after upgrading Newtonsoft.Json to version 7.0.1 in my UWP project, I get the following exception:

{"Could not load file or assembly 'System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.":"System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes"}

Downgrading to version 6.0.8 solves this problem.

Not sure if this might be a Windows 10 issue, I'm running build 100130 on a SP3. This affects Universal Windows Platform (UWP) projects, haven't checked out others.

Thanks
   Robert

**Comment by JamesNK** [comment]
It's a NuGet bug. Download NuGet 3 RC 2.
