### ISSUE TITLE
JsonTextReader does not respect DateFormatHandling enumeration

### ISSUE THREAD

**Issue by movermeire** [JamesNK/Newtonsoft.Json#607]
When serializing datetime types the JsonTextWriter used the DateFormatHandling setting to format the value to either MicrosoftDateFormat or IsoDateFormat. When deserializing a whole different strategy is used. The JsonTextReader infers the used format from the incoming value. It first tries to parse it as a Microsoft date, then tries to parse it as Iso date and finally it parses it as a regular date using culture settings.

My main goal is to enforce ISO 8601 on all dates either serialized or deserialized. This can be validated using viewmodel validation.

For example:

1972-09-18T04:29:12.264513+02:00; validation => expected=true; actual=true
09-18-1972T04:29:12.264513+02:00; validation => expected=false; actual=false
18-09-1972T04:29:12.264513+02:00; validation => expected=false; actual=false

18-09-1972; validation => expected=false; actual=false
09-18-1972; validation => expected=false; actual=true (this should not parse to a valid date)

**Comment by JamesNK** [comment]
I'm fine with this. If you want to be precious about incoming dates then read them as strings and validate them in a JsonConverter.
