### ISSUE TITLE
DiagnosticsTraceWriter not available

### ISSUE THREAD

**Issue by quincycs** [JamesNK/Newtonsoft.Json#608]
I'm trying to debug why I can't deserialize ... not sure if I can figure it out.  I would like the library to say more than "X" property failed on "Y" model.  I'd like the position in the json it failed at.  So I saw the documentation here http://www.newtonsoft.com/json/help/html/SerializationTracing.htm  but ...

Newtonsoft.Json.Serialization.DiagnosticsTraceWriter();

Is not available in Newtonsoft.Json.7.0.1\lib\portable-net45+wp80+win8+wpa81+dnxcore50\Newtonsoft.Json.dll

Error	CS0234	The type or namespace name 'DiagnosticsTraceWriter' does not exist in the namespace 'Newtonsoft.Json.Serialization' (are you missing an assembly reference?)

**Comment by JamesNK** [comment]
Diagnostics isn't available in a PCL.
