### ISSUE TITLE
Deserializing CancellationToken causes handle corruption

### ISSUE THREAD

**Issue by madelson** [JamesNK/Newtonsoft.Json#609]
We were burned for several days trying to debug an issue relating to deserializing a CancellationToken  with Json.NET (see the full issue described in this post: http://stackoverflow.com/questions/31168001/handle-is-invalid-error-when-opening-sqlconnection/31277850#31277850). 

To be clear, I don't consider this to be a bug in Json.NET: it's just a confluence of how CancellationToken is structured (with the default constructor effectively referencing the global instance)  and how Json.NET works with reflection. On the other hand, the current behavior when deserializing the token is clearly not functional (it ends up re-assigning CancellationToken.None.WaitHandle.Handle) and quite dangerous.

Obviously, no one should be in the business of deserializing CancellationTokens, but it's quite easy for this to happen accidentally if a developer adds a token property to a class without realizing that another part of the code deserializes that class from JSON. This is especially scary because the issue is unlikely to manifest itself in unit tests or other low-load scenarios.

I could see several potential solutions:
* Provide a default deserialization behavior for CancellationToken and/or WaitHandle and/or IntPtr that would throw or otherwise prevent this issue
* Do nothing, but maybe note the risk in the docs

Mostly, I just wanted to make you aware of the issue.

**Comment by JamesNK** [comment]
Thanks but the list of things that it is a bad idea to serialize and deserialize is endless.

**Comment by yfital** [comment]
hey @madelson ,
Unforunatly we wasted a couple of months chasing this issue on a large scale project, as gitHub removed private messaging, i'll be happy to get in contact with you to see how it was detected in your case? (for future learning :))

I dont see a way to otherwise contact you

For anyone else reaching this thread by mistake, be aware that if you attach with VS and get an SEHExcpetion, this is probably the case.

**Comment by madelson** [comment]
@yfital its been a while, but in our case we tracked this down by (1) theorizing that the issue could happen and (2) adding default serializer setting with a custom converter for intptr and friends that would throw hard on attempted serialization/deserialization. Those errors then led us to the offending call. See https://www.newtonsoft.com/json/help/html/DefaultSettings.htm

we kept the default settings after the fact to prevent this from happening again.

**Comment by yfital** [comment]
> @yfital its been a while, but in our case we tracked this down by (1) theorizing that the issue could happen and (2) adding default serializer setting with a custom converter for intptr and friends that would throw hard on attempted serialization/deserialization. Those errors then led us to the offending call. See https://www.newtonsoft.com/json/help/html/DefaultSettings.htm
> 
> we kept the default settings after the fact to prevent this from happening again.

So sorry, i missed your reply!
1. I don't understand how default settings will prevent this from happening? for example, this is a way to always reproduce the issue - https://stackoverflow.com/a/31277850/1548945
2. The custom provider for intptr is a nice idea, i'll add it on top of our CT covertor (which is needed)

**Comment by madelson** [comment]
> I don't understand how default settings will prevent this from happening?

@yfital this is what I mean:

```
class IntPtrConverter : JsonConverter<nint>
{
	public override nint ReadJson(JsonReader reader, Type objectType, nint existingValue, bool hasExistingValue, JsonSerializer serializer)
	{
		throw new InvalidOperationException("Deserializing IntPtr is unsafe!");
	}

	public override void WriteJson(JsonWriter writer, nint value, JsonSerializer serializer)
	{
		throw new InvalidOperationException("Serializing IntPtr is unsafe!");
	}
}

...

// in app start
JsonConvert.DefaultSettings = () => new() { Converters = { new IntPtrConverter() } };

// now try
JsonConvert.SerializeObject(CancellationToken.None); // throws "Serializing IntPtr is unsafe!"
```
