### ISSUE TITLE
Deserialize with PreserveReferencesHandling bugs

### ISSUE THREAD

**Issue by jessetabak** [JamesNK/Newtonsoft.Json#611]
Hi,

I have two problems when Deserializing with preserved references:
1. Deserializing $ref objects only works if the referenced object has the $id property specified first.
2. The object with $id must be bedeclared before it's referenced in an object using a $ref

Some code:
```
public class Person
{
     public string Name { get; set; }
     public Person Parent { get; set; }
}
```

After deserialization 'Parent' will reference Big John
```
[
    {$id:'1', name:'big john'},
    {$id:'2', name:'middle john'},
    {$id:'3', name:'little john', parent: { $ref: '1'}}
]
```

After deserialization 'Parent' will be null
```
[
    {name:'big john', $id:'1'},
    {$id:'2', name:'middle john'},
    {$id:'3', name:'little john', parent: { $ref: '1'}}
]
```

After deserialization 'Parent' will be null
```
[
    {$id:'3', name:'little john', parent: { $ref: '1'}},
    {$id:'1', name:'big john'},
    {$id:'2', name:'middle john'},
]
```

**Comment by JamesNK** [comment]
This is required because Json.NET reads forward through content only once.
