### ISSUE TITLE
JSON Source does not exist after install

### ISSUE THREAD

**Issue by notjust** [JamesNK/Newtonsoft.Json#612]
I have installed the JSON component on two servers and 3 versions of SQL (2008 R2, 2012 and 2014) and in each case the component does not exist in my data flow toolbox. The installation of all three were successful. What is the magic of installing this product?

**Comment by IanYates** [comment]
It sounds like you're talking about a SQL Server Integration Services tool.  JSON.Net is something used from .NET languages (C#, VB.NET, F#, etc).  Unless I'm missing some really cool bit of JSON.Net functionality I think you might have opened this issue in the wrong GitHub open source project.
