### ISSUE TITLE
Cannot serialise an Array with non-zero lower bound using JsonConvert.SerializeObject()

### ISSUE THREAD

**Issue by ianclegg** [JamesNK/Newtonsoft.Json#614]
When I try and serialize an array with a non-zero lower bound using JsonConvert.SerializeObject(<array>);
I get an IndexOutOfRangeException exception.

It looks like JSON.net is assuming the Array object is zero-based. While the assumption appears fair, it is not technically correct - since for .NET supports arrays of any arbitrary lower bound.

Can someone confirm if this is a known issue and would you accept a PR to fix it? From what I can see the fix will be non-breaking. Instead of assuming each rank's lowerbound is 0, it will be correctly determined by inspecting the Array object.

Reproduction:
```    
// lets create a two dimensional array, each rank is 1-based of with a capacity of 10.
var onebasedArray = Array.CreateInstance(typeof(double), new [] { 10, 10 }, new[] { 1,1 });
var randomSource = new Random();
// Iterate of the array elements and assign a random double
for (var i = onebasedArray.GetLowerBound(0); i <= onebasedArray.GetUpperBound(0); i++)
{
    for (var j = onebasedArray.GetLowerBound(1); j <= onebasedArray.GetUpperBound(1); j++)
    {
        onebasedArray.SetValue(randomSource.NextDouble(), new[] { i, j });
    }
}

// Now lets try and serialize the Array
string output = JsonConvert.SerializeObject(onebasedArray);
```

**System.IndexOutOfRangeException
_Index was outside the bounds of the array_.**

**Comment by JamesNK** [comment]
Cool bug. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/d26d54bd50579493c94df2f35c17cde1f3eb2718

**Comment by ianclegg** [comment]
sigh - your fix stole my thunder - I wanted to get into the contributors list for this project. I'm sure I'll get another shot. Joking aside, thanks for the quick turnaround!
