### ISSUE TITLE
JToken.ToObject does not use Converters specified on enum type

### ISSUE THREAD

**Issue by onovotny** [JamesNK/Newtonsoft.Json#616]
Here's the scenario:

Enum with a converter specified and EnumMember:

```
[JsonConverter(typeof(StringEnumConverter))]
public enum FooBar
{
[EnumMember(Value = "SOME_VALUE")]
SomeValue,

[EnumMember(Value = "SOME_OTHER_VALUE")]
SomeOtherValue
}
```
During serialization/deseriazation, this works as expected. I can have a type like so and the values are read and generated correctly:
```
public class MyObject
{
    public FooBar FooBar { get; set;}
}
```

However, if I want to get my value using a JObject, as I do in the case of implementing a custom converter to deal with abstract base classes and new'ing up the right type for deserialization, I need to get my enum value first.

So I do `var jo = JObject.Load(reader)` and then I want to do `var f = jo["FooBar"].ToObject<FooBar>()`. That does not work though. The code in ToObject does an Enum.Parse() and that fails as the value is `SOME_VALUE`. The declared JsonConverter does know how to handle it though, as does `EnumUtils.ParseEnumName`

Can ToObject be "fixed" to check for and use any JsonConverter that might be specified on the type? Also, not sure if there are other places that do this as well, but I'd expect consistent behavior anyplace I ask for a type.

Thanks

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/2c7a51c50a2dfe4ca37871ac27488abdbc924669
