### ISSUE TITLE
Handling invalid Json

### ISSUE THREAD

**Issue by madhugilla** [JamesNK/Newtonsoft.Json#622]
Hi,

We have a json that is invalid for ex :{" description": [{"Apple"}]}, is there a way in the JsonConverter or any extension point where we can get hold of the raw json and apply some regular expressions or pattern matching to construct an object ??

Thanks -Madhu

**Comment by IanYates** [comment]
It may be easier to do outside of JSON.Net if the search & replace you're doing is to fix the `[{"` and `"}]`.  Are you trying to fix something you've loaded from a DB, coming via WebAPI, MVC, or something else?

Having said that, if there's a clever extensibility point in JSON.Net I'd be keen to see it anyway :)

**Comment by JamesNK** [comment]
No.
