### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.IConvertible'

### ISSUE THREAD

**Issue by ajajij** [JamesNK/Newtonsoft.Json#624]
After upgrading to 7.0.1 from 6.0.8 in .NET Portable project, this error occurs:
```
Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.IConvertible'
```
for example, when:
```
double x = Convert.ToDouble(new Newtonsoft.Json.Linq.JValue(45));
```
I use nuget package manager to add the references. 
Working with: 6.0.8 dll: "Json .NET Portable .NET 4.0", Product version: 6.0.8.18111
Not working with: 7.0.1 dll: "Json .NET Portable", Product version: 7.0.1.18622

Is this not supported anymore?
Should I change something in my code?
Anything else?

**Comment by JamesNK** [comment]
"Json .NET Portable .NET 4.0" and "Json .NET Portable" are different builds. Use 7.0.1 of "Json .NET Portable .NET 4.0" if you want to that to continue to work.

**Comment by ajajij** [comment]
Thanks, I manually edited project files to point to `portable-net40+sl5+wp80+win8+wpa81` instead of `portable-net45+wp80+win8+wpa81+dnxcore50` which was set up automatically.
For now it started to work again, but unclear what future will bring.
