### ISSUE TITLE
Serialization error on interfaces with hidden members in v 7.0.1.

### ISSUE THREAD

**Issue by dsavin-software** [JamesNK/Newtonsoft.Json#625]
Serialization error on classes implementing the interfaces with hidden members. Similar issue was reported and fixed in earlier versions. Worked in v.6.0.8., apparently the regression in v.7.0.1.
The error message: “A member with the name '[Property Name]' already exists on '[Interface Name]'. Use the JsonPropertyAttribute to specify another name.”
Note that the class in question serializes OK by itself. The error is thrown when such class is a member (or collection member) of another class being serialized.
The example uses JsonConvert.SerializeObject(), the same error occurs for SerializeObject() of JsonSerializer.   

Consider the following code: 

public interface ISubclassBase
{
  int ID { get; set; }
  string Name { get; set; }
  **bool P1 { get; }**
}
public interface ISubclass : ISubclassBase
{
  **new bool P1 { get; set; }** 
  int P2 { get; set; } 
}
public interface IMainClass
{
  int ID { get; set; }
  string Name { get; set; }
  ISubclass Subclass { get; set; }
}

public class Subclass : ISubclass
{
  public int ID { get; set; }
  public string Name { get; set; }
  **public bool P1 { get; set; }**
  public int P2 { get; set; }
}
public class MainClass : IMainClass
{
  public int ID { get; set; }
  public string Name { get; set; }
  **public ISubclass Subclass { get; set; }**
}

public class MyFactory
{
  public static ISubclass InstantiateSubclass()
  {
     return new Subclass
     {
       ID = 123,
       Name = "ABC",
       P1 = true,
       P2 = 44
     };
  }
  public static IMainClass InstantiateManiClass()
  {
     return new MainClass
     {
       ID = 567,
       Name = "XYZ",
       Subclass = InstantiateSubclass()
     };
  }
}

public void Test()
{
  var mySubclass = MyFactory.InstantiateSubclass();
  var myMainClass = MyFactory.InstantiateManiClass();

  //Class implementing interface with hidden members - flat object. 
  //Passes both in 6.0.8 and 7.0.1
  var strJsonSubclass = JsonConvert.SerializeObject(mySubclass);

  //Class implementing interface with hidden members - member of another class. 
  //Passes in 6.0.8, fails 7.0.1
  **var strJsonMainClass = JsonConvert.SerializeObject(myMainClass);**
}

**Comment by goleafs** [comment]
We have observed this same issue.  Worked fine in 6.0.8 but after updating this is failing.

It looks like this was an issue in the past as well...
http://stackoverflow.com/questions/9304096/trying-to-hide-base-class-member-during-serialization-with-json-net#comment11736578_9304096

**Comment by SlippySken** [comment]
Same problem here :(

**Comment by JamesNK** [comment]
Fixed. This will be in the next release. Until then stick with 6.0.8.

**Comment by warappa** [comment]
I also being struck by this :/
Any news on when the next release is rolled out (since this bug is really bad and it's been about 4 months since the last release)?

EDIT:
Just found a workaround (in my case):
``[JsonIgnore]``, but not in a class but in an *interface*(!), where a property from a base-interface gets hidden.

**Comment by JamesNK** [comment]
It's available in pre-release now: https://www.nuget.org/packages/Newtonsoft.Json/8.0.1-beta1
