### ISSUE TITLE
TypeDescriptor supporting string values misinterpreted as mandatory string deserialization

### ISSUE THREAD

**Issue by genstein** [JamesNK/Newtonsoft.Json#627]
I've some business objects serialized by Json.NET into JSON objects successfully using JsonConvert.SerializeObject(). They're simple POCOs with only numeric data members.  They bear DataContract and DataMember attributes appropriately as I'm trying to avoid serialization platform specifics leaking into the data model.

For other reasons (to support a PropertyGrid) I've since added a TypeConverter to facilitate string conversion, via the TypeConverter attribute on the relevant class. Sadly now Json.NET is disinclined to deserialize any previously serialized object-format data:

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Foo' because the type requires a JSON string value to deserialize correctly.

This feels more untrue than true - unless I'm being dumb, no code has stated that the type must be a string value to deserialize correctly. It feels more like the code has stated that given a string value, Json.NET may rely on the TypeConverter for deserialization from a string.

Adding breakpoints, Json.NET is calling the TypeConverter, discovering that it supports strings, and deciding that it doesn't wish to deserialized the data any other way. But the presence of a TypeConverter supporting conversion to and from some type T isn't a mandate to avoid all other means of conversion?

Json.NET doesn't after all have a string to convert, and hasn't asked the TypeConverter what else it may support (for instance, whatever type Json.NET does have in hand...); besides which, Json.NET supports deserialization from an object without recourse to the TypeConverter, so I don't follow why it's asking in this case?

The exception message goes on:

> To fix this error either change the JSON to a JSON string value or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type *to force it to deserialize from a JSON object*.

This also feels marginally untrue - in fact, if I do add (and I'd like to avoid this) JsonObjectAttribute, the object will then freely deserialize from strings *and* objects. So this isn't so much forcing the type to deserialize from an object and only an object, as it is permitting it to deserialize from strings and objects. But this doesn't feel like it makes a huge amount of sense, since JsonObjectAttribute isn't needed to permit object-based deserialization in the first place...

Whether in the exception message or implementation, it feels like there may be an issue here? My instinct would be that the implementation should try its best to deserialize data in whatever form it has them, so a TypeConverter supporting strings doesn't feel like it should prevent deserialization from an object, even without a JsonObjectAttribute. Failing that, the exception message could be clarified, perhaps something like:

> Electing not to deserialize the current JSON object (e.g. {"name":"value"}) into type 'Foo' because the type permits conversion to string value. The presence of any string type conversion facility (for instance, a TypeConverter) is interpreted as mandating string serialization. ... JsonObjectAttribute can also be added to the type to permit deserialization from a JSON object as well as a string.

**Comment by JamesNK** [comment]
Serializers are built around conventions. The Json.NET convention is a type with a TypeConverter that can be converted to a string should be a string. As long as that can be overriden with JsonObjectAttribute then I'm happy with how it works.

**Comment by KamilSzot** [comment]
I just hit the same issue. I was trying to write TypeConverter that converts string to my POCO with the use of JsonConvert.DeserializeObject<>()
