### ISSUE TITLE
IJsonLineInfo returns incorrect LinePosition

### ISSUE THREAD

**Issue by yufeih** [JamesNK/Newtonsoft.Json#628]
With the following code to dump json line info:

```csharp

while (reader.Read())
{
    System.Console.WriteLine($"{reader.TokenType} {reader.LineNumber} {reader.LinePosition}");
}
```

`{"a":"bc"}` outputs:

StartObject 1 **1**
PropertyName 1 **5**
String 1 **9**
EndObject 1 **10**

`\n{"a":"bc"}` outputs:

StartObject 2 **2**
PropertyName 2 **6**
String 2 **10**
EndObject 2 **11**

This is incorrect, a new line shifts the line position by one to the right.

**Comment by JamesNK** [comment]
It's definitely incorrect. I'm surprised no one has noticed it before.

I'm not sure whether this is a bug that should wait for a major version change before fixing though.

**Comment by yufeih** [comment]
I am leaning towards a minor version change, because if someone did take a  **serious** dependency on this bad behavior, they are very likely to be aware of the issue when developing.

**Comment by JamesNK** [comment]
I think very few people will directly use them, but they are included in exception detail, e.g.

    Input string '3.3' is not a valid integer. Path '[1]', line 3, position 6.

**Comment by yufeih** [comment]
Yes, in that case it is ok to have the fix as a minor upgrade.

I am writing a tool to manipulate json files. It needs to preserve the formatting of the source file, including tabs, spaces and newlines. I use line info to track the exact shape of the source, so getting the correct line info is important to me. Luckily, this bug only occurs at the first new line, so I can workaround it.

Last time I check it was probably due to `_lineStartPos` not initialized to -1. 
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonTextReader.cs#L62

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/172c1d8f30913eae0431ca2eebb5eaf3b154243d
