### ISSUE TITLE
Deserializer does not respect property types

### ISSUE THREAD

**Issue by fsateler** [JamesNK/Newtonsoft.Json#630]
The following program (in linqpad) yields incorrect results:

	void Main()
	{
		var obj1 = new MyType {
			Name = "A",
			Children = new [] {
				new MyType {
					Name = "B",
				},
			},
		};
		
		var json = JsonConvert.SerializeObject(obj1);
		
		var result = JsonConvert.DeserializeObject<MyType>(json);
		
		result.Dump();
	}
	
	// Define other methods and classes here
	class MyType {
		public string Name { get; set; }
		
		private List<MyType> underlying = new List<MyType>();
		public IEnumerable<MyType> Children { get { return underlying.ToList(); } set { underlying = new List<MyType>(value); } }
	}

Results:

    Name      A 
    Children  (0 items) 
 
This appears to happen because json.net introspected the resulting object type, and then decided to add items to the returned list instead of setting the reference to a new list.

If the deserializer realized the return type is IEnumerable, it should not try to guess if the actual object is something else. That should be an implementation detail.

**Comment by luiscaiano** [comment]
hi, i also having this issue, have not found a work around. 

the strange thing is that you have all that trouble of defining a ContractResolver, and it gets totaly ignored. i have been tinkering with the source code, i was thinking of submitting a pull with a JsonSerializerSettings property UseInstanceContract [true/false] 
any guide lines for this ?

**Comment by tchekjunior** [comment]
hi, I have the same problem with my code after deserialization, can anyone help me or tell me how modify the code source. please

**Comment by JamesNK** [comment]
ObjectCreationHandling.Replace
