### ISSUE TITLE
CamelCasePropertyNamesContractResolver returns a wrong property name

### ISSUE THREAD

**Issue by SitoCH** [JamesNK/Newtonsoft.Json#631]
Hi,
I found a strange issue when using the CamelCasePropertyNamesContractResolver on a property named "ID" (all upper case).
With an older version (4.X) the returned JSON was something like:
```javascript
 { iD: 1234 }
```
With the latest version instead we receive:
```javascript
 { id: 1234 }
```
The "D" is now lowercase and breaks our API, is it an error? Reading through the code in CamelCasePropertyNamesContractResolver.cs there's a comment the seems to confirm my impression that this is an error:
```csharp
// lower case the first letter of the passed in name
return StringUtils.ToCamelCase(propertyName);
```

**Comment by JamesNK** [comment]
The comment is an error.

**Comment by gperhat** [comment]
hi @SitoCH , i have the same issue.
Did you manage to resolve it somehow?

**Comment by SitoCH** [comment]
Unfortunately not, I use Newtonsoft.Json with TypeLite and I configured it so it generates a definition file that matches this behaviour.
