### ISSUE TITLE
Add setter for JProperty name property

### ISSUE THREAD

**Issue by IlyaGrebnov** [JamesNK/Newtonsoft.Json#633]
Currently there is no way to change JProperty name after creation, but looking into source code I do not see any technical limitation. In our case we would like to modify name if JProperty (we have little DSL language build on top of JSON and we are using Json.net to work with it). 

Will it be possible to add setter Property name property?

James, please let me know if you ok with it? I will submit PR including unit tests.

**Comment by JamesNK** [comment]
I'd rather it was read-only. The property name is cached in a dictionary on a JObject for lookup performance for example and I'd have to raise an event to notify the JObject. Easy enough to remove and readd a new JProperty with the new name.

**Comment by IlyaGrebnov** [comment]
I tried to Remove and Add, but it is not working as I expecting. Here is example to illustrate problem. 

    var json = @"{
        ""prop1"": {
            ""foo"": ""bar""
        },
    }";

    var obj = JsonConvert.DeserializeObject<JObject>(json);

    var property = obj.Property("prop1");
    var value = property.Value;

    property.Remove();
    obj.Add(new JProperty("prop2", value));

    Debug.Assert(((JProperty)value.Parent).Name == "prop2", "Problem!");

**Comment by JamesNK** [comment]
You get that result because a value will be copied if it already has a parent.

```
var json = @"{
    ""prop1"": {
        ""foo"": ""bar""
    },
}";

var obj = JsonConvert.DeserializeObject<JObject>(json);

var property = obj.Property("prop1");
var value = property.Value;

// remove value so it has no parent
property.Value = null;

property.Remove();
obj.Add(new JProperty("prop2", value));

Assert.True(((JProperty)value.Parent).Name == "prop2", "Problem!");
```
