### ISSUE TITLE
Generic Serialize Methods

### ISSUE THREAD

**Issue by Tydude4Christ** [JamesNK/Newtonsoft.Json#634]
In cases where serializing an abstract class or interface one must remember to pass in the type in order for the root to have the type name serialized when the user uses TypeNameHandling.Auto.

If generic serialize methods were added to Json.NET, those methods could implicitly pass in the type using a typeof expression and users would not have to remember to pass in the type.

I understand this would be a breaking change upon recompilation to the library as most calls to serialize will now call the generic methods instead.

What are your thoughts on this?

**Comment by JamesNK** [comment]
I've decided I don't want to do this.

**Comment by Tydude4Christ** [comment]
Thanks for considering it.
