### ISSUE TITLE
Serialization of F# type doesn't honor the JsonProperty attribute

### ISSUE THREAD

**Issue by ridderholt** [JamesNK/Newtonsoft.Json#635]
I'm trying to serialize a type in F# to JSON and I have decorated my properties with the JsonProperty attribute and set the PropertyName property to get a different name when serialized.

```f#
type Customer = {
    [<JsonProperty(PropertyName = "customer_no")>]
    CustomerNumber : int
}
```

But when I'm trying to serialize the object using JsonConvert.SerializeObject the property is still named "CustomerNumber".

```f#
let json = Json.JsonConvert.SerializeObject({CustomerNumber = 123})
```

```json
{ "CustomerNumber": 123 }
```

I'm using F# 4.0 with Newtonsoft.Json version 7.0.1. When using reflection to check for attributes on the object I can see that the JsonProperty attribute is present with the correct value.

**Comment by JamesNK** [comment]
I get

    { "customer_no": 123 }
