### ISSUE TITLE
Stop creating unnecessary app.config files

### ISSUE THREAD

**Issue by sallgeud** [JamesNK/Newtonsoft.Json#636]
Two issues: 

1) You should not create app.config files for libraries as they are useless and cause issues
2) If an app.config file is not an actual file but a link to a shared file, DO NOT FAIL install... instead, update the shared file

**Comment by JamesNK** [comment]
I don't. That's VS or NuGet.

**Comment by mayerwin** [comment]
I still don't understand why Newtonsoft.Json is the only nuget library I am using which creates this file and the bindings. Is there really no way to prevent it?
See also this StackOverflow question: https://stackoverflow.com/questions/22227675/why-nuget-adds-app-config-with-assemblybinding-to-library-projects-during-a-nuge

**Comment by chucklu** [comment]
https://github.com/NuGet/Home/issues/9706
