### ISSUE TITLE
SelectToken documentation doesn't show how to work with selectors that contain whitespace and special characters

### ISSUE THREAD

**Issue by DanielLangdon** [JamesNK/Newtonsoft.Json#641]
In the documentation at http://www.newtonsoft.com/json/help/html/SelectToken.htm, there is a description of how to use the SelectToken function to select a value from JSON using a single string.  This is very useful.  However, I had to do some digging to figure out how to make SelectToken work when the selector contains whitespace and special characters.

I think that this documentation should explain the syntax and give an example.

**Comment by DanielLangdon** [comment]
I think that the following example would suffice to illustrate how to do this:

JObject o = JObject.Parse(@"{
    'Space Invaders': 'Taito',
    'Doom ]|[': 'Id',
    ""Yar's Revenge"": 'Atari',
    'Government ""Intelligence""': 'Make-Believe'
}");

string SpaceInvaders = (string)o.SelectToken("['Space Invaders']");
// Taito

string Doom3 = (string)o.SelectToken("['Doom ]|[']");
// Id

string YarsRevenge = (string)o.SelectToken("['Yar\\'s Revenge']");
// Atari

string GovernmentIntelligence = (string)o.SelectToken("['Government \"Intelligence\"']");
// Make-Believe

**Comment by DanielLangdon** [comment]
And also, I am told that around version 6.0.0 or so, the way special characters are handled has changed, and I think it's best that we document this, as well.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/6d91522d6bb08e282345789d25c51cd24288c257
