### ISSUE TITLE
Merging JObjects with Arrays

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json#642]
Hi

I have two jobject  that looks something like this.
    {

```
    "cars" :[
        {
            "reg" :1234,
            "make" :"",
            "model" :""
        },

        {
            "reg" :1235,
            "make" :"",
            "model" :""
        },

        {
            "reg" :1236,
            "make" :"",
            "model" :""
        }

    ]

}   
```

Arrays where index 0 in one refers to index 0 in the other  also where object/value in the array is not related is fine and works well . The problem comes when a field or something in the object determines the identifier of the object (like reg field in example).

Is it possible to add a something to merge so that i can right code myself to decide how the arrays gets merged(overload/delegate/callback).

thanks

**Comment by JamesNK** [comment]
Thanks for the suggestion but I think complexity like this is beyond the scope of the JSON merging in Json.NET. I suggest you merge the JSON manually.
