### ISSUE TITLE
SelectToken expression convertions not same as json parse

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json#643]
hi

I have this json

    "office": {
        "parkingRatio": 12.0,
        "hasGenerators": true,
        "generators": [
          {
            "_id": "ff2dc672-6e15-4aa2-afb0-18f4f69596ad",
            "office_id": "b62ce2c1-5fa2-4eee-9ce8-e04a2c3e6513",
            "make": "Broom Broom",
            "covered": true,
            "output": 1234.0
          }
        ]
    }

And this query

    $.office.generators[?(@._id =='ff2dc672-6e15-4aa2-afb0-18f4f69596ad')]

The jObject.parse convert the _id field of generators into a JValue of GUID but the expression get converted into JValue of String so when "BooleanQueryExpression" tries to compare them they are not equal.

thanks

**Comment by JamesNK** [comment]
Can you add a repo. This worked for me:

```
JObject o = JObject.Parse(@"{
  ""office"": {
    ""parkingRatio"": 12.0,
    ""hasGenerators"": true,
    ""generators"": [
      {
        ""_id"": ""ff2dc672-6e15-4aa2-afb0-18f4f69596ad"",
        ""office_id"": ""b62ce2c1-5fa2-4eee-9ce8-e04a2c3e6513"",
        ""make"": ""Broom Broom"",
        ""covered"": true,
        ""output"": 1234.0
      }
    ]
  }
}");

JObject g = (JObject)o.SelectToken("$.office.generators[?(@._id =='ff2dc672-6e15-4aa2-afb0-18f4f69596ad')]");

Assert.IsNotNull(g);
```

**Comment by fbarnard** [comment]
Hi

If you use the parse function the jvalue type is string. If you  do a
select token on that it works.

If u take object where the type is guid use the jobject.fromobject then the
jvalue type is guid  as you would  expect.


But then the expression does not work because  the expression jvalue  is
string and the field  jvalue is type guid.


So I think the conversion is as you  would  expect but the select token
should be a little more lenient with the comparison and except  a string to
be able to be compared against a guid seeing  that Json/jsonpath does not
have a concept if a guid.

Thanks

On Thursday, 3 September 2015, James Newton-King <notifications@github.com>
wrote:

> Can you add a repo. This worked for me:
>
> JObject o = JObject.Parse(@"{
>   ""office"": {
>     ""parkingRatio"": 12.0,
>     ""hasGenerators"": true,
>     ""generators"": [
>       {
>         ""_id"": ""ff2dc672-6e15-4aa2-afb0-18f4f69596ad"",
>         ""office_id"": ""b62ce2c1-5fa2-4eee-9ce8-e04a2c3e6513"",
>         ""make"": ""Broom Broom"",
>         ""covered"": true,
>         ""output"": 1234.0
>       }
>     ]
>   }
> }");
>
> JObject g = (JObject)o.SelectToken("$.office.generators[?(@._id =='ff2dc672-6e15-4aa2-afb0-18f4f69596ad')]");
>
> Assert.IsNotNull(g);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JamesNK/Newtonsoft.Json/issues/643#issuecomment-137572791>
> .
>


-- 
Francois D. Barnard
083 380 6645

**Comment by JamesNK** [comment]
Fixed

**Comment by fbarnard** [comment]
Hi

thanks...
