### ISSUE TITLE
Unable to serialize/deserialize SqlParameter (it has ExpandableObjectConverter)

### ISSUE THREAD

**Issue by malekpour** [JamesNK/Newtonsoft.Json#644]
JsonConvert is unable to serialize or desalinize System.Data.SqlClient.SqlParameter.

Serialize returns string value of SqlParameter.ParameterName only.

Desalinize throws JsonSerializationException:
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 
'System.Data.SqlClient.SqlParameter' because the type requires a JSON str...

**Comment by JamesNK** [comment]
You will have to write a JsonConverter to serialize SqlParameter, the ExpandableObjectConverter doesn't do a good job.
