### ISSUE TITLE
Async methods for JsonTextReader / JsonTextWriter

### ISSUE THREAD

**Issue by gretro** [JamesNK/Newtonsoft.Json#650]
Hello.

I wanted to know if there were any plans for Json.Net to provide async methods on the text reader and the text writer. Since those classes deal with streams, it could be good addition. I wanted to know if you would be doing it eventually soon, or if there were no plans.

I know you already made an attempt at creating those methods, but I wanted to know if you would try again without the Task.Run.

Thanks.

**Comment by JamesNK** [comment]
No plans right now. It was be a significant amount of work and I'm not confident I have the knowledge to write perfect async code currently.

**Comment by JonHanna** [comment]
https://github.com/JonHanna/Newtonsoft.Json/commit/0ec73f19773f6eaa4a810f5609f4c844ef7059bc is a quick start on this, pushing async through to the stream, and returning synchronously when that's not available (c.f. how `StringReader` and `StringWriter` return synchronously on their `*Async` methods) and mostly not trying to be too clever (refactoring can happen later).

I'd be happy to continue with this if it's desired.

**Comment by JamesNK** [comment]
Thanks for looking at this. I've been putting it off.

Wow that is a lot of copy and paste. I know most it can't be helped due to the nature of async. Looking at that, I'm worried about how doing a lot of things twice and testing them twice will effect maintainability. Also so much duplicate code, and all the async state machines are going to grow the DLL hugely.

**Comment by JonHanna** [comment]
That would be a primary focus of looking at this deeper. It's relatively easy to produce such a copy-paste implementation as this. The real work comes in with finding shared code and/or deciding to be synchronous with I/O

**Comment by JonHanna** [comment]
In a way though, this assembly is iin the perfect storm position. Most are either very close to the I/O (just add a couple of async overloads) or ultimate consumers (async or not; pick one), but this assembly is nastily between the two. 4

**Comment by AArnott** [comment]
+1 to async `JsonTextReader` (and possibly `JsonTextWriter`, although that's not impeding our progress so much). 
There are patterns that can be followed to avoid repetition of code to keep the test matrix small. I can explain and perhaps demonstrate those patterns if there's enough interest to respond with the update.

**Comment by JonHanna** [comment]
Well, it may have been a year between my saying I'd tackle it and my submitting a PR, but PTAL.

**Comment by erezvani1529** [comment]
Hi @JonHanna,

Would you please share a time-line (if it exists) as to when this change will be generally available on nuget as a stable package?

Thanks,
Elham

**Comment by AArnott** [comment]
BTW, consider using `ValueTask<T>` to avoid the cost of allocating Tasks for the async methods in the (hopefully frequent) case of not needing to refill the read buffer.

**Comment by JonHanna** [comment]
I'm afraid that if I'd posted a timeline for my part in this, it would now be lies.

What are other people's thoughts on ValueTask here? I'm personally torn between the advantages on one hand and the dependency addition, though as ValueTask becomes better known that is less of a big deal (if many consumers would depend on it anyway) and the stream consumption pattern of json would seem to be a good match. 

We would be breaking anyone currently using the async in the repository, which is an obvious downside.

**Comment by JamesNK** [comment]
> Would you please share a time-line (if it exists) as to when this change will be generally available on nuget as a stable package?

Probably in a week or two.

> BTW, consider using ValueTask<T> to avoid the cost of allocating Tasks for the async methods in the (hopefully frequent) case of not needing to refill the read buffer.

Should `ValueTask<T>` be exposed on public APIs? I was under the impression that it should be used internally. Right now calls to `JsonReader.Read()` will returned a cached `Task<bool>` most of the time. `JsonReader.ReadAsInt32()` and friends would be the calls that allocate a task.

**Comment by TylerBrinkley** [comment]
I think for the public contracts it should use `Task` but internally where available use `ValueTask`. For .NET Standard and .NET Framework 4.6.2+ use `ValueTask` and create an internal version of `ValueTask` for prior frameworks.

**Comment by JamesNK** [comment]
If ValueTask is only for internal usage then I don't see any benefit. Both the reader and the writer basically bubble up the task from TextReader/TextWriter. There was one place where Tasks were being allocated internally and it was refactored to no longer be an issue.

**Comment by TylerBrinkley** [comment]
Are those reader methods being used internally? If so then creating internal versions of those methods that return a ValueTask may be advantageous to avoid Task allocations.

**Comment by JamesNK** [comment]
They are but they're also virtual.

**Comment by JonHanna** [comment]
Yeah, we've done a lot to avoid a lot of the overhead of tasks when possible, so ValueTask might not win much, and could even add overhead in some cases. I wouldn't discourage anyone who wanted to experiment and see if it gained much, but it's not an obvious win a priori.

**Comment by AArnott** [comment]
`ValueTask<T>` is intended for public API use. Stephen Toub who was behind its creation said .NET would have returned them from `Stream` async methods had it been around at the time.
But if your methods return `Task<bool>` and you can return a cached task, then that's fine. `ValueTask<int>` is where it is really useful since the result value can vary.

**Comment by TylerBrinkley** [comment]
@AArnott, that makes sense but I doubt @JamesNK wants to add a dependency on `System.Threading.Tasks.Extensions` for the full .NET Framework when otherwise it doesn't have any external dependencies.
