### ISSUE TITLE
ImmutableArray light-up support missing from several builds

### ISSUE THREAD

**Issue by sharwell** [JamesNK/Newtonsoft.Json#652]
Currently [**ImmutableCollectionsUtils.cs**](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ImmutableCollectionsUtils.cs) is excluded from several builds (e.g. .NET 2.0, 3.5, 4.0, and 4.0 PCL). This is causing two problems:
1. When two extensions to the same application bundle JSON.net, where one of them bundles the 4.0 PCL build and the other uses an immutable, the application could load an assembly which is incapable of providing the functionality required by the .NET 4.5 extension. This appeared in the wild in DotNetAnalyzers/StyleCopAnalyzers#1359.
2. The Immutable Collections library is available going back _at least_ to .NET 3.5 using an identical API via the [Rackspace.Collections.Immutable](https://www.nuget.org/packages/Rackspace.Collections.Immutable/) package on NuGet.

If **ImmutableCollectionsUtils.cs** does not itself depend on functionality only available in .NET 4.5+, it should be included in other target builds as well to ensure proper light-up functionality for clients.

**Comment by JamesNK** [comment]
I'll include it with the .NET 4.0 PCL since it is likely it could be used with up level frameworks. Also I see it is the one you are using. Unfortunately since my tests for the .NET 4.0 PCL are .NET 4.0 I won't be able to give it test coverage. Hopefully the same code in .NET 4.0 doesn't cause any issues.

I think it is unlikely applications are using json.net 2.0, 3.5, 4.0 and are also using immutable types so I won't change them.

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/commit/239cde86f0f458863f76f063a09eb7fc0d64ecfa

**Comment by sharwell** [comment]
> I think it is unlikely applications are using json.net 2.0, 3.5, 4.0 and are also using immutable types so I won't change them.

We are. I originally found and filed this bug due to a report in a .NET 3.5 application.

**Comment by sharwell** [comment]
@JamesNK This issue is showing up as the cause of crashes in Visual Studio. In the event any application places the .NET 4.0 assembly in the GAC, all assemblies using that version of Json.NET will start to fail if they try to deserialize immutable collections. I believe this issue should be reopened, as it is currently impossible to reliably deserialize immutable collection types regardless of the build of Json.NET being used.

If you are interested, I would be willing to implement a light-up based fallback which is slower but at least functional to handle cases where applications load an "early" target of Json.NET and subsequently try to deserialize one of these collections.

**Comment by JamesNK** [comment]
Ok, I've made immutable support universal to all assemblies https://github.com/JamesNK/Newtonsoft.Json/commit/72b98ae7b2613ef55e786571024a51f6d22843e6

**Comment by sharwell** [comment]
🙌
