### ISSUE TITLE
Error converting float value to integer in Web API

### ISSUE THREAD

**Issue by pareshnawale** [JamesNK/Newtonsoft.Json#654]
Hi,

I am using Newtonsoft.Json NuGet package version 6.0.8. When I pass float value for the integer property of the model, model binding fails.

Here is the controller method , model and sample input 

Controller: 
```
 // POST api/values
        public string Post(MyModel model)
        {
               //some code here
        }
```
Model:
```
public class MyModel
    {
        public string ThisIsString { get; set; }
        public int ThisIsInt { get; set; }
        public decimal ThisIsDecimal { get; set; }
    }
```
Sample input:
```
{
    "ThisIsString": "string",
    "ThisIsInt": 2.20,  <-- Property is set to float number
    "ThisIsDecimal": 0
  }
```
When I tried above sample input, instead of receiving 0 for "ThisIsInt" property entire model received in controller method is null.

if I try same code using 6.0.3 version then I receive model with "ThisIsInt" set to 0 as expected.

Could you please help me resolve this issue? I have already tried upgrading  to latest version of NuGet package.

Thanks,
Paresh

**Comment by JamesNK** [comment]
Later versions of Json.NET throw an error when deserializing a floating point value onto an integer property.

**Comment by pareshnawale** [comment]
@JamesNK  Thanks for your reply. 
Is this by design or it is a bug? Is there any way to allow floating point value conversation into integer?

Thanks,
Paresh

**Comment by JamesNK** [comment]
By design.
