### ISSUE TITLE
7.0.2-beta1 with Profile 259 on Xamarin.Android: TypeConverter and System.Diagnostics.Tools not found

### ISSUE THREAD

**Issue by sunsided** [JamesNK/Newtonsoft.Json#659]
Because we're porting our Libraries to `dnx`/`dnu` projects I had to resort to using the `7.0.2-beta1` version as `7.0.1` couldn't be installed in Profile 259 (`".NETPortable,Version=v4.5,Profile=Profile259"`) targets.

The nasty thing is that the build process works (`dnu restore`, `dnu pack`), however when the library is added to Xamarin.Android projects two things happen:

NuGet selects the `dotnet` target (instead of the portable one) and fails because `System.ComponentModel.TypeConverter` can't be found in the PCL. I had to remove the `dotnet` target completely for this to work. (Granted, manually removing the reference and pointing it to the portable one helps as well.) 

However ...
The `Profile259` target can't be used as well because `System.Diagnostics.Tools` can't be found. I fixed this by patching out `System.Diagnostics.Tools` and the fencing the `[System.Diagnostics.CodeAnalysis.SuppressMessage(...)]` attribute in `DefaultContractResolver.cs` with `#if !NET20 && !PORTABLE`.

Both steps together made the library available and working out of the box (being our internal NuGet feed).

**Comment by JamesNK** [comment]
`dotnet` is still work in progress. I'm waiting for the nuget guys to document how it should be used.

I have changed the SuppressMessage to be only be included in the .NET 3.5 build.
