### ISSUE TITLE
NullReferenceException thrown when trying to convert serialized Object->Json->XML

### ISSUE THREAD

**Issue by yinon1992** [JamesNK/Newtonsoft.Json#660]
As you can see in the code sample below, I tried to create xml file from Json text, where the Json was produced by serializing a List of integers.
 
```
namespace ConsoleApplication40
{
    class Program
    {
        static void Main(string[] args)
        {
            var listOfIntegers = new List<int>{1,2,3,4,5};
            var ser = new JsonSerializer
            {
                
                PreserveReferencesHandling = PreserveReferencesHandling.All,  // Must have so that it will be serialized as an object
                TypeNameHandling = TypeNameHandling.Auto
            };
            var stringWriter = new StringWriter();
            var jsonTextWriter = new JsonTextWriter(stringWriter);
            ser.Serialize(jsonTextWriter, listOfIntegers);
            jsonTextWriter.Flush();
            jsonTextWriter.Close();

	    // Now try to convert the resulting JSON to XML
            string json = stringWriter.GetStringBuilder().ToString();          
            var output = JsonConvert.DeserializeXmlNode(json, "bla");
          }
    }
}
````

The serialization to Json succeded as expected (the Json text returned is {"$id":"1","$values":[1,2,3,4,5]}. ), but the conversion to xml has failed due to a NullReferenceException. I did some research and found that the reason is because the "$values" attribute that Json.NET adds when serializing a List to Json.

I think that there is an implicit assumption that after every expression that starts with '$' in the json text must come a scalar value and not List thus the JsonConvert.DeserializeXmlNode
fails.

What should i do ?

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/eccdf4bf954e6f96783f429fd293a96f5a9ae97b
