### ISSUE TITLE
Empty array serialization with json:Array='true'

### ISSUE THREAD

**Issue by caglarcem** [JamesNK/Newtonsoft.Json#661]
The following code (please note empty array):

```csharp
string xml = @"<person xmlns:json='http://james.newtonking.com/projects/json' id='1'>
              <role json:Array='true' />
            </person>";
var doc = new XmlDocument();
doc.LoadXml(xml);

var json = JsonConvert.SerializeXmlNode(doc);
```

returns this json (please note role 'array', it has an empty object [{}] in it):

```csharp
Assert.AreEqual(@"{""person"":{""@id"":""1"",""role"":[{}]}}", json);
```
However, we need this instead (we don't want empty object [] in the array) -and implemented a fix with unit tests passing-:
```csharp
Assert.AreEqual(@"{""person"":{""@id"":""1"",""role"":[]}}", json);
```

Is there a  way to achieve this in the current implementation? 

Not quite sure if this is fair to say, but if there is no element in the array, I would expect it to be completely empty. I would like to learn about the justification if this is not a bug :)

**Comment by richardp-au** [comment]
It looks like the XML has an element with no children but the JSON has an array with one child. They don't look equivalent to me.

**Comment by JamesNK** [comment]
The role element that `json:Array='true'` is on is an element in the array.

**Comment by richardp-au** [comment]
Is there a way to get an empty array like `"role": []` in the output?.

**Comment by JamesNK** [comment]
No.

**Comment by caglarcem** [comment]
when the "array" is dynamically generated and it's empty, {} tricks the parser at the other end as though there is an object in it. that just doesn't sound right, I'm a bit surprised how easily you closed the issue.

**Comment by JamesNK** [comment]
It doesn't sound right because it's not designed for empty arrays. The XML to JSON conversion only works under the strict set of guidelines listed in the documentation.

**Comment by sayedeltokhy** [comment]
role= new List<object>().ToArray()

**Comment by carcudi** [comment]
If you're still looking for an answer, the following tag:
<role xmlns:json="urn:http://james.newtonking.com/projects/json" />
Will produce:
"role" : []

**Comment by carcudi** [comment]
If you're still looking for an answer, the following tag:

`<role xmlns:json="urn:http://james.newtonking.com/projects/json" />`

will produce this json:

`"role" : []`

**Comment by dalepotter** [comment]
@carcudi I'm not able to reproduce the empty array that you mentioned.  Could you confirm the full XML that you are using?

Instead I get `"role":{"@xmlns:json":"urn:http://james.newtonking.com/projects/json"}`

This was produced using...
```
xml = @"<person xmlns:json='http://james.newtonking.com/projects/json' id='1'>
  <name>Alan</name>
  <url>http://www.google.com</url>
  <role xmlns:json='urn:http://james.newtonking.com/projects/json' />
</person>";

doc = new XmlDocument();
doc.LoadXml(xml);

json = JsonConvert.SerializeXmlNode(doc);
Console.WriteLine("JSON conversion from XML: " + json);
```
Full output:
```
JSON conversion from XML: {"person":{"@id":"1","name":"Alan","url":"http://www.google.com","role":{"@xmlns:json":"urn:http://james.newtonking.com/projects/json"}}}
```
