### ISSUE TITLE
Split functionality to several assemblies 

### ISSUE THREAD

**Issue by mogikanin** [JamesNK/Newtonsoft.Json#663]
Did you think about splitting some functionality into separate assemblies, e.g.
Newtonsoft.Json.dll
Newtonsoft.Json.Linq.dll
Newtonsoft.Json.Bson.dll, etc?

Because currently Newtonsoft.Json.dll has a size approx 500 kb, and contains a lot of excess code, which not needed in simple scenarios (just simple serialize\deserialize simple json objects).
It will be a nice to have a basic, lightweight assembly with some core functionality, and several other assemblies for cases when you need something more.

**Comment by JamesNK** [comment]
I think about it now but it's not going to change.
