### ISSUE TITLE
Advice on strong naming

### ISSUE THREAD

**Issue by amirtuval** [JamesNK/Newtonsoft.Json#664]
Hi,

I recently contacted you with [this issue](https://github.com/JamesNK/Newtonsoft.Json/issues/656).

As a result of this issue, I forked the repo, and compiled a version of json.net with my fix.
Since I do not have the signing key, I signed the assembly with a different key.

I now run into problems, because my project uses ASP.NET, which references json.net and expects the old key. I get compilation problems (not runtime errors) - 

The type 'Newtonsoft.Json.JsonSerializerSettings' is defined in an assembly that is not referenced. You must add a reference to assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.	

Note that I did change my web.config to reflect the new key in the assemblyBinding section, however this affects runtime only, and not compilation issues.

I was wondering if this is something you encountered before and have a solution for it, because I did not find anything.

Thanks
Amir

**Comment by JamesNK** [comment]
There is no easy solution. SN is dumb but that's the world we live in.
