### ISSUE TITLE
Json schema v4 to c# files

### ISSUE THREAD

**Issue by sacredMonster** [JamesNK/Newtonsoft.Json#665]
Disclaimer: Don't know if this is the right forum to ask.
I reached this post from https://github.com/cvent/json-schema-2-poco and I was wondering if someone could please guide me to a project that helps me generate c# files from a given json schema (v4). //github.com/cvent/json-schema-2-poco only supports v3 to POCO and I need to generate POCO files for V4. 

Thanks..

**Comment by JamesNK** [comment]
No?

**Comment by sacredMonster** [comment]
Hey James,
Does No? meant that there is no existing application/tool that can help me convert a json v4 schema to c# files?
Thanks
