### ISSUE TITLE
The precision of double serialization

### ISSUE THREAD

**Issue by bargitta** [JamesNK/Newtonsoft.Json#666]
I use this package with Microsoft Web API2. When serialize a C# double (64bit) to json, and convert the json back to javascript double (64bit), I find there will be precision loss. Anything I can configure there?

**Comment by JamesNK** [comment]
The documentation has information about float parsing options.

**Comment by bargitta** [comment]
Do you mean this one?
http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_FloatParseHandling.htm

I did not find others, will you please give more hints?
thanks.

**Comment by challenh** [comment]
Hi, I just come across this issue which is also a problem for me now. that is, always parsing numeric float string into either decimal or double will lead to precision loss. ideally I would expect the JsonTextReader to return decimal/double/long whichever can fit best. for example:

(1) decimal.MaxValue string should be automatically parsed as decimal not double: 

decimal.Parse("79228162514264337593543950335",NumberStyles.Float, NumberFormatInfo.InvariantInfo)  - correct parsing, has all the precision
79228162514264337593543950335

double.Parse("79228162514264337593543950335",NumberStyles.Float, NumberFormatInfo.InvariantInfo)
7.9228162514264338E+28

(2) double.MaxValue string should be automatically parsed as double not decimal:

decimal.Parse("1.7976931348623157E+308",NumberStyles.Float, NumberFormatInfo.InvariantInfo) 
throws 'System.OverflowException'

double.Parse("1.7976931348623157E+308",NumberStyles.Float, NumberFormatInfo.InvariantInfo)    - correct parsing, only double can hold this big number.
1.7976931348623157E+308

so a better approach to me is to do long.TryParse(...), if failed then decimal.TryParse(...), if failed again then double.Parse(...), and the latter two can be selected by a .FloatParseHandling setting.
@JamesNK  can you comment on this? I can start working on a PR as needed.

**Comment by challenh** [comment]
PR: #884

**Comment by JamesNK** [comment]
Sorry I disagree with this. The user is asking for a decimal. Getting a double when the value gets too large is more surprising than getting an error message saying the value is now too large.

I think in cases like this you should just deserialize to a string and then process it using your own rules. I'll re-purpose your test to make sure that this possible.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/81098652b37266bf7ed29d8c1e86c270ae18b79d

**Comment by challenh** [comment]
@JamesNK  thank you. In some other scenarios where user is unable to predict the numeric value & call ReadAsString(), I think the important thing is to read the accurate value out (no matter as decimal or as double, and with as much precision as possible) , then let user do further processing. so do you think this feature request is valid? 

Based on that, I have reverted the previous change, then add Json.FloatParseHandling.Auto for trying decimal precision first and fallback to double if needed. it is the same PR: #884

**Comment by challenh** [comment]
@JamesNK  the scenario I am seeking to solve is reading arbitrary JSON with as high precision as possible by calling Read() not ReadAsString()  (I can explain more about this feature request if needed), the below are 2 examples, looking forward to support of this.  so can you evaluate this PR?  #884   / 8d14715b13b7c57e30daf82342942c9089c1e461  .
"{\"amountValue\": 1.7976931348623157E+308}"   (result value has to be double)
or 
"{\"amountValue\": 792281625142643375935439503.35}"     (result value has to be decimal)

**Comment by Kein** [comment]
So, I have annoying old good issue with json and floats. I need to deserialize raw binary data, then serialize into JSON for editing then serialize into binary again. Obviously, I lose on floats. Value 0xF9FF4FC1 (big endian, roughly -12.9999933) gets rounded to 0xF6FF4FC1 ("-12.99999"). I know it is not a big loss and I know floats are little shits but I want to keep the precision as close as possible due to possibly incompatibility issues later. Anyone tackled this problem before with JSON?

**Yes**, I've tried built in option for handling floats but there is no difference in output unfortunately.
