### ISSUE TITLE
`JsonConvert.PopulateObject` compatibility with file header

### ISSUE THREAD

**Issue by terasato** [JamesNK/Newtonsoft.Json#667]
Recently I've switched from `JsonConvert.Deserialize` to `JsonConvert.PopulateObject`, and I found that `PopulateObject` is not compatible with "file headers".

`JsonConvert.Deserialize` accepts the following JSON, but `JsonConvert.PopulateObject` results 
`Unexpected initial token 'Comment'  when populating object. Expecting JSON object or array.`
```json
// file header
{
"prop": 1.0
}
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/b30e1a178b106580d928a541821120281a3b89ab
