### ISSUE TITLE
Problem serializing interfaces that derive from other interfaces and use "new" for a property.

### ISSUE THREAD

**Issue by jimcarley** [JamesNK/Newtonsoft.Json#669]
I have a situation where I have a [DataContract} class with a [DataMember} field of type "IEnumerator<int>". An instance of this class is failing to serialize with Json.Convert.SerializeObject with this exception:

Exception caught: Newtonsoft.Json.JsonSerializationException : A member with the
 name 'Current' already exists on 'System.Collections.Generic.IEnumerator`1[System.Int32]'. Use the JsonPropertyAttribute to specify another name.

IEnumerator<T> derives from IEnumerator. IEnumerator has the public property named "Current" which returns an "object". IEnumerator<T> has a "new" implementation of "Current" that returns a "T".

I found the following code in Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties:

        public static IEnumerable<PropertyInfo> GetProperties(Type targetType, BindingFlags bindingAttr)
        {
            ValidationUtils.ArgumentNotNull(targetType, "targetType");

            List<PropertyInfo> propertyInfos = new List<PropertyInfo>(targetType.GetProperties(bindingAttr));

            // GetProperties on an interface doesn't return properties from its interfaces
            if (targetType.IsInterface())
            {
                foreach (Type i in targetType.GetInterfaces())
                {
                    propertyInfos.AddRange(i.GetProperties(bindingAttr));
                }
            }

This is the code that is adding the "Current" property to the propertyInfos list a second time. 

We are getting the "Current" property added for both IEnumerable<T> and IEnumerable.

I modified the above code to try to avoid doing this, as follows:

        public static IEnumerable<PropertyInfo> GetProperties(Type targetType, BindingFlags bindingAttr)
        {
            ValidationUtils.ArgumentNotNull(targetType, "targetType");

            List<PropertyInfo> propertyInfos = new List<PropertyInfo>(targetType.GetProperties(bindingAttr));

            // GetProperties on an interface doesn't return properties from its interfaces
            if (targetType.IsInterface())
            {
                foreach (Type i in targetType.GetInterfaces())
                {
                    // jcarley begin
                    //propertyInfos.AddRange(i.GetProperties(bindingAttr));
                    bool alreadyInList = false;
                    foreach (var propertyInfo in i.GetProperties(bindingAttr))
                    {
                        foreach (var existingPropertyInfo in propertyInfos)
                        {
                            if (existingPropertyInfo.Name == propertyInfo.Name)
                            {
                                alreadyInList = true;
                                break;
                            }
                        }
                        if (alreadyInList)
                        {
                            continue;
                        }
                        propertyInfos.Add(propertyInfo);
                    }
                    // jcarley end
                }
            }

This code does NOT throw the exception and seems to work properly, but I am not 100% sure that this is the correct fix to the problem.

I currently running against dnxcore50 (1.0.0-beta7).

Here is what a little repro program looks like:

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace JSonSerializerIEnumeratorRepro
{
    public class Program
    {
        public void Main(string[] args)
        {
            try
            {
                ClassToSerialize serializeMe = new ClassToSerialize();
                JsonSerializerSettings settings = new JsonSerializerSettings
                {
                    TypeNameHandling = TypeNameHandling.Auto,
                    TypeNameAssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Simple,
                    ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                    ObjectCreationHandling = ObjectCreationHandling.Replace,
                    ReferenceLoopHandling = ReferenceLoopHandling.Serialize
                };

                var serialized = JsonConvert.SerializeObject(serializeMe, Formatting.Indented, settings);
                Console.WriteLine("SerializeObject succeeded");
                var deserialized = JsonConvert.DeserializeObject<ClassToSerialize>(serialized, settings);
                Console.WriteLine("DeserializeObject succeeded");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception caught: {0} : {1}", ex.GetType().ToString(), ex.Message);
            }

            Console.WriteLine("Press any <enter> to finish");
            Console.ReadLine();
        }
    }

    [DataContract]
    public class ClassToSerialize
    {
        [DataMember]
        IEnumerator<int> myEnumerator;
        [DataMember]
        List<int> myList;

        Type enumeratorType;

        public ClassToSerialize()
        {
            this.myList = new List<int> { 1, 2, 3 };
            this.myEnumerator = this.myList.GetEnumerator();
            this.enumeratorType = this.myEnumerator.GetType();
        }
    }
}

**Comment by JamesNK** [comment]
I believe this has already been fixed.

https://github.com/JamesNK/Newtonsoft.Json/commits/master/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs

I don't know when it will be released.
