### ISSUE TITLE
PopulateObject passes property types into Converters

### ISSUE THREAD

**Issue by biscuitWizard** [JamesNK/Newtonsoft.Json#671]
I'm not sure if this is intended functionality or not, but I find it /incredibly/ unusual.

Observed Results:
1. Write a JsonConverter implementation.
2. Add a breakpoint at CanConvert.
3. Observe types:
4. Try JsonConvert.SerializeObject(FooObject) -> type is FooObject
5. Try JsonConvert.DeserializeObject(FooObject) -> type is FooObject
6. Try JsonConvert.PopulateObject("sample json", FooObject) -> type is Int32 (a property on FooObject)

Expected Results:
PopulateObject would pass in the JToken/JObject tree for the /entire/ object being populated, and the existing object would be passed through the existingObject parameter on ReadJson().

**Comment by JamesNK** [comment]
That's by design. JsonConverters aren't designed to work with populate. They only run when creating a new type.

**Comment by 2kCarlos** [comment]
That's unfortunate. I was hoping I didn't have to keep creating new objects each time I'd like to read/interpret Json data. Is there any way I can "read-in-place" into an already-existing object, and customize how the Json data is read (basically what the JsonConverters do)?

**Comment by jzapdot** [comment]
> That's by design. JsonConverters aren't designed to work with populate. They only run when creating a new type.

How do you patch existing objects with custom serialization? This seems like a pretty substantial hole; a developer can write custom converters to deserialize/serialize an object, but if they need to patch it there isn't a way to control that in the same way?

**Comment by jzapdot** [comment]
I've added the question [here](https://stackoverflow.com/questions/68006064/how-can-you-patch-an-existing-object-with-custom-serialization-using-json-net) on StackOverflow since this is blocking progress on one of our features and the brute force way to solve this for patching an existing object seems like "reimplement all the custom serialization" in two places (i.e, load the patch json into a `JObject` and parse the entire thing manually 🤮).

**Comment by 2kCarlos** [comment]
@jzapdot Thanks for linking the StackOverflow question, and goodluck to you/your team >.< that does sound terrible haha ☠️ 

Hope there's a way!

**Comment by biscuitWizard** [comment]
This was exactly the problem I had 6 years ago. :) Amusing to me it's all game developers having this problem! At least we aren't suffering alone.
