### ISSUE TITLE
JsonConvert.ToString throws IndexOutOfRangeException for certain Unicode strings

### ISSUE THREAD

**Issue by brjohnstmsft** [JamesNK/Newtonsoft.Json#672]
A very specially-crafted string will cause `JsonConvert.ToString()` to throw `IndexOutOfRangeException`. This happens because `JavaScriptUtils.WriteEscapedJavaScriptString()` re-uses a buffer that’s the wrong size, but only if the different cases of its parsing logic are invoked in the correct order (hence the very specially-crafted string).

Here is a minimal repro:

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Newtonsoft.Json;

    namespace JsonNetCrash
    {
        [TestClass]
        public class JsonConvertTests
        {
            [TestMethod]
            public void ConvertStringToStringExpectSuccess()
            {
                const char NonAsciiChar = (char)257;
                const char EscapableNonQuoteAsciiChar = '\0';   // If you change this to 'a', the test will pass.
                string value = NonAsciiChar + @"\" + EscapableNonQuoteAsciiChar;

                string convertedValue = JsonConvert.ToString((object)value);
                Assert.AreEqual('"' + value.Replace(@"\", @"\\") + '"', convertedValue);
            }
        }
    }

I have used the above repro to verify that this issue exists in JSON.NET 6.0.4 and 7.0.1.

**Comment by JamesNK** [comment]
Cool bug. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/a2f9acf917d06c7646fbef8488581525956bfd1b
