### ISSUE TITLE
Add ShouldSerializeAttribute

### ISSUE THREAD

**Issue by sunsided** [JamesNK/Newtonsoft.Json#679]
At the moment, the `bool ShouldSerialize{Name}()` methods don't play well (at all) with refactoring. I'd propose the addition of a `[ShouldSerialize(Field = "name")]` method attribute, as this could be used with `nameof()`:

```csharp
public class Foo 
{
    public IList<string> SomeList { get; set; }

    [ShouldSerialize(Field = nameof(SomeList))]
    private bool ReallyEmbedThatList() 
    {
       return SomeList.Count > 0;
    }
}
```

**Comment by JamesNK** [comment]
You could do something like this with nameof already with a custom contract resolver. I don't think this would be used enough to be worth the complexity.
