### ISSUE TITLE
7.0.1 Nuget Package is failing on .net 4.5

### ISSUE THREAD

**Issue by fahadash** [JamesNK/Newtonsoft.Json#680]
I have a .NET 4.5 App. I pulled Newtonsoft Json from the Package Manager window. It showed everywhere that it pulled 7.0.1 but when I run my app, I get run-time error

Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference

It sounds like the there is a version conflict in reference vs the actual assembly

There was a similar error a year ago
http://stackoverflow.com/questions/22507189/could-not-load-file-or-assembly-newtonsoft-json-version-4-5-0-0-culture-neutr

**Comment by JamesNK** [comment]
7.0.1 works on 4.5. Sounds like an assembly loading issue.

**Comment by fahadash** [comment]
@JamesNK I created a fresh project and pulled 7.0.1 from Nuget and have this issue. I deferred to older versions of the package and my app works fine.
