### ISSUE TITLE
TypeNameHandling not working on deserialization

### ISSUE THREAD

**Issue by JoeyFR** [JamesNK/Newtonsoft.Json#682]
I went through the questions on the subject here and on SO, and [the closest to my situation][1] didn't address my concern.

I have the following classes :

    public abstract class BaseClass
    {
    
    }
    
    public class ConcreteClass
    {
    
    }

My setting object for both the serialization and the deserialization is the following one : 

    JsonSerializerSettings _serializationSettings = new JsonSerializerSettings 
    { 
    	NullValueHandling = NullValueHandling.Ignore, 
    	TypeNameHandling = TypeNameHandling.All, 
    	ContractResolver = new MyContractResolver(), 
    	ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor, ReferenceLoopHandling = ReferenceLoopHandling.Ignore 
    };

I am trying to deserialize like that :

    var myDeserializedObject = JsonConvert.DeserializeObject<BaseClass>(jsonString);

But for some reason, I am getting the error 

> Could not create an instance of type T Type is an interface or abstract class and cannot be instantiated

Even though the root Json object does have a $type property. I've tried deserializing to a JObject and then using `JObject.To<BaseType>()` but I'm having the same result. I need to get this approach working, and would prefer not to use custom converters as I use polymorphism all over the place.

Do you have any idea on how I can get this deserialization working ?

Thanks

**Update 10/10/15**

I am still investigating and I think that the issue might be that when I inspect the JObject of my deserialized object, the First property is the "_id" property :

[![enter image description here][3]][3]

I assume that since the error message is : 

[![enter image description here][2]][2]

JSON.NET probably needs to read the type first to instantiate the correct object. I don't see how to reproduce this situation where "_id" is first, from a separate project like the one provided below. I tried, a couple of combination, of nested complex properties, but I always have the $type first. And it is probably why it works fine there.

I first tryied to put together an override of `CreateProperties` on my ContractResolver :

    protected override System.Collections.Generic.IList<JsonProperty> CreateProperties(System.Type type, MemberSerialization memberSerialization)
        {
            var properties = base.CreateProperties(type, memberSerialization);

            var propWithDollar = properties.Where(x => x.PropertyName.Contains("$"));
            foreach (var prop in propWithDollar)
            {
                properties.Remove(prop);
                properties.Insert(0, prop);
            }

            return properties;
        }

That was never called on deserialization, and finally I managed to do put the $type property at the very top by using : 

    var prop = deserializedJObject.Property("$type");
    deserializedJObject.Remove("$type");
    deserializedJObject.AddFirst(prop);

But unfortunately it didn't help, I'm still facing the same cast issue.

I'm getting in serious troubles guys... I spent 4 days on that one. Any idea or suggestion would be very welcome.

  [1]: http://stackoverflow.com/questions/28128923/serializing-an-interface-abstract-objet-using-newtonsoft-json
  [2]: http://i.stack.imgur.com/5R3J0.png
  [3]: http://i.stack.imgur.com/wJ18a.png

**Comment by JoeyFR** [comment]
So folks, there is a bug here, I've finally been able to find that this error occurs when the $type property is not the very first property of the **json string**. Normally the order of the properties shouldn't matter. And for some reason, even reordering the properties in the JObject doesn't help. This one was a very subtly one, I've spent 4 days on that !  

Please note that with the increase of popularity of NoSQL my scenario is very common. Whenever I retrieve my JSON object, the database put the "_id" property at the very top. Now I need to look for a quick and dirty way to modify the JSON string.

**Comment by JoeyFR** [comment]
I have made a demonstration project to highlight where the issue is : http://we.tl/RiemGkRTF2

**Comment by JamesNK** [comment]
http://www.newtonsoft.com/json/help/html/DeserializeMetadataPropertyHandling.htm

**Comment by JoeyFR** [comment]
Thanks James! I think this should be in the doc page of TypeNameHandling. As a person new to the library, it took me 4 days to track my issue down  to the JSON string.

And I mean 4 days of reading all the SO questions, reading the source code etc... Before that you are in the dark and nobody can help you

**Comment by GeorgeGoodchild** [comment]
Thanks - you just saved me days of head scratching too

**Comment by titobf** [comment]
Thanks. I also ran into the same issue.

**Comment by JamesNK** [comment]
I've improved documentation by mentioning MetadataPropertyHandling alongside TypeNameHandling

https://github.com/JamesNK/Newtonsoft.Json/commit/376b9817692d9cc029f82be32614ca9d68639921
