### ISSUE TITLE
Add support for snake_case JSON?

### ISSUE THREAD

**Issue by RehanSaeed** [JamesNK/Newtonsoft.Json#684]
We already have the option of using `PascalCase` and `camelCase` for our JSON using the `CamelCasePropertyNamesContractResolver`. I've been doing some reading [here](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) and came across `snake_case` (I've also seen it called `bean_case`).

Apparently, based on an [eye tracking study](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?reload=true&tp=&arnumber=5521745) on camelCase and snake_case, snake_case is 20% easier to read than camelCase.

My understanding is that snake case is more popular in Python or Ruby circles while camel case is more popular in C# and Java. So, not sure what the appetite would be for this but I found the above empirical evidence quite compelling.

**Comment by JamesNK** [comment]
Camel case is the standard for JavaScript which is why it is included in the library. Other cases can be separate user created NuGet packages.
