### ISSUE TITLE
Strange behavior when serializing KeyValuePair using a contract implementing IContractResolver

### ISSUE THREAD

**Issue by alisabzevari** [JamesNK/Newtonsoft.Json#685]
Consider this code:
```c#
class Program
    {
        static void Main(string[] args)
        {
            var pairs = new KeyValuePair<int, int>(1, 1);

            var setting1 = new JsonSerializerSettings() { ContractResolver = new MyContractResolver() };
            var setting2 = new JsonSerializerSettings() { ContractResolver = new CamelCasePropertyNamesContractResolver() };

            var json1 = JsonConvert.SerializeObject(pairs, setting1);
            var json2 = JsonConvert.SerializeObject(pairs, setting2);

            Console.WriteLine(json1); // prints {"Key":1,"Value":1}
            Console.WriteLine(json2); // prints {"key":1,"value":1}
            Console.ReadKey();
        }
    }

    internal class MyContractResolver : IContractResolver
    {
        readonly IContractResolver _camelCaseContractResolver;

        public MyContractResolver()
        {
            _camelCaseContractResolver = new CamelCasePropertyNamesContractResolver();
        }

        public JsonContract ResolveContract(Type type)
        {
            return _camelCaseContractResolver.ResolveContract(type);
        }
    }
```
It seems that serializer refuses to use camel casing when dealing with KeyValuePair; But only when implementing a contract resolver using `IContractResolver`. I think serializer uses something more than just `ResolveContract` method; But only when defined `ContractResolver` is `DefaultContractResolver`.

**Comment by stoiKris** [comment]
From what I can gather, your resolver needs to override 'ResolvePropertyName', and return the camelcase version of the string received. But, then again, this is the same 'CamelCasePropertyNamesContractResolver' does.
Also, your Resolver will be ignored by the KeyValuePairConverter if it`s base class is not DefaultContractResolver

**Comment by alisabzevari** [comment]
@stoiKris Thank you for answering. I was wondering if it is possible to create a contract resolver with just implementing `IContractResolver` or every contract resolver needs to be inherited from `DefaultContractResolver`.
And why `KeyValuePairConverter` ignores my contract resolver but others don't?

**Comment by JamesNK** [comment]
Unfortunately this is a limitation of IContractResolver being an interface. There isn't a clean way to fix this limitation.
