### ISSUE TITLE
Converting booleans to strings makes unparsable values

### ISSUE THREAD

**Issue by veleek** [JamesNK/Newtonsoft.Json#690]
I have parsed some Json and I have a set of JValues that I'm looping through and eventually setting some properties in another document.  

Unfortunately, when I take the JValue and I call .ToString() on it, it converts my JValue with a bool type and a value of true, to the string "True".  This is the same behavior as saying

bool b = true;
string s = b.ToString();

Unfortunately, I send this updated document elsewhere, and it's deserialized but it will fail because it outputs "True" instead of "true".  This seems like unexpected behavior and I can't seem to find any way to get a Boolean JValue to produce the actual JSON string that could be parsed later.

NB: I'm actually setting attributes on an XML document, but the same behavior would be occurring if I was constructing a JSON document the way I am.  I don't necessarily know the type of the value, I just take to the .ToString() and set it as the value of the attribute and it would be nice if I didn't have to special case Booleans.

**Comment by veleek** [comment]
Actually, let me amend that quickly: 

In order to get a Boolean to produce true as the output, then I can use JsonConvert.SerializeObject(...), however this also produces quoted strings when serializing string objects which won't work in some cases.

**Comment by JamesNK** [comment]
That's by design. Strings in JSON aren't valid without quotes.
