### ISSUE TITLE
Cannot instantiate interfaces

### ISSUE THREAD

**Issue by nug700** [JamesNK/Newtonsoft.Json#691]
"Newtonsoft.Json.JsonSerializationException: Could not create an instance of type LibNoise.IModule. Type is an interface or abstract class and cannot be instantiated. Path 'module.ControlModule', line 3, position 25."

Why not? The library can determine the type behind the interface and get the values just fine, so why can't it save the type behind it, instantiate that type, and give it the values?

For example, say you have interface 'IA', and you have type 'B' that implements IA with member "mC" (that does not exist in IA),. Currently if you have a member in another struct/class of type "IA" named "ia" and you set it to type B, the library would save it like so:
{"ia":{"mC":value}}

Which obviously cannot be deserialized back into the original object B because it does not specify which type ia is. However, my point and question is why can't you simply just serialize the type with the  variable name, changing the json string to look something like this: 
 { "ia\<B\>":{"mC":value}}

Then you could just instantiate B and and set it to ia.

**Comment by IanYates** [comment]
Have you seen:  http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm  ?

**Comment by nug700** [comment]
Thank you that worked.
