### ISSUE TITLE
BsonReader converts 32-bit integers to long

### ISSUE THREAD

**Issue by pranavkm** [JamesNK/Newtonsoft.Json#692]
We use `BsonWriter` \ `BsonReader` to roundtrip a `Dictionary<string, object>` in Mvc 6. For some reason, the `BsonReader` casts `int` values to `long` which makes the round tripping a bit hard to work with. 

Here's the line of code that does the cast: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Bson/BsonReader.cs#L601.

Would you know why it behaves this way? Could the cast be removed?

**Comment by aravol** [comment]
Inheriting from and needing to work with methods in JsonReader, it looks like BsonReader is converting to long to stay in tune with the fact that Json integers are always longs

**Comment by JamesNK** [comment]
I did that to match the behavour of JsonTextReader. Integers are always long for numbers when no type information exists.

I'm pretty sure that changing this now would be a breaking change for some people.

**Comment by pranavkm** [comment]
Thanks. We have a mediocre workaround for this issue now. I'll try and figure out if there's an alternate scheme we could use so we can reliably round trip more data types.
