### ISSUE TITLE
error message causes string.Formate to throw error

### ISSUE THREAD

**Issue by nug700** [JamesNK/Newtonsoft.Json#693]
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.Drawing.Color[]]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'preset[0].images', line 13, position 19.

This error causes string.Format to throw "Input string was not in a correct formate" error, thus making it incredibly difficult to log and debug.

**Comment by JamesNK** [comment]
Then don't use it in a string.Format
