### ISSUE TITLE
Serializing System.Web.OData.Delta<T> results in empty JSON

### ISSUE THREAD

**Issue by ianschmitz** [JamesNK/Newtonsoft.Json#695]
Here's the relevant [StackOverflow post](http://stackoverflow.com/questions/31144817/serializing-deltat-to-json) with the issue i'm experiencing:

Using `JsonConvert.SerializeObject` returns `{}`. The incoming `Delta<T>` looks like it's correctly formed.

Any idea why `Delta<T>` is serializing to an empty JSON object?

**UPDATE**

- Using `System.Web.OData.Delta<T>` gives me `{}`.
- Using `System.Web.Http.OData.Delta<T>` gives me a full serialization of `T`, including unchanged properties.

**Comment by JamesNK** [comment]
I'm not familiar with either Delta

**Comment by ianschmitz** [comment]
Delta is used for PATCH requests in ASP.NET WebAPI or MVC.

http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint

**Comment by ivoalmeida** [comment]
Has this been fixed?

**Comment by ianschmitz** [comment]
It's still outstanding to my knowledge
