### ISSUE TITLE
Unable to use 'dynamic' with Json.Net and Universal Apps

### ISSUE THREAD

**Issue by TheBlueSky** [JamesNK/Newtonsoft.Json#696]
I have the following code

    var client = new HttpClient();
    var url = new Uri("https://someuri/someresource", UriKind.Absolute);
    var response = await client.GetAsync(url);
    var content = await response.Content.ReadAsStringAsync();
    var json = JsonConvert.DeserializeObject(content) as dynamic;

As per what I see when I debug the code, everything is completed successfully; i.e., the above returns the expected JSON, and `json` object has the expected properties... let's assume it is:

    { "current_page": 1, "total_pages": 7, "items": [ ... ] }

However, when I do `json.current_page`, I get the following exception:

> 'object' does not contain a definition for 'current_page' and no
> extension method 'current_page' accepting a first argument of type
> 'object' could be found (are you missing a using directive or an
> assembly reference?)

Does anyone has an ides on what's going wrong here?

P.S. I tried it with both types of Universal Apps, Windows 8.1 and Windows Phone 8.1.

P.S. Same code works with a Console application, but not Universal Apps; it also failed when tried it with an ASP.Net MVC application.

**Comment by JamesNK** [comment]
UWP apps use the PCL259 assembly and it doesn't support dynamic. A dedicated assembly will probably be added in the future but not anytime in the next couple of releases.
