### ISSUE TITLE
Add support for serializing 24:00 In JSON.NET

### ISSUE THREAD

**Issue by mburbea** [JamesNK/Newtonsoft.Json#697]
The ISO8601 spec allows for representing a date at midnight by representing it with 24:00
Here is a wiki article on the subject:
https://en.wikipedia.org/wiki/ISO_8601#Times
e.g.
The following two datetimes are equivalent:
```csharp
{
    "oneForm":"2015-01-01T24:00:00Z",
    "alternateForm":"2015-01-02T00:00:00Z"
}
```

Currently, JSON.net throws a parsing error:
```
Could not convert string to DateTime: 2015-01-01T24:00:00Z. Path 'oneForm'
```
Relevent stackoverflow:
http://stackoverflow.com/questions/32640773/parsing-json-dates-that-end-in-t240000z

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/331fcc0ebb2f5fdc8f4a66673a4074068efe44ef
