### ISSUE TITLE
WebApi default SerializerSettings and EnumConverter on deserializeo

### ISSUE THREAD

**Issue by meriturva** [JamesNK/Newtonsoft.Json#698]
Hi!
we set the default settings on startup of our web api 2.2 solution.
```
HttpConfiguration config = new HttpConfiguration();
config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new CustomStringEnumConverter { AllowIntegerValues = true });
```

Now when we produce output from our enums the CustomStringEnumConverter is called. Great!
....but not when we receive the enum from controller method as parameter

Any way to have the default CustomStringEnumConverter called also when we receive enums from method parameters?
Thanks.
Diego

**Comment by GaTechThomas** [comment]
We had a similar issue. We found that we needed to go into the MvcWebAppConfiguration.Register(HttpConfiguration configuration) method and set the values on configuration.Formatters.JsonFormatter.SerializerSettings on the configuration object passed into that method.

**Comment by meriturva** [comment]
Thanks GaTechThomas but the main problem here is that i don't have Mvc on our owin/selfhosted project so no way to configure Mvc part.
I also check if with IControllerConfiguration Attribute on specific controller solves the problem as: http://www.asp.net/web-api/overview/advanced/configuring-aspnet-web-api

but again no way.
So the main problem remain...how to use CustomEnumConvert when we receive parameter from method controller?

**Comment by meriturva** [comment]
Any news? i think it is really important to full support web api also with custom converters.

**Comment by JamesNK** [comment]
I don't know what happens inside web api. Raise it with them.

**Comment by pankashtan** [comment]
Hey, I had the similar problems, this [solution ](https://blogs.perficient.com/sitecore/2016/09/30/sitecore-and-web-api-set-custom-contractresolver/)helped me:
