### ISSUE TITLE
Ignoring properties still checks their type?

### ISSUE THREAD

**Issue by adrianhara** [JamesNK/Newtonsoft.Json#699]
Hi,

I ran into a strange issue today and wanted to ask if it's a bug or by design. I noticed that when ignoring some properties from serialization (either by JsonIgnore or declaring the object OptIn) the (de)serializer still looks at their type and throws at deserialization if the JSON string doesn't match it.

For example, I had a property declared of type "string", but not included in the serialization. However, the actual JSON string changed and now it was an object instead. I had expected this to not impact the deserialization code since the property was "ignored", however the deserializer threw. Changing the property type to "object" fixed it, but it's a bit surprising that an ignored property influences the deserialization. I would have expected the deserializer to just check the name of the property, see it's ignored and move to the next one.

Can anyone please shed some light on this?

Thanks!

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/226832ff5d94f6fd361140f2a8d689cc99d9ec4f
