### ISSUE TITLE
Precompiled token queries

### ISSUE THREAD

**Issue by OlduwanSteve** [JamesNK/Newtonsoft.Json#700]
Looking at the implementation of SelectToken, it parses the path into a JPath object then calls Evaluate. I have a use-case where I'll be running the same query on many different Json blobs, so I'd rather not do the work of parsing the query every time.

It seems like one approach would be to make JPath public, but I accept you may have had reasons for keeping it internal.

It would be *really* nice if I could pre-define the JPath object and perform a sort of 'streaming' parse that skips elements which don't match, and builds the query result on the fly.

Just making JPath public would be a great first step though, thanks for reading!

**Comment by JamesNK** [comment]
I don't want to expose the internal implementation. If perf is important I would recommend using something other than JSON Path.

**Comment by OlduwanSteve** [comment]
Fair enough. I'm using JSON Path because I need to define the queries as data. For now that's much more important than the slight perf hit so I'll stick with it as it is.
