### ISSUE TITLE
Breaking change in deserialization behavior for classes using [JsonExtensionData]

### ISSUE THREAD

**Issue by ayende** [JamesNK/Newtonsoft.Json#701]
Consider the following class:

    public class Item
    {
        [JsonExtensionData]
        public IDictionary<string, JToken> ExtensionData;

        public IEnumerable<string> Foo
        {
            get { yield return "foo"; yield return "bar"; }
        }
    }

It has three important features:

* It has an extension data 
* It uses a read only property that cannot be easily deserialized.
* It needs to be serialized with TypeNameHandling = TypeNameHandling.Auto

This code will fail:

    var jsonSerializer = new JsonSerializer
    {
        TypeNameHandling = TypeNameHandling.Auto
    };
    var stringWriter = new StringWriter();
    jsonSerializer.Serialize(stringWriter, new Item());
    var str = stringWriter.GetStringBuilder().ToString();
    Console.WriteLine(str);
    var deserialize = jsonSerializer.Deserialize<Item>(new JsonTextReader(new StringReader(str)));

The underlying problem happened in this commit:
https://github.com/JamesNK/Newtonsoft.Json/commit/3536c768730d7dbfe642874404ab43b2ce6b2256

More specifically, this change:
https://github.com/JamesNK/Newtonsoft.Json/commit/3536c768730d7dbfe642874404ab43b2ce6b2256#diff-0a9aaee3fa9afeb40961d1adf9202fc1R1789

The problem is that the code is trying to materialize the value, while before we just got the raw json value.

This is what the json looks like:

    {"Foo":{"$type":"ConsoleApplication1.Item+<get_Foo>d__2, ConsoleApplication1","$values":["foo","bar"]}}

Because this value cannot be deserialize, this fails with an error:

	Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error setting value in extension data for type 'Console
	Application1.Item'. Path 'Foo.$values', line 1, position 89. ---> Newtonsoft.Json.JsonSerializationException: Cannot cre
	ate and populate list type ConsoleApplication1.Item+<get_Foo>d__2. Path 'Foo.$values', line 1, position 89.

I reverted this line in our own copy of JSON.Net, because it is enough for our needs, but I'm not sure how to actually resolve it in JSON.Net, since this might create compatability issues if just reverted.

The ideal manner would be to have a way of saying, I don't need objects here, so if this fails, just let me run.
Maybe changing the extension data setter to get the json and a delegate to actually materialize the value?

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/92102f9a3352ca52d2bbbf0cd1eadae0783970ea
