### ISSUE TITLE
Json DateTimeOffset deserialization Problem

### ISSUE THREAD

**Issue by danejahn** [JamesNK/Newtonsoft.Json#702]
Hi, I used json.net to desrialize DateTimeOffset. 
1. "2015-10-29T18:56:20.328969+08:00" is ok.
2. "/Date(1418924498000+0800)/", is not ok. offset is 0, and the datetime is more than eight hours.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/c96779dc10fb6ed3c0c494c366a942322d78ed70
