### ISSUE TITLE
BsonWriter

### ISSUE THREAD

**Issue by liamfl** [JamesNK/Newtonsoft.Json#704]
When writing a large array of objects with BsonWriter you get an OutOfMemory exception. Remove the StartArray and EndArray calls and the writer works properly.

Here's some sample code that falls over:

Public Class Region
    Public Property Id As Integer
    Public Property Name As String
    Public Property FDS_Id As String
End Class

Public Class Regions
    Inherits List(Of Region)

    Public Sub New(capacity As Integer)
        MyBase.New(capacity)
    End Sub
End Class

Module Module1
    Sub Main()
        Dim list = GetRegionList(5000000)
        Dim elapsedBson = CreateFileBson_Stream(list)
        Debugger.Break()
    End Sub

    Public Function GetRegionList(count As Integer) As List(Of Region)
        Dim regions As New Regions(count - 1)
        For lp = 0 To count - 1
            regions.Add(New Region With {.Id = lp, .Name = lp.ToString, .FDS_Id = lp.ToString})
        Next
        Return regions
    End Function

    Public Function CreateFileBson_Stream(regions As Regions) As Long
        Dim sw As New Stopwatch
        sw.Start()
        Dim lp = 0

        Using stream = New FileStream("c:\atlas\regionsStream.bson", FileMode.Create, FileAccess.Write)
            Using ms = New MemoryStream
                Using writer = New Bson.BsonWriter(ms)
                    writer.WriteStartArray()

                    For Each item In regions
                        writer.WriteStartObject()
                        writer.WritePropertyName("Id")
                        writer.WriteValue(item.Id)
                        writer.WritePropertyName("Name")
                        writer.WriteValue(item.Name)
                        writer.WritePropertyName("FDS_Id")
                        writer.WriteValue(item.FDS_Id)
                        writer.WriteEndObject()

                        lp += 1
                        If lp Mod 1000000 = 0 Then
                            writer.Flush()
                            ms.WriteTo(stream)
                            stream.Flush()
                        End If
                    Next

                    writer.WriteEndArray()
                End Using
            End Using
        End Using

        sw.Stop()
        Return sw.ElapsedMilliseconds
    End Function
End Module

**Comment by JamesNK** [comment]
BSON has to be prefixed with the size so he entire object has to be loaded into memory at once.
