### ISSUE TITLE
accessing table index JArray with uint gives an exception, not with int

### ISSUE THREAD

**Issue by lapinroux** [JamesNK/Newtonsoft.Json#706]
//This gives an exception
uint number = 0;
JObject l_action = (JObject)currentScenario[ACTION_KEYWORD][number];

It gives this exception -> 
"An unhandled exception of type 'System.ArgumentException' occurred in Newtonsoft.Json.dll
Additional information: Accessed JArray values with invalid key value: 0. Array position index expected."

//This doesn't give an exception
int number = 0;
JObject l_action = (JObject)currentScenario[ACTION_KEYWORD][number];

**Comment by JamesNK** [comment]
I've improved the error message to say an Int32 is expected.
