### ISSUE TITLE
Nullable enum deserialization throws exception

### ISSUE THREAD

**Issue by BruceMellows** [JamesNK/Newtonsoft.Json#708]
The default serialize of an enum is to int which works when used as `jToken.ToObject<MyEnum>()` however `jToken.ToObject<MyEnum?>()` fails if the value is present in the JSON string, but works (returns null) when the value is not present in the JSON string.

I have locally corrected this by changing the following in
`class JToken ... public static object ToObject(JToken jToken, Type objectType)`
`- if (isEnum && jToken.Type == JTokenType.String)`
`+ if (isEnum && (jToken.Type == JTokenType.String || jToken.Type == JTokenType.Integer))`

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/2c3dafd62ddc52bac888e11e3fc3ddca816d18d5

**Comment by kotpal** [comment]
This is occurring if you use a FlagsEnumConverter and try to deserialize a nullable flags enum. The FlagsEnumConverter is here: http://stackoverflow.com/a/26105156/2183503
