### ISSUE TITLE
Setting JsonConvert.DefaultSettings changes the behavior of ToObject

### ISSUE THREAD

**Issue by npiasecki** [JamesNK/Newtonsoft.Json#709]
I have a scenario where I'm accessing the value of a `JProperty` by calling `JProperty.ToObject<string>()`. This has worked for me before so I always did it this way, though I could be a fool. Then I discovered that when some other code was introduced that changed the default serializer settings, it would fail. I was able to workaround it by calling `ToObject<string>()` on the `Value` instance instead.

I'm not sure if this behavior is a bug in the library, or if I've always been doing it wrong and just got lucky up until now.

Here's a sample function that reproduces it:

        [Test]
        public void Weird()
        {
            var json = "[{\"something\":[{\"property\":\"value\"}]}]";

            // Try to obtain the "value" ... this works
            {
                var array = JArray.Parse(json);
                var first = (JObject)array.First;
                var value = (first["something"] as JArray)
                    .Select(x => x as JObject)
                    .Select(x => x.Property("property").ToObject<string>())
                    .First();
                Assert.AreEqual("value", value);
            }

            // Set default serializer settings; the options don't seem
            // to matter, just that it is set
            JsonConvert.DefaultSettings = () =>
            {
                return new JsonSerializerSettings();
            };

            // Now try to obtain the "value" in the same way again ...
            try
            {
                var array = JArray.Parse(json);
                var first = (JObject)array.First;
                var value = (first["something"] as JArray)
                    .Select(x => x as JObject)
                    .Select(x => x.Property("property").ToObject<string>())
                    .First();
            }
            catch
            {
                // Whoops, failed with: Error reading string. Unexpected token: PropertyName. Path '', line 1, position 27.
            }

            // This method, however, still works
            {
                var array = JArray.Parse(json);
                var first = (JObject)array.First;
                var value = (first["something"] as JArray)
                    .Select(x => x as JObject)
                    .Select(x => x.Property("property").Value.ToObject<string>())
                    .First();
                Assert.AreEqual("value", value);
            }

            // This works too
            {
                var array = JArray.Parse(json);
                var first = (JObject)array.First;
                var value = (first["something"] as JArray)
                    .Select(x => x as JObject)
                    .Select(x => (string)x.Property("property").Value)
                    .First();
                Assert.AreEqual("value", value);
            }
        }

Here's the full stacktrace:

	Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: PropertyName. Path '', line 1, position 27.
	   at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
	   at Newtonsoft.Json.Linq.JTokenReader.ReadAsString()
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
	   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
	   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
	   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
	   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
	   at Shipvine.Badger.Engine.Test.Integration.SmartyStreetsStateLookupTest.<>c.<Weird>b__2_4(JObject x) in C:\Users\npiaseck\Desktop\Working Directories\Badger\Src\Shipvine.Badger.Engine.Test\Integration\Addressing\State Lookup\SmartyStreetsStateLookupTest.cs:line 55
	   at System.Linq.Enumerable.<>c__DisplayClass2`3.<CombineSelectors>b__3(TSource x)
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
	   at Shipvine.Badger.Engine.Test.Integration.SmartyStreetsStateLookupTest.Weird() in C:\Users\npiaseck\Desktop\Working Directories\Badger\Src\Shipvine.Badger.Engine.Test\Integration\Addressing\State Lookup\SmartyStreetsStateLookupTest.cs:line 53

**Comment by JamesNK** [comment]
That's by design.

**Comment by arbitertl** [comment]
@JamesNK, Can you please clarify idea behind this intention?
I faced exactly the same situation and I don't understand why JToken.ToObject<T> method has 2 branches:
JsonConvert.DefaultSettings == null and the rest.

I'm confused that if I just want to override some settings (let's say DateTimeFormatString), I can no longer use default logic (used in "JsonConvert.DefaultSettings == null" if branch)

**Comment by JamesNK** [comment]
The branch for when DefaultSettings is null is optimized for performance and matches Json.NET's default serialization rules. When DefaultSettings have been changed then it is possible the fast version no longer matches the serializer with the new settings.

**Comment by arbitertl** [comment]
Understood, but how about making it obvious that it's not safe to call JProperty.ToObject and call JProperty.Value.ToObject to avoid break-downs.

For example making JToken.ToObject virtual and overriding it in JProperty class:

- with throwing NotSupportedException (I understand that can break backward compatibility and it breaks Liskov Substitution Principle, but if it's used like that risk is already in place)
- mark JProperty.ToObject override with ObsoleteAttribute to draw attention

Ideal case would be that JProperty is not inherited from JToken at all and does not have this method IMHO.
