### ISSUE TITLE
Which JsonNet version is DotNet CompactFramework 2 compatible?

### ISSUE THREAD

**Issue by miguelpragier** [JamesNK/Newtonsoft.Json#711]
Hi.

I'm working on a CompactFramework 2 project, but taking the last JsonNet, plus LinqBridge isn't compiling.

Has anyone achieved to compile some ( JsonNet version ) + ( LinqBridge version ) to pure CF2?

I'm using Visual Studio 2008

Best regards.

**Comment by JamesNK** [comment]
It never has
