### ISSUE TITLE
Undefined value produces invalid JSON

### ISSUE THREAD

**Issue by alecouteurbisson** [JamesNK/Newtonsoft.Json#713]
The value created by JValue.CreateUndefined() is serialised as: undefined
This is not valid JSON and it prevents the use of the undefined value in objects to omit the property completely from the JSON.

The following code (in linqpad) 
```C#
var test = new
{
	fred = "thing",
	number = 5,
	message = JValue.CreateUndefined()
};
var json = JsonConvert.SerializeObject(test);
json.Dump();
```

produces the output
```json
{"fred":"thing","number":5,"message":undefined}
```
not 
```json
{"fred":"thing","number":5}
```

as expected

**Comment by JamesNK** [comment]
That's by design. Remove the property if you don't want it written to JSON
