### ISSUE TITLE
Issue with serializing/deserializing object graph with self-referencing objects in combination with JSON constructor.

### ISSUE THREAD

**Issue by hcd** [JamesNK/Newtonsoft.Json#715]
Hello,

I have encountered an issue during serialization/deserialization of an object graph that probably has to do with an issue with the JSON constructor.

I have crafted together an as simple as possible reproduction case: 

Imagine the parent-child entities with the following class definitions : 

      public class Parent
        {
            public Parent()
           {
                Children = new List<Child>();
            }
            public int ParentId { get; set; }
            public IList<Child> Children { get; set; }
       }

    public class Child
    {
        public Child()
        {
        }
        public int ChildId { get; set; }

        private Parent _parent;
        public Parent Parent
        {
            get { return _parent; }
            set
            {
                if (value == null) throw new InvalidOperationException("Parent cannot be null");
                _parent = value;
               if (!_parent.Children.Contains(this)) 
                                                                              _parent.Children.Add(this);
            }
        }
    }
                
To prevent the self-referencing loop, I use the follwoing Json settings :
                                              
     public static class UnitTestSerializerSettings
       {
           public static JsonSerializerSettings Settings = new JsonSerializerSettings()
           {

            MissingMemberHandling = MissingMemberHandling.Ignore,
            NullValueHandling = NullValueHandling.Include,
            DefaultValueHandling = DefaultValueHandling.Include,
            PreserveReferencesHandling = PreserveReferencesHandling.Objects,
            ContractResolver = new DefaultContractResolver() { IgnoreSerializableInterface = true, IgnoreSerializableAttribute = true }
        };
    }          `

Now take the unit test : 

        [TestClass]
       public class UnitTestPoco
       {

        [TestMethod]
        public void TestRelation()
        {
            Parent parent = new Parent() { ParentId = 1 };
            Child child = new Child() { ChildId = 2 };
            child.Parent = parent;

            string json = JsonConvert.SerializeObject(child, UnitTestSerializerSettings.Settings).FormatJson();
            Child deserialized = JsonConvert.DeserializeObject<Child>(json, UnitTestSerializerSettings.Settings);
            string json2 = JsonConvert.SerializeObject(deserialized, UnitTestSerializerSettings.Settings).FormatJson();

            Assert.AreEqual(json,json2);
        }
    }
                               
The resulting json after serialization is correct, AND is equal to json2 : (formatJson() is just an extensionmethod to indent the json)

      {
       "$id": "1",
       "ChildId": 2,
       "Parent": {
           "$id": "2",
           "ParentId": 1,
           "Children": [
               {
                   "$ref": "1"
             }
          ]
       }
      }

and the assert succeeds. So far, everything is correct.

But I need, for other reasons, another constructor to be called during deserialization. So I have created a new constructor for both Child & Parent classes, that have just a dummy unused argument so the signature is different :
for Parent : 

           [JsonConstructor]
           public Parent(bool callViaJson = false)
           {
               Children = new List<Child>();
           }

for Child:

           [JsonConstructor]
           public Child(bool callViaJson = false)
           {
           }

And now my Unittest breaks ! It seems that during deserialization, an extra null gets added to the Parent.Children collection (thus without passing the Child.Parent property, or it would throw an exception)
                               
So the json2 now is : 

      {
          "$id": "1",
          "ChildId": 2,
          "Parent": {
              "$id": "2",
              "ParentId": 1,
              "Children": [
                  null,    //<-- what is this null doing here ?
                  {
                      "$ref": "1"
                  }
              ]
          }
      }                              
                               
How can this be ?  I've uploaded a repro solution as a zipfile at www.hcd.be/repro.zip

EDIT: If I expand my test to 

         [TestMethod]
           public void TestRelation()
           {
            Parent parent = new Parent() { ParentId = 1 };
            Child child = new Child() { ChildId = 2 };
            child.Parent = parent;

            string json = JsonConvert.SerializeObject(child, UnitTestSerializerSettings.Settings).FormatJson();
            Child deserialized = JsonConvert.DeserializeObject<Child>(json, UnitTestSerializerSettings.Settings);
            string json2 = JsonConvert.SerializeObject(deserialized, UnitTestSerializerSettings.Settings).FormatJson();
            Child deserialized2 = JsonConvert.DeserializeObject<Child>(json2, UnitTestSerializerSettings.Settings);
            string json3 = JsonConvert.SerializeObject(deserialized2, UnitTestSerializerSettings.Settings).FormatJson();
            Child deserialized3 = JsonConvert.DeserializeObject<Child>(json3, UnitTestSerializerSettings.Settings);
            string json4 = JsonConvert.SerializeObject(deserialized3, UnitTestSerializerSettings.Settings).FormatJson();

            Assert.AreEqual(json,json2);
          }

During every ser./deser. run, a null gets added, so eventually I end up with json4 = 

      {
          "$id": "1",
          "ChildId": 2,
          "Parent": {
              "$id": "2",
              "ParentId": 1,
              "Children": [
               null,
               null,
               null,
               {
                   "$ref": "1"
               }
              ]
          }
      }

If I comment out the [JsonConstructor] in the Child-class so that the default constructor is used, I don't have this behavior, and json == json4.

**Comment by JamesNK** [comment]
Non-default constructors and preserving references don't work well together because the child values of a type have to be deserialized before the parent is created, so the reference resolved to null.
