### ISSUE TITLE
DivideByZeroException

### ISSUE THREAD

**Issue by tofutim** [JamesNK/Newtonsoft.Json#716]
Dear James,

Thank you so much for your great work on this library. I saw something odd today trying to Deserialize a DivideByZeroException as part of a unit test.

{"InnerException":null,"HelpLink":null,"HResult":-2147352558,"Message":"a message","Source":null,"StackTrace":null,"TargetSite":null,"Data":{}}

Is the json, and when it Deserializes the message is replaced by the normal one in iOS and Android, though it works fine in Windows-based scenarios.

**Comment by tofutim** [comment]
Maybe there is an ordering thing which causes Message to be re-written.

**Comment by tofutim** [comment]
Same problem in Universal Windows App.

**Comment by JamesNK** [comment]
Behavour will be different between the different platforms because some support ISerializable and some don't.
