### ISSUE TITLE
Null reference exception when serializing to XML

### ISSUE THREAD

**Issue by adamkirkton** [JamesNK/Newtonsoft.Json#724]
[Here's a gist to recreate the problem](https://gist.github.com/adamkirkton/d74617623f18b565603b)

The issue is that when null is cast to a string or if you have a property of type string that is null and you put this into a JObject the underlying token type is string.

So when you hit line 1447 of XmlNodeConverter.cs it evaluates to true and then line 1449 immediately fails with a null reference exception. As I see it, the easiest fix is to test for null on 1449 and return the appropriate value.

Maybe there is a bigger issue and the token type in the JObject property should actually be Null, but I could see that potentially being a pretty big breaking change. This fix would at least prevent an unwanted exception while still giving the intended answer.

Sorry I didn't put a PR for this, but I couldn't get the solution to build. I think my DNX fu is lacking or something because the tests project couldn't find NUnit even though it was installed by NuGet. Still need to understand how that whole system works now.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/425c1d8402800b07b2de7e72ea7876883addc14f

**Comment by adamkirkton** [comment]
Thanks for the quick response @JamesNK!
