### ISSUE TITLE
TypeNameHandling after class Renaming (due to refactoring)

### ISSUE THREAD

**Issue by JoeyFR** [JamesNK/Newtonsoft.Json#725]
Hi,

I was puzzled by a certain use case that I finally hit today. Many times you will need to rename a class, or move it around in different namespaces during the refactoring. This will break the deserialization since the $type property would reference a type that no longer exists. 

Is there a hook-in to maintain a sort of dictionary between the new type names and the old type names ? I think this use case is very important as NoSQL databases are becoming the norm, and people tend to iterate quickly with them increasing the probably of a need to refactor.

**Comment by JamesNK** [comment]
Binder

**Comment by BradStapleton** [comment]
[Link](https://www.newtonsoft.com/json/help/html/SerializeSerializationBinder.htm)
