### ISSUE TITLE
JSON.NET .NET Native Compilation Error (Windows 10, version 1511 UWP app)

### ISSUE THREAD

**Issue by callummoffat** [JamesNK/Newtonsoft.Json#729]
When I try and build an UWP app making use of the JSON.NET Nuget library, and target it against the new SDK for the November 2015, compiling said app in Release mode, which builds it via .NET Native, starts failing with the following error. 
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(1129,5): error : Error: NUTC301B:Internal Compiler Error: Assembly 'C:\Users\Callum Moffat\Documents\Visual Studio 2015\Projects\Tutorials\Hello1\WindowsApp1\WindowsApp1\obj\x86\Release\ilc\intermediate\ILTransformed\Newtonsoft.Json.ildll' not found
If I revert the app to the old 10240 SDK, it still seems to fail when compiling in Release mode, which is required in order to pass Store certification. It appears that JSON.NET isn't liking the new SDK build.

**Comment by JamesNK** [comment]
I haven't changed anything. Raise a bug with the UWP/.NET Native team.

**Comment by aivascu** [comment]
I am facing the same issue. Is there a workaround for this?

**Comment by aivascu** [comment]
I ended up disabling the "Compile with .Net Native tool chain" option in the project's settings.
I know it's not an answer to the question but maybe this will help someone who doesn't need .NET Native compilation.

**Comment by aivascu** [comment]
We have logged an [issue](https://connect.microsoft.com/VisualStudio/feedback/details/2137770) on Visual Studio's feedback board as @JamesNK suggested.

**Comment by MattWhilden** [comment]
@aivascu I work on the .NET Native team and would like to look into this issue. However, I cannot reproduce it with the information provided. If you're still having trouble please email us at dotnetnative@microsoft.com for some followup.

**Comment by aivascu** [comment]
@MattWhilden actually this Tuesday, I believe, after the latest OS updates this issue stopped reproducing. Not really sure which update did the trick but the project now compiles on Windows 8.1 and Windows 10, in Release mode and with the .NET Native toolchain enabled.

**Comment by MattWhilden** [comment]
Glad to hear you're back on track. If someone else hits this and finds this chunk of text, please don't hesitate to reach out to us or @ me.

**Comment by TommasoScalici** [comment]
@MattWhilden I think there are still issues with Json.NET + .NET Native.

I was just trying this little repro:

    public ImmutableList<string> Test { get; set; }
    
    public MainPage()
    {
        InitializeComponent();
        TestSerialization();
    }

    void TestSerialization()
    {
         var list = new List<string> { "hi", "hello" };
         string json = JsonConvert.SerializeObject(list);
         try
         {
                Test = JsonConvert.DeserializeObject<ImmutableList<string>>(json);
                // We'll get here with .NET Native disabled...
         }
         catch (Exception ex)
         {
             // But we get here with a JsonSerializationException when .NET Native is enabled.
             Debug.WriteLine(ex);
         }
    }

And also this one:

    public sealed class CustomFormatDateConverter : IsoDateTimeConverter
    {
        public CustomFormatDateConverter(string format)
        {
            DateTimeFormat = format;
        }
    }

    [JsonObject]
    public sealed class Test
    {
        [JsonConverter(typeof(CustomFormatDateConverter), "MMddyyyy")]
        [JsonProperty]
        public DateTimeOffset Date { get; set; } = DateTimeOffset.Now;
    }


    public MainPage()
    {
        InitializeComponent();
        TestSerialization();
    }

    void TestSerialization()
    {
        try
        {
            var test = new Test();
            string json = JsonConvert.SerializeObject(test);
            // Ok without .NET Native!
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex);
            // JsonException (message: Error creating 'App.MainPage+CustomFormatDateConverter') when using .NET Native
        }
    }

I also tried playing a little with the Default.rd.xml file, but nothing seems to change or maybe I don't get how Runtime Directives should work.

**Comment by JamesNK** [comment]
Email dotnetnative@microsoft.com
I can't fix .NET Native

**Comment by TommasoScalici** [comment]
@JamesNK Thanks for the answer, I just wrote to dotnetnative.
I was just unsure to what "side" the issue were belonging.

**Comment by MattWhilden** [comment]
As with most things, "fixes" can probably happen on either side. In a perfect world we'll get a fix in .NET Native for a future release and provide a workaround for you and other consumers of this library until it's available. It's actually pretty uncommon that we have to resort actually modifying the library... but not impossible! 

It looks like someone has responded to your mail, when that reaches a positive conclusion we'll add the details here in case someone else stumbles into this or a similar issue.

**Comment by JamesNK** [comment]
I have 2000 unit tests passing on .NET Core. Json.NET errors on .NET Native are bugs in .NET Native until you convinces me otherwise :grin:

**Comment by MattWhilden** [comment]
A completely reasonable assertion. I didn't mean to imply that fixes should end up here. Occasionally we end up in an awkward spot that ends with me forking/patching a library temporarily while fixes on our side make it out of the company. It's painful for everyone involved so we really do prefer all other options ahead of that! :-)

**Comment by isenthil** [comment]
@TommasoScalici - For your first sample , include the following in the default.rd.xml and it should just work fine. Its more related to .NET Native :)

<Type Name="System.Collections.Immutable.ImmutableList" Dynamic="Required All" />
