### ISSUE TITLE
DateTimeOffset and Integer deserializing woes 

### ISSUE THREAD

**Issue by mgazza** [JamesNK/Newtonsoft.Json#734]
Hi have noticed some inconstancies when deserialisating json using different methods.
Please run the following MSpec tests. As you can see the settings are the same but the methods fail in different ways finally a test which shows a work arround
using System;
using System.IO;
using Machine.Specifications;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

namespace ModuleService.Tests.Messaging
{
    public class ANumberWithADate
    {
        public int Number { get; set; }
        public DateTimeOffset Date { get; set; }
    }
    public class ANumber
    {
         public int Number { get; set; }   
    }

    public class ADate
    {
        public DateTimeOffset Date { get; set; }
    }

    public class JsonNetProfileSpec
    {

        public class When_deserializing_int_using_JObject_from_json_with_int
        {
            private static ANumber _result;
            private static string _json = "{'Number':-86400}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
            {
                _serializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                };

                _jsonSerializer = JsonSerializer.Create(_serializerSettings);

            };

            private Because _of = () => _result = (ANumber)JObject.Parse(_json).ToObject(typeof(ANumber), _jsonSerializer);

            private It should_have_parsed_correctly = () => _result.Number.ShouldEqual(-86400);

        }

        public class When_deserializing_int_using_JsonConvert_from_json_with_int
        {
            private static ANumber _result;
            private static string _json = "{'Number':-86400}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
            {
                _serializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                };

                _jsonSerializer = JsonSerializer.Create(_serializerSettings);

            };

            private Because _of = () => _result = (ANumber)JsonConvert.DeserializeObject(_json, typeof(ANumber), _serializerSettings);

            private It should_have_parsed_correctly = () => _result.Number.ShouldEqual(-86400);

        }

        public class When_deserializing_int_using_JObject_from_json_with_float
        {
            private static ANumber _result;
            private static string _json = "{'Number':-86400.0}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
                {
                    _serializerSettings = new JsonSerializerSettings
                        {
                            DateFormatHandling = DateFormatHandling.IsoDateFormat,
                            DateParseHandling = DateParseHandling.DateTimeOffset,
                            DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                            ContractResolver = new CamelCasePropertyNamesContractResolver(),
                        };

                    _jsonSerializer = JsonSerializer.Create(_serializerSettings);

                };

            private Because _of = () => _result = (ANumber)JObject.Parse(_json).ToObject(typeof(ANumber), _jsonSerializer);

            private It should_have_parsed_correctly = () => _result.Number.ShouldEqual(-86400);

        }

        public class When_deserializing_int_using_JsonConvert_from_json_with_float
        {
            private static ANumber _result;
            private static string _json = "{'Number':-86400.0}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
            {
                _serializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                };

                _jsonSerializer = JsonSerializer.Create(_serializerSettings);

            };

            private Because _of = () => _result = (ANumber)JsonConvert.DeserializeObject(_json, typeof(ANumber), _serializerSettings);

            private It should_have_parsed_correctly = () => _result.Number.ShouldEqual(-86400);

        }

        public class When_deserializing_dateoffset_using_JObject
        {
            private static ADate _result;
            private static string _json = "{'date':'2015-04-14T00:00:00+02:00'}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
            {
                _serializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                };

                _jsonSerializer = JsonSerializer.Create(_serializerSettings);

            };

            private Because _of = () => _result = (ADate)JObject.Parse(_json).ToObject(typeof(ADate), _jsonSerializer);

            private It should_have_offset_of_two_hours = () => _result.Date.Offset.TotalHours.ShouldEqual(2);

            private It should_have_correct_UTC_datetime = () => _result.Date.UtcDateTime.ShouldEqual(new DateTime(2015, 04, 13, 22, 0, 0, DateTimeKind.Utc));

        }

        public class When_deserializing_dateoffset_using_JsonConvert
        {
            private static ADate _result;
            private static string _json = "{'date':'2015-04-14T00:00:00+02:00'}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
            {
                _serializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                    ContractResolver = new CamelCasePropertyNamesContractResolver(),
                };

                _jsonSerializer = JsonSerializer.Create(_serializerSettings);

            };

            private Because _of = () => _result = (ADate)JsonConvert.DeserializeObject(_json, typeof(ADate), _serializerSettings);

            private It should_have_offset_of_two_hours = () => _result.Date.Offset.TotalHours.ShouldEqual(2);

            private It should_have_correct_UTC_datetime = () => _result.Date.UtcDateTime.ShouldEqual(new DateTime(2015, 04, 13, 22, 0, 0, DateTimeKind.Utc));

        }

        public class When_deserializing_dateoffset_using_JObject_and_ToObject
        {
            private static ANumberWithADate _result;
            private static string _json = "{'number': -86400.0, 'date':'2015-04-14T00:00:00+02:00'}";

            public static JsonSerializerSettings _serializerSettings;

            public static JsonSerializer _jsonSerializer;

            private Establish _context = () =>
                {
                    _serializerSettings = new JsonSerializerSettings
                        {
                            DateFormatHandling = DateFormatHandling.IsoDateFormat,
                            DateParseHandling = DateParseHandling.DateTimeOffset,
                            DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
                            ContractResolver = new CamelCasePropertyNamesContractResolver(),
                        };

                    _jsonSerializer = JsonSerializer.Create(_serializerSettings);

                };

            private Because _of = () =>
                {

                    var reader = new Newtonsoft.Json.JsonTextReader(new StringReader(_json));

                    var jobject = _jsonSerializer.Deserialize<JObject>(reader);

                    _result = jobject.ToObject<ANumberWithADate>(_jsonSerializer);
                };

            private It should_have_parsed_correctly = () => _result.Number.ShouldEqual(-86400);

            private It should_have_offset_of_two_hours = () => _result.Date.Offset.TotalHours.ShouldEqual(2);

            private It should_have_correct_UTC_datetime = () => _result.Date.UtcDateTime.ShouldEqual(new DateTime(2015, 04, 13, 22, 0, 0, DateTimeKind.Utc));

        }
    }
}

**Comment by mgazza** [comment]
Related to https://github.com/JamesNK/Newtonsoft.Json/issues/45

**Comment by JamesNK** [comment]
JObject.Parse reads the date as a DateTime by default.

**Comment by mgazza** [comment]
Hi James. I am not using any default settings as you can see I pass the settings in for both calls. Also there is the issue with parsing a float into an integer which works one way and not another. These tests should all pass as far as i can see. 
Otherwise can you please rewrite the last test so it passes without having to need the extra step.
