### ISSUE TITLE
JsonConvert.SerializeObject is crashing in winodws xp sp3

### ISSUE THREAD

**Issue by bshemanth** [JamesNK/Newtonsoft.Json#738]
I am using below code to serialize the object using Json .

  jsonObject = JsonConvert.SerializeObject(NodeConfigurator.Instance, Formatting.None, new JsonSerializerSettings()
                    {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                    });

But in windows xp sp3 it is crashing & giving below exception.

 "An unhandled exception of type 'System.NotSupportedException' occurred in Newtonsoft.Json.dll". The exception message is "'CommandConverter' is unable to convert 'abc.RelayCommand' to 'System.String'". The InnerException is null.
But in windows 7 & above it is working correctly. If the structure is simple it is working good but if it is complected it is crashing. My json in windows 7 is like below & in windows xp it is crashing

{"LastSavedPath":"C:\Program Files (x86)\abc\uOPC Server\Lastclosed.uopf","Channels":[{"NewDeviceCommand":{},"DeleteChannelCommand":{},"ChannelDoubleClickCommand":{},"Device":[{"NewTagCommand":{},"DeleteDevice":{},"IsNewTagCommandVisible":true,"IsDeleteDeviceVisible":true,"IsNewDeviceCommandVisible":true,"Tags":[{"IsEnableApplyBtn":false,"TagName":"Tag1","TagAddress":"102364","TagNameimg":null,"TagRightImg":null,"TagDescription":"New","DataType":"Bool","ClientAccess":"Read Only","ScanRate":0,"NewTag":null,"NewGrpTag":null,"DeleteCurGrpTag":null,"MultiTagGen":null,"ScalingNone":true,"ScalingLinear":false,"ScalingSquareRoot":false,"RVRHigh":0,"RVRLow":0,"SVRData":"Double","SVRHigh":0,"SVRHighClamp":false,"SVRLow":0,"SVRLowClamp":true,"SVRUnits":null,"NegateScalVal":true,"Location":"DiscreteInputs","Address":"02364","Length":1},{"IsEnableApplyBtn":false,"TagName":"Tag2","TagAddress":"102365","TagNameimg":null,"TagRightImg":null,"TagDescription":"dfdfdf","DataType":"Bool","ClientAccess":"Read Only","ScanRate":0,"NewTag":null,"NewGrpTag":null,"DeleteCurGrpTag":null,"MultiTagGen":null,"ScalingNone":true,"ScalingLinear":false,"ScalingSquareRoot":false,"RVRHigh":0,"RVRLow":0,"SVRData":"Double","SVRHigh":0,"SVRHighClamp":false,"SVRLow":0,"SVRLowClamp":true,"SVRUnits":null,"NegateScalVal":true,"Location":"DiscreteInputs","Address":"02365","Length":1}],"DeviceModel":"Modbus","DeviceName":"Device1","AsciiDeviceID":"5","AsciiDeviceIDType":"Decimal","EtherNetDeviceID":null,"ScanMode":"","ConnectionTimeout":3,"ScanRate":0,"IsAddedFirstDevice":false,"RequestTimeout":1000,"FailAfterSuccTimeout":3,"InterReqDelay":0,"EnableAutoDeviceDemotion":false,"DemotAftSuccFailure":0,"DemotForMS":0,"DiscardWriteReq":true,"StartUp":"Do not generate on startup","Action":"Do not overwrite, log error","PortNumber":"502","IPProtocol":"","AddtoGroup":0,"AllowAutoGenSubGrp":true,"UseZeroBasAdd":true,"UseZeroBitAddReg":false,"UseHoldRegBitMask":false,"UseModFun06RegWrite":false,"SingleRegisterWrites":"0","UseModFun05CoilWrite":false,"singleCoilWrites":"0","ClientPrivilege":"Read/Write","ModbusDeviceBaseAddress":"1","DefaultModByteOrd":true,"FirstWrdLowin32BitDT":true,"firstWordLowIn32Bit":"1","ByteOrder":"Big-endian","FirstDWrdLowin64bitDT":false,"firstDwordLowIn64Bit":"0","ModiconbitOrd":true,"LongasDblePrsUD":false,"CoilOutput":32,"CoilInput":32,"RegInternal":32,"RegHolding":32,"PerBlockRead":false,"CloseTCPSocTimeout":false,"VariableImport":null,"VariableImportBTN":null,"IncludeDescription":true,"DeactivateTagIllAddrExe":true,"RejectRepMsg":false,"UseModTCPFrame":true,"LeadingByte":0,"TrailingByte":0,"ImportFile":null,"ImportFileBTN":null,"SelectObjs":null,"FilterOptProp":false,"CreateTagasRWAllowed":false,"USeObjNameTagGrpName":false,"BitsperRegister":"16","IsModBusTcpIpSelected":false,"IsScanModeTextBoxEnable":true,"IsRTUSelected":true,"IsSelected":true}],"PageVisite":false,"ChannelName":"Channel1","DeviceDriver":"Modbus ASCII Serial","EnableDiagnostic":true,"VirtualNetwork":"None","TransactionsPerCycle":0,"NetworkMode":"Load Balanced","PhysicalMedium":"COM Port","ReadProcessing":"Ignore","ComID":"6","BaudRate":"9600","Databit":"7","Parity":"Even","Stopbit":"1","FlowControl":"None","NetworkAdapter":"Default","ReportConnErr":true,"reportConnectionErrors":"1","CloseConnWnIdle":true,"closeConnectionWhenIdle":"1","SecofIdleTime":0,"WriteAllTags":false,"LatesValNonboolTags":false,"LatesvalAllTags":true,"DutyCycle":0,"NonNormalizedValue":"","SingleSocket":true,"MoreSocket":false,"MaxSocketsperDevice":0,"PortNumber":"","IPProtocol":"","SerializePortsetting":true,"OperationCommunications":false,"EtherNetSettings":false,"IsTagListViewVisible":true,"IsChannelListViewVisible":true,"ChannelSelectedItem":null,"IsChannelSelected":false}]}

**Comment by JamesNK** [comment]
Ask on stackoverflow
