### ISSUE TITLE
pkgconfig

### ISSUE THREAD

**Issue by rapgro** [JamesNK/Newtonsoft.Json#742]
Please add support for pkgconfig. The following is a template for the .pc file.

```
# pkgconfig
mkdir -p %{buildroot}/%{_libdir}/pkgconfig
cat <<EOT >>%{buildroot}/%{_libdir}/pkgconfig/%{name}.pc
Name: %{libname}
Description: %{summary}
Version: %{version}
Requires: mono 
Libs: -r:%{_monodir}/%{name}/%{libname}.dll
Libraries=%{_monodir}/%{name}/%{libname}.dll
EOT
```

**Comment by JamesNK** [comment]
I don't know what this is. I'm happy with providing a zip and nuget file.

**Comment by rapgro** [comment]
I have built a package in Fedora Linux for usage with Mono. Pkgconfig is nice in MonoDevelop.
http://www.freedesktop.org/wiki/Software/pkg-config/
http://www.monodevelop.com/
