### ISSUE TITLE
Losing source timezone information on deserialization 

### ISSUE THREAD

**Issue by AndyHsuTW** [JamesNK/Newtonsoft.Json#744]
I know this issue seems same as #45 , but i don't know why this issue still remain while i am using v7.0.1.
I am deserialize jObject which contains iso datetime string, the timezone offset changed to my local timezone after deserialize even i use DateTimeZoneHandling.RoundtripKind.
Since the timezone changed after deserialize jObj, i can not get source timezone after i get the date attribute inside the jObj.

Here is my example code:

var serializerSettings = new JsonSerializerSettings
            {

                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
            };
string dateJObj = "{\"datTransBegin\":\"2015-11-30T06:44:22.000-05:00\"}";
JObject testJobj = JsonConvert.DeserializeObject<JObject>(dateJObj, serializerSettings);

after that, below is the result of testJobj:
testJobj = {
  "datTransBegin": "2015-11-30T19:44:22+08:00"
}
![json net_timezone_issue](https://cloud.githubusercontent.com/assets/16345050/11888571/d3df4b50-a579-11e5-9fc9-2b45a0284496.png)

**Comment by AndyHsuTW** [comment]
After look into the source code, turned out the JsonSerializerSettings need to set DateParseHandling = DateParseHandling.DateTimeOffset to preserve the source timezone.

I think the DateParseHandling should default to DateTimeOffset if DateTimeZoneHandling set to RoundtripKind. Otherwise DateTimeZoneHandling.RoundtripKind always work as DateTimeZoneHandling.Local

Please feel free to correct me, thanks.

**Comment by megakid** [comment]
I think you're right, would like this to be the default behaviour

**Comment by JamesNK** [comment]
No can do, it's too be a breaking change.

**Comment by oliverjanik** [comment]
@JamesNK and it's wrong
