### ISSUE TITLE
nameof expression in .net 4 or older

### ISSUE THREAD

**Issue by pischke** [JamesNK/Newtonsoft.Json#745]
Hello James,

in one of your last commits you added the nameof expression to source. So there is no possibility to compile under .Net 4 or lower.

Can we please fix this. Thanks.

**Comment by henkmollema** [comment]
It has nothing to do with .NET 4, just with the C# compiler. Visual Studio 2015 ships with the new Roslyn compiler, which supports the `nameof` operator. It's possible to use Roslyn in VS2013 too, not sure how though.

**Comment by JamesNK** [comment]
Yeah, VS2015 will be required to compile going forward.
