### ISSUE TITLE
Feature Request: Fluent Converters 

### ISSUE THREAD

**Issue by Ashtonian** [JamesNK/Newtonsoft.Json#748]
Fluent converters for serialization would be a wonderful alternative to using attributes and having to create another poco to keep the attributes out of the model. Something similar to the syntax described here: https://stackoverflow.com/questions/26801453/fluent-converters-mappers-with-json-net

If there is an extension point this could be added to and someone could provide an example i'd be glad to dive in!

**Comment by JamesNK** [comment]
I don't want to add this to the core library. Someone could create it as its own NuGet library over the top of the existing API.

**Comment by shatl** [comment]
+1 That would be really nice to have it in the light of new System.Text.Json coming in. 

I'm trying to ship a lightweight package with contracts without dependency on serializer. 

@JamesNK As I understand key classes to look at are `JsonContract` and DefaultContractSerializer ?
