### ISSUE TITLE
Serialization and deserialization with TypeNameHandling.All looses information about Guid type

### ISSUE THREAD

**Issue by centur** [JamesNK/Newtonsoft.Json#762]
Hi,
there might be a bug in SerializeObject when settings have ```jsonSerializerSettings.TypeNameHandling = TypeNameHandling.All```

Here is the small LinqPad repro of this issue
[JsonNetBug.zip](https://github.com/JamesNK/Newtonsoft.Json/files/70356/JsonNetBug.zip)

The output of the attached code is the following:

>======Original Dictionary :
>    I'm Guid - System.Guid
>======Deserialized Dictionary :
>    I'm Guid - System.String

Although Json.NET can successfully serialize and deserialize Guid when it's an object property, it looses type (struct in this case) information when it's in a collection.

**Comment by gabikliot** [comment]
Am I to understand that this is "by design" according to https://github.com/JamesNK/Newtonsoft.Json/issues/728?

I tried to wrote a converter to Guid, but it did not work. 
Could you please provide more/exact details of how this can be fixed?

**Comment by centur** [comment]
Is there any chance that this issue can be addressed and fixed or @JamesNK  can take a look on the code above with custom converters and explain why it didn't work

**Comment by JamesNK** [comment]
It's by design. Include type information for every primitive value would create a mess.

I'm guessing the converter didn't work because when there is no type data then objectType will be System.Object and this won't pass:

```
    public override bool CanConvert(Type objectType)
    {
        return (objectType == typeof(Guid));
    }
```
