### ISSUE TITLE
Platform Standard isn't supported

### ISSUE THREAD

**Issue by tenor** [JamesNK/Newtonsoft.Json#763]
The new platform standard according to this [announcement](https://github.com/aspnet/Announcements/issues/98) is not supported in the latest Json.NET version (8.0.1-beta3).

**To repro:**
1- Create a new PCL project targeting .Net 4.5 using VS 2015.
2- Add a project.json file with the following content:
```
{
  "dependencies": {
    "Newtonsoft.Json": "8.0.1-beta3"
  },

  "frameworks": {
    "dotnet5.2": {}
  }
}
```
3- Run `nuget restore` using the latest version of nuget (3.3.0)

Output:
```
Installing Newtonsoft.Json 8.0.1-beta3.
Newtonsoft.Json 8.0.1-beta3 is not compatible with .NETPlatform,Version=v5.2.
Some packages are not compatible with .NETPlatform,Version=v5.2.
```

**Remedy:**
On inspecting the Json.Net Nuget package, I see the `project.json` file is not being bundled under \content.
I don't see how the Nuget packages are built in the source tree but I think this is caused by:
1. The package wasn't packed by newer versions of Nuget and/or 
2. The project.json file is not in the `Newtonsoft.Json.Portable.csproj`

**Comment by JamesNK** [comment]
Waiting for RC2 - https://github.com/JamesNK/Newtonsoft.Json/issues/618
