### ISSUE TITLE
Error getting value from 'Url' on 'BlueDragon.Core.Http.HttpParameter'

### ISSUE THREAD

**Issue by wangtingwei** [JamesNK/Newtonsoft.Json#765]
in some compute throw last exception,but other compute run success

[XmlType("restInterface")]
    [Serializable]
    public class HttpParameter : ICloneable
    {
....................
....................
[XmlIgnore()]
        public Uri Url
        {
            private set { }
            get
            {
                if (logger.IsInfoEnabled)
                {
                    logger.Info(this.UriAbsolutePath+"==="+this.UriScheme+"====="+this.QueryString+"==="+this.UriAuthority);
                }
                URIBuilder builder=new URIBuilder().setScheme(this.UriScheme).setPath(this.UriAbsolutePath).setQuery(this.QueryString);
                IList<string> tupe = this.UriAuthority.Split(':');
                if (tupe.Count > 1)
                {
                    builder.setHost(tupe[0]).setPort(Int32.Parse(tupe[1]));
                }
                else
                {
                    builder.setHost(this.UriAuthority).setPort(-1);
                }
                return builder.build();
            }
        }

................
................
}

**Comment by JamesNK** [comment]
Ask on stackoverflow
