### ISSUE TITLE
Still Getting "Unable to find constructor for type" error

### ISSUE THREAD

**Issue by vbisbest** [JamesNK/Newtonsoft.Json#767]
Getting this error when "linking all assemblies" in Xamarin project (perhaps other languages as well).  This did not use to happen before Json.Net 7.   Only workaround is to set linking to "SDK assemblies only" but this makes the binary size huge.   Hopefully you can fix this.  Thx.

**Comment by JamesNK** [comment]
Sorry I don't how Xamarin works. Raise it with them.
