### ISSUE TITLE
JsonConverterAttribute with StringEnumConverter and CamelCaseText true

### ISSUE THREAD

**Issue by mikehaas763** [JamesNK/Newtonsoft.Json#769]
This issue is potentially a question and also a suggestion.

I would like to use an attribute to specific that one single property of type enum on a model being serialized should be serialized to text. That's easy enough.

```csharp
[JsonConverter(typeof(StringEnumConverter))]
```

However, StringEnumConverter has a bool property CamelCaseText that will serialize the enum value to camelCase. I don't have any way to set that using JsonConverterAttribute as is. There may be an better way to do what I'm trying to do and if so please just point me in the right direction.

With that said, my suggestion is to add a new constructor to StringEnumConverter.

```csharp
public StringEnumConverter(bool camelCaseText) : this()
{
    CamelCaseText = camelCaseText;
}
```

Then I can use JsonConverterAttribute
```csharp
[JsonConverter(typeof(StringEnumConverter), true)]
```

**Comment by JamesNK** [comment]
Good idea. Done https://github.com/JamesNK/Newtonsoft.Json/commit/0311bc0f245baac2cbc5487d92bd50cc8d45fca9

**Comment by GnanaPriyaNamasivayam** [comment]
Hi @mikehaas763 ,
 Am using same entry template for multiple fields. I have binded **ValueType** property 

Model.cs
 [JsonConverter(typeof(StringEnumConverter))]
        public JSchemaType ValueType { get; set; }

ViewModel.cs
 if (Name== "FieldHeight")
 {
        uiProperty.ValueType = Newtonsoft.Json.Schema.JSchemaType.Number;
 }
View
 <EntryControl x:Name="entry" 
                                         IsTextPredictionEnabled="True"
                                         Text="{Binding Value}" 
                                         **Keyboard="{Binding ValueType,Converter={StaticResource KeyboardValueTypeConverter}}"**>
                
</EditorEntryControl>

Converter.cs
   [JsonConverter(typeof(StringEnumConverter), true)]
    public class KeyboardValueTypeConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var defaultValue =Keyboard.Default;
            if (value != null)
            {
                var valueType = (string)value;
                if (string.Equals(valueType, "FieldHeight"))
                    return Keyboard.Numeric;
                else
                    return defaultValue;
            }
            else
                return defaultValue;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

Above does not work. Am i done anything wrong.
