### ISSUE TITLE
VS2105 Crashes when adding Newtonsoft.Json package

### ISSUE THREAD

**Issue by marqdouj** [JamesNK/Newtonsoft.Json#770]
I had no problems 2 weeks ago adding the package, but I just rebuilt my machine and installed the latest version of VS2105.  Now when I try and add the package to any non-asp.net project VS2105 crashes (no message) and restarts.  I can add the package to any asp.net project just fine.

The crash happens after the install completes; I can see the dll referenced and the package manager shows a green checkmark (installed) and the output window says it installed.  When VS2105 restarts and I open the project the dll reference is gone but the package manager indicates it is installed.

**Comment by JamesNK** [comment]
Sounds like a problem with VS or NuGet. Recreate the issue in the NuGet project.
