### ISSUE TITLE
Support for multiple constructors for deserializing objects based on available fields

### ISSUE THREAD

**Issue by bluemmc** [JamesNK/Newtonsoft.Json#776]
I really like Newtonsoft.Json's secret support for immutable objects but I would like better support for deserializing incomplete/full objects based on available name/value-pairs in json input. 

Specifically it would be nice if Newtonsoft.Json could handle multiple constructors and use the largest constructor that match available  name/value-pairs in that json input. That way I can construct objects differently based on what input is available.

**Comment by JamesNK** [comment]
I'm happy with the current constructor approach. It's more than complicated enough already.
