### ISSUE TITLE
Serialize an Array declared as IEnumerable when TypeNameHanding is set to Auto

### ISSUE THREAD

**Issue by davideicardi** [JamesNK/Newtonsoft.Json#779]
I have posted the following question on stackoverfow:

http://stackoverflow.com/questions/34662966/json-net-serialization-of-ienumerable-with-typenamehandling-auto

I think it is a bug...
Why IEnumerable is not serialized as json array? I think it should also when TypeNameHandling is set to auto.

**Comment by JamesNK** [comment]
That's expected behavour.

**Comment by dainius-bekeris** [comment]
Hello.
We have similar issue with type name handling set to Auto. For us it's too much to do as suggested on stackoverflow - set type name handling on every array property in all contracts...

I see it is possible to solve issue by extending type name handling a bit. If Auto flag would be possible to split to AutoArray and AutoObject then we would be able to disable adding type names to arrays but still keep $type in our objects. And this is what we really need - $type shall appear only on objects, we want any collection always appear as JSON array.

Is it possible to add such change?
