### ISSUE TITLE
Better way to serialize inherited types without full type name

### ISSUE THREAD

**Issue by smartnose** [JamesNK/Newtonsoft.Json#785]
Currently, serializing inherited types (polymorphic data) through JSON would need to write out the full type name. This becomes a problem working with Big Data projects, because if we refactor/renaming existing code base, the serialization tends to break. 

E.g. If I have a class:
Inherted: Base {
}

Json.net would serialize it to { $$type: "very.long.name.space.Inherited", the rest of the JSON. }

This makes it hard to keep the code base agile without having to purge the entire production data.

A more robust way is to allow a custom defined mapping from a set of stable type names to the internal type information, in a way similar to the trick used by Azure WebJobs SDK team:

https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Protocols/PolymorphicJsonConverter.cs

In this solution, they essentially created a custom converter that builds a map <string, Type>  to map from a state type name to the internal clr Type. The stable type name is specified through a custom JsonTypeNameAttribute

[JsonTypeName("inherited")]
Inherited: Base
{
}

So the JSON becomes  { $$type : "inherited", REST of JSON }

Later, when refactoring the code, I can change the class name or namespace, but keep JsonTypeName value intact, then serialization would still work.

However, there are a number of improvements I would like to do for this converter. Will give more details if this is deemed as a worthy issue to resolve.

**Comment by JamesNK** [comment]
You can already do this with a SerializationBinder.
