### ISSUE TITLE
Deserialization issue with wrapped BindlingList

### ISSUE THREAD

**Issue by ghostofcain** [JamesNK/Newtonsoft.Json#787]
Hi,

The steps to reproduce the problem are outlined in my SO question: http://stackoverflow.com/questions/34860022/de-serialization-issue-in-json-net-when-using-bindinglist

Basically, the problem is that with the TypeNameAssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Simple, I'm unable to deserialize a type of Wrapper<BindlingList<T>> whereas it's possible to do so with a simple List<>, i.e. Wrapper<List<T>>. (Wrapper is just a generic class containing the underlying item).

I don't quite understand why this would fail but if i change the FormatterAssemblyStyle.Simple to Full, it works. Ideally it would work with simply as well which is why I'm reporting the issue here as a bug.

Regards,

**Comment by JamesNK** [comment]
It looks like .NET just can't find that type with out a fully qualified assembly. I'm not sure what I can do to fix that.
