### ISSUE TITLE
Portable implementation of JsonSerializerSettings does not contain Binder setter

### ISSUE THREAD

**Issue by kordan11** [JamesNK/Newtonsoft.Json#788]
I am using Xamarin while developing a multi-platform solution, and I would like to have a settings definition in portable code so I can share it wherever I need it. It seems though that when I try to construct my settings in portable code I get a method not found exception on the Binder setter.

I have constructed a simple solution that demonstrates the problem. The settings provider in the portable library throws the method not found exception, while the one in the normal library does not. See the attached dropbox link.

https://www.dropbox.com/sh/zh38zdd82np5mz9/AADOVRbg9_pBCTum53MUQFvCa?dl=0

**Comment by JamesNK** [comment]
That's because System.Runtime.Serialization.SerializationBinder isn't available in portable. The property returns Newtonsoft.Json.SerializationBinder instead.
