### ISSUE TITLE
Deserialize untrusted string

### ISSUE THREAD

**Issue by bbbush** [JamesNK/Newtonsoft.Json#790]
HP Fortify complains if a string is from StreamReader.ReadToEnd. The stream can be from network or file. The message looks like https://gist.github.com/bbbush/d35abb80dc1bed6dd16a

A way to avoid warning is to use JsonSerializer.Deserialize<T> which does not use string. However that is not as convenient as JsonConvert. 

FYI (in System.Web.Script.Serialization) JavaScriptSerializer.Deserialize<T> accepts string but does not have this issue.

**Comment by JamesNK** [comment]
Use JsonSerializer. It mitigates what the tool is complaining about.
