### ISSUE TITLE
Setting a TraceWriter results in JsonWriterException - TraceWriter broken ?

### ISSUE THREAD

**Issue by bluemmc** [JamesNK/Newtonsoft.Json#793]
I have a ASP.NET 5 RC1 web application that uses Newtonsoft.Json v8.0.2 and a JsonConverter internally.

If I do not send a TraceWriter everything works (I get my json output) and my SerializerSettings.Error handler is NOT called (all is OK). 

If I set a TraceWriter (SerializerSettings.TraceWriter) to trace what is going on, the app breaks and mySerializerSettings.Error handler gets called with an Newtonsoft.Json.JsonWriterException: Token String in state Object would result in an invalid JSON object. Path 'data'.

Since everything appears to work just fine without the TraceWriter, I suspect the error is introduced because of some sideeffect by enabling the TraceWriter ?

**Comment by JamesNK** [comment]
I have tests for that so I need you to add a simple repo of what you're serializing to figure it out what is happening in your situation. The class, it's values, converter and the serializer settings, etc
