### ISSUE TITLE
Stream Closes on error

### ISSUE THREAD

**Issue by awb99** [JamesNK/Newtonsoft.Json#794]
I have a networkstream that sends Json Object after Json object. I use "SupportMultipleContent" which basically reads Json object after Json object; without this option I would have invalid
JSon context.

Now sometimes what happens is I get from the network card a partial json objet, and this
triggers Exceptions  in "Deserialize" the data. 

So far so good.

I also have specified "CloseInput = false".  And on this exceptions it is closing the stream. So
I have no way of rolling back to the last position that was read after the network stream has
received addtional data. I believe this is incorrect behavior.

This is the Code:

	public static void ProcessStreamNewtonSoft (MLogger logger, Stream readStream, Data dataCallback)
		{
			using(var sr = new StreamReader(readStream))
			{
				try
				{
					using(var reader = new Newtonsoft.Json.JsonTextReader(sr))
					{
						reader.SupportMultipleContent = true;
						reader.CloseInput = false;
						
						var ser = new Newtonsoft.Json.JsonSerializer();
						ser.CheckAdditionalContent= false;
						while(reader.Read())
						{
							try{
								var data = ser.Deserialize<TcpFeedData>(reader);
								dataCallback (data);
							}
							catch (Exception ex)
							{
								logger.Info ("err..");
							}
						}
					}
				}
				catch (Exception ex)
				{
					logger.Info ("err..");
				}
			}
		}

Regards
Andreas

**Comment by JamesNK** [comment]
I tested and it doesn't - https://github.com/JamesNK/Newtonsoft.Json/commit/04f7bb5d659404498972d5f2761b49b7f55f3924
