### ISSUE TITLE
Issue while deserializing object having double quotes in the value.

### ISSUE THREAD

**Issue by dev-Varun** [JamesNK/Newtonsoft.Json#795]
This is my json string that i want to deserialize. But runs into exception due to those double quotes in Content property's value for img src. 
"{\"ArticleId\":23,\"Title\":\"Testing\",\"Content\":\"img src=\"http://localhost:29647/WebRepository/ArticleContentPictures/vroon_23.jpg\"/>\"}"

**Comment by IanYates** [comment]
That's not really JSON.NET's fault.  A web browser's JSON.parse(...) will also fail on it for the same reason.

I'd suggest either
a) Fix the encoder; or
b) If you know it's going to break on src="...", use some regex to change to using ' rather than " for the img src
