### ISSUE TITLE
ExpandoObjectConverter not part of portable library in 8.0.2

### ISSUE THREAD

**Issue by dkackman** [JamesNK/Newtonsoft.Json#796]
I've got a portable class library (vs.net 2015. targeting .net 45, aspnet 5, win8, winphone8.1, winphone silverlight 8) that uses ExpandoObjectConverter. Updating from 7.0.1 to 8.0.2 give me a type or namespace cannot be found for that type. 

namespace directives using `Newtonsoft.Json;` and `using Newtonsoft.Json.Converters;` are in the [code file in question](https://github.com/dkackman/DynamicRestProxy/blob/master/DynamicRestProxy.Portable/HttpClientExtensions.cs)

steps to repro:
1 - create Portable class library project in vs.net 2015
2 - change library targeting from .net 46 and win10 to .net 45 and win8
3 - add json.net 8.0.2 reference from nuget.org
4 - add this code

    public class Class1
    {
        private Newtonsoft.Json.Converters.ExpandoObjectConverter converter;
    }

**Comment by JamesNK** [comment]
For some reason VS is referencing the .NET 4.0 portable library. The .NET 4.5 portable library has it.
