### ISSUE TITLE
Order of keys should not matter in JSON comparision

### ISSUE THREAD

**Issue by amitavmohanty01** [JamesNK/Newtonsoft.Json#797]
[TestMethod]
        public void TestJObjectEquality()
        {
            string ob1 = @"{""key1"":""1"",""key2"":""2""}";
            // Star wars would be so short if such a person was there.
            string ob2 = @"{""key2"":""2"",""key1"":""1""}";
            JObject j1 = JObject.Parse(ob1);
            JObject j2 = JObject.Parse(ob2);
            Assert.AreEqual(j1, j2);
        }

This test is failing. Is it by design ? I have not read documentation for JSON comparision but I think it would be nice to have such a comparision anyway.

**Comment by dbc2** [comment]
You can use [`JToken.DeepEquals(j1, j2)`](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_DeepEquals.htm) to check equivalence of json objects.
