### ISSUE TITLE
Invalid cast exception

### ISSUE THREAD

**Issue by VThayyil** [JamesNK/Newtonsoft.Json#798]
public partial class Test
        {
            public string last_name { get; set; }
            public string first_name { get; set; }
        }

jsonStr = "'{\"FIRST_NAME\":\"Patty\",\"LAST_NAME\":\"Lopez\"}'"

Test test = JsonConvert.DeserializeObject<Test>(jsonStr);

Error converting value "{"FIRST_NAME":"Patty","LAST_NAME":"Lopez"}" to type 'Mvc.Controllers.patronsController+Test'. Path '', line 1, position 44.

**Comment by VThayyil** [comment]
Error converting value "{"FIRST_NAME":"Patty","LAST_NAME":"Lopez"}" to type 'Mvc.Controllers.patronsController+Test'. Path '', line 1, position 44.

**Comment by JamesNK** [comment]
That's an escaped string.

**Comment by VThayyil** [comment]
Got it Thanx
