### ISSUE TITLE
Json.NET generated dynamic objects don't work with Nancy

### ISSUE THREAD

**Issue by ralfw** [JamesNK/Newtonsoft.Json#805]
I'd like to use Json.NET with Nancy's Super Simple View Engine. I need to pass a _dynamic_ view model to a view, e.g.:

```
public class SomeModule : NancyModule
{
    public SomeModule()
    {

        Get["/test"] = p => {
            dynamic vm = Newtonsoft.Json.JsonConvert.DeserializeObject("{\"Name\":\"Mary\"}");
            return View["index.html", vm];
        };
    }
}
```

Deserialization to `dynamic` works fine in general with Json.NET. But rendering with the view engine does not :-( The model reference `@Model.Name` in the `index.html` template does not pick up the `Name`.

The view engine supports only the following object types:

- Plain POCO objects
- `IDictionary<string, object>`
- `IDynamicMetaObjectProvider`
- `DynamicDictionaryValue`
- `DynamicObject`

As it seems, the object returned from `DeserializeObject` does not conform to that. How come? The types supported to me don't seem to be exotic but rather straightforward.

Wouldn't it be great for Json.NET to produce dynamic objects which conform to such ordinary interfaces to be more widely usable?

**Comment by JamesNK** [comment]
Json.NET dynamic works everywhere else. You're going to need to be specific about why nancy doesn't work. I don't know anything about nancy.

**Comment by ralfw** [comment]
Well, I'm just using Nancy. I can only report what I perceive.

This works:
```
dynamic vm = new ExpandoObject();
vm.Name = "Mary";
return View["index.html", vm];
```

This works:
```
dynamic vm = Codeplex.Data.DynamicJson.Parse("{\"Name\":\"Mary\"}");
return View["index.html", vm];
```

This does NOT work:
```
dynamic vm = Newtonsoft.Json.JsonConvert.DeserializeObject("{\"Name\":\"Mary\"}");
return View["index.html", vm];
```

When I asked the Nancy guys what the reason could be, they said, "The view engine supports reflection and a couple of interfaces to get at fields/properties of view models." So when I put `@Model.Name` in the HTML view to be replaced by the actual value "Mary" the view engine checks the view model `vm` by these means:

* Plain POCO objects
* `IDictionary<string, object>`
* `IDynamicMetaObjectProvider`
* `DynamicDictionaryValue`
* `DynamicObject`

Since `ExpandoObject` and whatever DynamicJson returns lead to working code and Json.NET does not, there must be a difference between what they deliver and what Json.NET delivers as a dynamic object.

The problem is easy to reproduce (see code above).

Since I'm a user of both technologies, I'm just asking: can something be done about this?

To me it looks like Nancy making a pretty good offer in terms of what they accept as interfaces. So maybe Json.NET could expand it's offer with regard to how it makes values available?

**Comment by JamesNK** [comment]
The Json.NET supports `IDynamicMetaObjectProvider`.
