### ISSUE TITLE
Issue serializing an object inherited from DynamicObject

### ISSUE THREAD

**Issue by aditya3889** [JamesNK/Newtonsoft.Json#807]
So, I have a class say Foo inherited from DynamicObject. The problem I'm trying to solve here is that I want all read/write properties on Foo should be Serialized and Deserialized back. So, now I have a custom resolver that does this:
```
public class CustomResolver : DefaultContractResolver
 {
         protected override IList<JsonProperty> CreateProperties(Type type, Newtonsoft.Json.MemberSerialization memberSerialization)
        {
            IList<JsonProperty> properties = base.CreateProperties(type, memberSerialization);
            foreach (var property in properties)
            {
                if (property.Readable && property.Writable)
                {
                    property.Ignored = false;
                }
            }

            return properties;
        }
}
```

The above custom serializer, serializes all properties that are inherited from a type other than DynamicObject but for DynamicObject the check for HasMemberAttribute superseedes the check for Ignored (if it's set to false) as can be seen below:
[https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L897]

Looking at the code/documentation, shouldn't the line be if (!property.Ignored) instead unless I'm missing something obvious?

**Comment by MerickOWA** [comment]
From http://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Dynamic

> Dynamic objects are serialized as JSON objects. A property is written for every member name returned by DynamicMetaObject.GetDynamicMemberNames(). **A dynamic object's normal properties aren't serialized by default but can be included by placing the JsonPropertyAttribute on them**.

So, if you really want to use a IContractResolver to change this behavior, just use

		public class CustomResolver : DefaultContractResolver
		{
			protected override IList<JsonProperty> CreateProperties(Type type, Newtonsoft.Json.MemberSerialization memberSerialization)
			{
				IList<JsonProperty> properties = base.CreateProperties(type, memberSerialization);
				foreach (var property in properties)
				{
					//pretend like every property has the [JsonProperty] attribute on it
					property.HasMemberAttribute = true;
				}

				return properties;
			}
		}
