### ISSUE TITLE
Strange behavior enumerating the results of ExtensionDataGetter

### ISSUE THREAD

**Issue by MerickOWA** [JamesNK/Newtonsoft.Json#811]
When trying to access the extension data of a JObjectContract created by the DefaultContractResolver, the enumerable behaves strangely if it is used multiple times.

For example, calling a LINQ "Any()" call will cause subsequent enumerations to not retrieve the first item.  This is due to the how the internal DictionaryEnumerator<,> class was wrapping the IEnumerable<,> returned by the extension data property.

Inital attempt to fix by simply adding a Reset() call prior to returning from DictionaryEnumerator<,>.GetEnumerator() fails as not all wrapped IEnumerable<,> can be reset (ie: JObject)

Instead, I wrote the fix to use the yield return syntax inside DictionaryEnumerator<,>.GetEnumerator() which is the most flexible solution.  It allows for multiple calls to GetEnumerator() as well as allowing those multiple enumerations to be done at the same time.

The downside is an extra allocation now takes place.

Possible alternative is to have DictionaryEnumerator<,> contain 2 private fields: one for the wrapped IEnumerable and one for the current IEnumerator.  This would remove the extra allocation at the sacrifice of slightly more memory usage (2 fields instead of 1), but would fail if multiple iterations were done at the same time.

**Comment by JamesNK** [comment]
Nice find. One extra allocation doesn't matter here. The foreach could be boxing many keys and/or values.

Fixed.
