### ISSUE TITLE
Parser accepts trailing comma's

### ISSUE THREAD

**Issue by ewoutkramer** [JamesNK/Newtonsoft.Json#818]
The parser accepts a trailing comma after the last member of a complex object. According to the spec at json.org, this should not be allowed.  Is this on purpose?  Is this configurable?

**Comment by JamesNK** [comment]
It is on purpose. It is not configurable. You could create a strict version of JsonTextReader.

**Comment by fenxu** [comment]
@JamesNK  How to create strict version of JsonTextReader to check the trailing comma? My code as below and it won't throw exception
```
            var jsonString = @"{ 'CPU': 'Intel',}";
            var reader = new JsonTextReader(new StringReader(jsonString));
            var t =  JToken.ReadFrom(reader);
```

**Comment by ewoutkramer** [comment]
The problem is that sometimes you need to be compliant to industry standards (like http://hl7.org/fhir), which require you to flag this as an error.  Additionally, these are the kinds of standards that many developers (here in healthcare) have to be compliant to.  As a consequence, this is not just a problem for me, but for many .NET developers with a need to be compliant - and so this workaround is forcing a considerable group to do this heavy lifting!

**Comment by veleek** [comment]
Yup, totally agree that it's not an ideal solution and it would be nice if there was something built in.  But I understand that there IS a performance implication to having it in place and in the end it's up to James to decide whether he wants it included in the library or not.  

Maybe it would be possible to get a blessing from @JamesNK to submit your own implementation of StrictJsonTextReader to share it with the community.  Either that or maybe changing the underlying implementation to make it a bit easier to override this type of behavior.  Thoughts?

**Comment by JamesNK** [comment]
Feel free to submit a PR with a setting added to JsonTextReader to enable strict mode. I suspect it would be a non-trivial amount of work to handle all use cases and unit test them.

Off the top of my head:

* Property quotation
* NaN, Infinity, -Infinity
* Constructors
* Multi-line strings
* Trailing commas
* Single-line comments
* Multi-line comments
* Octal integers
* Missing leading zeros

**Comment by ASmoliak** [comment]
Just wanted to add I use this library for my automation tests. Our automation OK'd the trailing commas, We've had a critical issue in production that other parsers fail duo to said trailing comma, that this library appears to ignore by design. Standards exist for a reason, and if you don't follow them, you hurt your ability to communicate with other libraries. 

I urge you guys to allow to at least configure the strictness. I wish we could put someone to do it ourselves, but can't.
