### ISSUE TITLE
JValue underlying type is lost on serialization

### ISSUE THREAD

**Issue by Torvin** [JamesNK/Newtonsoft.Json#826]
```C#
var value = new JValue(new Guid());
Assert.AreEqual(JTokenType.Guid, value.Type); // ok
var value2 = JsonConvert.DeserializeObject<JValue>(JsonConvert.SerializeObject(value));
Assert.AreEqual(JTokenType.Guid, value2.Type); // expected: Guid, but was: String
```
Using `JsonSerializerSettings` with `TypeNameHandling = TypeNameHandling.All` does not help. Same happens with `int` - it gets converted to `long` after serialisation/deserialisation.

This makes objects that contain `JToken`s inside completely broken after the deserialisation for me.

**Comment by Torvin** [comment]
Even simpler test:
```C#
var token1 = new JValue(Guid.NewGuid());
var token2 = JToken.FromObject(token1);
Assert.IsTrue(JToken.DeepEquals(token1, token2)); // false
Assert.AreEqual(token1.Type, token2.Type); // expected: Guid, but was: String
```

**Comment by Torvin** [comment]
The main question I have is, why do we even have a `JTokenType.Guid` type? It is not a 
"native" JSON type and it breaks `JToken.DeepEquals`. Is there a need for it?

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/092dc7da58dc1af088a83b6537d7b2e8527b3de3
