### ISSUE TITLE
Exceptions in JsonTextWriter on 8.0.2 with buffer pool

### ISSUE THREAD

**Issue by rynowak** [JamesNK/Newtonsoft.Json#835]
See https://github.com/aspnet/Mvc/issues/4213 - this is a customer reported bug on MVC, but we believe this is a JSON.Net issue. The buffer pool changed recently to throw when returning a buffer of non-standard size - it was definitely not created by the pool. https://github.com/dotnet/corefx/issues/5949

Relevant callstack:
```
System.Buffers.dll!System.Buffers.DefaultArrayPoolBucket<char>.Return(char[] buffer)
System.Buffers.dll!System.Buffers.DefaultArrayPool<char>.Return(char[] buffer, bool clearArray)    Microsoft.AspNetCore.Mvc.Formatters.Json.dll!Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonArrayPool<char>.Return(char[] array)
Newtonsoft.Json.dll!Newtonsoft.Json.JsonTextWriter.Close()
Newtonsoft.Json.dll!Newtonsoft.Json.JsonWriter.Dispose(bool disposing)
Newtonsoft.Json.dll!Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
Microsoft.AspNetCore.Mvc.Formatters.Json.dll!Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(System.IO.TextWriter writer, object value)
```

Note that this is throwing here: https://github.com/JamesNK/Newtonsoft.Json/blob/ce2a08dba228341742d96e8c8edfede6748d5bdc/Src/Newtonsoft.Json/JsonTextWriter.cs#L182 

Which means that `_writeBuffer` was initialized using `new char[...]` instead of a `pool.RentBuffer(...)`. This looks to be the culprit https://github.com/JamesNK/Newtonsoft.Json/blob/ce2a08dba228341742d96e8c8edfede6748d5bdc/Src/Newtonsoft.Json/Utilities/JavaScriptUtils.cs#L289

**Comment by JamesNK** [comment]
Looks like a Json.NET bug to me.

What version of System.Buffers causes this error and where can I find it?

**Comment by JamesNK** [comment]
Ok, latest version of System.Buffers on aspnetvnext does it.

**Comment by JamesNK** [comment]
Fixed - https://github.com/JamesNK/Newtonsoft.Json/commit/5ddbc508f0b9f19243076821c825a7f5056de4b1

**Comment by rynowak** [comment]
Thanks! :+1:
