### ISSUE TITLE
Using SelectTokens with inequality query dont return object/arrays

### ISSUE THREAD

**Issue by mrjwest** [JamesNK/Newtonsoft.Json#848]
I would like to report an behavior that might be considered inaccurate. Using inequality queries in the JsonPath value, ie. **$.[?(@.value!=null)]** or **$.[?(@.value!='string')]** will **not** return arrays or objects.

I've asked this question on stackoverflow and refer to more details with the following links:

[Stackoverflow question](http://stackoverflow.com/questions/36041621/issue-bug-using-selecttokens-with-jsonpath)
[Sample fiddle](https://dotnetfiddle.net/xpmzjW)

Is this an issue to be fixed or considered as correct behaivor?

Thanks in advance,
Jan

**Comment by mrjwest** [comment]
Finally figured out what was causing the .SelectTokens to ignore arrays and objects when using JSONPath. The issues occurs in [QueryExpressions.cs line 78][1]

    JValue v = r as JValue;


This will cause any JToken that is JObject/JArray to become **null** and hence being ignored when compared. My way of fixing this was to replace line 78 with the following code that handles JObject and JArray:

                JValue v = null;
                switch (r.Type)
                {
                    case JTokenType.Object:
                    case JTokenType.Array:
                        v = new JValue(r.ToString());
                        break;
                    default:
                        v = r as JValue;
                        break;
                }

This will ensure that JObject and JArray are returned when calling .SelectTokens. Please comment this solution if the approach has fallbacks and/or can be implemented. 

  [1]: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JsonPath/QueryExpression.cs#L78

**Comment by JamesNK** [comment]
Thanks for the example. I fixed it slightly differently but the result is the same - https://github.com/JamesNK/Newtonsoft.Json/commit/031222d4f4bd541e66f236329591f2427f835174
