### ISSUE TITLE
Feature request : PopulateObject for JObject

### ISSUE THREAD

**Issue by Shravan2x** [JamesNK/Newtonsoft.Json#850]
JObject has a `ToObject<T>()`. But it creates a new object only.

I have a case where a type takes constructor arguments that are then assigned to `readonly` variables. If a `JObject.PopulateObject(Object obj)` existed, I could instantiate the object with the values I want and then populate the other fields using it.

**Comment by JamesNK** [comment]
Why not use JObject.FromObject + Merge?

**Comment by Shravan2x** [comment]
Consider:

    private class TypeA
    {
        public string Val1 { get; }
        public string Val2 { get; set; }
    
        public TypeA(string val1)
        {
            Val1 = val1;
        }
    }

`JObject.FromObject(new TypeA("super")).Merge(JsonConvert.DeserializeObject("{\"Val2\":\"sub\"}"))` would leave me with a JObject, where I actually want a `TypeA`. I'd be glad if I could have something  neater like:

    TypeA original = JsonConvert.DeserializeObject("{\"Val2\":\"sub\"}").PopulateObject(new TypeA("super"));

**Comment by JamesNK** [comment]
Add ToObject<TypeA> at the end.

**Comment by Shravan2x** [comment]
The `ToObject<TypeA>()` does not assign Val1 as it has no setter i.e. running

    JObject res = JObject.FromObject(new TypeA("super"));
    res.Merge(JsonConvert.DeserializeObject("{\"Val2\":\"sub\"}"));
    TypeA typA = res.ToObject<TypeA>();
    Console.WriteLine("'" + typA.Val1 + "'\n'" + typA.Val2 + "'");

gives me:

    ''
    'sub'

since `Val1` does not get set.

**Comment by JamesNK** [comment]
Json.NET handles calling constructors. You get both values. I just tested.

**Comment by Shravan2x** [comment]
That's weird, Val1 is not set for me. Are you sure you didn't include a setter for Val1?

In case you need it, here's a paste of the full program : http://pastebin.com/F6jJ0kww

**Comment by JamesNK** [comment]
private class TypeA
    {
        public string Val1 { get; }
        public string Val2 { get; set; }

        public TypeA(string val1)
        {
            Val1 = val1;
        }
    }

    [Test]
    public void MergeCombinedWithSerialization()
    {
        JObject res = JObject.FromObject(new TypeA("super"));
        res.Merge(JsonConvert.DeserializeObject("{\"Val2\":\"sub\"}"));
        TypeA typA = res.ToObject<TypeA>();

        Assert.AreEqual("super", typA.Val1);
        Assert.AreEqual("sub", typA.Val2);
    }

**Comment by Shravan2x** [comment]
I got that working, but I think relying on the name of a constructor argument *name* for something important leaves any program very fragile. I think me and Joe Average would benefit greatly from a PopulateObject any day.

**Comment by IanYates** [comment]
The constructor parameter having a camelCase name for a PascalCase property is idiomatic C#.  Things like ReSharper, JustCode, CodeRush, etc also default to writing code that way.  Json.NET follows that convention quite well.
The code you posted in https://github.com/JamesNK/Newtonsoft.Json/issues/850#issuecomment-198181609 followed that convention but your pastebin code did not.
