### ISSUE TITLE
trouble with deserializing an complicated ISerializable

### ISSUE THREAD

**Issue by epsi1on** [JamesNK/Newtonsoft.Json#851]
Hi,
I have a complicated ISerializable object and when i try to deserialize with json.net i get:

": Unable to find a constructor to use for type BriefFiniteElementNet.ElementCollection"

But the ElementCollectionClass does have deserialization constructor with protected scope:

protected ElementCollection(SerializationInfo info, StreamingContext context)

here is my code:

```
 class Program
    {
        static void Main(string[] args)
        {
            ISerializable model = BriefFiniteElementNet.RandomStuff.GetRandomFrameModel(5);

            //serialize - deserialize with Json.NET - fail
            var json = Newtonsoft.Json.JsonConvert.SerializeObject(model);
            var reterievedObject = Newtonsoft.Json.JsonConvert.DeserializeObject<Model>(json);//throws exception


            //serialize - deserialize with Json.NET - does work
            var st = new MemoryStream();
            var formatter = new BinaryFormatter();
            formatter.Serialize(st, model);
            st.Position = 0;
            var reterievedObject2 = formatter.Deserialize(st);//works fine
        }
    }
```

the model object which is complicated is from this project:
https://brieffiniteelementnet.codeplex.com

Am i missing something?

**Comment by JamesNK** [comment]
It needs to be public.

**Comment by epsi1on** [comment]
sorry, can you please explain more?
What needs to be public?!

**Comment by JamesNK** [comment]
The constructor.

**Comment by epsi1on** [comment]
Thanks, that will probably fix the problem.
But i think all ISerializable classes do not necessarily have public constructors. So that would be good if you can handle constructors other than public (like protected or private) via reflection as .NET binary serialization do.

thanks again
