### ISSUE TITLE
LINQ JObject not exporting ContainsKey

### ISSUE THREAD

**Issue by ambs** [JamesNK/Newtonsoft.Json#854]
Hi

At 
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JObject.cs#L544
ContainsKey is not public. 
Where I could do

```
  float x = hash.ContainsKey('x') ? (float)hash['x'] : 0f;
```

I am needing to write 

```
    float x;
   JToken t;
   if (hash.TryGetValue('x', out t)) {
      x= (float)t;
  } else { x = 0f; }
```

Or am I missing something?

Thanks

**Comment by SamuelEnglard** [comment]
@ambs you could cast the `JObject` to a `IDictionary<string, JToken>` to get access to `ContainsKey` (though I agree you shouldn't have to)

**Comment by ambs** [comment]
Yep, can't recall how, but I solved the issue. But always good to have it explicitly.

**Comment by JamesNK** [comment]
I meant to make it public in 10 but I forgot. It will be public in 11.

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/a1388529946792a0c30222311e0e949e85fe7a1e
