### ISSUE TITLE
using regularExpression in JsonPath filter criteria

### ISSUE THREAD

**Issue by binitjha** [JamesNK/Newtonsoft.Json#858]
I am trying to do filter based on regular expression ( or simple contains ) in filter. for example 

`{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}`
For the Json above
$..phoneNumbers[?(@.type == 'home')].type  ==> works fine.

but I want to do something like @.type contains a given string or better yet matches with a regular expression. This doesn't seem to be supported.  Something like
$..phoneNumbers[?(@.type startswith 'home')].type  OR
$..phoneNumbers[?(@.type =~ /*ho*/)].type

Thanks.

**Comment by JamesNK** [comment]
You can't do that. If in the future there is a better standard, or a popular defacto standard then I'll add support.

**Comment by binitjha** [comment]
Thanks James. 
Really appreciate your response. There are few operator supported already. Instead of full fledge regex , one can also support simple string comparison like string.startswith or endswith or contains. 

I am not sure who updates the standard but I think the JSONPath is similar as Xpath and it supports regex.

Lets see if there are more demands for it.

**Comment by MinhNguyenDev** [comment]
We really need the regex compare in filter to make JSONPATH useful in real application. In Javascript JSONPATH library and other (i.e Jayway Jsonpath) they all can use regex. It would be very helpful to have "=~" syntax like Jayway (https://github.com/json-path/JsonPath)
