### ISSUE TITLE
Get during deserialization?

### ISSUE THREAD

**Issue by NPSF3000** [JamesNK/Newtonsoft.Json#860]
Hi Guys,  

Been recently tracking down a weird bug in our software.  Specifically a nullreference exception in one of our property gets (some logic there).  

Turns out the problem isn't in our code or even in the serialization of it to JSON, but rather the error occurs during *deserialization* (json to object).  If you look at the call stack (bottom right):

<img width="1258" alt="screenshot 2016-03-28 11 59 40" src="https://cloud.githubusercontent.com/assets/1442620/14083801/1fe0a46a-f4dd-11e5-8384-85c0a8d204ed.png">

You can see that Json.net is clearly calling:  Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue!

Confused,

NPSF3000

**Comment by JamesNK** [comment]
What settings are you using when deserializing? Some settings require a value to be fetched.

**Comment by NPSF3000** [comment]
Hi James,

```
var settings = new JsonSerializerSettings
{
	TypeNameHandling = TypeNameHandling.All,
	ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Error,
	ContractResolver = new CustomContractResolver(),
	Formatting = Formatting.Indented,
	Error = (o, args) => args.ErrorContext.Handled =
						 args.ErrorContext.Error.InnerException is NotImplementedException,
};

settings.Converters.Add(new DeepDictionaryConverter());
settings.Converters.Add(new ByteArrayConverter());
settings.Converters.Add(new IsoDateTimeConverter { DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK" });
```

DeepDictionaryConverter only applies if type is of TimeSlots, IDictionary or IDictionary<,>.  ByteArrayConverter only apply if type is byte[].  Bother are custom.

IsoDatetimeConverter is from Newtonsoft.Json.Converters.

CustomContractResolver ignores serialization attributes, enables writing to non-public sets, and in many situations uses GetSafeUninitializedObject to return an uninitialized object.

I have noted that this seems to be a deliberate design decision?  JsonSerializerInternalReader. SetPropertyValue you do call GetValue... https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L1007

Current thinking is that we're surprised to deserialization happening during serialization because our object is not yet in a valid state, nor do we want the performance overhead.  Is it the assumption from Json.net and likely IsoDateTimeConverter is that complex properties that depend on others is a rare occurance?

It's worth noting that this is clean json to object deserialization, we're not calling 'populate object' in this code.

Thanks,

Nathaniel Armer

**Comment by JamesNK** [comment]
The current value is passed into JsonConverter.ReadJson. You'll have to remove the error being thrown in the getter or not use a JsonConverter.
