### ISSUE TITLE
Parallel deserialization not supported?

### ISSUE THREAD

**Issue by johanolofsson** [JamesNK/Newtonsoft.Json#864]
I have a huge number of files with a lot of JSON. In order to improve the loading of these I tried to run multiple threads working in different subsets of the files. This should in theory improve performance approx by the number of cores available, given that the disk access is not the bottleneck. 

To my surprise I got no performance gain at all. To eliminate the potential bottleneck of the disk I first loaded all files into memory streams, and then want ahead with multiple tasks. No improvement.

I then started measuring the actual time each deserialization took. When using only one thread each deserialization took around 1ms (most files have the same size). When using multiple threads I got everything from 1 to 30ms per deserialization.

This is obviously just a guess, but to me this looks like there is some synchronization going in which t will only let one single object be deserialized at the time. If that is the case, what can I do to improve this?

**Comment by gaziqbal** [comment]
I'm also having difficulty finding documentation or guidance about multi-threaded usage. Are you using the same serializer instance across all threads or is each thread creating it's own?

**Comment by JamesNK** [comment]
Parallel deserialization is definitely supported. WebAPI uses it and IIS has a separate thread per request.
