### ISSUE TITLE
Json.Net is modifying dates with explicit offsets

### ISSUE THREAD

**Issue by jetuser** [JamesNK/Newtonsoft.Json#865]
If a json property has a date specified with an offset, json.net appears to be affecting the actual time without changing the offset. This seems like a bug as if an offset is obviously part of a date string you should respect the time zone or adjust the offset approprioately:

"EndDate": "2016-03-31T12:00:55.2831445-07:00",

When casted to DateTimeOffset turns into:

endDate	{3/31/2016 10:00:55 AM -07:00}

Edit: even if this is intentional by date settings, it is somewhat misleading as one would expect offsets are handled automatically by json.net if they are explicit

**Comment by oliverjanik** [comment]
Welcome to the club #525 #744. @JamesNK is very stubborn about this one and it causes me extreme pain to deal with. 

I understand the compatibility argument, but this behaviour is very surprising and actively harmful. I find it unacceptable.

**Comment by JamesNK** [comment]
Use the DateParseHandling.DateTimeOffset setting

**Comment by nbevans** [comment]
Agreed with @oliverjanik.

This behaviour just caught me out big time. It is not type safe and breaks the principle of least surprise.

If a field contains a DateTime then it will be typed as a DateTime. Not a String. If my String field contains what looks like a DateTime then, by default, it should not be manipulated at all.

**Comment by jetuser** [comment]
I'm with @nbevans and @oliverjanik in part. If the framework is going to be smart about date time parsing then you need to be completely consistent in handling dates. 

In the case of the offset dates, you are violating the data contract implicitly by forcing an offset date into a date time. It should be left up to the caller to decide whether or not they convert to date time or keep it as an offset. The conversion can be handled gracefully both ways if the source is represented correctly, but not when its converted without the knowledge of the caller.

**Comment by nbevans** [comment]
@jetuser It's just a library, not a framework. If it were a framework then this behaviour MIGHT be acceptable.

**Comment by JamesNK** [comment]
> It should be left up to the caller to decide whether or not they convert to date time or keep it as an offset.

Use the DateParseHandling.DateTimeOffset setting.

**Comment by winnerlein** [comment]
`JObject.Parse` causing silent data corruption using the default settings is insane. While there is a setting to avoid this, people have to know about it, which often happens only after data has been permanently corrupted. Please change the default to `DateParseHandling.None` in the next major version.

**Comment by derekm** [comment]
@JamesNK said,
> Use the DateParseHandling.DateTimeOffset setting.

Docs suck really bad, so it is hard to figure out how to configure `JToken` with `DateParseHandling.None` or `DateParseHandling.DateTimeOffset`, but you do it via `JsonConvert.DefaultSettings` as in:

```csharp
        JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
        {
            DateParseHandling = DateParseHandling.None
        };
```

Defaults come from `JsonSerializerSettings`'s default constructor, so you're getting stock `JToken` behavior plus the override on the `DateParseHandling` setting.
