### ISSUE TITLE
Alternate names for a property

### ISSUE THREAD

**Issue by thtp** [JamesNK/Newtonsoft.Json#867]
It would be great to have an ability to parse different json properties to a single .NET class property.

```
[JsonProperty("error", ProperyNameSynonyms = new [] {"error_message", "message"})]
public string Error { get; set; }
```
With a code like above I would like all the synonyms to be deserialised to the Error property. And Error property to be serialized as "error" (PropertyName).
If there are more than one suitable json property, exception would be thrown.

Is it viable / useful / doable?

**Comment by JamesNK** [comment]
The usefulness is a little narrow, and I'm trying to avoid adding too much to Json.NET now.

For cases like this you could write a JsonConverter.
