### ISSUE TITLE
Apply the property naming convention from the IContractResolver when using JsonExtensionDataAttribute

### ISSUE THREAD

**Issue by guillaume86** [JamesNK/Newtonsoft.Json#868]
When using the CamelCasePropertyNamesContractResolver,
the additional properties serialized or deserialized into/from the [JsonExtensionData] Dictionary<string, object> do not respect the naming convention. 

Maybe useful information: when directly serializing a IDictionary<K,V>, the naming convention is respected (including for nested dictionaries).

**Comment by robgha01** [comment]
Ok, so its not only me at least now i know way i don't get proper named json...
any status on this issue ?
@guillaume86 dide you find any workarounds ?

**Comment by JamesNK** [comment]
Fixed with https://github.com/JamesNK/Newtonsoft.Json/issues/1077
