### ISSUE TITLE
Class  DynamicReflectionDelegateFactory has a bug

### ISSUE THREAD

**Issue by tangdunfeng** [JamesNK/Newtonsoft.Json#869]
Class  DynamicReflectionDelegateFactory has a bug。
 
Method CreateGet ,

 `  DynamicMethod dynamicMethod = CreateDynamicMethod("Get" + propertyInfo.Name, typeof(T), new[] { typeof(object) }, propertyInfo.DeclaringType);`
ReturnType is typeof(object), parameterType is new[] { typeof(T) }.

**Comment by JamesNK** [comment]
I don't understand. What is the bug causing to happen? Can you give information for reproducing it.

**Comment by tangdunfeng** [comment]
This is a bug, but will not cause an exception.
The current code is:
`DynamicMethod dynamicMethod = CreateDynamicMethod("Get" + propertyInfo.Name, **typeof(T)**, new[] { **typeof(object)** }, propertyInfo.DeclaringType);`
The correct code is :
`DynamicMethod dynamicMethod = CreateDynamicMethod("Get" + propertyInfo.Name, **typeof(object)**, new[] { **typeof(T)** }, propertyInfo.DeclaringType);`

**Comment by JamesNK** [comment]
Fixed
