### ISSUE TITLE
Question about inheritance behavior of DataContract

### ISSUE THREAD

**Issue by taori** [JamesNK/Newtonsoft.Json#872]
Hello @JamesNK. This question arose from reading #603.

I started looking for it because i was wondering why DataContract wasn't inherited. It does make sense now though - Out of curiosity: Would deriving from DataContract with modified AttributeUsage inheritance be considered by JSON.NET right now? 

The way i see it both scenarios of serialization behavior inheritance is wanted and unwanted. Not having to subclass anything to get it done could be kind of nice.

**Comment by JamesNK** [comment]
I'm not going to change whatever the current behavior is now for backwards capability.

**Comment by taori** [comment]
Yeah. However my question was if creating a custom DataContract attribute with modified attributeusage set to inherited true would work

**Comment by JamesNK** [comment]
You could do that in a custom contract resolver.

**Comment by taori** [comment]
Ok. I suppose that will do - Thanks!

**Comment by joaoportela** [comment]
@JamesNK any change of adding an opt-in flag to enable standard behavior?

This way we wouldn't need to break backwards compatibility.

**Comment by joaoportela** [comment]
In benefit of anyone else coming across this issue:

If you can't remove the `[DataContract]` from the base class you can always re-enable the (default) opt-out behavior on your derived class by using `[JsonObject(MemberSerialization.OptOut)]`
