### ISSUE TITLE
Converting xml to JSON with JSON Schema

### ISSUE THREAD

**Issue by Sushil-Dhiver** [JamesNK/Newtonsoft.Json#873]
Hi.

Is there a way to convert an xml to JSON with a JSON Schema?
I can see JSchema that we can use to validate an existing JSON but is there something we can use to create a JSON out of JSON Schema just like we create xml's out of xsd.

**Comment by JamesNK** [comment]
No there isn't

**Comment by Sushil-Dhiver** [comment]
thanks for the reply. I have an issue where my xml has a node that has some child nodes so when i convert the xml into json using JSON.net, it converts the child nodes into an array, but there are certain instances when the XML that i get can contain only one child node instead of a list so when I convert this xml into json, it converts it into an object rather than an array. do we have a work around for this?
