### ISSUE TITLE
Datetime format string deserialize

### ISSUE THREAD

**Issue by tangdunfeng** [JamesNK/Newtonsoft.Json#876]
`public class DateTimeObject
        {
            public string String { get; set; }

            public object Object { get; set; }

            public DateTime DateTime { get; set; }
        } 
         string json = @"{
                String:""2016-03-08T16:00:00.000Z"",
                Object:""2016-03-08T16:00:00.000Z"",
                DateTime:""2016-03-08T16:00:00.000Z""
             }";
            JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings {
                DateTimeZoneHandling = DateTimeZoneHandling.Local
            };
            DateTimeObject dateTimeObject;

            JsonSerializer jsonSerializer = JsonSerializer.CreateDefault(jsonSerializerSettings);
            using (TextReader textReader = new StringReader(json)) {
                using (JsonReader jsonReader = new JsonTextReader(textReader)) {

                    JObject jsonObj = (JObject) jsonSerializer.Deserialize(jsonReader);
                    dateTimeObject = (DateTimeObject) jsonObj.ToObject(typeof (DateTimeObject), jsonSerializer);
                }
            }

            Console.WriteLine(dateTimeObject.String);
            Console.WriteLine(dateTimeObject.Object.GetType());
            Console.WriteLine(dateTimeObject.Object);
            Console.WriteLine(dateTimeObject.DateTime);`
The result is "03/09/2016 00:00:00
System.DateTime
2016/3/9 0:00:00
2016/3/9 0:00:00
"
I want to "Object" property  is the DateTime type.
The "String" property value of "03/09/2016 00:00:00",but the correct result is "2016-03-08T16:00:00.000Z".

**Comment by JamesNK** [comment]
Hi, try asking for help on stackoverflow
