### ISSUE TITLE
Duplicate data if you serialize several  time

### ISSUE THREAD

**Issue by jkljajic** [JamesNK/Newtonsoft.Json#878]
Hi,
I have strange problem with following test code
` public class testJson
    {
        
        private List<int> _test;
        public List<int> test
        {
            get
            {
                if (_test == null)
                {
                    _test = new List<int>();
                    if (!_test.Contains(12))
                    {
                        _test.Add(12);
                    }

                }
                return _test;
            }
            set { _test = value; }
        }
    }
    internal class Program
    {

        private static void Main(string[] args)
        {

            var r1 = JsonConvert.SerializeObject(new testJson());
            var e1 = JsonConvert.DeserializeObject<testJson>(r1);
            var r2 = JsonConvert.SerializeObject(e1);
            var e2 = JsonConvert.DeserializeObject<testJson>(r2);
            var r3 = JsonConvert.SerializeObject(e2);
            var e3 = JsonConvert.DeserializeObject<testJson>(r3);
            var r4 = JsonConvert.SerializeObject(e3);
            var e4 = JsonConvert.DeserializeObject<testJson>(r4);
            var r5 = JsonConvert.SerializeObject(e4);
            var e5 = JsonConvert.DeserializeObject<testJson>(r5);
            var r6 = JsonConvert.SerializeObject(e5);
            var e6 = JsonConvert.DeserializeObject<testJson>(r6);
        }
    }`

Expecting result is {"test":[12]} every time
But i getting : {"test":[12,12,12,12,12,12]}
x times i try to serialize same output.
same problem is on version 7.0.1 and last one 8.0.3

Please i need feed back if this is bug or something else

**Comment by JamesNK** [comment]
You want ObjectCreationHandling.Replace
