### ISSUE TITLE
8.0.3 breaks existing code based upon camel case resolver

### ISSUE THREAD

**Issue by CoolDadTx** [JamesNK/Newtonsoft.Json#880]
The recent "fix" for the camel case resolver in 8.0.3 breaks existing apps that had client-side models based upon the 8.0.2 casing. For a minor update this shouldn't have caused a breaking change.  

This will prevent us from upgrading until we can go through all our code and update the casing. Ideally it should be reverted to the 8.0.2 behavior and fixed in a major update instead. Alternatively a new resolver could be added such that existing code won't have to be changed.

**Comment by JamesNK** [comment]
Every bug fix is a breaking change if you depend upon the bug.

You can copy the camel case contract resolver and implement one that still has the old behavior if you want.

**Comment by ericburcham** [comment]
@JamesNK - Would you mind providing some before/after behavior examples so that people know how to update their existing source code that "depends on the bug?"

This would _really_ be helpful to people that _apparently did the wrong thing_, and now want to find their mistakes and correct them.

**Comment by JamesNK** [comment]
I haven't got time for that.
