### ISSUE TITLE
Decimal numbers not converted correctly when using decimal comma

### ISSUE THREAD

**Issue by gertdc** [JamesNK/Newtonsoft.Json#882]
Hi, 

JsonConvert.DeserializeObject converts the decimal numbers to integers when a decimal comma separator is used instead of a decimal point.

I tried to do the following:

```
 var settings = new JsonSerializerSettings();
                settings.Culture = new CultureInfo( "nl-BE" );
                settings.Culture.NumberFormat.NumberDecimalSeparator = ",";
                var returnList = JsonConvert.DeserializeObject<List<T>>(json, settings );
```
But that didn't solve the problem. So a decimal number e.g. 73,55 in the json array is serialized to 7355

Any idea how to fix this?

Thanks!
Kind regards,
Gert.

**Comment by gertdc** [comment]
Sorry, this is fixed in the last version.

**Comment by muhamadahsan** [comment]
@gertdc : Dear, we are facing the same issue with the version 9.0.1 (the latest version). Can you please confirm is it fixed or not. If it has been fixed, then which version? Any workaround if has been fixed? Quick response will highly be appreciated.

**Comment by gertdc** [comment]
Hi muhamadahsan, it was fixed in version 8.

**Comment by vishnu4** [comment]
honestly i'm suprised you have to add the NumberDecimalSeparator at all.  shouldn't specifying the culture as nl-BE do that for you already?

**Comment by twieskot** [comment]
maybe i made something wrong, but if have the same issue opposite around. In my json file are decimals with the format "123.45"
After deserialization i get "12345" as decimal value.

My Verison of Netonsoft.Json is 13.0.3.

I even tried the same method than gertdc, without success:

...
CultureInfo ci = CultureInfo.CurrentCulture;
CultureInfo new_cult = (CultureInfo)ci.Clone();
new_cult.NumberFormat.NumberDecimalSeparator = ".";
using (StreamReader file = File.OpenText(filename))
{
    JsonSerializer serializer = new JsonSerializer();
    serializer.Culture = new_cult;
    return (MyObj)serializer.Deserialize(file, typeof(MyObj));
}
...

Any ideas what could be wrong here. I have got the same Experience with "System.Json" - 
there it is not even possible to set the culutre.
