### ISSUE TITLE
Create a Json.NET analyzer

### ISSUE THREAD

**Issue by giggio** [JamesNK/Newtonsoft.Json#883]
Following the idea of code aware libraries that was brought up by Roslyn, it would be nice if Json.NET already came with some analyzers.
We actually build some for CodeCracker, and our license allows us to contribute them to the Json.NET project.

Example of error diagnostics currently raised by CodeCracker:

````csharp
JsonConvert.DeserializeObject<Person>("foo");
JObject.Parse("foo");
JArray.Parse("foo");
````

They are here:
For C#
https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Usage/JsonNetAnalyzer.cs
Tests:
https://github.com/code-cracker/code-cracker/blob/master/test/CSharp/CodeCracker.Test/Usage/JsonNetAnalyzerTests.cs
For VB:
https://github.com/code-cracker/code-cracker/blob/master/src/VisualBasic/CodeCracker/Usage/JsonNetAnalyzer.vb
Tests:
https://github.com/code-cracker/code-cracker/blob/master/test/VisualBasic/CodeCracker.Test/Usage/JsonNetAnalyzerTests.vb

@JamesNK what do you think? I could work on a PR that you could review and approve.

After they are added to the project, we would remove them from CodeCracker, which is something we are already planning on doing (see https://github.com/code-cracker/code-cracker/issues/778).

**Comment by JamesNK** [comment]
I like the idea but I don't want to include it inside of Json.NET - I'm trying hard to keep the library small and focused. I think this would be great as an additional NuGet package that people can optionally install.

**Comment by giggio** [comment]
Ok, I can work with that. How would you like to proceed?

**Comment by JamesNK** [comment]
It can be a completely separate github repository and NuGet package. You don't need me at all.

**Comment by giggio** [comment]
Is it a problem to use the JSON.NET name?

**Comment by JamesNK** [comment]
No problem. I'd prefer that you don't start the package name with Newtonsoft.Json, but other than that go crazy.
