### ISSUE TITLE
Guid Type gets lost when toObject

### ISSUE THREAD

**Issue by fbarnard** [JamesNK/Newtonsoft.Json#888]
hi

I have a JObject with a "id" field thats Guid. When i try toObject it it looses the guid type and makes it a string.

![code](https://cloud.githubusercontent.com/assets/2089396/14741302/94ca6768-0895-11e6-84a7-0f119b937cbc.png)

Thanks

**Comment by fbarnard** [comment]
HI

I played a bit more and found that 

anon["id'].Value.ToObject<object>()  // String

anon["id'].Value.ToObject<Guid>()  // Guid

thanks

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/86c2f803114631fca7df9e82855728e7e71ad89b

**Comment by fbarnard** [comment]
thanks
