### ISSUE TITLE
JSON Linq: a JValue exception prohibits null content object (not like System.Xml.Linq).

### ISSUE THREAD

**Issue by olivier-spinelli** [JamesNK/Newtonsoft.Json#889]
Considering the following code to create a JSON object the "functional way":
```
                return ParsedProcedure == null
                        ? new JObject( new JProperty( "error", ParseError ) )
                        : new JObject(
                            new JProperty( "name", ParsedProcedure.SchemaName ),
                            new JProperty( "parameters",
                                new JArray( ParsedProcedure.Parameters.Select( p => 
                                        new JObject( 
                                            new JProperty( "name", p.Name ),
                                            new JProperty( "type", p.SqlType.ToStringClean() ),
                                            new JProperty( "direction", p.IsInput ? "I" + (p.IsOutput ? "O" : "") : "
                                            p.DefaultValue != null 
                                                ? new JProperty( "default", p.DefaultValue.ToString() )
                                                : null
                                            ) ) )));
```
**Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject.** is thrown by the null content object. I perfectly understand that a 'null' token has nothing to do here, and this is fine: by simply ignoring/skipping null object content (and not raising an error), this would enable the JObject construction to work just like the XElement does.

The work around here is to:
-  add back the property, later in the code (and say goodbye to the nice pure function).
- generate an empty string since I can not use null since null is a perfectly valid default value:
`new JProperty( "default", p.DefaultValue != null ? p.DefaultValue.ToString() : string.Empty )`
but I'd rather not produce the property at all...

I have looked for drawbacks did not found any. Do I miss something (a "JNOProperty")? or should this behavior be corrected to work like System.Xml.Linq?

**Comment by JamesNK** [comment]
C# null will be converted to a JValue that is Null when added to a JToken. There isn't any way to optionally add a property using a ternary statement. You'll have to have a method with an if statement.
