### ISSUE TITLE
Visual studio 2013 nuget package manager

### ISSUE THREAD

**Issue by miladganjali** [JamesNK/Newtonsoft.Json#891]
When I trying add Newtonsoft.Json packages to my Projects this error appears : 

> Installing 'Newtonsoft.Json 8.0.3'.
> Successfully installed 'Newtonsoft.Json 8.0.3'.
> Adding 'Newtonsoft.Json 8.0.3' to MyProjects
> Uninstalling 'Newtonsoft.Json 8.0.3'.
> Successfully uninstalled 'Newtonsoft.Json 8.0.3'.
> Install failed. Rolling back...
> Object reference not set to an instance of an object.

Other Packages work just fine

![untitled](https://cloud.githubusercontent.com/assets/8298544/14767265/e51aae4c-0a36-11e6-958e-a3d5095ed7ef.png)

**Comment by JamesNK** [comment]
Hi, could you raise the issue with the NuGet team

https://github.com/nuget/home/issues
