### ISSUE TITLE
[InvalidCastException] Deserialization of MathNet.Numerics.LinearAlgebra.Double.DenseVector

### ISSUE THREAD

**Issue by FoggyFinder** [JamesNK/Newtonsoft.Json#895]
When trying to deserialize MathNet.Numerics.LinearAlgebra.Double.DenseVector a get an exception:

 ```InvalidCastException - Unable to cast object of type 'System.Collections.Generic.List`1[System.Double]' to type 'System.Double[]'```

Example:

```
            var v = new DenseVector
                (new[] { -0.014147478859765236, -0.011419606805541858, -0.010038461483676238 });
            var json = JsonConvert.SerializeObject(v);
            var jobj = JsonConvert.DeserializeObject<DenseVector>(json);
```

**Comment by JamesNK** [comment]
Hi, I've fixed a bug related to that error message but deserializing that type isn't supported. It needs a constructor that takes an `IEnumerable<double>`
