### ISSUE TITLE
Serialization with Mono and overriden Properties

### ISSUE THREAD

**Issue by richseviora** [JamesNK/Newtonsoft.Json#897]
Hi folks, I've ran into a problem where serialization in Xamarin/Mono is exhibiting different behaviour from .NET. In my case, I have:
```
public class A<T>
{
  public virtual IList<T> Property { get; set; }
}

public class B : A<C>
{
  [JsonProperty(PropertyName="Name")]
  public virtual IList<C> Property {get; set;}
}

public class C {
  public string Name => "Bob";
}
```

Serializing B in .NET generates the appropriate object 
```
{
  "Name":[{"Name":"Bob"}]
}
```
 but Serializing B under Mono generates a duplicate property like so:

```
{
  "Name":[{"Name":"Bob"}]
  "Property":[{"Name":"Bob"}]
}
```

I've confirmed that the problem is rooted in differences in reflection by comparing the ContractResolver instance cache's property data for class `B` between .NET and Mono. In the latter it has an extra entry for `Property` with the property name `Property` as declared by type `A`, in addition to the entry for `Property` with property name `Name` as declared by type `B`.

I'm under deadline and will be working around this problem, but wanted to put it on your radar. I'll see if I can take some time to create a sample project in Mono to duplicate this problem.

This may be related to Issue #726 .

Packages:
Newtonsoft.Json, Version 8.0.3
Xamarin.Forms, Version 2.2.0.31

**Comment by JamesNK** [comment]
It looks like a bug in Mono. You will need to raise it with them.
