### ISSUE TITLE
Behaviour of `Undefined`

### ISSUE THREAD

**Issue by yaakov-h** [JamesNK/Newtonsoft.Json#899]
Hi,

While trying to trace a bug in my code, I've hit an area of Newtonsoft.Json that I can't find documentation for: Undefined values.

In the following code snippet:

```
var text = @"{ ""abc"": undefined }";
JsonConvert.DeserializeObject
var jo = JToken.Parse(text);
var abc = jo["abc"];
```

`abc` is not `null`, but `abc.Type` is equal to `JTokenType.Undefined`.

According to my understanding of RFC 7159, `{ "abc": undefined }` is not valid JSON. `undefined` is not part of the JSON spec, only values, objects, arrays and `null`.

How can I parse only JSON text to a `JObject` or `JToken` object graph and either:
1. Ignore `undefined` values, so the corresponding `JObject`/`JToken` is `null`, or
2. Deem the JSON text invalid, and throw an exception when parsing?

I couldn't find any APIs (e.g. `JsonLoadSettings`) to handle this case.

Thanks.

**Comment by reinseth** [comment]
I'm bumping this. Any input from the author?

**Comment by JamesNK** [comment]
At some point there maybe a strict mode on JsonTextReader to throw an error for invalid JSON. No plans to do it right now.
