### ISSUE TITLE
Handled JSON serialization error still writes object

### ISSUE THREAD

**Issue by heaths** [JamesNK/Newtonsoft.Json#902]
Using 8.0.3, when we're serializing a array of objects and, for example, one object's property getting throws, we don't want to include that object at all. Normally we'll throw an exception, but there are cases where'd we want to continue serializing the rest of the objects. But that object that threw would be invalid during deserialization (perhaps in other readers) so we'd rather not include it.

Handling the error just ignores that member, but it would be nice to have a way to just prevent that whole object from being included. If one was serializing simple types - like the `DateTime` example in the documentation - it wouldn't be included. But it would be nice to extend this to complex objects.

Seems it would be possible using our own `JsonConverter` (which we have for deserializing child types of an abstract parent based on some member, but are returning `false` for `CanWriter` to just let normal serialization occur), but seems like it would be overkill for just wanting the default behavior. We'd basically have to clone the incoming `JsonWriter` and write content to using the current contract then, if no error occurs, write that (potentially formatted) content to the original `JsonWriter` using `WriteRaw` (hopefully that respects the current indentation level).

**Comment by JamesNK** [comment]
Not possible, by the time the error happens the start of the object has already been written.
