### ISSUE TITLE
Async operations cannot be canceled

### ISSUE THREAD

**Issue by heaths** [JamesNK/Newtonsoft.Json#903]
Serializing or deserializing large object graphs can take time (granted, less so with JSON.NET!) but we do support cases where the user may want to cancel. It would be great if the async methods could take a `CancellationToken` to cancel. One way to do this would be in the `JsonReader` or `JsonWriter` to call `CancellationToken.ThrowIfCancellationRequested()` for the various Read and Write operations.

**Comment by JamesNK** [comment]
The async methods have been deprecated. Your best option is to do deserialization on another thread (Task.Run) and cancel that.
