### ISSUE TITLE
Feature request: More formatting options

### ISSUE THREAD

**Issue by colgreen** [JamesNK/Newtonsoft.Json#905]
FYI I'm overriding the default formatting so that arrays of numbers (and a few other primitive types) serialise to a single line. I'm doing this with a JsonConverter (code in stackoverflow link below). The motivation for this is that we like the formatted JSON for readability, but where we have arrays of numbers it's sometime more readable to have each array on one line (scrolling off to the right if necessary), rather than many lines each with a single value and indentation wwhitespace.

Thanks.

[ArrayNoFormattingConverter](http://stackoverflow.com/a/37158962/15703)

**Comment by jmessenger235** [comment]
On an additional note. That code does not work for generic un-typed JSON. In the below code the array filter does not work at all. That chain only supports Jvalues. The overridden WriteTo methods of the various concrete implementations of JToken do not support Json converters like they do in other cases. I would consider this a bug,  but as the only reason I am using it is to override formatting for an advanced format class.
```csharp
	var t = "{\"continuousSearch\":true,\"filters\":[{\"or\":[{\"and\":[{\"distance\":1024,\"biomes\":[\"Forest\"]},{\"distance\":1024,\"biomes\":[\"Plains\"]}]},{\"and\":[{\"distance\":1024,\"biomes\":[\"Mesa\"]},{\"distance\":1024,\"biomes\":[\"Desert\"]}]}]}]}";
	var obj = Newtonsoft.Json.JsonConvert.DeserializeObject(t);
	var f = Newtonsoft.Json.JsonConvert.SerializeObject(obj, settings);
	Console.WriteLine(f);

	JToken jt = JToken.Parse(t);
	Console.WriteLine(jt.ToString(Newtonsoft.Json.Formatting.Indented, new MyConverter()));
```
@JamesNK would a pull request for formatting enhancements be a welcome addition or does that depend on the design?

**Comment by JamesNK** [comment]
Hi, I'd prefer to keep formatting simple. There are so many styles that trying to cover them all isn't realistic. And like @jmessenger235 has pointed out it doesn't cover untype scenarios, e.g. IList<object> that contains just integers wouldn't have the special formatting applied but IList<int> would.
