### ISSUE TITLE
`JsonConvert.DeserializeObject<Model>(“{float: NaN}”)` fails

### ISSUE THREAD

**Issue by syndicatedshannon** [JamesNK/Newtonsoft.Json#908]
Although deserializing 'NaN' to a float is not required in the JSON specification, it appears that NewtonSoft once supported this and may not have intentionally removed the feature.

More details on it, and a workaround converter I am currently using, can be found here:

http://stackoverflow.com/questions/35066308/jsonconvert-deserializeobjectmodelfloat-nan-fails

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/1c4160cd844eccb8dfa808e1f636e088fefdc79e
