### ISSUE TITLE
Publish on NuGet a version compatible with NetStandard

### ISSUE THREAD

**Issue by Flavien** [JamesNK/Newtonsoft.Json#909]
I am using ASP.NET Core RC 2 and I am trying to target ``netstandard1.3``, however JSON.NET is not compatible.

I can see that [project.json](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/project.json) is already updated to target ``netstandard1.0`` so it's probably just a matter of publishing a new version on NuGet.

**Comment by PawelGerr** [comment]
Same here but I'm targeting `netstandard1.5` and `netcoreapp1.0`.

**Comment by JamesNK** [comment]
Done https://www.nuget.org/packages/Newtonsoft.Json/8.0.4-beta1

Let me know if you have any issues.
