### ISSUE TITLE
Datetime JavaScript 

### ISSUE THREAD

**Issue by zigzag95** [JamesNK/Newtonsoft.Json#923]
Some one could give me a working example for converting a datetime to js Date.
I think this is broken in .net core

**Comment by tangdunfeng** [comment]
[http://weblog.west-wind.com/posts/2014/Jan/06/JavaScript-JSON-Date-Parsing-and-real-Dates](url)

**Comment by zigzag95** [comment]
Thank you but I need an example showing how to convert a DateTime into JavaScript Date()

**Comment by tangdunfeng** [comment]
[https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/JavaScriptDateTimeConverter.cs](url)

**Comment by JamesNK** [comment]
Ask questions on Stackoverflow please.
