### ISSUE TITLE
Compiler errors on .NET Standard 1.3+ when source importing

### ISSUE THREAD

**Issue by niemyjski** [JamesNK/Newtonsoft.Json#925]
We are source importing our JSON.NET and internalizing it in our project. We do this for a few reasons, one mainly is that we don't have to worry about someone else already using a different version of JSON.NET..

When we try and compile using dotnet build using the following (framework target.. please note that there is more stuff than required in the profile below...) we get tons of errors due to the 1.3+ profile has a lot of reflection types that don't exist in 1.0-1.2. I'm using the `PORTABLE` compiler directive 
as that is what you have in your definition.. I changed to `DOTNET` and it was a bit better but still lots of errors.

Can you guys add a 1.3 framework target to JSON.NET, this would fix this issue as well as allow you to support `BigInteger` and more with `System.Runtime.Numerics`.

**P.S., You have a compiler directive defined as `NETSTANDARD10` but it's never used and the convention the community is using is `NETSTANDARD1_0` :). 

```json
"netstandard1.3": {
            "buildOptions": {
                "debugType": "portable",
                "define": [ "PORTABLE", "NETSTANDARD", "NETSTANDARD1_3" ]
            },
            "dependencies": {
                "Microsoft.CSharp": "4.0.1-rc2-24027",
                "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-final",
                "System.Collections": "4.0.11-rc2-24027",
                "System.Collections.Concurrent": "4.0.12-rc2-24027",
                "System.Diagnostics.Debug": "4.0.11-rc2-24027",
                "System.Diagnostics.Process": "4.1.0-rc2-24027",
                "System.Diagnostics.StackTrace": "4.0.1-rc2-24027",
                "System.Diagnostics.TraceSource": "4.0.0-rc2-24027",
                "System.Dynamic.Runtime": "4.0.11-rc2-24027",
                "System.Globalization": "4.0.11-rc2-24027",
                "System.IO": "4.1.0-rc2-24027",
                "System.IO.Compression": "4.1.0-rc2-24027",
                "System.Linq": "4.1.0-rc2-24027",
                "System.Linq.Expressions": "4.0.11-rc2-24027",
                "System.Net.Primitives": "4.0.11-rc2-24027",
                "System.Net.Requests": "4.0.11-rc2-24027",
                "System.ObjectModel": "4.0.12-rc2-24027",
                "System.Reflection": "4.1.0-rc2-24027",
                "System.Reflection.Extensions": "4.0.1-rc2-24027",
                "System.Resources.ResourceManager": "4.0.1-rc2-24027",
                "System.Runtime": "4.1.0-rc2-24027",
                "System.Runtime.Extensions": "4.1.0-rc2-24027",
                "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027",
                "System.Security.AccessControl": "4.0.0-rc2-24027",
                "System.Text.Encoding": "4.0.11-rc2-24027",
                "System.Text.Encoding.Extensions": "4.0.11-rc2-24027",
                "System.Text.RegularExpressions": "4.0.12-rc2-24027",
                "System.Threading": "4.0.11-rc2-24027",
                "System.Threading.Tasks": "4.0.11-rc2-24027",
                "System.Threading.Timer": "4.0.1-rc2-24027",
                "System.Threading.Thread": "4.0.0-rc2-24027",
                "System.Xml.ReaderWriter": "4.0.11-rc2-24027",
                "System.Xml.XDocument": "4.0.11-rc2-24027",
                "System.Xml.XmlSerializer": "4.0.11-rc2-24027"
            }
        }
```

**Comment by JamesNK** [comment]
I'm going to add a newer profile at some point but it isn't a priority right now.

**Comment by niemyjski** [comment]
I'm seriously blocked on this at the moment and I suspect others will be as well..  I'd be more than happy to help spend a little bit of time on this with some guidance...

I referenced a commit that seemed to help but I still have even more errors on .net standard 1.5 that my temp work around didn't fix.. I just want to get to a compiling state.

**Comment by niemyjski** [comment]
Here's a direct link to my project with the project.json target framework versions listed if you're interested..

https://github.com/exceptionless/Exceptionless.Net/tree/feature/netstandard/src/Exceptionless.Portable

**Comment by JamesNK** [comment]
You have a copy of the source code. You're not seriously blocked.

There will be a newer standard targeted but I want to wait until core is finished and out to figure out which one to target.

**Comment by niemyjski** [comment]
@JamesNK I just spent the whole morning adding .net standard directives for each version of the .net standard here (https://github.com/exceptionless/Exceptionless.Net/commit/3302d8ea5a6da7a1b05cac0f1fb761bea1e72183) Could you take a quick look at this and see if this is something you'd be willing to accept as a pull request. If so, I'll work on a pr..

What my changes allow for things to really lightup as you increase the .net standard version  to JSON.NET based on the selected target framework :)

**Comment by niemyjski** [comment]
I created a pull request for this.

**Comment by SergioMorchon** [comment]
How is going this?
I'm also stuck by this issue: my core library depends on this one, and cannot target any netstandard :S

**Comment by JamesNK** [comment]
I will add a netstandard1.3+ target sometime after .NET Core is RTM.

**Comment by kirankulkarni747** [comment]
.NET Core RTMed on 6/27. Can we have this issue re-opened?

**Comment by JamesNK** [comment]
Sure.

Stuff to figure out is whether IL emit that is in 1.3 should be supported. Need to find a way to determine whether IL emit is supported on a platform and dynamically switch between it and regular reflection.

**Comment by niemyjski** [comment]
@JamesNK have you had a chance to look at my pr? It was pretty complete.

**Comment by niemyjski** [comment]
https://github.com/JamesNK/Newtonsoft.Json/pull/927

**Comment by JamesNK** [comment]
I've thought about this and right now I'm only interested in a netstandard1.1 build to add BigInteger.
