### ISSUE TITLE
Not possible to use Portable and non Portable versions in the same application

### ISSUE THREAD

**Issue by Pikhulya** [JamesNK/Newtonsoft.Json#928]
There are cases when both: Portable and non Portable versions of the library have to be used by the same application which exposes a problem because from .NET point of view Portable and non Portable versions are identical: the assembly file name, as well as Version and the Key are the same, so, there is no way to put both of those DLLs into let's say the same folder so the app would be able to consume both.
An example when both are needed:
ASP.NET Web Api specific assembly internally references non portable version which means that it has to be available for the application. At the same time the web api app could reference another library which is portable and therefore it references portable version of the Json dll, now we have a problem because both of those DLLs with the same name have to be put into the application folder.

The problem could be solved if the Portable versions have different file name, do you think you could do something like this?

**Comment by IanYates** [comment]
Have you added binding redirects to your web.config?

**Comment by Pikhulya** [comment]
No, I have not because I don't see a sense to do that (https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx). The redirect helps when an application was compiled with an assembly version let's say 1.0.0.0 but at runtime another assembly is available, let's say version 3.0.0.0. But, please note, the problem I outlined in this issue is very different.

**Comment by Pikhulya** [comment]
Just wondering whether you need more details on the issue.

**Comment by JamesNK** [comment]
This is basically a limitation of .net. You can only have one version loaded.

**Comment by Pikhulya** [comment]
Please note - I am not asking you to change the library in such a way that it would be possible to load into AppDomain more than one instance of the same version, instead I am asking to not ship 2 different dlls (portable and regular) as they are of the same version (the version includes not only literally numeric version but a dll name as well), by shipping it the way you do today you are preventing people from using both - portable and regular in a single process which is often required.
