### ISSUE TITLE
Add Converter for converting integer types to JSON string and back

### ISSUE THREAD

**Issue by tmds** [JamesNK/Newtonsoft.Json#930]
Integer types are often used as ids. Since javascript only support floating point numbers, it would be nice if a converter could be specified to automatically convert .NET integer types to javascript strings and back. A culture neutral format should be used.

```
class MyEntity
{
    [JsonConverter(typeof(StringIntegerConverter))]
    public int Id { get; set; }
}
```

**Comment by JamesNK** [comment]
Someone can make it and put it on NuGet but I don't want it part of the core library to keep it small.

**Comment by tmds** [comment]
Hi @JamesNK after creating the issue it didn't trouble me much for the small application I was writing. The int I used in c# automagically converted into a string in javascript and when that string went back, Newtonsoft.Json automagically converted the string back into an int.

The problem is a real one. For example, the twitter API includes a string version of the 64-bit id because of the lack of number precision (see https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake).

I have no feeling for how much weight NewtonSoft.Json would take on by including such a converter. Putting it in a separate NuGet file seems like a lot of overhead. Since I won't implement it soon, I don't mind you closed the issue.
