### ISSUE TITLE
Handling duplicate elements in JSON payload

### ISSUE THREAD

**Issue by dmoeff** [JamesNK/Newtonsoft.Json#931]
What is the best way with Json.NET to restrict occurrence of duplicate elements in JSON payload?
For example:
 {
    "role" : "default",
    "username" : "mallory",
    "role": "admin",
    "password" : "Evil123!"
}

**Comment by thebothead** [comment]
I would like to know how to do this using the JSON.NET schema library as well.

**Comment by thebothead** [comment]
According to the spec as well:

2.2.  Objects

   An object structure is represented as a pair of curly brackets
   surrounding zero or more name/value pairs (or members).  A name is a
   string.  A single colon comes after each name, separating the name
   from the value.  A single comma separates a value from a following
   name.  The names within an object SHOULD be unique.

      object = begin-object [ member *( value-separator member ) ]
      end-object

      member = string name-separator value

**Comment by JamesNK** [comment]
You will need to use JsonTextReader

**Comment by thebothead** [comment]
We tried that.  The text reader does not restrict duplicates, in fact it
seems to allow them and uses the last property/value combination specified.

**Comment by JamesNK** [comment]
Oh I misunderstood. There is no way in Json.NET to restrict them. It will use the last value.

**Comment by thebothead** [comment]
Seeing as the JSON spec indicates valid JSON should contain unique names
within an object it seems like this should be a feature of the
validation/schema library of JSON.NET?  Perhaps a feature request is in
order?

**Comment by dmoeff** [comment]
try
            {
                var message =   "{" +
                                    "\"DeviceAdded\" :" + 
	                                "{" +
                                        "\"DeviceId\" : \"SN123456\"," +
                                        "\"Protocols\" : []," +
                                        "\"DeviceType\" : \"UPS\"," +
                                        "\"Model\" : \"12345\"," +
                                        "\"HardwareVersion\" : \"1.0.0.0\"," +
                                        "\"FirmwareVersion\" : \"2.0.0.0\"," +
                                        "\"SoftwareVersion\" : \"3.0.0.0\"," +
                                        "\"SerialNumber\" : \"1\"," +
                                        "\"SerialNumber\" : \"456\"" +
                                    "}" +
                                "}";

                var jobj = JsonConvert.DeserializeObject<JObject>(message);
                Console.WriteLine(jobj);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.GetType());
                Console.WriteLine(ex.Message);
            }

If I use Newtonsoft.Json 6.0.8 I get exception System.ArgumentException: Can not add property SerialNumber to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.

If I use Newtonsoft.Json 8.0.2 the code executes without error. What changed between these two versions? How with Newtonsoft.Json 6.0.8 I can get the same behavior as with Newtonsoft.Json 6.0.8?

**Comment by IanYates** [comment]
```
What changed between these two versions? How with Newtonsoft.Json 6.0.8 I can get the same behavior as with Newtonsoft.Json 6.0.8?
```
A lot I suspect.  You've accidentally specified the same version twice in your sentence.  Are you trying to get 8.0.2 to behave like 6.0.8, or make 6.0.8 behave like 8.0.2?

**Comment by dmoeff** [comment]
I would like 8.0.2 to behave as 6.0.8 in that when duplicate elements occurs in JSON payload an exception to be thrown. For example:

 var message = "{" +
                                "\"role\" : \"default\"," +
                                "\"username\" : \"mallory\"," +
                                "\"role\" : \"admin\"," +
                                "\"password\" : \"password!\"" +
                           "}";
  var jobj = JsonConvert.DeserializeObject<JObject>(message);

Here "role" element occurs twice. In this case 6.0.8 will throw a System.ArgumentException exception, where 8.0.2 deserialize it successfully with admin value for the "role".

**Comment by dbjorge** [comment]
@JamesNK  My team would really like to be able to detect this case. Would you be amenable to a PR that adds a new JsonSerializerSettings option for switching between the current "accept last" behavior and "emit parse error" behavior?

**Comment by davidagross** [comment]
How can this functionality be employed by patterns that use JsonConvert.DeserializeObject?  If it can't, I'd like to open an issue to add this functionality to JsonSerializerSettings.

**Comment by imtrobin** [comment]
I just found this issue too. I thought it was supposed to throw, and it didn't.

**Comment by mikhail-barg** [comment]
> How can this functionality be employed by patterns that use JsonConvert.DeserializeObject? If it can't, I'd like to open an issue to add this functionality to JsonSerializerSettings.

see #1922:
```с#
JsonLoadSettings settings = new JsonLoadSettings { DuplicatePropertyNamesHandling = DuplicatePropertyNamesHandling.Throw }
```

**Comment by mschmitz2** [comment]
> > How can this functionality be employed by patterns that use JsonConvert.DeserializeObject? If it can't, I'd like to open an issue to add this functionality to JsonSerializerSettings.
> 
> see #1922:
> 
> ```
> new JsonLoadSettings { DuplicatePropertyNamesHandling = DuplicatePropertyNamesHandling.Throw }
> ```

@mikhail-barg could you elaborate on how one can pass the `JsonLoadSettings` into `JsonConvert.DeserializeObject`, which, as I understand, only takes a `string` and `JsonSerializerSettings` as arguments?
```
public static T DeserializeObject<T>(string value, JsonSerializerSettings settings)
```
Thanks!

**Comment by DanCarterGMSL** [comment]
+1 for adding this as a property to `JsonSerializerSettings`.

I'm using Json.NET indirectly through ASP.NET Core, and I was surprised to see it behaving this way.

**Comment by rajrao** [comment]
While we wait for JsonSerializerSettings to get this behavior, I have found this code to work:

```
public object SerializeObject(string json, JsonSerializerSettings settings)
{
	JsonSerializer jsonSerializer = JsonSerializer.CreateDefault(settings);
	using (var stringReader = new StringReader(json))
	using (var jsonTextReader = new JsonTextReader(stringReader))
	{
		JsonLoadSettings loadSettings = new JsonLoadSettings { 
												DuplicatePropertyNameHandling = DuplicatePropertyNameHandling.Error 
											};
		var jtoken = JToken.ReadFrom(jsonTextReader, loadSettings);
		return jtoken.ToObject<object>(jsonSerializer);
	}
}
```
