### ISSUE TITLE
Error in JObject and JArray GetHashCode

### ISSUE THREAD

**Issue by timotyweis** [JamesNK/Newtonsoft.Json#933]
I've encountered a funky behavior of the `JObject.GetHashCode` (that in turn will call `JObject.GetDeepHashCode()` and then `JContainer.ContentsHashCode()`): calling the method with exactly the same object does return two different hash codes. 

Also `JArray` presents the same problem, whereas `JValue` seems not affected.

Here a simple test to prove it: 
```c#
[Fact]
public void NewtonsoftJsonJObjectGetHashCodeBug()
{
	// JValue: is ok
	var v1 = JToken.FromObject(1);
	var v2 = JToken.FromObject(1);
	Assert.Equal(v1.GetHashCode(), v2.GetHashCode());

	// JObject: does not return the same HashCode for equal objects
	var o1 = JToken.FromObject(new Exception("test"));
	var o2 = JToken.FromObject(new Exception("test"));

	Assert.Equal(o1, o2);

	// o1.GetHashCode()-> 59408853
	// o2.GetHashCode()-> 56152722
	Assert.NotEqual(o1.GetHashCode(), o2.GetHashCode()); // --> This should really be Assert.Equal

	var e = new Exception("test");
	var o3 = JToken.FromObject(e);
	var o4 = JToken.FromObject(e);

	Assert.Equal(o1, o3);
	Assert.Equal(o1, o4);
	Assert.Equal(o3, o4);

	// o3.GetHashCode()-> 26847985
	// o4.GetHashCode()-> 199777
	Assert.NotEqual(o3.GetHashCode(), o4.GetHashCode()); // --> This should really be Assert.Equal

	
	// JArray: does not return the same HashCode for equal objects
	var a1 = JToken.FromObject(new List<int>() { 1, 2, 3 });
	var a2 = JToken.FromObject(new List<int>() { 1, 2, 3 });

	Assert.Equal(a1, a2);

	// o1.GetHashCode()-> 1897140
	// o2.GetHashCode()-> 18262443
	Assert.NotEqual(a1.GetHashCode(), a2.GetHashCode()); // --> This should really be Assert.Equal

	var list = new List<int>() { 1, 2, 3 };

	var a3 = JToken.FromObject(list);
	var a4 = JToken.FromObject(list);

	Assert.Equal(a1, a3);
	Assert.Equal(a1, a4);
	Assert.Equal(a3, a4);

	// a3.GetHashCode()-> 4463106
	// a4.GetHashCode()-> 66622070
	Assert.NotEqual(a3.GetHashCode(), a4.GetHashCode()); // --> This should really be Assert.Equal
}
```

**Comment by JamesNK** [comment]
Assert.Equal isn't calling Object.Equals on the types. I'm not sure what the comparison is (maybe comparing the items in the collections?) but Object.Equals would return false, and the difference in hash codes isn't a bug.

**Comment by timotyweis** [comment]
@JamesNK The problem was not the equals or what xUnit is calling, but how the hash code is computed. As you can see, all `GetHashCode` is returning different values for the same objects. I can check the equality of the hash code in all different ways, the problems remains (2 object intrinsically equal have different hash codes):

```
  Assert.NotEqual(o1.GetHashCode(), o2.GetHashCode());
  Assert.False(o1.GetHashCode().Equals(o2.GetHashCode()));
  Assert.False(o1.GetHashCode() == o2.GetHashCode());
```

By looking in the code, the get hash code should compere the actual elements of the object (`GetDeepHashCode`) but as you can see the values returned are different for object containing the same thing. I'm not getting why a deep comparison should actually return different values for the same objects, however if it is by design it is fair enough.

**Comment by JamesNK** [comment]
> same objects

Objects that look the same or the same references? Two JObjects that have the same content aren't the same object and so shouldn't share the same hashcode.

**Comment by timotyweis** [comment]
My confusion is due to the name of the method `GetDeepHashCode`. 
In `JContainer` you're actually iterating through all children tokens, hence the term "deep" fits perfectly. But right because the naming, I was actually expecting to see the same hashcode for the "same" JToken (meaning a JToken with the same content but different reference).

By the way as far as I can see xUnit Equal is using the default IEqualityComparer:
```
    public static void Equal<T>(T expected, T actual)
    {
      Assert.Equal<T>(expected, actual, Assert.GetEqualityComparer<T>(false, (IEqualityComparer) null));
    }
```

**Comment by JamesNK** [comment]
> But right because the naming, I was actually expecting to see the same hashcode for the "same" JToken (meaning a JToken with the same content but different reference).

GetDeepHashCode does return the same hashcode: https://github.com/JamesNK/Newtonsoft.Json/commit/7ac27587c0c4f54dc3072dedbeff8e77d14db7dd

xUnit is not calling Equals so it must be using a custom EqualityComparer.

**Comment by timotyweis** [comment]
```
            var o1 = JToken.FromObject(new Exception("test"));
            var o2 = JToken.FromObject(new Exception("test"));

            Assert.Equal(o1, o2);

            // o1.GetHashCode()-> 59408853
            // o2.GetHashCode()-> 56152722

// --> This should really be Assert.Equal
            Assert.False(o1.GetHashCode().Equals(o2.GetHashCode()));
            Assert.False(o1.GetHashCode() == o2.GetHashCode());
            Assert.False(o1.GetHashCode().Equals(o2.GetHashCode()));
```

**Comment by JamesNK** [comment]
> // --> This should really be Assert.True

No it shouldn't.

Once again, you're using GetHashCode. They're different references, Equals returns false, the hashcodes shoulde be different.

GetDeepHashCode returns the same result, like it should.
