### ISSUE TITLE
Asp.Net RC1 to RC2 - JSON version issue.

### ISSUE THREAD

**Issue by katsuragi545** [JamesNK/Newtonsoft.Json#939]
I'm currently upgrading an Asp.NET RC1 project to RC2. When building I get the following error:

C:\Users\user\Documents\cwc_scaffold\project\error CS1705: Assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json' with identity 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

Prior to upgrading to RC2, I used the JToken method ToObject - it worked perfectly fine but now Visual Studio throws this error:

Error CS0411 The type arguments for method 'JToken.ToObject<T>(JsonSerializer)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Does anyone know what I need to do to fix this?

**Comment by katsuragi545** [comment]
So it seems to be related to my ConfigureServices method in my Startup.cs file. Here's my method:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver =
                    new CamelCasePropertyNamesContractResolver();

            });
        }
```

If I remove this function the error doesn't show up when building, but, the application won't run properly either. Any ideas on how to fix this method?

**Comment by JamesNK** [comment]
I have no idea. If there is a bug here then it is likely a bug in .NET Core. Raise the issue with MS
