### ISSUE TITLE
It's not possible to deserialize a Google GeoCoding response

### ISSUE THREAD

**Issue by JStarkl** [JamesNK/Newtonsoft.Json#940]
Hi

I'm not really sure if this is an issue, or if the deserializer simply isn't designed to do so, but when I wanted to deserialize a resonse from the Google GeoCoding Service to a DataSet, I ran into exceptions regarding the format

Although, the response is valid by RFC4627, RFC7159 and ECMA-404

So this is how the request looks:

{
"results" : [
{
"address_components" : [
{
"long_name" : "84",
"short_name" : "84",
"types" : [ "street_number" ]
},
{
"long_name" : "Saalachstraße",
"short_name" : "Saalachstraße",
"types" : [ "route" ]
},
{
"long_name" : "Salzburg",
"short_name" : "Salzburg",
"types" : [ "locality", "political" ]
},
{
"long_name" : "Salzburg",
"short_name" : "Salzburg",
"types" : [ "administrative_area_level_2", "political" ]
},
{
"long_name" : "Salzburg",
"short_name" : "Salzburg",
"types" : [ "administrative_area_level_1", "political" ]
},
{
"long_name" : "Austria",
"short_name" : "AT",
"types" : [ "country", "political" ]
},
{
"long_name" : "5020",
"short_name" : "5020",
"types" : [ "postal_code" ]
}
],
"formatted_address" : "Saalachstraße 84, 5020 Salzburg, Austria",
"geometry" : {
"location" : {
"lat" : 47.831183,
"lng" : 12.9943384
},
"location_type" : "ROOFTOP",
"viewport" : {
"northeast" : {
"lat" : 47.8325319802915,
"lng" : 12.9956873802915
},
"southwest" : {
"lat" : 47.8298340197085,
"lng" : 12.9929894197085
}
}
},
"place_id" : "ChIJpb71O0WFdkcR1NFhuRKJfPQ",
"types" : [ "street_address" ]
}
],
"status" : "OK"
}

The problem starts at the "geometry" node, the following property-set are not enclosed in square brackets, so the deserializer breaks up

To solve this, I manipulated the plain input string with the following code:

`inputText = inputText.Replace("geometry\" : {", "geometry\" : [{");
inputText = inputText.Replace("viewport\" : {", "viewport\" : [{");
inputText = inputText.Replace("location\" : {", "location\" : [{");
inputText = inputText.Replace("},\n            \"location_type", "}],\n            \"location_type");
inputText = inputText.Replace("northeast\" : {", "northeast\" : [{");
inputText = inputText.Replace("},\n               \"southwest\" : {", "}],\n               \"southwest\" : [{");
inputText = inputText.Replace("}\n            }\n         },\n         \"place_id", "}]\n            }]\n         }],\n         \"place_id");
inputText = inputText.Replace(",\n   \"status\" : \"OK\"\n", "");`

The last replacement is obvious for me, but I wonder, if the structure with the missing square brackets should be supported?

Kind regards
Jürgen

**Comment by IanYates** [comment]
The JSON looks OK to me.  I'm not familiar with JSON.Net dataset support - do you provide it a typed dataset ahead of time?  
The geometry node represents an object with some properties
* location - which itself has lat & lng
* location_type
* viewport - which has northeast and southwest, each with a lat & lng

Sounds like you might want viewport as a dictionary unless northeast & southwest are well-known 'properties' on some viewport object of yours.

What are you trying to do downstream with the dataset?  Maybe you can achieve what you need without needing a dataset?

**Comment by JStarkl** [comment]
Hi

Yes, the JSON is valid

No, I don't provide a Type

I simply deserialize:

`dataSet = JsonConvert.DeserializeObject<DataSet>(inputText);`

The properties which matter to me are "location_type", "latitude" and "logitude"

Kind regards
Jürgen

**Comment by JamesNK** [comment]
Ask on stackoverflow

**Comment by JStarkl** [comment]
Hmm, I thought this would be the right place to post possible issues in your code

Anyway, as thinks work for me with a little extra work, I let it go
