### ISSUE TITLE
Additional Context in JsonReaderException

### ISSUE THREAD

**Issue by seanfisher** [JamesNK/Newtonsoft.Json#941]
Thanks for a great library - use it every day.

Would it be possible to add in some additional context in a JsonReaderException's error message? Right now it looks like:

    Unexpected character encountered while parsing value: P. Path '', line 0, position 0.

Could it add some additional characters around the parsing error? For example:

    Unexpected character encountered while parsing value: P. Path '', line 0, position 0. Text in context: 'Parsing this will err[...]'
    --------------------------------------------------------------------------------------------------------^

or 

    Unexpected character encountered while parsing value: t. Path '', line 0, position 22. Text in context: '[...]ata": "" this is incorrect JSO[...]'
    -----------------------------------------------------------------------------------------------------------------------^

A third-party library we're using is throwing this exception up to us after deleting the JSON it was trying to parse, so any hints as to what JSON they were trying to parse is helpful.

**Comment by JamesNK** [comment]
The problem is Json.NET is a forward only reader. Reading forward to get more text for the error message prevents a user being able to recover from the error and do something else.

Also, with an error the reader doesn't know what state it is in. How does it know how far ahead to read?
