### ISSUE TITLE
JToken.Remove error when trying to remove a JProperty

### ISSUE THREAD

**Issue by BloodyRain2k** [JamesNK/Newtonsoft.Json#942]
The answer on SO about the error thrown in this case is helpful to understand why the error happens in the first place. http://stackoverflow.com/a/21899609/6378458

But couldn't JToken.Remove check for the potential of this error being thrown itself and in that case do the .Parent.Remove() way itself internally?

After reading the answer a few times I've understood why it works with .Parent.Remove() and why not without, but given the description of JToken.Remove(), mainly the part about it removing the element from it's parent, does .Parent.Remove() at first sound as if you'd be now about to remove the element you wanted to remove something from too.

**Comment by JamesNK** [comment]
The problem with making it remove the property is someone will call .Remove and then expect the .Parent property to be null, but it won't, the parent JProperty's .Parent will be null.
