### ISSUE TITLE
Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll" 

### ISSUE THREAD

**Issue by flashmandv** [JamesNK/Newtonsoft.Json#945]
I'm trying to build Unity game for Windows 10 Universal app, but when I do - I get "Failed to run serialization weaver" error on Newtonsoft.Json.dll.
Versions:
Unity 5.4.0 beta
Newton json 8.0.3

My Unity is set to .Net 2.0 (not the subset)
Here is more from the error stack:

UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll" -pdb -verbose -unity-engine="Temp\StagingArea\Data\Managed\UnityEngine.dll" "Temp\StagingArea\TempSerializationWeaver" -lock=UWP\project.lock.json -additionalAssemblyPath="Temp\StagingArea\Data\Managed" 
....
...
Symbols will be read from Temp\StagingArea\Data\Managed\UnityEngine.pdb
No symbols for Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll
Weaving assembly E:\PROJECTS\MyGame\Temp\StagingArea\Data\Managed\Newtonsoft.Json.dll
 + Newtonsoft.Json.JsonException
 + Newtonsoft.Json.JsonWriterException
 + Newtonsoft.Json.JsonReaderException
 + Newtonsoft.Json.JsonSerializationException
 + Newtonsoft.Json.Schema.JsonSchemaException
Will export symbols of pdb format
Mono.Cecil.ResolutionException: Failed to resolve **System.Runtime.Serialization.Formatters.FormatterAssemblyStyle**
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)

...
...
I tried everything and I can't get rid of this error :( Please help

**Comment by flashmandv** [comment]
After half day struggle - the I've found this forked newtonsoft json which works with Win 10 UWP
https://github.com/SaladLab/Json.Net.Unity3D/releases
JsonNet-UwpWorkaround.8.0.3.zip

**Comment by ryamldess** [comment]
I tried the workaround above and still get the same error. The 'workaround' does not work.

**Comment by vino4all** [comment]
The workaround suggested by @flashmandv worked for me. Build successful for UWP.

**Comment by vino4all** [comment]
The workaround suggested by @flashmandv worked for me. Build successful for UWP.
Use the library [UwpWorkaround.8.0.3.zip](https://github.com/SaladLab/Json.Net.Unity3D/releases/download/8.0.3/JsonNet-UwpWorkaround.8.0.3.zip)

**Comment by smag1** [comment]
Worked for me too, just go, in windows explorer,  in your Unity's Package Folder (I think it work with every folder if the folder is a  subfolder of the asset's  one). then just copy/past what you have exctract from the UwpWorkaround.8.0.3.zip
Then go back to your unity project in unity explorer => your project is updated => I hope it's now working
