### ISSUE TITLE
AllowIntegerValues = false for StringEnumConverter doesn't seem to be working.

### ISSUE THREAD

**Issue by dmikov** [JamesNK/Newtonsoft.Json#948]
I assumed that this setting will either generate error (wouldn't want that) or will skip property as invalid.
But it seems to be having no effect. Lots of our enums have assigned values and they start with 1, So in certain cases when we don't assign anything it sets it to 0 (None). Now serializer since it cannot find text outputs it as 0, which of course now breaks the validation. I hoped that not allowing integer values will prevent output of 0.

```
void Main()
{
	var obj = new Test();
	var jsonSerializer = new JsonSerializer();
	jsonSerializer.Converters.Add(new StringEnumConverter() { AllowIntegerValues = false});
	var jObject = JObject.FromObject(obj, jsonSerializer);
	Console.WriteLine(jObject.ToString());
}

public class Test
{
	public TestEnum MyProperty { get; set; }
}

public enum TestEnum
{
	One=1,Two=2,Three=3
}
```

Result:
```
{
  "MyProperty": 0
}
```

**Comment by Tydude4Christ** [comment]
AllowIntegerValues is only implemented when deserializing. For validation when serializing you should do validation within your class object model instead.

**Comment by dmikov** [comment]
Thank you. Maybe add it to docstring?

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/7ac27587c0c4f54dc3072dedbeff8e77d14db7dd
