### ISSUE TITLE
NullValueHandling.Ignore not working as expected with ExpandoObject

### ISSUE THREAD

**Issue by kwehrle** [JamesNK/Newtonsoft.Json#951]
Serializing an ExpandoObject and ignoring Null values isn't working. Is this by design or a bug?

    internal string toJson(ExpandoObject o)
    {
        return JsonConvert.SerializeObject(o, Newtonsoft.Json.Formatting.None, 
            new JsonSerializerSettings {
            NullValueHandling = NullValueHandling.Ignore
        });
    }

**Comment by JamesNK** [comment]
It's by design. NullValueHandling is only for properties on classes. An ExpandoObject is like a dictionary.
