### ISSUE TITLE
  The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from '...\Assets\Plugins\Newtonsoft.Json.dll'

### ISSUE THREAD

**Issue by minghz** [JamesNK/Newtonsoft.Json#952]
I'm working in an Unity project while using Newtonsoft.Json library.
It seems Newtonsoft is overwriting my project's native `System.Runtime.CompilerServices.ExtensionAttribute`

Are namespaces properly defined in the library?

Some extra info:
My Unity project compiles and runs in the Unity editor, but MonoDevelop is not able to run the Debugger.

**Comment by haico1992** [comment]
Use Newtonsoft.dll for .Net framework 3.5. For the poor soul that come after you..
