### ISSUE TITLE
IDictionary does not provide ordering capability

### ISSUE THREAD

**Issue by smarts** [JamesNK/Newtonsoft.Json#953]
Users should have a way to control the order of serialization of dictionary items.
IMHO, the method provided by `DefaultContractResolver` - `IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)` - should work when serializing an instance of `IDictionary`.

A concrete example:
```c#
public class Foo { public string Z; public string A; }

public class OrderedContractResolver : DefaultContractResolver
{
    protected override System.Collections.Generic.IList<JsonProperty> CreateProperties(System.Type type, MemberSerialization memberSerialization)
    {
        return base.CreateProperties(type, memberSerialization)
          .OrderBy(p => p.PropertyName)
          .ToList();
    }
}

// boiler-plate code omitted for brevity
object foo = new Foo { Z = "Z", A = "A" };

// serializes as { "Z": "Z", "A": "A" }
JsonConvert.SerializeObject(foo);

// serializes as { "A": "A", "Z": "Z" }
JsonConvert.SerializeObject(foo, new JsonSerializerSettings
{
    ContractResolver = new OrderedContractResolver()
});

foo = new Dictionary<string, string>
{
  { "Z", "Z" },
  { "A", "A" }
};

// serializes however the key-value-pairs are enumerated
JsonConvert.SerializeObject(foo);

// serializes however the key-value-pairs are enumerated
JsonConvert.SerializeObject(foo, new JsonSerializerSettings
{
    ContractResolver = new OrderedContractResolver()
});
```

**Comment by JamesNK** [comment]
You could do this by inheriting from Dictionary, and modifying the IEnumerable that it returns to include an order by. The IEnumerable is used when serializing a dictionary.

**Comment by smarts** [comment]
I understand that there is a work-around, but I also think that this is a legitimate bug. CreateProperties(Type, MemberSerialization) does not work as expected when the type is a dictionary. Are you open to discussing a fix for the problem?

**Comment by JamesNK** [comment]
There is no other way to order proprieties other than CreateProperties. Results from lists and dictionaries is controlled by the order of values returned from GetEnumerable.

**Comment by JamesNK** [comment]
There is no other way to order proprieties other than CreateProperties. Results from lists and dictionaries is controlled by the order of values returned from GetEnumerable.

**Comment by smarts** [comment]
I think that's fine (and even desirable) for non-dictionary IEnumerables, because they map to JS arrays, for which there is no property name. Dictionary mapping is inherently different, and is much more like that of other non-collection types. So as a client of the JSON.NET APIs, that's how I would expect to have control over it via the exposed extension points (as opposed to implementing special classes for serialization).

**Comment by Tydude4Christ** [comment]
@smarts, this is the way the System.Collections.Generic.Dictionary class was defined. See the documentation at [MSDN](https://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx). It says 

> For purposes of enumeration, each item in the dictionary is treated as a KeyValuePair<TKey, TValue> structure representing a value and its key. The order in which the items are returned is undefined.

You should implement an OrderedDictionary if ordering is important. As an implementation detail, Dictionary will be ordered the way it was inserted until a removal is performed.
