### ISSUE TITLE
Serialize to C# object literal

### ISSUE THREAD

**Issue by kasajian** [JamesNK/Newtonsoft.Json#955]
I want call JsonConvert.Serialize an a C# object, but rather than give me JSON, I want it to give me a set of C# steps that could be executed that would regenerate the original C# object.

Example:

        var tn = new TrainNode();
            tn.Templates[0].Color = "Yellow";
            tn.Templates[0].Dim = 3;
            tn.Templates[0].Pviewx = -12;
            tn.Templates[0].Pviewy = 12;

Or it could generate C# object literal initialization.

Does anyone know if this can be done via a custom converter?

**Comment by JamesNK** [comment]
Serializing to C# is completely different to serializing to JSON. I'm afraid Json.NET is a JSON serializer.

**Comment by kasajian** [comment]
Thanks for the response.   I was just asking because of two reasons:

1.  JSON.NET already support serializing to formats other than JSON, such as XML.
2.  I thought, and this is the part that I'm not sure about, is that JSON.NET is in a unique position in that it has some smarts and heuristics that it performs during the Deserialization step where it has to hydrate a new .NET object from JSON.   This means anywhere from instantiating it, to initializing the members, etc.   This part is tricky.   Like, maybe what looks like in JSON is an array, but in C# it's an IList, or an array, or what looks like in JSON is an object, but in C# the corresponding field is a dictionary.  JSON.net is smart enough to figure all that stuff out.    That logic seems similar to the type of logic that one would write to do serialize an object to C#.   If this is true, I can see that it's not part of JSON.NET, but if one were to be ambitious enough to write a C# serializer, I can imagine this part of JSON.NET could be reused.
