### ISSUE TITLE
List contents being doubled

### ISSUE THREAD

**Issue by mmkal** [JamesNK/Newtonsoft.Json#962]
This may be related to https://github.com/JamesNK/Newtonsoft.Json/issues/959 , but I have my own repro which is causing me serious problems. I have a class containing a Dictionary of items, and each of those items have properties which are lists. I would like to serialise the whole thing. Here's a small sample that you can run in xUnit which reproduces the problem:

```C#
public class ListContainer
{
    public List<int> Numbers { get; set; }
}
public class DictContainer
{
    private readonly Dictionary<string, ListContainer> _listContainers = new Dictionary<string, ListContainer>();

    public DictContainer()
    {
        OneToThree = new ListContainer { Numbers = new List<int> { 1, 2, 3 } };
    }

    public ListContainer OneToThree
    {
        get { return _listContainers["OneToThree"]; }
        set { _listContainers["OneToThree"] = value; }
    }
}

public class DictContainerTests
{ 
    [Fact]
    public void DeserialisationWorksProperly()

    {
        var dictContainer = new DictContainer();

        var json = JsonConvert.SerializeObject(dictContainer);

        var deserialised = JsonConvert.DeserializeObject<DictContainer>(json);

        Assert.Equal(dictContainer.OneToThree.Numbers.Count, deserialised.OneToThree.Numbers.Count); // Fails with Expected: 3, Actual: 6
    }
}
```

Bizzarely, when I deserialise again, the `Numbers` property contains [1,2,3,1,2,3] when it should contain [1,2,3].

This feels very much like a bug to me. Is there a workaround I can use for this?

**Comment by JamesNK** [comment]
You want ObjectCreationHandling.Replace
