### ISSUE TITLE
TraceJsonWriter handles nullable bytes incorrectly and throws an exception

### ISSUE THREAD

**Issue by lukeatron** [JamesNK/Newtonsoft.Json#963]
When the `TraceJsonWriter.WriteValue(byte?)` overload is called it writes the value to `_textWriter` and `_innerWriter` then calls `JsonWriter.WriteValue(byte?)`.  If the value is null there is no problem but if not it calls `WriteValue(byte)` which is overloaded by the `TraceJsonWriter` class.  The overload attempts the write the value to `_textWriter` and `_innerWriter` again but this time around the `_currentState` of the underlying `JsonWriter`s is `State.Object` instead of `State.Property` and this is invalid state to be writing a property value.

The fix seems simple enough.  Just get rid of the `TraceJsonWriter.WriteValue(byte?)` overload all together.  The base class will either call the overloaded `WriteNull` or `WriteValue(byte)`, both of which already handle writing the value to both `_textWriter` and `_innerWriter`.

**Comment by JamesNK** [comment]
Thanks, fixed https://github.com/JamesNK/Newtonsoft.Json/commit/0546ded7194ae0a80137fd4c0315a26e2c35b65e
