### ISSUE TITLE
Add Schema's OneOf/AnyOf/AllOf serialization compatibility

### ISSUE THREAD

**Issue by pmunin** [JamesNK/Newtonsoft.Json#964]
As we know JsonSchema allows developer flexible definition of object properties
https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not

E.g.:
```json
//from: http://json-schema.org/example2.html
{
    "id": "http://some.site.somewhere/entry-schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "schema for an fstab entry",
    "type": "object",
    "required": [ "storage" ],
    "properties": {
        "storage": {
            "type": "object",
            "oneOf": [
                { "$ref": "#/definitions/diskDevice" },
                { "$ref": "#/definitions/diskUUID" },
                { "$ref": "#/definitions/nfs" },
                { "$ref": "#/definitions/tmpfs" }
            ]
        },
        "fstype": {
            "enum": [ "ext3", "ext4", "btrfs" ]
        },
        "options": {
            "type": "array",
            "minItems": 1,
            "items": { "type": "string" },
            "uniqueItems": true
        },
        "readonly": { "type": "boolean" }
    },
    "definitions": {
        "diskDevice": {},
        "diskUUID": {},
        "nfs": {},
        "tmpfs": {}
    }
}
```

It'd be great If developer could have ability to unambiguously map class hierarchy to flexible JsonSchema. So for schema provided above classes would be like this:
```C#
public class Root
{
   public OneOf<DiskDevice, DiskUUID, Ntfs, Tmpfs> Storage {get;set;}
   public FstypeEnum FsType{get;set;} 
   //....
   public bool Readonly{get;set;}
}

public class DiskDevice{...}
public class DiskUUID {...}
public class Ntfs {...}
public class Tmpfs {...}
```

In this case OneOf<...>, AnyOf<...>, AllOf<...>,... are predefined value holder classes, that should be  provided by Json.Net with special serialization contracts. This will allow to generate C# classes by schema and visa versa.

There are challenges of integrating validation requirement that will allow deserializer to define which type is to select during deserialization in case of OneOf<...> in case it's too similar classes. One of the solution I see is to use fluent sdk, like:

```C#

public OneOf<DiskDevice, DiskUUID, Ntfs, Tmpfs> Storage {get;}
       = OneOf
            .Type<DiskDevice>(dd=>DiskName!=null)
            .Type<DiskUUID>(duid=>duid.Id!=null)
            ....
;

```

**Comment by ekevoo** [comment]
The right way to do that in the strongly typed world is a class hierarchy.

**Comment by pmunin** [comment]
@ekevoo, does not applicable for JsonSchema: https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not

**Comment by JamesNK** [comment]
I don't want to bake a JSON Schema concept deeply into the Json.NET serializer. You could already do something like this by having a property being an interface, have the deserialized types implement this interface, and use a JsonConverter to pick the correct type during deserialization.
