### ISSUE TITLE
Suggestion: JObject TryGetValue<T> extension

### ISSUE THREAD

**Issue by MV10** [JamesNK/Newtonsoft.Json#965]
Personally I find a ToObject&lt;T&gt; as the TryGetValue out parameter to be a more natural-feeling usage, so I use the following extension, which I'm suggesting as an addition to the project:

<pre><code>        public static bool TryGetValue<T>(this JObject obj, string key, out T value)
        {
            JToken token;
            bool result = obj.TryGetValue(key, out token);
            if (result)
            {
                value = token.ToObject<T>();
            }
            else
            {
                value = default(T);
            }
            return result;
        }</code></pre>

Then of course, usage is very simple, particularly with generics type inference:

<pre><code>    void ReadPerson(JObject jobject)
    {
        Person person;
        if(jobject.TryGetValue("person", out person) { ... }
    }</code></pre>

**Comment by JamesNK** [comment]
If this was done then the name would have be something like TryGetValueAndToObject to accurately describe what is happening (both getting and possibly deserializing the value), and a name that long smells wrong to me. It is simple enough for people to create an extension method like you have done if it is something that is repeated a lot in their app.
