### ISSUE TITLE
Deserializing null regex property throws JsonSerializationException

### ISSUE THREAD

**Issue by sonotude** [JamesNK/Newtonsoft.Json#966]
I think I have found an issue with deserializing a null value for a Regex property. The below code will error with a `Newtonsoft.Json.JsonSerializationException`

```
class SimpleClassWithRegex
{
    public Regex RegProp { get; set; }
}

[TestMethod]
public void RegexTest()
{
    string json = JsonConvert.SerializeObject(new SimpleClassWithRegex {RegProp = null}); 
    // json = {"RegProp":null}
    SimpleClassWithRegex obj = JsonConvert.DeserializeObject<SimpleClassWithRegex>(json); 
    //Above line throws a JsonSerializationException
}
```

The exception message is
```
Newtonsoft.Json.JsonSerializationException: Unexpected token when reading Regex. Path 'RegProp', line 1, position 15.
```
I have a fix ready that I can submit a pull request for if this is in fact a bug like I think it is.

**Comment by sonotude** [comment]
Oh and here is a fiddle showing the issue: https://dotnetfiddle.net/1GT5D9

**Comment by JamesNK** [comment]
Thanks, fixed https://github.com/JamesNK/Newtonsoft.Json/commit/b83e1fab4c3eb5074547bece3c1bfbefa2ac0a41

**Comment by sonotude** [comment]
Awesome, thanks
