### ISSUE TITLE
How do you serialize and deserialize special characters like @?

### ISSUE THREAD

**Issue by gsogol** [JamesNK/Newtonsoft.Json#967]
I have a need to serialize and deserialize classes where json is:
{
  "@type": "error",
  "code": "REPO_10707",
  "description": "Incorrect user name or password specified.",
  "statusCode": 403
}

Notice the @type. This is no my api so I have no control in changing it but need to JsonConvert.Serialize and Deserialize appropriately. Any luck?

**Comment by ekevoo** [comment]
Name the property anything you like and decorate it with JsonProperty

    [JsonProperty("@type")]
    public string Type { get; set; }

Documentation: http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonPropertyAttribute.htm

**Comment by gsogol** [comment]
#FacePalm

Thank you

**Comment by VitaliyAnders** [comment]
Have the same issue  @"{
                              'name': 'bool',
                              'description': 'bool',
                              'parameters': [
                                {
                                  'key': 'bool define',                                 
                                  'field': {
                                    '$type': 'UserDefinedBoolean',
                                    'description': 'boolean defined'
                                  }
                                }
                              ]
                            }";
Event when I put   [JsonProperty("$type")] on a field or more general [DataMember(Name ="$type")] not working at all
