### ISSUE TITLE
Int32/Int64 type information from BSON is not reflected in JTokenType

### ISSUE THREAD

**Issue by asgerhallas** [JamesNK/Newtonsoft.Json#97]
When serializing an .NET Int32, the BSON value is correctly written as Int32.

When deserializing from BSON to JObject this type information is lost and the JTokenType is the more generic JTokenType.Integer. 

When serializing the JObject to BSON again the value is now written as Int64.

I can understand the reasons behind this given that there's no Int32 in JSON. But would it be possible to have JObjects reflect the correct type information when deserialized from BSON?

**Comment by squire40** [comment]
When I deserialize my JSON, my integer values are getting deserialized as Int64.  This is breaking my app.  Due to this bug, I am unable to use this package.  Are there any plans to fix this? I am not using BSON, this is regular JSON.

**Comment by lvtoto** [comment]
yes, same issue. when I deserialize my JSON codes, integer will be deserialized as Int64 but Int32...Why?

**Comment by lvtoto** [comment]
see http://stackoverflow.com/questions/8297541/how-do-i-change-the-default-type-for-numeric-deserialization/9444519#9444519
