### ISSUE TITLE
What's the guidance on moving to NamingStrategy from contract resolvers?

### ISSUE THREAD

**Issue by jnm2** [JamesNK/Newtonsoft.Json#970]
I couldn't find any documentation on this, but I saw the NamingStrategy in the release notes and wanted to make sure I understood it completely.
- Are there breaking changes to contract resolvers?
- Is NamingStrategy preferred over a contract resolver?
- Is this simply an API factoring or what do they do differently?

What would I need to know in order to upgrade to v9? I'm using this everywhere:

``` c#
settings.Converters.Add(new StringEnumConverter { CamelCaseText = true });
settings.ContractResolver = new SignalRCamelCasePropertyNamesContractResolver();
```

Other than that, the most complicated contract resolver I have is this:

``` c#
private sealed class SignalRCamelCasePropertyNamesContractResolver : IContractResolver
{
    private readonly Assembly signalRAssembly = typeof(Microsoft.AspNet.SignalR.Infrastructure.Connection).Assembly;
    private readonly IContractResolver camelCaseContractResolver = new CamelCasePropertyNamesContractResolver();
    private readonly IContractResolver defaultContractSerializer = new DefaultContractResolver();

    public JsonContract ResolveContract(Type type) =>
        (type.Assembly == signalRAssembly ? defaultContractSerializer : camelCaseContractResolver)
        .ResolveContract(type);
}
```

**Comment by bherila** [comment]
It looks like `settings.ContractResolver` has been removed so yes, there is a breaking change.

**Comment by TylerBrinkley** [comment]
@bherila, that's not true. `ContractResolver` is still a member of `JsonSerializerSettings`.

**Comment by bherila** [comment]
You are right @TylerBrinkley. I reinstalled the library from Nuget and it came back. Not sure what happened!

**Comment by jnm2** [comment]
Closing due to lack of response.
