### ISSUE TITLE
ASP.NET Core Compatability

### ISSUE THREAD

**Issue by Legends** [JamesNK/Newtonsoft.Json#977]
(VS2015 Update 3 + Patch)

**Is Newtonsoft.Json 9.01 compatible with .NET Core 1.0 ?**

I have a plain .NET console application (.NET 4.6) and reference a .NET core class library that targets NetStandard v1.3. The class library has a reference to Newtonsoft.JSON.

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "9.0.1"
  },
  "buildOptions": { "platform": "anycpu" },

  "frameworks": {
    "netstandard1.3": {
      "imports": "dnxcore50"
    }
  }
}
```
The referenced NewtonSoft.JSON package is deployed here:

C:\Users\UserAccount\.nuget\packages\Newtonsoft.Json\**9.0.1**
The Exception:

An unhandled exception of type '**System.IO.FileNotFoundException**' occurred in DotNetConsoleApplication.exe

Additional information: Could not load file or assembly 'Newtonsoft.Json, **Version=9.0.0.0**, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by JamesNK** [comment]
It is. You could ask on dotnet/cli why you are getting this error.

**Comment by Legends** [comment]
ok, opened an [issue ](https://github.com/dotnet/cli/issues/3967)for that in the dotnet/cli repo
