### ISSUE TITLE
Assembly.LoadWithPartialName causes lots of hidden exceptions (visible from Intellitrace)

### ISSUE THREAD

**Issue by spicelogic** [JamesNK/Newtonsoft.Json#978]
There is a line in DefaultSerializationBuilder.cs as shown in the attached screenshot named hidden_exception.jpg. That line is causing many hidden exceptions that are visible from the Visual Studio Intellitrace. I have attached a screenshot of that intellitrace window named "intellitrace view.jpg".
![hidden_exception](https://cloud.githubusercontent.com/assets/8801786/17291892/540cbcae-5808-11e6-9df5-81ceb44f020f.png)
![intellitrace view](https://cloud.githubusercontent.com/assets/8801786/17291897/58d72990-5808-11e6-8631-86cc0833e39e.png)

**Comment by JamesNK** [comment]
Hi. I can't do anything about the internal errors, and I can't change the method called without breaking changes. You could report the issue on the dotnet/corefx repo and ask MS to improve their logic. You could also implement your own serializer binder that avoids that error, and use it while serializing.
