### ISSUE TITLE
Extend Required enumeration with DisallowDefault

### ISSUE THREAD

**Issue by veleek** [JamesNK/Newtonsoft.Json#979]
We have a JSON contract that contains a GUID parameter.  This parameter value is required, and must be none empty GUID.

We can use DisallowNulls to cause a deserialization failure when null is provided, but we still need to have manual checks for `!= Guid.Empty` everywhere in order to make sure invalid requests don't get through.  

The same applies for other simple types such as int, or enum where non-null isn't enough to indicate validity.  

Is there a reason that DisallowDefault doesn't exist?  Is there an easier workaround than manally checking?

**Comment by JamesNK** [comment]
You couldn't have DisallowNull and DisallowDefault at the same time. The default value for Guid? is null.

**Comment by veleek** [comment]
Using a `Guid?` still just prevents the user from passing in null.  They can still pass in `Guid.Empty`.  

For many scenarios, DisallowDefault should not conflict with DisallowNull.  It's only if you're using `DefaultValue` attributes that you might want to to be explicit about it.   If this is something that many people end up requiring you could have DisallowNull, DisallowDefault, DisallowNullAndDefault.

**Comment by JamesNK** [comment]
My point is DisallowDefault on Guid? would just prevent null. Guid.Empty is not the default value of Guid?

I'm happy with the current functionality. Additional validation can be done either in the property or using serialization events.
