### ISSUE TITLE
Fix "Bad JSON escape sequence: \x"

### ISSUE THREAD

**Issue by finesay** [JamesNK/Newtonsoft.Json#980]
`Newtonsoft.Json.Linq.JObject.Parse(@"{'title':'1\x2B1\x3D2\x3F'}")`

> Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \x. Path 'title', line 1, position 13.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)

**Comment by JamesNK** [comment]
That's not valid JSON.

**Comment by finesay** [comment]
Well, I have to call the method "DecodeJSString" first before "JObject.Parse". 
I copied the code from Fiddler's TextWizard. @JamesNK 
`
        public static string DecodeJSString(string s)
        {
            StringBuilder builder;
            char ch, ch2;
            int num, num2, num3, num4, num5, num6, num7, num8;
            if (string.IsNullOrEmpty(s) || !s.Contains(@"\"))
            {
                return s;
            }
            builder = new StringBuilder();
            num = s.Length;
            num2 = 0;
            while (num2 < num)
            {
                ch = s[num2];
                if (ch != 0x5c)
                {
                    builder.Append(ch);
                }
                else if (num2 < (num - 5) && s[num2 + 1] == 0x75)
                {
                    num3 = HexToInt(s[num2 + 2]);
                    num4 = HexToInt(s[num2 + 3]);
                    num5 = HexToInt(s[num2 + 4]);
                    num6 = HexToInt(s[num2 + 5]);
                    if (num3 < 0 || num4 < 0 | num5 < 0 || num6 < 0)
                    {
                        builder.Append(ch);
                    }
                    else
                    {
                        ch = (char)((((num3 << 12) | (num4 << 8)) | (num5 << 4)) | num6);
                        num2 += 5;
                        builder.Append(ch);
                    }
                }
                else if (num2 < (num - 3) && s[num2 + 1] == 0x78)
                {
                    num7 = HexToInt(s[num2 + 2]);
                    num8 = HexToInt(s[num2 + 3]);
                    if (num7 < 0 || num8 < 0)
                    {
                        builder.Append(ch);
                    }
                    else
                    {
                        ch = (char)((num7 << 4) | num8);
                        num2 += 3;
                        builder.Append(ch);
                    }
                }
                else
                {
                    if (num2 < (num - 1))
                    {
                        ch2 = s[num2 + 1];
                        if (ch2 == 0x5c)
                        {
                            builder.Append(@"\");
                            num2 += 1;
                        }
                        else if (ch2 == 110)
                        {
                            builder.Append("\n");
                            num2 += 1;
                        }
                        else if (ch2 == 0x74)
                        {
                            builder.Append("\t");
                            num2 += 1;
                        }
                    }
                    builder.Append(ch);
                }
                num2 += 1;
            }
            return builder.ToString();
        }

        public static string EncodeJSString(string sInput)
        {
            StringBuilder builder;
            string str;
            char ch;
            int num;
            builder = new StringBuilder(sInput);
            builder.Replace(@"\", @"\\");
            builder.Replace("\r", @"\r");
            builder.Replace("\n", @"\n");
            builder.Replace("\"", "\\\"");
            str = builder.ToString();
            builder = new StringBuilder();
            num = 0;
            while (num < str.Length)
            {
                ch = str[num];
                if (0x7f >= ch)
                {
                    builder.Append(ch);
                }
                else
                {
                    builder.AppendFormat(@"\u{0:X4}", (int)ch);
                }
                num += 1;
            }
            return builder.ToString();
        }

        public static int HexToInt(char h)
        {
            if (h < 0x30 || h > 0x39)
            {
                if (h < 0x61 || h > 0x66)
                {
                    if (h < 0x41 || h > 0x46)
                    {
                        return -1;
                    }
                    return ((h - 0x41) + 10);
                }
                return ((h - 0x61) + 10);
            }
            return (h - 0x30);
        }`

**Comment by darkguy2008** [comment]
Actually what @finesay did was the solution for me. "Not valid JSON" is not very helpful, this is. Too bad I have to apply the patch in my code instead... but hey, at least someone shared it. Infinite thanks @finesay :)

**Comment by AncientTree** [comment]
> That's not valid JSON.
It is a fact but not good answer. thanks sir. @finesay
