### ISSUE TITLE
Unable to deserialize from json to object

### ISSUE THREAD

**Issue by ruchika1** [JamesNK/Newtonsoft.Json#981]
Hello - 
I am facing an issue with deserialization of an object using newtonsoft. My test app code is pasted below -
RemoteExecutionContext source = new RemoteExecutionContext();
source.InputParameters.Add("test", new EntityReference("test"));
            source.OutputParameters.Add("tareget", new Entity("test"));
            string jsonString = JsonConvert.SerializeObject(source);

            var target = (RemoteExecutionContext) JsonConvert.DeserializeObject(jsonString); // exception Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Microsoft.Xrm.Sdk.RemoteExecutionContext'.
            var target1 = JsonConvert.DeserializeObject(jsonString); // no exception
            var target2 = JsonConvert.DeserializeObject<RemoteExecutionContext>(jsonString); // no exception but input and output parameters are empty collections

RemoteExecutionContext is a type defined in the dynamics CRM SDK and contains collections of input and output parameters.
Does anyone know if there is a way to make the deserialization work in this scenario?
Thanks

**Comment by ruchika1** [comment]
Sample code to show the above failure can be found here -
https://github.com/ruchika1/DeserializationTest/

**Comment by JamesNK** [comment]
You can ask this question on stackoverflow
