### ISSUE TITLE
Can delete old KVM tools from Tools folder

### ISSUE THREAD

**Issue by Eilon** [JamesNK/Newtonsoft.Json#984]
The ones here: https://github.com/JamesNK/Newtonsoft.Json/tree/master/Tools/Kvm

These haven't been needed for probably 1.5 years now 😄

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/d26b66f4b40e2264eaa71a6b14e33b44f718cba9

**Comment by Eilon** [comment]
Nice, thanks!
