### ISSUE TITLE
Publish breaking changes

### ISSUE THREAD

**Issue by jorgebay** [JamesNK/Newtonsoft.Json#985]
I'm looking for a place (changelog) where I could find a list of breaking changes between versions of the JSON.NET, in order to add support from the libraries we maintain to JSON.NET version ranges without having to test them all.

Is JSON.NET following semver?

**Comment by JamesNK** [comment]
Anything that I consider a change is listed under changes here - https://github.com/JamesNK/Newtonsoft.Json/releases

**Comment by qub1n** [comment]
Hi Jason,
the link you provided contains changes, not specifically breaking changes.

I am i interested in breaking changes as well. Especially I would like to answer question, can I update safely to the new one?

**Comment by gdbjohnson** [comment]
Bueller?  Bueller?  I'm also looking for this.

There is also this...
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0
