### ISSUE TITLE
Reference to type 'System.*' could not be found

### ISSUE THREAD

**Issue by b8ne** [JamesNK/Newtonsoft.Json#986]
Im currently using Newtonsoft.Json in a Xamarin.Forms project, so not entirely sure if this is a forms issue or a Newtonsoft issue, hoping someone can help me out either way.
Im simply trying to use a JObject object, and on compilation getting these errors.

`Error CS7069: Reference to type System.ComponentModel.ICustomTypeDescriptor' claims it is defined assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found (CS7069)`

`Error CS7069: Reference to type 'System.ComponentModel.INotifyPropertyChanging' claims it is defined assembly'System,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089', but it could not be found (CS7069)`

`Error CS7069: Reference to type 'System.ComponentModel.ITypedList' claims it is defined assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found (CS7069)`

`Error CS7069: Reference to type 'System.ComponentModel.IBindingList' claims it is defined assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found (CS7069)`

`Error CS7069: Reference to type 'System.ICloneable' claims it is defined assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found (CS7069)`

Im getting this even on JObject initializtion so I dont think usage is an issue.
Has anyone dealt with this before or know of the cause?
Cheers.

**Comment by b8ne** [comment]
Found to be a version issue, please delete

**Comment by imcheney** [comment]
I run int the same problem like this post, and I solved it by switch the Newtonsoft.Json.dll to the "Bin\net20\Newtonsoft.Json.dll"  one.

I don't actually know exact reason. Somehow version of this dll is important for its compatibility.
