### ISSUE TITLE
SerializeXmlNode converts \n (or whitespace) to empty text string

### ISSUE THREAD

**Issue by otomer** [JamesNK/Newtonsoft.Json#988]
**First many thanks for this great library!!**

I recently upgraded my .NET's library to  Newtonsoft.Json v9.0.0 and seen a certain behavior that seems like wrong/bug or maybe intended (though i would like to know if it is).
My main use case is converting XML document to JSON while certain type of characters is emitted and converted wrongly to empty string.

```
XmlDocument doc = new XmlDocument();
doc.LoadXml(xml); //xml = "<TEXT>\n</TEXT>" or "<TEXT> </TEXT" (first is new line, second is a whitespace)
string json = Newtonsoft.Json.JsonConvert.SerializeXmlNode(doc);
```

Issue is: when passing an xml node with \n (or \r \something etc...), or even a white-space inside the TEXT node, the SerializeXmlNode method transforms this to a json output **{ TEXT: "" }**, meaning, empty string instead of my original value. that seems akward.

Thanks in advance for any help/comment

**Comment by JamesNK** [comment]
This isn't caused by Json.NET. By default XmlReader in .NET ignores whitespace.
