### ISSUE TITLE
Ability to dynamically determine what properties to include in serialization

### ISSUE THREAD

**Issue by Olorin92** [JamesNK/Newtonsoft.Json#989]
Hi there,

As the title says, is there a built in way to dynamically determine which properties should be included as part of the serialization process (including nested objects as properties which also need to be customized)? I looked at the DefaultContractResolver class but this seems to only work at a root level, and as I need to be able to specify what properties to include for child properties (which can also be other objects), this solution didn't work for me.

For now I've made a change to the source, adding an optional parameter to the SerializeObject method that takes a JsonField object. This object is basically a representation of the object you're serializing, with the property names you want serialized included. If the serializer doesn't find a specified property in this list at any level, it just doesn't serialize it.

I haven't put this in as a pull request as I'm not sure this is in line with what Json.Net is meant to achieve. At any rate, is there another existing way to do this, or is my implementation the only way? If the latter, does my implentation sound feasible (and should I submit a pull request for review)?

Thanks,

Alex

**Comment by JamesNK** [comment]
You can ask this on stackoverflow

**Comment by Olorin92** [comment]
Hi again,

Sorry for the extremely late reply, I've only just seen this reply. I have looked on StackOverflow, but I'm fairly confident what I'm asking for hasn't been implemented.

Currently we are using the source for Newtonsoft.Json with our changes included to achieve what we want to do. This allows us to pass in a string with a predefined format to indicate what properties should be serialized, and ensures only those properties are touched, the rest are ignored.

This has been achieved by adding a nullable parameter to the Serialize method of object type JsonField (this is a custom class we created, the name probably isn't great however). This JsonField object is then used to decide which properties should be serialized, including children lists, and properties as part of a list class.

Again, this works fine for our purposes, but I haven't tested it through all scenarios. Is this something I should commit for a review? Or is there actually some built in way of doing this already (which hasn't popped up on the 100s of threads I've looked through)?

Cheers,

Alex

**Comment by Olorin92** [comment]
Mind you, half our problem is the fact we have lots of lazy loaded properties, so without being able to override what Json.NET serializes on the first serialization, any option is basically null and void, because all those properties will be fetched when they might not be needed.
