### ISSUE TITLE
$type not included for the root object when TypeNameHandling is Auto

### ISSUE THREAD

**Issue by urig** [JamesNK/Newtonsoft.Json#990]
When I set Json.NET to serialize with TypeNameHandling set to `TypeNameHandling.Auto`, it correctly sets `$type` for child properties of an object but does not do so for the root object being serialized. Why?

Please consider the following repro:
  
    public class Animal
    {
        public Animal[] Offspring { get; set; }
    }

    public class Dog : Animal {}

    Animal fido = new Dog
    {
        Offspring = new Animal[] { new Dog() }
    };
    
    var json = JsonConvert.SerializeObject(fido, 
        new JsonSerializerSettings
        {
            TypeNameHandling = TypeNameHandling.Auto
        });

The Json emitted into the `json` variable is:

    {
        "Offspring": [{
            "$type": "MyApp.Dog, MyApp",
            "Offspring": null
        }]
    }

The Json.NET [Documentation](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm) says that for `TypeNameHandling.Auto` the behavior is:

> Include the .NET type name when the type of the object being serialized is not the same as its declared type. 

Should fido not have `"$type": "MyApp.Dog, MyApp",` like its puppy? :)

**Comment by TylerBrinkley** [comment]
This is due to Json.NET not using a generic SerializeObject method thus the object your serializing is passed in as an object. You can however specify a type argument for the root type in one of the SerializeObject overloads which will achieve what you want.

**Comment by JamesNK** [comment]
Yup

**Comment by urig** [comment]
Thanks. Would it make sense for me to try and submit a PR to make the behavior consistent with the documentation?

Alternatively, might the documentation be amended to specify this behavior more clearly?

**Comment by JamesNK** [comment]
I'm happy with the current behavior, I'd prefer to change the documentation to make it clearer how it works. Where is the documentation inconsistent?

**Comment by urig** [comment]
Hi. I first have to say, thank you for Json.Net. It is *awesome*.

In the [documentation for "TypeNameHandling Enumeration"](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm), the description for "Auto" says:
> Include the .NET type name when the type of the object being serialized is not the same as its declared type. 

In my example the object being serialized (`fido`, a `Dog`) is indeed not the same as its declared type (`Animal`) so my expectation is that the .NET type name would be included but it isn't.

Perhaps another sentence can be added saying "with the exception of the root object"?

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/f1587f073dcb06934738815429eb7d50fe80f50c

**Comment by urig** [comment]
Thanks. Much appreciated :)
