### ISSUE TITLE
Can't deserialize `Guid`

### ISSUE THREAD

**Issue by btecu** [JamesNK/Newtonsoft.Json#991]
`JsonConvert.DeserializeObject<Guid>(Guid.NewGuid().ToString())` doesn't work.

It seems that the other primitives work: http://www.newtonsoft.com/json/help/html/serializationguide.htm#JsonConverter

```
JsonConvert.DeserializeObject<int>("55")
JsonConvert.DeserializeObject<bool>("1")
```

**Comment by ekevoo** [comment]
A bare Guid is not valid Json. You have to enclose it in double quotes (i.e. a string).

**Comment by btecu** [comment]
That seems confusing, but it works.
I'd expect `JsonConvert.DeserializeObject<Guid>("'167744c5-759b-4f1c-ad87-20a28d1166b8'")` to work. Otherwise, what's the point in specifying the type?

**Comment by ekevoo** [comment]
Whether you specify the type or not, this is a Json library and you must provide valid Json for it to work. If it were to try to understand invalid Json, the scope (thus size, complexity, bugs) would increase exponentially.
