### ISSUE TITLE
JsonSchema4 cannot load Azure ARM template schema.

### ISSUE THREAD

**Issue by windoze** [JamesNK/Newtonsoft.Json#996]
`var schema = JsonSchema4.FromUrl("https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json");`

This statement hung for hours and memory usage kept increasing, not sure what happened.

**Comment by JamesNK** [comment]
I didn't write JsonSchema4. My schema library is https://github.com/JamesNK/Newtonsoft.Json.Schema

**Comment by windoze** [comment]
Oops, sorry I've post it to the wrong place.
