### ISSUE TITLE
DeserializeXNode in .net core

### ISSUE THREAD

**Issue by wojtpl2** [JamesNK/Newtonsoft.Json#997]
In attachment is console project with very simple code using "Newtonsoft.Json": "9.0.1":
```cs
string json = @"{
    ""CreatedDate"": ""2014-01-23T00:00:00""
}";
var dxml = JsonConvert.DeserializeXNode(json, "root");
Console.WriteLine("CreatedDate: " + dxml.Root.Element("CreatedDate").Value);
Console.WriteLine(dxml.ToString());
```

If you run this application on .net net452 you see output:
```xml
CreatedDate: 2014-01-23T00:00:00
<root>
  <CreatedDate>2014-01-23T00:00:00</CreatedDate>
</root>
```

If you run this application as .netCoreApp you see:
```xml
CreatedDate: 2014-01-23T00:00:00+01:00
<root>
  <CreatedDate>2014-01-23T00:00:00+01:00</CreatedDate>
</root>
```

Function DeserializeXNode add time zone to datetime in in .net core.

I check that any test from XmlNodeConverterTest.cs not run for .net core. Function DeserializeXNode don't have test on this platform.

[DeserializeXNode.zip](https://github.com/JamesNK/Newtonsoft.Json/files/438797/DeserializeXNode.zip)

**Comment by pieceofsummer** [comment]
This is because overload `XmlConvert.ToString(DateTime, XsdDateTimeFlags)` is not avaliable for `netstandard1.0`, and it ends up with implicit conversion of `DateTime` to `DateTimeOffset` (which doesn't support `DateTimeKind.Unspecified` and assumes local time zone instead). 

See https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/XmlNodeConverter.cs#L1677.

Since date format in XML is fixed and culture-invariant, I'd suggest to replace `XmlConvert` with custom formatter for `DateTime` values.

**Comment by wojtpl2** [comment]
You should read datetime like this:
return XmlConvert.ToString((DateTime)value, XmlDateTimeSerializationMode.RoundtripKind); 

see .net core (corefx) source
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Xml.XmlSerializer/src/System/Xml/Serialization/XmlCustomFormatter.cs#L202 

or see ExtendedXmlSerializer
https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/PrimitiveValueTools.cs#L61

**Comment by pieceofsummer** [comment]
I meant it when I said it is not supported by `netstandard1.0`. Particularly, it is not supported in `XmlConvert` from Profile259 subset. As @JamesNK stated many times, he doesn't plan to move from `netstandard1.0`, that's why I suggested using a custom serializer.

**Comment by wojtpl2** [comment]
OK. sorry. I understand now. 
Maybe you should add another build for netstandard1.6? (I tell about add "netstandard1.6": {} in project.json)

Or use d.ToString("s") - it generate string always with format ISO 8601 ("yyyy'-'MM'-'dd'T'HH':'mm':'ss".)
https://msdn.microsoft.com/en-us/library/az4se3k1.aspx#Sortable
I checked this option - all project built.

If you don't agree with me please tell me how to create custom serializer for datetime.

Thank you.

**Comment by pieceofsummer** [comment]
I'm not a maintainer of the library, so it's not my call to do so. 

But you're certainly welcomed to file a pull request :)

**Comment by JamesNK** [comment]
If something required in netstandard1.0 is missing and it is simple to do then the best approach would be to add an internal implementation.

**Comment by wojtpl2** [comment]
I created the pull request [1015](https://github.com/JamesNK/Newtonsoft.Json/pull/1015).

**Comment by JamesNK** [comment]
Thanks. Fixed!
