### ISSUE TITLE
SelectToken with JSONPath fails with unexpected character $

### ISSUE THREAD

**Issue by saiphcbk** [JamesNK/Newtonsoft.Json#998]
I'm trying to test for the value of a property which is not in an array but i'm getting an error:
Unexpected character while parsing path query: $
here's my fiddle: [https://dotnetfiddle.net/QpkilW](https://dotnetfiddle.net/QpkilW)

my JSONPath filter expression is $.[?($.store.bicycle.price < 20)]
This expression works in the javascript and jayway's java implementation of JSONPath (Goessner 0.8)
[http://jsonpath.herokuapp.com/?path=$.[?($.store.bicycle.price%20%3C%2020)]](http://jsonpath.herokuapp.com/?path=$.[?($.store.bicycle.price%20%3C%2020)])

Can we not use the root object as part of the filter expression?

```
var json = @"
			{ ""store"": 
			  {
				""book"": [ 
				  { ""category"": ""reference"",
					""author"": ""Nigel Rees"",
					""title"": ""Sayings of the Century"",
					""price"": 8.95
				  },
				  { ""category"": ""fiction"",
					""author"": ""Evelyn Waugh"",
					""title"": ""Sword of Honour"",
					""price"": 12.99
				  },
				  { ""category"": ""fiction"",
					""author"": ""Herman Melville"",
					""title"": ""Moby Dick"",
					""isbn"": ""0-553-21311-3"",
					""price"": 8.99
				  },
				  { ""category"": ""fiction"",
					""author"": ""J. R. R. Tolkien"",
					""title"": ""The Lord of the Rings"",
					""isbn"": ""0-395-19395-8"",
					""price"": 22.99
				  }
				],
				""bicycle"": {
				  ""color"": ""red"",
				  ""price"": 19.95
				}
			  },
			  ""expensive"": 10
			}";
		var jobj = JObject.Parse(json);

		var coursesTokens = jobj.SelectTokens("$.[?($.store.bicycle.price < 20)]");
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/ac2d61947428a34eb6e48d26bfd22f7141c757ce

**Comment by IlyaDeskov** [comment]
Hello.
I've got the same error with '?' character:
code:
....
from jsonpath_ng import jsonpath, parse
....
json_label_synchronize = parse("labels[?(@.name == 'Sync')].id")
....
and part of the stacktrace:
   File "/app/app.py", line 19, in <module>
     json_label_synchronize = parse("labels[?(@.name == 'Sync')].id")
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 14, in parse
     return JsonPathParser().parse(string)
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 32, in parse
     return self.parse_token_stream(lexer.tokenize(string))
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 55, in parse_token_stream
     return new_parser.parse(lexer =
 IteratorToTokenStream(token_iterator))
   File "/app/.heroku/python/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
     return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
   File "/app/.heroku/python/lib/python3.6/site-packages/ply/yacc.py", line 1061, in parseopt_notrack
     lookahead = get_token()     # Get the next token
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 179, in token
     return next(self.iterator)
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/lexer.py", line 35, in tokenize
     t = new_lexer.token()
   File "/app/.heroku/python/lib/python3.6/site-packages/ply/lex.py", line 386, in token
     newtok = self.lexerrorf(tok)
   File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/lexer.py", line 167, in t_error
     raise JsonPathLexerError('Error
 on line %s, col %s: Unexpected character: %s ' % (t.lexer.lineno, t.lexpos - t.lexer.latest_newline, t.value[0]))
 jsonpath_ng.lexer.JsonPathLexerError: Error on line 1, col 7: Unexpected character: ?

**Comment by Jose-Bastos** [comment]
> Hello.
> I've got the same error with '?' character:
> code:
> ....
> from jsonpath_ng import jsonpath, parse
> ....
> json_label_synchronize = parse("labels[?(@.name == 'Sync')].id")
> ....
> and part of the stacktrace:
> File "/app/app.py", line 19, in
> json_label_synchronize = parse("labels[?(@.name == 'Sync')].id")
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 14, in parse
> return JsonPathParser().parse(string)
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 32, in parse
> return self.parse_token_stream(lexer.tokenize(string))
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 55, in parse_token_stream
> return new_parser.parse(lexer =
> IteratorToTokenStream(token_iterator))
> File "/app/.heroku/python/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
> return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
> File "/app/.heroku/python/lib/python3.6/site-packages/ply/yacc.py", line 1061, in parseopt_notrack
> lookahead = get_token() # Get the next token
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/parser.py", line 179, in token
> return next(self.iterator)
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/lexer.py", line 35, in tokenize
> t = new_lexer.token()
> File "/app/.heroku/python/lib/python3.6/site-packages/ply/lex.py", line 386, in token
> newtok = self.lexerrorf(tok)
> File "/app/.heroku/python/lib/python3.6/site-packages/jsonpath_ng/lexer.py", line 167, in t_error
> raise JsonPathLexerError('Error
> on line %s, col %s: Unexpected character: %s ' % (t.lexer.lineno, t.lexpos - t.lexer.latest_newline, t.value[0]))
> jsonpath_ng.lexer.JsonPathLexerError: Error on line 1, col 7: Unexpected character: ?

Did you find the answer?
